[1단계 - 자동차 경주 구현] 완태(김태완) 미션 제출합니다.
woowacourse/java-racingcar pull request #166
Opened 2021-02-06 06:12 UTC by wannte

첫번째 풀리퀘스트 제출입니다! 아직 많이 부족하지만, 피드백 주시면 적극 반영하겠습니다.

이번 과정에서 집중해서 봤던 요소들을 정리해보겠습니다.

1. TDD
테스트를 먼저 만들고, 테스트를 하기 좋은 방식으로 코드를 구현해 나가고자 노력하였습니다. 도메인 로직에서의 TDD는 비교적 쉽게 구현이 되었지만, 여러가지 도메인이 겹치게 되었을 때, 이를 테스트를 먼저 만들고 진행해 나가기가 쉽지 않았습니다.

예를 들어 게임이라는 객체를 만들었을 때, 정상적으로 게임 객체가 잘 만들었는지 테스트할 방법입니다. 단순히 게임의 구성원들의 이름을 비교하는 것이 테스트 검증일까? 라는 의문이 들었습니다.

짝과 많이 이야기한 부분인데, String name을 가지는, A라는 객체에 대한 테스트를 통해 A에는 null의 요소가 name에 들어가지 않는다는 테스트를 진행했을 때, A객체의 리스트로 구성된  B객체의 테스트에는 {"이름1","이름2",null}이란 테스트를 진행하는 것은 불필요한 테스트일까요?
제가 생각하기로는 각 클래스별로의 테스트를 별개로 두어 각 클래스의 안정성을 보장하는 것이 좋은 방법으로 생각이되어집니다. 이렇게 하게 되면, 매번 테스트에서 null과 같은 요소를 체크해야하는 불상사가 있다고도 생각은 합니다.

2. 객체를 생성할 때의 유효성 검증
처음 차 객체를 생성로직을 구현했을 때, 저의 개인적인 욕심으로, 생성자 안에서 다른 (static이 아닌) 메소드를 호출하는 것에 불편함을 느꼈습니다. 아직 생성되지도 않은 객체의 메소드를 생성하는 과정에서 사용하다니? 라는 생각이었습니다.

그렇게 해서 만들었던 클래스가 CarFactory였고, validation을 CarFactory에서 진행하고, Car는 CarFactory를 통해서만 만들 수 있도록 정의하고 싶었습니다. CarFactory말고 다른 클래스에서 Car객체를 생성하지 못하도록 하는 방법이 있을 것으로 예상되지만(패키지를 구분한다? 정도), 지금 당장은 수업시간에 다루었던 정적 팩토리 메소드를 이용해보고자 로직을 수정하였습니다.

정적 팩토리 메소드를 이용함으로써, validation로직을 static method로 뺌으로써, Car객체의 생성을 효율적이고, 안전하게 만들 수 있었다고 생각합니다.

적다보니 글이 조금 길어졌습니다! 잘 부탁드립니다 :)

2021-02-07 02:33 UTC, wbluke requested changes
안녕하세요 완태! 첫 번째 미션 리뷰를 맡은 닉입니다 🙇 
1단계부터 깔끔하게 잘 구현해주셨네요!
질문에 대한 답변 포함하여 몇 가지 코멘트 남겼으니, 확인 후 재요청 부탁드려요 🙂

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/domain/Car.java
> +    public static Car generateCar(String name) {
질문 주신 부분 여기에 답변 남길게요 ㅎㅎ

> 짝과 많이 이야기한 부분인데, String name을 가지는, A라는 객체에 대한 테스트를 통해 A에는 null의 요소가 name에 들어가지 않는다는 테스트를 진행했을 때, A객체의 리스트로 구성된 B객체의 테스트에는 {"이름1","이름2",null}이란 테스트를 진행하는 것은 불필요한 테스트일까요?
제가 생각하기로는 각 클래스별로의 테스트를 별개로 두어 각 클래스의 안정성을 보장하는 것이 좋은 방법으로 생각이되어집니다. 이렇게 하게 되면, 매번 테스트에서 null과 같은 요소를 체크해야하는 불상사가 있다고도 생각은 합니다.

넵 좋은 생각입니다! 제 생각은 결이 약간 달라서 말씀드려보면요.
`A객체의 리스트로 구성된 B객체의 테스트`에서는 말씀해주신 케이스, 즉 다수의 A와 null이 포함된 리스트에 대한 테스트를 할 필요는 없다고 생각합니다.
`단위 테스트`라는건 각 객체의 안정성을 보장해주는 것이기에, 이를 조합의 형태로 엮었을 때 굳이 다른 객체에서 `A의 생성`이라는 기능을 다시 한번 테스트를 할 필요는 없다고 생각해요. (나중에 경험하실 `통합 테스트`와는 또 다른 맥락입니다)
도메인이 복잡해지고 양파껍질(?)이 쌓여갈 수록 상대적으로 외부에 있는 객체들은 내부의 감싸고 있는 객체들을 다 테스트해야하니 테스트 범위가 기하급수적으로 늘어날 것 같아요 ㅎㅎ
다만 위 경우에 리스트 전체가 null로 들어온다던지에 대한 케이스는 `A의 생성`이 아닌 B 자체에 대한 문제이기 때문에, 상황에 따라 잘 판단해서 결정하면 될 것 같아요 :)

> 객체를 생성할 때의 유효성 검증
처음 차 객체를 생성로직을 구현했을 때, 저의 개인적인 욕심으로, 생성자 안에서 다른 (static이 아닌) 메소드를 호출하는 것에 불편함을 느꼈습니다. 아직 생성되지도 않은 객체의 메소드를 생성하는 과정에서 사용하다니? 라는 생각이었습니다.
그렇게 해서 만들었던 클래스가 CarFactory였고, validation을 CarFactory에서 진행하고, Car는 CarFactory를 통해서만 만들 수 있도록 정의하고 싶었습니다. CarFactory말고 다른 클래스에서 Car객체를 생성하지 못하도록 하는 방법이 있을 것으로 예상되지만(패키지를 구분한다? 정도), 지금 당장은 수업시간에 다루었던 정적 팩토리 메소드를 이용해보고자 로직을 수정하였습니다.

넵 정확하십니다. Factory를 사용하는 이유는 특정 객체가 어떤 특별한 방법, 일관된 방법으로만 생성되기를 원하기 때문인데요.
Factory 사용 시에도 Factory를 통해서만 인스턴스를 생성할 수 있도록 패키지 접근제어를 활용하시는게 맞습니다.
다만 특별히 복잡한 로직이 아니라면, 일반 생성자(혹은 정적 팩토리 메서드)로도 충분히 validation을 진행할 수 있다고 봐요.
validation만을 위해서 Factory 구조를 만드는건 복잡도를 높일 수 있기 때문에 충분히 고려한 후에 적용해보면 좋을 것 같아요 :)

그리고 얼마든지 생성 과정에서 내부 private 메서드를 활용할 수 있다고 생각해요.
(정확히는 메서드가 먼저 생긴 것이 아니라 반대로 생성자의 로직을 메서드로 추상화한 것이겠네요)
생성자의 역할은 인스턴스가 정확히 생성되는 것도 보장해야 하기 때문에 저는 validation 로직을 생성자에 놓는 편입니다 :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/domain/Car.java
> +    private static final int CAR_NAME_LENGTH_MAX_SIZE = 4;
상수의 위치는 클래스 가장 상단입니다 :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/domain/Car.java
> +        if (name.equals("")) {
name에 null이 들어올 경우 NPE가 터지는데요 (물론 null 체크를 먼저 하고 있지만 메서드 순서가 바뀌거나 하면 문제가 생기겠네요)
두 대상의 동등성을 비교할 때에는 더 확실한 쪽을 기준으로 equals를 호출하는 것이 좋습니다 :)
```suggestion
        if ("".equals(name)) {
```

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/controller/InputController.java
> +public class InputController {
static method로만 이루어진 클래스에는 private 기본 생성자를 명시하여 방어적인 코드를 작성하는 습관을 들이면 좋습니다 :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/controller/InputController.java
> +        if (!Pattern.matches("^[1-9]+[0-9]*$", input)) {
문자열 계산기 쪽에 남긴 코멘트 참고해주세요 :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/controller/InputController.java
> +        names = Arrays.asList(input.split(","));
중요한 문자열도 상수로 관리하면 좋을 것 같아요 :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/controller/GameController.java
> +                   .filter(car -> car.getPosition() == maxPosition)
Car에 메시지를 던져서 해결해볼 수 있을까요? :)

2021-02-07 02:33 UTC, wbluke commented on src/main/java/javaracingcar/controller/GameController.java
> +    public static List<Car> getWinners(Game game) {
- 이 메서드를 비롯한 대부분의 로직을 GameController가 아닌 Game에서 책임을 가져갈 수 있을 것 같아요. (Game 내부에 있는 Cars를 꺼내서 작업을 하고 있네요)
- Game의 네이밍이 좀 더 구체적이면 좋을 것 같네요 :)

2021-02-07 13:43 UTC, wannte commented on src/main/java/javaracingcar/controller/GameController.java
> +    public static List<Car> getWinners(Game game) {
안녕하세요! 다양한 관점에서의 피드백 정말 감사합니다!

구현하는 데 있어서, 또 하나가 MVC패턴에서 Controller와 Model의 역할을 어떻게 분담을 해야할 것인가였습니다!
최종적으로 저희가 협의하여 구현하고자 했던 방식은, 모델의 경우 최대한 수동적인 객체로 두고, 그와 관련된 연산이나 작업들은 컨트롤러에서 진행을 한다 라는 관점에서 프로그램을 구현하였는데요!

피드백 주신 부분에 따르면, 이러한 관점보다는 컨트롤러는 게임이 어떠한 로직을 수행하는지 제어?하는 정도의 역할을 맡는 것일까요? 

MVC패턴에 대한 이해가 부족한 상태라 이를 구분하는 기준에 대해 부연 설명 부탁드려도 될까요? 아니면, 참고할 만한 자료가 있으면 알려주시면 정말 감사하겠습니다!

2021-02-08 11:53 UTC, wbluke approved these changes
피드백 반영 감사합니다 👍 
질문에 대한 답변 남겼으니 참고해주시고, 다음 단계 진행해주세요! 🙂

2021-02-08 11:53 UTC, wbluke commented on src/main/java/javaracingcar/controller/GameController.java
> +
질문에 대한 답변 여기에 남길게요!

> 구현하는 데 있어서, 또 하나가 MVC패턴에서 Controller와 Model의 역할을 어떻게 분담을 해야할 것인가였습니다!
최종적으로 저희가 협의하여 구현하고자 했던 방식은, 모델의 경우 최대한 수동적인 객체로 두고, 그와 관련된 연산이나 작업들은 컨트롤러에서 진행을 한다 라는 관점에서 프로그램을 구현하였는데요!
> 
> 피드백 주신 부분에 따르면, 이러한 관점보다는 컨트롤러는 게임이 어떠한 로직을 수행하는지 제어?하는 정도의 역할을 맡는 것일까요?
> 
> MVC패턴에 대한 이해가 부족한 상태라 이를 구분하는 기준에 대해 부연 설명 부탁드려도 될까요? 아니면, 참고할 만한 자료가 있으면 알려주시면 정말 감사하겠습니다!

넵 말씀하신 내용이 맞습니다 ㅎㅎ
컨트롤러에서 역할을 가져가게 되면 모델이 하는 일이 거의 없게 되고, 애플리케이션이 커질수록 컨트롤러만 엄청 거대한, 하나의 슈퍼 클래스가 될 것 같아요.
오히려 모델 쪽에서 각 역할에 맞게 책임을 분배해서 가져가면, 단위 테스트도 훨씬 쉽고 명확하게 할 수 있을거구요. 
컨트롤러는 View와 Model을 연결하는 제어의 역할만 가지고 있으면 충분합니다 :)
이런 고민들은 이번 미션 말고도 앞으로의 미션들에서 피부로 느껴볼 기회가 많을거에요 ㅎㅎ

2021-02-08 11:53 UTC, merged