[1단계 - 자동차 경주 구현] 피케이(박유진) 미션 제출합니다.
woowacourse/java-racingcar pull request #167
Opened 2021-02-06 06:46 UTC by pkeugine

**👋 지노 안녕하세요! 피케이입니다.**

주말 잘 보내시고 계신가요? 저는 정말 즐거운 하루하루를 보내고 있답니다!
처음으로 페어 프로그래밍을 해봐서 아직 부족하지만 잘 부탁드려요. 🙏

아, 제가 이번 미션을 진행하면서 궁금했던 점이 두 개 있었는데요!
풀리퀘스트와 함께 여기 작성해보도록 할게요.

## TDD를 할 때 아주 간단한 메서드도 테스트 케이스를 작성한다?

예를 들어, 그냥 문자열을 출력하는 System.out.println() 하나 들어가 있는 메서드 말이죠. 🤔
아무래도 테스트 케이스를 작성하는게 이번 생에 처음이다보니... 저와 제 페어가 이번 미션에서는 나름의 기준을 정해봤어요.

### "이 경우에 해당하는 메서드만 테스트 케이스를 작성하자"
1. 메서드가 반환하는 무언가가 있다 (void 가 아니다)
2. 너무 당연한 값을 리턴하지 않는다 (제 코드의 경우 Car 객체의 getPosition() 과 같은 메서드는 테스트 케이스가 없습니다. 너무나도... 당연하니까요)

## 테스트를 위해 메서드를 웬만하면 public 으로 두는 것이 좋다?

저는 거의 모든 메서드를 private 으로 두고, 다른 클래스가 사용하는 경우에만 public 으로 두는 편입니다.
그런데 그렇게 하니 테스트 케이스 작성할 때 private 메서드를 불러오지 못했어요.
IntelliJ 에서 추천하던 해결책이 private 도 public 도 아닌 **protected 를 사용하는 방법인데**,
제 짧은 프로그래밍 인생사에 비춰보면 protected 는 클래스 자기 자신과 자식 클래스가 사용할 수 있도록 하는 것이라고 알고 있습니다.
그렇다면 private 으로 두고 싶은 메서드는 어떻게 테스트를 할까요? IntelliJ 가 맞았던 걸까요? 🤨

---

제가 글 쓰는 실력이 좀 부족해서 전달이 잘 되었는지 확실하지 않네요 😅
그리고 바쁘신 와중에 리뷰 해주셔서 정말 감사합니다. 좋은 하루 보내세요!!

2021-02-06 13:42 UTC, hyunssooo requested changes
안녕하세요 피케이! 지노입니다 ☺️
빠르게 미션 잘 진행해주셨어요! 👍👍👍
몇 가지 피드백을 남겼습니다! step2 미션이 mvc 패턴으로 리팩토링이기 때문에 관련 피드백은 남기지 않았습니다 :)
피드백을 읽어보시면서 궁금하거다 다르게 생각하시는 부분이 있다면 편하게 DM주세요!

> TDD를 할 때 아주 간단한 메서드도 테스트 케이스를 작성한다?

TDD는 테스트부터 작성하는 개발 방법 입니다. 테스트 케이스를 먼저 작성한다면 간단한 메서드도 테스트 케이스는 존재하겠죠.
또한, 테스트가 가능한 부분과 테스트가 불가능한 부분에 대해서 고민하면 좋을거 같아요. System.out.println()의 경우 사실상 테스트가 불가능하지 않을까요??

> 테스트를 위해 메서드를 웬만하면 public 으로 두는 것이 좋다?

저도 다른 클래스가 사용하는 경우에만 public으로 두는 편입니다 :) 
우선 테스트를 작성하는 대상은 메서드가 아니라 객체 아닐까요?? 그렇다면 public 메서드들은 해당 객체에 메세지를 보낸다고 생각합니다. 그렇다면 그 객체에 공개된 메소드들만 테스트하면 된다고 생각합니다. private 메서드들은 구현 부분이기 때문에 외부에서는 관심이 없어야 한다고 생각하기 때문입니다. 또한, private 메소드가 존재한다면 분명 그 메서드를 사용하는 public 메소드가 존재할 거라고 생각해요. 그렇다면 간접적으로 private 메소드도 테스트 한 것 아닐까요?? :)

2021-02-06 13:49 UTC, pkeugine commented on src/main/java/racingcar/utils/ValidateUtils.java
> +    }
진짜 문화충격입니다....

2021-02-07 18:42 UTC, pkeugine commented
@hyunssooo 지노! 안녕하세요~

저번 피드백 정말 잘 읽고 많이 배웠습니다.

제가 궁금했던 점들을 정말 시원하게 알려주셨구요,
리뷰 보면서 제가 왜 저렇게 코드를 작성했는지 생각해보는 시간도 가질 수 있었어요.

Step 2로 넘어가기 전에 리뷰를 반영해봤습니다!

2021-02-07 18:49 UTC, pkeugine commented on src/main/java/calculator/StringCalculator.java
> +    }
이 부분을 다시 돌아보면서 Pattern, regex, 그리고 실행 속도에 대해서 배워볼 수 있었네요!

그런데 한 가지 궁금한게 있습니다.
Pattern.compile 에 대해서 이것 저것 알아보니 String 에서도 자주 쓰인다는 것을 알 수 있었어요.

예를 들어 String 의 split(), matches(), replaceAll() 등 메서드의 구현을 확인해보니까 다 Pattern을 그 때마다 생성해서 리턴하네요...!
그렇다면 해당 메서드를 사용하는 것도 최대한 지양해야 할까요?

2021-02-08 15:37 UTC, hyunssooo requested changes
안녕하세요 피케이! 지노입니다!
가벼운 피드백 남겼습니다! 피드백을 읽어보시면서 궁금하거다 다르게 생각하시는 부분이 있다면 편하게 DM주세요!

2021-02-08 15:37 UTC, hyunssooo commented on src/main/java/racingcar/domain/car/CarRepository.java
> +    }
repository에서 우승자를 구하는게 맞을까요??
피케이가 생각하는 repository에 대한 역할을 말씀해주시면 함께 고민하는 시간이 될거 같습니다 🙂

2021-02-08 15:37 UTC, hyunssooo commented on src/main/java/racingcar/domain/car/Car.java
> +    }
car 객체가 ValidateUtils에게 name에 대한 예외 사항을 위임하군요! 

https://woowacourse.github.io/javable/post/2020-07-16-static-method/
한 번 읽어보시면 좋을 거 같아요!

2021-02-08 15:37 UTC, hyunssooo commented on src/main/java/racingcar/domain/car/Car.java
> +    }
toString() 메서드가 View에 의존적으로 사용되는것 같아요~
toString() 은 보통 객체의 상태를 표현하기 위해 사용되어, 정해진 규칙에 의해서 재정의하는게 좋습니다.

2021-02-11 06:07 UTC, pkeugine commented
@hyunssooo 지노~ 안녕하세요! 오랜만이죠? 😅

지난번 피드백을 받고, 우테코에서 수업을 들으면서 굉장히 새로운 것들을 많이 배우느라...
피드백을 적용하는데 시간이 엄청 오래 걸렸네요! 거의 처음부터 다시 짜는 느낌이 들 정도로 대부분 수정되었어요.

아직 고칠 점이 많이 있을 것 같긴한데, 제가 지난번 피드백 요청 때와 어떤 부분을 다르게 했는지 알려드릴게요!

#### 1. CarRepository 삭제
저는 원래 CarRepository 라는 스태틱 클래스를 만들어서 거기에 Car 객체를 보관했어요. 그리고 게임이 끝나면 거기서 우승 객체들을 모아서 view로 전달했습니다. 그런데 지노가 언급했던 것처럼, '이게 객체지향이 맞나?'라는 생각이 들었어요. CarRepository가 우승 객체를 찾는 것도 뭔가 어울리지 않았고요.

그래서 Cars, WinnerCars 라는 새로운 클래스를 만들었습니다.
- Cars : Car 객체들을 담고 있고, moveIndividuals() 를 이용하여 갖고 있는 모든 Car 객체에게 움직이라고 할 수 있다
- WinnerCars : Cars 객체를 이용하여 우승 객체들을 골라 담는 객체

#### 2. 검증이 필요한 요소는 모두 클래스로 만들고, static 클래스는 적당히 사용
마지막으로 리뷰를 받았을 때는 ValidateUtils, ErrorUtils 라는 유틸 클래스를 만들어 사용했습니다.
ValidateUtils는 이름 그대로 도메인에서 검증이 필요한 상황에 사용했고 (이름 길이, 시도 횟수 크기 등)
ErrorUtils는 에러 출력을 담당하는 유틸이었어요.

이제는 검증이 필요한 것들을 객체로 만들도록 했습니다:
Name : 자동차 이름. 이름 길이 관련 검증은 모두 여기로
CarNames : 자동차 이름들을 모아두는 곳. 이름 중복 관련 검증은 모두 여기로
Round : 시도횟수. 최소 횟수 관련 검증은 모두 여기로

그리고 에러 출력은 새로 만든 OutputView 라는 클래스에서 처리하도록 했어요.

---

이렇게 객체를 많이 만들다보니 테스트 케이스도 많이 생겼네요 ㅋㅋㅋ
천천히 리뷰해주세요! 그리고 새해 복 많이 받으세요~~ :)

2021-02-11 13:58 UTC, hyunssooo approved these changes
안녕하세요 피케이! 지노입니다!
짧은 시간에 많은 것이 코드에 반영되었네요! 😃👍
step1 진행하신다고 수고 많으셨습니다!
간단한 코멘트 몇 가지 남겼습니다! 
그리고 이미 MVC의 개념을 잘 알고 계신 거 같아요 ㅎㅎ
step2 진행하시면서 제가 남긴 코멘트 고민해보시면 좋을 거 같아요! 
즐거운 명절 보내시고, 새해 복 많이 받으세요! 🙇‍♂️

2021-02-11 13:58 UTC, merged