[1단계 - 자동차 경주 구현] 욘(김영빈) 미션 제출합니다
woowacourse/java-racingcar pull request #178
Opened 2021-02-06 11:24 UTC by thisisyoungbin

게이츠 안녕하세요: ) 코드 리뷰를 위해 귀한 시간 내주셔서 감사합니다 !
프리코스 때 해봤던 미션인데도 페어프로그래밍을 통해 진행하니 새로웠네요. 어떤 피드백도 감사히 받아 반영해보겠습니다!

TDD 방식으로 코드를 짜는 것도 처음이라 익숙하지 않았으나 페어의 도움으로 잘 헤쳐나간 것 같습니다.
이번 미션에서는 프리코스 때 알게 된 MVC 패턴을 적용해 코드를 짜봤는데요. 패턴을 적용해 나가며 생긴 궁금증을 공유해봐도 될까요?

---
- TryNumber를 입력받고 유효성을 검사하는 게 InputView에서 이뤄지고 있는데요. 이 정도(?)의 유효성 판별은 view를 통해 이뤄져도 괜찮을지가 궁금합니다.
- Random 수를 생성하고 기준 값을 넘으면 자동차를 전진시키는 테스트에서 예측할 수 없는 상황 때문에 값의 범위를 통해 테스트를 진행했는데요. 적절한 방법인지는 확신이 안 섰는데... 이런 경우엔 test를 어떤 방식으로 하는게 좋은 방식인지 궁금합니다.

그 외에도 이번 미션에서 중요하게 생각했어야 할 부분들이 있으면 말씀해주시면 감사하겠습니다 !

2021-02-07 05:57 UTC, serverwizard requested changes
안녕하세요. 첫번째 미션을 함께하게 된 (빌)게이츠가 되고 싶은 게이츠입니다. ^^

첫번째 미션 정말 잘 진행해주셨어요 💯
피드백 몇 개 남겨 놓았는데, 리펙토링 진행해보시면 좋을 것 같아요.

과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 DM 혹은 코멘트 남겨주세요 😄

다음 PR도 기대하며 기다리고 있을게요 🙇

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        List<Car> carGroup = makeCarGroup(carNames);
현재 Controller에서 InputView로부터 자동차 이름을 전달 받아, 자동차 리스트를 만든 다음, 이를 RacingCarGame에 전달해주고 있는데요. 이를 RacingCarGame 내에서 진행해줄 수는 없는 걸까요?

두 개의 차이점에 대해 생각해보시고 공유해주시면 좋을 것 같아요~

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Car.java
> +        this(name, INITIAL_POSITION);
주 생성자를 이용해서 초기화 👍

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Car.java
> +    private final String name;
코드를 너무 잘 구현해주셔서 한 가지 미션을 더 드리자면 
primitive type(원시값)도 포장해보셨으면 좋겠어요!

그리고 이렇게하게되면 어떤 변화가 있는지를 공유해주시면 좋을 것 같아요!

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Cars.java
> +public class Cars {
일급 콜렉션 사용 👍
혹시 어느 부분에서 일급 콜렉션을 사용하면 좋을 것 같다란 생각이 드셨는지 공유해주시면 좋을 것 같아요~

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/racingcargame/RacingCarGame.java
> +    public List<Cars> execute(RandomNumberGenerator randomNumberGenerator) {
현재 해당 메소드는 테스트하기가 힘들 것 같은데요.
이는 내부에 테스트하기 어려운 RandomNumberGenerator을 가지고 있기 때문이에요.
이럴 땐, 테스트 하기 어려운 부분을 외부에서 주입받도록 변경해서 테스트하기 힘든 부분과 그렇지 않은 부분을 분리하면 되는데요.

사실 여기까지 접근은 굉장히 잘해주셨어요.
그런데 주입받는 대상이 무조건 RandomNumberGenerator로 고정되어 있어서 테스트하기 힘든 건 동일한 것 같아요.

만약 MovingStrategy 인터페이스를 선언하고 이를 구현한 RandomMovingStrategy(production code에서 사용)와 FixedMovingMovingStrategy(테스트에서 사용)를 만든 다음, execute메소드에서는 MovingStrategy 인터페이스로 주입받는 대상을 받도록 하면은 어떨까요?

2021-02-07 05:57 UTC, serverwizard commented on src/test/java/racingcar/domain/car/CarTest.java
> +class CarTest {
테스트 코드 깔끔 👍

2021-02-07 05:57 UTC, serverwizard commented on src/test/java/racingcar/domain/car/CarsTest.java
> +        assertThat(carsValue.get(0).getPosition()).isGreaterThanOrEqualTo(0).isLessThanOrEqualTo(1);
자동차의 위치를 값의 범위를 이용해서 검증하지 않았으면 좋겠어요!

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Cars.java
> +        return Collections.unmodifiableList(cars);
불변 객체(immutable object) 사용 👍

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Car.java
> +            return new Car(name, position + 1);
불변 객체(Immutable Object) 사용 👍 
불변 객체를 사용하시려고 생각한 이유를 공유해주시면 좋을 것 같아요~

2021-02-07 05:57 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Cars.java
> +        return maxPosition;
해당 부분을 Stream API를 사용하여 리팩토링해보면 좋을 것 같아요~
```
return this.cars.stream() 
	.mapToInt( 구현 ) 
	.max() 
	.orElse(0);
```
이것 뿐 만 아니라 Stream API를 사용할 수 있는 부분을 찾아서 모두 변경해보면 좋을 것 같아요!

2021-02-07 06:03 UTC, serverwizard commented
```
TryNumber를 입력받고 유효성을 검사하는 게 InputView에서 이뤄지고 있는데요. 이 정도(?)의 유효성 판별은 view를 통해 이뤄져도 괜찮을지가 궁금합니다.
```
코드 구현할 때를 생각해보면, View(UI)와 서버 모두 유효성 검사를 진행하듯이, 두 곳 모두에서 진행해주시면 좋을 것 같아요.
다만 현재 교육과정이 백엔드 중심 과정이다 보니 View(UI)쪽은 신경을 크게 안 쓰셔도 될 것 같아요.

```
Random 수를 생성하고 기준 값을 넘으면 자동차를 전진시키는 테스트에서 예측할 수 없는 상황 때문에 값의 범위를 통해 테스트를 진행했는데요. 적절한 방법인지는 확신이 안 섰는데... 이런 경우엔 test를 어떤 방식으로 하는게 좋은 방식인지 궁금합니다.
```
해당 부분은 코드리뷰에 남겨뒀으니 값의 범위를 통해 테스트 진행했던 부분은 변경해보시면 좋을 것 같아요!

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        List<Car> carGroup = makeCarGroup(carNames);
현재와 같은 방식을 생각하게 된 과정은 이렇습니다. RacingCarGame은 Cars와 TryNumber를 파라미터로 받아 실행한다 -> InputView에서 Cars를 만드는 로직은 작성하지 않도록 한다 -> 컨트롤러에서 Cars를 만들어 전달하는 방식을 사용한다. 

Cars를 어디서 만들어야 하는지 책임에 대한 생각을 다시 해봤는데요! 컨트롤러가 Cars를 직접 만들어 전달하는 것보단 단지 InputView를 통해 입력받은 값을 RacingCarGame에 전달하고 Cars를 만드는게 더 적절한 방식인 것 같아요. 
다만 이렇게 RacingCarGame에서 Cars를 생성하게 되면 유효하지 않은 자동차 이름들을 입력받아도 시도횟수까지 다 입력받고, RacingCarGame 인스턴스가 만들어질 때 자동차 이름에 관한 에러메시지를 출력하게 되는 의도치 않은 버그(?)가 발생해서...

1. TryNumber와 마찬가지로 InputView에서 적절한 입력인지를 검증
2. 차이름 입력 -> RacingCarGame 인스턴스 생성 -> 시도횟수 입력 -> setter 사용

이렇게 두 가지 해결방법을 생각해봤고 2번은 우테코에서 추구하는 객체지향 생활 체조 원칙에 어긋나 1번의 방식으로 해결해봤습니다.  다만 이게 InputView에서 유효성을 검증하다 보니 잘 디자인된 코드인지는 확신이 안 서네요.. 게이츠의 의견이 궁금합니다 !

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/Car.java
> +    private final String name;
CarPosition을 만들어 TryNumber처럼 원시값을 포장해봤습니다. 
원시값을 포장하면서 일급 컬렉션 같다는 생각이 들었는데요. 
원시값 포장도 마찬가지로 외부의 영향을 받지 않아 변하지 않는 값을 저장할 수 있을 것 같습니다 !

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/Cars.java
> +public class Cars {
일급 콜렉션은 페어의 아이디어로 처음 알게 돼 사용하게 됐습니다. 
자동차 이름을 배열로 바꾸고 인스턴스를 만들 때 중복되는 이름의 유효성 판별을 어떻게 해야 할지 고민하다 일급 컬렉션을 알게 됐고, 일급 컬렉션을 통해 이름을 검증하고 저장할 수 있고, 변하지 않는 자동차 객체를 담을 수 있다해 https://jojoldu.tistory.com/412 블로그를 참고해 구현해봤습니다 !

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/racingcargame/RacingCarGame.java
> +    public List<Cars> execute(RandomNumberGenerator randomNumberGenerator) {
피드백 반영해 수정해봤습니다 !

2021-02-08 10:22 UTC, thisisyoungbin commented on src/test/java/racingcar/domain/car/CarsTest.java
> +        assertThat(carsValue.get(0).getPosition()).isGreaterThanOrEqualTo(0).isLessThanOrEqualTo(1);
말씀해주신 대로 인터페이스를 선언하고 테스트와 production code에서 각각 다르게 구현해 두 개로 나눠 서 구현했습니다.

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/Car.java
> +            return new Car(name, position + 1);
이 부분은 사실 처음에 불변객체로 사용하지 않고 진행을 했었는데요. 
그러다보니 경기결과가 출력될 때 마지막 라운드의 값을 출력하는 버그가 생겼고, 이를 해결하기 위해 한 경기가 끝날 때 마다 새로운 객체를 만들어서 반환하게 했습니다. 이 부분도 페어가 낸 아이디어로 구현하게 됐습니다.

2021-02-08 10:22 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/Cars.java
> +        return maxPosition;
이 부분도 모두 리팩토링 해봤습니다 !

2021-02-08 17:15 UTC, serverwizard commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        List<Car> carGroup = makeCarGroup(carNames);
개인적으로 저도 View(프론트)에서 유효성 검사를 해줘야만 한다고 생각해요. ^^

근데, 제가 여기서 욘이 고민 해봤으면 했던 부분은 
RacingCarGame을 호출(생성)하는 쪽에서 Cars객체가 무엇인지, TryNumber객체가 무엇인지 알아야만 할까였어요~

그냥 호출(생성)하는 쪽에서는 `자동차 이름`과 `시도 횟수`만 넘겨주고 
RacingCarGame 내부에서 관련 객체를 생성하면은 안될까였어요~

욘이 걱정하는 부분인 `유효하지 않은 자동차 입력을 입력받는 경우`는 
우선 View에서 유효성 검사를 하기 때문에 미리 걸러지지 않을까요?

만약, 악의적인 사용자가 View 영역을 조작하여 View쪽 유효성 검사를 통과 시켰다면
당연히 Model(도메인) 만들어질 때라도 예외를 발생하는 게 정상적인 행위라고는 볼 수 없을까요?

2021-02-08 17:24 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Car.java
> +            return new Car(name, position + 1);
정말 좋은 경험을 하셨네요!

2021-02-08 17:33 UTC, serverwizard approved these changes
자동차 경주 구현을 정말 깔끔하게 잘 구현해주셨네요. 💯

사실 2단계 요구사항까지 한 번에 다 구현해주신 느낌이라 
다음 단계도 빠르게 진행하실 수 있을 것 같네요. ^^

궁금한점 있으시면 편하게 코멘트 또는 DM 남겨주세요

2021-02-08 17:33 UTC, serverwizard commented on src/main/java/racingcar/domain/trynumber/TryNumber.java
> +        if (tryNumber > FINISH_VALUE) {
아래와 같이 변경해볼 수도 있을 것 같아요~
```suggestion
return tryNumber-- > FINISH_VALUE;
```

2021-02-08 17:33 UTC, serverwizard commented on src/main/java/racingcar/domain/car/Car.java
> +    private final String name;
여기도 원시 값을 포장해보면 좋을 것 같네요!

2021-02-08 17:33 UTC, serverwizard commented on src/main/java/racingcar/domain/car/util/RandomMovingStrategy.java
> +    private final int END_EXCLUSIVE_NUMBER = 10;
클래스 변수가 아닌, 인스턴스 변수로 선언한 이유가 있을까요?

2021-02-08 17:33 UTC, serverwizard commented on src/test/java/racingcar/domain/car/CarTest.java
> +        assertThat(car.getName()).isEqualTo(name);
값으로 비교가 아닌, 객체끼리 비교해볼 수도 있겠네요!

2021-02-08 17:33 UTC, merged

2021-02-09 16:21 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/trynumber/TryNumber.java
> +        if (tryNumber > FINISH_VALUE) {
알아보기 훨씬 깔끔하고 좋네요. 이런 부분을 왜 놓쳤던 걸까요.. 반드시 기억해야겠네요 👍

2021-02-09 16:21 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/Car.java
> +    private final String name;
CarPosition을 포장할 때는 단위테스트를 하는 것을 깜빡했었는데, 마침 오늘은 피드백 강의 시간에도 언급됐던 부분이라 이전보다 수월하게(?) 단위 테스트를 먼저 진행하며 포장해볼 수 있었습니다. :)

2021-02-09 16:21 UTC, thisisyoungbin commented on src/main/java/racingcar/domain/car/util/RandomMovingStrategy.java
> +    private final int END_EXCLUSIVE_NUMBER = 10;
인터페이스 구현을 처음 해보면서 한 실수 같아요. main에서 `new RandomMovingStrategy()`로 생성되어 전달돼서 인스턴스 변수로 선언했던 것 같은데요. 상수로 처리되니 클래스 변수로 사용 되는 게 더 적절하겠네요.

2021-02-09 16:21 UTC, thisisyoungbin commented on src/test/java/racingcar/domain/car/CarTest.java
> +        assertThat(car.getName()).isEqualTo(name);
이 부분에서 질문이 있는데요 ! 따로 밑에 코멘트로 남겨보겠습니다 :)

2021-02-09 16:27 UTC, thisisyoungbin commented
이번 2단계도 리뷰를 위해 시간내주셔서 감사합니다 :D  
부끄럽지만 평소 생각을 깊게 하지 않는 편인데요...
던져주신 질문들을 고민해보며 나름대로 생각하는 것을 연습하는 계기가 됐네요.

익숙하지 않은 뇌활동이라 여전히 놓치고, 부족한 부분이 많을 거라 생각합니다.
제가 놓치거나 잘못 생각하고 있는 부분들이 있다면 말씀해주시면 감사하겠습니다.
***
이번 2단계 리팩토링 과정에서 name값을 포장하며 생긴 궁금즘이 있어서 질문드려요.
CarName이라는 없던 클래스를 만들다보니 기존에 작성했던 테스트코드들을 수정해야 테스트가 통과되는 경험을 했는데요.

예를들어 CarTest-testEqualToPosition()에서 
`Car car = new Car("benz", new CarPosition(2));` 와 같은 부분이 
`Car car = new Car(new CarName("benz"), new CarPosition(2));`와 같이 변경이 필요하게 되는데 (이 과정은 CarPosition에서도 겪었던 부분), 뭔가 Test를 통과하기 위해 짜맞추고 있다는 생각이 들었습니다. 

- 위의 상황처럼 **테스트코드를 수정하는 과정이 발생할 수도 있나요?**
#
또 CarName이 새로운 객체로 생성되어 같은 이름이더라도 다른 Car객체로 판단을 하고 있는 것 같습니다. 
그래서 이름 중복 유효성 검사를 못하는 버그가 발생하게 됐는데요 ! 
이름 값을 모아서 비교하도록 수정해서 fix는 했습니다만 테스트코드에서도 객체끼리 비교하지 못하고 이름 값(String)으로 비교했는데요.

- **포장된 원시 값을 지닌 객체의 경우 객체끼리의 비교가 불가능한 게 맞나요?**  
#

2021-02-09 16:46 UTC, thisisyoungbin commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        List<Car> carGroup = makeCarGroup(carNames);
RacingCarGame이 반드시 Cars 객체와 Trynumber가 뭔지 알고 받아서 실행되지 않아도 될 것 같아요! 
말씀해주신대로 `자동차 이름`과 `시도 횟수`만 input으로 받고, RacingCarGame 내부에서 input에 대한 유효성검사를 하고 Cars와 TryNumber를 각각 생성해도 될 것 같습니다 !

게이츠가 던져준 질문을 고민해보면서 '프론트단에서 검증을 마쳤다고 하더라도 백엔드에서 다시 한 번 검증을 하면 더 악의적인 조작이 있더라도 안전할 수 있겠구나'라는 생각이 들었습니다. 비용이 좀 들더라도 안전장치를 하나 더 설치하는 것이 최악의 경우에 발생할 수 있는 피해보다 낫다! 라고 비유해볼 수 있을 것 같아요. 이런 점들을 고민해볼 수 있도록 질문을 던져주신 게 맞나요? ㅎㅎ

제가 놓쳤거나 잘못 생각한 부분들이 있다면 더 말씀해주세요~

2021-02-14 14:42 UTC, serverwizard commented on src/main/java/racingcar/controller/RacingCarGameController.java
> +        List<Car> carGroup = makeCarGroup(carNames);
잘 이해해주셨네요~^^