[2단계 - 자동차 경주 리팩토링] 케빈(박진홍) 미션 제출합니다.
woowacourse/java-racingcar pull request #197
Opened 2021-02-08 02:35 UTC by xlffm3

안녕하세요.
지난번 주요 피드백 내용은 다음과 같습니다.

* 테스트 메서드명에 snake 표기법을 사용하지 말고 DisplayName 애너테이션을 사용하기.
* 유효성 검증 테스트시 예외 발생 여부 확인과 더불어서 예외 메시지 확인하기.
* dto 패키지 위치 변경
* 생성자 검증 로직 순서 변경 (인스턴스에 값 할당 전에 검증하도록)
* Car, Cars가 int 랜덤값을 받아 움직이는 로직에 대한 리팩토링

해당 피드백들을 적용하고 그에 따른 리팩토링을 진행해보았습니다. 이번 리뷰도 잘 부탁드리겠습니다. :D

2021-02-09 09:32 UTC, choihz requested changes
안녕하세요, 케빈!
1단계에서부터 잘 해주셔서 2단계도 금방 마치셨군요 👍 이번에 남겨드린 코멘트는 대부분이 정답이 없는 문제에 관한 것이라, 스스로 고민하고 학습하신 후 케빈이 옳다고 생각하는 부분만 선택하여 반영하시면 됩니다.

남겨주신 질문에 관하여 제 의견을 말씀드리자면,
1. DTO를 사용하는 것이 좋은지 안 좋은지, 만약 사용한다면 어느 범위에서 생성하고 사용해야 하는지 등에 관해서는 정말 정답이 없어요. 때로는 상황에 따라서, 때로는 취향에 따라서 갈라지곤 하죠 😅 다만 현재의 구조에서는 문제가 될 수 있는데요, 도메인 객체가 DTO를 알고 생성하고 의존하고 있기 때문이에요. 케빈이 언급하신 것처럼 이렇게 되면 바깥의 요구사항이 변경될 때마다 도메인에서도 변경이 일어나야 하죠(이게 대체 왜 문제일까에 대해서도 생각해 보세요). 심지어 `CarsTest`에서는 DTO를 이용해 도메인 객체를 검증하고 있어요.
따라서 DTO가 무엇인지, 어떤 장점이 있어 사용하는 것인지 학습해 보시고, 만약 이번 미션에서 DTO를 사용하는 것이 적절하다고 판단하신다면 어디서 이것을 생성할 것인지도 고민해 보시면 좋을 것 같습니다.
2. 우선 재입력은 미션의 요구사항에는 없기 때문에 본인이 필요하다고 생각하면 구현하시면 됩니다.
유효성 체크는 당연히 View에서도 해주면 좋습니다. View에서는 빈 값 등 최소한의 검증만 한 후 도메인에서 구체적으로 검증해도 되고요. 말씀하신 것처럼 웹 어플리케이션이라면 더 꼼꼼하게 검증하는 것이 중요하겠지만, 이번 미션에서는 이 정도도 충분하다고 생각합니다 ☺️

궁금증이 충분히 해결되었을지 모르겠네요. 더 궁금한 점이 있으시다면 언제든 코멘트나 DM 주세요~

2021-02-10 05:29 UTC, xlffm3 commented on src/main/java/racing/domain/Car.java
>      }
다시 보니 말씀하신 것 처럼 되게 부자연스럽네요!! 😥

2021-02-10 05:40 UTC, xlffm3 commented on src/main/java/racing/domain/Cars.java
>      public List<CarDto> getCarDtos() {
도메인 객체와 DTO 간의 변환 작업을 어느 위치에서 진행해야 할지 다시 고민해봐야겠습니다.

2021-02-10 06:13 UTC, xlffm3 commented on src/main/java/racing/domain/RandomMovingStrategy.java
> +        return randomNumber >= MINIMUM_MOVE_NUMBER;
RandomMovingStrategy는 클래스 이름 자체로도 랜덤한 전략을 통해 이동한다는 점을 시사하고 있으니, 랜덤을 결정짓게 하는 요소는 해당 클래스 내부에 두어도 될 것 같아요. :D

2021-02-10 06:30 UTC, xlffm3 commented
안녕하세요!
남겨주신 피드백은 전부 반영했습니다.

도메인 모델 데이터를 뷰에 노출시키는 방법과, 도메인 모델과 DTO간의 변환 작업 위치에 대해 많이 고민해보았습니다.

https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application
https://javacan.tistory.com/entry/methods-about-exporting-domain-object-to-view
https://buildplease.com/pages/repositories-dto/

등을 참고해서 Domain 객체는 DTO에 대해 알지 못하게 하고, Controller에서 DTOAssesmbly를 이용해서 변환 작업을 수행했습니다.

DTO 관련해서 공부를 진행하다보니 [DTO를 어느 레이어까지 사용해야 하는지](https://stackoverflow.com/questions/21554977/should-services-always-return-dtos-or-can-they-also-return-domain-models) 등 정답이 없는 이슈들이 많다는것을 다시금 느꼈어요. (제가 남긴 질문들 포함...😅😅)

특히 도메인 모델과 비슷한 DTO 생성은 코드의 복잡성과 도메인 모델의 보호 및 안정성 측면에서 상충되는 부분이 있다보니, 나중에는 프로젝트 규모 등을 고려해서 DTO 사용할지를 고려해야겠습니다.😊😊

2021-02-10 09:44 UTC, choihz approved these changes
안녕하세요 케빈!
우와, 코멘트에서 정말 많이 학습하시고 고민하신 게 느껴지네요. 말씀하신 것처럼 개발을 하다 보면 생각했던 것보다 정답이 없는 문제가 정말 많더라구요. 앞으로도 이렇게 공부하고 고민하다 보면 본인만의 답을 찾아가실 수 있을 거예요 👍
첫 미션 진행하느라 정말 고생 많으셨습니다. 즐거운 설 연휴 보내세요~!

2021-02-10 09:44 UTC, merged