[2단계 - 자동차 경주 리팩터링] 루트(김준근) 미션 제출합니다.
woowacourse/java-racingcar pull request #219
Opened 2021-02-10 07:10 UTC by Junroot

## 후기

안녕하세요 휴! 1단계에서 자세한 피드백 고마워요! 🙏 

피드백 내용을 읽고, 레이싱 게임을 관리하는 도메인을 만들고 컨트롤러에 있는 비즈니스 로직들을 분리시켰어요! (<https://github.com/woowacourse/java-racingcar/pull/176#discussion_r571433794>)

확실히 분리시켜보니 자연스럽게 `WinnerUtils`가 사라지고, 자연스럽게 static 메서드들의 의존성 문제도 해결됐어요!!

그리고 이번에 일급컬렉션이라는 것을 알게되어서 제 코드에도 `Cars`라는 클래스를 새로 만들어 봤어요! 
(<https://github.com/woowacourse/java-racingcar/pull/176#discussion_r571439700>)

이렇게 클래스를 분리하니 리스트에대한 validate를 생성자에서 처리할 수 있으니, 검사가 실수로 빠지는 경우가 사라져서 좋았어요 ㅎㅎㅎㅎ

## 질문

### 생성자의 인자

`Cars`라는 클래스를 만들 때 이런 의문이 들었어요. 

> 인자로 파싱되기 전의 `String`(ex. "A,B,C")을 보낼까, 밖에서 파싱한 후의 `List<Car>`를 보낼까?

일단 저는 생성자에 클래스의 인스턴스 변수와 직접적인 연관이 없는 것을 생성자의 인자로 받는 것이 어색하게느껴져, 생성자의 인자로는 `List<Car>`를 받고 `newInstance(String input)`이라는 정적 팩토리 메서드를 만들어서 이 메서드 안에서 파싱을 한 후 생성하도록 구현했어요. 생성자의 인자를 얼마나 wrapping 하는 것이 좋을지 선택하는 좋은 팁이 있다면 알려주세요! 혹시 정해진 기준이 없다면 휴는 어떻게 선택해서 사용하고 있는지 알려주세요!

2021-02-10 15:44 UTC, Hue9010 requested changes
잘 구현해주셨네요! 👍
약간 아쉬운 부분이 있어 피드백 남겼어요.  금방 반영하실 수 있을 것 같아요. 😉
명절 때도 부담 갖지말고 리뷰 요청 보내주시면 시간 될 때 피드백 드리도록 할게요.
새해복 많이 받으세요~!!

2021-02-10 15:44 UTC, Hue9010 commented on src/main/java/racingcar/domain/Cars.java
> +    }
> Cars라는 클래스를 만들 때 이런 의문이 들었어요.
>
> 인자로 파싱되기 전의 String(ex. "A,B,C")을 보낼까, 밖에서 파싱한 후의 List<Car>를 보낼까?
>
> 일단 저는 생성자에 클래스의 인스턴스 변수와 직접적인 연관이 없는 것을 생성자의 인자로 받는 것이 어색하게느껴져, 생성자의 인자로는 List<Car>를 받고 newInstance(String input)이라는 정적 팩토리 메서드를 만들어서 이 메서드 안에서 파싱을 한 후 생성하도록 구현했어요. 생성자의 인자를 얼마나 wrapping 하는 것이 좋을지 선택하는 좋은 팁이 있다면 알려주세요! 혹시 정해진 기준이 없다면 휴는 어떻게 선택해서 사용하고 있는지 알려주세요!

"A,B,C"를 기반으로 List\<Car>를 만들기 때문에 연관이 없다고 생각치 않아요. 파싱하고 List로 만드는 것도 생성을 위한 과정이기 때문에 생성과 별개의 기능이 들어가 있지도 않다고 생각합니다.

> Effective Java에서는 다음과 같은 장단점을 설명한다.
>
> *장점*
이름이 있으므로 생성자에 비해 가독성이 좋다.
호출할 때마다 새로운 객체를 생성할 필요가 없다.
하위 자료형 객체를 반환할 수 있다.
형인자 자료형(parameterized type) 객체를 만들 때 편하다.
*단점*
정적 팩토리 메서드만 있는 클래스라면, 생성자가 없으므로 하위 클래스를 못 만든다.
정적 팩토리 메서드는 다른 정적 메서드와 잘 구분되지 않는다. (문서만으로 확인하기 어려울 수 있음)

[정적 팩토리 메서드(static factory method)](https://johngrib.github.io/wiki/static-factory-method-pattern/)

현재 의도하신 바는 팩토리 메서드를 만드는 이유에도 속하지 않습니다. 생성자를 심플하게 하고 싶은게 목적을 보입니다.

2021-02-10 15:44 UTC, Hue9010 commented on src/main/java/racingcar/domain/Cars.java
> +        this.value = new ArrayList<>(value);
deep copy👍
```java
private final List<Car> value;
```

---

Q. value를 final로 선언해 주셨는데 정말 변경 불가능 한 상태일까요? 🤔 
A. 리스트의 요소인 Car의 Position이 바뀌고 있기 때문에 불변 객체는 아닙니다. List.add 등 리스트 자체도 변경 될 수있습니다. 재할당만 금지된 상태죠. 
그래서 final 키워드 사용 목적이 불변 객체로 관리하기 위함인지, 재할당을 막기 위함인지에 따라 잘못 사용한 케이스가 됩니다.

2021-02-10 15:54 UTC, Hue9010 commented on src/main/java/racingcar/domain/Cars.java
> +        this.value = new ArrayList<>(value);
[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)
`2. 불변`에서 이 내용을 잘 설명해주네요!

2021-02-10 15:55 UTC, Hue9010 commented on src/main/java/racingcar/domain/Cars.java
> +    private final List<Car> value;
이건 다른 분들 코드도 보다보니 values로 네이밍을 많이 가지고 있는데 어떤 내용이 있었는지 알 수 있나요? 
제가 모르고 있던 내용이나 어떤 방법의 다른 컨벤션이 있는지 궁금하네요. 😋

2021-02-10 16:17 UTC, Junroot commented on src/test/java/racingcar/TrialTest.java
> +            final Trial trial = Trial.newInstance(input);
헉 이런 실수를... 죄송합니다... ㅠㅠㅠㅠ

2021-02-11 01:49 UTC, Junroot commented on src/main/java/racingcar/domain/Cars.java
> +    private final List<Car> value;
`📖 자동차 경주 피드백` 수업시간에 제이슨이 일급 컬렉션을 알려주셨는데 그 때 인스턴스 변수를 `value`로 사용했어요! 저도 그 때 일급 컬렉션을 처음 알게 된거여서 그렇게 네이밍을 했는데, 문제가 없다면 `cars`로 하는게 더 좋을거같아요!!

2021-02-11 01:56 UTC, Junroot commented on src/main/java/racingcar/domain/Cars.java
> +        this.value = new ArrayList<>(value);
휴의 말대로 Car의 인스턴스 변수의 값이 계속 바뀌기 때문에 재할당을 막기 위해서 사용한 `final`이였어요! 로직 상으로 재할당 될 일이 없을거라고 판단해서 `final`을 붙였어요!!

2021-02-13 10:48 UTC, Hue9010 approved these changes
Position, Name까지 만들어주시다니 👍
전체적으로 깔끔히 잘 구현해주셨어요! 워낙 잘해주셔서 이번엔 크게 드릴만한 피드백이 없을정도네요. 💯  
이번 단계는 여기서 머지하도록 할게요.
고생 많으셨습니다. 다음 단계도 화이팅입니다! 😉

2021-02-13 10:48 UTC, Hue9010 commented on src/main/java/racingcar/domain/RacingGameFactory.java
> +        if (!NUMBER_PATTERN.matcher(input).matches()) {
참고로 `NUMBER_PATTERN.matcher()`로 matcher를 상수화 시킬 수도 있지 않을까 생각해볼 수도 있지만 Matcher의 설명을 보면 쓰레드 세이프하지 않아 그러면 안되다는 걸 알 수 있답니다. 😉 
```java
 * <p> Instances of this class are not safe for use by multiple concurrent
 * threads. </p>
```

2021-02-13 10:48 UTC, Hue9010 commented on src/main/java/racingcar/domain/car/Name.java
> +public class Name {
👍

2021-02-13 10:48 UTC, Hue9010 commented on src/main/java/racingcar/domain/car/Position.java
> +    }
💯

2021-02-13 10:48 UTC, merged