[2단계 - 자동차 경주 리팩토링] 샐리(조연우) 미션 제출합니다.
woowacourse/java-racingcar pull request #223
Opened 2021-02-10 09:41 UTC by dusdn1702

안녕하세요 데이브! :)

이번 2차 미션은 데이브가 주신 리뷰를 바탕으로, 이번 강의에서 배운 것까지 접목시키며 나름의 기준(?)을 갖고 리팩토링 해보았어요 😄

제가 주로 노력한 부분은
- 객체에 메시지를 보내자   
_최대한 책임이 있는 객체가 행위를 하도록 한다._ 라는 기준으로 객체를 다시 나누고, 메서드를 정리해보았어요. 정리하고 나니 자연스레 제가 갖고 있던 몇몇 의문들도 해결되더라구요 ㅎㅎ
- getter의 최소화  
_outputView가 아닌 이상 getter를 사용하지 않는다. 디미터의 법칙을 지킨다._ 라고 생각하고 구현을 하려는데 car(객체) -> carName(객체) -> name(문자열) 을 가져오는 부분에서 
```java
for (Car car : cars.toList()) {
            OutputView.printCarInfo(car.getName().getName(), car.getPosition());
        }
```  
과 같이 디미터의 법칙이 위반되는 경우 어떻게 하면 좋을지 고민을 하다가 car라는 객체에서의 getter를 다음과 같이 구현을 해봤어요!
```java
    public String getName() {
        return carName.getName();
    }
```  
그러고 나니 왜 디미터의 법칙이라는 것이 생겨났을까에 대해서 고민해봤을 때, 객체의 속사정을 알리지 않고 책임을 분명히 하기 위해서라고 생각했는데, 이처럼 구현하면 다른 점이 없는 것 아닐까? 라는 생각이 들었어요. 데이브는 어떻게 생각하시나요?  
- 불변의 객체  
제이슨의 최대한 final을 활용해 불변의 객체를 생성하라는 강의를 듣고 제 코드에서 lap과 position을 final로 제한해주었어요.  
그런데 position이라는 것이 어쩔 수 없이 변할 수밖에 없는 값이다보니, Car가 가진 Position은 final로 제한할 수 없었어요. 그 Position이 자체로 보증된 값이니 괜찮은 걸까요?  
- 방어적 복사
값을 안전하게 관리하기 위해 **방어적 복사**라는 것을 제이슨의 강의에서 배우고, 일급컬렉션으로 포장된 객체들에게 적용해보았어요. 사실 처음으로 배운 개념이고, 맞게 적용했는지는 모르겠지만 사용자가 건드릴 수 없는 다른 객체들에서는 불필요할 것이라고 생각했어요. 아직 이 부분에 대해서 많이 공부가 필요한지라, 앞으로 더 공부해보려고 해요 🤨

오늘도 귀한 시간 내어주셔서 정말 감사해요, 데이브 ☺️
새해 복 많이 받으시고 즐거운 연휴 보내시길 바랄게요 🧧

2021-02-14 06:33 UTC, dave915 requested changes
샐리 셜 연휴 잘 보내셨나요 ㅎㅎ 
2단계 요구사항도 잘 반영해주셨네요! 
피드백과 남겨주신 질문에 대해 코멘트 남겼어요. 
혹시 궁금한 점이 있다면 언제든지 DM주세요!

2021-02-14 06:33 UTC, dave915 commented on src/main/java/racingcar/domain/Cars.java
>      }
이 메소드는 RandomNumber.make()에서 어떤 숫자가 나올지 몰라서 테스트 하기 힘들텐데, 어떻게 하면 moveAllCars() 메소드를 호출했을때 car.moveByNumber가 동일하게 호출 되었는지 알 수 있을까요? 🤔

2021-02-14 06:33 UTC, dave915 commented
>그러고 나니 왜 디미터의 법칙이라는 것이 생겨났을까에 대해서 고민해봤을 때, 객체의 속사정을 알리지 않고 책임을 분명히 하기 위해서라고 생각했는데, 이처럼 구현하면 다른 점이 없는 것 아닐까? 라는 생각이 들었어요. 데이브는 어떻게 생각하시나요?

```
for (Car car : cars.toList()) {
            OutputView.printCarInfo(car.getName().getName(), car.getPosition());
        }
```
```
car.getName();

public String getName() {
        return carName.getName();
    }
```
제 생각에는 위와 아래는 분명한 차이가 있다고 생각해요.
자판기로 비유를 해보자면.. 커피를 얻기위해 위 코드는 자판기 안에 재료통 안에 커피가루를 갖고와서 사람이 커피를 타는 느낌이고, 아래는 자판기에게 커피를 요청하면 자판기가 내부에서 커피를 만들어서 주는 느낌이라고 해야하나 ㅎㅎ 
캡슐화라고 생각하시면 될 것 같아요!

>Car가 가진 Position은 final로 제한할 수 없었어요. 그 Position이 자체로 보증된 값이니 괜찮은 걸까요?

Position 객체가 VO인 특성을 갖고있기때문에 괜찮다고 생각이 드네요 :)

2021-02-15 05:36 UTC, dusdn1702 commented
어제 피드백을 받은 이후로, 어떻게 테스트를 구현할 수 있을까 고민을 하다가 '인터페이스'라는 것을 알게 되었어요!!
아직 자바라는 언어에 익숙치 않은 단계라 인터페이스라는 것도 들어만 보았지 처음 적용해보는 개념이라 익히는데 시간이 조금 걸렸네요..
인터페이스를 분리함에 따라 moveAllCar라는 메서드도 테스트할 수 있게 되었어요!!👍

2021-02-15 17:01 UTC, dave915 approved these changes
샐리 안녕하세요! 
마지막 피드백도 반영한 것 확인했습니다! 
혹시 궁금한 점이 있다면 언제든 DM 주세요 :) 
이만 머지할게요!

2021-02-15 17:01 UTC, dave915 commented on src/main/java/racingcar/domain/number/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements NumberGenerator {
👍👍

2021-02-15 17:01 UTC, merged