[1단계 - 자동차 경주 구현] 더즈(이동규) 미션 제출합니다.
woowacourse/java-racingcar pull request #259
Opened 2022-02-10 12:47 UTC by ldk980130

안녕하세요! 더즈입니다. 부족하지만 첫 리뷰 잘 부탁드립니다!!

다음은 제가 페어와 함께 코딩하다가 어려웠던 점을 정리한 것입니다.

**Dto사용**
getter 사용을 지양하고 함수에 메시지를 던지라는 피드백을 프리코스 때 받았습니다. 그래서 getter를 사용하지 않자니 뷰 부분에서 Car의 이름과 위치를 필연적으로 출력해야해서 getter를 써야하나 고민했지만 Dto를 만들어서 해결하기로 했습니다.
그러다 보니 Car의 필드 값이 필요할 때마다 Dto로의 변환 작업이 여기저기서 이루어졌는데 이렇게 사용하는게 맞는지 의문이 들었습니다.

**Controller에서 비즈니스 로직 구현**
자동차 경주 로직 상 레이스가 시도 횟수만큼 반복 되면서 중간중간에 레이스 진행 상황이 출력되어야 합니다. 그래서 Service에서 레이스 로직을 다 끝내고 Controller에서는 결과만 View로 전달하는데 어려움이 있었습니다.
그래서 Service에서는 한 시도 횟수의 레이스 로직을 구현하고 횟수만큼 반복하는 부분은 Controller에서 View 처리와 함께 구현되었습니다. Service에서 처리되어야할 것 같은 이런 로직이 Controller에서 구현되는게 석연치 않았습니다.

**Ramdom값 발생 로직을 위한 Test Code 작성 시 어려움**
Random 값을 사용하다 보니 테스트 코드 작성 시 어려움이 있었습니다. 이를 해결하기 위해 랜덤 값을 생성하는 인터페이스를 만들고 실제로는 난수를 발생시켜 애플리케이션을 실행하고 테스트 코드에서는 고정 값을 전달하여 테스트를 확인하도록 하였습니다.
하지만 이러한 인터페이스 관련 코드들은 테스트를 짜지 않았더라면 필요 없었을 코드들입니다. 이렇게 테스트를 위한 코드가 추가되는 게 괜찮은 방법인지 의문이었습니다

2022-02-11 00:30 UTC, toneyparky requested changes
반가워요 더즈! 저는 토니입니다. 이렇게 우테코 4기 첫 미션으로 만나게 되었네요!!

작성하신 코드 잘 확인했구요. 코드를 보며 깔끔하다는 인상을 받았어요.!

특히, 프로그래밍 요구사항을 꼼꼼하게 지켜주신거 같습니다 👍👍

질문하셨던 부분은 `Qeustion.md`에 남겨놨으니 확인부탁드리고 추가 질문은 언제든 환영입니다!

DM도 좋아용 😀

2022-02-11 00:30 UTC, toneyparky commented on docs/racingcar/README.md
> +## 요구사항 기능목록
요구사항에 대한 정리를 잘 해주셨네요!! 좋습니다 👍  
앞으로도 빠트리는 요구사항, 예외 처리가 없도록 꼼꼼하게 작성해주시면 미션을 진행하시는 데에 많은 도움이 될거에요.

지금의 형태에서 더즈에게 맞는, 미션에 맞는 형태로 변화시켜가며 작성해봅시다!

2022-02-11 00:30 UTC, toneyparky commented on src/main/java/racingcar/view/InputView.java
> +public class InputView {
`InputView`는 현재 사용자에게 어떤 입력이 필요한지에 대한 메시지를 전달하고, 실제로 입력을 받는 역할을 하네요!

여기에 추가로 사용자 입력이 올바른 형태인지 검증하는 행위를 하는군요! 

묻고 더블로 `Car` 객체의 이름과 시도 횟수가 요구사항에 맞는지에 대해서도 검증하네요. 

아직 끝나지 않았어요. `InputView`를 사용하는 사람이 `Car` 객체를 바로 사용할 수 있도록 `List<Car>` 형태로 변환까지 해주네요!

똑똑한 녀석인거 같아요 🤓

---

이렇게 많은 일을 하는 친구는 연관된 한가지 요구사항이 바뀌더라도 내부 구현을 변경해야할 일이 잦아진답니다. 

`InputView`라는 객체가 정말 해야하는 역할과 행위가 뭔지에 대해서 생각해보면 좋을 것 같아요!

2022-02-11 00:30 UTC, toneyparky commented on docs/racingcar/Question.md
> +- 아니면 그냥 0을 넘겨주는게 더 좋은 방법일지?
제 의견을 말씀드리자면, 리드미에 적어주셨듯 `CarRepository`은 자동차를 저장하는 객체네요. 

자동차 내에 속한 필드가 `position`이구요.

사용자는 `findMaxPosition`메서드를 사용하기 전에 `CarRepository`가 자동차를 가지고 있는지 없는지 알 수 없죠. (따로 확인하지 않는 이상)

해당 메서드를 사용하는 입장에서는 자동차가 있겠거니 하고 사용할거 같아요. 그렇다면 max position이 0으로 나온다면 어떻게 받아드릴까요? 저는 자동차가 N대 있지만 출발한 적이 없거나, 모두 이동하는 데에 실패했을 수도 있다는 생각을 할 거 같아요. 0도 0만의 의미가 있을 수 있다 생각합니다 😬

정답은 없다 생각해요. 다만 요구사항을 해치지 않는 한에서 사용하는 사람이 납득가는 방향으로 구현하시면 될 거 같아요!

2022-02-11 00:30 UTC, toneyparky commented on docs/racingcar/Question.md
> +- 안 쓰려면 View 기능이 객체 안으로 들어가야 함
게터에 대한 사용은 이를 남용하지 말자라는 의도로 이해하고 있어요. 필요한 곳에서는 사용해야 한다고 생각합니다. 남용의 측면에서 말씀드리자면, 게터를 여러번 연결하여 객체 내부의 내부의 값을 꺼내서 사용하는 예시를 들 수 있겠네요!

게터의 사용을 막기 위해 DTO를 사용하셨군요!!  
DTO를 사용해도 게터를 사용함은 변하지 않는데 `Car` 객체에서 그대로 게터를 사용함과 DTO를 통해 사용하는 차이는 뭘까요?

2022-02-11 00:30 UTC, toneyparky commented on docs/racingcar/Question.md
> +- Ramdom으로 발생하는 값을 제어할 수 있을지?
더즈가 지금 고민하신 내용은 너무 좋아요 👍  
랜덤과 같이 테스트하기 힘든 부분과 테스트할 수 있는 부분을 구분하기 위해 인터페이스로 잘 분리해주셨구요!!  
구현에 있어 핵심은 자동차가 특정 상황에서 이동할 수 있는가 없는가라고 생각하기에 특정 상황을 테스트할 수 있도록 잘 처리하셨다고 생각합니다 😬

2022-02-11 00:30 UTC, toneyparky commented on docs/racingcar/Question.md
> +- 서비스 안에서 반복하면 직접 View를 호출해야 함
비즈니스 로직에 대한 경계와 서비스와 뷰 간의 관계를 맺지 않으려는 고민이 보이네요!! 

비즈니스 요구사항이 얼마나 변할 여지가 있는지에 따라 결정되면 좋을 것 같아요. 자동차에 대한 비즈니스 로직은 차가 움직일 수 있는지에 대한 여부(숫자 4 이상)와 같은 정책이 변경될 여지가 있고 시도 횟수의 비즈니스 로직보다는 변동성이 크기에 서비스단에서 처리해주는 데에서 얻는 이득이 더 클거 같아요! 여기서 이득이라 함은 변화에 대한 영향을 최소화하여 다른 객체에 영향을 최소화할 수 있음을 예로 들 수 있을 것 같습니다.

하지만 시도 횟수는 자동차 경주라는 도메인 내에서 지금의 형태를 벗어날 일이 없을 것 같기에 `RacingController`이 담당하는 어플리케이션의 흐름을 제어한다는 행위를 위해 사용되어도 좋지 않을까라는 생각이 듭니다 😉

좋은 고민이에요!

2022-02-11 00:30 UTC, toneyparky commented on src/main/java/racingcar/validator/Validator.java
> +	}
```suggestion
	public static void ofCarNames(String input) {
		Arrays.stream(validateCarCount(input))
			.forEach(Validator::validateCarName);
	}

	private static String[] validateCarCount(String input) {
		String[] split = input.split(SEPARATOR_OF_CAR_NAME);
		if (split.length < CAR_COUNT_LIMIT) {
			throw new IllegalArgumentException(CAR_COUNT_LIMIT_ERROR_MESSAGE);
		}
		return split;
	}

	private static void validateCarName(String name) {
		if (name.isEmpty()) {
			throw new IllegalArgumentException(EMPTY_CAR_NAME_ERROR_MESSAGE);
		}
		if (name.length() > NAME_LENGTH_LIMIT) {
			throw new IllegalArgumentException(INVALID_CAR_NAME_ERROR_MESSAGE);
		}
	}

```

위의 제안사항과 같이 먼저 사용되는 private 메서드를 위에 적어준다면 좋습니다. 

그 이유는 우리는 보통 위에서 아래로 글을 읽기에 가까이에 위치하면 이해하기가 더 좋아서에요 😁

2022-02-11 00:30 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +	}
자동차라는 객체의 입장에서 내가 움직일 수 있는지 없는지 여부를 판단하는데에 입력받는 값이 `randomNumber`라는 구체적인 의미를 가진 값인지 알아야 할 필요가 있을지에 대해서 생각해봅시다!

2022-02-11 00:30 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +	}
요 친구를 사용하면 

이름이 steve jobs이고 포지션이 -100인 자동차 객체를 만들 수 있겠군요!!

자동차 객체에 대한 유효성 검사에 대한 책임은 누구에게 있을지 생각해보면 좋을 것 같아요!

2022-02-11 00:30 UTC, toneyparky commented on src/main/java/racingcar/view/InputView.java
> +		return Converter.toCarList(scanner.next());
더즈! 혹시 scanner.next()와 scanner.nextLine()의 차이에 대해서 알고 계신가요?!

2022-02-14 00:11 UTC, toneyparky requested changes
고생 많으셨어요 더즈! 리뷰 반영 잘 해주셨네요. DM으로 질문 주신 부분도 좋았어요!

아직 시간이 있기에 머지하기 보다는 리뷰 및 궁금한 점에 대해서 남겨봤어요 😀

추가적으로 리뷰에 답글을 달아주시면 더 재미있게 코드 리뷰할 수 있을거에요!! 소통하는 느낌이 드니까요. 

오늘도 화이팅입니다!

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/controller/RacingController.java
> +	private final RandomUtilImpl randomUtil = new RandomUtilImpl();
```suggestion
	private final RandomUtil randomUtil = new RandomUtilImpl();
```

요건 이렇게 작성할 수도 있죠!

지금 더즈의 구현과 어떤 차이점이 있을까요?

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +			throw new IllegalStateException();
이 상황에 맞는 예외 메시지를 던져볼까요?

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +	}
정적 팩토리 메서드에 대해서 조금 더 공부해볼까요?

[글](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)을 읽으면 도움이 될 거에요.

어떤 경우에 사용하는지, 네이밍 컨벤션은 어떤지 학습해보죠!

2022-02-14 00:11 UTC, toneyparky commented on docs/racingcar/README.md
> +  - RacingController
스프링의 구조를 차용하신 부분은 어떤 과정을 통해 결정되었는지 궁금해요 😉

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +
공백이 두 줄이네요. 코드를 작성함에 있어 공백도 의미를 가지기에 주의하시면 좋을 것 같아요 😬

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +	private static final CarRepository carRepository = new CarRepository();
`CarRepository`를 static으로 선언해주신 이유가 있을까요?

2022-02-14 00:11 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +	public static final int MINIMUM_NUMBER_OF_RACE_POSSIBLE = 2;
public 상수가 private 상수 아래에 위치하네요. 앞선 리뷰의 연장선으로 말씀드리자면, 변수나 상수 그리고 메서드 선언의 순서는 읽는 이를 배려하는 좋은 규칙이라 생각해요. 

[구글의 자바 코딩 스타일](https://google.github.io/styleguide/javaguide.html)이나 [오라클의 컨벤션](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html)을 보며 순서를 익혀볼까요?

추가적으로 `MINIMUM_NUMBER_OF_RACE_POSSIBLE`가 public인 이유에 대해서도 고민해보면 좋겠어요.

2022-02-14 04:43 UTC, ldk980130 commented on src/main/java/racingcar/controller/RacingController.java
> +	private final RandomUtilImpl randomUtil = new RandomUtilImpl();
질문을 듣고 찾아보던 도중 DI와 인터페이스로 추상화에 대해 조금 알아봤습니다. 타입을 인터페이스로 추상화함으로써 랜덤 숫자 생성 전략이 바뀌더라도 코드 변경이 줄어들고 다양한 의존관계를 맺을 수 있게 된 것 같습니다. 나중에 RandomUtil을 외부에서 주입받게 되었을 땐 런타임 시점에 동적으로 구현체를 갈아끼우는 것도 가능해질 것 같습니다!

2022-02-14 04:59 UTC, ldk980130 commented on src/main/java/racingcar/domain/Car.java
> +	}
좋은 글 공유 감사합니다!!  정적 팩토리 메서드가 이름을 부여할 수 있다는 것과 하위 자료형 객체를 상황에 따라 반환할 수 있다는거까지는 알고 있었는데 캐싱이나 네이밍 컨벤션에 대해선 잘 몰랐어서 많은 되었습니다. 제 코드에선 네이밍 컨벤션에 맞게 이름만 매개변수로 받는 저 친구는 Car.from()으로 변경되어야할 것 같군요

2022-02-14 05:03 UTC, ldk980130 commented on src/main/java/racingcar/service/RacingService.java
> +	public static final int MINIMUM_NUMBER_OF_RACE_POSSIBLE = 2;
제 원래 의도는 private이었는데 뭔가 실수로 public이 된 것 같습니다. 수정하겠습니다!

2022-02-14 05:17 UTC, ldk980130 commented on src/main/java/racingcar/service/RacingService.java
> +	private static final CarRepository carRepository = new CarRepository();
처음엔 CarRepository의 cars가 항상 같은 객체임을 보장해야 한다고 생각해서 static을 붙인것 같은데 토니 질문을 듣고 생각해보니 이미 CarRepository에서 cars 리스트가 static이기 때문에 RacingService가 가지고 있는 CarRepository는 이미 cars의 단일객체를 보장하기 때문에 static 선언을 해주지 않아도 될 것 같아요. 싱글톤에 대해 아직 개념이 모호한 것 같아 더 공부해야할 것 같습니다ㅠ

2022-02-14 05:41 UTC, ldk980130 commented on docs/racingcar/README.md
> +  - RacingController
제가 혼자 공부하던 시절 김영한님의 스프링 인강을 들었었는데 강의에서 패키지 구조를 대부분 저렇게 짜셨습니다. 그래서 저 구조가 손에 익어서 대부분 저렇게 짜게 되는 것 같던데 어찌보면 깊은 생각을 안하고 그대로 따라한 감도 없지 않아 있습니다. 프로그램 구조를 짜는데 이런 스프링 구조 말고도 다른 방법도 시도해 보는것이 좋을까요?

2022-02-14 10:35 UTC, toneyparky commented on docs/racingcar/README.md
> +  - RacingController
독학하실 때에 하셨던 스프링 공부가 빛을 발하는군요! 좋습니다. 

다만, 제가 질문드린 이유는 지금의 구조가 꼭 스프링의 구조를 따를 필요가 없다는 생각이 들어서에요. 

스프링의 구조는 레벨 2에서 많이 도전해보실테니 지금은 더즈가 생각하는, 미션에 더 적합한 구조로 진행해봐도 좋을 것 같습니다 😀

이번 미션에서 구조를 다 바꾸는 게 힘들다면 다음에 도전해봐도 좋아요.

2022-02-14 10:37 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +	public static final int MINIMUM_NUMBER_OF_RACE_POSSIBLE = 2;
네! 좋아요. 

코드를 두 번, 세 번 확인하고 pr을 날려봅시다! (저도 많이 부족한 부분이에요 😂)

2022-02-14 10:37 UTC, toneyparky commented on src/main/java/racingcar/service/RacingService.java
> +	private static final CarRepository carRepository = new CarRepository();
좋습니다. 이렇게 공부를 해나가는거죠! 

매일매일 부족한 부분을 정리하는 시간을 가지면 금방 지식이 쌓일거에요. 

댓글에 달아주셨듯, carRepository에는 static을 넣어줄 필요가 없습니다~!

2022-02-14 10:37 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +	}
맞아요. 이름이 바뀌면 이해하는 데에 도움이 되겠죠?

다만, 팀에서 합의된 다른 이름이 있다면 그걸 사용하는 것도 방법이에요.

2022-02-14 10:37 UTC, toneyparky commented on src/main/java/racingcar/controller/RacingController.java
> +	private final RandomUtilImpl randomUtil = new RandomUtilImpl();
더즈가 해주신 말씀이 맞아요. 인터페이스를 사용하여 행위를 구현하도록 처리할 경우에는 말씀해주신 이점을 얻을 수 있죠!

지금 구현에 대해서 이야기해보자면, `RandomUtilImpl` 이라는 구현체의 타입으로 객체를 할당하기보다는, `RandomUtil`이라는 인터페이스로 할당하여 `randomUtil`이라는 변수가 인터페이스로써 사용될 수 있도록 하면 좋아요. 추상화 된 인터페이스 타입을 통해 변수를 더 유연하게 사용할 수 있기 때문이에요.

2022-02-14 10:42 UTC, toneyparky approved these changes
이번 미션은 여기서 마무리해도 좋을 것 같아요. 

제가 남긴 코멘트에 답변 안 다신 것들은 추후에라도 부탁드려요. 언제든 소통하죠!

첫 머지네요. 고생하셨어요 더즈.

2단계도 화이팅입니다!

2022-02-14 10:42 UTC, merged

2022-02-14 11:16 UTC, ldk980130 commented on src/main/java/racingcar/service/RacingService.java
> +	private static final CarRepository carRepository = new CarRepository();
Car를 저장, 관리하는 CarRepository 인스턴스가 여러개 생성된다면 각 인스턴스에 저장된 Car들의 일관성이 깨질까 염려되어 싱글톤을 적용하였습니다. 하지만 그 일관성은 CarRepository의 cars에 static을 선언하면서 cars 리스트는 이미 단 하나였네요. 아예 CarRepository를 싱글톤으로 하는 것, 아니면 필드 변수인 cars를 static 선언하는 것 중엔 어떤 방법이 나은 것일까요?

2022-02-14 11:20 UTC, ldk980130 commented on docs/racingcar/Question.md
> +- 안 쓰려면 View 기능이 객체 안으로 들어가야 함
Car 객체에 게터를 적용하는 것은 객체의 캡슐화를 깨뜨리고 원하지 않은 정보까지 보여줄 수 있는 위험이 있지만 Dto를 만들어 게터를 사용하는 것은 정말 보여줘야할 필요한 정보만 따로 담아서 보여줄 수 있다는게 차이인 것 같습니다!