[1단계 - 자동차 경주 리팩토링] 라라(박세은) 미션 제출합니다.
woowacourse/java-racingcar pull request #260
Opened 2022-02-10 12:50 UTC by sure-why-not

에단 안녕하세요 ! 라라입니다. ㅎㅎ
첫 코드리뷰이다보니 떨리네요..! (괜히 부끄럽기도 하고...)
아무쪼록 잘 부탁드립니다 ! 😆

1단계 미션을 진행하면서 궁금했던 점을 몇가지 작성해보겠습니다.

**getter 사용 + DTO**
---
자동차의 위치를 출력하거나 Service에서 max값을 찾는데 getPosition()과 같은 getter가 필요한 상황이 있었습니다.
getter/setter 사용을 지양하는 것이 좋다고 알고 있어 CarDto를 추가하여 이부분을 해결했는데,
이 부분이 잘 사용되고 구현된 것이 맞는지, CarDto를 사용하는 곳이 여러곳인데 이래도 괜찮은 것인지 궁금합니다.

**비즈니스 로직을 Controller에서 수행**
---
Controller 에서 입력받은 시도 횟수만큼 for 반복하며 Service.race 메소드를 호출하도록 구현했습니다.
매 시도마다 경주 결과를 출력해야하기 때문에 Service 안에서 직접 View를 호출해야하기 때문에 이처럼 구현하게 됐습니다.
이러한 비즈니스로직이 Service에서 구현되어야 할 것 같아 의문이 남아있는 상태입니다..!

**Ramdom값 발생 로직을 위한 Test Code 작성 시 어려움**
---
TDD로 코드를 짜면서 페어와 가장 많은 고민을 했던 부분입니다.
Ramdom 값이 발생하는 로직은 Service가 가지고 있는데, Random 값이 발생하는 것을 테스트 코드상에서 직접 제어할 수가 없었습니다.
따라서 테스트 코드가 동작하도록 RandomUtil 인터페이스를 추가하여 해결해보았습니다.
이건 어떻게 보면 테스트 코드로 접근하기 위해 만들어진 구조인데, 이런식으로 테스트 코드에 맞춰지게 코드를 작성해나가는 것이 맞는 것인지 궁금합니다.

감사합니다 ! 😻

2022-02-10 15:32 UTC, Laterality commented
안녕하세요 라라, 리뷰어 에단입니다.

첫 미션인데 꼼꼼히 신경쓰신 것이 느껴지네요 👍 

고민해보시면 좋을 만한 부분들을 몇 군데 짚어봤는데요. 참고 부탁드립니다.

질문 주신 부분에 대해서도 간략하게 의견 남겨드렸는데요. 확인해보시고 궁금하신 점이나 다른 의견이 있으시면 언제든 코멘트 남겨주세요!

## Q&A

1. getter의 사용 + DTO
  a. getter/setter를 무분별하게 사용하는 것을 바람직하지 않다고 하는 이유는 무엇일까요? 모든 값을 숨겨버리면 사용자는 비지니스 로직이 잘 처리됐는지 알 수 없을테니, 어떤 값은 getter나 DTO를 통해 노출할 필요도 있겠지요. 따라서 "getter/setter는 절대 사용해선 안된다"라기보다는 필요한 경우에만 적절하게 사용하는 것이 좋다고 볼 수 있겠네요. 
  b. "CarDto를 사용하는 곳이 여러곳인데 이래도 괜찮은 것인지 궁금합니다."에 대해서는, 반대로 **`CarDto`를 사용하는 곳이 여러 곳인 경우 어떤 문제가 있을지** 고민해보시면 좋겠습니다. 여러 곳에서 `CarDto`를 사용하고 있다는 것은 `CarDto`가 당장의 요구사항을 해결해주었기 때문일 텐데요. "만약 여러 곳 중 한 곳에서 새로운 요구사항이 발생한다면 어떤 일이 벌어질까?"라는 질문에서 시작해보셔도 좋겠네요.
  c. `position` 필드는 사용자에게 전달될 값이다보니 getter로 노출이 되겠지만, getter 없이 max를 찾는 문제는 `CarRepository`의 스트림 부분에 남겨드린 코멘트를 고민해보시면 답을 찾으실 수 있을 것으로 보여요.

2. 비즈니스 로직을 Controller에서 수행
  a. "이러한 비즈니스로직이 Service에서 구현되어야 할 것 같아 의문"부분이 어떤 의미일까요? 앞에서 말씀하신 "View를 호출하는 Service"를 어떻게 개선하면 좋을지 고민이라는 뜻일까요, 아니면 비즈니스 로직이 Service에서 구현되는 것에 어떤 의문점이 있으신 걸까요?
  b. 매 시도마다 경주 결과를 출력하기 컨트롤러에서 for 처리하신 부분을 고민중이신 것으로 이해했습니다. 매 시도마다 결과를 출력하는 대신, 매 시도마다 결과를 기록한 뒤에 게임이 종료되면 전체 결과를 한번에 반환하는 방법은 어떨까요?

3. Ramdom값 발생 로직을 위한 Test Code 작성 시 어려움
  a. 이번에 경험하신 것과 같이 테스트하기에는 비용이 너무 많이 들거나 테스트가 불가능한 부분이 언제든 발생할 수 있는데요. 모든 코드를 테스트하는 것이 이상적이지만, 현실적으로 테스트하기 곤란한 부분이 생기기 마련이고, 이런 경우 **테스트하기 어려운 부분을 테스트 가능한 다른 부분들과 어떻게 분리할 것인지** 고민이 필요합니다. 이번 미션의 `Car` 도메인을 예로 들면, `Car`에서 중요한 건 `move`의 입력값에 대해 기대한 대로 `position`을 움직이는가(테스트 가능한 부분)와 같은 부분이지, `move`의 입력값을 생성하는 부분(테스트하기 어려운 부분)은 `Car` 도메인과는 관계 없는 부분으로 보입니다. 실제로 `RandomUtil`이라는 인터페이스로 두 부분을 잘 분리하셨고요.
  b. 테스트 가능한 부분과 테스트하기 어려운 부분을 잘 나누려면 무엇을 테스트해야 하는지(테스트 대상) 정확하게 파악하는 것이 중요합니다. 예를 들어 `CarTest`에서는 `Car` 도메인의 동작들(`move`에서 기대한 대로 position을 바꾸는지)을 테스트하는 곳이지, `RandomUtil`의 구현체가 무작위 숫자를 잘 생성하는지 테스트해야 하는 것은 아닌 것처럼요.

2022-02-10 15:33 UTC, Laterality requested changes

2022-02-10 15:33 UTC, Laterality commented on src/main/java/racingcar/domain/Car.java
> +	}
생성자와 동일한 인자를 받는 정적 팩토리 메서드를 추가하셨네요.
생성자 대신 정적 팩토리 메서드를 노출하신 이유가 있을까요?

2022-02-10 15:33 UTC, Laterality commented on src/main/java/racingcar/domain/Car.java
> +	public void move(int randomNumber) {
인자를 `randomNumber`라고 명명하신 건 자동차 이동에 사용하는 값이 "무작위"라는 점을 내포하고 있는 것처럼 보이는데요.

자동차 모델에서도 숫자가 어떻게 생성되는지 알고 있는 걸까요?

2022-02-10 15:33 UTC, Laterality commented on src/main/java/racingcar/repository/CarRepository.java
> +	public List<Car> findCars() {
반환 타입을 구체 타입인 `ArrayList` 대신 `List` 인터페이스로 노출하셨네요 👍 

Java의 컬렉션 프레임워크를 살펴보시면 구체 타입인 `ArrayList`가 인터페이스인 `List`를 구현하고, `List`는 또 다시 다른 인터페이스를 상속받는 구조인 것을 볼 수 있는데요. 상속 구조를 따라가다보면 최상위에 `Iterable` 인터페이스가 존재하는 것을 알 수 있습니다.

반환 타입을 가장 하위 타입인 `ArrayList`로 노출했을 때와 가장 상위 타입인 `Iterable`로 노출했을 때의 장단점이 어떤 게 있을지 고민해보시면 좋겠습니다 :)

2022-02-10 15:33 UTC, Laterality commented on src/main/java/racingcar/repository/CarRepository.java
> +			.max()
스트림에는 아래와 같은 시그니처를 가진 `max`  메서드도 있는데요.

```java
Optional<T> max(Comparator<? super T> comparator);
```

이 메서드를 활용하면 아래처럼 더 간단하게 처리할 수 있습니다, 예를 들면:

```java
cars.stream()
    .max(Car::compareTo)
    .orElseThrow(...)
```

어떻게 하면 불필요한 객체 변환 없이 최대 position을 가진 인스턴스를 찾을 수 있을까요?

2022-02-10 15:33 UTC, Laterality commented on src/main/java/racingcar/validator/Validator.java
> +public class Validator {
여러 모델의 여러 제약 조건들이 `Validator`라는 하나의 클래스에 모여있네요.

제약 조건들이 도메인 객체가 아닌 유효성 검사를 위한 별도의 클래스에 위치한 것은 도메인의 규칙은 아니라고 판단하셨기 때문일까요?

2022-02-10 15:33 UTC, Laterality commented on src/test/java/racingcar/RacingServiceTest.java
> +		assertThat(carCount).isEqualTo(2);
`RacingService`의 테스트인데 이 메서드에는 `racingService`를 테스트하는 부분이 보이질 않네요 😱

2022-02-14 09:43 UTC, sure-why-not commented on src/main/java/racingcar/domain/Car.java
> +	public void move(int randomNumber) {
자동차 모델에서는 숫자가 랜덤으로 발생되는지는 알 필요가 없다고 판단되어 movingNumber 으로 네이밍을 수정했습니다!

2022-02-14 09:51 UTC, sure-why-not commented on src/main/java/racingcar/domain/Car.java
> +	}
정적 팩토리 메서드를 알고는 있었지만 어떤 장단점이 있는지는 정확히 파악하지 못하고 사용했던 것 같습니다. 😅
여러 글들을 읽어보니 생성자를 내부적으로 숨기고, 명확한 의도를 알 수 있는 이름을 가진 메소드를 가지고 객체를 생성할 수 있고, 
반환 타입의 하위 타입 객체를 반환할 수 있는 점 등을 장점으로 파악했습니다.
또한, 단점으로는 상속 구조를 가질 경우 public이나 protected 생성자가 필요하여 사용할 수 없다고 파악했는데요.
이런 장/단점을 파악해보니 현재 상황에서 큰 메리트가 없기 때문에 굳이 사용하지 않아도 될 것 같다고 판단되는데, (아직 남겨두었지만)
혹시 다른 의견이 있으실지 궁금합니다..!

2022-02-14 09:52 UTC, sure-why-not commented on src/main/java/racingcar/repository/CarRepository.java
> +			.max()
힌트로 알려주신 방법을 사용하여 수정해보았습니다!
직접 값을 꺼내어보지 않아도 비교할 수 있는 새로운 방법을 알게 되었네요!

2022-02-14 10:00 UTC, sure-why-not commented on src/main/java/racingcar/validator/Validator.java
> +public class Validator {
해당 피드백을 보고 입력값을 검증하는 책임을 누구에게 부여할지 많은 고민을 거쳐서 수정하게 되었습니다!

기존에는 InputView에서 모두 검증을 했었지만,

InputView의 책임은 "입력값을 받아오는 역할" 이라고 판단되어 값이 입력이 되었는지만 검증하도록 하였고,
자동차 이름의 길이같은 경우 Car 객체의 규칙이기 때문에 Car 에서 검증하도록 했습니다.

또한, 시도 횟수를 입력받아 InputView 에서 값이 입력이 되었는지만 검증하도록 하였고,
시도 횟수가 숫자로 잘 입력되었는지에 대한 검증은
값을 직접 사용하는 RacingController에서 검증하도록 수정했습니다.
확신이 들진 않지만 ,,,
(String)"12" -> (int)12 로 변환하는 로직이지만, 나중에 (String) "열두번" -> (int) 12 로 로직이 변경되더라도
직접 그 값을 변환하여 사용하는 곳에서 로직을 수정하고 처리해야할 것 같다고 판단했기 때문입니다!

그리고 시도 횟수(AttempNumber) 값도 Layer간에 Dto 로 전달하는게 좋을지도 궁금합니다.
원래 Dto로 주고받도록 수정했었는데, Controller 내부에서만 사용하는 값을 Dto로 전달받아 사용하다보니
명확한 방법이 아닌 것 같아 의문점으로 남아있는 상태입니다..!

2022-02-14 10:01 UTC, sure-why-not commented on src/test/java/racingcar/RacingServiceTest.java
> +		assertThat(carCount).isEqualTo(2);
그렇네요 🥶  삭제 반영했습니다!!

2022-02-14 10:14 UTC, sure-why-not commented on src/main/java/racingcar/repository/CarRepository.java
> +	public List<Car> findCars() {
큰 이유를 가지고 List 인터페이스를 노출시킨 것은 아니었는데,
해당 방법이 좋은 방법이라는 것을 에단 덕분에 알게 되었네요!

제가 파악해본 장점은 
LikedList<Car> cars = findCars();
ArrayList<Car> cars = findCars();
와 같이 자바의 다형성을 통해 하위 타입들을 갈아끼워 사용할 수 있기 때문이라고 생각이 듭니다.

그런데 단점은 제가 서칭을 잘 못하는 것인지 얻지 못했는데 ...ㅠㅠ 혹시 알고 계시다면 여쭤보고 싶습니다...!! 😃

2022-02-14 13:00 UTC, Laterality commented on src/main/java/racingcar/repository/CarRepository.java
> +	public List<Car> findCars() {
"`List` 인터페이스에 선언된 메서드만 사용할 수 있다"정도를 단점으로 뽑을 수 있겠네요. 인터페이스의 구현체는 더 많은 기능(메서드)을 제공할 수도 있는데, 인터페이스로 노출하게 되면 구현체가 제공하는 다른 메서드는 가리는 셈이 될 테니까요.

결과적으로는 단점에 비해 말씀하신 것과 같은 장점이 더 크다보니 가능하다면 인터페이스를 사용하는 편이 좋겠네요.

2022-02-14 13:00 UTC, Laterality commented on src/main/java/racingcar/domain/Car.java
> +	}
말씀하신 것과 같은 장점들이 있다보니 종종 사용하게 되는데요. 사용자의 입장에서는 생성자를 통해 객체를 생성하는 방법과 정적 팩토리를 통해 객체를 생성하는 방법을 혼용하게 되면 혼란스러울 수 있으니 객체 생성 방식을 어떻게 제공할 것인지에 대해서만 명확한 기준을 잡으시면 좋겠습니다.

추가로 궁금한 점인데요. "반환 타입의 하위 타입 객체를 반환할 수 있는 점"은 객체 지향 원칙(SOLID) 중 DIP를 위반하는 경우가 아닐까 하는 생각이 들었는데, 다른 의미였을까요?

2022-02-14 13:00 UTC, Laterality commented on src/main/java/racingcar/validator/Validator.java
> +public class Validator {
검증하는 역할을 나누셨네요 👍 

DTO에 관해서는, "DTO가 필요한가?"를 고민해보시면 좋겠습니다. DTO를 사용하지 않은 경우(primitive type으로 값을 전달하는 경우) 어떤 문제가 있는지 이해하고 DTO가 그 문제를 해결할 수 있다면 사용해볼 수 있겠습니다.
그렇지 않은 경우, DTO를 쓰는 게 왠지 맞는 것 같은데 누가 "왜 썼는지" 물어봤을 때 마땅한 대답이 떠오르지 않는다면 굳이 사용할 필요는 없다고 생각합니다.

2022-02-14 13:00 UTC, Laterality approved these changes
안녕하세요. 

코멘트 드린 부분에 대해 많이 고민하신 것이 느껴지네요. 도움이 됐으면 좋겠습니다 🙏 

질문 주신 부분에 대해서는 코멘트 남겨드렸으니 참고 부탁드립니다.

이번  MR은 이만 머지할게요. 고생하셨고 다음 미션도 잘 부탁드려요!

2022-02-14 13:01 UTC, merged