[1단계 - 자동차 경주 구현] 코린(유현지) 미션 제출합니다.
woowacourse/java-racingcar pull request #263
Opened 2022-02-11 03:32 UTC by hamcheeseburger

안녕하세요. 첫 PR이네요! 잘 부탁드립니다! 😊

미션을 진행하면서 가장 고민이 많았던 부분이 두 가지 정도 되었는데요. 아래에 정리해 보겠습니다.

### 책임의 범위

RacingCar의 move() 라는 메소드에서 이루어져야 할 책임의 범위가 조금 헷갈리더라고요. 

현재 저의 코드에서는 move()가 호출되면 RacingCar의 position 값이 무조건 증가하는 것으로 구현을 하였습니다. 그런데 저의 페어인 오리는 아래의 코드와 같이 RacingCar의 move()에서 position을 증가할지 말지를 결정하는게 좋지않겠냐는 입장이었어요! 

```java
public int move(boolean command) {
		if(command) {
				return ++position;
		}
		return position;
}
```

이렇게 책임의 범위가 헷갈릴 때는 어떤 기준을 잡는 것이 좋을까요?

### Random 값 생성에 대한 테스트

‘Random값이 4 이상이면 자동차가 전진한다.’ 라는 테스트를 만들고 싶었는데, Random 값을 생성하는 부분을 제가 직접적으로 제어할 수가 없어서 도저히 방법이 생각이 안나더라구요.

그래서 아래와 같이 parameter로 무조건 자동차가 전진할 수 있는 랜덤값의 범위를 지정하여 테스트를 하려고 했는데, 너무 테스트를 위한 코드를 만드는 것이 아닌가라는 생각이 들었습니다.

```java
public int generateRandomNumber(int start, int end) {
		// start 부터 end 까지의 범위에 해당하는 랜덤값을 생성하여 반환
		// ...
}
```

이러한 상황에서는 어떤 방법으로 테스트를 할 수 있을까요? 또한 테스트를 위한 프로덕션 코드를 만드는 것이 의미있는 일 일까요?

페어프로그래밍과 TDD 개발이 처음인지라 페어인 오리에게 많은 도움을 받은 것 같습니다!! 페어와의 대화를 통해 갇혀있던 생각이 점차 열리는 느낌이었어요! 신기하고 재밌는 경험이었습니다 🙂 🙂

2022-02-11 12:49 UTC, hongbin-dev reviewed
안녕하세요 코린. 리뷰어 앨런입니다. 반갑습니다!

페어프로그래밍을 처음 접하셨다니, 많은 고민을 하고 코드를 작성하신게 보입니다!

작성하신 코드에 몇가지 피드백 남겨봤습니다 확인해주세요 🙂

2022-02-11 12:49 UTC, hongbin-dev commented on src/main/java/racingcar/controller/RacingCarDto.java
> +    }
```suggestion
    private RacingCarDto(String name, int position) {
        this.name = name;
        this.position = position;
    }

    public static RacingCarDto from(RacingCar racingCar) {
        return new RacingCarDto(racingCar.getName(), racingCar.getPosition());
    }
```
정적팩토리메소드로 객체 생성을 유도하시려면, 객체 생성자를 private으로 막는게 좋을 것 같네요 🙂

2022-02-11 12:49 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
생성자로 전달받은 name이 null 혹은 empty string이 올 수 있을 것 같은데요.
이 부분도 고려해주시면 좋을 것 같아요!

2022-02-11 12:49 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
이 메서드가 public으로 열린다면 'RacingCar은 내부상태에 position상태를 갖고, int값을 갖고 있다' 가 예측 가능해보이는데요. 이 부분에서 캡슐화가 깨졌다고 생각해요. 

`int position` 말고 다른 비교할 수 있는 방법은 없을까요?

2022-02-11 12:49 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
move가 두가지 역할을 하는 것 같아요 😶
- 포지션을 이동한다
- 증가된 포지션을 반환한다

2022-02-11 12:50 UTC, hongbin-dev commented
### 책임의 범위
명확한 기준이라고 함은 말씀드리기가 어렵네요😶 

요구사항에 집중하고, 각 책임을 갖는 객체들을 나눈 후 어디까지의 책임을 갖을지 경계를 나누는게 좋을 것 같아요. 거기에서 객체의 이름도 중요하다고 생각합니다.

현재 랜덤값을 구해주는 클래스를 만들어주셨는데요.

단순 RandomGenerator라는 이름을 봤을 때 ‘차량을 움직이는거에 관여하는게 맞을까? 단순 랜덤값만 던지지않을까?’ 라는 생각이 들었어요.


### Random 값 생성에 대한 테스트
해당 부분을 추상화하면 테스트를 하기 편할 것 같아요. 가령 인터페이스를 활용한다면 해당 부분의 테스트코드와  RandomGenerator를 사용하는 클래스도 테스트 가능해보입니다!


궁금하신 점 있으시면 comment나 DM으로 편하게 질문주세요. 감사합니다 🙂

2022-02-11 15:01 UTC, hongbin-dev requested changes
안녕하세요 코린. 리뷰어 앨런입니다. 반갑습니다!

페어프로그래밍을 처음 접하셨다니, 고민하고 코드를 작성하신게 보입니다!

작성하신 코드에 몇가지 피드백 남겨봤습니다 확인해주세요 🙂

2022-02-13 15:44 UTC, hongbin-dev requested changes
코린! 피드백 반영하신 거 확인했습니다 
추가로 의견 남겨봅니다 🙂

2022-02-13 15:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
`checkCarsEmpty()`이 부분은 객체 생성시점에 검증하는게 어떨까요?
승자를 구하는 시점에 에러가 발생하면 피드백이 너무 느릴 것 같다는 생각이 드네요.

2022-02-13 15:44 UTC, hongbin-dev commented on src/test/java/racingcar/domain/RacingCarsTest.java
> +    }
👏

2022-02-13 15:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCarCommander.java
> +    }
RacingCarCommander를 인터페이스로 분리했군요 💯

2022-02-13 15:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
마이너이슈지만 메서드가 **순서에 의존적**이네요.
checkNameLength에서는 가벼운 널체크도 진행하면 좋을 것 같네요 🙂

2022-02-13 15:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
매개변수 boolean 타입이 `command`라는 이름이 때문일까요? 코드가 조금 모호하네요.

```suggestion
    public void move() {
            position++;
    }
```
이런 형태를 갖고, 도메인를 호출하는코드에서 조건을 분기하는 건 어떻게 상각하세요?

2022-02-13 15:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
객체를 비교하기위한 인터페이스 `Comparable`를 구현해보는 건 어떨까요? 

오라클 docs [https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html)

2022-02-13 15:44 UTC, hongbin-dev commented on src/test/java/racingcar/domain/RacingCarTest.java
> +    }
👍

2022-02-14 01:59 UTC, hamcheeseburger commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
아래와 같이 변경하는 것도 메서드가 순서에 의존적인 걸까요??
```java
    public RacingCar(String name) {
        validateRacingCarName(name);
        this.name = name;
    }
    
    private void validateRacingCarName(String name) {
        isEmpty(name);
        checkNameLength(name);
    }
    
    private void isEmpty(String name) {
        if (name == null || name.isEmpty()) {
            throw new IllegalArgumentException("자동차 이름은 비어있을 수 없다.");
        }
    }

    private void checkNameLength(String name) {
        if (name != null && name.length() > NAME_MAX_LENGTH) {
            throw new IllegalArgumentException("자동차 이름은 5자를 초과할 수 없다.");
        }
    }
```

순서에 의존적이지 않으려면 `isEmpty()`와 `checkNameLength()`가 같은 함수 내에서 동작하는 방법밖에는 생각이 안나네요..🥲

2022-02-14 12:44 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCar.java
> +    }
네! 제가 생각한 방향입니다 👏

2022-02-14 13:01 UTC, hongbin-dev approved these changes
안녕하세요 코린!
처음에 구현과 테스트코드를 잘 작성해주셔서 더 피드백 드릴게 없네요 👏
코멘트달린 마이너이슈들은 다음미션에서 반영해주세요~

2022-02-14 13:01 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
Comparable도 구현했으니 Stream.max()를 통해서 최고점수를 구해볼까요?

[https://www.geeksforgeeks.org/stream-max-method-java-examples/](https://www.geeksforgeeks.org/stream-max-method-java-examples/)
[https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html)

2022-02-14 13:01 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
0이라는 의미가 어떤 뜻인지 알기 어렵네요. 상수로 포장하면 좋을 것 같습니다 🙂

2022-02-14 13:01 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
이 부분은 테스트에서만 사용한다면 지우는게 좋겠네요

2022-02-14 13:01 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
java 내에서 getter라는 네이밍은 관습상 객체의 상태를 꺼내는 느낌이 많이드는데요.
작성해주신 getRacingCars()라는 네이밍은 `RacingCar`라는 객체를 리턴해줄 것 같은 네이밍인데, RacingCarDto를 던지고 있네요.
이 부분은 수정하고 넘어가면 좋을 것 같네요.

2022-02-14 13:03 UTC, merged