[1단계 - 자동차 경주 구현] 릭(나일성) 미션 제출합니다.
woowacourse/java-racingcar pull request #273
Opened 2022-02-11 05:23 UTC by nailseong

안녕하세요!!
페어와 함께 미션 진행하면서 고민했던 부분들 답변 받고 싶어서 정리해보았습니다. 

1. MockRandomGenerator를 추상 클래스로 만들어서 상속받아 CarTest, CarsTest에서 사용했는데, 이런 방식으로 Mock을 사용하는 것이 괜찮을지? 더 좋은 방법이 있을까요?

2. Mockito 라이브러리 도움 없이도 가짜 객체를 만들거나 임의의 결과를 낼 수 있는 방법이 있을까요?

3. static 메서드가 메모리를 일반 메서드보다 과하게 사용할 수 있을 것 같은데 static을 최소화하는 것이 좋을까요?

4. static으로 Scanner를 생성하여 사용해 보니 전체 테스트를 돌릴 때, NoSuchElementException이 터지며, No line found라는 메시지가 발생했습니다. 
그래서 Console 객체를 만들어 Reflection 접근하여 Scanner가 없거나 닫혔을 때 scanner를 생성하여 반환하는 클래스를 만들었는데, 이때 Reflection을 사용하는 것에 대해 어떤 생각을 갖고 계신지 궁금합니다.

2022-02-12 09:15 UTC, lxxjn0 requested changes
릭, 안녕하세요!!! 이번에 릭의 코드 리뷰를 맡게 된 스티치라고 합니다 😄 

이번에는 1단계 미션의 목적에 맞게 리뷰를 진행하였어요. 그래서 MVC 패턴과 관련된 관점에 대한 리뷰는 2단계에서 진행하려고 합니다. 이 부분 확인해주시면 좋을 것 같네요 :)

그리고 코드 리뷰는 정말 말 그대로 리뷰입니다. 제가 릭의 코드를 보고 가진 생각을 적은 것이죠!! 그래서 저의 말이 무조건 맞다고 생각하시지 말고 만약 릭의 생각과 다른 점이 있거나 궁금한 점이 있다면 언제든 질문해주세요!!
코드 리뷰로 남기기 어려운 질문이라면 DM으로도 가능하니 부담가지지 말고 리뷰어를 잘 써먹어(?)주세요 👍🏼 

질문을 답하기에 앞서 '이게.. 정말 Level 1 첫번째 미션이 맞나?' 싶은 생각이 들 정도로 잘 구현해주셨어요 💯
테스트도 꼼꼼히 잘 짜주셨고 자바에 대한 이해도도 높으신 것 같네요!! 

릭의 관점이 아닌 저의 관점으로 보여진 부분들에 대해 코멘트 남겨두었으니 참고 부탁드릴게요!!

그리고 릭이 남긴 질문에 대한 답변입니다!

1. 우리가 작성한 코드를 테스트 하는 방법은 여러가지가 있는데, 그 중에서도 Mocking은 일반적으로 많이 사용되는 방법 중 하나입니다.
릭이 Mocking을 한 RandomGenerator의 경우, 임의의 값을 만들어내는 역할을 하기 때문에 기존의 RandomGenerator를 사용하며 테스트하기는 매우 어려울 것입니다(당연히 일관적인 테스트 결과를 만들기도 어렵고요). 그래서 이런 객체를 Mocking 하는 새로운 객체를 만들고, 이를 테스트에 활용하는 것도 매우 좋은 방법이고요 👍 
하지만, 이번에 RandomGenerator를 Mocking을 하기 위한 방식(방법)으로 Mockito 라이브러리를 활용한 것이 좋은 방식인가에 대해서는 의문이 들었습니다. 
우리는 간단한 클래스의 경우 테스트를 위한 Mock 객체를 직접 만들어서 테스트를 진행하지만, 프로젝트가 커지면서 코드의 양이 늘고 의존성이 점점 늘어나면 직접 Mock 객체를 만들어 Mocking을 하면서 테스트를 하기란 쉽지 않습니다. 한 클래스를 테스트하기 위해 만들어야 하는 Mock 객체가 몇 배나 많다면 오히려 주객전도가 되어버릴 수도 있죠. 테스트 또한 비용이기 때문에 우린 이 비용을 줄여야하고요.
그런 상황에서 Mockito 라이브러리는 우리가 테스트에서 비용을 줄일 수 있도록 도와주는 좋은 도구이고요. 하지만 여기서 가장 중요한 것은 Mockito 라이브러리를 사용하지 않더라고 우리가 테스트 가능한 구조로 만들 수 있다는 것이 전제되어야 합니다. 그러한 이해가 바탕이 되어야지 Mockito 라이브러리를 보다 잘 사용할 수 있을테니깐요!!
그런 의미에서 Mock을 사용하려는 릭의 의도는 매우 좋고 바람직하다고 생각합니다. 그러나 Mockito 라이브러리에 의존하지 않고 직접 Mocking 하는 방법을 조금 더 고민해보면 좋을 것 같아요 🙂
2. 위 1번의 질문에 이어지는 질문일 것 같네요!!! 저도 릭과 마찬가지로 예전에 동일한 고민을 했었어요. 그래서 [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/) 이 글을 한번 참고해보면 좋을 것 같습니다 👍 (넵!! 제가 쓴 글이에요 😎 )
3. static 메서드는 인스턴스 메서드와 사용하는 목적이 다르다고 생각하기 때문에 메모리 관점이 아닌 다른 관점으로 고민해보면 좋을 것 같아요. 물론 메모리 관점에서 고민이 나쁘다는 것은 절대 아닙니다. 좋은 개발자는 릭이 한 로우레벨의 고민도 함께 할 수 있어야 하죠!! 그러나 지금 단계의 미션에선 보다 중요한 부분(클래스의 책임, 메서드의 책임을 어떻게 하면 더 잘 분리할 수 있을 것인가)에 집중하여 개발하면 릭에게 더 도움이 많이 될 것 같네요!!
그래도 릭의 궁금증에 대한 해소를 도와드려야 하니, 저의 답변보다 더 좋은 글을 소개해드릴게요!! [정적 메소드, 너 써도 될까?](https://tecoble.techcourse.co.kr/post/2020-07-16-static-method/) 이 글을 한번 읽어보시면 좋을 것 같아요 👍🏼 
4. 이 부분도 지금은 고민하지 않아도 될 것 같아요!! 이번 미션에서 목표를 가지는 부분들에 대한 고민들을 집중적으로 하는 것이 릭에게도 더 많이 도움이 될 것 같고요!! 하지만, 이런 디테일한 고민들이 릭을 좋은 개발자로 성장시켜 주는 재료임은 틀림없습니다!! 그래서 제가 이 부분은 추가로 더 확인해보고 추가로 코멘트 남기도록 할게요!! 😎

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/calculator/StringCalculator.java
> +    public static final String CUSTOM_FINDER = "\n";
접근 지정자에 대해서 고민해보면 좋을 것 같아요!!

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/calculator/StringCalculator.java
> +    private static String CUSTOM_START = "//";
변수의 사용 목적은 상수로 보이는데 final을 붙이지 않은 이유가 있을까요?

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException(NOT_VALID_DELIMITER);
예외는 발생 자체도 의미가 있지만 어떠한 예외 클래스인지를 통해서도 의미를 파악할 수 있어요.
RuntimeException이 아닌, 현재 context에서 보다 어울리는 예외를 한번 고민해보는 것도 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/README.md
> +output => 안내 메시지
릭이 작성해 준 README는 미션에서 요구한 '구현할 기능 목록'으로 보긴 어려운 것 같아요.
누군가가 릭의 코드를 읽기 전에 '프로그램의 목적을 달성하기 위해서 이러한 기능들을 구현했구나'라고 이해할 수 있는 문서면 좀 더 좋을 것 같네요 😄

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/RacingCar.java
> +        RacingController racingController = new RacingController();
MVC 패턴에 대한 피드백은 2차 리팩토링 미션의 코드 리뷰에서 남겨드릴게요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/controller/RacingController.java
> +    public void play() {
코드 전체적으로 공백(빈 라인)의 사용이 적은 것 같아요.

공백은 내가 작성한 코드의 가독성을 높여주고 문맥(의도)을 이해하기 쉽도록 도와주는 역할을 하기도 합니다. 우리가 글을 읽을 때 적절한 띄워쓰기와 단락이 구분되어 있는 글이 읽기 쉽고 작성자의 의도를 파악하기 쉬운 것 처럼요 :)

릭도 작성한 코드에 적절한 공백을 사용하면서 본인의 의도를 코드에 더 잘 보여질 수 있도록 하면 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/controller/RacingController.java
> +    private String[] getRightName() {
코드 전반적으로 배열을 많이 사용하시는 것 같아요. 

자바에서 제공하는 List는 배열보다 더 사용하기 쉽고 많은 기능들을 제공해줍니다. 자바에서 다양한 자료구조를 사용하기 쉽도록 도와주는 프레임워크를 JCF(Java Collection Framework)라고 하는데요, 한번 공부해보면 좋을 것 같네요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/controller/RacingController.java
> +        }
현재 코드는 만약 정상적인 입력이 아닐 경우 자기 자신(`getRightName()`)을 다시금 호출하고 있어요.
혹시... 릭에게 나쁜 마음을 품은 사람이 수백수천번, 아니 수천만번을 해당 로직에서 비정상적인 입력을 한다면 어떻게 될까요? 재귀가 수천만번 반복이 된다면???

이 부분은 이번 미션의 포인트는 아니지만 릭이 한번 재밌게 고민해보면 좋을 부분이라 생각해서 코멘트 남길게요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
> +    final private String name;
final과 private의 위치가 바뀐 것 같아요!! 자바 코드 컨벤션을 한번 확인해주세요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
> +    public String toString() {
`toString()` 함수의 목적을 한번 공부해보면 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
> +    }
만약 누군가가 해당 public 메서드를 `car.isMaxPosition(10)` 이렇게 사용했다고 생각해볼게요. 
10이 정말 maxPosition일까요? 만약 그렇지 않다면 해당 `isMaxPosition()` 메서드는 잘못된 역할을 하는 걸까요? 우리가 이런 의심을 하지 않으려면 메서드 명을 어떻게 하면 좋을까요?

메서드 이름과 실제 메서드의 행위가 정말로 동일한지 한 번 생각해보면 좋을 것 같아요!!

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
> +    }
이번 미션에서 자동차는 숫자가 4 이상이면 전진을, 그렇지 않으면 정지를 합니다.

그런데 갑자기 자동차가 숫자가 5 이상이면 전진을 한다면 어떻게 될까요? 더 나아가 갑자기 "전진"이라는 문자열일 경우에만 자동차가 전진해야 한다고 한다면 어떡해야 할까요?

여기 Car 객체는 본인의 위치를 기억하면서 이를 변경하는 책임만 가지면 될까요? 아니면 이처럼 자동차가 어떤 경우(조건)에 이동을 해야하는지 비즈니스에 대한 책임도 가져야 할까요?

구현해주신 Car가 어떠한 책임을 가져야 하는지, 그리고 만약 어떤 요구사항이 변경이 되었을 때, 그때 Car를 바꿔야 할 지, 아니면 다른 로직을 바꿔야 할 지에 대해 한번 고민해보면 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
> +    private final List<String> winners = new ArrayList<>();
해당 부분은 Cars의 생성자에게 역할을 주어도 좋을 것 같아요!! 다양한 생성자를 활용한다면 보다 유연하게 코드를 작성할 수 있을 거에요 😄

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
> +    }
이 부분도 생성자를 통해서 좀 더 명시적이고 유연하게 해결해보면 좋을 것 같아요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
> +    }
일급 컬렉션 Cars를 만들고 이를 활용한 부분 정말 굿입니다!! 💯

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
> +    }
접근 지정자가 public으로 되어 있는데 실제 사용하는 곳은 Cars, CarsTest 두 곳에서만 사용하고 있네요. 이 부분도 한번 고민해보면 좋을 것 같아요.

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
> +    }
`getWinners()` 메서드의 코드을 읽으면 가장 먼저 나오는 메서드가 `getMaxPosition()`입니다. 그러나 `getMaxPosition` 메서드는 `getWinner` 메서드와 조금 멀리 떨어져있어요.

클린 코드에서 좋은 코드는 마치 신문처럼 읽히는 코드라는 말이 나옵니다. 다른 코드에서 언제 사용되는지, 그렇다면 어디에 위치해두어야 읽기 편할 지도 한번 고민해보면 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
> +    }
추가로 이런 관점은 특히 public 메서드이기 떄문에 더욱 중요한 부분일 수 있어요. private 메서드라면 해당 클래스 내부에서만 사용되기 때문에 우리가 그 의도를 제한할 수 있습니다. 하지만 public 메서드는 누구든 사용할 수 있는 메서드라 의도를 제한하기 어렵습니다. 이런 관점도 한번 같이 고민해보면 좋을 것 같네요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/utils/RandomGenerator.java
> +public class RandomGenerator {
해당 코드는 위에 릭이 남겨준 질문과 연결되는 부분이라 추가적인 코멘트는 남겨두지 않을게요 :)
닉이 고민해보고 수정해주면 그때 다시 한번 확인해보도록 하겠습니다!!

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/utils/Validator.java
> +    }
이 부분도 String 객체의 적절한 메서드를 활용한다면 향상된 for문으로 개선이 가능할 것 같아요. 그러면 하위의 메서드들도 보다 간결하게 구현할 수 잇을 것 같아요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/main/java/racingcar/utils/Validator.java
> +    }
해당 코드를 보면 각각의 메서드에서 모두 for문을 반복하고 있어요. 가독성도 중요하지만 성능을 개선하면서 가독성도 잡을 수 있다면 일석이조이지 않을까요?
릭이 한번 고민해보고 개선해보면 좋을 것 같아요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/test/java/calculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
테스트를 꼼꼼하게 잘 짜주었네요 💯

2022-02-12 09:15 UTC, lxxjn0 commented on src/test/java/racingcar/domain/CarTest.java
> +public class CarTest extends MockRandomGenerator {
이 부분도 위의 질문에 대한 답변을 보고 릭이 고민 후 개선해보면 좋을 것 같아요 :)

2022-02-12 09:15 UTC, lxxjn0 commented on src/test/java/racingcar/utils/MockRandomGenerator.java
> +public abstract class MockRandomGenerator {
해당 코드도 마찬가지로 질문에 대한 답변을 확인 후 개선해보시면 좋을 것 같아요 👍🏼

2022-02-12 09:15 UTC, lxxjn0 commented on src/test/java/racingcar/view/InputViewTest.java
> +    }
해당 테스트 코드를 보면 InputView에서 Validator의 로직에 대한 테스트까지 이뤄지고 있어요.

앞서 Validator의 테스트 코드에서 검증이 된 부분인데도 중복으로 검증이 필요하네요. 이런 시점에서 릭이 한 번 의심해보고 고민을 해보면 좋을 것 같아요. 아래처럼 말이죠 ㅎㅎㅎ
> Validator가 변경이 된다면 InputView의 테스트 코드도 수정을 해야하는데? 이게 맞을까? InputView가 정말 가져야 할 역할은 뭐지?

2022-02-12 09:17 UTC, lxxjn0 commented on src/main/java/racingcar/README.md
> +output => 안내 메시지
추가적으로 구현할 기능 목록을 꼼꼼히 작성한다면 그에 맞게 commit 단위를 가져가기도 좋을 것 같아요 :)

2022-02-12 16:17 UTC, lxxjn0 commented
추가로 아래의 글들도 이번에 읽어보면 도움이 많이 될 것 같아서 첨부합니다 :)
- [좋은 코드를 위한 자바 변수명 네이밍](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/)
- [좋은 코드를 위한 자바 메서드 네이밍](https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/)

2022-02-13 04:24 UTC, nailseong commented on src/main/java/racingcar/domain/Car.java
> +    public String toString() {
`toString()` 함수는 디버깅, 로깅을 편하게 하기위해서 주로 쓰이는것 같아요.
지금처럼 view 에서 사용할 목적이아니라 `Car(name=rick, position=3)` 이런 형식의 String을 반환하도록 변경하는게 좋을것 같아요.

2022-02-13 08:27 UTC, nailseong commented on src/main/java/racingcar/utils/Validator.java
> +    }
for문에서 또 다른 메서드를 호출하고 있고, 그 메서드들은 for문에서만 사용되어서 2개의 메서드를 합치는 식으로 개선해 보았습니다.
- 메서드를 2번 호출하지 않고 1번만 호출한다.
- 메서드가 2개에서 1개로 줄어들었다.

이러한 점을 개선할 수 있었는데요.

스티치가 이야기한 의도를 잘 이해했는지 헷갈려서 혹시 잘 못 이해했다면 코멘트 남겨주세요 🤨

2022-02-13 15:55 UTC, lxxjn0 commented
추가로 intellij를 사용하고 계신다면 [woowacourse-docs > Java Style Guide](https://github.com/woowacourse/woowacourse-docs/tree/master/styleguide/java) 문서의 style.yml 파일을 intellij에 적용해보면 좋을 것 같아요!!
intellij에 style.yml을 적용하는 방법은 [[IntelliJ] Code Style(Google Style) 적용하기](https://tychejin.tistory.com/334) 글을 참고하면 될 것 같아요!!

IDE를 잘 활용하는 것 또한 개발 실력을 향상시키는 데 많은 도움이 됩니다!!

2022-02-14 13:48 UTC, nailseong commented
스티치!! 피드백 반영해서 수정해보았어요 🤨
이번에 진행하면서 객체가 책임을 어디까지 가져야 하는지를 많이 고민했어요.
특히 `Car`의 이동 조건에 대한 비즈니스 로직을 전략 패턴을 활용해서 `Car`에서 분리해서 `MoveStrategy`클래스를 만드는 데 고민을 많이 했어요.
이 부분에 대해 스티치 의견이 듣고 싶어요!! 🧐

2022-02-14 16:17 UTC, lxxjn0 approved these changes
릭, 리뷰 반영하느라 수고 많았어요 👍🏼 

저의 코멘트를 찰떡같이 알아듣고 코드를 멋지게 개선해주셨군요!! 릭의 실력이 일취월장 하시는 모습이 보여서 뿌듯하네요!! 😄 

릭이 추가로 고민해보고 반영해보면 좋을 만한 부분들에 대해서 코멘트 남겨두었습니다!! 해당 부분은 2단계 미션에서 반영해보면 좋을 것 같아요!!! 이번 1단계 미션은 여기서 머지하도록 할게요!! 

수고 많으셨습니다 💯

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/README.md
> +## 구현 기능 목록
상세한 기능 목록 작성 👍🏼

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
>      public String toString() {
`toString` 메서드를 원래의 목적에 맞게 작성하셨군요!! 👍🏼

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Car.java
>      }
해당 코드를 조금 잘 바꿔본다면 car의 멤버 변수로 strategy를 관리하지 않아도 되지 않을까요??

클래스의 멤버 변수는 해당 객체의 존재 의미를 나타내는 값들입니다. 그런 관점에서 Car들이 각각 이동 전략을 가지고 있도록 하는게 맞는지 한번 고민해보면 좋을 것 같아요!!

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
>      }
위에서 만들어 둔 `Cars(final List<Car> cars)` 생성자를 사용한다면 이 코드를 좀 더 간결하게 작성할 수 있지 않을까요??
그리고 추가적으로 정적 팩토리 메서드에 대해서도 한번 찾아보시면 좋을 것 같아요 :)

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Cars.java
>      }
적어도 외부에서 cars 리스트에 값의 추가, 삭제는 막을 수 있도록 unmodifiableList를 사용하였네요!!
이러한 사소한 디테일이 코드를 보다 안전하고 신뢰도 있게 만들어주죠!! 💯

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Name.java
> +public class Name {
Name 인스턴스를 만들어서 이름의 유효성 검증에 대한 부분을 Name을 생성하는 시점에 처리해줬군요!!! 객체 지향적인 설계의 장점을 최대한 가져려고 노력한 모습이 보입니다!! 👍🏼

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/TrialCount.java
> +public class TrialCount {
마찬가지로 시도 횟수를 객체 지향적으로 만들어서 유효성 검증을 해결하였군요!! 👍🏼

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Winners.java
> +        int max = 0;
별거 아닌 부분일 수 있지만 변수명을 max가 아닌 maxPosition으로 좀 더 디테일하게 작성해준다면 코드를 이해하기 좀 더 편리할 것 같아요!!

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Winners.java
> +                .collect(Collectors.toList());
스트림을 활용하여 코드를 간결하게 만들었군요!! 👍🏼

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/Winners.java
> +                .map(car -> car.getName())
이 부분은 메서드 참조를 사용할 수 있을 것 같아요!!

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/movestrategy/MoveStrategy.java
> +public interface MoveStrategy {
MoveStrategy보다는 MovingStrategy가 문법,의미적으로 좀 더 적절한 것 같은데 어떤가요?

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/domain/movestrategy/RandomMoveStrategy.java
> +    }
해당 함수를 통해서 이동 전략을 관리한 부분 정말 좋습니다 👍🏼 

만약 제가 메서드 명을 좀 더 명확하게 지어본다면 `canMoveForward`가 어떨까 싶네요!! `canMove`도 좋지만 단순히 '이동한다'는 단어로는 차가 앞으로 가는지, 뒤로 가는지는 표현하기엔 어려울 것 같아요!!

2022-02-14 16:17 UTC, lxxjn0 commented on src/main/java/racingcar/view/InputView.java
> +    public static TrialCount insertNumber() {
InputView 클래스는 입력을 처리하는 책임을 지니고 있을 것 같아요!! 입력을 처리하는 책임을 가지는 클래스에서 TrialCount를 생성하는 책임까지 지니고 있어야 할까요? 

클래스가 가져야 하는 책임을 적절히 관리한다면 보다 응집도 있는 코드를 작성할 수 있을 것 같아요 :)

2022-02-14 16:17 UTC, lxxjn0 commented on src/test/java/racingcar/domain/movestrategy/MovableMoveStrategy.java
> +public class MovableMoveStrategy implements MoveStrategy {
테스트를 위한 mock 객체를 생성해서 테스트한 점 굿입니다 👍🏼 

릭에게 조금 더 고민해 볼 수 있는 포인트를 준다면, MovableMoveStrategy, StoppableMoveStrategy를 둘 다 생성하지 않고 처리해보면 어떨까요?? 아래 글을 한번 읽어보면 아이디어를 얻을 수 있을 것 같아요 :)

https://tecoble.techcourse.co.kr/post/2020-04-28-test-without-method-change/

2022-02-14 16:17 UTC, merged