[1단계 - 자동차 경주 구현] 썬(윤선용) 미션 제출합니다.
woowacourse/java-racingcar pull request #280
Opened 2022-02-11 06:21 UTC by syoun602

안녕하세요!! 첫 코드 리뷰라 그런지 떨리네요!
부족하지만 보내주신 피드백을 바탕으로 빠르게 성장하겠습니다!
잘 부탁드립니다!!

다음은 페어와 함께 고민했던 사항이나 개인적인 궁금증을 담아 보았습니다!

---

1. 대부분의 매직 넘버나 상수는 static final을 이용해 상수화하였는데, InputValidator의 오류 문구는 따로 상수 처리하는 것이 더 직관적이지 못한 것 같아서 그대로 두었는데, 혹시 현업에서는 어떠한 방식을 더 선호하나요?

2. GameController에서 필드에 Cars와 trialnum을 따로 생성하였는데, 이것이 MVC 모델 관점에서 보면 Controller가 너무 많은 책임을 지고 있는 것인가요?

3. 테스트에 자동차_전진_확인()이 있는데, 처음에는 랜덤 값을 지정해서 넣어주고 해당 자동차의 position을 확인하고자 하였으나, 테스트 코드에서 랜덤 값을 지정해주는 방법을 찾지 못하여 야매(?) 방식을 이용했는데, 더 좋은 방법이 있었을까요?

지금까지 생각난 질문은 다음과 같습니다! 더 생각난다면 추가로 작성하겠습니다. 감사합니다!

2022-02-11 14:18 UTC, ksy90101 requested changes
안녕하세요 썬 리뷰어 럿고입니다.
작성하신 코드 잘 봤습니다 :) 고생 많으셨습니다. 💯
피드백을 남겼으니 확인해주고 요청 주시면 감사하겠습니다.
질문이 있다면 언제든지 남겨주거나 DM주시면 감사하겠습니다

1. 대부분의 매직 넘버나 상수는 static final을 이용해 상수화하였는데, InputValidator의 오류 문구는 따로 상수 처리하는 것이 더 직관적이지 못한 것 같아서 그대로 두었는데, 혹시 현업에서는 어떠한 방식을 더 선호하나요?
네 저도 오류 문구까지는 상수로 처리할 필요가 없다고 생각합니다. 저같은 경우에도 오류 메시지와 같은 부분은 리터럴로 작성을 해두는 방식을 취하고 있습니다.

2. GameController에서 필드에 Cars와 trialnum을 따로 생성하였는데, 이것이 MVC 모델 관점에서 보면 Controller가 너무 많은 책임을 지고 있는 것인가요?
이건 개인적으로는 본인이 가져하는 책임보다 더 많은 책임을 가지고 있다고 생각이 드는데요. 이 부분은 피드백을 받고 수정하시면 자연스럽게 각자의 책임으로 이동될거라고 생각합니다 :) 

3. 테스트에 자동차_전진_확인()이 있는데, 처음에는 랜덤 값을 지정해서 넣어주고 해당 자동차의 position을 확인하고자 하였으나, 테스트 코드에서 랜덤 값을 지정해주는 방법을 찾지 못하여 야매(?) 방식을 이용했는데, 더 좋은 방법이 있었을까요?
관련 부분은 리뷰에 남겨두었습니다 :) 참고해주세요!

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/model/Car.java
> +    private int position;
상수와 필드는 분리를 하는게 더 가독성 측면에서 좋은거 같습니다 :) 
```suggestion
    public static final int MINIMUM_POSITION = 0;
    public static final int MOVE_FORWARD = 4;
    
    private final String name;
    private int position;
```

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("입력 값은 숫자여야 합니다.");
더 의미있는 예외인 `NumberFormatException` 이걸로 사용해보시는게 어떨까요?
굳이 메시지를 보지 않아도 예외 클래스 이름만 보고 어떤 예외인지 알수 있을거 같습니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        return numList.stream().mapToInt(Integer::intValue).sum();
한줄에 점 하나씩이라는 개념으로 스트림을 한줄에 하나의 메서드로 처리한다면, 더 가독성은 높아질거 같습니다.
```suggestion
        return numList.stream()
                .mapToInt(Integer::intValue)
                .sum();
```
아울러 아래 사진과 같이 IDE에서 각 연산마다 어떤 값이 return되는지도 확인할 수 있어 더 편리한거 같습니다.

![image](https://user-images.githubusercontent.com/53366407/153602667-bd2ca559-90e1-429d-8021-3d6e7154486a.png)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +    public static Integer sumList(List<Integer> numList) {
List라는 단어는 굉장히 포괄적인 단어인데요.
배열이나 리스트와 같은 복수형인 경우에는 복수 단어를 사용하는 것을 추천드립니다 :)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        if (input == null || input.isEmpty()) {
isEmpty() vs isBlank()의 차이를 찾아보고, 위와 같은 케이스는 어떤 상황이 더 좋은지 생각해보세요 :) 

아울러 이 부분도 메서드로 추출하면 어떤부분을 validate하는지 확인할 수 있을거 같습니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        String regExp = ",|:";
위 문자열을 계속 생성할 필요가 있을까요?
상수로 처리해도 괜찮지 않을까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +            int idx = input.indexOf("\n");
개행은 OS마다 사용하는 값이 다른데요.
예를들어 Unix계열은 "\n"을 사용하지만, MS Window 같은 경우는 "\r\n"을 사용합니다.
이에 맞춰서 Java API에서 `System.lineSeparator()` 이러한 메서드를 지원해주고 있는데요.
한번 찾아보시면 좋을듯 합니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("커스텀 구분자 내에 숫자가 포함되어 있습니다.");
Checked Exception vs UnChecked Exception의 차이를 한번 알아보시고, 현재 코드에서 어떤게 더 좋은지 고민해보시겠어요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        return input.startsWith("//") && input.contains("\n");
"\\" 및 "\n" 모두 매직문자열 입니다 :)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/Application.java
> +public class Application {
Application이름을 어떤 Application인지 명시해서 이름을 지어보면 어떨까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +
이 Class에서만 사용하는 상수라면 접근 제어자를 private으로 하면 어떨까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +        scanner.close();
저는 이렇게 한 메서드에 여러줄이 들어가는 경우에는 개행으로 가독성을 높일수 있을거 같다고 생각이 듭니다.
썬이 생각하시는 대로 어떻게 묶이는게 더 좋게 보이는지 한번 해보시면 어떨까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +        Scanner scanner = new Scanner(System.in);
입력을 받는 책임이 Controller가 맞을까요?
View의 역할은 무엇인지 고민해보시면 좋을듯 합니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +        List<String> carNameList = splitCars(carNames);
List라는 단어보다는 이런 경우에는 복수를 사용하시는걸 추천드립니다 :)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +        List<String> carNameList = Arrays.asList(carNames.replaceAll(SPACE, BLANK).split(COMMA));
`carNames.replaceAll(SPACE, BLANK).split(COMMA)`
여기의 값이 어떤 값인지 맨 처음 봐서는 잘 알기가 힘들거 같은데요.
이 부분을 변수로 빼서 의미있게 이름을 작성해보시겠어요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +    public Cars initCars(List<String> carNameList) {
이 부분도 이 Class에서만 사용할거로 보이는데요.
이 부분도 private으로 접근제어자를 지정하면 어떨까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/model/Car.java
> +    }
저는 아래와 같은 순서로 클래스 내에서 메서드를 선언하는데요. 한번 확인해보시고 재 정렬 해보시겠어요?

```
- constructors first
- static methods next, if there is a main method, always before other static methods
- non static methods next, usually in order of the significance of the method followed by any methods that it calls. This means that public methods that call other class methods appear towards the top and private methods that call no other methods usually end up towards the bottom
- standard methods like toString, equals and hashcode next
- getters and setters have a special place reserved right at the bottom of the class
```

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +    public static final String JOIN_BY_COMMA = ", ";
여기도 해당 클래스에서만 사용한다면 private으로 처리하는게 좋을듯 합니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +                .max(Comparator.comparing(x -> x))
x라는 변수는 굉장히 의미없는 이름이라고 생각이 듭니다. x가 어떤걸 의미하는지 더 명확히 명명을 해주시면 좋을듯 합니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/util/InputValidator.java
> +    public static final int MINIMUM_CAR_NAME_LENGTH = 5;
여기도 해당 클래스에서만 사용한다면 private으로 변경해주세요.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/util/InputValidator.java
> +        if (!carNameList.stream().allMatch(carName -> carName.length() <= MINIMUM_CAR_NAME_LENGTH)) {
carNameList.stream().allMatch(carName -> carName.length() <= MINIMUM_CAR_NAME_LENGTH)

이 부분은 어떤 값을 의미하는걸까요? 이런 경우에는 위에 따로 변수로 빼서 어떤걸 의미하는지 명시해주는게 가독성이 더 좋을거 같아요 :)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/util/InputValidator.java
> +        long distinctNum = carNameList.stream().distinct().count();
스트림은 한줄에 점 하나씩!

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +        Random random = new Random();
메모리에 하나만 올라가면 되지 않을까요?
이 부분도 상수로 정의하면 좋을거 같습니다.

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/view/InputView.java
> +    private static final String INPUT_TRIAL_NUMBER_MESSAGE = "시도할 회수는 몇회인가요?";
해당 부분을 상수로 빼신 이유가 있을까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void 콤마_구분자() {
Junit5부터는 `@DisplayName` 을 지원해주고 있습니다.
이걸 사용하면 문자 인코딩 문제가 없는데요.
혹시 찾아보시고 적용해보실수 잇을까요?

2022-02-11 14:18 UTC, ksy90101 commented on src/test/java/calculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
현재 테스트를 봐도 한 클래스에 많은 테스트가 있다고 생각이 들지 않을까요?
테스트가 많다는 것은 그만큼 책임을 많이 가지고 있거나, 다른 곳에서 테스트 커버를 하지 못했다고 생각이 드는데요.
한번 고민해보시면 좋을거 같습니다 :)

2022-02-11 14:18 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +    }
실제 이부분을 테스트를 어떻게 할 수 있을까요?
이 테스트는 일단 Random이라는 컨트롤 하기 어려운 값이 있기 때문에 어렵다고 생각이 드는데요.
이런 경우에는 `인터페이스로 추상화 하는 방법`을 많이 사용하고 있습니다.
즉, 인터페이스를 하나 만들고 랜덤을 사용해서 돌려주는 구현체 또는 원하는 값을 돌려주는 구현체 두가지를 만들어서 전자는 실제 프로덕션에서, 후자는 테스트에서 사용하는 방법이죠.

한번 고민해보시고 해당 부분도 테스트를 작성해주시면 좋겠습니다!

2022-02-14 05:38 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +    private int position;
✅

2022-02-14 05:39 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        String regExp = ",|:";
✅

2022-02-14 05:41 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +            int idx = input.indexOf("\n");
몰랐던 부분이었는데 앞으로 참고하겠습니다!! 아 근데 해당 줄에서 사용한 것은 커스텀 구분자가 "//" 로 시작해서 "\n"로 끝나야한다는 의미였어서 "\n" 필요하다고 생각됩니다. 다만, 이를 더 명확하게 명시해주기 위해 CUSTOM_SUFFIX로 상수화하였습니다!

2022-02-14 05:42 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        return input.startsWith("//") && input.contains("\n");
✅

2022-02-14 05:44 UTC, syoun602 commented on src/main/java/racingcar/view/InputView.java
> +    private static final String INPUT_TRIAL_NUMBER_MESSAGE = "시도할 회수는 몇회인가요?";
따로 이유없이 작성하였습니다..... 코드 통일화를 위해 한 클래스 내에서만 쓰이는 오류 및 메시지들은 상수처리 하지 않는 것으로 변경하였습니다!

2022-02-14 05:45 UTC, syoun602 commented on src/main/java/racingcar/util/RandomNumberGenerator.java
> +        Random random = new Random();
✅

2022-02-14 05:52 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +
✅

2022-02-14 05:56 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +    public Cars initCars(List<String> carNameList) {
initCars() 는 테스트 코드에서도 사용되고 있어서 public으로 변경하였었는데, 혹시 테스트코드 때문에 접근제어자에 변경이 생기면 안될까요?.... 만약 그렇다면 이를 해결하기 위한 다른 방법이 있을까요?!!

2022-02-14 07:59 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +    public static final String JOIN_BY_COMMA = ", ";
✅

2022-02-14 07:59 UTC, syoun602 commented on src/main/java/racingcar/util/InputValidator.java
> +    public static final int MINIMUM_CAR_NAME_LENGTH = 5;
✅

2022-02-14 08:06 UTC, syoun602 commented on src/main/java/racingcar/util/InputValidator.java
> +        long distinctNum = carNameList.stream().distinct().count();
✅

2022-02-14 08:07 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("입력 값은 숫자여야 합니다.");
✅

2022-02-14 08:10 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        return numList.stream().mapToInt(Integer::intValue).sum();
해당 방식을 이용하면 더욱 직관적일 것 같습니다!! 다만, 제 IDEA 안에서는
![image](https://user-images.githubusercontent.com/67397679/153824747-2f8e8bbf-3690-41f2-a6fa-ede9a875e68d.png)
중간 연산 값들이 표시가 안되고 있는데, 해결 방법이 있을까요?

2022-02-14 08:21 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +    public static Integer sumList(List<Integer> numList) {
넵 좀 더 의미있게 sumNumbers로 변경해봤습니다!

2022-02-14 08:23 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("입력 값은 숫자여야 합니다.");
요구사항에 맞춰서 하다보니 좀 더 명확한 것에 대한 생각을 덜 해본거 같아요!! 이후부터는 예외 클래스만으로도 오류를 알 수 있도록 잘 연관된 예외를 사용해 보겠습니다!

2022-02-14 08:39 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        if (input == null || input.isEmpty()) {
isBlank()를 이용하여 null, "", " " 세 가지 상황에 대한 처리를 할 수 있다는 것을 알게 되었습니다! 😄   또한, validate함수를 추가하여 어떤 상황인지 잘 나타내도록 변경하였습니다!

2022-02-15 04:52 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("커스텀 구분자 내에 숫자가 포함되어 있습니다.");
이 부분에 대해서 알아본 결과 checked는 반드시 예외 처리가 되어야 하는 complie 시점에서 발생되는 exception이고 unchecked는 명시적으로 예외 처리를 해주지 않아도 되는 runtime 시점의 exception인 것을 알아냈습니다. 다만, 아직 이해를 제대로 하지 못한 것인지 해당 부분에서 checked exception이 사용될 방법에 대해 잘 모르겠습니다.. 혹시 말씀하신 부분이 RuntimeException 보다 좀 더 명시적으로 입력 형식이 잘못되었다는  IllegalArgumentException을 사용하라는 것일까요?

2022-02-15 04:54 UTC, syoun602 commented on src/main/java/racingcar/Application.java
> +public class Application {
Application에 대해서는 이름을 바꿔볼 생각을 한번도 해보지 못했습니다! 하여 RacingApplication으로 바꿔보았는데 괜찮은가요?!

2022-02-15 05:00 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +        Scanner scanner = new Scanner(System.in);
이부분에 있어서 프리코스때 굉장히 많이 고민했었는데, 당시에 적용했던 방식을 잊어버렸었네요..... View에서 입력을 받는 함수를 두고 controller에서는 불러오기만 하는 방식으로 변경하였습니다!!!

2022-02-15 05:10 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +        scanner.close();
자동차들을 처리하는 함수들과 시도 횟수를 처리하는 함수 두가지를 하나의 개행으로 가독성을 높여봤습니다!

2022-02-15 05:17 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +        List<String> carNameList = splitCars(carNames);
✅

2022-02-15 05:18 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +        List<String> carNameList = Arrays.asList(carNames.replaceAll(SPACE, BLANK).split(COMMA));
✅

2022-02-15 05:19 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +    }
✅

2022-02-15 05:32 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +                .max(Comparator.comparing(x -> x))
✅

2022-02-15 05:34 UTC, syoun602 commented on src/main/java/racingcar/util/InputValidator.java
> +        if (!carNameList.stream().allMatch(carName -> carName.length() <= MINIMUM_CAR_NAME_LENGTH)) {
✅

2022-02-15 05:56 UTC, syoun602 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void 콤마_구분자() {
넵!! displayname으로 변경해보았습니다. 이에 대해 인지하고 있었는데, 테스트를 한글로 작성할 경우에는 굳이 사용할 필요 없겠다라고 생각했었습니다. 혹시 supress warning이 야기할 수 있는 문제사항이 있을까요?

2022-02-15 06:09 UTC, syoun602 commented on src/test/java/calculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
넵 StringCalculator와 RacingGame 모두 경계에 따라 테스트를 나누어 보았습니다!

2022-02-15 09:00 UTC, syoun602 commented
두번째 리뷰요청 남깁니다!!! 꼼꼼하게 봐주셔서 감사합니다.. 생각보다 수정할 사항이 많았는데 너무 대충 올렸나 싶었습니다.... 올려주신 리뷰는 모두 반영하였습니다! 중간 중간에 궁금한 점은 댓글에 다시 남겨놓았습니다! 아래 질문은 이외에 궁금한 점입니다!!

---

1. 인터페이스 부분도 말씀하신 것을 참고하여 NumberGenerator 라는 Interface를 두고 RandomNumberGenerator와 FixedNumberGenerator를 사용하여 변경하였고 테스트 코드도 이에 따라 수정하였는데, 테스트 코드를 위해 새로운 클래스 FixedNumber 가 추가되는 부분이 맞을까요?

2. Car 객체를 보면 테스트를 위한 생성자가 하나 더 추가되어 있는데, 원래 테스트를 위해 생성자를 추가하는 것을 피해야 하나요?

감사합니다 ❗❗

2022-02-15 09:10 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +    }
말씀해주신대로 변경해보았습니다!!!!

2022-02-15 13:50 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        if (input == null || input.isEmpty()) {
isBlank()는 null을 방지하지는 못합니다.
참고로 Java11부터 사용도 가능하구요.
해당 부분도 꼭 알아두시면 좋을거 같아요. 차후 현업을 갔을때 Java11을 쓰지 않을수도 있으니깐요 ㅎㅎ

2022-02-15 13:51 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +            throw new RuntimeException("커스텀 구분자 내에 숫자가 포함되어 있습니다.");
그건 아니였고, 제가 미션 요구사항을 자세히 읽어보지 않았네요. 죄송합니다.  RuntimeExcetpion을 발생시키도록 하는것이였는데요.
현재와 같이 작성해주시면 되고, Checked와 UnChecked를 다음 미션부터는 적절한 상황에 써주시면 감사하겠습니다.

2022-02-15 13:53 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +    public Cars initCars(List<String> carNameList) {
테스트를 위해 접근제어자를 public으로 여는건 굉장히 좋지 않다고 생각이 드는데요.
그렇다면 private 메서드를 어떻게 테스트를 할수 있을까요?
private 메서드는 기본적으로 다른 public 메서드에서 쓰일거 같은데요.
그렇다면 private 메서드를 사용하는 public 메서드에서 검증하면 되지 않을까요?

2022-02-15 13:53 UTC, ksy90101 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void 콤마_구분자() {
혹시라도 같이 협업하는 동료의 컴퓨터의 인코딩이 한글을 지원하지 않는다면 어떻게 될까요?

2022-02-15 14:09 UTC, ksy90101 requested changes
안녕하세요 :) 썬 리뷰어 럿고입니다.
전반적으로 코드가 더 읽기 쉬워지게 변경된거 같아요.
너무 고생 많으셨습니다 💯 

이번 리뷰는 조금 구조를 많이 변경해야 하는 피드백을 남겨보았는데요.
객체로 만들수 있는 것들을 한번 객체로 만들어서 처리해보시면 좋을거 같아요.
대표적으로 현재 Car의 Name과 Game의 TrialNum을 만들어 보시는걸 추천드립니다.

아울러 남겨주신 질문은 리뷰를 남기다 보니, 자연스럽게 답변이 있는거 같아서, 리뷰를 참고해주시면 좋을거 같습니다.

조금만 더 힘내봐요 👍

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        List<Integer> numList = new ArrayList<>();
List라는 단어는 굉장히 좋지 않은데요.
클린코드에서도 아래와 같이 자료구조의 명명은 아래와 같이 작성하라고 하는데, 혹시 한번 확인해보시겠어요?
```
개발자에게는 특수한 의미를 가지는 단어(List, Array등)는 실제 저수준 자료구조를 표현한 의미가 아닌 이상 accountList와 같이 변수명에 붙이지 말자. 고수준 비즈니스 정책에 맞는 복수형 단어를 사용합니다
```

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        return Arrays.stream(strArr).count() == 1 && strArr[0].equals("");
스트림은 한줄에 점 하나씩!
그렇다면 지금같은 경우에는 어떻게 사용할 수 있을까요?
`Arrays.stream(strArr).count()`이 값이 어떤걸 의미하는지 나타내면 되지 않을까요?

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        return Arrays.stream(strArr).count() == 1 && strArr[0].equals("");
1, "" 모두 매직넘버 입니다 :) 의미있는 단어를 사용해주세요.

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/calculator/StringCalculator.java
> +        isPositive(value);
이 validation이 이 메서드의 책임이 맞을까요?

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +        InputValidator.validateDuplicateName(carNames);
현재 검증을 Controller에서 하고 있는데요.
carName을 Name이라는 VO를 만들어서 검증하게 한다면, 차후 Name에 추가되는 비즈니스 로직도 같이 넣을수 있지 않을까요?

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
> +    private int trialNum;
trialNum도 한번 객체로 만들어보고, 관련된 책임을 도메인으로 모아볼까요?

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/model/Car.java
> +        return name;
```suggestion
    }

    public String getName() {
        return name;
```

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +    public List<Car> getCars() {
저는 메서드 순서를 아래와 같이 하고 있는데요. 한번 참고해보시고 순서를 지정해보실까요?

````

constructors first
static methods next, if there is a main method, always before other static methods
non static methods next, usually in order of the significance of the method followed by any methods that it calls. This means that public methods that call other class methods appear towards the top and private methods that call no other methods usually end up towards the bottom
standard methods like toString, equals and hashcode next
getters and setters have a special place reserved right at the bottom of the class
````

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/util/FixedNumberGenerator.java
> +public class FixedNumberGenerator implements NumberGenerator {
해당 객체는 테스트를 위해 만드신거 같은데요.
테스트에서만 사용하는 객체는 어디에 있으면 좋을까요?
프로덕션에 있다면 어떤 문제가 있을까요?

일단 코드가 많아진다는것은 컴파일할 코드가 많다는 것이고 그렇게 된다면 굉장히 비대해질거 같아요.
테스트 폴더에는 테스트만 넣어야 한다는 규칙은 따로 없기도 합니다 :)

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/util/InputValidator.java
> +    public static void validateDuplicateName(List<String> carNameList) {
여기도 List가 아닌 복수를 사용하는게 더 좋을거 같습니다 :)

2022-02-15 14:09 UTC, ksy90101 commented on src/main/java/racingcar/util/NumberGenerator.java
> +public interface NumberGenerator {
👍

2022-02-15 14:09 UTC, ksy90101 commented on src/test/java/calculator/InputValidationTest.java
> +public class InputValidationTest {
지금 보면 굉장히 중복인 테스트가 있는데요.
결국 StringCalculator.splitAndSum() 이 메서드에 인자를 넣어서 테스트를 하는것 같아요.
이런 경우에는 중복코드를 어떻게 줄일 수 있을까요?
`@ParameterizedTest` 라는 키워드를 찾아보시고 한번 적용해볼까요?

2022-02-15 14:09 UTC, ksy90101 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void splitByComma() {
여기도 동일한 테스트가 많아 보이네요.
위의 리뷰를 참고해서 수정해주세요 :)

2022-02-15 14:09 UTC, ksy90101 commented on src/test/java/racingcar/InputValidationTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
IllegalAgrumentException은 굉장히 포괄적인 에러라고 생각이 드는데요.
이런 경우 우리가 생각한 예외인지를 어떻게 판단할수 있을까요?
`hasMessageContaining()`이러한 메서드를 찾아보시고 한번 적용해보시겠어요?

2022-02-15 14:09 UTC, ksy90101 commented on src/test/java/racingcar/RacingGameTest.java
> +public class RacingGameTest {
Junit5부터는 public을 지양하고 있는데요.
이유는 아래와 같습니다. 한번 읽어보세요~

````
Class and method visibility
Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private.

It is generally recommended to omit the public modifier for test classes, test methods, and lifecycle methods unless there is a technical reason for doing so – for example, when a test class is extended by a test class in another package. Another technical reason for making classes and methods public is to simplify testing on the module path when using the Java Module System.
````

2022-02-16 08:39 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        List<Integer> numList = new ArrayList<>();
✅

2022-02-16 08:40 UTC, syoun602 commented on src/main/java/racingcar/util/InputValidator.java
> +    public static void validateDuplicateName(List<String> carNameList) {
✅

2022-02-16 09:04 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        return Arrays.stream(strArr).count() == 1 && strArr[0].equals("");
✅

2022-02-16 09:04 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        return Arrays.stream(strArr).count() == 1 && strArr[0].equals("");
✅

2022-02-16 09:20 UTC, syoun602 commented on src/main/java/calculator/StringCalculator.java
> +        isPositive(value);
숫자를 변환하는 과정에서 생길 수 있는 오류라고 생각했습니다. 다만 이를 확인하는 메서드를 만들어서 숫자 판별과 양수 판별을 따로 두었습니다.

2022-02-16 11:26 UTC, syoun602 commented on src/test/java/racingcar/InputValidationTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
앗 감사합니다!! 적용하여 좀 더 직관적으로 어떤 오류에 대한 테스트였는지 그리고 해당 오류가 실제로 발생했는지 알 수 있게 만들겠습니다!

2022-02-16 11:31 UTC, syoun602 commented on src/test/java/racingcar/RacingGameTest.java
> +public class RacingGameTest {
테스트가 다른 테스트를 불러오는 등의 특정 경우가 아니라면 access modifier를 붙이지 말라는 내용이네요!! 아직 익숙하지 않았어서 Junit 문서롤 읽어본 적이 없었습니다.. 감사합니다!!

2022-02-16 12:29 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +        InputValidator.validateDuplicateName(carNames);
넵 제안해주신대로 Name이라는 VO를 만들어서 해당 객체에서 validation을 할 수 있도록 변경해보았습니다. 이렇게 하면 추후에 name이라는 속성을 가지는 곳에서 (예시로: 버스, 기차) 등에서 사용할 수 있을 것 같습니다!!
중간에 버스나 기차에서는 이름에 대한 요구사항이 변경되면 어떡하지? 라는 생각을 했었는데,  더 요구사항이 추가된다면 name VO에서 하는 검증을 완화시키고 각 객체에서 더 처리하면 되겠다는 생각에 CarMaxLength에 대해서는 Car 객체 내에서 확인하도록 변경하였습니다!

2022-02-16 12:44 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
> +    private int trialNum;
✅

2022-02-16 12:44 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +        return name;
✅

2022-02-16 12:54 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +    public List<Car> getCars() {
✅

2022-02-16 12:56 UTC, syoun602 commented on src/main/java/racingcar/util/FixedNumberGenerator.java
> +public class FixedNumberGenerator implements NumberGenerator {
아하 테스트를 위해서 만든 코드이기 때문에 테스트로 옮겨도 되는군요. NumberGenerator interface를 재정의한 클래스이기 때문에 모두 같은 패키지에 속해 있어야 한다고 생각했습니다ㅠㅠ

2022-02-16 13:33 UTC, syoun602 commented on src/test/java/calculator/InputValidationTest.java
> +public class InputValidationTest {
넵 중복적인 테스트에 대해서는 `ParameterizedTest`와 `MethodSource`를 이용해서 줄여보았습니다.

근데 아래의 코드의 경우에 대해서 궁금한 것이 있습니다! 😢 
만약 테스트 코드 자체는 똑같지만 다른 내용에 대해서 테스트하는 경우에, displayName에 합쳐서 이를 묶어주어야 하나요??
![image](https://user-images.githubusercontent.com/67397679/154275062-d5419044-370d-4ea3-aa31-ba4ad0b8ddf6.png)

2022-02-16 13:33 UTC, syoun602 commented on src/test/java/calculator/StringCalculatorTest.java
> +    void splitByComma() {
✅

2022-02-16 13:46 UTC, syoun602 commented
안녕하세요 럿고! 벌써 세 번째 리뷰 요청이네요 👀 
꼼꼼하게 봐주셔서 감사합니다!
아래는 이번 댓글에서 언급한 질문 이외에 궁금한 점들입니다!

---

1. 아래 코드처럼 메소드안에 메소드를 넣어놓는 것은 좋은 방식이 아닌가요?? 
![image](https://user-images.githubusercontent.com/67397679/154275900-33408c91-a144-4709-9d55-927991591fa8.png)

2. 현재 getName이 중복되고 있는데, 이에 대한 명칭 변경이 필요할까요??
![image](https://user-images.githubusercontent.com/67397679/154276692-4cc23565-ceec-48c9-ab82-6073cb18f463.png)

3. 마지막으로 메소드 순서에 대한 궁금증이 항상 있었는데, 혹시 럿고는 아래의 상황에서 다음 메소드로 splitCars와 inputTrialNum 중 무엇을 우선시 하나요? 직관적으로는 inputTrialNum을 놓고 싶은데, 지난 리뷰에서 작성해주신 메소드 순서를 보면 해당 메소드가 부르는 다음 메소드를 바로 부른다고 적혀있어서요 ㅠㅠ 
![image](https://user-images.githubusercontent.com/67397679/154276898-1ea12bbb-34f5-4d81-8ce1-bd780de6f0d3.png)

2022-02-17 00:35 UTC, ksy90101 approved these changes
안녕하세요 :) 썬 너무 고생 많으셨습니다!
코드가 훨씬 깔끔해진거 같네요! 💯 
2단계때 더 이야기 나눠봐요 고생많으셨습니다~

1. 아래 코드처럼 메소드안에 메소드를 넣어놓는 것은 좋은 방식이 아닌가요??
좋은 방식이다. 아니다 라는 것 보다는 제 생각은 취향이라고 생각이 듭니다.
사실 이 부분은 가독성에 문제라고 생각이 드는데요. 저는 둘다 가독성은 나쁘지 않다고 생각해요.
그러나 한 줄에 메서드가 많다면 그것도 가독성이 떨어지겠죠?ㅎㅎ 아울러 한 메서드에서 여러 메서드를 부른다는 것은 그만큼 책임이 많다고 생각이 들거든요. 한 메서드가 다른 메서드를 부를때 그 메서드가 다른 메서드의 일을 처리하는 책임을 갖고 잇다고 생각이 들어요 ㅎㅎ

2. 현재 getName이 중복되고 있는데, 이런 상황은 피해야 할까요?
저는 도메인에서 해당 필드를 내려주는걸 더 선호하고 있는데요. 말씀하신 대로 car.getName에서 Name 객체가 아니라 Name.getName을 내려주면 어덜까요?

2022-02-17 00:35 UTC, merged