[1단계 - 자동차 경주 구현] 마루(송채원) 미션 제출합니다.
woowacourse/java-racingcar pull request #290
Opened 2022-02-11 07:29 UTC by chawani

안녕하세요😊 마루입니다!
코드리뷰를 난생 처음 받아봐서 떨리고 설레네요ㅎㅎ 잘 부탁드립니다🙇‍♂️

미션을 진행하면서 궁금했던 점 몇가지를 정리해봤어요

**1. 유효성 검사는 어디서?**
입력값에 대한 유효성 판정을 Parser에서 진행했습니다! Parser에서 진행하는것이 맞을까요? 만일 controller를 만들게 된다면 입력에 대한 유효성검사를 controller vs parser 어느곳에서 해야하는지도 궁금합니다~ 또한, 유효한지 판별하는 메서드들을 따로 빼서 클래스를 만드는 것이 좋은지도 궁금합니다

**2. 어디까지가 매직넘버?**
수가 음수인지 양수인지를 판별할때 if문에서 x>0 이런식으로 쓰는 값들은 매직넘버인지 아닌지 궁금합니다! 배열이 비었을때도 배열.length == 0 이런식으로 쓰면 0은 매직넘버인가요?

**3. 은닉을 잘하는 방법?**
(1) RacingGame 클래스에서 Car의 position을 최대한 getter로 받아오지 않으려고 노력했습니다. 따라서 Car에 getCurrentPosition이라는 메서드를 만들어 name과 position을 출력형식 String으로 만들어서 리턴하도록 하였는데, 더 좋은 방법이 있는지 궁금합니다~!
(2) getCurrentPosition라는 메서드의 이름이 Car가 position이라는 속성을 가지고있다는것을 드러나게 하는거같은데, 이럴땐 어떤 이름을 짓는 것이 좋은가요?
(3) RacingGame 클래스에서 우승자의 이름을 가져와야하는데 getter를 안쓰고 가져오는 방법을 잘 모르겠습니다. 어떻게하면 좋을까요?

**4. static 메서드는 언제쓰는 걸까요?**
InputView와 OutputView 클래스의 메서드들을 static으로 만들었는데, static 메서드로 구현해도 괜찮은가요? 어느시점에서 static메서드를 사용해야하는지 잘 모르겠습니다ㅜ.ㅜ

읽어주셔서 감사합니다😀

2022-02-11 17:23 UTC, sonypark requested changes
마루 안녕하세요! 리뷰어 소니입니다 :)
첫 리뷰를 맡게 되어 영광입니다.
미션 수행하느라 고생하셨어요.
전반적으로 잘 작성해주셨지만 몇가지 아쉬운 점이 있어 의견 남겼습니다
질문 주신 것에 대한 답변과 코멘트 남겼으니 확인 부탁드립니다!


1. 유효성 검사는 어디서?
좋은 고민입니다. 이런 고민을 하게된 이유가 있을텐데요. Parser 클래스에 검증 로직을 넣다가 '이게 Paser의 역할인가?'에 대한 생각을 하셨을 것 같아요. 역할별로 클래스를 나누고 최대한 그 역할에 맡는 일만 할 수 있도록 해주는 것이 객체지향 코드를 작성하는데 도움이 될 거에요. Paser에서 진행하는 검증이 어떤 규칙에 의해 생긴 검증인지 생각해보고 해당 클래스로 이동해보는건 어떨까요?

```
또한, 유효한지 판별하는 메서드들을 따로 빼서 클래스를 만드는 것이 좋은지도 궁금합니다
```
물론 Validator 클래스 같은 걸 만들어 유효성 검사 로직만 따로 뺄 수 있습니다. 그만큼 여러 곳에서 범용적으로 쓰일만한 로직이라면 빼도 될 것 같아요. 그게 아니라 특정 클래스에만 해당하는 검증 로직이라면 클래스로 분리하기엔 오버엔지니어링은 아닐지 생각해봐야겠죠?

2. 어디까지가 매직넘버?
도메인 지식이 없는 누군가가 코드를 봤을 때 의미가 불분명한 값이라면 매직넘버라고 볼 수 있습니다.
한 번 매직넘버에 대해 검색해보고 예시를 보면 도움이 될 것 같네요. 예시로 주신 것은 매직넘버일까요? 물론 숫자를 상수로 뺄 수도 있지만  isEmpty()와 같은 메서드를 사용할 수도 있겠네요.

- 수가 음수인지 양수인지를 판별할때 if문에서 x>0 이런식으로 쓰는 값
- 배열.length == 0

3. 은닉을 잘하는 방법?
(1) RacingGame 클래스에서 Car의 position을 최대한 getter로 받아오지 않으려고 노력했습니다. 따라서 Car에 getCurrentPosition이라는 메서드를 만들어 name과 position을 출력형식 String으로 만들어서 리턴하도록 하였는데, 더 좋은 방법이 있는지 궁금합니다~!
getCurrentPosition는 개선이 필요해보입니다. 아래 코멘트에 남겼으니 어떻게 개선할 수 있을지 고민해보세요~

(2) getCurrentPosition라는 메서드의 이름이 Car가 position이라는 속성을 가지고있다는것을 드러나게 하는거같은데, 이럴땐 어떤 이름을 짓는 것이 좋은가요?
Car가 position 속성을 갖고 있는게 맞고 프로그램 흐름 상 Car에서 position을 가져오는게 필요한데요. 어떤 부분이 문제라고 생각하신 걸까요? (이름이 길다면 getCurrentPosition -> getPosition 이라고만 해도 될 것 같아요)

(3) RacingGame 클래스에서 우승자의 이름을 가져와야하는데 getter를 안쓰고 가져오는 방법을 잘 모르겠습니다. 어떻게하면 좋을까요?
우승자의 이름을 가져오려면 getter를 써야겠죠? getter 사용을 무조건 지양해야 하는 건 아닙니다. 부적절하게 사용되는걸 지양해야하죠. 부적절한 getter 사용은 어떤 경우를 말하는걸까요? 

4. static 메서드는 언제쓰는 걸까요?
[When to use static methods](https://stackoverflow.com/questions/2671496/when-to-use-static-methods)
반대로 생각해보면 될 것 같아요. 인스턴스를 생성해서 써야하는 클래스는 어떤 클래스인가? View 클래스는 인스턴스 생성이 필요한 클래스일까요? 객체는 어떤 특징을 가질까요? 객체로 생성하지 않으면 안되는 클래스는 어떤 클래스일까요? 이 미션에 있는 클래스를 대상으로 한 번 생각해보시면 좋을 것 같아요 :)

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Calculator.java
> +
total은 필요한 변수일까요?
파라미터 타입을 `int[]` 으로 해준 이유가 있을까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Calculator.java
> +}
객체지향 생활체조 원칙을 지켜볼까요?
`한 메서드에 오직 한 단계의 들여쓰기만 한다.`

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Calculator.java
> +}
RuntimeException 이 적절한 exception인지도 고민해봅시다.
예외 메시지는 상수로 빼주면 좋을 것 같아요~

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Parser.java
> +            }
여기도 `String[]`로 받고 있네요. List를 사용해보면 어떨까요? 두 가지 타입이 장단점은 무엇이 있을까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/StringCalculator.java
> +
입력값이 "1,2,3" 으로 고정되어 있네요.
이 경우 계산기의 결과값은 6으로 정해져 있을텐데, 여러 입력값을 받도록 하려면 어떻게 해야할까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/StringCalculator.java
> +
여기도 배열을 사용하셨군요~ 배열과 리스트의 차이에 대해 공부해보시면 좋을 것 같아요 :)

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Parser.java
> +    String regex = ",|:";
상수로 선언하면 어떨까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/calculator/Parser.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(input);
정규표현식 패턴도 상수로 추출할 수 있겠네요~
상수로 추출할 때 이점은 무엇일까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/Application.java
> +        System.out.println(OutputView.RACE_RESULT_MESSAGE);
출력은 OutputView의 책임 인 것 같은데, OutputView에게 위임하는건 어떤가요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/Parser.java
> +
Paser의 역할에 대해 생각해봅시다. 값의 변환과 값에 대한 검증까지 하고 있는데 Paser의 역할이 맞을까요?
Paser가 아닌 InputView에서도 검증할 수 있을 것 같은데 Paser에서 하신 이유가 있으신가요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/Parser.java
> +    }
isXXX 라는 메서드 이름은 보통 boolean을 반환할 때 사용하는데요. void인 경우는 어떤 네이밍으로 해주면 좋을까요?
예외가 발생했을 때 에러메시지가 없다면 어떤 이유로 예외가 발생했는지 알기 어려워요.🥲 한 번 수정해볼까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/Parser.java
> +    }
자동차 이름에 대한 검증을 Paser에서 하는게 맞을까요? 이 규칙은 어떤 레이어의 규칙이고, 검증은 어디서 해야할까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +    }
Car에서 랜덤 숫자를 생성하는 일을 하고있군요. Car의 역할이 맡을까요?
이 메서드가 호출 될때마다 Random() 객체를 생성하는데, 어떤 문제가 있을까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +    }
이 부분은 출력을 위한 로직인것 같은데 Car의 역할이 맡을까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +    }
이 메서드를 보면 Car 스스로 우승자를 판단할 수 있는 것 같은데요
파라미터 값으로 항상 우승자의 점수가 들어오는걸까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
가장 점수가 높은 Car를 선정하는 로직을 어떻게 하면 개선할 수 있을지 고민해봅시다!
- highScore 필드는 꼭 필요한 걸까요?
- cars 리스트를 이용해 최고점을 얻을 수는 없을까요?

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
👍

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +    }
메시지는 상수로 추출해도 좋겠네요

2022-02-11 17:23 UTC, sonypark commented on src/main/java/racingcar/view/OutputView.java
> +    }
여기도 상수로 추출할 부분이 보이네요

2022-02-11 17:23 UTC, sonypark commented on src/test/java/racingcar/ParserTest.java
> +    }
테스트가 실패하는 것 같아요~

2022-02-11 17:23 UTC, sonypark commented on src/test/java/racingcar/domain/CarTest.java
> +    }
이 부분은 car.getCurrentPosition() 메서드를 개선하면서 고쳐봅시다.
Car의 position을 문자열로 확인하는게 맞는지 고민해보세요 🤔

2022-02-11 17:24 UTC, sonypark commented on src/main/java/racingcar/Application.java
> +        OutputView.printChampionList(racingGame);
인자로 racingGame를 넘겨주기 보다 우승자의 이름을 넘겨주는 건 어떤가요?

2022-02-13 14:30 UTC, chawani commented
소니 안녕하세요! 리뷰 주신거 너무 너무 도움이 됐어요😊
고쳐야 할 부분이 많았어서 그런지, 다음엔 더 꼼꼼하게 진행해야겠다는 반성이 되네요😭

먼저, 배열을 사용하지 않고 리스트를 사용해야하는 이유에 대해서 찾아봤는데 공변과 불공변의 차이가 있어서 에러를 컴파일 할 때 발견하느냐, 런타임때 발견하느냐 하는 차이가 있다고 하더라구요! 아직 완벽하게 이해하기는 힘들지만 천천히 꼼꼼히 보면서 습득하도록 하겠습니다!
그리고, 유효성 검사하는 부분을 모두 Parser에 넣어놨었는데, 각자 역할에 맞춰서 최대한 분리해보았어요!
또, getter를 적당한 선에선 써야한다고 하셔서, 단순히 name이나 position 정보가 필요할때는 getter를 사용하도록 하고, 비교같은 어떠한 연산이 들어갈때는 내부에서 동작하도록 했는데 적절한 방법일까요??

수정한 것들에 대해서도 아낌없는 리뷰 부탁드립니다 :) 감사합니다!

2022-02-14 14:18 UTC, sonypark requested changes
안녕하세요 마루🙂
피드백 잘 반영해주셨네요. 이전 보다 코드가 보기 편해진 것 같습니다👍
조금 더 개선할 부분에 코멘트 남겼으니 이번 것만 개선하고 2단계로 넘어가보도록 하죠!

2022-02-14 14:18 UTC, sonypark commented on src/main/java/calculator/StringCalculator.java
> +        }
input에 값을 할당할 필요없이 바로 return하면 되지 않을까요?

2022-02-14 14:18 UTC, sonypark commented on src/main/java/calculator/StringCalculator.java
> +    }
입력받는 곳만 있고 출력해주는 곳은 없네요

2022-02-14 14:18 UTC, sonypark commented on src/main/java/calculator/StringCalculator.java
> +        List<String> values = Arrays.asList(parser.split(input));
parser.split의 반환값을 외부에서 리스트로 맵핑하기 보내 리스트로 반환해주는건 어떨까요?

2022-02-14 14:18 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +    }
반환값을 String으로 해준 이유가 있나요?

2022-02-14 14:18 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +    }
Character.isDigit()을 사용하지 않고 숫자 검증을 할 수 있는 방법은 없을까요?

2022-02-14 14:18 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +}
👍

2022-02-14 14:18 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +    }
위치를 비교하는 메서드인데 car가 아닌 position만 넘겨줘도 되지 않을까요?

2022-02-14 14:18 UTC, sonypark commented on src/main/java/racingcar/domain/RacingGame.java
> +
여기도 final을 붙여주는게 좋겠네요

2022-02-14 14:18 UTC, sonypark commented on src/test/java/racingcar/domain/RacingGameTest.java
> +    void getChampionNames_우승자가_한명() {
`@DisplayName` 어노테이션을 이용하면 각 테스트에 대한 설명을 적을 수 있으니 활용해보세요 :)

2022-02-15 03:28 UTC, chawani commented on src/main/java/racingcar/view/InputView.java
> +    }
생각해보니 int로 반환하는게 훨씬 깔끔할거같아 수정하였습니다!

2022-02-15 12:19 UTC, sonypark requested changes
마루 안녕하세요.
코드 수정해주신것 확인했습니다!
그런데 테스트코드가 많이 깨지네요...?🥲 
푸시 전에 테스트 코드가 깨지지 않는지 확인하고 푸시해주세요🙏🏻
테스트 코드 통과되면 다음 단계로 넘어가봅시다💪
수정 후 리뷰 요청 주세요!
![Uploading image.png…]()

2022-02-15 12:41 UTC, sonypark commented
인텔리제이 캐시 문제로 발생한 에러였네요..🥲 죄송합니다! 바로 머지하겠습니다.
2단계 진행해주세요~💪

2022-02-15 12:41 UTC, sonypark approved these changes

2022-02-15 12:41 UTC, merged