[1단계 - 자동차 경주 구현] 헌치(박지우) 미션 제출합니다.
woowacourse/java-racingcar pull request #333
Opened 2022-02-11 08:52 UTC by BETTERFUTURE4

로운님 반갑습니다!
자동차경주 구현/ 문자열 계산기의 1차 리팩토링을 해보았습니다.
첫 우테코 리뷰를 받게 되어 감회가 새롭네요!ㅎㅎㅎ

---
## 질문

1. 자동차 경주 구현 프로그램에서 페어 주디의 의견을 따라 패키지를 mvc 이외에도 utils,service, validator 등 추가해보았습니다. 이와 같은 방식의 패키지 분리가 맞는 방향성일까요?
2. Console을 통해 가져온 인풋 값을 테스트하기 어려워서 주요 클래스별로 테스트 코드를 작성해 보았는데, 테스트 코드에서 임의의 임풋 값을 설정하는 방법이 있을까요?
3. 상수들을 따로 Constants 클래스를 만들어 분리했는데, 기존 클래스 위에 상수화 하는 것과 비교하면 어떤 방법이 더 좋을까요?
4. 객체를 일급 콜렉션으로 묶었을 때에는 해당 일급콜렉션을 변수로 갖는  클래스에서 public으로 처리하고, getter와 setter를 쓰지 않으려 했는데, 이 방향이 맞을까요? 일급콜렉션에 대헤 여러 의견들이 있는 것 같아서요!
5. RequestService 클래스에서 Try-catch 문 등 몇 요소들이 반복되는데, 이를 합쳐서 처리할 수 있는 방법이 있을까요?
6. 자동차 경주 구현 예외처리를 이번엔 다양한 곳에서 처리했습니다. 
예를들어 자동차들의 이름을 받아올 때
````
public static void requestNames(RacingCarsService carsService) {
  try {
	  String input = Input.inputNames();
	  NameValidator.validateInput(input);
	  carsService.initiateCars(input);
  } catch (Exception exception) {
	  Output.printError(exception.getMessage());
	  requestNames(carsService);
  }
}
````
첫 인풋값을 가져올 때와

````
public class RacingCars {
	private List<Car> cars = new ArrayList<>();

	public RacingCars(List<String> cars) throws Exception {
		NameValidator.validateNameList(cars);
		for (String car : cars) {
			this.cars.add(new Car(car));
		}
	}
````
자동차들이 모여있는 모델 생성자 때와
````
public Car(String name) throws Exception {
  NameValidator.validateName(name);
  this.name = name;
}
````
자동차 모델을 생성할 때

이 세 곳으로 나누어 예외처리를 진행했습니다. 
그런데 막상 코드를 보니 예외처리를 한 곳에서 진행하는 게 더 깔끔해보이는 것 같기도 하네요ㅠㅠ
어느 방향이 맞는 건지 궁금합니다.
---
아직 배워가는 시기라서 잘 모르는 부분들이 많네요!
피드백 기다리고 있겠습니다. 감사합니다!!

2022-02-11 15:56 UTC, lowoon requested changes
반가워요 헌치! 리뷰어 로운입니다! 😄 
작성하신 코드 잘 확인했습니다. 질문의 양만큼 많은 고민의 흔적이 느껴졌습니다 💯 
소소한 피드백 몇 가지 남겨봤으니 확인 부탁드려요.

질문하셨던 부분 답변을 드리면
1. package
utils와 service 등의 패키지는 이후 spring을 쓰면 많이 쓰게 되는데요. 많이 쓴다고 쓰기 보다는 controller, service등의 역할이 무엇인지 왜 쓰는지 고민해보는게 좋을 거 같아요. validator의 경우, 단순히 입력인 경우와 다르게 내부적인 비지니스 검증인 경우, 객체가 스스로 검증하도록 할 수 있지 않을까요??

2. 테스트
임의의 인풋값이라는게 랜덤으로 생성된 랜덤값을 의미하는 걸까요?? 저러한 랜덤값으로 어떤 부분을 테스트 하고 싶은걸까요?? 테스트는 내가 작성한 코드가 내가 의도한대로 동작했는지 확인하는 작업입니다. 그렇다면 어디가 제대로 동작했는지, 확인하고 싶으신 부분을 생각해보시면 좋을거 같아요.

3. 상수
여러 클래스에서 사용하는 경우에는 공통으로 빼는 것이 좋을 수도 있겠죠? 한 곳에서 사용하는데 공통으로 빼놓을 경우 검색이나 값을 찾는데 더 많은 시간이 들지 않을까요?? 같이 모아놓는 것과 각각에서 관리하는 것의 장단점을 고민해보면 좋을거 같아요.

4. getter, setter
getter와 setter를 쓰지 않으려고 하는 이유는 객체가 자신의 데이터를 자기 자신만 관리하도록 만들기 위해서라고 생각해요. 무조건적으로 메서드 자체를 안만들기보다 왜 안만들려고 하는지를 생각해보는게 좋지 않을까요??

5. request service
request service에 car service를 넘기지 않고 car service를 사용하는 로직을 제거하면 하나의 메서드로 합칠 수 있지 않을까요?? request service에게 car service를 넘기는 것이 맞을까요??

 6. 예외처리
 예외처리를 했다는게 throw exception을 말씀하시는 걸까요?? throw exception은 해당 메서드에서 exception이 발생하더라도 처리하지 않고 상위에서 처리하도록 exception을 던진다고 합니다. 실제로 처리를 하는 부분은 try-catch를 쓴 request service 한 곳이라고 보시면 됩니다. 깔끔해보이는 것보다는 다른 곳에서는 왜 try-catch로 처리하지 않았는지를 생각해보는게 좋을거 같아요.

답변이 도움이 되었으면 좋겠네요 😸 
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-02-11 15:56 UTC, lowoon commented on src/main/java/racingCar/model/Car.java
> +		return name + Constants.ROUND_REGEX + Constants.POSITION_SIGNATURE.repeat(position) + "\n";
다른 것들이 다 상수화가 되어 있네요. 👍 
\n도 System.lineSeparator()를 써도 좋을거 같네요

2022-02-11 15:56 UTC, lowoon commented on src/main/java/racingCar/model/RacingCars.java
> +			.map(Car::getName).collect(Collectors.toList());
한줄에 한 chaining을 명시해주는 것이 좀 더 명확해요.
그리고 메서드의 이름이 getWinners가 맞을까요??
실제로 리턴해주는 것은 입력한 값과 같은 차량들 아닌가요?? 입력한 값이 다른 값이여도 return 하지 않나요?

2022-02-11 15:56 UTC, lowoon commented on src/main/java/racingCar/model/Car.java
> +	public void go() {
car에 대한 테스트는 왜 없을까요??

2022-02-11 15:56 UTC, lowoon commented on src/main/java/racingCar/model/RacingCars.java
> +		cars.forEach(Car::go);
forEach보다는 for문이 좀더 명확할 거 같아요

2022-02-11 15:56 UTC, lowoon commented on src/main/java/racingCar/service/RacingCarsService.java
> +			Convertor.separate(nameString)
```suggestion
               String[] names = Convertor.separate(nameString);
               cars = new RacingCars(Arrays.asList(names));
```
한번에 많은 것들을 하기보다 하나씩 단계별로 진행을 하는 것이 명확해요.

2022-02-11 15:56 UTC, lowoon commented on src/test/java/racingCar/service/RacingCarsServiceTest.java
> +		int expectMaxPosition = 4;
given when then으로 나눠서 적어보면 어떨까요??

2022-02-11 15:56 UTC, lowoon commented on src/test/java/racingCar/validator/NameValidatorTest.java
> +		String name = "abcdef";
Exception만 확인하기보다 해당 상황에 맞는 메세지가 나오는지를 테스트하는게 목적이지 않을까요??

2022-02-14 03:53 UTC, BETTERFUTURE4 commented on src/main/java/racingCar/model/Car.java
> +		return name + Constants.ROUND_REGEX + Constants.POSITION_SIGNATURE.repeat(position) + "\n";
System.lineSeparator()라는 좋은 메서드가 있었네요!!🥺

2022-02-14 04:30 UTC, BETTERFUTURE4 commented on src/main/java/racingCar/model/RacingCars.java
> +			.map(Car::getName).collect(Collectors.toList());
"한줄에 한 chaining을 명시해주는 것"의 뜻은 "."마다 한줄 씩 띄어쓰면 된다는 거겠죠?
메소드의 이름에 대해서는 생각 못했던 부분이에요! 반영할게요!!

2022-02-14 04:32 UTC, BETTERFUTURE4 commented on src/main/java/racingCar/model/RacingCars.java
> +		cars.forEach(Car::go);
이런 이슈가 있었네요! 앞으로는 forEach는 제한된 영역에서만 사용할게요!

2022-02-14 04:34 UTC, BETTERFUTURE4 commented on src/main/java/racingCar/service/RacingCarsService.java
> +			Convertor.separate(nameString)
오 정말 보기 훨씬 명확하네요!😆 
메소드가 너무 중첩되어 복잡해질 땐 중간에 변수로 한번씩 끊어주도록 할게요!

2022-02-14 04:40 UTC, BETTERFUTURE4 commented on src/test/java/racingCar/service/RacingCarsServiceTest.java
> +		int expectMaxPosition = 4;
전에 몰랐던 새로운 방법이네요!
적용해서 리팩토링을 하던 도중 궁금한 점들이 생겼어요!
1. 길이가 길지 않은 테스트 코드(2~3줄)도 given/when/then으로 나누어 적는 것이 더 명확할까요?
2. assertThat() 안에 //when 에 해당하는 실행함수가 들어가는 경우, 따로 실행함수를 변수로 명명해서 //when 파트를 만드는 게 나을까요? 
3. assertThatThrownBy()를 사용해 예외확인을 할 때에도 위의 방식으로 나누어 적는 방법이 있을까요?
긴 질문 죄송합니다ㅠ.ㅠ

2022-02-14 04:43 UTC, BETTERFUTURE4 commented on src/test/java/racingCar/validator/NameValidatorTest.java
> +		String name = "abcdef";
아 그렇겠네요! 
.hasMessage()를 이용해 메세지 내용도 테스트할 수 있도록 수정할게요!

2022-02-14 04:47 UTC, BETTERFUTURE4 commented on src/main/java/racingCar/model/Car.java
> +	public void go() {
그렇네요😅😅
car를 비롯해 검증이 필요한 클래스들에 대해 테스트코드를 구현하겠습니다!
TDD의 방식이 아니라 아쉽네요ㅠㅠ 다음엔 더 신경써볼게요!

2022-02-14 05:00 UTC, BETTERFUTURE4 commented
1. 기존에는 try-catch를 이용해 로직이 인풋 값이 잘못됐을 때 에러메세지 출력 후 다시 인풋을 받는 방식이었는데
해당 로직은 프리코스 로직이고, 이번 1단계 미션의 요구사항에는 없는것 같아서
단순히 에러를 throw하는 방식으로 바꿨습니다.
2. 기존 static 메소드/변수를 사용한 부분도 수정해보았습니다.
3. 상수 클래스가 좋은 선택이 아닌 것 같아서 각각의 상수들을 사용되는 클래스 안으로 이동했습니다.

그외에 피드백 주신 부분들에 대한 개선을 적용하였습니다!

리뷰 부탁드려요! 감사합니다! 😃

2022-02-14 07:12 UTC, lowoon approved these changes
고생하셨어요. 헌치! 이전 리뷰 내용을 잘 반영해주셨습니다 💯
몇가지 코멘트를 달아봤어요.
1단계에서는 충분히 잘 해주셨기에 코멘트 반영은 2단계에서 부탁드릴게요.
추가적인 궁금증은 이 pr이 머지되어도 댓글 남겨주셔도 좋구 DM도 좋습니다.

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/model/Name.java
> +	private static final int maxNameSize = 5;
Name과 Position 객체 좋네요 👍 

상수의 명명 규칙은 모두 대문자를 사용, 단어 사이는 밑줄로 연결합니다~

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/exception/NullInputException.java
> +public class NullInputException extends IllegalArgumentException {
exception도 분리해보셨군요! 👏

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/model/Position.java
> +	public boolean isSame(int position) {
주요 로직 메서드는 getter보다 위에 있는게 좋은거 같아요
```
public class ClassName {
	// private static final 
	// 상수
	// 클래스 변수
	// 인스턴스 변수
	// 생성자
	// 팩토리 메서드
	// 일반 메서드
	// getter, setter
	// equals, hashCode, toString
}
```

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/model/RacingCars.java
> +		if (new HashSet<>(cars).size() != cars.size()) {
HashSet으로 size비교를 했는데 의도한대로 동작을 할까요??
참고하시면 좋을거 같아요. https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/utlis/Util.java
> +		return new Random().nextInt(RANDOM_MAX_BOUND_INTEGER);
Random을 항상 새로 호출해야할까요?? 새로 호출했을 때 이슈는 없을까요??

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/model/RoundCount.java
> +		if (count <= 0) {
0은 상수화 시키는 것이 낫지 않을까요??

2022-02-14 07:12 UTC, lowoon commented on src/test/java/racingCar/model/CarTest.java
> +	public Car car = new Car("jiwoo");
접근 제어자를 public으로 연 이유가 있을까요??

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/model/Car.java
> +        final int goNumber = 4;
리뷰를 잘 반영해 주셔서 이것을 2단계에 도전해 보죠 😎
https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/
https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

2022-02-14 07:12 UTC, lowoon commented on src/main/java/racingCar/view/Output.java
> +                    car.name + ROUND_REGEX + POSITION_SIGNATURE.repeat(car.position.get()) + System.lineSeparator());
model이 view로 넘어와도 될까요??

2022-02-14 07:12 UTC, lowoon commented on src/test/java/racingCar/model/utlis/UtilTest.java
> +    public void t1() {
display name이 있어서 이름을 t1 이런 식으로 한 거 같은데 메서드 자체에서도 무엇을 의미하는지 알려주는게 명확할 거 같아요.
두 개를 합쳐서 메서드를 한글로 작성해볼 수 있지 않을까요??

2022-02-14 07:21 UTC, lowoon commented on src/test/java/racingCar/service/RacingCarsServiceTest.java
> +		int expectMaxPosition = 4;
궁금한 것이 많으면 좋은 거에요! 그걸 통해서 계속해서 배울테니까요. 그 부분에 대해 같이 이야기하기 위해 리뷰어들이 있는 거랍니다? 😄 

1. 길이가 길지 않고 given when then으로 나누어지지 않는 테스트의 경우에는 나눌 필요가 없어요. 바로 확인이 될 거라서요.
2. 네. when이라는 행동으로 나온 결과를 then에서 확인하고 싶은 것이기 때문에 파트를 나누는게 나을 거 같아요.
3. 에러를 확인하는 경우에는 메서드 자체가 행위를 파라미터로 받고 있어서 위의 방식으로 나누는 것은 어렵지 않을까요??

given when then은 테스트를 확인할 때 명확하도록 템플릿화 되어 있는 것인데요. 이 방식에 맞게 나누기 어려울 경우에는 꼭 이 방식에 맞추려고 힘들어하지 않고 간단하게 작성해도 될거 같아요!
개인적인 의견입니다~

2022-02-14 07:22 UTC, merged

2022-02-14 09:45 UTC, lowoon commented on src/main/java/racingCar/model/Car.java
> +    public final Position position = new Position();
변수의 접근제어자가 public으로 열려있는데요. 이렇게 되면 어디에서나 값을 수정할 수 있게 되지 않을까요??
접근제어자에 대한 고민이 필요할거 같아요!

2022-02-14 09:46 UTC, lowoon commented on src/test/java/racingCar/model/CarTest.java
> +    public Car car = new Car("jiwoo");
가장 중요한 go에 대한 테스트가 없는거 같아요.
https://github.com/woowacourse/java-racingcar/pull/333/files#r805550422
를 반영하며 테스트도 같이 만들어 보는게 좋을거 같아요!

2022-02-14 09:54 UTC, lowoon commented on src/main/java/racingCar/model/RacingCars.java
> +    private final List<Car> cars = new ArrayList<>();
테스트가 없는거 같네요??