[2단계 - 자동차 경주 리팩터링] 알파(배철환) 미션 제출합니다.
woowacourse/java-racingcar pull request #355
Opened 2022-02-16 04:28 UTC by bcc0830

안녕하세요 에단님!
 저번 1차 미션의 피드백에 집중해서 이번 2차 과제는 MVC 패턴에서 각 부분이 어떤 "**책임**"을 가져야 하는 지, 그 범위는 어디까지 인지를 중점적으로 고민했습니다. 알고리즘 문제 같이 정답과 오답이 없는 문제라서 하루에도 생각이 많이 바뀌었습니다. 부족한 코드이지만 잘 부탁드립니다! 아래는 리팩토링 미션을 진행하면서 궁금했던 점입니다.

----
### 일급 컬렉션이 감싸는 원시 클래스의 범위는 어디까지인가?

- 2차 미션에서는 1차 미션과의 가장 큰 차이점으로 객체 Car를 담는 일급 컬렉션인 CarList를 추가하였습니다. 그런데 난수를 생성할 때도 난수를 담는 RandomNumberList라는 일급 컬렉션을 만들었는데요. 그러나, 난수는 자바에서 기본적으로 제공하는 Random 객체이기 때문에 굳이 이것도 일급 컬렉션으로 감싸야 하는게 맞는지 잘 모르겠습니다. 에단님께서는 일급 컬렉션을 만약 사용하신다면 어느 정도의 객체까지(직접 만든 객체만 혹은 빌트인 객체도 포함) 감싸는 일급 컬렉션을 사용하시는지 궁금합니다!

### 상수를 Enum으로 빼는 것의 기준은 무엇일까?

- 프리코스에서 Enum이라는 것을 알게 된 이후, 클래스 내에서 상수를 선언하지 않고 바로 Enum으로 처리하는 버릇이 생겼습니다. 비슷한 성질의 상수들을 하나의 Enum에서 관리하기 때문에 사용할 때 굉장히 편리하다는 느낌을 받았습니다. 하지만, Enum으로 상수를 별도로 처리하는 것이 적절하지 않을때도 있는지 궁금합니다. 개인적으로 이번 미션을 진행하면서 `상수이름.getValue()` 로 상수값을 처리하다보니 가독성이 좋지 않다고 느꼈습니다.

### 컨트롤러에서 UX/UI로직과 비즈니스 로직을 같이 호출하면 안되는 걸까?

- 컨트롤러에 아래와 같은 메소드가 있을 때, for문 안에서 cars를 움직이고 나서 그 결과를 OutputView로 출력하고 있을 때 이것을 UX/UI 로직과 비즈니스 로직을 함께 처리하는 상황이라고 봐야 하는지 궁금합니다!

 ```
    public void playGame(int totalTurn) {
        OutputView.displayBeforeGame();
        for (int now = 0; now < totalTurn; now++) {
             moveCarList();
             OutputView.displayCars();
        }
    }

2022-02-16 15:04 UTC, Laterality requested changes
안녕하세요 알파, 리뷰어 에단입니다.

코드의 많은 부분을 개선하려고 노력하신 게 눈에 띄네요. 고생 많으셨습니다.

몇가지 의견 남겨 드렸는데, 참고 부탁드려요.

질문 주신 부분과 겹치는 부분도 있을텐데, 추가로 아래와 같은 부분들도 고민해보시면 더 좋은 코드를 작성하는 데 도움이 될 거라 생각합니다. 

1. util 클래스의 필요성
    `IntegerConst`, `StringConst` 등의 enum에 상수를 모아두셨는데요. 매직 넘버를 왜 상수로 분리하라고 하는지, 이 클래스는 어떤 책임을 갖는지에 대해 고민해보시면 좋겠습니다.
    util 패키지는 일반적으로 M/V/C 중 특정한 계층에 속하지 않다보니 계층에 상관 없이 여러 코드가 util 패키지를 참조할 수 있습니다. 이는 util 패키지의 코드가 아주 안정적(구현이 단순하고, 변경 가능성과 빈도가 매우 낮은)이어야 한다는 의미인데요. 현재 util의 코드는 안정적일까요?
3. 들여쓰기 통일
    코드 곳곳에 tab과 space 들여쓰기가 혼용돼 있는데요. 여러 사람이 작성하는 코드이니만큼 들여쓰기나 괄호의 위치 등과 같은 기본적인 형식은 일관되게 지켜주시는 게 좋습니다. 아마 페어 프로그래밍하시면서 서로 다른 에디터 설정을 사용하시면서 발생한 것으로 보여요. 이렇게 개인 별로 에디터의 기본 설정이 다른 경우를 위해 공통적으로 지켜야 할 에디터 설정을 코드베이스에 포함시키기도 하는데요. 시간이 되신다면 [editorconfig](https://editorconfig.org/)를 살펴보시면 도움이 될 거라고 생각합니다.
4. ArrayList
   코드 곳곳에 반환 타입을 `ArrayList`로 명시하셨는데요. 반드시 `ArrayList`여야 하는 이유가 없다면 인터페이스 타입을 사용하시는 게 좋습니다.

## Q&A

1. 일급 컬렉션이 감싸는 원시 클래스의 범위는 어디까지인가?
    "일급 컬렉션을 왜 사용할까요?" 먼저 이 질문에 대한 답을 고민해보시면 좋겠습니다. 일급 컬렉션을 통해 어떤 이점을 누리고자 하는 것인지 이해하신다면 질문에 대한 답도 찾으실 수 있을 거라 생각합니다.
2. 상수를 Enum으로 빼는 것의 기준은 무엇일까?
    위와 동일합니다. 상수를 왜 Enum으로 빼야 할까요? 반대로 생각해보면, 상수를 사용하는 클래스에 두지 않으신 이유는 무엇일까요?
3. 컨트롤러에서 UX/UI로직과 비즈니스 로직을 같이 호출하면 안되는 걸까?
    예로 들어주신 코드를 정리하면 Model에서 비지니스 로직을 수행한 후, 그 결과를 View로 출력하고 있네요. 이 동작은 Controller의 역할에 부합할까요? 만약 아니라면, 왜 그럴까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +            System.out.println(error.getMessage());
오류를 출력하는 목적에 따라 적절한 출력 방법이 나뉠 수 있습니다.

* 사용자에게 오류가 발생했음을 알리는 게 목적이라면 View를 통해야겠습니다.
* 개발자가 오류 발생을 인지하기 위해 남기는 게 목적이라면 오류의 발생 위치와 종류 등을 더 상세히 알 수 있도록 `printStackTrace`를 사용하는 것이 좋습니다.

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +        for (int nowTurn = IntegerConst.ZERO.getValue(); nowTurn < totalTurn; nowTurn++) {
`IntegerConst.ZERO`는 굳이 상수로 사용하는 이유가 있을까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +            OutputView.displayCarPosition(carList.getNameList(), carList.getEachCarPosition(), StringConst.POSITION_DELEIMIER.getValue());
뷰의 요구사항이 바뀌어서 `StringConst.POSITION_DELIMITER` 대신 다른 값을 써야 한다면, 뷰가 변경돼야 할까요, 컨트롤러가 변경돼야 할까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +        return nameList;
`ArrayList`에는 `Collection`을 인자로 받는 생성자도 있습니다.

```suggestion
        return new ArrayList(nameList);
```

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +    public int getMaxPosition() {
테스트 외에는 클래스 외부에서 사용되지 않는 메서드인데요. 외부로 노출할 필요가 있을까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +        return (ArrayList<String>) this.carList.stream().filter(car -> car.isWinner(maxPosition)).map(Car::getName).collect(Collectors.toList());
1. 캐스팅하면서까지 `ArrayList`로 변환해야 하는 이유는 무엇일까요?
2. `Collectors.toList`는 내부 구현이 `ArrayList`를 반환하고 있지만 선언된 반환 타입은 `List`입니다. 만약 어떤 이유로 `toList`의 구현이 `List`의 다른 구현체를 반환하도록 바뀐다면 어떤 일이 일어날까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/model/RandomNumberList.java
> +            this.randomNumberList.add(random.nextInt(IntegerConst.RANDOM_UPPER_BOUND.getValue()));
`RANDOM_UPPER_BOUND`라는 상수는 이 클래스 내에서만 쓰이는데, 별도로 분리하신 이유가 있을까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/view/InputView.java
> +    private static void isNull(String stringInput) throws IllegalArgumentException {
보통 `is`로 시작하는 메서드는 일정 조건의 만족 여부에 따라 `boolean`을 반환하는 것이 일반적인데요.

특정 조건을 검사하여 만족하지 않는 경우 예외를 던지는 메서드라면 `check` 같은 단어로 시작하면 어떨까요?

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/view/InputView.java
> +	public static String[] getCarNameInput() throws IllegalArgumentException {
다른 곳은 들여쓰기가 space로 돼 있는데 이 부분은 tab이네요. 포맷은 일정하게 맞춰주세요.

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/view/OutputView.java
>  }
파일 끝에 new line도 동일하게 추가해주세요.

2022-02-16 15:04 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +    public void runRace() {
게임 전체의 흐름이 진행되는, 미션에서 굉장히 핵심적인 로직임에도 불구하고 테스트가 없네요.

이 메서드에 대한 테스트도 추가해주세요.

2022-02-16 15:04 UTC, Laterality commented on src/test/java/racingcartest/CarListTest.java
> +        assertThat(String.join(StringConst.WINNER_DELIMITER.getValue(), winnerNameList)).isEqualTo("pobi, jun");
`getWinnerNames`가 반환한 것은 `String` 컬렉션인데, 컬렉션을 그대로 검증하는 것이 아니라 단일 문자열로 바꿔서 검증하는 이유는 무엇일까요?

2022-02-16 15:04 UTC, Laterality commented on src/test/java/racingcartest/CarTest.java
> +        assertThat(car.isWinner(2)).isEqualTo(true);
이 메서드에 대해 이전 PR에서 코멘트 드린 적이 있었는데요. 

`car.isWinner(2)`라는 코드는 실제 동작을 잘 나타내고 있을까요?

저는 이 코드를 이해하기 위해 아래와 같은 과정을 거치게 될 것으로 보여요.

1. `car.isWinner` 라는 이름으로 미루어보면, 이 객체가 우승자인지 확인하는 것처럼 보이는데요.
2. 단순히 내부 상태를 반환하는 게 아니라 어떤 인자를 받고 있습니다.  이 인자는 무엇을 의미하는 걸까요?
3. 동작 방식을 확인하기 위해 내부 구현을 찾아가봅니다. 인자와 내부 position을 비교해서 같은지를 비교하고 있네요.

위와 같은 과정을 거쳐 이해한 바로는, 이 메서드는 인자로 받은 `position`을 `car.position`과 같은지 비교해서 그 결과를 반환하고 있습니다.

`isWinner`는 이러한 내부 동작을 잘 나타내는 이름일까요?

2022-02-16 15:04 UTC, Laterality commented on src/test/java/racingcartest/NameTest.java
>  public class NameTest {
단위테스트는 **테스트 대상 클래스**의 이름에 `Test` 등의 접미사를 붙인 이름을 사용하는 것이 보편적입니다.

테스트의 내용을 더 잘 나타낼 수 있는 이름은 무엇일까요?

2022-02-17 01:41 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +            OutputView.displayCarPosition(carList.getNameList(), carList.getEachCarPosition(), StringConst.POSITION_DELEIMIER.getValue());
뷰가 변경되야 한다고 생각합니다. 그런데 displayCarPosition은 View의 메소드이고, 구분자도 파라미터로 변경할 수 있게 했는데 혹시 이렇게 해도 뷰가 변경된 것이 아닌가요?

2022-02-17 01:44 UTC, bcc0830 commented on src/main/java/racingcar/model/CarList.java
> +    public int getMaxPosition() {
private로 바꿔야 한다고 생각합니다

2022-02-17 01:45 UTC, bcc0830 commented on src/main/java/racingcar/model/CarList.java
> +        return (ArrayList<String>) this.carList.stream().filter(car -> car.isWinner(maxPosition)).map(Car::getName).collect(Collectors.toList());
1. 특별한 이유는 없습니다
2. 캐스팅이 안되서 컴파일 에러가 발생할 거라고 생각합니다

2022-02-17 01:46 UTC, bcc0830 commented on src/main/java/racingcar/model/RandomNumberList.java
> +            this.randomNumberList.add(random.nextInt(IntegerConst.RANDOM_UPPER_BOUND.getValue()));
이번에도 딱히... 없습니다.
상수를 강박적으로 enum으로 뺀 결과라고 생각합니다

2022-02-17 01:49 UTC, bcc0830 commented on src/test/java/racingcartest/CarListTest.java
> +        assertThat(String.join(StringConst.WINNER_DELIMITER.getValue(), winnerNameList)).isEqualTo("pobi, jun");
딱히 없습니다.. 단순히 출력 형식이랑 같으면 좋지 않을까?라는 의도였습니다

2022-02-17 01:51 UTC, bcc0830 commented on src/test/java/racingcartest/CarTest.java
> +        assertThat(car.isWinner(2)).isEqualTo(true);
아니라고 생각합니다

2022-02-17 01:52 UTC, bcc0830 commented on src/test/java/racingcartest/NameTest.java
>  public class NameTest {
InputViewTest로 바꾼 후, TurnTest의 내용을 합치는 것이 낫다고 생각합니다

2022-02-17 02:12 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +        for (int nowTurn = IntegerConst.ZERO.getValue(); nowTurn < totalTurn; nowTurn++) {
딱히 없습니다. 상수로 쓰지 않으면 하드코딩한 것 같아서 상수로 뺐습니다

2022-02-17 02:21 UTC, bcc0830 commented on src/main/java/racingcar/model/CarList.java
> +        return nameList;
제안해주신 변경사항에 nameList는 혹시 Car의 이름들을 담은 collection인지 궁금합니다!

2022-02-17 13:33 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +    public void runRace() {
미션 요구사항에 System.in과 System.out에 대한 테스트는 필요없다고 했기 때문에 나머지 메소드만 테스트하는게 낫다고 생각합니다. 그런데, 이를 위해서는 난수를 테스트해야 하는데 개인적으로 이미 만들어진 Random에 대한 테스트는 무의미하다고 생각합니다. 따라서, runRace에 대한 테스트 필요성이 잘 와닿지 않는데 에단은 어떻게 생각하시는지 궁금합니다

2022-02-17 13:44 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +            System.out.println(error.getMessage());
사용자에게 오류가 발생했음을 알리는 것이 목적입니다. OutputView를 통해 처리하겠습니다

2022-02-17 13:45 UTC, bcc0830 commented on src/main/java/racingcar/view/InputView.java
> +    private static void isNull(String stringInput) throws IllegalArgumentException {
check로 바꾸겠습니다!

2022-02-17 13:45 UTC, bcc0830 commented on src/main/java/racingcar/view/InputView.java
> +	public static String[] getCarNameInput() throws IllegalArgumentException {
네 알겠습니다!

2022-02-17 13:45 UTC, bcc0830 commented on src/main/java/racingcar/view/OutputView.java
>  }
네 알겠습니다!

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/view/InputView.java
> +	public static void checkNameError(String nameInput) throws IllegalArgumentException {
유효성 검사 로직을 테스트하기 위해 `private` 메서드가 `public`이 됐네요.

테스트를 위해 비공개 메서드를 노출하는 것은 바람직할까요?

테스트하기 곤란한 클래스에 테스트가 필요한 로직이 있다면 어떻게 처리하면 좋을까요?

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +	private static final String POSITION_DELIMITER = "-";
`POSITION_DELIMITER`가 이곳으로 이동했네요. 

다시 처음 질문으로 돌아와서, 만약 위치 출력에 `-` 대신 `+`를 사용하고자 한다면 어떤 클래스가 수정돼야 할까요?

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/model/Car.java
> +	public Boolean isNowPositionAt(int maxPosition) {
1. `Now`는 불필요한 단어로 보이네요. `isPositionAt`으로도 의미를 충분히 나타낸다고 생각해요.
2. 인자 이름도 적절하게 바꿔보면 어떨까요?

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +            OutputView.displayCarPosition(carList.getNameList(), carList.getEachCarPosition(), StringConst.POSITION_DELEIMIER.getValue());
코드에서 View 영역에 대한 요구사항이 바뀌었을 때, 그로 인해 코드를 변경해야 한다면 어느 부분을 바꿔야 할지 찾아보시면 됩니다. 만약 View가 아닌 다른 영역에도 변경사항이 생긴다면 관심사가 잘못 분리된 거라고 볼 수 있겠죠.

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +        return nameList;
앗, 이름을 따로 빼서 리스트를 만드는군요. 제가 착각했네요 😅

2022-02-18 00:24 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +    public void runRace() {
그렇네요. View에 대한 의존성도 있어서 현재로선 테스트하기 어렵겠네요 🙆‍♂️

2022-02-18 00:24 UTC, Laterality commented on src/test/java/racingcartest/CarListTest.java
> +        assertThat(String.join(StringConst.WINNER_DELIMITER.getValue(), winnerNameList)).isEqualTo("pobi, jun");
단위 테스트에는 테스트 대상에 필수적인 요소만 사용하는 것이 좋습니다.

"만약 출력 형식이 바뀌는 `CarListTest`까지 바뀌어야 할까?"라고 반문해볼 수 있겠네요.

2022-02-18 00:24 UTC, Laterality requested changes
안녕하세요 알파, 피드백을 잘 반영해주셨네요.

피드백을 반영하는 작업이 단순히 시키는 대로 코드를 고치는 작업이 아니라 문제점을 발견하고, 왜 문제인지 고민해보고 좋은 코드를 작성할 수 있는 기술을 쌓으시는 과정이 됐으면 좋겠습니다.

사소한 부분에 코멘트를 남겨드렸어요. 이 부분만 확인 부탁드릴게요!

2022-02-18 05:55 UTC, bcc0830 commented on src/main/java/racingcar/view/InputView.java
> +	public static void checkNameError(String nameInput) throws IllegalArgumentException {
삭제한 `private static String checkTurnError(String str)`과 현재 있는 `public static String checkTurnError(String turnInput)`는 전혀 다른 기능을 담당하는 메소드였습니다. 
 원래 존재하던 checkTurnError는 유효성 검증을 다 하고 나서 "[ERROR]"라는 문자열이 있는지 확인하여 에러가 있다면 적절하지 않은 횟수 입력에 대한 flag로서 "-1"을 리턴하고, 반대로 정확한 횟수 입력은 그대로 리턴하게 하는 메소드 였습니다. 
 현재의 기능은 유효성 검증 자체를 하는 메소드입니다. 구조를 전반적으로 리팩토링하는 과정에서 무의식적으로 이름을 같게하여 혼란을 드린 것 같습니다. 죄송합니다

2022-02-18 05:56 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +	private static final String POSITION_DELIMITER = "-";
OutputView 클래스가 수정되어야 한다고 생각합니다!

2022-02-18 10:36 UTC, Laterality commented on src/main/java/racingcar/view/InputView.java
> +	public static void checkNameError(String nameInput) throws IllegalArgumentException {
잘 이해가 안되는데요 😕 

제가 궁금한 점은 `checkNameError`가 public일 필요가 있는가 하는 부분이었습니다.

2022-02-18 11:56 UTC, bcc0830 commented on src/main/java/racingcar/view/InputView.java
> +	public static void checkNameError(String nameInput) throws IllegalArgumentException {
전 checkTurnError를 말씀하신 줄 알았습니다 :sweat_smile: 확실히 InputView에서만 쓰이기 때문에 public일 필요는 없다고 생각합니다...

2022-02-18 13:44 UTC, Laterality commented on src/main/java/racingcar/view/InputProcessView.java
> +public class InputProcessView {
1. 클래스의 책임이 불명확합니다. 이름은 View지만 내부에서 하는 일은 인자로 받은 값을 검증하는 일 뿐이네요.
2. public 메서드명이 `get`으로 시작하면서 getter 성격의 메서드임을 암시하지만 실제 내부 동작도 그럴까요?

값에 대한 검증 로직을 입출력과 분리하는 아이디어는 좋은 시도입니다 👍 

힌트를 드리면, 이 검증 로직은 Model/View/Controller 중 어느 영역의 관심사일까요?

여기서 검증하는 조건들은 어디로부터 온 걸까요?

2022-02-20 01:42 UTC, bcc0830 commented on src/main/java/racingcar/view/InputProcessView.java
> +public class InputProcessView {
검증하는 조건은 UserInputView에서 왔습니다. 그렇기 때문에 검증 로직은 View의 관심사입니다!

2022-02-20 08:04 UTC, Laterality requested changes
안녕하세요 알파, 에단입니다 :)

피드백을 꼼꼼히 반영해주셨네요.

View-Controller 간 책임만 적절히 분리되면 이번 미션은 마무리할 수 있겠네요. 코멘트 남겨드린 부분만 확인 부탁드려요.

고지가 멀지 않았어요, 화이팅!

2022-02-20 08:04 UTC, Laterality commented on src/main/java/racingcar/controller/GameController.java
> +			playGame(InputViewChecker.checkTurnInput(new UserInputView().getUserInput()), carList);
1. `UserInputView`는 입력을 받을 때마다 인스턴스를 매번 새로 생성해야 하는 걸까요?
2. 컨트롤러에서 `InputViewChecker`를 호출해서 유효성을 검증하고 있네요. 입력값을 검증하는 것은 어느 영역에 있어야 할까요?
    a. 입력값의 유효성을 검증하는 일이 뷰의 책임이라면 View에서 검증된 입력값을 반환해야 할 테고요.
    b. 컨트롤러의 책임이라면 `InputViewChecker`가 뷰 영역에 위치하는 것은 적절하지 않아보여요.

2022-02-20 08:04 UTC, Laterality commented on src/main/java/racingcar/model/Car.java
> +	public static final int BASE_POSITION = 0;
이 상수는 public이어야 할까요?

2022-02-20 08:04 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +	public List<Integer> getEachCarPosition() {
비슷한 메서드와 이름을 통일하면 사용자가 메서드의 동작을 이해하기 더 쉽습니다.

2022-02-20 08:04 UTC, Laterality commented on src/main/java/racingcar/model/CarList.java
> +        return (ArrayList<String>) this.carList.stream().filter(car -> car.isWinner(maxPosition)).map(Car::getName).collect(Collectors.toList());
반환타입은 그대로 `List`일 것이기 때문이 컴파일도 문제없이 성공할 거에요.

캐스팅이 실제로 수행되는 것은 코드가 실행되는 시점이기 때문에 컴파일에서 오류 여부를 알 수 없습니다. 

아래 코드를 실행해보면 알 수 있는데요.

```java
// LinkedList -> List -> ArrayList 순서로 캐스팅
ArrayList<String> list = ((ArrayList<String>) ((List<String>) new LinkedList<String>()));
```

위 코드는 문법 상으로 아무런 문제 없는 코드입니다. 때문에 컴파일도 문제 없이 성공하지만 코드를 실행하면 `ClassCastException`이 발생합니다. 때문에 캐스팅과 관련된 문제는 컴파일 시점에 인지하기 어렵습니다.

이러한 이유로 캐스팅은 꼭 필요한 상황에서만 신중하게 사용하고, 캐스팅이 실패하는 경우를 대비한 방어코드를 추가하는 것이 좋습니다.

다만 캐스팅을 해도 안전한 경우가 있는데요. `Collectors.toList`에서 `ArrayList`를 `List`로 암묵적으로 캐스팅해서 변환하는 케이스가 그 예입니다. 이 부분에 관해서는 "업 캐스팅"과 "다운 캐스팅"이란 키워드에 관해 공부해보시면 도움이 될 거에요.

2022-02-20 10:33 UTC, bcc0830 commented on src/main/java/racingcar/controller/GameController.java
> +			playGame(InputViewChecker.checkTurnInput(new UserInputView().getUserInput()), carList);
1. GameController에서 한번만 생성하면 될 거 같습니다
2. 뷰의 책임이라고 판단했기 때문에 View에서 처리하도록 하겠습니다!

2022-02-20 10:33 UTC, bcc0830 commented on src/main/java/racingcar/model/Car.java
> +	public static final int BASE_POSITION = 0;
private이 적절하다고 생각합니다

2022-02-21 03:16 UTC, Laterality approved these changes
안녕하세요 알파.

피드백을 잘 반영해주셨네요.

코멘트를 여러 방면으로 드려서 쉽지 않았을 텐데, 고생 많으셨습니다.

이번 미션은 여기서 마무리하도록 할게요 :)

그냥 가면 아쉬우니, 한가지 고민해볼 만한 부분을 남겨드릴게요.

첫 번째는 `Checker`, `Validator`와 같은 검증 목적의 클래스가 필요한가 하는 점인데요.

객체가 능동적으로 어떤 행위를 수행한다기보다는 수동적으로 받은 입력에 대한 검증만을 처리하고 있어요. 어딘가에 있어야 할 기능이 불필요하게 분리된 것은 아닌지 고민해보시면 좋겠습니다.

두 번째는 사용자의 입력에 대한 검증을 `InputViewChecker`가 모두 처리하고 있는데요.

여기서 검증하고 있는 내용들이 정말 모두 뷰의 관심사인지 고민해보시면 좋겠습니다.

만약 뷰가 다른 구현체로 바뀌었을 때도 일관되게 검증해야 하는 내용을 `InputViewChecker`에서 검증하고 있다면 이는 뷰가 아닌 다른 곳에서 검증해야 하는 조건일 수 있어요. 콘솔 뷰를 새로 구현해보시거나 `InputStream`/`OutputStream`을 통해 입출력을 처리하는 뷰를 새로 구현했을 때 검증 로직이 동일하지는 않은지 실험해보시면 뷰, 컨트롤러, 모델 각 컴포넌트에서 어떤 것들을 검증해야 할 지 감이 오실 거라고 생각해요.

2022-02-21 03:16 UTC, merged