[2단계 - 자동차 경주 리팩터링] 아서(김현태) 미션 제출합니다.
woowacourse/java-racingcar pull request #361
Opened 2022-02-16 08:41 UTC by Hyunta

안녕하세요 에단! 아서입니다:)

2단계 미션은 MVC패턴 기반으로 리팩토링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현하는 리팩터링 미션이었습니다.
기존에 패키지를 구분해둬서 어떤 부분을 손봐야할지 모르겠어서 고민하는 시간을 많이 보냈습니다.

1. validator의 위치?역할?
1단계에서 구현한 코드는 검증과정을 view 패키지의 클래스에서 하다보니 `Car`를 생성할 때 `InputView`에 의존을 한다고 생각하여 검증하는 과정을 `GameController`로 가져왔습니다. 혹시 검증하는 과정을 `Car`으로 옮기는 것이 더 응집성이 있는 코드일까 하는 생각이 드는데 `Car` 도메인에서 검증도 담당하는게 과연 적절할까 하는 의문이 듭니다, 뭔가 코드가 길어지고 복잡해질 것 같다는 이유가 전부이긴 합니다.

2. 형변환을 얼마나 검증해줘야하는지 궁금합니다.
```java
    private int getProperMoveCount() {
        try {
            String moveCount = InputView.getMoveCount(scanner);
            MoveCountValidator.validateMoveCount(moveCount);
            return Integer.parseInt(moveCount);
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
            return getProperMoveCount();
        }
    }

```
`GameController` 에 있는 메서드입니다. `return Integer.parseInt(moveCount);` 이 부분이 노출되어있는데, 위에 validate 메서드를 통해 검증된 값이기 때문에 바로 변환해서 반환을 해줬는데 `Converter` 클래스를 따로 만들어서 변환한 값을 반환하는 것이 더 괜찮을지에 대해 궁금합니다.

제 코드가 아직 많이 부족한데, 어디를 개선해야할지도 잘 모르겠습니다.
수정해야하거나 고민해봤으면 하는 코드를 지적해주시면 최대한 공부해보겠습니다!!
바쁘신 와중에 시간내주셔서 감사합니다😁👍🏻

2022-02-16 13:59 UTC, Laterality requested changes
안녕하세요 아서, 리뷰어 에단입니다.

잘 구현해주셨네요. 몇가지 의견을 남겨드렸는데, 확인 부탁드립니다.

## Q&A

1. validator의 위치, 역할

    "도메인의 검증"이라 함은 도메인의 문제 해결(기능)을 위해 지켜져야 하는 전제 조건과 제약사항을 지키는지 확인하고 객체가 살아있는 동안 이를 보장한다는 걸 의미합니다. 

    예를 들어 `Car` 클래스에서 자동차의 이름을 검증한다는 것은 `Car`  객체가 사라지기 전까지 자신의 이름이 일정한 제약사항을 지킨다는 것을 보장하는 일이 되겠죠.

    그렇다면, 검증하는 로직을 도메인에 두는 것은 응집성을 높이는 일일까요, 단순히 코드를 복잡하게 만드는 일일까요?

2. 형변환을 얼마나 검증해야 하는지

    언급하신 `GameController`의 코드는 `validateMoveCount`에서 이미 `parseInt`를 통해 검증하고 있는데, 값을 반환하면서 `parseInt`를 다시 한번 호출하면서 중복으로 검증하고 있습니다. 일정한 로직이 중복으로 발생하고 있다면 합쳐져야 할 두 로직이 떨어져 있는 건 아닐지 한번 의심해 볼 수도 있겠네요 😉 

    검증되지 않아 불안한 요소가 있다면 테스트를 통해 이를 검증하는 것도 좋은 방법이 될 수 있습니다.

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/GameController.java
> +            System.out.println(e.getMessage());
오류 메시지를 출력하는 방법은 목적에 따라 두 가지 방법으로 나눌 수 있는데요.

* 사용자에게 오류가 발생했음을 알리는 게 목적이라면 View를 통해야겠죠?
* 개발자가 로그 등에 오류 상황을 기록하는 것이 목적이라면 오류 발생 지점 등과 같이 더 자세한 정보를 포함하는 `printStacktrace` 등의 메서드가 적절합니다.

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/domain/Car.java
> +    public void move(int value) {
👍

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/domain/Cars.java
> +            car.move(RandomNumberGenerator.makeRandom());
난수를 생성하는 메서드가 외부로 이동했지만 여전히 `makeRandom`을 직접 호출하면서 테스트하기 어려운 상태네요.

어떻게 하면 이 메서드를 테스트할 수 있을까요?

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/utils/RandomNumberGenerator.java
> +public class RandomNumberGenerator {
utils 패키지는 도메인과는 관련 없지만 여러 코드에 걸쳐 동일하게 사용되는 코드가 위치하는 것이 일반적입니다.

이 클래스는 `Random` 클래스처럼 난수를 생성하는 범용적인 이름을 가지고 utils 패키지에 위치해 있지만 실제로는 `RANDOM_NUMBER_BOUND`라는 어떤 요구사항에 맞춘 숫자 범위 내에서만 숫자를 생성하고 있네요.

이 클래스를 역할을 더 잘 나타낼 수 있는 이름과 패키지 위치는 없을까요?

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/GameController.java
> +            String carNames = InputView.getCarNames(scanner);
입력 메서드를 호출할 때마다 `scanner`를 넘겨주고 있는 것은 `InputView`가 static이기 때문일까요, 아니면 매번 입력마다 서로 다른 `scanner` 인스턴스가 사용될 수 있다고 보셨기 때문일까요?

2022-02-16 13:59 UTC, Laterality commented on src/main/java/racingcar/view/InputView.java
>      public static String getCarNames(Scanner scanner) {
단순히 내부의 필드를 반환하는 getter가 아니라 사용자로부터 입력을 받는 작업까지 한다면 `prompt`나 `ask`로 시작하는 이름은 어떨까요?

2022-02-18 08:08 UTC, Hyunta commented on src/main/java/racingcar/GameController.java
> +            System.out.println(e.getMessage());
지금의 경우에는 사용자에게 알리는 목적을 갖고 있으니 OutputView에서 처리할 수 있도록 변경했습니다.

2022-02-18 08:24 UTC, Hyunta commented on src/main/java/racingcar/GameController.java
> +            String carNames = InputView.getCarNames(scanner);
InputView가 static이기 때문에 그때그때 scanner를 넘겨주었습니다. 이 부분에 대해서는 자세히 고민해보지 못했네요. 프리코스 미션을연습 할 때는 view의 클래스들을 인스턴스로 만들어서 사용해본적도 있는데 솔직히 둘의 차이점을 잘 모르겠습니다...😅
view 인스턴스로 만들게되면 scanner를 한번만 받아도되서 유리하다고 생각이 드는데,, 확실하지가 않습니다 도움부탁드려요!!

2022-02-18 09:13 UTC, Hyunta commented
안녕하세요, 아서입니다!
피드백을 바탕으로 수정해보고 생각을 정리해봤습니다.
바쁘신 와중에 신경써주셔서 감사합니다!🙏🏻

1. `toString()` 메서드에 대한 고민

   1단계에서 주신 html로 출력했을 시에 문제점에 대해서 페어와 같이 얘기해봤습니다. 제가 `toString`메서드를 단순히 String으로 반환해주는 기능이라고 생각해서 구현했었는데, 깊이있게 알고자 이펙티브 자바의 12장을 읽고 고민해봤습니다. 콘솔로 출력할 때는 기능적으로 문제가 없지만, 이것도 응집성의 문제라고 생각했습니다. 어떤 형태로 출력할지도 도메인에서 정하는게 단일 책임 원칙을 위반한다고 생각하여, view 패키지의 클래스에서 관리하고 `toString`은 간결하면서 사람이 읽기 쉬운 형태의 유익한 정보를 반환하는게 옳다고 생각하여 책임을 view패키지로 옮겼습니다.

   의문점 : `OutputView` 클래스에 구현을 하다보니 getter를 쓰게되었는데, getter를 안쓰고 구현하는 방법은 없을까?

   

2. 도메인의 검증에 대해서

   >예를 들어 `Car` 클래스에서 자동차의 이름을 검증한다는 것은 `Car` 객체가 사라지기 전까지 자신의 이름이 일정한 제약사항을 지킨다는 것을 보장하는 일이 되겠죠.
   >
   >그렇다면, 검증하는 로직을 도메인에 두는 것은 응집성을 높이는 일일까요, 단순히 코드를 복잡하게 만드는 일일까요?

   주어진 메세지가 제약사항을 지키는지 검증하는 일은 `Car`가 스스로 하는 것이 응집성을 높이는 것이 아닐까 생각됩니다.  하지만 내부 메서드로 관리하는 것보다는 외부 유틸클래스를 만들어 검증하는 방식이 나아보입니다. 유지보수의 관점에서 비지니스 로직과 검증 로직은 분리해놓는게 리스크가 적어보여서 입니다. 혹시 틀렸다면 언제든지 지적해주세요😅

   `utils`  패키지의 `CarNameValidator`를 그대로 이용하면서 검증하는 시점을 Cars가 생성될 때로 변경했는데, 이러면 어디에서든 객체를 만들더라도 제약조건에 맞는지 검증하기 때문에 더 좋아보입니다. 

3. 중복 검증에 관하여

   >  언급하신 `GameController`의 코드는 `validateMoveCount`에서 이미 `parseInt`를 통해 검증하고 있는데, 값을 반환하면서 `parseInt`를 다시 한번 호출하면서 중복으로 검증하고 있습니다. 일정한 로직이 중복으로 발생하고 있다면 합쳐져야 할 두 로직이 떨어져 있는 건 아닐지 한번 의심해 볼 수도 있겠네요 😉
   >
   > 검증되지 않아 불안한 요소가 있다면 테스트를 통해 이를 검증하는 것도 좋은 방법이 될 수 있습니다.

   이 부분은 애매해서 아직 수정하지 않았는데 의견을 묻고싶습니다. 제 생각에 `MoveCountVaildator`가 검증도 하고 변환을 하는건 단일 책임 원칙에 어긋난다고 생각합니다. 그래서 int로 변환된 값을 보내주는게 맞나 싶으면서도 그러면 예외처리를 한번더 해야해서 코드가 복잡해진다고 생각합니다. 어떤 방법을 채택하는게 좋을지, 아니면 다른 관점을 공유해주시면 참고하겠습니다!

4. `startEachRace`에 대한 테스트

   > 난수를 생성하는 메서드가 외부로 이동했지만 여전히 `makeRandom`을 직접 호출하면서 테스트하기 어려운 상태네요.
   >
   > 어떻게 하면 이 메서드를 테스트할 수 있을까요?

   ```java
     public void startEachRace() {
           for (Car car : cars) {
               car.move(RandomNumberGenerator.makeRandom());
   ```

   처음에 어떻게 테스트해야하나 막막했는데, 남겨주신 코멘트들에 대해서 고민하다보니 자연스레 해결할 수 있었습니다. 이렇게 의도적으로 설계하신건지 모르겠지만 소름돋았습니다....ㅎㅎ

   `RandomNumberGenerator`를 따로 만들긴 했지만 `RANDOM_NUMBER_BOUND`요구사항에 맞는 난수만 생성하고 있어서 범용적인 역할을 부여했습니다. 따라서 클래스의 이름과 패키지의 위치를 변경하지 않고 범용적으로 만들기 위해서 메서드를 수정했습니다. 그랬더니 자연스럽게 테스트가 용이해졌습니다. 상수로 이용했던 bound를 입력받도록 구현하니, 테스트할 때 bound를 임의로 정할 수 있게되어서 테스트가 가능했습니다.

   **의문점:**

   a. 메서드를 오버로딩하여 테스트에 사용을 했는데 이렇게 해도 되는지 궁금합니다.

   b. `makeRandom`메서드를 테스트할 때 귀납적으로 구성하게되었습니다. 100회 반복해서 체크하는데 이 부분이 거슬립니다.. 어쩔 수 없는 한계인지 아니면 다른 방법이 있는지 궁금합니다.

정말 많이 모자랐는데 덕분에 성장하고 있음을 느낍니다!
아직도 많이 고쳐야할 점이 많지만 지속적으로 고민할거리를 던져주셔서 너무 좋습니다!!
이번에도 시간내주셔서 봐주셔서 진심으로 감사합니다👍🏻

2022-02-18 11:58 UTC, Laterality requested changes
안녕하세요 아서,

추가로 개선해보면 좋을 만한 부분들에 코멘트를 남겨드렸어요. 확인 부탁드릴게요.

1단계에서 남겨드린 코멘트를 참고해보시면 도움이 될 거에요!

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/GameController.java
> +            String carNames = InputView.getCarNames(scanner);
`InputView`가 static이라 넘기셨다면 그 다음으로는 "`InputView`가 왜 static인가, static이어야 하는가"를 고민해볼 수 있겠어요.

지금의 `InputView`처럼 본문이 static 메서드로만 이루어진 클래스에서, 메서드들이 공통적으로 특정 인자를 받고 있다면 그 인자가 사실은 non-static 클래스의 필드여야 한다는 신호일 수도 있습니다.

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/domain/Cars.java
> +    public int findMaxPosition() {
클래스 외부에서 사용되는 곳이 테스트 뿐이네요.

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/utils/CarNameValidator.java
> +public class CarNameValidator {
util 패키지/클래스/메서드의 역할과 갖춰야 할 요건들에 대해 고민해보시면 좋겠어요.

일반적으로 프로젝트 내의 여러 부분에서 공통적으로 필요로 하는 작업들을 주로 util이라는 패키지에 두는데요. 예를 들면 시간을 변환하는 작업(특정 타임존의 시간으로 변환하거나, Unix epoch를 `LocalDateTime` 등으로 변환하는 등)이 있습니다. 

위 문장에서 알 수 있듯, util 클래스는 보통 프로젝트 내라면 어디서든지 호출될 수 있기 때문에 한 메서드를 수십군데에서 호출하는 경우도 생깁니다.

이러한 특징으로 인해 구현이 변경될 경우 미치는 파급력 또한 큰데요. 그렇기 때문에 구현은 최대한 단순하고, 변경 가능성이 매우 낮으면서도 도메인 로직과는 관계 없는 작업을 수행해야 합니다.

`CarNameValidator`는 이러한 요건에 부합할까요?

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/domain/Cars.java
> +        return cars;
`cars` 필드를 그대로 반환하면 클라이언트가 내부의 참조를 그대로 갖게 되고, 이로 인해 `cars` 필드와 이 컬렉션에 속한 객체를 마음대로 조작할 수 있게 됩니다.

2022-02-18 11:58 UTC, Laterality commented on src/test/java/racingcar/domain/CarTest.java
>  }
파일의 끝에는 new line을 넣어주세요.

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/domain/Cars.java
> +            car.move(RandomNumberGenerator.makeRandom(bound));
`startEachRace(int)`와 `startEachRace(int,int)`는 테스트에서만 사용되는 메서드네요.

이전 [PR의 코멘트](https://github.com/woowacourse/java-racingcar/pull/284#pullrequestreview-881502413)를 참고해주세요.

2022-02-18 11:58 UTC, Laterality commented on src/main/java/racingcar/view/OutputView.java
> +
코드와 코드 사이에 빈 줄은 최대 하나만 사용해주세요.

2022-02-19 10:31 UTC, Hyunta commented on src/main/java/racingcar/domain/Cars.java
> +    public int findMaxPosition() {
해당 메서드를 private으로 만들고 필요한 메서드를 테스트 클래스에서 구현했습니다

2022-02-19 11:29 UTC, Hyunta commented on src/main/java/racingcar/domain/Cars.java
> +        return cars;
`CarDto ` 를 통해 정보를 전달할 수 있도록 수정했습니다.

2022-02-19 11:35 UTC, Hyunta commented on src/main/java/racingcar/utils/CarNameValidator.java
> +public class CarNameValidator {
설명을 들으니 확실이 utilj적인 성향은 없는 것 같아서 `Car` 클래스와 같은 위치로 옮겼습니다.
사실상 검증 기능이 `Car` 객체를 생성할 때만 사용하는데 `Car` 내부로 옮기는 것 에 대해서는 어떻게 생각하시나요? 저는 클래스가 복잡해보이기도 하고 나중에 검증 기능을 수정할 때 비지니스 로직과 같은 위치에 있는게 불안해서 분리해두고 싶은데 패키지를 새로 만드는게 좋을까요?

`MoveCountValidator` 또한 마찬가지로 util 적인 성향은 없다고 생각되는데 이것도 옮기는게 좋을까요? validator 패키지를 만들어서 옮기는 것도 괜찮은 방법일까요?

2022-02-20 05:51 UTC, Hyunta commented on src/main/java/racingcar/domain/Cars.java
> +            car.move(RandomNumberGenerator.makeRandom(bound));
`startEachRace(int minBound, int maxBound)` 로 최소와 최대 범위를 설정할 수 있도록 변경했습니다.

2022-02-20 06:15 UTC, Hyunta commented on src/main/java/racingcar/GameController.java
> +            String carNames = InputView.getCarNames(scanner);
`InputView`가 같은 `scanner`를 사용하기를 바라서 static으로 만들기 보다는 non-static 으로 만들어서 같은 `scanner`를 사용할 수 있도록 변경했습니다.

2022-02-20 09:02 UTC, Laterality requested changes
안녕하세요 아서, 에단입니다 :)

몇 군데만 개선되면 이번 미션을 마무리할 수 있겠네요.

코멘트 확인 부탁드리고, 어려우신 부분이나 잘 이해가 안되는 부분이 있다면 코멘트를 남겨주셔도 좋고 DM으로도 질문해주세요!

2022-02-20 09:02 UTC, Laterality commented on src/main/java/racingcar/utils/CarNameValidator.java
> +public class CarNameValidator {
`XX`라는 도메인 객체와 `XXValidator`라는 객체가 쌍으로 등장하는 경우가 많다면 두 클래스가 합쳐져야 하는 것은 아닌지 고민해볼 수 있겠네요.

`Car` 객체를 생성할 때 검증해야 하는 유효성은 `Car`와 밀접한 관련이 있는 로직일 텐데요. 이를 다른 클래스로 분리하는 것이 오히려 응집성을 떨어트리는 것은 아닌지도 생각해볼 부분입니다. 

"클래스가 복잡해보이"고 "비지니스 로직과 같은 위치에 있는 게 불안"하기 때문에 둘을 합치는 것이 망설여지신다면, 무엇 때문에 클래스가 복잡해지는지, 무엇 때문에 비지니스 로직과 같은 위치에 있는 것이 불안한지를 제시할 수 있어야 합니다.

클래스가 복잡한 이유는 단순히 코드를 엉망으로 작성했기 때문일 수도, 실제로 문제 영역(도메인) 자체가 복잡한 경우일 수도 있는데요. 코드가 엉망이라면 리팩터링이 필요할 테고, 문제 영역이 복잡하다면 이를 어떻게 풀어내야 할 지 다시 고민해봐야겠지요. 불안감을 주는 요인이 무엇인지에 대해서도 마찬가지로 그 원인을 찾아 테스트를 추가하거나 코드를 적절히 분리하는 것으로 해결하는 것이 좋겠습니다.

2022-02-20 09:02 UTC, Laterality commented on src/main/java/racingcar/GameController.java
> +    private static final int RANDOM_NUMBER_MAX_BOUND = 9;
상수 이름에 `RANDOM`이 있는 것으로 보아서는, `GameController`는 숫자가 랜덤으로 생성된다는 내부 로직을 알고 있는 걸까요?

2022-02-20 09:02 UTC, Laterality commented on src/main/java/racingcar/GameController.java
> +            cars.startEachRace(RANDOM_NUMBER_MIN_BOUND, RANDOM_NUMBER_MAX_BOUND);
숫자의 생성 범위를 외부에서 제어할 수 있어야 할까요?

혹시 테스트를 위한 것은 아닐까요?

[자동차 경주 피드백](https://techcourse.woowahan.com/s/NASxoOCp/ls/HTlB35ml)을 참고하셔서 숫자를 생성하는 부분을 분리해보시면 좋겠어요.

2022-02-20 13:53 UTC, Hyunta commented on src/main/java/racingcar/utils/CarNameValidator.java
> +public class CarNameValidator {
`Car` 과 `CarNameValidator` 는 분리되어있으면 오히려 코드의 응집성을 떨어뜨리는 것이 맞는 것 같습니다. 클래스가 복잡해지는 이유는 단순히 코드가 길어지는 것이 복잡하다고 생각했던 것 같습니다. 반대로 정적 클래스를 사용하지 않고 도메인 내에서 검증이 이뤄진다고 생각하면 클래스가 단순해졌다고 보는게 맞다고 생각했습니다. 해당 클래스는 삭제하고 각각 `Car` 과 `Cars` 클래스에서 검증하도록 변경했습니다.

2022-02-20 15:12 UTC, Hyunta commented
안녕하세요 에단, 아서입니다!
두가지 코멘트 확인하고 수정해봤습니다.

1. **`Car`과 `CarValidator`은 합치는게 코드의 응집도를 높인다고 판단하여 검증기능을 도메인으로 옮겼습니다.**
a. 클래스가 복잡해지는 이유는 단순히 코드가 길어지는 것이 복잡하다고 생각했던 것 같습니다. 
b. 오히려 정적 클래스를 사용하지 않고 도메인 내에서 검증이 이뤄진다고 생각하면 응집도가 높아지는 것 같습니다. 해당 클래스는 삭제하고 각각 `Car` 과 `Cars` 에서 검증하도록 변경했습니다.

2. **`startEachRace()` 를 테스트하기 위해서 전략패턴을 사용해봤습니다.**
a. 컨트롤러에서 숫자의 생성 범위를 제어하는 것은 책임이 위임되어 안좋은 것 같습니다. 하지만 숫자가 랜덤으로 생성된다는 것을 노출하는건 왜 문제가 되는지 잘 모르겠습니다.
b. 테스트를 하기 위해서 구현체를 두개 만들었습니다. 테스트패키지 안에 있기때문에 무관하다고 생각하는데 이것또한 문제가 되는지 궁금합니다.

2022-02-21 03:35 UTC, Laterality approved these changes
안녕하세요 아서, 피드백을 잘 반영해주셨네요 👍 

이번 미션은 여기서 마무리하도록 할게요. 고생 많으셨습니다 :)

## Q&A

Q. 숫자가 랜덤으로 생성된다는 것을 노출하는 부분이 왜 문제인가

1. 이 부분은 숫자 생성 전략이 외부로 분리된다는 가정 하에 말씀드렸던 건데, 타이밍이 좀 이상했네요 😅
    숫자 생성 전략을 분리하게 되면 `GameController`에서는 숫자가 생성되는 방법에 대해서는 전혀 알 수 없게 될 테니, 생성 전략이 분리된 뒤에도 숫자의 범위를 `GameController`가 알고 있어야 한다면 `RANDOM`과 같이 구체적이 생성 전략이 포함된 이름은 적절하지 않다는 취지로 남겨드렸어요.
2. 좋은 접근입니다 👍 
    다형성의 장점 중 하나죠. 테스트에 편리하게 사용할 수 있는 구현체를 만들어 활용할 수 있는데요. 일반적으로는 미리 입력된 값을 순서대로 반환하거나 하는 등의 간단한 구현을 갖는 경우가 많아서 테스트가 필요한 경우는 많지 않은데요. 만약 구현이 다소 복잡하거나 본인이 생각하기에 테스트가 필요하다고 생각된다면 테스트를 작성하셔도 무방합니다.

2022-02-21 03:36 UTC, merged

2022-02-21 11:29 UTC, Laterality commented
앗, 질문을 남겨주셨는데 제가 못보고 지나쳤네요. 늦었지만 참고가 될 지 몰라 남겨드려요 🙏 

1. 메서드를 오버로딩하여 테스트에 사용을 했는데 이렇게 해도 되는지 궁금합니다.
   테스트만을 위해 오버로딩한 메서드를 추가하는 것이라면 마찬가지로 테스트를 위해 메서드가 만들어진 경우라고 봐야겠습니다. 테스트를 위해 오버로딩했다고 하더라도 작성자가 의도하지 않은 방향으로 메서드가 사용될 수 있으니까요.

2. makeRandom메서드를 테스트할 때 귀납적으로 구성하게되었습니다. 100회 반복해서 체크하는데 이 부분이 거슬립니다.. 어쩔 수 없는 한계인지 아니면 다른 방법이 있는지 궁금합니다.
    테스트하기 어려운 몇 가지 대표적인 유형들이 있는데요. 난수, 날짜와 시간, 그리고 멀티 스레드를 사용하는 동시성 코드입니다. 유형별로, 테스트하는 상황별로 테스트 방법이 있긴 하지만 완전히 테스트하기 어렵다는 점이 특징입니다. 난수 생성에 관해서는 범위와 횟수가 적절히 조절된다면 말씀하신 것과 같은 방법이 최선이라고 생각해요. 가장 좋은 것은 이런 요소를 사용하지 않는 것이겠지만, 만약 기능 구현에 필요하다면 이런 요소들을 테스트하기 용이한 다른 부분들과 잘 분리할 것인지 고민하는 게 가장 중요하겠죠?