[2단계 - 자동차 경주 리팩터링] 잉(유영우) 미션 제출합니다.
woowacourse/java-racingcar pull request #363
Opened 2022-02-16 09:18 UTC by Yboyu0u

안녕하세요 잉입니다.

2022-02-17 09:27 UTC, sonypark requested changes
잉 안녕하세요~~
2단계 리뷰를 빠르게 주셨군요!
질문에 대한 답변과 추가 코멘트 남겼으니 확인부탁드릴게요😃

---

**1. view의 책임에 관해**
아래 코멘트를 참고해주세요 :)

**2. 검증로직**
검증의 우선순위는 도메인 > 서비스/컨트롤러 > 뷰 라고 생각해요. 가장 중요한건 검증되지 않은 도메인 객체가 생성되지 않도록 하는 것입니다. 앞 단에서 아무리 검증 로직으로 방어를 했어도 도메인 로직에 검증이 로직이 없으면 언제든 비즈니스 규칙에 어긋난 객체가 생성될 수 있다는 뜻이니까요. 실수로 앞단에 검증로직을 빼먹을 수도 있고, new Car()로 직접 호출하여 검증 로직을 거치지 않을수도 있구요. 정리하자면, '검증로직은 여러곳에도 해도 되지만 우선순위가 높은 순으로 해주자'가 저의 생각입니다. 잉의 생각은 어떤가요?

**3. stream max() vs compareTo()**
잉의 생각이 궁금하네요. 잉은 stream max()를 이용한 정렬이 더 낫다고 판단해서 이렇게 구현하신건가요? 그렇다면 왜 그렇게 생각하셨나요? 같이 토론해봅시다 :)

2022-02-17 09:27 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +	}
InputView가 도메인 객체를 생성하는 역할까지 담당하는 것에 대해 어떻게 생각하시나요?
InputView에서는 자동차의 이름만 전달 받고 도메인 객체는 도메인 레벨에서 생성해주는 것이 자연스럽지 않을까요?
현재 로직에서는 InputView가 달라지면(console -> web) 새로운 InputView에서 또다시 Car를 생성하는 로직이 들어가야 할 거에요.

2022-02-17 09:27 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +	}
Count에 숫자가 아닌 문자가 들어가면 어떻게 되나요? 사용자에게 어떤 메시지가 갈까요?

2022-02-17 09:27 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
>      }
Car의 생성자에 MovingPolicy가 필요할까요?
만약 Car를 한 번 생성해서 MovingPolicy를 변경하고 싶으면 어떻게 해야될까요?
현재로서는 새로 Car객체를 만들거나 MovingPolicy를 업데이트해주는 함수를 만들어야할텐데요.
좀 더 변경에 유연한 구조로 개선할 수는 없을까요?

힌트: move 메서드, 의존성 주입

2022-02-17 09:27 UTC, sonypark commented on src/main/java/racingcar/domain/Racing.java
>  		cars.forEach(Car::move);
핵심 비지니스 로직이 들어있는 클래스인데 테스트 코드가 없네요..🥲

2022-02-17 09:27 UTC, sonypark commented on src/main/java/racingcar/validator/RacingCarValidator.java
> +		}
Set 자료구조를 사용한 중복제거 체크 👍
Set 자료구조를 사용했다면 List와 Set의 size 비교만으로 중복 검증을 할 수 있지 않을까요?

힌트: overlapChecker.size(), carNames.size()

2022-02-17 09:27 UTC, sonypark commented on src/test/java/racingcar/validator/RacingCarValidatorTest.java
> +		);
😂

2022-02-18 08:53 UTC, Yboyu0u commented on src/main/java/racingcar/view/InputView.java
> +	}
그냥 NumberFormatException()이 뜨더라고요,,,,, 이 문제를 해결하기 위해 

~~~
public Count(String input) {
		try {
			int number = Integer.parseInt(input);
			RacingCarValidator.validateCount(number);

			this.count = number;

		} catch (NumberFormatException ex) {
			throw new IllegalArgumentException(NOT_INT_ERROR);
		}
	}
~~~

다음과 같이 생성자에서 예외 처리를 해주었는데 뭔가 보기 지저분한 것 같기도 하네요. ㅎ
예외처리를 validator class에서 처리하는 것을 제일 먼저 생각했었는데 그렇게 되면 
Interger.parseInt()를 두 번 처리해야 하는 문제가 발생하더라고요. 

위의 코드처럼 해도 괜찮은 방법일까요??

2022-02-18 09:01 UTC, Yboyu0u commented on src/main/java/racingcar/domain/Car.java
>      }
피드백을 받고 고민해 봤는데 전략이 바뀐다는 생각은 안해봤던 것 같네요....

~~~
public void move(MovingPolicy movingPolicy) {
        if (movingPolicy.isMovable()) {
            position++;
        }
    }
~~~

다음과 같은 구조로 변경해봤습니다!

2022-02-18 09:05 UTC, Yboyu0u commented on src/main/java/racingcar/view/InputView.java
> +	}
View의 원초적인 기능과 책임에 대해 망각하고 있던 것 같습니다. 
그저 InputView는 메서드가 적지만 domain의 class에는 많은 메서드가 들어가 있어서 InputView에서 처리하는 것이 깔끔해 보인다는 이유로 저렇게 하였었는데 
피드백 감사합니다!!

2022-02-18 09:06 UTC, Yboyu0u commented on src/main/java/racingcar/validator/RacingCarValidator.java
> +		}
~~~
Set<Car> overlapChecker = new HashSet<>(carNames);
		if(overlapChecker.size() != carNames.size()) {
			throw new IllegalArgumentException(CAR_NAMES_DUPLICATE_ERROR);
		}
~~~

위와 같이 변경했습니다!
훨씬 깔끔해졌네요. 감사함다 ㅎㅎ

2022-02-18 09:13 UTC, Yboyu0u commented on src/main/java/racingcar/domain/Racing.java
>  		cars.forEach(Car::move);
src/test/racingcar/domain/RacingTest에 추가했습니다!

2022-02-18 09:35 UTC, Yboyu0u commented
## 검증로직에 대한 생각 
'검증로직은 여러곳에도 해도 되지만 우선순위가 높은 순으로 해주자'
소니님의 의견이 맞다고 생각해요. 사실은 '검증' 이라는 것에 그렇게 큰 생각은 안해봤던 것 같아요.
그저 좀 더 깔끔하게 코드를 작성하려면 어떻게 해야되지? 라는 얕은 생각으로만 접근 했었네요....
한 수 배워갑니다🙏 

## stream max() vs compareTo()
사실 처음에 코드를 짤 때는 후자를 이용하는 방법을 생각 못하고 그냥 전자의 방법으로 코드를 짰습니다.
 
근데 리팩토링 중에 후자의 방법이 생각나서 질문을 드린 건데 제 생각에는 stream max()를 이용한 방법이 더 나은 것 같기는 합니다. 

이유는 나중에 compareTo()를 사용해야만 하는 기능이 추가될 수 있어서(postion값 말고 다른 인스턴스 변수들을 이용해 정렬해야 하는 상황?) 굳이 사용하지 않아도 되는 부분에는 전자의 방법을 이용하는 방법이 적합하다는 생각이 들긴 하네요….. 

소니 생각은 어떠신가여??

2022-02-18 12:13 UTC, sonypark commented on src/main/java/racingcar/view/InputView.java
> +	}
Count의 인자를 int 타입으로 받으면 어떨까요? 그렇게 되면 Integer.parseInt()도 필요 없을 것 같아요.
입력받은 문자열이 숫자인지에 대한 검증을 InputView에서 해줘도 될 것 같은데 어떻게 생각하시나요?
물론 Count에서 검증을 해줘도 되긴합니다:) 선택의 문제!😃

2022-02-18 12:13 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
>      }
:100:

2022-02-18 12:26 UTC, sonypark approved these changes
잉 안녕하세요~
질문 남겨주신 부분에 제 생각도 남겼으니 같이 고민하고 선택해봅시다 :)
코드상 크게 고칠 부분은 안 보여서 이만 merge 하겠습니다.
(스트링 배열을 사용하신 부분은 특별한 이유가 있다면 코멘트 남겨주세요~~)

**stream max() vs compareTo()**
둘 다 괜찮지만 굳이 고르자면 저는 전자를 사용할 것 같습니다. 그게 더 직관적이라고 생각해서요. 또한, 현재는 순위 기준이 position의 내림차순으로 변경된다면 Car에도 변경사항이 일어나게 되는데요. 순위 기준이 Car와 강하게 결합되어 있을 필요가 있을까라는 생각이 드네요. 외부에서 기준을 변경 하면 asc, desc로 간단히 변경/확인 가능하고 Car 자체에도 영향이 없어서 전자로 사용할 것 같아요~ :upside_down_face:

2022-02-18 12:26 UTC, sonypark commented on src/main/java/racingcar/domain/Racing.java
> +		List<Car> inputCars = getCars(carNames);
String[] 으로 받는 이유가 있을까요?

2022-02-18 12:27 UTC, merged

2022-02-19 06:06 UTC, Yboyu0u commented on src/main/java/racingcar/domain/Racing.java
> +		List<Car> inputCars = getCars(carNames);
InputView -> RacingController -> Racing 이 플로우로 String[] carNames가 전달 되는데 
**1. InputView**
```
	public static String[] getCarNames() {
		System.out.println(INPUT_CAR_NAMES_MESSAGE);
		String input = scanner.nextLine();

		return input.split(CAR_DELIMITER);
	}
```

**2. RacingController**
```
public void run() {
		String[] carNames = InputView.getCarNames();
		String tryNo = InputView.getCount();

		Racing racing = new Racing(carNames, tryNo);
		OutPutView.printStatusMessage();
		while (!racing.isEnd()) {
			OutPutView.printStatus(racing.race());
		}

		OutPutView.printResult(racing.getWinners());
	}
```
**3. Racing**
~~~
	public Racing(String[] carNames, String tryNo) {
		List<Car> inputCars = getCars(carNames);
		RacingCarValidator.validateCars(inputCars);

		this.cars = inputCars;
		this.count = new Count(tryNo);
	}
~~~
Racing 생성자에서 굳이 List<String>(List<Car>로 만드는 작업은 domain에서 하는게 적절하다는 피드백을 참고해서)으로 받고(제 생각으로는 controller에서 stream을 이용해 List로 바꿔서 전달하는 방법으로.) Racing에서 다시 List<Car>형태로 바꿀 필요가 없을 것 같아서 저렇게 하긴 했습니다! 뭔가 변환을 두 번(String[] -> List<String> -> List<Car>)하는 느낌이라고 해야하나,,,,, 

이런 생각으로 저렇게 하긴 했는데 자연스럽지 않거나 조금 이상하다면 피드백 주시면 감사하겠습니다🙇🏼‍♂️

2022-02-21 13:18 UTC, sonypark commented on src/main/java/racingcar/domain/Racing.java
> +		List<Car> inputCars = getCars(carNames);
InputView에서 List로 반환해주는건 어떤까요?