[2단계 - 자동차 경주 리팩터링] 칙촉(안영윤) 미션 제출합니다.
woowacourse/java-racingcar pull request #372
Opened 2022-02-16 16:37 UTC by Youngyoon-1

안녕하세요!! 😄 앨런 1단계에서 앨런의 피드백 덕분에 정말 많은 공부가 됐어요!! 감사해요🙏!!
피드백 주신대로 저도 검증기능이 순서 의존적이라는 생각이 들었어요. Null에 대한 예외처리는 Optional 클래스를 사용해서 생성자 내부에서 먼저 체크한 뒤에 다른 유효성 검증을 하도록 구현해봤어요!!
제가 질문드리고 싶은 부분은 위임받은 객체의 기능을 테스트 하는 것은 어떤 의미가 있는 걸까요?! 제 생각에는 이미 테스트 통과된 기능인데 이를 또 테스트 해야하나 싶은 생각이 들어서요!!

2022-02-17 23:08 UTC, hongbin-dev requested changes
안녕하세요 칙촉!
1단계에서 미션진행 잘 해주셔서 큰 이견이 없네요! 그 외 사소한 코멘트 남겨봐요. 확인해주세요 🙂

[https://github.com/Youngyoon-1/java-racingcar/blob/a5015b1583595da86e6c568f5ebb65bf771512b7/src/main/java/racingcar/controller/GameController.java#L13](https://github.com/Youngyoon-1/java-racingcar/blob/a5015b1583595da86e6c568f5ebb65bf771512b7/src/main/java/racingcar/controller/GameController.java#L13)
이 부분에서 컨트롤러가 가변이 될 가능성을 갖으면서 Count 객체와, RacingCarGame 객체를 멤버로 갖고 있는 이유가 있을까요?

[https://github.com/Youngyoon-1/java-racingcar/blob/a5015b1583595da86e6c568f5ebb65bf771512b7/src/main/java/racingcar/domain/RacingCarGame.java#L35](https://github.com/Youngyoon-1/java-racingcar/blob/a5015b1583595da86e6c568f5ebb65bf771512b7/src/main/java/racingcar/domain/RacingCarGame.java#L35)
승자를 구하는코드에 '게임이 종료 됐을때만 승자를 구할 수 있다'라는 검증로직이 들어가는게 어떨까요?

2022-02-17 23:08 UTC, hongbin-dev commented on src/main/java/racingcar/controller/GameController.java
> +                .orElseThrow(() -> new IllegalArgumentException("null은 사용할 수 없습니다. MoveStrategy타입을 사용하세요."));
개인적인 생각으론 Optional을 만드는 것도 비용인데요. Optional을 생성해서 예외를 만들어내기 위해 사용하는건 비효율적이라고 생각해요.
가볍게 null체크하는 방향으로 가는 건 어떨까요?

테코블에 optional의 대한 내용이 있군요! 참고하시면 좋을 것 같아요. [Optional 과 null 에 대해](https://tecoble.techcourse.co.kr/post/2021-06-20-optional-vs-null/)

2022-02-17 23:08 UTC, hongbin-dev commented on src/main/java/racingcar/domain/Car.java
> +                .orElseThrow(() -> new IllegalArgumentException("null은 사용할 수 없습니다. CarName타입을 사용하세요."));
이 부분도 마찬가지입니다.

2022-02-17 23:08 UTC, hongbin-dev commented on src/main/java/racingcar/domain/CarName.java
> +        if (name.isBlank()) {
검증로직을 static으로 잡은 이유가 있을까요?

2022-02-17 23:08 UTC, hongbin-dev commented on src/main/java/racingcar/domain/CarName.java
> +        if (name.isBlank()) {
```suggestion
    private static void checkBlank(String name) {
        if (Objects.isNull(name) || name.isBlank()) {
```
추가로 방어적으로 null 체크를 진행하면 좋겠네요.

2022-02-19 01:35 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> +                .orElseThrow(() -> new IllegalArgumentException("null은 사용할 수 없습니다. MoveStrategy타입을 사용하세요."));
넵 앨런!! 단순히 null체크해서 예외발생을 시키는데 비싼 비용이 드는 방법 보다는 Objects클래스를 사용하거나 기존 방법대로 null체크를 해볼께요!

2022-02-19 02:08 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> -        this.moveStrategy = Optional.ofNullable(moveStrategy)
이번 미션을 하면서 모든 객체에서 null체크를 해봤는데 지금은 괜찮지만 규묘가 큰 프로젝트에서는 모든 부분에서 null체크를 하기는 어려울 것 같아요. 코드도 길어지고 지금은 외부에 노출할 라이브러리를 만드는게 아니기 때문에 다른 사용자를 믿고 null 체크는 별도로 하지 않으려고 해요!!

2022-02-19 02:10 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> +        if (Objects.isNull(moveStrategy)) {
이번 미션을 하면서 모든 객체에서 null체크를 해봤는데 지금은 괜찮지만 규묘가 큰 프로젝트에서는 모든 부분에서 null체크를 하기는 어려울 것 같아요. 코드도 길어지고 지금은 외부에 노출할 라이브러리를 만드는게 아니기 때문에 다른 사용자를 믿고 null 체크는 별도로 하지 않으려고 해요!!

2022-02-19 02:13 UTC, Youngyoon-1 commented on src/main/java/racingcar/domain/RacingCarGame.java
> +    private Count count;
게임이 끝난 경우에 우승자를 뽑을 수 있도록 하기 위해서 count객체를 포함시켰어요!!

2022-02-19 02:18 UTC, Youngyoon-1 commented on src/main/java/racingcar/domain/CarName.java
> +        if (name.isBlank()) {
리펙토링 과정에서 깜빡하고 수정하지 못했던 부분이네요..

2022-02-19 02:24 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> -    private RacingCarGame racingCarGame;
생각해보니 횟수와 레이싱게임 객체 모두 멤버필드로 선언해서 관리해줄 필요가 없을것 같네요!!

2022-02-19 02:25 UTC, Youngyoon-1 commented on src/main/java/racingcar/domain/RacingCarGame.java
> +        this.count = count;
콘솔에서 사용자 입력값에 대한 예외 발생시 각각의 입력값을 다시 입력받도록 구현어요. 그런데 이름의 유효성 검증은 RacingCarGame에서 하기때문에 이름에 대한 유효성 검증을 위해서 RacingCarGame을 먼저 생성하게 됐어요.
그래서 count는 setter를 통해서 주입 시켜줬어요!! 또한 생성자를 통해 주입시키기에는 파라미터가 많은 것 같기도 해서요!

2022-02-19 02:27 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> +        }
이번 미션을 하면서 모든 객체에서 null체크를 해봤는데 지금은 괜찮지만 규묘가 큰 프로젝트에서는 모든 부분에서 null체크를 하기는 어려울 것 같아요. 코드도 길어지고 지금은 외부에 노출할 라이브러리를 만드는게 아니기 때문에 다른 사용자를 믿고 null 체크는 별도로 하지 않으려고 해요!!

2022-02-20 01:06 UTC, hongbin-dev requested changes
안녕하세요 칙촉!
전반적으로 MVC 구조를 잘 잡아주신 것 같아요 💯  
controller의 흐름에 대해 코멘트남겼으니 확인해주세요~ + 코멘트의 답변은 DM으로 드렸습니다

2022-02-20 01:06 UTC, hongbin-dev commented on src/main/java/racingcar/controller/GameController.java
> +        racingCarGame.setCount(count);
이 부분이 꼭 필요할까? 생각이 들어요.

RacingCarGame 객체생성시점을 count이후로 한다면 setter가 필요없어질 것 같은데요.
setter를 열어놓은다는건 상태를 변경할 수 있다는 여지를 주는 것 같아요.

```
RacingCars racingCars = getCarNamesWithDelimiter();
final Count count = getCountFromUser();

RacingCarGame racingCarGame = new RacingGame(racingCars, count); 
```
이런 플로우로 가는건 어려울까요? racingCarGame의 불변상태를 유지할 수 있을 것 같네요.

2022-02-20 01:06 UTC, hongbin-dev commented on src/main/java/racingcar/domain/RacingCarGame.java
> +        count.decrease();
RacingCarGame의 책임을 분리시켜준게 인상적이네요👍

2022-02-20 11:41 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> +        racingCarGame.setCount(count);
네!! setter을 없애고 기존 정책대로 콘솔 사용자의 입력값이 잘못 됐다면 거기서 부터 다시 입력 받도록 구현했어요. 그 과정에서 racingGame이 하던 split하고 자동차를 생성하는 역할을 util의 Convertor에게 줬어요!!

2022-02-20 13:11 UTC, hongbin-dev requested changes
안녕하세요 칙촉!
한가지 코멘트 남깁니다! 코멘트 확인해주세요 🙂

2022-02-20 13:11 UTC, hongbin-dev commented on src/main/java/racingcar/controller/GameController.java
> +            return new Cars(cars, moveStrategy);
UserInputConvertor를 따로 추가하신 이유가 있을까요?

`return new Cars(carNamesWithDelimiter, moveStrategy);` 이런 플로우도 있을텐데 말이죠!

어떤기준으로 객체를 나누셨는지 궁금합니다!

2022-02-20 13:30 UTC, Youngyoon-1 commented on src/main/java/racingcar/controller/GameController.java
> +            return new Cars(cars, moveStrategy);
안녕하세요! 앨런 UserInputConvertor를 추가한 이유는 cars객체가 문자열을 split하고 자동차를 생성하는 역할을 분리하고 싶어서 별도로 만들어줬어요!!

2022-02-21 11:26 UTC, hongbin-dev approved these changes
안녕하세요 칙촉! 첫 미션 하시느라 고생많으셨어요.
마지막 코멘트 답변은 DM으로 남겨드렸어요 이만 머지하겠습니다 🙂

2022-02-21 11:26 UTC, merged