[2단계 - 자동차 경주 리팩토링] 루키(최지훈) 미션 제출합니다.
woowacourse/java-racingcar pull request #375
Opened 2022-02-17 00:33 UTC by Wishoon

토니! 다시 뵙게 되어 반갑습니다 🙋‍♂️🙋‍♂️

먼저 말씀드릴께 저의 깃 미숙으로 인해 제 `step2` 브랜치에 커밋 기록이 엉켜버려서 해결을 해보다가 부득이하게 `step3`으로 PR을 제출드립니다 😭😭 (깃에 대해서 좀 더 공부해보도록 하겠습니다 🥲)

이번 미션이 MVC 패턴이 중점으로 되어 있는데 1차 미션때 MVC 패턴을 적용한 것 같아 1차 미션의 피드백과 새로 공부한 내용을 위주로 리팩토링을 하여 PR을 요청드려봅니다 

추가적으로, 이번에 리팩토링을 하면서 고민했던 점 혹은 궁금한 점을 다시 여쭤보고자 합니다.

### 1. DTO의 사용

1단계에서 잘못 사용하고 있던 `DTO`를 리팩토링 해보았습니다. 단지 도메인을 `DTO`로 래핑하여 `View`로 전달하는 것이 아닌, 해당 도메인을 `Controller`에 전달한 후, 필요한 데이터만 'Controller'에서 `DTO`로 변환해주고 `View`가 이를 받아서 출력을 하는 로직으로 구현해보았습니다.

### 2. 원시값을 포장

1단계 코드에서 남아있던 원시값들을 객체로 포장하여 로직을 구현하였습니다. 다만, 각 자동차의 현재 위치를 비교하는 `compareTo`로직에 getter를 사용해서 값을 비교하고 있는데 해당 방법이 옳은 접근 방법이 아니라는 생각을 하고 있습니다. 해당 부분도 `Position`에 책임을 위임하는 방법으로 구현을 하는것이 좋은지 궁금합니다!!

```java
public class Car implements Comparable<Car> {
    // ...
    @Override
    public int compareTo(Car car) {
        return position.getPosition() - car.getPosition();
    }
}
```

### 3. 정적 팩토리 메서드 vs 생성자

1단계에서는 **단지 정적 팩토리 메서드에 이름을 부여할 수 있다라는 이유 때문**에 관성적으로 제가 정적 팩토리 메서드를 사용했다고 생각해요.

하지만 곰곰히 고민을 해보니깐 **굳이 생성자를 배재하고 정적 팩토리 메서드를 써야 하나?** 이런 생각을 하게 되었어요. 
 
리팩토링을 하면서 `DTO` 처럼 매개변수로 도메인을 받는 경우나, `View`에서 입력 데이터를 전달받을때만 정적 팩토리 메서드를 사용하는 방법으로 구현을 해봤어요.

이번 리팩토링을 하면서 정적 팩토리 메서드를 어떤 부분에 사용해야하는 것이 좋은지에 대한 내용을 읽어보고 고민은 해봤지만 아직 정확히 잘 와닿지가 않네요 😭😭

혹시 토니는 정적 팩토리 메서드를 사용하는 기준이 있는지 여쭤보고 싶어요!!

<br>

역시 부족한 코드지만 계속 발전시켜 나가보겠습니다. 토니 감사드립니다 🙇‍♂️🙇‍♂️

2022-02-17 12:24 UTC, toneyparky requested changes
고생하셨어요 루키!! 

지난 번에 이야기드린 부분에 대해서 고민을 많이 하시고 잘 반영해주셨네요 !! 

추가로 질문 주신 부분은 코멘트에 달아뒀으니 확인부탁드려요.

충분히 머지해도 좋을 코드지만, 루키와 조금 더 대화를 나누고 싶어서 몇가지 질문과 변경 요청드립니다!

고생하셨어요 😬

2022-02-17 12:24 UTC, toneyparky commented on docs/racingcar/README.md
> +## 2단계 - 기능 구현 목록
크.. 2 단계도 깔끔하게 정리해주셨군요! 좋습니다!

리팩터링 요구사항에 알맞은 도메인별 역할을 적어주셔서 확인하기 쉽네요!

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/controller/RacingGameController.java
> +            Round.fromNumber(InputView.getRound()),
이번에 루키가 정적 팩토리 메서드의 이름에 의미를 부여해보니 어떤 느낌이 들었나요??

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +        return position.getPosition() - car.getPosition();
두 번째 질문에 대해서 이야기하기 전에!

루키가 지금의 구현이 옳은 접근 방법이 아니라는 생각은 어떻게 하셨는지 궁금해요 😀

그럼에도 불구하고 지금 상태를 유지하신 이유도 말이죠!

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +        return Objects.equals(name, car.name) && Objects.equals(position, car.position);
객체로 묶게 되면 요 부분이 약간의 단점(?)이 되어버리죠! 부가적인 코드가 많아집니다. `equals ` 메서드도 더 복잡해졌죠!

그렇기에 원시값을 포장하며 얻는 이득과 손해를 고려하여 적용하면 좋아요! 

지금은 이름과 포지션이 각각 유효성 검사에 대한 로직을 가지게 되니 충분히 좋은 선택이라 생각해요 😁

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/domain/Name.java
> +    public Name(final String name) {
이렇게 인자에 final을 붙이면 어떤 장점이 있을까요?

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/domain/Name.java
> +    private static final String NAME_CONTAINS_BLANK = " ";
세 상수의 이름에 대해서 한 번만 더 고민해볼까요?!

위의 둘은 영문법을 명확하게, 아래 하나는 조금 더 추상적인 이름을 가져도 좋을 것 같아요.

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/domain/RacingGame.java
> -    }
세 번째 질문에 대해서 이야기를 해볼까요?

1 단계에서 루키가 정적 팩토리 메서드에 대해서 답변을 잘 달아주셨기에 장점에 대해서는 이해하고 계실거라 생각해요. 

이번에 주신 질문은 사용하는 기준이군요! 

제 생각을 말씀드릴게요. 

우선 장점을 살릴 수 있는 부분에는 사용합니다. 생성시에 복잡한 로직이 들어있거나, 의미를 담고 싶거나 할 때 말이죠 😊

그리고 이를 훼손하지 않는 선에서 **일관된** 규칙을 유지해요. 우테코에서도 혼자 개발하지 않으시죠? 현업에서도 마찬가지에요! 함께 개발하는, 리뷰하는 팀원들이 쉽게 이해할 수 있도록 이런 경우에는 사용하자라는 규칙을 정해요. 그리고 그 규칙은 팀의 상황이나 맡고 있는 프로젝트마다 달라지겠죠? 

이런 측면에서 루키가 이번에 고민한 포인트는 좋아요. 왜냐하면 리팩터링 과정에서 본인만의 규칙을 세우고 이를 지켜나갔기 때문이에요. 다음, 다다음 미션에서도 생성자와 정적 팩토리 메서드, 추후에는 빌더 패턴까지 포함한 고민을 하게 될거에요. 지금처럼 고민하시고, 함께 개발하는 분과 상의하며 결정하시다보면 지금의 흐릿함이 조금씩 명료해질거에요. 

명쾌한 답변으로 느껴지지 않을 수 있지만, 정답이 없는 게 프로그래밍의 묘미기도 하다는 이야기를 남기며...

---

이대로 가기 아쉬우니 저희 팀의 예시를 드리자면, 객체를 생성할 때에 주로 빌더 패턴을 사용하구요. 생성자보다는 정적 팩터리 메서드를 사용하는 편이에요. 특히 A 객체에서 B 객체를 생성해야할 경우에 말이죠. 

빌터 패턴은 참고 삼아 슥 찾아보셔도 좋을 것 같아요.

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/view/OutputView.java
> +import racingcar.dto.ResultDto;
첫 번쨰 질문이네요!

DTO에 대한 고민 좋아요. 

이번에는 조금 더 명확하게 차이가 생긴거 같네요!!

그렇게 느낀 이유는 DTO라고 생각하며 설계하셨지만 기존에 도메인 객체인 `Car`를 들고 있던 `RacingRecord`나 `RacingResult`가 사라지고 정말 필요한 값들만 들고 있는 DTO들이 생성되어서에요.

`CarDto`는 굳이 `Position`이나 `Name`의 객체를 들고 있을 필요 없고 원시 값만 들고 있으면 되죠!

지금은 MVC 패턴에서 컨트롤러가 모델과 뷰 사이에 의존성을 끊어주기 위한 DTO를 변환하는 역할도 잘 하고 있으니 적절한 리팩터링이라고 생각합니다!

💯

2022-02-17 12:24 UTC, toneyparky commented on src/main/java/racingcar/dto/RecordDto.java
> +}
DTO는 생성될 때에 전달하고자하는 값을 가지고 생성되죠!

그리고 그 값은 변하면 안되구요!

`getRacingRecord` 처럼 `unmodifiableList`로 반환해주는 건 좋은 선택이라고 생각해요! 그래야 사용하는 사람이나 코드가 마음대로 값을 바꿀 수 없으니까요. 

여기에 추가로 필드 선언시에 final을 붙이면 어떨까요? 물론 List라서 효용은 조금 떨어지지만 DTO의 불변성에 대해서 공부한다고 생각하면 좋을 것 같네요 🤓

2022-02-18 09:03 UTC, Wishoon commented on src/main/java/racingcar/controller/RacingGameController.java
> +            Round.fromNumber(InputView.getRound()),
확실히 `from`, `of` 로 메서드 네이밍을 했을때보다 인자값으로 어떤 값이 들어오는지 알 수 있어 명확한 의미 전달이 가능해진 것 같아요 😄

이를 통해, 명확한 객체 생성의 목적이 전달되어 추후 협업시 해당 로직을 상대방이 쉽게 이해할 수 있을 것 같아요!!

2022-02-18 09:08 UTC, Wishoon commented on src/main/java/racingcar/domain/Car.java
> +        return position.getPosition() - car.getPosition();
위의 작성된 내용처럼 **객체에게 메시지를 던지라**에 대해 학습하고 난 이후 대부분의 리팩토링은 수월하게 잘 마무리 되었지만 유독 해당 부분은 리팩토링 방법이 떠오르지 않았어요 😅

```java
public class Car implements Comparable<Car> {
    // ...
    private Position position;

    // ...
    @Override
    public int compareTo(Car car) {
        return position,.getPosition() - car.getPosition();
    }
}
```
getter를 통해 메시지를 던지지 않고 데이터를 꺼내는 잘못된 방법임을 확신? 하면서도 이를 리팩토링할 좋은 방법을 찾지 못했다고 생각해서 질문을 드렸었어요!!

제가 최초 리팩토링 하면서 최초에 생각한 방법은 다음과 같습니다.

```java
public class Car implements Comparable<Car> {
    // ...
    private Position position;

    // ...
    @Override
    public int compareTo(Car car) {
        return position.compareTo(car);
    }
}

public class Position implements Comparable<Position> {
    private int position;

    @Override
    public int compareTo(Car car) {
        return position - car.getPosition().position;
    }
}
```

`Car`에 `Position`이 멤버 변수로 있는데 이를 다시 인자로 넘겨주는게 이질적으로 느껴져서 질문을 드렸었어요!!

(해당 질문을 구체적 이유와 코드를 같이 첨부했었어야 했는데 너무 간략하게 질문을 드렸네요.. 반성합니다 😓😓)

<hr>

재질문을 받고 해당 부분을 다시 곰곰히 생각하다가 굳이 **`Car`를 넘겨줄 필요가 있을까? `Position`만 념겨줘도 괜찮지 않을까?** 해서 다시 밑의 코드로 구현을 해보았습니다.

```java
public class Car implements Comparable<Car> {
    // ...
    private Position position;

    // ...
    @Override
    public int compareTo(Car car) {
        return position.compareTo(car.position);
    }
}

public class Position implements Comparable<Position> {
    private int position;

    @Override
    public int compareTo(Position otherPosition) {
        return position - otherPosition.position;
    }
}
```

해당 방법으로 구현을 하는게 객체에 메세지를 던져라는 방법에도 일치한다고 생각해서 리팩토링을 진행했습니다!!

2022-02-18 09:11 UTC, Wishoon commented on src/main/java/racingcar/domain/Car.java
> +        return Objects.equals(name, car.name) && Objects.equals(position, car.position);
확실히 트레이드 오프의 문제인거 같아요. 앞으로도 각 상황에 맞는 설계를 해보도록 노력해볼게요 😁😁

2022-02-18 09:12 UTC, Wishoon commented on src/main/java/racingcar/domain/Name.java
> +    public Name(final String name) {
메서드 인자에 `final` 키워드를 사용하면 메서드 안에서 파라미터 값을 변경할 수 없다는 기능을 수행합니다.

이로 인해, 만약 파라미터에 재할당 로직이 들어갈 경우 컴파일 시점에서 이를 확인할 수 있는 장점을 가지고 있다고 학습 후 적용했습니다.

다만 이번에 크루들과 관련해서 얘기를 하다보니 **메서드 라인 내에서 재할당하는 경우는 거의 없기 때문에 인자에는 `final`을 붙이지 않는다는 의견도 있었습니다.**

역시 이것도 팀원들과 협업 시 컨벤션의 항목에 포함 된다고 봐야 할까요??

2022-02-18 09:20 UTC, wishoon commented on src/main/java/racingcar/domain/RacingGame.java
> -    }
이번 토니의 답변을 듣고 제 고민이 해결되었다고 생각해요. 결국 프로그래밍은 명확한 답이 있는게 아닌 상황에 맞게 그리고 팀원들과의 소통을 통해서 규칙을 만들어 나간다는 것을요 😁

앞으로도 문서를 통해 컨벤션과 규칙을 만들어 나가고 해당 규칙을 유지하기 위해 노력하려고 합니다. 토니 감사드립니다 😁😁

<hr>

추가적으로 학습한 빌더 패턴에 대한 내용입니다.

빌더 패턴은 생성자에 들어갈 매개 변수가 많든 적든 차례차례 매개 변수를 받아들이고 모든 매개 변술를 받은 뒤에 이 변수들을 통합해서 한번에 사용하는 방법으로 사용됩니다.

만약, 생성자만으로 사용할 경우 다음과 같은 코드를 작성해야 합니다.
```java
UserInfo userInfo = new UserInfo("루키", "BE", "서울시 구로구");
```

이때, 주소에 대한 정보를 입력하지 않는다면 `null`을 통해서 입력을 해주어야 합니다.
```java
UserInfo userInfo = new UserInfo("루키", "BE", null);
```

`null` 입력 대신 추가로 생성자를 만들어서 문제릃 해결할 수 있지만 매번 생성자를 만드는 것도 자원이기에 이런 상황을 해결하고자 나온 것이 **빌더 패턴**으로 학습을 했습니다.

**빌더 패턴**을 적용할 경우 빌더 클래스를 만들어서 사용해야 합니다.

```java
public class UserInfoBuilder {
    private String name;
    private String group;
    private String addr;

    public UserInfoBuilder setName(String name){
        this.name = name;
        return this;
    }

    public UserInfoBuilder setGroup(String group){
        this.group = group;
        return this;
    }

    public UserInfoBuilder setAddr(String addr){
        this.addr = addr;
        return this;
    }

    public UserInfo build(){
        return new UserInfo(name, group, addr);
    }
}
```

이후 만들어진 빌더 객체를 다음과 같이 사용합니다.
```java
UserInfoBuilder userInfoBuilder = new UserInfoBuilder();
UserInfo userInfo = userInfoBuilder
        .setName("루키")
        .setGroup("BE")
        .setAddr("서울 구로구")
        .build();
```

이를 통해, 불필요한 **생성자를 제거하고, 데이터의 순서에 상관없이 객체 생성이 가능하며, 명시적 선언으로 이해하기 쉽다는 장점**이 있다고 학습했습니다.

2022-02-18 09:31 UTC, Wishoon commented on src/main/java/racingcar/dto/RecordDto.java
> +}
`DTO`에 대해서 추가 학습을 진행했습니다. 

객체지향 프로그래밍에서는 **가변 객체를 지양하라**는 말이 있는데 해당 문구는 `DTO`에도 동일하게 적용되어야 한다고 학습했습니다.

**데이터를 전달하는 로직만 수행**하는 `DTO`가 **값의 불변을 보장하여 더 안전하게 기능을 구현할 수 있다는 장점**이 있기 때문에 `DTO` 역시 **불변 객체**로 만들어 사용하는 것이 좋다고 학습을 진행했습니다.

2022-02-18 09:51 UTC, Wishoon commented on src/main/java/racingcar/domain/Name.java
> +    private static final String NAME_CONTAINS_BLANK = " ";
다음과 같이 상수 이름을 수정하면 괜찮을까요??

```java
private static final int MINIMUM_LENGTH = 1;
private static final int MAXIMUM_LENGTH = 5;
private static final String BLANK = " ";
```

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/domain/Cars.java
> +            .map(Car::new)
메소드 참조를 사용하여 간결하게 표현하셨군요! 좋습니다.

2022-02-19 07:52 UTC, toneyparky commented on src/test/java/racingcar/domain/CarsTest.java
>          assertThat(cars.getDriveRecord().size()).isEqualTo(2);
`assertThat`에서 매번 `cars.getDriveRecord()`를 호출하기보다는 반환값을 객체로 선언한 후에 이를 재사용해봐도 좋겠네요!

2022-02-19 07:52 UTC, toneyparky commented on src/test/java/racingcar/domain/CarsTest.java
>      }
테스트하고자하는 목표에 집중하면 좋을 것 같아요. 

여기서는 우승자를 파악하기만 하면 되죠. 5, 4라는 숫자가 들어감으로 인하여 읽는 사람이 추가적인 컨텍스트를 파악해야할거 같아요. 

```suggestion
        Cars cars = Cars.from(carList);
        
        Int drivableNumber = 4;
        
        car1.drive(drivableNumber);
        car2.drive(drivableNumber);

        assertThat(cars.getWinners().size()).isEqualTo(2);
    }
```

예시로 작성한 코드라 문법적으로 틀릴 수도 있지만 요런 식으로 맥락을 줄여서 사용자가 읽기 편하게 만들어볼 수 있겠다 싶네요~!

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/controller/RacingGameController.java
> +            Round.fromNumber(InputView.getRound()),
넵! 좋습니다, 다만 그냥 `of`, `from`만 사용하자는 의견도 있기에 대화를 통해 네이밍 정책을 가져가면 좋을 것 같아요. 

충분한 근거를 가지고 협업자와 소통하여 규칙을 정한다!!

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/domain/Name.java
> +    public Name(final String name) {
포함 된다고 생각합니다. 적용하기로 결정된, 규칙에 맞는 부분에는 항상 적용되어야하니까요.

규칙을 정할 때에는 루키가 적어주신 장점을 활용하고 싶다면, final을 활용하면 되구요. 장점이 있지만 final 때문에 코드 파악하기가 더 어려워진다 하면 굳이 안 써도 되는거구요. 저라면 기본적으로는 굳이 사용하지 않고 생성시에 인자가 수정이 안되야하는 특별한 상황에서 사용할거 같아요😀

마지막으로 final은 의미를 가집니다. 읽는이로 하여금 `해당 변수가 불변이라는 것을 알 수 있게` 해주죠. 그래서 불변임을 알려줘야하는 곳에는 꼭 사용되어야 하지만, 남용되면 안된다고 생각해요.

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/domain/RacingGame.java
> -    }
빌더 패턴에 대해서 깔끔하게 정리해주셨군요! 루키의 학습에 도움이 된 것 같아 기쁘네요 🤓

협업자와의 충분한 소통, 그리고 문서화! 좋습니다.

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +        return position.getPosition() - car.getPosition();
친절하게 설명해주셔서 감사해요 루키!

최종 리팩터링 버전은 코드를 이해하기도 좋고 객체에 책임이 적절하게 배분된 모양새네요 💯 

---

아래의 코드 처럼 Car 객체 내부에서 다른 Car 객체의 private position 필드를 참조할 때에 getter가 아니라 필드값 참조로 취급 됨을 아시면 좋을 것 같아요. 실제로도 `getPosition`을 사용하지 않죠! 

`return position.compareTo(car.position);`

이러한 자바의 설계에 대해서는 여러가지 이야기가 있지만 이렇게 설계 됨을 알고 적절하게 활용하면 된다고 생각합니다.

참고 글 : 
https://stackoverflow.com/questions/17027139/access-private-field-of-another-object-in-same-class

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/domain/Name.java
> +    private static final String NAME_CONTAINS_BLANK = " ";
저는 훨씬 간결하면서도 정확해진거 같아요. 최고!

2022-02-19 07:52 UTC, toneyparky commented on src/main/java/racingcar/dto/RecordDto.java
> +}
DTO를 불변으로! 좋습니다. 불변의 의미를 잘 활용한 리팩터링 같아요.

저도 위에서 말씀드렸듯 List는 final로 선언하여도 할당이 안될 뿐 객체 내부 값의 수정은 가능하죠! 정확하게 알고 계시는군요. 정말 불변을 지키려면 들어오는 인자를 `unmodifiableList`로 처리해줘서 필드에 할당해주면 되려나 싶지만 너무 코드가 더러워지기에 List에 대해서는 타협하는 편입니다(?)

자바의 이런 문제를 해결하기 위해 코틀린이라는 언어에서는 수정이 가능한/불가능한 리스트 두가지의 타입을 지원한답니다.
참고 : https://hinos.tistory.com/22

2022-02-19 07:54 UTC, toneyparky approved these changes
고생하셨어요 루키!

리뷰 반영과 질문에 대한 답변, 추가적인 학습까지 잘 마무리해주셨네요 😎

우테코에서의 첫 미션을 머지할 시간이군요!!

앞으로 다음 미션에서도 지금처럼 열정을 보여주시면 많이 성장하실겁니다!

추가적인 질문이 있으시다면 대댓글이나 DM 주세용~

2022-02-19 07:55 UTC, merged