[2단계 - 자동차 경주 리팩토링] 열음(이주형) 미션 제출합니다.
woowacourse/java-racingcar pull request #380
Opened 2022-02-17 07:05 UTC by Juhyung990122

안녕하세요 제이!
1단계 피드백을 참고해서 리팩토링한 코드를 보냅니다:)
진행하면서 의문점이 생겼던 것들이 있는데, [1단계 피드백](https://github.com/woowacourse/java-racingcar/pull/313)쪽에 코멘트로 달아두었으니 확인 부탁드려요! 

확실히 짜는것보다 고치는게 고민할 것이 많네요... 부족한점도 많은 것 같구요.
가감없는 피드백 주시면 기반삼아 열심히 해보겠습니다!
감사합니다😊

2022-02-17 17:24 UTC, jjj0611 requested changes
안녕하세요 열음 리뷰어 제이입니다. 
2단계도 고생 많았어요
전체적으로 코드가 깔끔해져가고 있네요! :)

그런데 코드를 수정하면서 테스트가 돌지 못하네요 :(
확인 한 번 해주시고 PR 요청 부탁드려요!

그리고 1단계에서 코멘트 드린 부분 중에 반영이 안된 부분이 있는 것 같아요!
잘 모르겠거나 의문이 들면 질문해주세요 :)

1단계 답글 달아주신 것에 코멘트 드렸으니 확인해주시고 2단계에 같이 답변해주시거나 녹여주세요!

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/Application.java
> +                new RacingController(new ConsoleOutputView());
오 이제 InputView와  Movement는 주입하지 않고 있네요
이유가 있을까요?

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +        Game game = new Game(new ConsoleInputView(), new DetermineMovementByRandomNumber());
여기서 생성하는 것에는 이유가 있을까요?

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +            game.carsMove();
자동차가들이 진행한다를 한 준위 더 올려서 표현할 수 있을 것 같아요.

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +        outputView.printWinners(game.winnerCarsInfo());
저번 코멘트에서 못 드렸던 것 같은데 info라는 단어는 최대한 지양하는게 좋습니다. data, info등 의미를 모호하게 드러내는 단어는 최대한 피하는게 좋아요 :)

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
> +    private Integer distance;
지난 리뷰를 참고해주세요!

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
> +                .orElse(INITIAL_DISTANCE);
다음 라인에 대한 indent가 과하게 깊게 들어간 것 같아요!
이게 컨벤션인가요??

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
> +                .filter(car -> car.isSameDistance(maxDistance))
isSameWith(maxDistance) 정도도 괜찮지 않을까요? :)

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +    }
좋은 추상화네요 :)

2022-02-17 17:24 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +    }
이전 리뷰에서 domain이 dto를 의존하고 있는 것에 대한 이야기를 했던 것 같은데 반영이 안되어 있는 것 같아요! 답글도 따로 안달려 있는 것 같은데 확인 한 번 해주세요~

2022-02-18 06:33 UTC, Juhyung990122 commented on src/main/java/racingcar/Application.java
> +                new RacingController(new ConsoleOutputView());
전에 피드백주셨던 멤버변수 부분을 수정하면서 여러명이 게임을 실행한다는 가정을 해봤는데
여러명이서 게임할때 입력객체를 공유하는게 좀 어색하단 생각이 들더라구요
따라서 Game 객체 생성시 주입하는 방식으로 바꿔서 게임단위로 관리하는게 더 좋겠단 생각이 들었어요

2022-02-18 06:36 UTC, Juhyung990122 commented on src/main/java/racingcar/controller/RacingController.java
> +        Game game = new Game(new ConsoleInputView(), new DetermineMovementByRandomNumber());
run은 프로그램 시작으로 생각해서 시작 -> 생성 -> 동작 -> 종료 흐름으로 가고자 했습니다🤔

2022-02-18 07:00 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Game.java
> +    }
앗 1단계[ 2번째 리팩토링때](https://github.com/woowacourse/java-racingcar/pull/313/commits/6c911997031ccb32c5a3d70a8f8c3e744857fa12) 의존성에 대한 이해가 부족해서 잘못했나보네요..ㅎㅎ
저때당시엔 단순히 도메인 내에 new 키워드만 없으면 괜찮다고 생각해서 toDto 메소드만 분리했었거든요.
의존성에 대해 좀더 공부해봐야겠어요🤔 
이번 변경사항도 의존성이 제거되지 않았다면 말씀주세요!

2022-02-18 07:03 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Cars.java
> +                .orElse(INITIAL_DISTANCE);
확인해보니 한번 더 탭을 해야해서 수정했습니다:)

2022-02-18 07:05 UTC, Juhyung990122 commented on src/main/java/racingcar/controller/RacingController.java
> +        outputView.printWinners(game.winnerCarsInfo());
네 수정했습니다! 감사합니다:)

2022-02-18 09:44 UTC, Juhyung990122 commented on src/main/java/racingcar/controller/RacingController.java
> +            game.carsMove();
혹시 준위를 올린다는게 어떤 뜻인가요..?👀  
해당코드를 game내에 합쳐서 Controller에서는 한 메소드로 보여지게끔 표현하라는 말씀이실까요?-?

2022-02-18 15:42 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Car.java
> +    private Integer distance;
수정했습니다:)!!

2022-02-18 15:46 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Cars.java
> +                .filter(car -> car.isSameDistance(maxDistance))
수정했습니다~:)

2022-02-19 02:21 UTC, Juhyung990122 commented
안녕하세요 제이:)
제이의 피드백을 참고해서 리팩토링 해보았어요!
더불어 1단계에서 반영되지 않았던 것들도 고쳐보았는데요
이번 코드의 큰 수정사항들은 다음과 같습니다.

- Dto와 Domain간 의존성끊기
- Car의 정렬조건 바꾸기
- 객체 내 요소 도메인으로 분리하기

이외에도 자잘한 요소들이나 궁금증은 comment로 답글 남겨두었으니 확인 부탁드려요:)
항상 시간내서 리뷰해주셔서 감사합니다!

+) 테스트랑 실제 실행여부 저번에 체크 못한거 죄송해요:( 이번엔 잘 체크해서 보냈으니 문제없을거라 생각합니다~!

2022-02-19 11:48 UTC, jjj0611 commented on src/main/java/racingcar/Application.java
> +                new RacingController(new ConsoleOutputView());
그러면 사용자의 입력을 받는 것은 Game 객체의 역할인데 해당 객체가 생성되는 시점에 InputView와 강하게 결합이 되어있는 것이지 않을까요??

InputView에서의 변경 일어나면 필연적으로 Game에서도변경이 일어날 수 있겠군요!

2022-02-19 11:51 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +            game.carsMove();
'진행한다'의 의미가 불충분하다고 느껴졌던 것 같아요!
네이밍이 가지고 있는 의미의 준위가 적절히 추상화되어 있어야 좋은 네이밍을 지을 수 있는 것 같아요!

2022-02-19 12:04 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +    }
의존성이라는 것은 가장 단순하게 이야기 하면 A를 변경했을 때 B가 변경되어야 하는가를 생각해보시면 편합니다.
기존 코드에서 CarDto의 이름을 CarInfo로 변경하면 intellij가 아주 편하게 변경을 해주지만, 실제로는 Car 객체와 Cars 객체에서도 import 문의 변경등 변경사항이 생겼을겁니다.
이렇게 A를 변경했을 때 B가 변경되어야하는가를 항상 고민해보면 좋을 것 같아요!

이때 분명히 관계가 있는 코드라면 1곳은 영향을 받을 수밖에 없어요.
그런데 view에 전달되는 Dto 객체의 변화가 도메인에 영향을 미치는 것보다 도메인의 변화가 Dto에 영향을 주어야 Dto가 변경된다고 하더라도 도메인을 변경할 일은 없을 거에요! :)
이런 의존성들을 잘 고민하다보면 좀 더 변화에 유연한 코드를 작성할 수 있습니다 :)

고민하는 것 같아서 살짝만 말씀을 드렸는데,
자동차 경주게임부터 고민할만한 내용은 아니니 슬쩍 생각만하고 넘겨주셔도 됩니다!

2022-02-19 13:12 UTC, jjj0611 requested changes
안녕하세요 열음! 리뷰 반영해주신 부분 잘 봤습니다!
코드가 점점 깔끔해져 가는 것 같아요!(저만 그렇게 느끼는건 아니겠죠...? 😅)

조금 더 고민할 부분 코멘트 드렸어요!
얼마 안남았습니다! 혹시 이해가지 않는 코멘트 있다면 답변이나 DM 주세요~

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +            game.carsMove();
좀 더 추상화된 코드가 되었네요 👍

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +        return CarDto.toDtoList(cars);
이렇게 되면 Controller만이 view와 car라는 domain을 알게 되고,
view와 car는 서로를 모르는 영역이 됩니다!
MVC 패턴의 그림을 잘 보면 두 개가 연결된 선은 없는 것을 볼 수 있을거에요!

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
> +    private static final int SAME = 0;
처음에 메서드를 보기 전까지는 도대체 이게 무슨 의미일까 고민을 많이 했던 것 같아요!
좀 더 의미가 명확한 변수명을 지어주면 좋을 것 같아요!

혹은 이게 매직넘버인가?에 대한 고민을 다시 해봐도 좋을 것 같아요!
보통 우리가 매직넘버라고 부르는 것들은 도메인 로직에 좀 더 가까운 의미가 불분명한 것들을 이야기하는데요.
정렬 조건으로 -1, 1, 0이 의미하는 것이 정말 매직넘버인가?에 대한 고민을 해보면 좋겠네요!

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/CarName.java
> +    private void validateCarName(String value) {
validate 로직을 묶어서 표현해주셨네요!

이 부분은 확실히 취향의 영역인 것 같긴하지만, 저는 이런 표현을 더 선호합니다!
validateBlank라고 이름 짓지 않아도, blank일 때에 예외가 발생하고 있고,
length가 5보다 큰 경우에 예외가 발생한다는 것은 한 눈으로 보아도 알 수 있죠.
만약 그렇지 않으면 만일을 위해 모두 앞에서 null 체크를 해야만 완벽한 메서드의 분리라고 할 수 있는데,
이 부분이 오히려 비효율을 만든다고 생각해요!

여기서는 validate라는 하나의 메서드가 일종의 원자성을 가지고 움직인다고 생각합니다!
따라서 그런 방향을 이야기 드렸었는데 (이렇게 되면 blank와 lengh의 메서드 호출 순서가 바뀌는 일은 없기 때문에) 잘 반영해주셨네요!
하지만 어디까지나 취향의 영역이기도 하니 참고 정도로 이해해주셔도 좋을 것 같아요 :)

그래도 만약 기존의 코드로 사용하고 싶으시면, blank와 lengh를 체크하는 메서드에서도 null 방어가 되어야 완벽할 것 같아요!
만약 다른 개발자가 CarName 내부에서 해당 메서드를 사용하려고 할 때 null 방어가 안된 채로 사용을 할 수도 있으니까요!

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
>                  .orElseThrow(IllegalArgumentException::new);
지난번에 코멘트를 못드렸었네요!
maxDistance를 구하는 상황에서 언제 orElseThrow를 탈까요?
해당 케이스에서 예외를 던지는 것과 기본값을 주는 것 중 어떤게 더 좋은 방법일까요??

보통 리뷰를 받을 때 리뷰이들의 마음을 알기에 기우에 몇마디 더 적으면, 절대로 기본값이 좋다고 말씀드리는게 아닙니다! 정말 열음의 생각을 들어보고 싶은거에요 :)

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
> +    private Distance distance;
다른 것들과 다르게 final 키워드가 안 붙은 이유가 있을까요? :)

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +    }
게임을 생성할 때 InputView를 받아서 생성할 수도 있지만, 이 부분이 조금 분리되면 좋을 것 같아요!
물론 InputView를 interface화하였지만, 그럼에도 불구하고 InputView는 View이고, Game은 도메인입니다.
여전히 view와 model이 강결합되어 있는 것 같지 않나요??

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +    }
자동차가 움직이는 것과 시도 횟수가 마이너스가 되는데 메서드명은 자동차가 움직이는거에요!
24번라인의 메서드명이 좀 더 추상적일 수 있을까요?!

더물어서 열음은 객체에서 this를 항상 사용하는 것을 선호하시나요?!

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/Game.java
> +        return this.trialCount.getTrialCount() > 0;
trialCount의 역할이지 않을까요?!

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/domain/TrialCount.java
> +        this.trialCount = Integer.parseInt(inputTrialCount);
regex로 판단하기보다는 숫자로 변환하여 체크하는 것이 더 좋지 않을까요?
regex로 판단하신 이유가 있을까요??

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/racingcar/service/DetermineMovementByRandomNumber.java
> +        if (randomNumber >= MOVE_CRITERION) {
`return randomNumber >= MOVE_CRITERION` 으로 표현 가능하지 않을까요? :)

2022-02-19 13:12 UTC, jjj0611 commented on src/main/java/stringcalculator/StringCalculator.java
> +        return Integer.parseInt(token);
전체적으로 regex를 사용하여 판단하신 부분들이 많네요!
Integer.parseInt를 신뢰해보면 어떨까요? :)

2022-02-20 15:02 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Cars.java
>                  .orElseThrow(IllegalArgumentException::new);
음..저는 이 케이스에선 예외를 던지는 것이 더 좋다고 생각해요!

왜냐하면 저 로직에서 최대값이 안나올 경우가 일반적으론 없을거라 생각했어서
만약 orElseThrow를 탄다면.. 그건 뭔가 지금 제가 예상치 못한 문제가 있는 경우일 것 같아요.
만일 그런 상황이 있다면 그걸 알기위해서 예외로 처리하는게 좋을 것 같습니다~!

2022-02-20 15:28 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Car.java
> +    private Distance distance;
이전엔 distance가 한 라운드마다 계속 변하는 값이라 생각해서 final을 붙이지 않았었는데요.
해당 코멘트를 보고 fianl에 대해 더 찾아보니 객체로 분리하게 될경우 final을 붙여도 객체의 요소값은 변경할 수 있더라구요!
그래서 변경했습니다 :)

2022-02-20 16:53 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Game.java
> +    }
반영했습니다:)!

음.. 네! 다른 객체와 비교한다 했을때 
element > other.element
보다 
this.element > other.element 
가 더 읽기 좋을 것 같아서 this를 붙이는걸 선호합니다.
그리고 통일성을 고려해서 비교케이스가 아니더라도 this를 붙이곤해요.

하지만 읽는사람 입장에서 가독성이 떨어진다면 언제든 바꿀 의향 있습니다ㅎㅎ
혹시 리뷰하시면서 어떠셨나요?-?

2022-02-20 16:55 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Game.java
> +        return this.trialCount.getTrialCount() > 0;
맞습니다! 수정했어요:)

2022-02-20 16:57 UTC, Juhyung990122 commented on src/main/java/racingcar/service/DetermineMovementByRandomNumber.java
> +        if (randomNumber >= MOVE_CRITERION) {
헉 맞아요! 반영했습니다:) 줄이니 넘 간결하네요ㅎㅎ

2022-02-20 17:37 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/TrialCount.java
> +        this.trialCount = Integer.parseInt(inputTrialCount);
음.. 이유가 있다면 InputViewConsole에서 CarNames과 통일성을 주고싶어서 에요!
이를 위해 뷰에서는 공백체크만 한 뒤 String을 넘기고 
domain에서 실질적으로 들어갈 수 있는 값인지(숫자인지 아닌지 + 양수인지) 검사하기 위해 regex를 사용했었어요.

근데 다시보니 다음 세가지의 이유로 수정했습니다:)
- 한번에 다른 두가지의 검사를 하고있어서 메소드명이 바뀔 필요가 있어보임
- 숫자인지 아닌지 검사하는건 Input을 받은 View단에서 해결하는게 더 적절해보임
- 말씀하신대로 숫자이니 문자열 비교보다는 숫자로 변환 후 체크하는게 좋아보임

2022-02-20 17:53 UTC, Juhyung990122 commented on src/main/java/stringcalculator/StringCalculator.java
> +        return Integer.parseInt(token);
네! TrialCount쪽 코멘트에서 말씀드렸듯 이것도 숫자라서 변환 후 검사가 좋을 것 같아 수정했습니다!
다만 제가 TrialCount에서는 regex로 숫자인지 아닌지 검사 -> parseInt -> 양수인지 검사 로직으로 작성했는데요.
여기서는 다음과 같이 try - catch 문을 사용해서 regex 없이 검사하는 방식을 사용해보았어요.
```
private int convertTokenIsPositiveNumber(final String token) {
        try{
            int convertedToken = Integer.parseInt(token);
            validatePositive(convertedToken);
            return convertedToken;
        } catch (NumberFormatException e){
            throw new IllegalArgumentException(IS_NOT_NUMBER);
        }
    }

    private void validatePositive(int convertedToken) {
        if(convertedToken < 0){
            throw new IllegalArgumentException(IS_NOT_POSITIVE);
        }
    }
```

trialCount처럼 하자니 말씀해주신 regex를 완전히 제거할 수 없고,
이거처럼 하자니 try - catch문을 예상가능한 예외에 사용한다는 점이 좀 고민되더라구요.

혹시 제이는 둘중에 어떤게 더 괜찮다고 생각하시나요?

2022-02-20 18:03 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Game.java
> +    }
네 맞습니다! 그래서 InputView 주입위치는 컨트롤러에서 하는것으로 수정했습니다:)

2022-02-20 18:13 UTC, Juhyung990122 commented on src/main/java/racingcar/controller/RacingController.java
> +        return CarDto.toDtoList(cars);
제이 좀 웃기실수도 있는 질문인데요..ㅎㅎ
잘 고쳤다고 말씀 하신걸까요 아님 뭔가 더 생각해보라고 말씀 하신걸까요?
혹시 제가 이해한 의미와 다를까봐 여쭤봅니다👀

2022-02-21 01:08 UTC, Juhyung990122 commented on src/main/java/racingcar/domain/Car.java
> +    private static final int SAME = 0;
제이의 피드백을 듣고 생각해봤는데 도메인과 엄청 직접적으로 연관된 숫자는 아니여서 매직넘버가 아니라는 결론이 났어요!
그래서 매직넘버를 해제하고 어떻게 바꿔야 좋을지 좀 고민해보았는데요.
어차피 max에는 고정값(1, -1)을 넘겨주긴 해야해서 다음과 같이 메소드 내에 변수로 선언하는 방법을 사용해보았어요! 
```
    public int orderByDistanceAsc(Car otherCar) {
        int thisCarIsFarther = 1;
        int otherCarIsFartherOrSame = -1;

        if (this.distance.isBigger(otherCar.distance)) {
            return thisCarIsFarther;
        }
        return otherCarIsFartherOrSame;
    }
```
근데 아무래도 고정값을 이렇게 처리한건 익숙치 않아서 이게맞나 싶네요🤔 
매직넘버까진 아니지만 값 자체는 고정인 경우에 이런식으로 처리하는 경우도 있나요?-?

+) 혹시 여기에서 Integer.compare()을 사용하는건 어떻게 생각하시나요?
Comparable 의 compareTo를 구현했을때와 로직상 큰 차이는 없는 것 같아서
이때 의도하신 바가 [이 코멘트](https://github.com/woowacourse/java-racingcar/pull/313#discussion_r810430144)와 같다면 Integer.compare을 쓰는게 더 간결하고 좋겠다 싶어서요!

2022-02-21 01:21 UTC, Juhyung990122 commented
안녕하세요 제이:) 열음이에요!
제이가 남겨주신 리뷰를 읽으면서 평소에 간과하던 부분들을 생각해볼 수 있었습니다.
생각을 계속 하다보니 점점 깔끔한 코드가 되어가는 것 같아 만족스럽네요~!~!(제이만 그렇게 느끼신거 아녜요ㅎ_ㅎ)

이번 리팩토링을 진행하면서 주요한 변경사항은 다음과 같습니다

- InputView 주입 위치 변경을 통한 view와 domain 의존관계 제거
- 숫자 요소 검사에 regex 제거
- 자동차 정렬기준 매직넘버 변경

이외에 변경사항이나 질문사항은 코멘트에 정리해두었어요.
부족한 점은 편하게 말씀해주시면 감사하겠습니다ㅎㅎ
더불어, 바쁘실텐데 시간내어 봐주셔서 언제나 감사해요 :)❤️

2022-02-22 03:18 UTC, jjj0611 approved these changes
안녕하세요 열음! 리뷰어 제이입니다.

자동차 경주게임 코드리뷰를 진행하면서 코드가 많이 달라져왔네요!
학습해야할 것들에 대해서 잘 학습하고, 리뷰 코멘트도 잘 반영해주셔서 감사해요 :)

마지막 코멘트 조금 남겨 드렸으니 확인보시면 좋을 것 같아요!
그동안 리뷰 드린 것들이 열음의 성장에 도움이 되었으면 좋겠네요!
자동차 경주게임 미션 진행하시느라 고생하셨고, 코드는 여기서 머지하겠습니다. 

다음 미션도 화이팅하세요! 😄

2022-02-22 03:18 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +        int inputTrialCount = inputView.inputTrialCount();
뷰의 역할이 List<String>과 int를 반환하는 것까지 역할을 잘 분리해주셨네요!

2022-02-22 03:18 UTC, jjj0611 commented on src/main/java/racingcar/controller/RacingController.java
> +    public Game gameSet(){
public일 필요는 없을 것 같아요!

2022-02-22 03:18 UTC, jjj0611 commented on src/main/java/racingcar/domain/CarName.java
> +            throw new NullPointerException(ExceptionMessage.NULL_CAR_NAME);
NPE로 변경하신 이유가 있나요?

2022-02-22 03:18 UTC, jjj0611 commented on src/main/java/racingcar/view/InputView/ConsoleInputView.java
> +        validateTrialCount(inputTrialCount);
matches로 판단하지 않고 바로 변환하면서 예외를 던져주는건 어떨까요?

2022-02-22 03:18 UTC, merged