[2단계 - 자동차 경주 리팩터링] 이스트(신동훈) 미션 제출합니다.
woowacourse/java-racingcar pull request #385
Opened 2022-02-17 11:02 UTC by EastHShin

안녕하세요 제이!

이미 MVC패턴으로 되어 있었기 때문에 이번 미션은 1차때 피드백 주셨던 랜덤 테스트에 대한 리팩터링과 어떻게 도메인에서 최대한 getter를 사용하지 않을까에 대한 고민을 많이 했던것 같아요!

미션 진행하면서 궁금했던 점도 같이 적습니다😄

1. domain 패키지에서 view 패키지를 의존하지 않도록 구현해야 하는데, Car와 Cars 모두 view 패키지내에 있는 exception 메세지 상수를 불러와 에러 발생시 사용하고 있습니다. 이런 경우도 view패키지를 의존하고 있다고 보아야할까요? 의존하고 있는거라면 messages 패키지를 root 경로에 두어 모든 패키지에서 사용할 수 있다는 의미를 두면 될지 궁금합니다!

이번 리뷰도 잘 부탁드리고 항상 감사드립니다!!

2022-02-17 23:53 UTC, JunHoPark93 requested changes
안녕하세요 이스트!
2단계 미션 하시느라 고생많으셨습니다!
변경된 코드의 양은 많지는 않네요. 피드백 몇가지 남겨두었는데 확인부탁드려요!
질문주신 부분은 코멘트에 남겨두었어요.
궁금한점 있으시면 편하게 말씀주세요!

2022-02-17 23:53 UTC, JunHoPark93 commented on src/main/java/carracing/view/messages/ExceptionMessage.java
> +	CAR_NAME_BLANK_EXCEPTION("자동차의 이름에 공백은 포함될 수 없습니다."),
첫 번째 질문입니다.

> domain 패키지에서 view 패키지를 의존하지 않도록 구현해야 하는데, Car와 Cars 모두 view 패키지내에 있는 exception 메세지 상수를 불러와 에러 발생시 사용하고 있습니다. 이런 경우도 view패키지를 의존하고 있다고 보아야할까요? 의존하고 있는거라면 messages 패키지를 root 경로에 두어 모든 패키지에서 사용할 수 있다는 의미를 두면 될지 궁금합니다!

정말 좋은 질문해주신거같아요!
넵 이런경우에도 의존하고 있다고 생각해요. 특정 해당 상수를 도메인에 두고 뷰에서 참조한다면 의존을 끊을 수 있구요. root에 두어도 되긴하는데 예외클래스 포맷정도는 괜찮을거같아요. 그런데 메세지를 들고있는건 역할에 안맞는 생각이 드네요. 🤔
개인적으로는 해당 메세지를 도메인에서 들고있게 하는 편입니다.
이것도 뷰에 친화적인 메세지 아닌가? 라고 생각하실수있어요. 엄밀히 말하면 저도 이 부분에 있어서 동의는 합니다.
client에 따라서 예외메세지 형태가 달라진다면 도메인에서 범용적인 에러메세지를 내리는것이 맞고 그렇지 않다면 도메인에서 가지고있어도 무방하다고 생각해요.
혹시 다른 의견있으시면 말씀주세요~

2022-02-17 23:53 UTC, JunHoPark93 commented on README.md
> +- [x] 자동차 이름을 입력받는다.
앞으로 미션 진행하시는데 있어서 단계별로도 요구사항을 나눠서 관리한다면, 단계별로 익히는 내용에 대해서 스스로 정리가 더 잘될 거에요 🙏

2022-02-17 23:53 UTC, JunHoPark93 commented on src/main/java/carracing/model/Car.java
> +	public static Car nameOf(String name) {
이거는 개인적인 의견이어서 참고만 해주세요~
메서드이름에서 name은 빼도되지 않을까요? 인자들이 달라지면 메서드 이름을 같이 수정해야하는 부분도있고 인자인 String name에서 의미가 드러나니까요!

2022-02-17 23:53 UTC, JunHoPark93 commented on src/main/java/carracing/model/Cars.java
> +			.filter(car -> car.isTiedWith(winner))
메서드 역할 분리를 할 수 있을까요? 🤔

2022-02-17 23:53 UTC, JunHoPark93 commented on src/test/java/carracing/util/ImmovableNumberGenerator.java
> +}
테스트에서 사용할 generator를 만들어주셨네요 👍
상수도 정의해주셨는데 return 때 사용하면 되겠네요!

2022-02-18 06:29 UTC, EastHShin commented on src/main/java/carracing/view/messages/ExceptionMessage.java
> +	CAR_NAME_BLANK_EXCEPTION("자동차의 이름에 공백은 포함될 수 없습니다."),
도메인에서 에러 메시지를 들고 있게하는것! 좋은 방법인것 같습니다!
그런데, client에 따라서 예외 메시지 형태가 달라진다는 의미는 잘 이해가 안가네요...! 만약, 웹 어플리케이션인 경우에 rest api로 메세지를 넘겨주거나, 서버 내에서만 로깅을 하더라도 문자열인 형태로 메세지를 넘겨주는건 똑같지 않나 해서요!!

2022-02-18 06:32 UTC, EastHShin commented on src/main/java/carracing/model/Car.java
> +	public static Car nameOf(String name) {
의도를 드러내기 위해 이런 방식으로 메서드 명을 지었는데, 인자로도 의도를 드러낼 수 있었다는 생각을 못했네요!!
정적 팩터리 메서드의 네이밍 컨벤션에 따라서도 제이가 말씀해주신 방법이 더 좋은것 같습니다!

2022-02-19 00:13 UTC, JunHoPark93 commented on src/main/java/carracing/view/messages/ExceptionMessage.java
> +	CAR_NAME_BLANK_EXCEPTION("자동차의 이름에 공백은 포함될 수 없습니다."),
현재구조에서 OutputView 말고 다른 종류의 view(다른 출력포맷을가진) 가 생길때의 이야기였어요! 도메인에서 여러 view 처리를 위한 메세지를 들고있을필요가 없으니까요

2022-02-19 00:20 UTC, JunHoPark93 approved these changes
안녕하세요 이스트!
2단계 피드백 반영하시느라 고생많으셨어요 🙇‍♂️
질문 주신 부분은 코멘트 남겨두었습니다.
남은 우테코 기간 체력안배 잘하셔서 끝까지 완주하시길 바랍니다 🙏

2022-02-19 00:20 UTC, JunHoPark93 commented on src/main/java/carracing/view/output/OutputView.java
> +public interface OutputView {
이 인터페이스는 정의하신 이유가 있을까요?
개인적으로 현재는 구현체가 하나여서 굳이 인터페이스를 만들 필요까지는 없어보여요.
출력에 있어서 여러종류의 view가 생기는 경우에는 필요할 수 있겠네요! (처음 질문주신 [이부분](https://github.com/woowacourse/java-racingcar/pull/385#discussion_r810410957)과도 연관성이 있을거같아요)

2022-02-19 00:21 UTC, merged

2022-02-19 03:16 UTC, EastHShin commented on src/main/java/carracing/view/output/OutputView.java
> +public interface OutputView {
여러 종류의 view가 생길 경우를 생각해서 인터페이스로 바꾸어봤어요! 당장 필요한 작업은 아니었던것 같네요ㅎㅎ