[2단계 - 자동차 경주 리팩터링] 썬(윤선용) 미션 제출합니다.
woowacourse/java-racingcar pull request #386
Opened 2022-02-17 11:37 UTC by syoun602

안녕하세요 럿고! 2단계 리뷰도 잘 부탁드려요 ! 🙂 

이번 2단계에서는 지난 피드백들에서 힌트를 얻어 controller가 가지고 있는 상당 부분의 책임을 각자 도메인에 나누어보았습니다! 제 초기 코드보다는 훨씬 간결해진 것 같은데 어떻게 보일지 모르겠네요... 

이번 단계에서는 VO를 위한 Winner와 Result를 추가해보았는데, 사실 두 가지 모두 비슷한 값을 들고 있다고 생각되어서 좀 과하게 나눈게 아닌가? 라는 생각도 들었는데 어떻게 생각하시는지 의견 주시면 감사하겠습니다!!

2022-02-17 12:28 UTC, ksy90101 requested changes
안녕하세요 썬 :) 리뷰어 럿고입니다.
2단계도 너무 고생 많으셨습니다 👏 
2단계에서는 RacingGame을 만들어서 비대했던 Controller가 굉장히 가벼워진거 같습니다. 💯 
간단한 피드백과 테스트 코드 추가 리뷰를 해봤습니다.
한번 진행해보시고 질문이 있다면 언제든지 요청주세요!

2022-02-17 12:28 UTC, ksy90101 commented on src/test/java/racingcar/model/CarTest.java
>      @DisplayName("특정 값을 통한 자동차 비전진 확인")
이쪽의 코드를 확인해보시면 아래와 같이 되어있습니다 :) 
```
 assertThat(car.getPosition()).isEqualTo(0);
```

이런경우에는 assertJ에서 isZero()라는 0인지를 확인하는 메서드를 지원하고 있는데요.
혹시 확인해보시면 좋을거 같아요.
저는 이런식으로 명명으로 하는게 더 가독성은 높다고 생각합니다 :)

2022-02-17 12:28 UTC, ksy90101 commented on src/test/java/racingcar/model/WinnerTest.java
> +public class WinnerTest {
여기도 public이 들어가 있네요.
junit5부터는 public은 특정 상황이 아닌 경우에는 사용하지 않는걸 추천드립니다 :) 

```
Class and method visibility
Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private.

It is generally recommended to omit the public modifier for test classes, test methods, and lifecycle methods unless there is a technical reason for doing so – for example, when a test class is extended by a test class in another package. Another technical reason for making classes and methods public is to simplify testing on the module path when using the Java Module System.
```

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/view/OutputView.java
>  public class OutputView {
InputValidator 클래스도 OutputView도 보면 현재 객체 생성이 가능한데요. 객체 생성할 필요가 없다면 객체 생성을 하지 못하도록 막는게 더 좋을듯 합니다.
[불필요한 객체 생성은 피하라](https://github.com/Meet-Coder-Study/book-effective-java/issues/6)라는 글을 한번 확인해보세요 :)

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +    public void moveAll() {
이쪽에 대한 테스트 코드는 현재 없는거 같아요.
혹시 한번 작성해볼까요?

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/RacingGame.java
> +public class RacingGame {
이쪽에 대한 테스트 코드는 아예 없는거 같습니다.
한번 테스트 코드를 작성해서 검증해볼까요?

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/controller/GameController.java
>  public class GameController {
RacingGame이 생기게 되면서 컨트롤러가 굉장히 깔끔해졌네요 💯

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/RacingGame.java
> +        return Arrays.stream(carNames.split(","))
"," 여기에도 매직스트링이 있네요!

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/RacingGame.java
> +    private Cars createCars(String namesInput) {
private 메서드보다는 public 메서드를 더 위쪽에 올리는게 좋을거 같습니다 :)

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/Result.java
> +    private final Winner winner;
Winner가 한명이 아닐꺼 같은데, 이런경우에는 Winner가 한명이 아니라는 의미를 나타내주면 좋을거 같아요.
예를들면 WinnerCars로 나타내는거죠.
혹시 썬의 생각은 어떠신가요:?

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/TrialNum.java
> +    private int value;
여기도 value로 하신 이유가 있나요?

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/model/Winner.java
> +                .allMatch(car -> car.getPosition() == maxPosition)) {
if문 내의 조건은 변수로 빼서 작성하는게 더 깔끔해 보일거 같습니다 :)

2022-02-17 12:28 UTC, ksy90101 commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println(car.getName() + COLON + makeDash(car.getPosition()));
String 연산은 성능이 굉장히 좋지 않은데요.
String 연산은 어떻게 해야 할까요?
한번 StringBuilder와 StringBuffer를 찾아보세요 :)

2022-02-17 12:28 UTC, ksy90101 commented on src/test/java/racingcar/RacingGameTest.java
> +        assertThat(actual).contains("sun").doesNotContain("bom");
저는 개인적으로 한 assertThat에서 하나의 검증만 이뤄지는게 좋을거 같다는 생각이 들어요.
혹시 썬은 어떤 생각이실까요?

2022-02-18 05:57 UTC, syoun602 commented on src/test/java/racingcar/model/CarTest.java
>      @DisplayName("특정 값을 통한 자동차 비전진 확인")
✅

2022-02-18 06:13 UTC, syoun602 commented on src/test/java/racingcar/model/WinnerTest.java
> +public class WinnerTest {
ㅠㅠㅠㅠㅠ 클래스 자동 생성을 할때마다 까먹네요...... 감사합니다....

2022-02-18 06:52 UTC, syoun602 commented on src/main/java/racingcar/view/OutputView.java
>  public class OutputView {
앗! 정리해두신 글 잘 보았습니다!!! 객체 생성 비용 때문에 무분별한 객체 생성의 위험성에 대해 알아볼 수 있었습니다. 현재 InputValidator나 OutputView는 자동 생성자 때문에 의도하지 않았더라도 사용자는 이를 알 수 없기에 해당 객체를 사용할 여지가 있군요... 

아이템4의 `인스턴스화를 막으려거든 private 생성자를 사용하라` 를 참고해서 고쳐보았습니다!!

2022-02-18 07:36 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +    public void moveAll() {
❓ 

넵!! 해당 테스트 코드를 작성하기 위해 기존에 cars의 인스턴스 필드에 있던 RandomNumberGenerator를 RacingCar로 옮겨서 moveAll()에서 인자를 통해 randomNumber라는 구현체를 받아오도록 변경하였습니다. 하지만 이 과정에서 RacingGame 안에 인스턴스 변수가 4개로 늘어나게 되었는데 이렇게 되면 RacingGame에 너무 많은 요소가 들어간 것인지 궁금합니다!!

2022-02-18 07:44 UTC, syoun602 commented on src/main/java/racingcar/controller/GameController.java
>  public class GameController {
감사합니다 👀

2022-02-18 08:12 UTC, syoun602 commented on src/main/java/racingcar/model/RacingGame.java
> +public class RacingGame {
RacingGame 테스트 클래스는 기존에 최종 우승자 출력에 대한 테스트만 진행하고 있기에 경주 게임 정상 종료 조건 테스트를 추가하여 race()가 진행되어 TryCnt가 증가하고 있는지를 확인해보았습니다!!


❓ ❓ ❓ : 여기에 관해서 질문이 있는데 이외에 메소드들은 단순 객체 생성에 관한 것들인데 단순 객체 생성도 doesNotThrowException() 등을 이용해서 정상적으로 만들어지는지 테스트를 해야하나요??

2022-02-18 08:12 UTC, syoun602 commented on src/main/java/racingcar/model/RacingGame.java
> +        return Arrays.stream(carNames.split(","))
✅

2022-02-18 08:14 UTC, syoun602 commented on src/main/java/racingcar/model/RacingGame.java
> +    private Cars createCars(String namesInput) {
✅

2022-02-18 08:20 UTC, syoun602 commented on src/main/java/racingcar/model/Result.java
> +    private final Winner winner;
✅  앗 넵 우승자가 복수로 나타날 수 있으므로 저도 WinnerCars와 같은 명시적인 네이밍이 더 낫다고 판단됩니다!!

2022-02-18 08:22 UTC, syoun602 commented on src/main/java/racingcar/model/TrialNum.java
> +    private int value;
그냥 값에 의미로 사용하였는데, 다시보니 VO가 TrialNum이므로 number로 하는게 더 좋다고 생각되어 변경하였습니다 🙂

2022-02-18 08:25 UTC, syoun602 commented on src/main/java/racingcar/model/Winner.java
> +                .allMatch(car -> car.getPosition() == maxPosition)) {
✅

2022-02-18 08:29 UTC, syoun602 commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println(car.getName() + COLON + makeDash(car.getPosition()));
가변성을 가지는 속성 때문에 문자열의 추가, 수정, 삭제의 경우 더 빠른 연산이 되네요! 앞으로도 string 연산이 필요한 경우 사용하겠습니다 !!

2022-02-18 08:37 UTC, syoun602 commented on src/test/java/racingcar/RacingGameTest.java
> +        assertThat(actual).contains("sun").doesNotContain("bom");
하나의 assert안에 여러가지 검증이 들어간다면 어디서 잘못되었는지를 모른다는 단점이 있을 것 같습니다! String 비교이기 때문에 정확이 어떤 답을 요구하는 테스트인지 expected에 적어서 Equal로 비교했습니다.

2022-02-18 08:55 UTC, syoun602 commented
안녕하세요 럿고! 2단계도 벌써 두 번째 리뷰 요청이네요. 항상 좋은 피드백 감사합니다! 가끔 똑같은 실수를 반복하는데 신경써서 고쳐보겠습니다 🙁  

---

댓글에 ❓ ❓ ❓ 을 달아서 해당 부분과 관련된 질문을 남겨 놓았습니다!

이외에도 조금 간단한 질문사항이 있는데 럿고의 의견을 들려주세요!!
1. VO를 사용할 경우 equals와 hascode를 재정의가 `항상` 이루어져야 하나요?

2. VO와 dto에 대해서 더 공부해보았는데 그럼 일급컬렉션인 cars나 winnerCars 또한 VO로 분류할 수 있을까요?

3. commit을 할때 만약 한 클래스내에서 작은 변경이력이 있다면 메시지에 refactor(CarTest): ~~~~~ 와 같이 클래스명을 명시하는 것이 더 직관적인가? 에 대한 궁금증이 항상 있었는데, 혹시 럿고는 어떤 방식을 사용하는지 알 수 있을까요?!!

2022-02-19 02:27 UTC, ksy90101 commented on src/main/java/racingcar/model/RacingGame.java
> +public class RacingGame {
개인적으로 저는 단순 객체 생성 같은 경우에는 테스트를 하지 않아도 괜찮을거 같아요.
그러나 단순 객체 생성에 대한 테스트를 해야 할 케이스는 validation이 있을때 일거 같아요. 정확한 객체를 생성하는 것도 테스트의 하나의 일환이라고 생각합니다 :)

2022-02-19 02:28 UTC, ksy90101 commented on src/main/java/racingcar/model/Cars.java
> +    public void moveAll() {
인스턴스 변수가 너무 많아지면 문제가 되지만 4개 정도면 괜찮지 않을까요?
지금까지 썬이 개발하시면서 인스턴스 변수 4개가 너무 많았는지 한번 고민해보세요 :)

2022-02-19 02:29 UTC, ksy90101 commented on src/test/java/racingcar/util/RandomNumberGeneratorTest.java
> +}
```suggestion
}

```

혹시 10000번을 돌린 이유가 있나요?

2022-02-19 02:39 UTC, ksy90101 requested changes
썬 안녕하세요 :) 리뷰어 럿고입니다.
리뷰를 잘 적용해주셨네요 💯 
훨씬 더 깔끔해지고, 테스트 코드도 풍푸해진거 같습니다.
간단한 피드백을 남겼으니, 참고해서 답변을 남겨주시면 합니다 :) 
마지막까지 파이팅 입니다 👍

2022-02-19 02:39 UTC, ksy90101 commented on src/test/java/racingcar/util/RandomNumberGeneratorTest.java
> +}
```suggestion
}

```

혹시 10000번을 돌린 이유가 있나요?

2022-02-19 02:39 UTC, ksy90101 commented on src/main/java/racingcar/model/WinnerCars.java
> +        return cars;
이 부분을 불변으로 해보면 어떨까요?

2022-02-19 02:39 UTC, ksy90101 commented on src/main/java/racingcar/model/WinnerCars.java
> +                .allMatch(car -> car.getPosition() == maxPosition);
getter를 사용을 최소화 하는 이유가 잇을까요?
Car에게 메시지를 보내서 position이 같은지를 물어볼수도 잇을거 같아요 :) 
혹시 어떻게 생각하실까요?

2022-02-19 02:39 UTC, ksy90101 commented on src/main/java/racingcar/model/Result.java
> +    private final WinnerCars winnerCars;
사실 저는 WinnerCars와 Result와 다른 의미의 객체인지를 모르겠네요.
혹시 이런 경우에는 어떤 문제가 잇을까요?

객체를 최대한 쪼개는것도 좋지만, 객체가 너무 많아진다면 협업 동료가 이해하기가 어려움이 있을꺼 같아요.
따라서 저는 쓸모없는 객체를 만들지 않는게 좋다고 생각이 들어요.
썬의 생각은 어떠실까요?

2022-02-19 02:42 UTC, ksy90101 commented
제가 답변을 남기다가 모르고 엔터를 눌러버렸어요.
질문에 대한 답변은 여기에 남길게요.

1., VO를 사용할 경우 equals와 hascode를 재정의가 항상 이루어져야 하나요?
네 저는 항상 재정의가 이뤄지는게 좋을거 같아요 :) VO는 필드값을 검증해 동일한지를 보는 경우가 많으니깐요!

2. VO와 dto에 대해서 더 공부해보았는데 그럼 일급컬렉션인 cars나 winnerCars 또한 VO로 분류할 수 있을까요?
네 저는 일급컬렉션도 VO의 일환이라고 생각합니다.

3. commit을 할때 만약 한 클래스내에서 작은 변경이력이 있다면 메시지에 refactor(CarTest): ~~~~~ 와 같이 클래스명을 명시하는 것이 더 직관적인가? 에 대한 궁금증이 항상 있었는데, 혹시 럿고는 어떤 방식을 사용하는지 알 수 있을까요?!!
이건 사실 케바케 일거 같아요 :) 저는 클래스명을 명시를 안하고 있는데요. 그 이유는 github의 diff를 보면 충분히 어느 클래스가 변경되었는지 알수가 있기 떄문에 굳이 쓸 필요가 없다고 생각이 들어요. 커밋메시지를 잘 작성해놓은다면, 이런 부분들도 다 알수 있을듯 해요!

2022-02-19 13:36 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +    public void moveAll() {
원래는 변수 네개가 많다고 생각을 해보지 않았었는데, 자동차 경주 자체가 조금 가벼운 프로그램이라 여쭤보았습니다! 감사합니다!

2022-02-19 13:38 UTC, syoun602 commented on src/main/java/racingcar/model/RacingGame.java
> +public class RacingGame {
앗 감사합니다! 저 또한 해당 방식을 이용해보겠습니다 🙂

2022-02-19 13:43 UTC, syoun602 commented on src/main/java/racingcar/model/Result.java
> +    private final WinnerCars winnerCars;
넵 저 또한 두 객체가 동일한 역할을 하고 있다는 생각이 들었습니다. 만약 결과에 우승한 자동차 이외에 다른 값들이 필요했다면 별도로 Result와 WinnerCars를 두었겠지만, 현재는 그러한 상황이 아니기 때문에 Result 를 삭제하고 winnerCars를 반환하도록 변경했습니다!

2022-02-19 14:06 UTC, syoun602 commented on src/main/java/racingcar/model/WinnerCars.java
> +                .allMatch(car -> car.getPosition() == maxPosition);
Getter를 자주 사용할 경우 해당 객체의 상태값이 외부에서 다른 로직을 수행할 수 있게 되어 객체가 행동하거나 메시지를 주고 받는 상태가 아니게 됩니다. 하여 객체가 그 역할을 충분히 하지 못하게 되는 것으로 알고 있습니다. 해당 경우 또한 이와 같은 상황이기 때문에 isSamePosition() 이라는 메서드를 통해 객체가 메시지를 보내도록 변경하였습니다!

2022-02-19 14:09 UTC, syoun602 commented on src/main/java/racingcar/model/WinnerCars.java
> +        return cars;
WinnerCars 내부에서 final로 선언하여 괜찮을거라고 생각했었는데, 외부로 상태값이 보내질 경우 변경될 우려가 있었네요! unmodifiableList를 통해 불변으로 변경했습니다!

2022-02-19 14:23 UTC, syoun602 commented on src/test/java/racingcar/util/RandomNumberGeneratorTest.java
> +}
사실 랜덤 값이 0~9 사이라는 테스트를 어떻게 돌려야할 지 모르겠어서 그냥 최대한 많은 빈도 수로 확인해보자는 의미가 컸는데, 이는 확률적인 테스트이기 때문에 좋은 테스트인가? 라는 생각이 들었습니다. 인터넷에 다른 글을 참고해본 결과 랜덤 생성이라는 테스트는 제공되는 라이브러리를 테스트 하겠다는 것이기 때문에 라이브러리를 믿고 해당 테스트를 진행하지 않아야겠다고 결론을 지었습니다.... 

혹시 다른 의미로 물어보신거라면 힌트를 남겨주시면 더 고민해보겠습니다!!

2022-02-19 15:09 UTC, syoun602 commented
안녕하세요 럿고! 또 한번 리뷰 요청 드립니다!! 답변해주신 것들을 통해 항상 더 많은 것을 찾아보게 되고 배우는 것 같습니다 감사합니다!

2022-02-19 15:10 UTC, ksy90101 commented on src/test/java/racingcar/util/RandomNumberGeneratorTest.java
> +}
네 정답을 잘 찾아가셨네요 :) 
라이브러리를 극단적으로 할 필요가 없다는 의미였습니다.
그러나 이건 정책이 들어가있죠? 현재 같은 경우에는 10이하의 값이 나오는 부분일거 같아요. 
누군가 이 정책을 깰수도 있으니 테스트 코드는 넣어두셔야 합니다 :)

2022-02-19 15:17 UTC, ksy90101 commented on src/main/java/racingcar/model/Result.java
> +    private final WinnerCars winnerCars;
Dto라고 명시되어 있지 않아서 Dto라는 생각을 하지 못했네요 😂
개인적으로 아직은 Dto까진 사용하지 않으셔도 된다고 생각합니다 :) 
규모가 작아서 포장하지 않고 이런걸 의도한건 아니였습니다 ㅎㅎ

2022-02-19 15:20 UTC, ksy90101 approved these changes
썬 안녕하세요 리뷰어 럿고 입니다 :) 
2차 리뷰도 잘 적용해주시고, 답변도 남겨주셔서 감사합니다.
훨씬 깔끔하고, 테스트 코드를 통해 많은 검증이 된거 같네요!
썬과 계속 이야기 하면서 저도 많이 배우는 시간이였습니다 :) 
이만 썬의 자동차 경주 미션은 마무리 하도록 할게요.
그동안 너무 고생 많으셨습니다 💯 

언제든지 질문이 있다면 DM이나 댓글을 남겨주세요~

2022-02-19 15:20 UTC, ksy90101 commented on src/test/java/racingcar/model/CarsTest.java
> +        assertThat(cars.getCars().stream()
테스트 코드도 클린코드를 신경써야 한다고 생각이 드는데요.
assertThat 매개변수도 변수로 뺴서 명명을 해주면 더 가독성이 올라갈꺼 같아요 :)

2022-02-19 15:21 UTC, merged