[2단계 - 자동차 경주 리팩터링] 써머(최혜원) 미션 제출합니다.
woowacourse/java-racingcar pull request #390
Opened 2022-02-17 13:31 UTC by hyewoncc

안녕하세요, 범블비!
남겨주신 리뷰 감사하게 읽었습니다 
2단계는 Model과 View가 서로 의존하지 않도록 분리하고,
mvc 패턴에 대해 공부하며, 패턴 구조와 의도에 맞게 클래스를 수정하는 걸 중점으로 진행해봤어요

View에 의존하는 걸 포함해 controller가 할 일을 GameService에서 떼어 내니,
GameService에서 하는 일이 Cars의 메서드를 실행시키는 일 밖에 남지 않았습니다
그랬더니 이번 미션의 제가 작성한 코드에서는 service가 아닌 Cars가 model에 해당한다는 사실이 비로소 보여서
service를 삭제하고 controller가 Cars를 조작하게 했어요 
이제까지는 service를 두루뭉술하게 비즈니스 로직을 담당하는 레이어다 정도로 알고 있었는데,
'비즈니스 로직'이라는 개념을 정확히 몰라 controller의 역할을 적당히 나눠주려 했던 게 문제였다고 성찰했습니다 

또 테스트 쪽도 변경 했는데요, 
```java
void randomNum_is4OrOver_carGoForward() {
        Car testCar = new Car("test");

        // 랜덤값이 4일 때 전진
        testCar.goForward(intRandomCondition);
        assertThat(testCar.getPosition()).isEqualTo(1);

        //랜덤값이 5일 때 전진
        testCar.goForward(intOverRandomCondition);
        assertThat(testCar.getPosition()).isEqualTo(2);
    }
```
이 부분의 컨텍스트가 분리되지 않았던 게 제일 큰 문제였지만, 반복 코드도 획기적(?)으로 줄였어요 
이렇게 하니까 좀 귀찮네~ 하다 올려주신 ParameterizedTest 자료를 보고,
아, 역시 귀찮은 부분은 항상 더 나은 방법이 어딘가는 있는 법인데... 하고 
너무 미션 마감에 초조해 하지 말고 자료도 더 적극적으로 찾아보자, 그게 더 빠른 길이다! 싶었습니다 

프리코스 때 부터 늘 객체 지향 정말 뭔지 모르겠다.. 헛발질 하고 있는 것 같다... 하는 괴로움이 있었는데요 
Car의 isAlsoWinner 메서드가 객체 지향 입장에서 왜 바람직한 메서드인지 꼼꼼히 알려주셔서
아! 하고 조금 감을 잡은 기분이 들었습니다 😭 
마지막 코멘트를 읽고 괴로움 대신 더 열심히 할 의욕과 용기를 얻었어요! 감사합니다! 
이번 기회에 잘 이해가 안갔던 객체 지향 책을 다시 읽어보려고 해요

원래 궁금한 걸 쓰려고 한 pr인데, 지금은 질문이 떠오르지 않는 걸 보니 모른다는 걸 모르는 상태 같네요 
매번 감사합니다, 이번 리뷰도 잘부탁드려요!

2022-02-17 15:18 UTC, ddaaac requested changes
안녕하세요 써머!

이전 단계에서 잘 작성해주셔서 코드의 변화가 그리 많지 않네요 👍 
남겨둔 리뷰도 잘 반영해주셨어요. 간단하지만 생각해볼만한 코멘트 남겼습니다.

> mvc 패턴에 대해 공부하며, 패턴 구조와 의도에 맞게 클래스를 수정하는 걸 중점으로 진행해봤어요

잘 수정해주셨어요. 레이싱카 미션은 단순한 MVC 패턴만으로도 충분히 깔끔하게 구현할 수 있는 미션인 거 같아요. 각 객체가 적당히 자신의 책임을 다하게 구현 잘 해주셨습니다.

> 아, 역시 귀찮은 부분은 항상 더 나은 방법이 어딘가는 있는 법인데... 하고
너무 미션 마감에 초조해 하지 말고 자료도 더 적극적으로 찾아보자, 그게 더 빠른 길이다! 싶었습니다

직접 더 좋은 방법을 찾아보려는 습관 💯 
더 나은 방법을 직접 찾아보셔도 좋고, 리뷰를 제출해서 리뷰어에게 책임을 미루는 것도 하나의 방법입니다. 우테코 미션이 리뷰 중심으로 진행돼서 얻는 장점 중 하나죠.

> 원래 궁금한 걸 쓰려고 한 pr인데, 지금은 질문이 떠오르지 않는 걸 보니 모른다는 걸 모르는 상태 같네요

저도 교육을 받았던 입장에서 공감하는 코멘트네요 ㅋㅋㅋ

이해가 안 가시는 부분이 있으면 편하게 DM이나 코멘트 주세요~

2022-02-17 15:18 UTC, ddaaac commented on src/main/java/racingcar/view/Input.java
> +    public static String[] getCarNamesSeperatedByDelimiter(String delimiter) {
[Array보단 List](https://velog.io/@new_wisdom/Effective-java-item-28.-%EB%B0%B0%EC%97%B4%EB%B3%B4%EB%8B%A4%EB%8A%94-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)를 사용해볼까요?

2022-02-17 15:18 UTC, ddaaac commented on src/main/java/racingcar/view/Input.java
> +            return getCarNamesSeperatedByDelimiter(delimiter);
스택오버플로우를 불러일으킬 가능성이 있는 재귀함수는 지양하는게 좋습니다.
입력값이 잘못되면 그대로 exception을 던지고 끝나도 될 거 같아요(아마 이 내용은 스프링을 배울 때 쯤에 이해가 될 거 같아요)

2022-02-17 15:18 UTC, ddaaac commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(car -> car.goForward(RandomUtil.getRandomForCar()));
`moveAllByRandom()` 도메인 객체 `Cars`의 메서드임에도 테스트가 불가능해보여요.
어떻게 하면 이 메서드를 테스트해볼 수 있을까요?

메서드를 호출할 때마다 랜덤한 넘버를 반환하는 객체를 만들어서 Cars에 넘겨주면 되지 않을까 싶어요.

조금 더 고민해보시면 좋을 거 같아서 코멘트는 이 정도까지 남길게요. 너무 오래 고민하시진 마시고 적당히 고민하다가 방법이 잘 안 떠오르면 다시 코멘트 남겨주세요!

2022-02-17 15:18 UTC, ddaaac commented on src/test/java/racingcarTest/CarTest.java
> +    void randomNum_is4OrOver_carGoForward(int random, int expectedCarPosition) {
`@ParameterizedTest`를 사용해서 경계값까지 잘 테스트해주셨어요.

여기서는 `@MethodSource`에 대해서 생각해보면 좋을 거 같아요.
전 테스트 코드는 한 눈에 들어와야 좋다고 생각합니다.  `@MethodSource`를 사용하면 **물리적으로** 테스트 코드와 테스트 소스의 거리가 멀어지게 됩니다. 한 도메인에 대한 테스트가 많아질수록 거리는 더 멀어지게 되겠죠. 그만큼 테스트 코드도 읽기 어려워지겠구요.

필요하면 사용하는게 맞겠지만 여기서는 `@CsvSource`정도만 사용해도 원하는 바를 충분히 달성할 수 있을 거 같아요.
추가로 `@ValueSource`도 많이 사용한답니다 :)

2022-02-18 07:46 UTC, hyewoncc commented on src/main/java/racingcar/view/Input.java
> +            return getCarNamesSeperatedByDelimiter(delimiter);
여기 재귀함수를 쓴 이유는 while(True)문 안에 try ~ catch문을 쓰니 depth가 2가 되어서였는데요,
depth를 줄이면서 할 방법이 그냥 try ~ catch만 메서드로 떼어 내고 다시 while 문 안에 넣는다.. 밖에 생각나지 않아요 
찾아보니 꼬리 재귀 얘기가 나오는데 이 케이스에 적용하긴 힘들어 보이고요 
미션에서는 프리 코스 때와 달리 재요청 하라는 얘기는 없었지만 방법을 알고 싶은데,
스프링을 배울 때 쯤 이해가 될 거라는 말은 그 때는 스프링에서 뭔가 획기적인 해결책을 제공한다는 얘기일까요?
아니면 스프링의 원리를 배우다 보면 스택 메모리 관리에 대해 이해를 얻을 거라는 얘기인지 궁금합니다

2022-02-18 13:02 UTC, ddaaac commented on src/main/java/racingcar/view/Input.java
> +            return getCarNamesSeperatedByDelimiter(delimiter);
예외가 발생했을 때 다시 입력을 받지 말고 프로그램을 종료하는게 어떨까 하는 코멘트였습니다.
[예외는 정말 예외 상황에만 사용해라](https://icarus8050.tistory.com/112)라는 아이템을 보면, 예외가 발생하면 이미 정상적인 상황이 아님을 알 수 있습니다. 예외를 잡아서 다시 정상적인 상황으로 돌려놓을 필요가 없다는 얘기겠죠.

스프링은 어플리케이션 전역에 try~catch가 걸려있는 모양입니다.
프로그램이 예외를 던지면 최상위에 있는 try~catch가 잡아서 클라이언트에 에러가 발생했다고 알려주는 식이죠.
아래와 같은 느낌이라고 보시면 좋을 거 같아요.
```java
    try {
        RacingController.run()
    } catch() {
    }
```
스프링이야 예외가 발생했다고 프로그램이 종료되면 안되니 이런 처리를 하지만, 이번 미션에서는 꼭 처리를 해줄 필요는 없어보여요.
그대로 throw 하고 프로그램을 종료해도 좋을 것 같습니다.

2022-02-18 16:20 UTC, hyewoncc reviewed
전략 패턴이 범블비가 리뷰로 남겨준 고민의 맞는 방법인지는 자신이 없지만,
이 경우에 AllMoveStrategy와 NoMoveStrategy를 작성한 것이 테스트 코드만을 위한 코드 짜기에 해당하지 않을지 궁금합니다
나중에 프로그램을 확장한다면 실제로 쓸 수도 있겠지만, 지금으로써는 테스트 외엔 너무 쓸모없게 느껴져서요
이번 리뷰도 잘부탁드릴게요!

2022-02-18 16:20 UTC, hyewoncc commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(car -> car.goForward(moveStrategy.canMove()));
이동 유형을 MoveStrategy로 빼서, boolean 값을 canMove() 메소드로 반환하는 세 가지 구현체를 만들었어요
- 랜덤값을 생성하고 기준치를 넘으면 true를 반환하는 RandomMoveStrategy
- 무조건 true를 반환하는 AllMoveStrategy
- 무조건 false를 반환하는 NoMoveStrategy  

그래서 프로덕션 코드에서는 RandomMoveStrategy를, 
테스트 코드에서는 All/NoMoveStrategy를 전달했습니다  
다만 이러면 All/NoMoveStrategy가 테스트 코드 작성을 위한 클래스가 되어버려서 맞는 방향성인지 모르겠어요

2022-02-18 16:20 UTC, hyewoncc commented on src/main/java/racingcar/domain/Car.java
> +        if (canGo) {
다른 분들의 학습 로그를 보다가 전략 패턴에 대해서 알게 되었는데, 
랜덤 생성 객체를 Cars에 넘겨주면 Car에서 랜덤값에 대한 기준치 판단을 할 필요가 없어서 이렇게 수정했습니다 
그런데 지금 발견했는데... 영문을 모르겠지만 공백이 두 칸 이네요? 고쳐두도록 하겠습니다

2022-02-18 16:20 UTC, hyewoncc commented on src/test/java/racingcarTest/CarTest.java
> +        testCar.goForward(move);
@CsvSource를 적용하니 훨씬 깔끔하고 코드도 한 눈에 잘 들어오더라고요! 👍

2022-02-18 16:20 UTC, hyewoncc commented on src/test/java/racingcarTest/CarsTest.java
> +    }
무조건 true를 반환하는 구현체를 넣어, `moveAll이 실제로 모든 Car의 position을 증가시켰는지` 테스트했습니다  
@ValueSource랑 @CsvSource를 적용할 수 없어서 일단 두 가지를 그냥 작성했는데... 
여기야말로 @MethodSource를 써야 했을 것 같기도 하네요 ㅠㅠ

2022-02-18 17:46 UTC, ddaaac commented on src/main/java/racingcar/controller/GameController.java
> +            cars.moveAll(new RandomMoveStrategy());
매번 RandomMoveStrategy 객체를 생성하지 않아도 될 거 같아요.

2022-02-18 17:46 UTC, ddaaac commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(car -> car.goForward(moveStrategy.canMove()));
잘 작성해주셨습니다! `MoveStrategy`란 인터페이스를 둠으로써 자동차들이 어떻게 움직일지를 자유롭게 런타임에 정할 수 있게 되었어요.

> 다만 이러면 All/NoMoveStrategy가 테스트 코드 작성을 위한 클래스가 되어버려서 맞는 방향성인지 모르겠어요

맞습니다. 테스트 코드만을 위한 클래스/메서드는 지양되어야하죠. 그런데 여기 조건이 하나 더 붙습니다.
테스트 코드만을 위한 "프로덕션 코드에 작성되는" 클래스/메서드는 지양되어야합니다. 
테스트 디렉토리 하위에 테스트 코드가 생기는 건 문제가 없지 않을까요?

2022-02-18 17:46 UTC, ddaaac commented on src/main/java/racingcar/domain/Car.java
> +        if (canGo) {
`Cars` 객체에 전략패턴 잘 적용해주셨어요. 여기서 좀 더 개선해볼 부분이 있는 거 같아요.

현재 `Car` 객체는 움직임에 있어서 수동적입니다. 누군가가 가라고 하면 가고, 가지말라고 하면 가지 않고 있죠.
사실 이렇게 되면 굳이 파라미터로 boolean을 넘겨주지 않고 상위 객체에서 if 문을 처리하는 게 좋을 수도 있을 거 같아요.

`Car` 객체를 좀 더 주체적으로 변경해볼까요? `Car` 객체에도 전략패턴을 적용해보면 좋을 거 같네요.
[이 글](https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/)을 참고해보세요!

2022-02-18 17:46 UTC, ddaaac commented on src/test/java/racingcarTest/CarsTest.java
> +    }
이 부분은 써머가 판단하시면 좋을 거 같아요. 지금은 분리돼있는 테스트만 작성해보셨으니 `@MethodSource`를 사용해서도 작성해보시는거죠. 어느 쪽이 더 직관적으로 이해할 수 있을까 고민해보시고 선택하시면 될 것 같습니다.

----

전체적으로 코멘트를 봤을 때 코드나 성장의 방향성에 대해서 많이 걱정하시고 있는 거 같아요.
레이싱카 미션은 우테코 레벨1의 첫번째 미션입니다. 이전 코멘트에도 몇 번 남겼지만 정말 잘해주고 계세요.
교육 시작하고 아직 2주도 채 안지난 시점에서 얼마나 많은 걸 배웠는지 돌아보면 자신감 회복에 좀 도움이 될까요?
써머가 작성해주신 코드를 보면 많은 고민을 한 게 느껴지고, 그 결과도 코드를 충분히 개선시키고 있으니 자신감을 가져도 될 거 같아요.
남은 미션도 화이팅! 💪

2022-02-18 17:46 UTC, ddaaac requested changes
안녕하세요 써머!

리뷰 반영 잘 해주셨어요.
코멘트 남긴 부분들 답변 달았으니 확인해주세요!

2022-02-20 14:23 UTC, hyewoncc commented
안녕하세요, 범블비! 남겨주신 리뷰 잘 읽고 반영했어요
미션 진행하며 다른 분들 코드를 보니 제가 몰랐던 게 많아 초조함이 있었는데, 티가 났구나 싶어 조금 머쓱했어요 ㅋㅋ
범블비가 남겨준 코멘트를 보고 처음 제출했던 코드를 보니, 미션을 하면서 정말 많은 것을 배웠구나 싶어서 자신감이 좀 차올랐어요
다 범블비의 세심한 코드리뷰 덕입니다🙇 감사해요!!

2022-02-20 16:59 UTC, ddaaac approved these changes
안녕하세요 써머 👋

첫 번째 미션 진행하시느라 정말 고생 많으셨습니다.

`Car` 객체에 대한 예리한 통찰력이 인상적이었습니다. 처음 작성했던 코드에 비해 훨씬 가독성도 좋아졌구요.

이번 미션은 머지해도 될 것 같네요. 남은 미션들도 화이팅입니다!

2022-02-20 16:59 UTC, ddaaac commented on src/test/java/racingcarTest/domain/AlwaysMoveStrategy.java
> +        return 9;
기왕이면 경계값이면 더 안정적인 테스트가 되지 않을까 싶어요.

2022-02-20 16:59 UTC, ddaaac commented on src/main/java/racingcar/domain/Car.java
> +    public void goForward(int number) {
객체로 엮는 것도 좋을 것 같아요.
`goForward(number)`란 시그니처와 `goForward(moveStrategy)`라는 시그니처 중에
어떤 쪽이 특정 조건을 만족하면 차가 이동한다를 더 잘 나타내는지 생각해보아요.

2022-02-20 16:59 UTC, merged