[2단계 - 자동차 경주 리팩터링] 아리(양유림) 미션 제출합니다.
woowacourse/java-racingcar pull request #395
Opened 2022-02-17 15:19 UTC by ulimy

안녕하세요 핀!
이제서야 step2 리뷰요청을 보내서 죄송합니다.
노트북이 갑자기 망가져서 정신이 없었어요ㅠㅠ
이번 리뷰도 잘 부탁드립니다. 감사합니다 :)

2022-02-18 00:10 UTC, lalize requested changes
안녕하세요 아리!
2단계도 잘해주셨습니다~ 코드가 점점 깔끔해지고 있네요 👍
몇 가지 코멘트 남겨두었으니 고민해보시고 리뷰 반영 부탁드릴게요!
궁금한 점 있으시면 편하게 DM 주셔도 좋습니다!

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>          if (target >= CONDITION_FOR_MOVE) {
1단계에서는 [메서드 시그니처를 수정하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/) 로 테스트하기 쉬운 구조로 리팩토링 하셨는데요~
지금처럼 테스트 하기 쉬우면서 코드의 변경 없이 확장할 수 있으려면 어떻게 해야할까요?
충분히 고민하시고나서 아래 글을 읽어보시면 좋을 것 같아요!


* [상속보다는 조합(Composition)을 사용하자.](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/)
* [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/)

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarDTO.java
>      public String getCarName() {
getter는 일반적으로 필드명과 같은 이름으로 짓습니다 :)

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarName.java
> +    private static final String NO_SPACE = "[ERROR] 공백을 포함하는 자동차 이름은 허용되지 않습니다.";
일반적으로 상수가  필드보다 위에 위치합니다 :)

```suggestion
    private static final int MIN_LENGTH_OF_NAME = 1;
    private static final int MAX_LENGTH_OF_NAME = 5;
    private static final String EMPTY_CAR_NAME = "[ERROR] 자동차 이름이 입력되지 않았습니다.";
    private static final String MORE_THAN_ONE_LETTER = "[ERROR] 1글자 미만의 자동차 이름은 허용되지 않습니다.";
    private static final String LESS_THAN_FIVE_LETTER = "[ERROR] 5글자 초과의 자동차 이름은 허용되지 않습니다.";
    private static final String NO_SPACE = "[ERROR] 공백을 포함하는 자동차 이름은 허용되지 않습니다.";
    
    private final String name;
```

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>      }
보통 getter는 일반 메서드보다 아래에 위치하도록 합니다 :)

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarName.java
> +    public static void validateCarName(String name) {
```suggestion
    private static void validateCarName(String name) {
```

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarName.java
> +    }
클래스 메서드로 선언하신 이유가 궁금합니다 :)

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    }
`Set<Car>` 를 매개변수로 받는 주 생성자를 만들고 해당 생성자는 부 생성자로 만드는 게 어떨까요?
생성자가 많을수록 클래스는 더 개선되고, 사용자는 클래스를 더 편하게 사용할 수 있습니다!

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    public Car getCar(String name) {
테스트를 위한 편의 메서드는 제거해주세요.

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    }
move라고 해도 충분할 것 같네요!

```suggestion
    public void move() {
        for (Car car : cars) {
            car.move(generateRandomNumber());
        }
    }
```

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +public class CarRepository {
`Set<Car>`에 대한 일급컬렉션을 만들려고 하신 것 같은데요!
Repository라는 네이밍보다 Cars와 같은 네이밍이 좋지 않을까요?

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<String> selectWinners() {
이름을 반환하기 보다는 Car를 반환하는 게 어떨까요?

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<CarDTO> getExecutionResult() {
getExecutionResult가 CarRepository의 책임인가요?

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    private int getMaxPosition() {
필드를 반환하는 메서드가 아니면 getter 네이밍 보다는 findMaxPosition 등과 같은 네이밍이 좋을 것 같아요.

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +                .orElse(0);
getter를 사용하지 않고 객체에게 메시지를 보내서 해결할 수는 없을까요?

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final String SIGN_OF_CAR_NAME = ",";
static이 빠졌네요 :)

```suggestion
    private static final String SIGN_OF_CAR_NAME = ",";
```
---

그리고 사용자 입력을 분리하는 것이 RacingGame 도메인의 책임인지 한번 고민해보시면 좋을 것 같아요.

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +    private int totalAttempt = 0;
객체를 제대로 초기화하지 않고 사용하게 되면 어떤 문제가 발생할까요?
객체를 생성할 때는 항상 초기화하는 게 좋습니다.

2022-02-18 00:10 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +        List<List<CarDTO>> totalExecutionResult = new ArrayList<>();
`List<List<CarDTO>>` 가 어떤 의미인지 이해하기 어렵네요.
`주행 기록`과 같은 도메인 객체를 만드는 건 어떨까요?

2022-02-18 00:10 UTC, lalize commented on src/test/java/racingcar/CarRepositoryTest.java
> +        assertThat(cars.selectWinners()).containsExactly("co");
getCar와 같은 테스트를 위한 편의 메서드를 도메인 코드에 작성한 부분과 우승자 구하는 것을 테스트하기 위해서 4 이상 입력되면 자동차가 움직인다라는 내부 구현을 안다는 전제로 테스트 코드를 작성하게 된 근본적인 원인이 무엇인지 한번 고민해보세요.

2022-02-18 00:10 UTC, lalize commented on src/test/java/racingcar/RacingGameTest.java
> +    RacingGame racingGame;
테스트 코드도 접근 제어자를 항상 신경써주세요.

2022-02-18 07:55 UTC, ulimy commented on src/main/java/racingcar/domain/CarDTO.java
>      public String getCarName() {
수정했습니다ㅠ!

2022-02-18 07:57 UTC, ulimy commented on src/main/java/racingcar/domain/CarName.java
> +    private static final String NO_SPACE = "[ERROR] 공백을 포함하는 자동차 이름은 허용되지 않습니다.";
상수 -> 클래스 변수 -> 인스턴스 변수 순서대로 정렬 하겠습니다.

2022-02-18 07:59 UTC, ulimy commented on src/main/java/racingcar/domain/Car.java
>      }
수정 했습니다!

2022-02-18 08:02 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +    private int totalAttempt = 0;
넵 :)

2022-02-18 09:38 UTC, ulimy commented on src/main/java/racingcar/domain/CarName.java
> +    }
생성자 안에서 사용되는 메서드이다보니 당연히 클래스 메서드로 선언해야만 사용 가능하다고 생각했는데 억측이었군요! 수정했습니다.

2022-02-18 09:54 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    }
해당 생성자 말고 다른 생성자를 이용할 일이 없는데도 선언하는 것이 더 좋은 코드라는 이야기일까요..?

2022-02-18 09:55 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    }
동의합니다 수정 했습니다!

2022-02-18 09:57 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +public class CarRepository {
동의합니다. 수정했습니다.

2022-02-18 10:00 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<String> selectWinners() {
우승자는 이름만 출력하기 때문에 Car를 통째로 반환하는 것은 필요 없는 데이터까지 반환하는 것이라 생각하여 이름만 반환하도록 구현했습니다!

2022-02-18 10:02 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<CarDTO> getExecutionResult() {
getExecutionResult는 현재 모든 자동차의 진행 횟수를 DTO에 담는 함수이기 때문에 모든 자동차에 대한 정보를 담고있는 CarRepository의 책임이라 생각했습니다.

2022-02-18 10:03 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    private int getMaxPosition() {
동의합니다. 수정했습니다.

2022-02-18 10:06 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +                .orElse(0);
전체 자동차의 position 중에서 최대값을 구하는 함수인데 각 자동차에게 메시지를 보내서 해결하라는 이야기가 어떤 의미인지 조금만 더 설명해주실 수 있을까요?ㅜㅜ

2022-02-18 10:13 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final String SIGN_OF_CAR_NAME = ",";
사용자에 입력에 관한 처리이니 view에 있는 것이 맞는 것 같습니다. 수정했습니다.

2022-02-18 10:28 UTC, ulimy commented on src/test/java/racingcar/RacingGameTest.java
> +    RacingGame racingGame;
넵 수정했습니다.

2022-02-18 10:28 UTC, ulimy commented on src/main/java/racingcar/domain/CarName.java
> +    public static void validateCarName(String name) {
수정했습니다.

2022-02-18 11:38 UTC, ulimy commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<CarDTO> getExecutionResult() {
ExecutionResult을 도메인 분리해보니 해당 도메인해서 실행결과를 구성하는 것이 맞는 것 같아 수정했습니다!

2022-02-18 11:39 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +        List<List<CarDTO>> totalExecutionResult = new ArrayList<>();
동의합니다! 수정했습니다.

2022-02-18 16:12 UTC, lalize requested changes
아리! 질문에 대한 답변은 코멘트로 남겨두었습니다~
아직 리뷰 반영이 안된 부분이 있어 확인해 주시면 감사하겠습니다!
그리고 몇 가지 코멘트도 추가 했으니 이것도 같이 봐주시면 좋겠습니다~
추가로 궁금한 점 생기시면 그때 그때 편하게 DM 주셔도 좋습니다~

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/CarDTO.java
>  public class CarDTO {
Dto가 어떤 이유로 생성되었고 도메인 영역에 위치하도록 결정했는지 다시 한번 고민해보세요.
* [DTO의 사용 범위에 대하여](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)

도메인 객체로서 의미가 있다면 조금 더 객체가 무엇인지 이름으로 나타내면 좋을 것 같네요.

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/CarName.java
> +    }
일반적으로 public 메서드 아래 private 메서드가 오는 것이 컨벤션이지만, 컨벤션을 일부 지키면서 서로 관련있는 코드는 모으는 게 가독성이 더 좋을 수 있습니다.

```suggestion
    public CarName(String name) {
        validateCarName(name);
        this.name = name;
    }

    private void validateCarName(String name) {
        validateEmpty(name);
        validateSpace(name);
        validateLength(name);
    }

    private void validateEmpty(String name) {
        if (name == null || name.isEmpty()) {
            throw new IllegalArgumentException(EMPTY_CAR_NAME);
        }
    }

    private void validateSpace(String name) {
        if (name.contains(" ")) {
            throw new IllegalArgumentException(NO_SPACE);
        }
    }

    private void validateLength(String name) {
        if (name.length() < MIN_LENGTH_OF_NAME) {
            throw new IllegalArgumentException(MORE_THAN_ONE_LETTER);
        }

        if (name.length() > MAX_LENGTH_OF_NAME) {
            throw new IllegalArgumentException(LESS_THAN_FIVE_LETTER);
        }
    }
    
    public String getName() {
        return this.name;
    }
```

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/Cars.java
> +    }
리뷰를 잘못드렸던 것 같습니다 🙇‍♂️ 

주 생성자를 두고 정적 팩토리 메서드를 사용하면 좋을 것 같습니다!

* [정적 팩토리 메서드(Static Factory Method)는 왜 사용할까?](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)

```suggestion    
    public Cars(Set<Car> cars) {
        validateDuplication(cars);
        this.cars = cars;
    }
    
    public static Cars of(String[] names) {
        Set<Car> cars = new HashSet<>();
        for (String name : names) {
            cars.add(new Car(name));
        }
        
        return new Cars(cars);
    }
```


다만 아래 생성자는 오직 테스트를 위해 생성된 생성자로 보입니다.

```java
public Cars(Map<String, Integer> carInfo) {
    Set<String> names = carInfo.keySet();
    validateDuplication(names.toArray(new String[names.size()]));

    for (String name : names) {
        cars.add(new Car(name, carInfo.get(name)));
    }
}
```

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/Cars.java
> +    public List<CarDTO> convertToDTO() {
[DTO의 사용 범위에 대하여](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/) 한번 읽어보시는 것을 추천드립니다!

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/Cars.java
> +    }
외부에서 cars를 변경하면 객체 내부 상태가 변경되고 의도하지 않은 방법으로 사용될 수 있겠네요.
* [방어적 복사와 Unmodifiable Collection](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +    private List<ExecutionResult> totalExecutionResult = new ArrayList<>();
Cars, totalAttempt를 받는 생성자를 통해 객체를 초기화 하는 게 어떨까요?

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +    private List<ExecutionResult> totalExecutionResult = new ArrayList<>();
`totalExecutionResult`를 필드로 둬야할까요?

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +        totalAttempt = Integer.parseInt(attempt);
사용자 입력이 문자열로 입력되어 도메인 객체까지 영향을 끼치고 있네요.
파싱 작업은 도메인 밖에서 처리하는 게 좋지 않을까요?

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/Cars.java
> +        HashSet<String> hashSet = new HashSet<>(Arrays.asList(carNames));
구체적인 타입보다는 추상적인 타입을 사용해주세요!

2022-02-18 16:12 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>      }
>최종우승자를 테스팅 하기 위해 코드를 수정하는 과정에서
getCar() 라는 메소드를 새롭게 작성한 것은 테스트 편의를 위한 메소드이니 삭제하라 해주셨고,
모든 멤버변수의 초기화 값을 입력받는 생성자를 만드는 것은 테스트를 위한 것이 아니라 생각된다는 피드백 주셨습니다.
테스트를 위한 코드가 추가된다는 점은 동일한데 후자는 가능한 이유를 알 수 있을까요?

현재는 객체를 생성하는 방법이 클라이언트 구현에 의존적이며, 생성자가 추가될 때마다 객체 검증 및 초기화를 중복으로 해야하는 것으로 보여요.
객체 검증 및 초기화는 주 생성자에서 하고 부 생성자가 주 생성자를 사용하면 단순히 테스트를 위한 생성자라고 할 수 있을까요?

```java
public Car(String name) {
  this(new CarName(name), DEFAULT_POSITION);
}

public Car(CarName name, int position) {
  this.name = name;
  this.position = position;
}
```

2022-02-18 16:22 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +    public List<String> selectWinners() {
> 우승자는 이름만 출력하기 때문에

View에 의존적인 코드를 구현한 게 아닐까요?

CarRepository 입장에서는 selectWinners라는 건 우승 자동차 목록을 가져올 것 같다고 생각되지 않나요?
단순히 `List<String>`를 반환하면 사용하는 입장에서는 이 값이 어떤 값인지 내부 구현을 들여다 봐야하지 않을까요?
View에 그릴 때는 View와 데이터를 주고 받는 레이어에서 자동차 이름 목록으로 변환하여 제공해주면 되지 않을까요?

2022-02-18 16:34 UTC, lalize commented on src/main/java/racingcar/domain/CarRepository.java
> +                .orElse(0);
자동차 최대 거리값을 구하는 게 아닌 최대 거리에 있는 자동차를 가져오면 getter를 사용하지 않고도 해결할 수 있을 것 같아요!
```java
// Car.java
public Car selectWinner(Car car) { // TODO };

// CarRepository.java
private Car findFirstWinner() { // TODO };
```

2022-02-19 16:12 UTC, ulimy commented on src/main/java/racingcar/domain/CarName.java
> +    }
안그래도 조금은 불편한 컨벤션이군.. 이라고 생각하던 참이었는데! 역시 가독성을 위해 컨벤션을 지키지 않기도 하는군요. 수정했습니다.

2022-02-19 16:21 UTC, ulimy commented on src/main/java/racingcar/domain/Cars.java
> +        HashSet<String> hashSet = new HashSet<>(Arrays.asList(carNames));
이유가 궁금하여 검색해보니 유연한 코드를 위해서임을 알게되었습니다. 구현 클래스를 수정해야 할 경우 저런 코드라면 문제가 될 수 있겠군요. 수정했습니다.

2022-02-19 16:50 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +        totalAttempt = Integer.parseInt(attempt);
파싱 작업이 도메인이 아니라 뷰에서 이뤄지도록 리팩토링 해보았는데요. 그러다보니 문자를 입력하는 경우의 테스팅을 위해 private이어야 할 것 같은 InputView.validateIntegerThenParse 함수가 public으로 선언되는 일이 발생했습니다. 또한 이렇게 되니 시도횟수를 검증하는 코드가 ( 정수인지 검증하는 부분 InputView /  양수인지 검증하는 부분 - RacingGame ) 둘로 쪼개지게 되었습니다. 저는 이것보다는 이 전의 코드가 더 가독성이 좋다고 느껴지는데 핀의 의견은 어떠신가요?

2022-02-19 16:51 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +    private List<ExecutionResult> totalExecutionResult = new ArrayList<>();
동의합니다. 수정했습니다!

2022-02-20 03:54 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +        totalAttempt = Integer.parseInt(attempt);
`validateIntegerThenParse`는 `inputAttemptCount` 구현의 일부로 보이는데요! private로 변경하고 가능하면 `inputAttemptCount`를 테스트해야 하지 않을까요?

사용자 입력에 대한 검증과 도메인 검증은 분리되어야 한다고 생각합니다!

2022-02-20 06:05 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +    private List<ExecutionResult> totalExecutionResult = new ArrayList<>();
함수 내에서 충분히 해결될 수 있는 변수였기에 삭제했습니다!

2022-02-20 13:06 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +        totalAttempt = Integer.parseInt(attempt);
넵 뷰에서 이뤄지도록 하고, InputStream을 통해 콘솔 입력을 테스팅 할 수 있도록 구현했습니다!

2022-02-20 14:42 UTC, ulimy commented on src/main/java/racingcar/domain/Cars.java
> +    }
정적 팩토리 메소드.. 핀 덕분에 처음 알게되었습니다! 덕분에 다음 리뷰 요청이 늦어졌네요..ㅎㅎㅎㅎㅎ 덕분에 테스팅 하기가 훨씬 수월한 코드가 완성되었습니다! 다만 공부하다보니 of는 여러개의 매개변수를 받아서 객체를 생성하는 메서드명, from은 한개의 매개변수를 받아서 객체를 생성하는 메서드명으로 선정하는 것이 컨벤션이라고 하여 from으로 선언했습니다!

2022-02-20 14:43 UTC, ulimy commented on src/main/java/racingcar/domain/Cars.java
> +    }
Collections.unmodifiable() 처음 알게되었습니다! 감사합니다 :)

2022-02-20 14:48 UTC, ulimy commented on src/main/java/racingcar/domain/Car.java
>      }
생성자가 또 다른 생성자를 호출하는 방식.. 핀 덕분에 처음 알게되었습니다! 다만 public Car(CarName name, int position)는 Car 내부에서만 이용되는데 public으로 선언 할 필요가 없지않을까요? 또한 private으로 선언한다면 테스팅 코드에는 이용할 수 없게됩니다.. 그렇다면 0으로 초기화 해주는 것과 큰 차이가 없게 되는데요.. 핀의 의견은 어떠신가요?

2022-02-20 14:51 UTC, ulimy commented on src/main/java/racingcar/domain/Car.java
>      }
저는 DEFAULT_POSITION 을 Car가 아닌 Cars에 선언하는 방법이 떠오르는데요. 이 상수에 대한 책임은 Cars가 아니라 Car가 가지고 있는 것이 맞는 것 같다는 생각도 듭니다.

2022-02-21 00:49 UTC, lalize requested changes
안녕하세요 아리~ 피드백 반영 잘해주셨어요!
몇 가지 코멘트와 질문에 대한 답변을 남겨두었으니 확인 부탁드릴게요!
추가로 궁금한 점 있으시면 코멘트나 DM 주세요~

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>      }
> public Car(CarName name, int position)는 Car 내부에서만 이용되는데 public으로 선언 할 필요가 없지않을까요? 또한 private으로 선언한다면 테스팅 코드에는 이용할 수 없게됩니다.. 그렇다면 0으로 초기화 해주는 것과 큰 차이가 없게 되는데요.. 핀의 의견은 어떠신가요?

주 생성자를 private으로 선언하면 어떤 이점이 있을까요? 오히려 클래스 사용을 어렵게 만들지 않나요?
현재는 내부에서만 사용된다고 해도 조금 더 유연하게 객체를 생성할 수 있는 방법을 제공하면 좋다고 생각합니다.
참고로 저는 객체를 완전히 초기화하고 검증할 수 있는 주 생성자를 만들고 필요하면 부 생성자를 만드는 방식을 선호합니다!

> 저는 DEFAULT_POSITION 을 Car가 아닌 Cars에 선언하는 방법이 떠오르는데요. 이 상수에 대한 책임은 Cars가 아니라 Car가 가지고 있는 것이 맞는 것 같다는 생각도 듭니다.

부 생성자가 name만 받는다고 하면 position을 어떤 값으로 초기화할지는 Car가 스스로 결정해야하지 않을까요?

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>          if (target >= CONDITION_FOR_MOVE) {
저번에 피드백 드린 부분도 한번 도전해보면 좋을 것 같아요 :)

https://github.com/woowacourse/java-racingcar/pull/395#discussion_r809523451

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/CarName.java
> +public class CarName {
equals & hashcode도 재정의하면 졿을 것 같네요!

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +        this.totalAttempt = totalAttempt;
attempt도 객체로 포장할 수 있지 않을까요?

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/Cars.java
> +import static racingcar.util.RandomUtil.generateRandomNumber;
```java
public class RandomUtil {
    private static int MAX_NUMBER = 9;
    private static int MIN_NUMBER = 0;
    ...
}
```

final이 빠졌네요!

2022-02-21 00:49 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +        return Collections.unmodifiableList(totalExecutionResult);
해당 메서드에서 새 리스트를 반환하니까 `unmodifiableList`를 해주지 않아도 될 것 같아요!

2022-02-21 06:19 UTC, ulimy commented on src/main/java/racingcar/domain/Car.java
>      }
외부에서 사용되지 않는다면 priavate이어야 한다는 저의 고정관념이었던 것 같습니다. 아직 주성생자 부생성자에 활용능력이 부족한 것 같네요. 더 공부해보겠습니다!

2022-02-21 07:19 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +        this.totalAttempt = totalAttempt;
너무 좋은 생각입니다. 포장했습니다!

2022-02-21 07:20 UTC, ulimy commented on src/main/java/racingcar/domain/Cars.java
> +import static racingcar.util.RandomUtil.generateRandomNumber;
헉 제가 빼먹었네요. 수정했습니다!

2022-02-21 07:20 UTC, ulimy commented on src/main/java/racingcar/domain/RacingGame.java
> +        return Collections.unmodifiableList(totalExecutionResult);
동의합니다. 수정했습니다.

2022-02-21 07:21 UTC, ulimy commented on src/main/java/racingcar/domain/Car.java
>          if (target >= CONDITION_FOR_MOVE) {
제가 왜 이 피드백을 놓쳤을까요... 인터페이스 분리라니 생각지도 못한 방법입니다. 알려주셔서 너무너무 감사합니다 핀!

2022-02-21 08:09 UTC, ulimy commented on src/main/java/racingcar/domain/CarName.java
> +public class CarName {
재정의함으로써 자동차 이름의 중복을 처리할 수 있도록 하였고, 중복을 검증하여 에러를 발생시키는 코드가 불필요해져 삭제했습니다.

2022-02-21 10:31 UTC, lalize approved these changes
안녕하세요 아리 🐥 
코드가 정말 많이 개선되었고~ 피드백 반영도 잘해주셨습니다 💯 
첫번째 미션 하느라 정말 고생 많으셨어요!
이번 미션은 여기서 머지하도록 할게요! 다음 미션도 화이팅하세요~

2022-02-21 10:31 UTC, lalize commented on src/main/java/racingcar/domain/Attempt.java
> +        if (attempt <= 0) {
매직넘버는 상수화 해주세요~

2022-02-21 10:31 UTC, lalize commented on src/main/java/racingcar/domain/Car.java
>          if (target >= CONDITION_FOR_MOVE) {
`target >= CONDITION_FOR_MOVE` 조건 자체를 인터페이스로 분리하면 확장에 용이하지 않을까요?

2022-02-21 10:31 UTC, lalize commented on src/main/java/racingcar/domain/RacingGame.java
> +    }
정말 깔끔하네요!

2022-02-21 10:31 UTC, lalize commented on src/test/java/racingcar/domain/CarTest.java
> +        car.move(new MovableNumberGenerator());
인터페이스를 구현해야할 메서드가 하나이면 클래스를 따로 만들지 않고 이렇게도 할 수 있어요!
        car.move(() -> 9);
```

2022-02-21 10:31 UTC, merged

2022-02-21 11:17 UTC, ulimy commented on src/test/java/racingcar/domain/CarTest.java
> +        car.move(new MovableNumberGenerator());
와.. 너무 좋네요 감사합니다..!!