[2단계 - 자동차 경주 리팩터링] 파랑(이하은) 미션 제출합니다.
woowacourse/java-racingcar pull request #399
Opened 2022-02-17 17:23 UTC by summerlunaa

안녕하세요! 파랑입니다.

1. 1단계에서부터 MVC 패턴을 적용시키고자 노력해서 크게 바뀐 부분은 없습니다. Controller, Util 패키지를 만들어 GameController와 Utils를 옮겨놓았습니다.
2. 우승자 출력을 위한 문자열 구성 로직을 domain에서 view로 이동시켰습니다. toString을 사용할 경우 어떤 문제가 생기는지 알려주셔서 이번에 확실히 이해할 수 있었습니다ㅎㅎ.
3. 우승자를 구하는 테스트를 추가해 보았습니다. 테스트를 어떻게 구현해야 할지 고민을 많이 했는데, 현재 구현된 코드로는 테스트를 진행하기가 힘들어 보였습니다. 그래서 Car, Cars 각각에 테스트를 위한 생성자를 추가하여 구현했습니다. 이러한 방식이 맞는지 확신이 없어서 제이의 리뷰와 내일 있을 자동차 경주 피드백을 듣고 리팩토링 해보려 합니다! 

감사합니다 :)

2022-02-19 03:59 UTC, jjj0611 requested changes
안녕하세요 파랑! 리뷰어 제이입니다.
2단계 제출해주신 코드 잘 봤습니다!

고민해볼만한 부분들 코멘트 드렸으니 확인해주시고 적용해주세요!
제가 파랑이 좀 더 잘 고민해봤으면 좋겠다는 의미로 조금은 추상적으로 남겨서 이해가 잘 안가실 수도 있을텐데,
고민해보시고 많이 어렵다고 느껴지시면 코멘트로 달아주시거나 DM으로 이야기 해주세요 :)

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
> +			cars.add(new Car(carName));
자동차들의 로직을 RacingGameValidator 안에서 해결하고 계시네요!
이렇게되면 RacingGameValidator의 위치가 validator로 들어가야 하는지 고민해보면 좋을 것 같아요.
해당 패키지는 지금 모든 패키지에서 의존하는 패키지가 됩니다.
그런데 RacingGameValidator는 Cars 내에서만 쓰이고 있는데, 이 로직이 Cars에 있지 않고 Validator를 따로 두신 이유가 있을까요?
좀 더 도메인을 고민해보자면 이름의 중복을 허용하지 않는 것과 자동차가 1개인 것은 `이름`의 로직이 아닌 `경주`의 로직입니다.
좀 더 Cars에 가까운 로직이지 않을까요?

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/view/OutputView.java
> +			.forEach(System.out::println);
MVC 패턴을 좀 더 잘 적용해볼까요? :)

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/view/OutputView.java
> +		);
MVC 패턴을 좀 더 잘 적용해볼까요? :)

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
> +		CarNameValidator.validateName(name);
ditto

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
>  	private int position = 0;
0은 무엇이 있을까요?

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
>  	private int position = 0;
두 자료형 String과 int는 각각 의미를 가집니다.
name이라는 필드는 1이상 5이하의 글자수만 가져야 하고, 공백으로만 이루어져 있으면 안됩니다.
position이라는 필드는 위치라는 의미상 음수가 될 수 없습니다.

그냥 String과 int라고만 했을 때 충분히 발생할 수 있는 문제네요.
이런 로직들을 담은 객체로서 만들어주면 어떨까요?

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Car.java
> +	}
테스트를 용이하기 위해 새로운 생성자를 만드신 것 같은데,
조금 단호하게 이 생성자를 없애주세요.
그러면서도 충분히 테스트를 좋게 만들 수 있습니다!
그 부분을 공부하고 적용해보면 어떨까요? :)

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
> +	}
어디서 호출하고 있냐에 따라 다르지만,
현 상태로는 MVC를 조금은 파괴하는 구조가 되었네요.
MVC를 더 잘 적용시켜보면 어떨까요?

2022-02-19 03:59 UTC, jjj0611 commented on src/main/java/racingcar/domain/Cars.java
> +	}
ditto

2022-02-21 06:07 UTC, summerlunaa commented
안녕하세요! 파랑입니다.
리뷰 반영해서 리팩토링 해보았습니다.

1. Name, Position, Winners, MoveCount와 같은 의미있는 변수들을 객체로 만들었습니다.
2.

2022-02-22 10:05 UTC, jjj0611 approved these changes
안녕하세요 파랑! 리뷰어 제이입니다.

Name, Position, Winners, MoveCount와 같은 의미있는 변수들을 객체로 만들었습니다.
이렇게 해서 Validator에 있던 검증 코드들을 각각의 도메인 클래스로 이동시킬 수 있었습니다. 그리고 Winners를 통해서 테스트를 위한 생성자를 없애고 테스트 코드를 조금 더 효율적으로 구현할 수 있었습니다.
MVC을 더 잘 적용시키려 노력했습니다.
OutputView에서 도메인 객체에 의존하지 않도록 수정했습니다.
하면서 궁금했던 점은

1. OutputView는 무조건 domain 객체에 의존하면 안 되는 것인가요? 

-> 무조건이라는 것은 없습니다! 사실 자동차 경주게임 같은 경우에는 view와 도메인을 완전히 분리하는게 더 오버한 설계일 수도 있어요. 또 domain에서 view의 로직을 모르게 하는 것이 첫 걸음이 맞습니다! 다만 view에서도 domain을 모르게 좀 과한 요구를 드렸는데요. 만약 view에서 domain을 알게되는 순간 domain에 불필요한 메서드들이 생길 가능성이 높다고 생각해요. 저는 그래서 최대한 view와 domain은 서로를 몰라야 한다고 생각합니다 :) 일단 domain에서 view를 모르는 것만으로 충분 합니다 :)

2. 이런 경우가 DTO를 사용하면 좋은 경우일까요?

-> 넵 저는 DTO에 대한 존재를 알려드리려고 했던 부분이 있었습니다. 아마 레이스를 보여주는 상태에서 carName : position과 같은 상태를 보여주는거라서 Map<String, Integer>로 전달을 주셨을 것 같은데, 해당 Map은 Car에 대한 정보라는 것에 대한 확신!이 없다고 생각해요. 그냥 key가 String이고, value가 Integer인 자료구조일 뿐이죠. 근데 이런 것을 Dto 같은 것으로 묶어주면 적어도 Class type을 통해 CarDto라는 것을 알 수 있겠죠? dto의 존재를 한 번 인지하셨으면 좋겠다는 생각에 드린 코멘트였습니다!

자동차 경주게임 너무 고생하셨어요!
드린 코멘트가 도움이 많이 되었길 바랍니다 :)
다음 미션도 화이팅 하세요 😄

2022-02-22 10:05 UTC, jjj0611 commented on src/main/java/racingcar/view/OutputView.java
>  	public static final String WINNER_JOIN_DELIMITER = ", ";
public일 이유가 있을지 고민해보면 좋을 것 같아요 :)

2022-02-22 10:05 UTC, jjj0611 commented on src/main/java/racingcar/view/OutputView.java
> +	public static void printCarPosition(Map<String, Integer> carsInfo) {
자동차 정보를 Map이 아닌 형태로 넘겨주는 방법을 고민해보면 좋을 것 같아요 :)

2022-02-22 10:05 UTC, merged