[2단계 - 자동차 경주 리팩터링] 앤지(손수민) 미션 제출합니다.
woowacourse/java-racingcar pull request #409
Opened 2022-02-18 08:58 UTC by soominsohn

안녕하세요 닉! 앤지입니다.
이렇게 또 뵙게되네요 ~ :)

2단계에서는 요구사항인 MVC 패턴 적용과

1단계 PR에서 말씀해 주셨던

1. Cars 일급 컬렉션 사용하여 책임을 분리해 테스트가 용이하게 만들기
2. 문맥에 맞게 공백 라인 추가
3. 자동차 전진조건을 추상화 한 인터페이스 만들기

를 적용해 리팩토링 해보았습니다.
특히 3번을 적용시키며 말씀해 주셨던 

> 어떤 숫자가 4보다 크다 라는 자동차 전진 조건을 추상화해서 boolean을 반환하는 형태의 메서드를 가지는 인터페이스로 만들고, 파라미터로 해당 인터페이스 구현체(람다)를 받아볼 수도 있어요.테스트에서는 테스트하고자 하는 조건을 인터페이스 구현체로 넣어줄 수 있고요.

이 부분을 구현하며 생겼던 궁금한점은 comment로 남겨 두었습니다.

오늘도 감사합니다 닉 :) 
좋은 하루 보내세요~!

2022-02-18 09:17 UTC, soominsohn commented on src/main/java/racingcar/domain/Cars.java
> +            car.movePosition(() -> makeRandom() >= MINIMUM_MOVE);
MoveCondition 이라는 인터페이스를 만들어 isMovable() 이라는 method로 전진 가능한 조건을 추상화 해봤습니다. 
이 때 구현체를 람다로 만들어 파라미터로 넣어 줬습니다. 

구현체를 만드는 과정에서 궁금한점이 생겼습니다.
바로 구현체를 1. 람다로 만든다 vs 2. MoveCondition 인터페이스를 상속받은 RandomMoveCondition 클래스를 만든다.

이 두가지중 어느 것이 더 좋을지에 대한 고민입니다.

1번 람다 방식에 대한 장점으로는

1) 전진에 대한 요구사항이 변경 될때마다 moveCondition을 상속받은 클래스를 만들 필요없이 람다식만 고쳐주면 된다.
2) 객체 생성을 할 필요가 없다.
3) 테스트가 용이하다.

그러나 여기서 의문이 들었던 것은 `전진 조건인 랜덤값이 4이상이면 전진한다.` 를 Cars라는 객체가 알고 있을 이유가 있을까? 였습니다. 

그래서 아예 2번 방법인 RandomMoveCondtion을 만들어 랜덤값 생성도 이 클래스에서 해주고, isMovable()한지 판단도 하여 돌려주는 방법도 생각해봤습니다.

그러나 만들고 나니 다시 도돌이표로 전진에 대한 요구사항이 변경 되면 RandomMoveCondtion은 더이상 필요 없어지는데 따로 관리하는게 필요할까? 로 돌아왔습니다. 

이런 경우에 대해 닉의 의견이 듣고싶습니다! 
감사합니다:)

2022-02-19 08:52 UTC, wbluke requested changes
안녕하세요 앤지~ 인터페이스 잘 적용해 주셨네요 👍 
질문 주신 부분 답변드렸고, 추가적으로 코멘트 드렸으니 확인하시고 리팩토링 해보시면 좋겠습니다 🙂

2022-02-19 08:52 UTC, wbluke commented on src/main/java/racingcar/domain/Cars.java
> +            car.movePosition(() -> makeRandom() >= MINIMUM_MOVE);
저라면 RandomMoveCondtion 을 만들 것 같아요.
현재는 람다로만 있기 때문에 오히려 movePosition() 메서드에 무엇을 파라미터로 넣어주고 있는지 한눈에 알아보기가 어려운 것 같아요 ㅎㅎ
RandomMoveCondtion 객체로 추상화한다면 이름을 통해 명확한 전략을 알려줄 수 있기 때문에 구체 클래스를 만들어서 사용하는 것이 좋다고 생각합니다 :)

다른 이유도 있는데요, 말씀해주신 것처럼 현재는 랜덤생성 로직인 makeRandom() 메서드가 Cars에 있는데, 해당 메서드만 놓고 보면 Cars와 전혀 관련이 없는 로직 같아요 ㅎㅎ
객체를 만들어주면 적절한 위치로 해당 메서드를 옮겨줄 수 있겠네요 :)

2022-02-19 08:52 UTC, wbluke commented on src/main/java/racingcar/domain/Cars.java
> +            car.movePosition(() -> makeRandom() >= MINIMUM_MOVE);
그리고 현재는 랜덤값을 포함한 전략을 Cars 클래스에서 만들어주고 있지만, 이렇게 되니 Cars의 move() 메서드도 테스트하기가 어려워졌어요.
테스트가 어려운 부분을 더 외부로 분리해보면 어떨까요? 그러면 Cars의 해당 메서드도 테스트 가능할 것 같아요 :)

2022-02-19 08:52 UTC, wbluke commented on src/main/java/racingcar/domain/Cars.java
> +            car.movePosition(() -> makeRandom() >= MINIMUM_MOVE);
추가적으로, 자동차가 움직일 때마다 전략이 변경되는 도메인 요구사항이 아니라면,
자동차를 생성할 때 해당 자동차의 전진 전략을 결정해주는 방식은 어떨까요? 
move() 메서드가 더 깔끔해질 것 같아요 :)

2022-02-19 08:52 UTC, wbluke commented on src/main/java/racingcar/domain/Cars.java
> +        return findWinnerByPosition(findMaxPosition(cars), cars);
cars가 필드에 있어서, 메서드 시그니처를 더 깔끔하게 만들 수 있지 않을까요? :)

2022-02-19 08:52 UTC, wbluke commented on src/test/java/racingcar/CarTest.java
>  @SuppressWarnings("NonAsciiCharacters")
아마 메서드 이름 때문에 달아놓으신 것 같은데요, 매 테스트 클래스마다 달아야겠네요.ㅎㅎ
IDE 설정을 이용하는 방법도 있고, JUnit5의 `@DisplayName`을 활용하면 문제가 해결될 것 같아요 :)

2022-02-19 08:52 UTC, wbluke commented on src/test/java/racingcar/CarTest.java
> +        car.movePosition(() -> argument >= 4);
제 생각에는 movePosition() 메서드가 boolean을 반환하는 MoveCondition을 파라미터로 받도록 변경되었기 때문에,
위와 같은 구체적인 전략을 두고 파라미터 테스트를 진행하기 보다는
- `() -> true`일 경우 전진한다.
- `() -> false`일 경우 전진하지 않는다.

요렇게 테스트하면 더 간단하면서도 명확한 테스트가 될 것 같아요 :)

2022-02-19 08:52 UTC, wbluke commented on src/test/java/racingcar/CarsTest.java
> +            .containsExactly("happy", "good");
```suggestion
        assertThat(cars.getCars())
                .extracting("name")
                .containsExactly("happy", "good");
```
요렇게 추출할 수 있는 기능이 있답니다 :)

2022-02-20 05:29 UTC, soominsohn commented on src/main/java/racingcar/domain/Cars.java
> +            car.movePosition(() -> makeRandom() >= MINIMUM_MOVE);
makeRandomNumber() 메서드를 포함한 randomMoveCondition로 바꿔주었어요! 또한 자동차의 생성자에 moveCondition을 넣어 주었답니다! 이렇게 바꾸어주니 한결 더 명확해 보이네요. 어떻게 해야할지 고민 많이 했었던 부분인데 조언해주셔서 감사합니다!

2022-02-20 05:29 UTC, soominsohn commented on src/main/java/racingcar/domain/Cars.java
> +        return findWinnerByPosition(findMaxPosition(cars), cars);
오오! cars를 삭제할 수 있겠군요! 감사합니다.
findWinnerByPosition(findMaxPosition());로 바꾸었습니다 :)

2022-02-20 05:30 UTC, soominsohn commented on src/test/java/racingcar/CarTest.java
>  @SuppressWarnings("NonAsciiCharacters")
IDE 설정에서 바꾸어 주었어요! 클래스 만들때마다 혹시 빼먹을까봐 걱정했었는데, 이제 안심하고 코드를 작성할 수 있겠습니다 감사합니다 :)

2022-02-20 05:30 UTC, soominsohn commented on src/test/java/racingcar/CarTest.java
> +        car.movePosition(() -> argument >= 4);
* () -> true일 경우 전진한다.
* () -> false일 경우 전진하지 않는다.
가 자주쓰여서 상수로 바꾸고, moveCondition을 생성자로 넣으면서 movePosition() 으로 바꾸었습니다!

2022-02-20 05:30 UTC, soominsohn commented on src/test/java/racingcar/CarsTest.java
> +            .containsExactly("happy", "good");
assertThat 이후에 올 수 있는 메서드가 굉장히 많았군요! 다른 상황에서도 사용할 수 있게 다른 메서드들도 정리해봐야겠어요. 감사합니다 :)

2022-02-21 01:37 UTC, wbluke approved these changes
피드백 반영 잘 해주셨네요 👍 
생각해볼만한 코멘트 하나 더 남겼으니 참고해 주시고요, 첫 미션 정말 수고 많으셨어요~! 🙂

2022-02-21 01:37 UTC, wbluke commented on src/test/java/racingcar/CarTest.java
> +    private static final MoveCondition FALSE_MOVE_CONDITION = () -> false;
중복이 많아 상수로 추출하셨군요 ㅎㅎ 👍 

저는 테스트를 작성할 때 조금 다른 시각으로 접근하는데요.
테스트 코드의 역할 중 하나는 프로덕션 코드의 **명세(문서)** 입니다.
그래서 상수보다는 약간의 중복이 발생하더라도 각 테스트에서 given이 무엇인지 나타내주는 게(로컬 변수 등으로 추출해서 더 명확하게 나타내줄 수도 있겠죠), 더 나은 가독성을 가져다준다고 생각해요 ㅎㅎ
다시 말하면 이 프로젝트를 처음 접한 사람이 테스트 문서를 읽으면서, 현재 테스트를 위해 준비된 데이터(Test Fixture, given절)가 무엇인지 한눈에 알아볼 수 있어야 한다고 생각해요.
프로덕션 코드의 상수와는 조금 다른 의미를 가지고 있다고 볼 수 있겠습니다. 한번 참고해보세요 :)

2022-02-21 01:37 UTC, merged