[2단계 - 자동차 경주 구현] 에덴(김성산) 미션 제출합니다.
woowacourse/java-racingcar pull request #417
Opened 2022-02-19 04:06 UTC by leo0842

안녕하세요 핀! 에덴입니다.

지난번 리뷰 요청때 주셨던 여러 코멘트에 대해 이리저리 생각도 해보고 수정 과정을 거쳐 이렇게 2단계 구현에 대한 PR 요청을 드립니다!

핀의 코멘트 덕분에 제 코드에 대해 깊이 생각해 볼 수 있는 기회가 되었습니다. 정말 감사드립니다!

코멘트에 대한 변경 사항과 제 생각을 해당 코드 부분에 덧글 달아놓겠습니다!!

2022-02-19 04:12 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
> +    private final List<Car> cars;
final 을 붙인 이유는 List<Car> 가 재할당되거나 cars 변수가 다른 타입으로 변경되는 것을 막기 위함입니다.

2022-02-19 04:19 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +    }
isWinnerPosition 이었던 메소드명을 isSamePosition 으로 바꾸었습니다. 너무 전체적인 흐름에 집중하여 해당 메소드에 집중하지 못했었던 것 같습니다. 지적 감사드립니다!!

2022-02-19 04:22 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
> +    }
해당 부분 이외에도 int 원시타입 대신 Integer wrapper 클래스 사용을 남용하였습니다. 
실제로 Integer 클래스의 메소드를 이용하지도 않고, null 이 허용되는 부분이 아닌데 Integer wrapper 클래스를 계속 사용하고 있었습니다. wrapper 클래스가 필요하지 않은 부분 모두 원시 타입으로 수정하였습니다. 지적 감사드립니다!

2022-02-19 04:24 UTC, leo0842 commented on src/main/java/racingcar/view/InputView.java
> +    }
getXXX 가 가지는 명칭의 특징에 대해 더 깊이 생각하여 사용하도록 하겠습니다!
해당 부분은 requestXXX 로 변경하였습니다!

2022-02-19 04:40 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +        this.moving = new BiggerNumberMoving(MOVABLE_NUMBER);
Car 에서 interface 를 구현하는 대신 의존 주입받아서 사용하는 것으로 변경해보았습니다.
새로운 패턴에 대해 공부하고 생각해볼 수 있었습니다. 기존 방식대로라면 수정/변경시 OCP 원칙을 위배한다는 사실에 대해 알게 되었고 해당 패턴을 적용하여 수정, 확장에 용이하도록 변경하였습니다. 
지적 감사드립니다!!

2022-02-19 04:43 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +        return name.getName();
추상화 수준이 다른 부분에 대해 수정하였습니다.
해당 부분에서 getter 가 반환하는 값을 실제 값(int, String) 으로 할지, 해당 값 객체(Location, Name) 으로 할지 고민을 해보았습니다. getter 를 호출하는 객체에서 원하는 값은 무엇인지, 값 객체를 그대로 전달하는 게 맞는 것인지 등에 대해 생각해보았고, 결론적으로 실제 값을 반환하는 것으로 수준을 맞추었습니다.

2022-02-19 04:45 UTC, leo0842 commented on src/main/java/racingcar/model/Name.java
> +
가독성을 위한 의미있는 공백 줄을 추가하였습니다. 이외의 부분에도 지적해주신 곳 모두 공백 줄을 추가하였습니다. 지적 감사드립니다!

2022-02-19 04:45 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
> +    public int participateSize() {
해당 부분 이외에도 int 원시타입 대신 Integer wrapper 클래스 사용을 남용하였습니다.
실제로 Integer 클래스의 메소드를 이용하지도 않고, null 이 허용되는 부분이 아닌데 Integer wrapper 클래스를 계속 사용하고 있었습니다. wrapper 클래스가 필요하지 않은 부분 모두 원시 타입으로 수정하였습니다. 지적 감사드립니다!

2022-02-19 04:45 UTC, leo0842 commented on src/main/java/racingcar/view/InputView.java
>      }
getXXX 가 가지는 명칭의 특징에 대해 더 깊이 생각하여 사용하도록 하겠습니다!
해당 부분은 requestXXX 로 변경하였습니다!

2022-02-19 05:11 UTC, leo0842 commented on src/test/java/racingcar/model/ParticipantsTest.java
>  }
해당 테스트에 대해서 고민도 많이 해보고 크루들에게 요청하여 처음으로 의논도 나눠보았습니다.

1. private 을 public 으로 바꾸어 랜덤 값을 강제로 부여하는 방법
- 이 방법은 지양해야 하기 때문에 일찍 접었습니다.
2. private 에서 사용되는 Math.random() 을 mockito 의 when().thenReturn() 으로 조작하는 방법
- Math 가 final 클래스여서 mock 으로 전환이 되지 않아 실패하였습니다. Math 클래스의 생성자가 private 이기때문에 인스턴스화도 불가능하였습니다. [관련 글](https://www.baeldung.com/mockito-final)
3. car에게 tryMove 메세지를 요청하는지만 알아보기 위해 verify() 확인
- 역시 car 객체를 mock 으로 전환할 수 없어 실패하였습니다.

이외에도 핀이 남겨주신 [메서드 시그니처를 수정하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/) 도 확인하였고, 해당 부분은 Car 객체에서 구현되어 있는 것을 확인하였습니다.

Participants 객체에서 단순히 car 객체에 tryMove 메세지를 for loop 를 돌면서 요청하는 것이기때문에 굳이 해당 메소드가 있어야 하나 싶어서 race 메소드를 없애는 것도 생각해 보았지만 participants 내부에서 요청하는 것이 책임이 명확해 보였기때문에 메소드를 남겨 놓았습니다.

결론적으로 car 에게 요청보내는 tryMove() 메소드는 car 에서 테스트 케이스가 존재하며, race() 내부에서 for loop 를 돌면서 단순히 car 에게 메세지 요청보내는 것이 race() 의 역할이기때문에 굳이 현재 로직에서는 테스트가 필요하지 않다고 판단하였습니다.

2022-02-19 08:09 UTC, lalize requested changes
안녕하세요! 에덴!
2단계 리팩토링 정말 잘 해주셨어요! 코드가 굉장히 읽기 쉽고 깔끔하네요~ 👍
질문에 대한 답과 몇 가지 코멘트 남겨두었으니 확인 후 반영 부탁드릴게요!
궁금한 점 있으시면 언제든지 편하게 DM 주셔도 좋아요~

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/controller/Racing.java
> +        String[] carNames = inputView.requestCarNames().split(",");
split 처리는 requestCarNames에서 해도 되지 않을까 싶어요 ㅎ

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/controller/Racing.java
>              participants.participateInRacing(car);
참가자 목록을 생성과 동시에 초기화 해도 좋을 것 같네요.

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/BiggerNumberMoving.java
> +}
전략 패턴 👍

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +    private final static int MOVABLE_NUMBER = 4;
Moving 인터페이스 구현에 따라 해당 상수가 안쓰일 수도 있겠네요!
실제로 사용하는 쪽에 선언하면 좋지 않을까요?

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +        this.moving = new BiggerNumberMoving(MOVABLE_NUMBER);
딱 제가 원하던 방식이였습니다!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +    public Car(String name) {
Name, Location, Moving을 인자로 받는 주 생성자를 만들고 해당 생성자를 부 생성자로 바꾸면 좋을 것 같네요!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +    public void tryMove(int number) {
이제 메서드가 인자를 받지 않아도 충분히 요구사항을 만족할 수 있는 형태로 바꿀 수 있겠네요.
사용자 입장에서는 해당 입력을 굳이 넣어주지 않아도 되고  number가 tryMove에서 어떻게 처리되는지 알 필요도 없겠군요!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +    public boolean isSamePosition(int position) {
👍

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Name.java
Name 객체를 완전한 VO 형태로 만들 수 있을 것 같아요!

* [VO(Value Ojbect)란 무엇일까?](https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/)

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Participants.java
>              car.tryMove(makeRandomNumberBetweenZeroAndNine());
https://github.com/woowacourse/java-racingcar/pull/417#discussion_r810448496

> 결론적으로 car 에게 요청보내는 tryMove() 메소드는 car 에서 테스트 케이스가 존재하며, race() 내부에서 for loop 를 돌면서 단순히 car 에게 메세지 요청보내는 것이 race() 의 역할이기때문에 굳이 현재 로직에서는 테스트가 필요하지 않다고 판단하였는데 테스트가 없어도 되는 건지 여쭙고 싶습니다!

race 내부 구현을 아는 상태라서 테스트가 불필요하다고 느껴진 게 아닐까요? race 내부 구현이 바뀌었을 때는 어떻게 될까요?!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Participants.java
> +    public List<String> findRacingWinners() {
객체의 내부를 반환하기 보다는 일급 컬렉션이 관리하는 Car 자체를 반환하는 게 어떨까요?
String을 반환하는 이유는 View 때문인 것 같습니다!
View에 데이터를 넘겨주는 레이어에서 String 으로 변환해서 넘겨주면 좋지 않을까요?

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/Participants.java
>                          .map(Car::getCarPosition)
여기서도 결국엔 `getter`를 사용하고 있는데요~
`객체에 값을 꺼내지말고 메시지를 보내라`를 지키려면 어떻게 해야할까요?
`두 자동차 중에서 우승자를 구해줘`라는 메시지를 보낼 수도 있겠군요!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/model/PlayTime.java
> +    }
* [equals와 hashCode는 왜 같이 재정의해야 할까?](https://tecoble.techcourse.co.kr/post/2020-07-29-equals-and-hashCode/)

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println(String.join(WINNER_RESULT_DELIMITER, winners) + WINNER_RESULT_MESSAGE);
깔끔해졌네요!

2022-02-19 08:09 UTC, lalize commented on src/test/java/racingcar/model/CarTest.java
> +        assertThat(car.isSamePosition(1)).isEqualTo(true);
테스트하려는 대상은 isSamePosition인데 tryMove가 잘못되어 테스트가 실패한건지, isSamePosition이 잘못되어 테스트가 실패한건지 어떻게 알 수 있을까요?

테스트는 독립적이어야 합니다!

2022-02-19 08:09 UTC, lalize commented on src/test/java/racingcar/model/ParticipantsTest.java
>  }
관련 코드에 코멘트 남겼습니다!

2022-02-19 08:09 UTC, lalize commented on src/main/java/racingcar/controller/Racing.java
>          showRacingResult();
콘솔 출력을 매 반복문 마다, 서로 다른 시점에 하는 게 아니라 웹 요청과 응답처럼 한번에 출력할 수는 없을까요?

2022-02-21 02:28 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +    public Car(String name) {
덕분에 주 생성자와 부 생성자에 대해 알아볼 수 있게 되었습니다. 감사합니다!!

2022-02-21 03:11 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +    public void tryMove(int number) {
메서드가 인자를 받지 않도록 구상을 해보았는데, Car 객체 내부 또는 전략 패턴 구현체 내부에서 random number 를 생성하는 쪽으로 생각해 보았습니다. 하지만 그렇게 구성을 한다면 핀이 남겨주셨던 [메서드 시그니처를 수정하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/) 와 같이 테스트 하기가 힘들 것 같아서 우선은 인자를 받는 쪽으로 놔두었습니다. 혹시 다른 방안이 있을까요??

2022-02-21 03:13 UTC, leo0842 commented on src/main/java/racingcar/model/Name.java
Equals 와 hashCode 를 override 하여 완전한 VO 형태로 만들었습니다! Location 은 변수가 계속 수정이 이루어지기때문에 완전한 VO 형태로는 만들지 않았습니다!

2022-02-21 03:18 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
>              car.tryMove(makeRandomNumberBetweenZeroAndNine());
race 라는 메소드에 대해 다시 한번 생각해 보았습니다. 아래 핀의 코멘트와 함께 race 메소드가 매 레이싱 결과를 반환하도록 구상해보았고 race 메소드가 레이싱 결과를 잘 반환하는지 테스트 케이스를 만들어 보았습니다. 테스트가 필요하지 않다고 말씀드린 부분에 대해서는 매우 잘못된 생각이었던 것 같습니다. 벽보고 반성하겠습니다!

2022-02-21 03:19 UTC, leo0842 commented on src/main/java/racingcar/model/PlayTime.java
> +    }
좋은 정보 감사드립니다! 두 메소드가 인텔리제이에서 왜 함께 묶여있는지 알게 되었습니다!

2022-02-21 03:21 UTC, leo0842 commented on src/main/java/racingcar/controller/Racing.java
> +        String[] carNames = inputView.requestCarNames().split(",");
requestCarNames에서 split 처리를 하도록 수정하였습니다. View 의 역할에 대해 조금 더 깊게 고민해보겠습니다!

2022-02-21 03:23 UTC, leo0842 commented on src/main/java/racingcar/controller/Racing.java
>              participants.participateInRacing(car);
해당 부분에 대해서 Participants 를 생성할 때 carNames 를 가지고 한번에 만들도록 수정하였습니다. 결과로 불필요한 메소드가 줄어들 수 있었습니다. 지적 감사드립니다.

2022-02-21 03:23 UTC, leo0842 commented on src/main/java/racingcar/model/Car.java
> +    private final static int MOVABLE_NUMBER = 4;
불필요한 변수를 줄이도록 고민해보겠습니다. 감사합니다!

2022-02-21 03:25 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
> +    public List<String> findRacingWinners() {
이 부분에 대해서도 controller 와 view 의 역할, 반환하는 값에 대해 더 생각해보게 되었습니다. 지적 감사드립니다!

2022-02-21 03:26 UTC, leo0842 commented on src/main/java/racingcar/model/Participants.java
>                          .map(Car::getCarPosition)
getter 를 어쩔 수 없이 쓴다는 구실을 만들어 계속 객체의 값을 꺼냈습니다. 메시지를 보내도록 getter 를 최대한 지양하는 쪽으로 짜보겠습니다. 감사합니다!!

2022-02-21 03:29 UTC, leo0842 commented on src/main/java/racingcar/model/PlayTime.java
> +    }
좋은 정보 감사드립니다! 두 메소드가 인텔리제이에서 왜 함께 묶여있는지 알게 되었습니다!

2022-02-21 03:29 UTC, leo0842 commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println(String.join(WINNER_RESULT_DELIMITER, winners) + WINNER_RESULT_MESSAGE);
핀 덕분입니다. 감사합니다 ㅎㅎ

2022-02-21 03:30 UTC, leo0842 commented on src/test/java/racingcar/model/CarTest.java
> +        assertThat(car.isSamePosition(1)).isEqualTo(true);
테스트는 독립적이어야 한다는 말씀에 조금 더 유의하여 테스트를 작성하겠습니다!

2022-02-21 03:31 UTC, leo0842 commented on src/main/java/racingcar/controller/Racing.java
>          showRacingResult();
for loop 안에서 레이싱을 돌 때마다 출력하던 것을 매 레이싱마다 결과를 쌓아 한 번에 출력하도록 수정하였습니다. 덕분에 코드가 더 직관적으로 바뀐 것 같습니다. 감사합니다!

2022-02-21 10:05 UTC, lalize approved these changes
안녕하세요 에덴~
첫번째 미션 진행하느라 고생 많으셨어요!
피드백 반영도 정말 잘해주셔서 구조가 많이 개선이 되었고 가독성도 높아졌네요 💯 
이번 미션은 이만 머지하도록 하겠습니다!! 다음 미션도 화이팅하세요~!

2022-02-21 10:05 UTC, lalize commented on src/main/java/racingcar/model/Car.java
> +    public void tryMove(int number) {
> 전략 패턴 구현체 내부에서 random number 를 생성하는 쪽으로 생각해 보았습니다.

👍 

[메서드 시그니처를 수정하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/) 보다 조금 더 개선된 버전이 에덴이 하신 [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/) 입니다 ㅎㅎ.

2022-02-21 10:05 UTC, lalize commented on src/main/java/racingcar/model/Participants.java
>      }
아직 position을 꺼내서 비교하는 부분이 존재하네요!
아래 예시를 참고해서 개선해보시면 좋을 것 같아요~
```java
public List<Car> findRacingWinners() {
  Car winner = findRacingWinner();

  return cars.stream()
    .filter(car -> car.isSamePosition(winner))
    .collect(...);
}
```

2022-02-21 10:05 UTC, lalize commented on src/main/java/racingcar/model/RacingGame.java
> +public class RacingGame {
👍

2022-02-21 10:06 UTC, merged