[2단계 - 자동차 경주 리팩토링] 이브(이유정) 미션 제출합니다.
woowacourse/java-racingcar pull request #418
Opened 2022-02-19 04:40 UTC by 2yujeong

안녕하세요!
1단계 미션에서 피드백 받은 부분들 리팩토링 해가면서 2단계 진행했습니다.

이번 미션을 진행하면서 던이 남겨주신 리뷰들을 참고하여  MVC 패턴에서 컨트롤러의 역할에 대해 많이 고민해보게 되었고, 관련 내용을 주제로 학습로그도 작성했습니다🙂 
https://prolog.techcourse.co.kr/studylogs/1865
1차 피드백 반영 시에 생각했던 대로 컨트롤러를 뷰와 모델 사이에서 데이터를 전달하는 역할로 정의하고 게임 진행 로직은 별도의 도메인 클래스로 분리하려고 했는데, 막상 리팩토링을 하다보니 컨트롤러의 역할이 모호해진다는 느낌을 받았습니다. 그래서 이번 미션에서는 컨트롤러의 역할을 조금 다른 관점에서 정의하여 어플리케이션의 전체적인 흐름을 조정하는 역할로써 구현하게 되었습니다.

그외 미션 진행하면서 변경된 부분들은 커밋 로그로 남겨놓았습니다😀

2022-02-19 04:47 UTC, 2yujeong commented on src/main/java/racingcar/controller/RacingCarController.java
> +		Cars cars = new Cars(validateCarNames(InputView.getCarNames()));
입력값이 빈 문자열인지 검증하는 메서드, 입력 시도 횟수를 검증하는 로직, 입력 처리(split)는 View에서 처리하도록 구현했는데, 각 자동차 이름에 대한 검증 로직은 자동차 생성 정책에 따라 달라질 수 있기 때문에 비즈니스 로직에 가깝다고 생각하여 split 후 컨트롤러에서 처리하도록 구현했습니다.

2022-02-19 04:50 UTC, 2yujeong commented on src/main/java/racingcar/controller/RacingCarController.java
> +		Cars cars = new Cars(validateCarNames(InputView.getCarNames()));
입력값이 빈 문자열인지 검증하는 메서드 / 입력 시도 횟수를 검증하는 로직 / 입력 처리(split)는 View에서 처리하도록 리팩토링했는데, 각 자동차 이름에 대한 검증 로직은 자동차 생성 정책에 따라 달라질 수 있기 때문에 비즈니스 로직에 가깝다고 생각하여 split 후 컨트롤러에서 처리하도록 구현했습니다.

2022-02-19 07:38 UTC, 2yujeong commented on src/test/java/racingcar/domain/CarsTest.java
>  	}
getSize() 대신 지난 피드백에서 힌트 주신 equals와 hashcode 재정의를 이용하여 자동차 생성 테스트를 리팩토링하려고 했는데 생각대로 잘 구현이 되지 않았습니다😔 핵심 로직인 자동차 생성 기능의 적절한 테스트 방법이 떠오르지 않는다는 건 Cars 설계에 바람직하지 않은 부분이 있기 때문이라는 생각이 들어서 Cars 내부 로직을 조금 리팩토링 했습니다.
우선 최종 우승자를 찾는 로직을 Cars에서 모두 WinnerNames로 옮김으로써 Cars의 WinnerNames에 대한 의존성을 제거했습니다. WinnerNamse에서 unmodifiableList로 넘겨받은 cars를 이용하여 최종 우승자를 찾아 리턴하도록 구현했는데 이 과정에서 추가된 getCars()를 이용하여 자동차 생성을 테스트 할 수 있게 리팩토링했습니다.

2022-02-19 07:41 UTC, 2yujeong commented on src/test/java/racingcar/domain/CarsTest.java
> +    }
getSize() 대신 지난 피드백에서 힌트 주신 equals와 hashcode 재정의를 이용하여 자동차 생성 테스트를 리팩토링하려고 했는데 생각대로 잘 구현이 되지 않았습니다😔 핵심 로직인 자동차 생성 기능의 적절한 테스트 방법이 떠오르지 않는다는 건 Cars 설계에 바람직하지 않은 부분이 있기 때문이라는 생각이 들어서 Cars 내부 로직을 조금 리팩토링 했습니다.
우선 최종 우승자를 찾는 로직을 Cars에서 모두 WinnerNames로 옮김으로써 Cars의 WinnerNames에 대한 의존성을 제거했습니다. WinnerNamse에서 unmodifiableList로 넘겨받은 cars를 이용하여 최종 우승자를 찾아 리턴하도록 구현했는데 이 과정에서 추가된 getCars()를 이용하여 자동차 생성을 테스트 할 수 있게 리팩토링했습니다.

2022-02-19 15:23 UTC, gch01410 commented on src/main/java/racingcar/controller/RacingCarController.java
> +    public final RandomNumberGenerator randomNumberGenerator;
RandomNumberGenerator를 Controller의 인스턴스 변수로 선언한 이유가 있을까요~?

2022-02-19 15:23 UTC, gch01410 commented on src/main/java/racingcar/controller/RacingCarController.java
> +		Cars cars = new Cars(validateCarNames(InputView.getCarNames()));
맞습니다! 저도 자동차 이름에 대한 검증은 비즈니스 로직이라고 생각해요.
근데 비즈니스 로직은 도메인 영역에 있는것이 더 적합하지 않을까요?
자동차 객체가 자동차 이름에 관한 책임을 갖도록 하는건 어떨까요?

2022-02-19 15:49 UTC, gch01410 requested changes
안녕하세요 이브! 리뷰어 던입니다.
코드를 작성하면서 고민했던것들이 느껴지네요! 본인만의 생각을 정리해나가는 모습이 보기 좋습니다!
그리고 벌써 layered architecture까지 공부하셨군요! 대단합니다 💯 
간단한 코멘트 남겼으니 확인 부탁드려요!

2022-02-19 15:49 UTC, gch01410 commented on src/main/java/racingcar/domain/CarStatusDTO.java
> +    int position;
인스턴스 필드는 반드시 private으로 선언해주세요!

2022-02-19 15:49 UTC, gch01410 commented on src/main/java/racingcar/domain/WinnerNames.java
> +    private final List<String> winnerNames;
지금 구조라면 winnerNames 인스턴스 필드가 없어도 구현가능해보여요!
winnerNames를 인스턴스 필드로 선언하지않고 구현해볼 수 있을까요?

2022-02-19 15:49 UTC, gch01410 commented on src/test/java/racingcar/domain/CarsTest.java
> +    public void 최종_우승자_찾기_테스트() {
최종 우승자를 찾는 로직은 Cars의 로직은 아닌것 같아요!

2022-02-19 15:49 UTC, gch01410 commented on src/test/java/racingcar/view/InputValidatorTest.java
> +public class InputValidatorTest {
정상적인 값이 입력되었을 경우 예외가 발생하지 않고 정상적으로 처리되는 케이스도 검증하면 더 꼼꼼하게 테스트 코드가 작성될 것 같아요!

2022-02-20 08:05 UTC, 2yujeong commented on src/main/java/racingcar/controller/RacingCarController.java
> +    public final RandomNumberGenerator randomNumberGenerator;
RandomNumberGenerator의 경우 자동차 경주 게임 실행 시 항상 필요한 객체이고 playGame 메서드가 실행될 때마다 매번 새로 할당될 필요가 없기 때문에 어플리케이션의 전체적인 흐름을 담당하는 컨트롤러의 인스턴스 변수로 선언 후 생성자로 초기화했습니다. RandomNumberGenerator의 컨트롤러 인스턴스 변수 선언과 관련해서 던의 의견은 어떠신지 궁금합니다😀

2022-02-20 12:07 UTC, gch01410 approved these changes
안녕하세요 이브! 리뷰어 던입니다.
MVC 구조로 잘 적용하셔서 코드파악이 쉽게 되네요! 테스트 코드도 꼼꼼하게 잘 작성하셨습니다!
마지막으로 간단한 코멘트 하나 남겼습니다! 확인부탁드려요.
첫번째 미션 구현하시느라 수고많으셨습니다! 👍

2022-02-20 12:07 UTC, gch01410 commented on src/main/java/racingcar/controller/RacingCarController.java
> +    public final RandomNumberGenerator randomNumberGenerator;
👍 이브의 의견도 맞다고 생각합니다!
메서드가 실행할때마다 재할당하지 않기 위해서라면 싱글턴 패턴을 적용해봐도 좋을 것 같네요! (학습을 위해서요!)
저는 반드시 인스턴스 필드로 선언하지않으면 안되는 경우를 제외하고는 메서드의 파라머티로 전달받는다거나 메서드의 로컬변수로 선언하는 편입니다. 변수가 사용되는 범위를 고려하여 선언위치를 결정하는 편입니다! 
이 경우에서는 playGame 메서드에서만 사용되니 playGame메서드의 로컬변수로 선언할 것 같습니다. 그치만 요구사항이 추가되어 여러 메서드에서 RandomNumberGenerator를 사용하게 된다면 그때 인스턴스 필드로 변경할 것 같아요!

그리고 인스턴스 필드는 반드시 private로 설정해주세요!

2022-02-20 12:07 UTC, merged