[1단계 - 자동차 경주 구현] 블랙캣(송우석) 미션 제출합니다.
woowacourse/java-racingcar pull request #467
Opened 2023-02-09 06:20 UTC by Songusika

안녕하세요, 우테코 5기 백엔드 크루 블랫캣(송우석)입니다.
백엔드 크루 에단(김석호)와 함께 진행한 미션 PR 보냅니다.

docs/README.md 에 기능목록과 함께 이번 미션의 목표를 작성하였습니다.
이번 미션의 저희 목표는 MVC와 SRP 원칙을 지키도록 하였습니다.

따끔한 코드리뷰 부탁드리겠습니다.
감사합니다!

2023-02-10 06:01 UTC, Hyeon9mak requested changes
안녕하세요 블랙캣! 자동차 경주 미션을 함께 하게된 현구막입니다~
미션 리뷰가 늦었어요 🙏 

전반적으로 완성도 높게 미션을 진행해주셨어요!
그래서 조금 디테일한 부분들에 코멘트를 남겼습니다 😄 

또 아래와 같은 케이스에서 에러가 발생되는데!
확인 후 리팩터링 해주시면 좋을 것 같아요.
<img width="962" alt="image" src="https://user-images.githubusercontent.com/37354145/218014526-0cd626b9-06bf-487f-9888-d241d94aff8c.png">

궁금하신 점 답글 코멘트와 DM 부담없이 남겨주세요~ 🙇‍♂️

2023-02-10 06:01 UTC, Hyeon9mak commented on docs/README.md
> +- [x] 최종 우승자 출력 OutputView#printWinner()
기능목록 정리 좋아요 👍

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +            names = CommaSeparator.sliceNameByComma(getNames());
Q1. 레이싱 게임 컨트롤러의 역할은 무엇일까요?
Q2. 다른 크루가 블랙캣의 프로젝트를 유지보수하게 된 상황에서  "콤마 대신에 띄어쓰기를 기준으로 문자열을 잘라주세요." 라는 요구사항이 전달된다면 controller 와 view 중 어떤 패키지를 먼저 열어보게 될까요?

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +        } catch (CommaNotFoundException | NameIsOutOfBoundException e) {
표준 예외와 커스텀 예외를 사용했을 때 각각의 장단점은 무엇일까요?

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +        try {
```suggestion
    private RacingCars createRacingCar() {
        try {
                  List<String> names = ...
```



`names` 를 catch 내부에서 사용하려했던걸까요?
지금은 쓰이지 않는 것 같으니 try 내부로 넣어주면 가독성이 더 올라갈 것 같아요 😄

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +    private TryCount getTryCount() {
원시값 포장을 잘 해주셨네요 👍 👍 
믿고 사용할 수 있는 값이 되었네요 😄

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +    }
`tryCount` 의 정확한 값에 대해서는 모르지만, 0 이라는 걸 직접 물어보는 형태네요.

`tryCount` 에게 '더 할 수 있는 기회가 남았니?' 라고 조금 더 추상화해서 물어볼 수도 있을거 같아요 🤔 이러면 유지보수 관점에서 어떤 장점이 생길까요?

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/Name.java
> +    }
`validate...`, `validate...`, `validate` 가 계속해서 반복되네요 😱 
private 접근제한자로 어차피 `Name` 내부에서만 사용되는데, 스탭을 나눠놓을 필요가 있을까요?
콜 뎁스를 조금 더 줄여보면 어떨까요? 줄여서 얻는 이점은 무엇일까요?

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +public class RacingCar extends RandomGenerator {
상속은 IS-A 관계일 때 사용하는 것이 가장 유지보수에 뛰어난 형태라고 생각하는데요, 현재 랜덤 발급기와 레이싱 카는 IS-A 관계가 아닌 것 같아요. 🤔 IS-A 관계가 아닐 때 상속을 사용하게 되면 어떤 일이 생길까요? (유지보수 관점에서)

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +    private static final int moveThreshold = 4;
사용되지 않는 것 같아요 😉

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +public class RacingCar extends RandomGenerator {
`move()` 를 진행할 때 내부에서 난수를 생성하여 진행되기 때문에 테스트가 어려워서 별개로 테스트용 `RacingCar` 객체를 만드는 생성기가 만들어진 것 같은데요, `RandomGenerator`를 이용하는게 `RacingCar`가 아닌 다른 녀석이 되면 어떨까요?

(힌트: 의존성 주입)

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/RacingCars.java
> +    }
일급 컬렉션 활용 💯 👍 
단순 컬렉션의 역할을 넘어 비즈니스 로직의 핵심을 품게된다면 일급 컬렉션으로 만들어서 관리해주면 좋죠

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/domain/RacingCars.java
> +    }
wow! 포지션 기준 역정렬 후 첫번째 원소 (포지션이 가장 먼) 기준 같은 값 추출!! 기가 막히네요 😄 👍 👍 👍 

엇, 그런데 저는 `getSortedByPosition` 네이밍을 보고 오름차순 정렬인 줄 알았어요.. 😢

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/util/RandomGenerator.java
> +}
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/37354145/218011828-3001fb82-c2a8-45ef-9e93-3fa929f80d3b.png">

intellij eof 설정을 해주면 파일 끝에 자동으로 개행이 되어요 😄

2023-02-10 06:01 UTC, Hyeon9mak commented on src/main/java/view/InputView.java
> +    }
`scanner` 변수가 정적으로 선언되어 있는데, 입력을 받을 땐 매번 `Scanner` 인스턴스를 새로 할당하고 있네요! 어떻게 개선할 수 있을까요?

2023-02-10 06:01 UTC, Hyeon9mak commented on src/test/java/domain/NameTest.java
> +    }
// given // when // then 같은 주석 모두 가독성을 위한 것이니까, 필요치 않다면 제거해줘도 좋을 것 같아요 😉

2023-02-10 06:01 UTC, Hyeon9mak commented on src/test/java/domain/RacingCarsTest.java
> +        result.moveAll();
given when then 패턴에서 when 절은 정확하게 하나의 행동만 나타내어주어야 해요!
`RacingCars resut` 조차도 준비절로 보아야 합니다!

2023-02-12 05:30 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +    }
`tryCount` 객체는 포장되어 있기 때문에 안에 어떠한 타입으로 count 를 저장하는지 명확하지 않을 수 있겠네요 (int나, list가 될 수 도 있기에) 따라서 int를 저격하는 `isZero()` 라는 네이밍보다는` isOpportunity()` 네이밍이 더 맞는 것 같네요 좋은 피드백 감사합니다. 덕분에 일급 컬랙션에 대해서도 한번더 돌아보는 계기가 되었어요

2023-02-12 05:30 UTC, Songusika commented on src/main/java/domain/RacingCar.java
> +    private static final int moveThreshold = 4;
미쳐 확인을 못했었네요 수정하였습니다 감사합니다

2023-02-12 05:32 UTC, Songusika commented on src/main/java/domain/RacingCars.java
> +    }
다음부터는 조금더 세세한 네이밍을 해야겠습니다!
해당 로직은 `max()` 메서드를 사용하는 것으로 리팩터링하였습니다.

2023-02-12 05:32 UTC, Songusika commented on src/main/java/util/RandomGenerator.java
> +}
꿀팁감사합니다!

2023-02-12 05:35 UTC, Songusika commented on src/main/java/view/InputView.java
> +    }
InputView 클래스에서 하나의 `Scanner` 인스턴스만 가질 수 있도록 `static final` 키워드로 수정 후 할당하였습니다.

2023-02-12 05:54 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +            names = CommaSeparator.sliceNameByComma(getNames());
A2. 아무래도 콤마로 이름을 구분한다는 도메인 로직보다는 입력받는 로직에 대한 요구사항이니 view 패키지를 먼저볼 거 같네요! 이에 해당 로직을 InputView 클래스로 위임하였고 util 패키지에 있던 `CommaSeperator` 또한 InputView 클래스 내부에서 한번만 사용되어서 InputView 패키지 내부로 옮겨 리팩터링하였습니다.

2023-02-12 05:59 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +        try {
미쳐 발견하지 못했었네요 바로 수정했습니다 감사합니다!

2023-02-12 06:08 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +    }
추가적으로 추후 count 를 저장하는 변수의 타입이 변경 되더라도 메서드명을 바꾸지 않아도 되니 유지보수 관점에서도 좋아보입니다.

2023-02-12 06:09 UTC, Songusika commented on src/main/java/domain/Name.java
> +    }
콜 스텝을 줄임으로써 조금더 가독성 높고 이해하기 쉬운 코드가 되었습니다!

2023-02-12 07:31 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +        } catch (CommaNotFoundException | NameIsOutOfBoundException e) {
표준예외

- 장점
  - 예외메시지만으로도 의미 전달이 가능하다.
  - 가독성이 높아진다.
- 단점
  - 발생 위치를 정확하게 판악하기 힘들 수 있다.
  - 테스트 코드에서 발생 가능한 범위가 넓어 메시지까지 체크하여야 한다.
 
커스텀 예외

- 장점
  - 이름만으로도 어떤 예외가 발생했는지 유추할 수 있다.
  - 상세한 예외 정보를 전달할 수 있다.
  - 예외 발생 후처리가 용이하다.
- 단점
  - 많은 커스텀 예외가 생성될 수 있다.

출처: https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

현제 저의 코드에서도 커스텀 예외가 따로 처리하는 일이 없고,이름을 붙여주는 의미로만 커스텀 예외를 사용했네요!
각 예외 클래스가 에러 메시지를 가지게 하도록 리팩터링 할 수 있지만, 저의 코드에서는 커스텀 예외 클래스가 딱히 처리하는 일이 없고,
에러 메시지로만 충분히 표현 가능하다고 판단해서 표준 예외를 통해서 에러 메시지를 전달해주도록 리팩터링 하였습니다.

2023-02-12 10:50 UTC, Songusika commented on src/main/java/domain/RacingCar.java
> +public class RacingCar extends RandomGenerator {
기존 상속을 이용한 코드는 자동차를 움직이는 요구조건이 변경되어서 `RandomGenerator` 클래스의 `int generate()` 가 변경된다면 해당 클래스를 상속받은 `RacingCar` 클래스에서도 코드 수정이 일어나겠군요!

즉 상위 클래스인 `RandomGenerator` 가 변경되면 하위 클래스인 `RacingCar` 가 강하게 의존, 결합하기 때문에 변경에 유연하게 대처하기 힘들어집니다.

또한 추후 클래스 폭발 문제도 야기할 수 있을 거 같습니다.

따라서 `ThrottleGenerator` 인터페이스를 만들고 이를 구현하는 `RandomThrottleGenerator` 클래스를 별도로 만들었습니다. 이후 `RacingCar` 클래스가 인스턴스 변수로 `ThrottleGenerator` 클래스를 가지는 조합 방식으로 리팩터링 하였습니다.

이렇게 리팩터링하고 보니 ‘무조건 전진’ 혹은 ‘무조건 정지’만 하는 테스트용 `ThrottleGenerator` 를 구현해서 `RacingCar` 객체를 생성할 때 주입하다 보다 더 쉽게 테스트할 수 있게 되었습니다.

해당 부분을 조합으로 구현하다보니 궁금증이 생겼습니다.

**Q**. `RacingCar`가 움직일 수 있는지 검사하는 로직은 `RacingCar` 스스로 `isMoveable()` 을 통해 검사하는데요 이 비즈니스 로직을 `TrottleGenerator` 에 위임하는 것은 어떻게 생각하시나요? 뭔가 지금은 자동차 스스로 _나 움직일 수 있니?_ 라고 묻는 것 같아서요!
추가로 해당 로직을 `TrottleGenerator` 에 위임함으로써 추후 요구사항 변경으로 인해 움직임 조건의 변수 타입이 변경되어도 `RacingCar` 의 변경은 없을테니 유지보수 측면에서도 좋을 것 같아서요! 현구막님의 의견이 궁금합니다!

2023-02-12 12:48 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +            names = CommaSeparator.sliceNameByComma(getNames());
> 레이싱 게임 컨트롤러의 역할을 다음과 같다고 생각하고 구현하였어요!

좋습니다! 정리하자면 Domain 과 View 의 흐름을 관장한다고 말할 수 있겠네요.

> 입력받는 로직에 대한 요구사항이니 view 패키지를 먼저볼 거 같네요!

💯

2023-02-12 12:50 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +        } catch (CommaNotFoundException | NameIsOutOfBoundException e) {
꼭 리팩터링이 필요한 부분은 아니었지만, 한 번 고민해보시면 좋을 것 같아 리뷰드렸습니다 😄 👍 
커스텀 예외의 경우 처음 보는 개발자가 무엇을 뜻하는 예외인지, 다른 엣지 케이스에 사용해도 괜찮은지 혼선이 생긴다는 단점도 있는 것 같아요. 그래서 저는 대부분의 경우 표준 예외를 선호하는 편이긴 합니다.

2023-02-12 12:51 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +    }
> 추가적으로 추후 count 를 저장하는 변수의 타입이 변경 되더라도 메서드명을 바꾸지 않아도 되니 유지보수 관점에서도 좋아보입니다.
💯

2023-02-12 13:08 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +public class RacingCar extends RandomGenerator {
블랙캣이 충분한 고민을 거쳤으므로 지금도 멋지다고 생각하고, `TrottleGenerator`에게 위임하는 것도 좋다고 생각합니다. 정답은 없고 결국 블랙캣의 선택에 따라 달라질 것 같아요. 

> 뭔가 지금은 자동차 스스로 나 움직일 수 있니? 라고 묻는 것 같아서요!

그런 느낌이 드는 건 무작정 코드를 작성하지 않고 객체지향적인 코드를 작성하기 위해 꾸준히 의식하고 있다는 좋은 신호이기도 하지만, 조금 다르게 생각해보면 '왜 객체지향적인 코드가 좋은지, 왜 그런 코드를 짜야하는지' 확신을 갖지 못했다는 뜻 같아요. 자동차가 스스로 '나 움직일 수 있니?' 물어보면 안되는 이유가 무엇일까요?

어떤게 더 좋은 설계일지 헷갈릴 때 제 개인적인 해결책이 있는데, 동료 개발자가 처음 이 코드를 본다면 어떻게 느낄지, 어떻게 만들어 둬야 더 적은 클래스 파일을 열어보고 로직을 이해할지, 어떻게 만들어야 (나를 포함한) 개발자가 유지보수를 할 떄 Files changed 개수가 줄어들지를 상상해보는 것이에요. 사실 블랙캣은 이미 어떤게 더 좋은 설계인지 찾은 걸로 보여요.

> 해당 로직을 `TrottleGenerator` 에 위임함으로써 추후 요구사항 변경으로 인해 움직임 조건의 변수 타입이 변경되어도 `RacingCar` 의 변경은 없을테니 유지보수 측면에서도 좋을 것 같아서요!

저희가 객체지향을 공부하고, 실천하는 이유는 모두 유지보수 때문인 것 같아요. 객체지향에서 이야기하는 원칙들도 모두 유지보수 관점에서 만들어진 것들이구요. https://hyeon9mak.github.io/consider-oop/

2023-02-12 13:31 UTC, Hyeon9mak approved these changes
블랙캣~ 자동차 경주 1단계 고생 많으셨습니다~

질문 주신 내용에 대해 답변과 제 생각을 적어보았어요.
2단계 미션을 진행하시면서 함께 고민해보시면 좋을 것 같아요 😄 

- https://github.com/woowacourse/java-racingcar/pull/467#discussion_r1103797336
- https://github.com/woowacourse/java-racingcar/pull/467#discussion_r1103800119

추가로 몇몇 수정사항이 적용되지 않은 것 같은데요, 다시 한번 체크해주시고 2단계에 마저 반영해주세요!
그럼 2단계에서 만나요~ 👋

2023-02-12 13:31 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +            return new RacingCars(createRacingCar(names));
`Names names` 변수가 catch 내부에서 사용되지 않는 것 같은데요,
그렇다면 try 내부로 집어넣어서 가독성을 더욱 확보할 수 있을 것 같아요.

2023-02-12 13:31 UTC, Hyeon9mak commented on src/main/java/controller/RacingGameController.java
> +            System.out.println(e.getMessage());
'에러를 보게되는 대상이 현재는 개발자가 아닌 사용자이므로 요것도 view 의 역할이 아닐까..' 라는 저의 소소한 생각입니다 😄

2023-02-12 13:31 UTC, Hyeon9mak commented on src/main/java/domain/TryCount.java
> +    }
`validateTryCount` 는 검증을 뜻하는 메서드로 보이는데, 내부에서는 그 이상의 역할을 수행하는 것 같네요. 명칭을 변경하거나 분리되면 더 좋을 것 같아요.

2023-02-12 13:31 UTC, Hyeon9mak commented on src/main/java/view/InputView.java
> +    }
그쵸. 쉼표를 기준으로 자르고 자시고 뭐하고 그런건 view 의 역할일뿐, `RacingCar`, `RacingCars`, `Name`, `Names` 는 자동차 경주에 정말 필요한 필수 로직들만 잘 수행하면 되죠.

2023-02-12 13:31 UTC, merged

2023-02-13 04:48 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +            return new RacingCars(createRacingCar(names));
commit 만하고 push 를 안했었네요...!
다음부터는 확인 잘 하겠습니다!

2023-02-13 07:03 UTC, Songusika commented on src/main/java/domain/TryCount.java
> +    }
`validateTryCount`에서 int 형으로 변환도하고, 검증도 거치고, 검증된 값을 반환도 하네요
해당 로직을 분리하도록 리팩터링하였습니다.

2023-02-13 07:10 UTC, Songusika commented on src/main/java/controller/RacingGameController.java
> +            System.out.println(e.getMessage());
Names 객체, TryCount 객체를 InputView에서 생성 후 익셉션 발생 시 사용자에게 재입력 받도록 리팩터링하였습니다.