[1단계 - 자동차 경주 구현] 헤나(박현서) 미션 제출합니다.
woowacourse/java-racingcar pull request #469
Opened 2023-02-09 06:34 UTC by hyena0608

안녕하세요 리뷰어님 😁
먼저 자동차 경주 구현 리뷰 감사드립니다 🙏

### 고려하며 구현한 점은 다음과 같습니다.

- 현재 설계가 요구사항이 적합한지 고민했습니다.
- 요구사항을 벗어나는 구현 했는지 고민했습니다.
- 클래스를 무리하게 분리 했는지 고민했습니다.

### 현재 PR 이후에 해보고 싶은 것은 다음과 같습니다.

아래와 같은 시도를 해보고 싶습니다.

분리를 하는 경우 변경에 대한 유연함이 증가하지만 현재 필요한 설계라고 느껴지지는 않았습니다.

때문에 현재 PR에 대한 코드는 요구사항에서 필요하다고 생각한 만큼만 구현하려고 노력했습니다.

- 자동차 데이터와 자동차 기능을 분리해서 구현해보고 싶습니다.
  - 오직 자동차 관련 데이터를 위한 클래스
  - 자동차 데이터를 조작하는 클래스
  - example) Cars의 데이터, 기능 분리
    - Cars가 우승자들을 찾는 기능을 분리하고 싶습니다.
    - Cars가 자동차들을 한번에 이동시키는 기능을 분리하고 싶습니다.

2023-02-09 16:36 UTC, sonypark requested changes
헤나 안녕하세요. 리뷰어 소니입니다! 만나서 반가워요 :) 
메서드 분리도 역할에 맞게 잘 해주시고 클래스별 역할 분담도 잘해주셔서 읽기 좋은 코드였습니다.👏
테스트도 꼼꼼히 잘 해주셨습니다!
PR에 고민했던 부분과 앞으로 시도할 부분에 대해 정리해주신것도 좋았어요!💯
시도할 부분에 대해서는 이미 적어주셔서 따로 코멘트 남기지는 않았습니다. 간단한 사항에 대해 코멘트 남겼으니 확인 부탁드려요~

2023-02-09 16:36 UTC, sonypark commented on README.md
> +- [x] 자동차들의 현재 위치를 통해 우승자를 정하는 기능
요구사항 리스트업!!💯

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
현재 enum은 getter 역할만 있네요. 클래스 내 상수로 선언해서 사용하는것과 어떤 차이가 있을까요?

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +		validateNameLength(name);
검증로직 👍

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/CarMovement.java
> +	}
메서드 분리 💯
if문을 지나 마지막 리턴값은 어떤 경우에 발생하나요? 멈추거나 전진하는것 이외의 동작이 있나요?

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/CarMovement.java
> +	}
클래스 분리..!!👍👍

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/Car.java
> +	}
이 메서드는 어떻게 테스트 할 수 있을까요?

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/Cars.java
> +	}
혹시 같은 이름의 Car가 생성되면 안된다는 도메인 규칙이 있나요?

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/domain/GameManager.java
> +	}
역할별로 메서드를 분리하니 가독성이 좋네요~

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/dto/GameRoundRequest.java
> +
round에 대한 입력값을 int가 아닌 String으로 받으신 이유가 있을까요?

2023-02-09 16:36 UTC, sonypark commented on src/main/java/racingcar/view/OutputView.java
> +	}
이 부분은 과도한 메서드 분리 같습니다😅 System.out.print(message) 으로 써도 될 것 같아요.

2023-02-10 00:23 UTC, hyena0608 commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
- 클래스 내 상수 선언의 경우
  - 클래스 라인 수가 길어집니다.
  - 설정을 변경할 경우 해당 클래스에 직접 접근해야 합니다.

- 외부 주입의 경우
  - 기능과 설정을 분리하고 싶었습니다.
      - CarMovement는 이동을 판단 해주는 기능이고
      - CarMovementConfig는 이동 판단 기준 설정으로 나누고 싶었습니다.

즉, 저는 외부 값을 이용해서 이동을 판단하게 작성하고 싶었고
설정에 대한 패키지를 가지고 있음으로서 어떤 설정들이 들어가는지 한눈에 파악할 수 있었다고 생각합니다. 🙂

2023-02-10 00:34 UTC, hyena0608 commented on src/main/java/racingcar/domain/CarMovement.java
> +	}
20라인 return false의 경우 움직이지 않습니다.

정지에 대한 숫자가 아니고
전진에 대한 숫자가 아니라면

"정지해서 아무것도 하지 말아라" 라는 것을 생각했었습니다.

하지만 소니가 말씀하신 이유가 
return false의 경우 어떤 동작이 일어날지 명확하지 않고
만약 false로 return 됐을 때 자동차가 후진하게 된다면 요구사항에 부합하게 되는거라는 생각을 할 수 있었습니다. ✌️

때문에 범위에 부합한 number가 들어왔을 경우는 애플리케이션 내 오류라고 판단하는게 맞다는 의견을 내고 싶습니다.

다음과 같이 코드를 변경하겠습니다. 😁
```suggestion

	public boolean isMoveForward() {
		int number = numberGenerator.generateNumber();
		if (isStop(number)) {
			return false;
		}
		if (isForward(number)) {
			return true;
		}
		throw new IllegalStateException(CAR_MOVEMENT_NUMBER_EXCEPTION.getMessage());
	}
```

2023-02-10 00:43 UTC, hyena0608 commented on src/main/java/racingcar/domain/Cars.java
> +	}
소니... 없습니다 !! 😅 ㅎㅎ 
다만 추가적으로 필요한 부분이라고 생각했습니다. 🫣

마치 크루의 닉네임이 겹치지 않도록 하는 것처럼
자동차 이름도 겹치게 된다면 혼란을 일으킬 수 있을 거라고 느꼈습니다. 🧐

때문에 요구사항을 추가적으로 넣어보았습니다.

개발자마다 기준이 다르겠지만
요구사항에 이름이 중복되면 안된다는 말도 없지만 중복을 허용한다는 말도 없었기에 애매한 부분이고
저같은 경우 필요하다면 팀원과 합의해서 조건을 추가하는 것을 선호하고 있습니다.

소니는 어떻게 생각하시나요 ? 😄

2023-02-10 00:56 UTC, hyena0608 commented on src/main/java/racingcar/dto/GameRoundRequest.java
> +
GameRoundRequest가 데이터를 가지고 있을 뿐만 아니라
String을 int형으로 변환시켜주는 역할까지하고 있어서 일어난 상황입니다.

페어 프로그래밍을 진행하면서 의견이 나누어진 부분으로
입력 값 변환은 inputView의 역할이라고 생각하고 있었지만
페어는 InputView는 입력을 받는 역할만하고 해당 값을 Request가 제대로 받았는지 받았다면 변환까지 하자는 의견이었습니다.

InputView는 입력을 받는다는 것은 맞는 말이고
Request에 들어온 값이 적합한 값인지 검증까지는 좋다고 생각하지만 

Request에서 변환에 대한 책임을 지는 것에 소니는 어떻게 생각하시는지 궁금합니다. 😃

2023-02-10 01:00 UTC, hyena0608 commented on src/main/java/racingcar/view/OutputView.java
> +	}
소니의 말이 맞습니다 ! 👍
저도 메서드를 분리하면서 과도하다는 느낌을 받았습니다. 🥲

하지만 제가 다음과 같이 print 메서드를 작성한 이유는
해당 메서드를 사용함으로서 어디서 출력 하고 있는지 IDE의 도움을 통해서 보다 편리하게 알 수 있었기 때문입니다.

소니는 이러한 부분에 대해서 어떻게 생각하시는지 궁금합니다 ! 😄

2023-02-10 14:20 UTC, sonypark commented on src/main/java/racingcar/domain/CarMovement.java
> +	}
현재 코드상 0~9 이외의 값이 들어올 수 있나요?

2023-02-10 14:20 UTC, sonypark commented on src/main/java/racingcar/domain/Cars.java
> +	}
아 그렇군요! 규칙을 추가하신건 좋고 전혀 문제없습니다 :)
도메인규칙으로 넣으신거라면 이러한 규칙을 Car의 equals에 넣는게 적절할지는 고민이 필요할 것 같습니다.
Car객체의 동일성을 현재 name으로만 판단을 하는데, 동일성 규칙을 이동거리까지 같은 Car가 된다면 equals 메서드를 또다시 재정의 해줘야하겠네요

CarName과 같은 새로운 도메인을 만들고 검증 로직을 할당하는 방법도 생각해보면 좋을 것 같아요!
`hint. 값객체`

2023-02-10 14:20 UTC, sonypark commented on src/main/java/racingcar/view/OutputView.java
> +	}
```
해당 메서드를 사용함으로서 어디서 출력 하고 있는지 IDE의 도움을 통해서 보다 편리하게 알 수 있었기 때문입니다.
``` 
위 말씀이 어떤건지 제대로 이해를 못했네요🥲 저 메서드를 출력하는 클래스?메서드?의 위치를 알 수 있다는 의미일까요?
이 메서드는 입/출력 클래스에서만 쓰이는데 출력 위치를 알아야할 필요성이나 그로인해 얻는 이점은 어떤게 있는지 더 자세히 말씀해주실 수 있나요?🙂

"이미 라이브러리에서 하나의 기능을 수행하도록 만들어놓은 메서드를 이름만 바꿔서 호출했을 때의 장점"은 저는 없다고 생각했어요~ 헤나가 생각한 장점이 무엇인지 궁금합니다!

2023-02-10 14:42 UTC, sonypark approved these changes
헤나 안녕하세요. 1단계는 여기서 마무리하고 2단계 진행하시죠!👍
질문에 대한 코멘트 남겼으니 한 번 체크 부탁해요~~

2023-02-10 14:42 UTC, sonypark commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
- 클래스 라인 수가 길어집니다. -> enum을 사용하는게 코드 라인수가 더 길어지는 것 아닐까요..ㅎㅎㅎ?😲
- 설정을 변경할 경우 해당 클래스에 직접 접근해야 합니다. -> 해당 클래스라면 어떤 클래스를 생각하셨나요? Car일까요? RandomNumberGenerator일까요? 해당 클래스에 직접 접근하면 안되는 이유가 있을까요?
- 설정을 분리했을 때의 장점도 분명 있습니다. 그런데 너무 분리하다보면 오히려 코드 응집성이 깨지고 가독성도 낮아지게 될 위험도 있습니다. 현재 구현하는 프로그램이 설정을 분리할 만큼의 구조일지도 고민해보세요~
- 기능을 생각하고 최대한 분리하며 외부에서 주입하려는 고민 자체는 매우 좋습니다. 단, 모든 설계나 기술이 그렇듯 필요한만큼만 적절히 사용하는것도 중요한 것 같습니다. 모래로 두꺼비집을 만드는데 포크레인을 가져올 필요는 없으니까요 :) 이건 단순히 위와 같이 설정 클래스로 분리한 것에 대한 피드백은 아니고 앞으로 진행하는 미션 모두에 해당되는 것이니 참고만 해주세요! 헤나가 고민한 부분은 충분히 이해되고 좋은 시도였다고 생각합니다. 앞으로도 헤나의 생각을 코드에 적극적으로 반영해주세요~💯

2023-02-10 14:42 UTC, sonypark commented on src/main/java/racingcar/dto/GameRoundRequest.java
> +
Request에서 변환에 대한 책임을 DTO까지 가져와야 하는지는 의문입니다.🤔
어플리케이션에서 받고자 하는 값의 타입이 있고 그 타입이 오지 않으면 타입 캐스팅 에러가 발생하는게 자연스럽다고 생각합니다.
DTO는 단순 데이터 전달 역할만 하는게 목적에 부합한다는 생각이 드네요.🙂
DTO에 대해 공부해보고 헤나의 생각도 공유해주세요~

2023-02-10 14:46 UTC, merged

2023-02-10 14:57 UTC, sonypark commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
추가로 enum의 경우는 getter 이외에 다양한 기능을 활용할 수 있는데 여기서는 enum이 아니라 상수를 담는 클래스로 사용해도 무방할것 같아요. enum에 대해 공부해보고 헤나 의견도 공유해주세요 :)

2023-02-11 04:49 UTC, hyena0608 commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
- 클래스 라인 수
  - 자동차 움직인 판단 값을 CarMovement 클래스 내에서 상수로 선언하여 사용할 경우 CarMovement 클래스의 라인 수가 증가하는 것을 생각했습니다.
  - 또한 움직임을 판단하는 것 자체에 대한 기능을 다른 곳에서 처리하게 리팩터링할 수 있다고 생각했습니다.
  - 때문에 해당 상수들을 외부에서 가져다 쓰는 방식을 이용해봤습니다.
- 자동차 움직임 판단 값 (설정 변경 시 해당 클래스 직접 접근)
  - CarMovement 클래스 내에서 움직임 판단 값을 가질 시에 
  - CarMovement를 테스트할 때 자동차 움직임 판단 값을 알 수 없어서 어떤 값을 리턴하게 될 지 모르는 상태였습니다. 
```java
public class CarMovement {
  private static final int STOP_MIN_NUMBER = 0;
  private static final int STOP_MAX_NUMBER = 3;
  private static final int MOVE_FORWARD_MIN_NUMBER = 4;
  private static final int MOVE_FORWARD_MAX_NUMBER = 9;

  // ...
}
```
```java
@DisplayName("자동차 움직임 성공 및 실패 테스트")
@Test
void isRandomCarMoveTest() {
  final int number = 1; /* 성공 값인지 실패 값인지 알 수 업다 */
  carMovement = new CarMovement(() -> number);

  boolean isCarMoved = carMovement.move();

  // assertThat(isCarMoved).isTrue();
  // assertThat(isCarMoved).isFalse();
}
```
  - 때문에 테스트를 더 정확하게 할 수 있는 장점까지 있다고 판단하여 CarMovementConfig를 만들었습니다.
```java
public enum CarMovementConfig {
  STOP_MIN_NUMBER(0),
  STOP_MAX_NUMBER(3),
  MOVE_FORWARD_MIN_NUMBER(4),
  MOVE_FORWARD_MAX_NUMBER(9);

  // ...
}
```
```java
@DisplayName("자동차 움직임 성공 및 실패 테스트")
@Test
void isRandomCarMoveTest() {
  carMovement = new CarMovement(() -> MOVE_FORWARD_MIN_NUMBER.getNumber());

  boolean isCarMoved = carMovement.move();

  assertThat(isCarMoved).isTrue();
}
```

  - 특정한 정수 값을 넣었을 때 움직임을 판단하는 책임을 CarMovementConfig가 가지게 되었을 때 Enum일 때 더 간결한 코드가 될 거라 생각합니다.


  - enum을 단순히 상수를 더 간단하게 사용하기 위한 목적이 아니라 움직임까지 판별하는 책임을 갖는다면 클래스 명을 Movement로 바꾸면서 아래와 같이 더 활용할 수 있습니다.
 ```java
public enum Movement {
	MOVE_STOP(0, number -> 0 <= number && number <= 3),
	MOVE_FORWARD(1, number -> 4 <= number && number <= 9);

	private final int moveCount;
	private final IntPredicate rangeTrue;
	
	Movement(int moveCount, IntPredicate rangeTrue) {
		this.moveCount = moveCount;
		this.rangeTrue = rangeTrue;
	}
	
	public static Movement from(int number) {
		return Arrays.stream(Movement.values())
			.filter(movement -> movement.rangeTrue.test(number))
			.findAny()
			.orElseThrow(() -> new IllegalArgumentException());
	}
	
	public int getMoveCount() {
		return this.moveCount;
	}
}
```

2023-02-11 05:12 UTC, hyena0608 commented on src/main/java/racingcar/domain/CarMovement.java
> +	}
현재 코드상에서 0-9 이외의 값이 들어올 수 없습니다.
랜덤으로 나올 수 있는 범위를 0-9로 지정해놨기 때문입니다.

하지만 랜덤의 범위가 0-10으로 바뀌는 순간 애플리케이션이 오작동 할 수 있다고 판단하여
이외의 값이 들어올 경우에 예외를 던져서 인지 하려고 했습니다.
현재 요구사항은 정지, 전진 두 가지 이동 방법밖에 없기 때문에 아래 코드와 같이 전진이 아니면 return false로 정지만 시켜도 될 거 같습니다.
```java
public boolean isMoveForward() {
   if (isForward(number) {
    return true;
  }
  return false;
}
```

하지만 저는 만약에 이동 방식이 "정지", "전진"이 아닌 "후진", "전진" 이었다면
기존 코드에서 마지막에 return false 할 경우에는 후진하여 오작동 할 수 있습니다.
```java
public boolean isMoveForward() {
  int number = numberGenerator.generateNumber();
  if (isStop(number)) {
    return false;
  }
  if (isForward(number)) {
    return true;
  }
  return false;
}
```

그러한 요구상이 바뀌었을 때 테스트 코드에서 실패하여 고칠 수 있겠지만
모든 if 조건에 부합 했을 경우는 없어야 한다는 정보를 주고 싶었습니다.
때문에 아래와 같은 코드로 변경하게 되었습니다.
```java
public boolean isMoveForward() {
  int number = numberGenerator.generateNumber();
  if (isStop(number)) {
    return false;
  }
  if (isForward(number)) {
    return true;
  }
  throw new IllegalStateException(CAR_MOVEMENT_NUMBER_EXCEPTION.getMessage());
}
```

2023-02-11 06:00 UTC, hyena0608 commented on src/main/java/racingcar/domain/Cars.java
> +	}
단순하게 처음에 자동차를 등록할 때만 검증하자라는 생각에 구현하고
이후에 리팩터링을 진행하면서 Car 객체의 equals의 재정의가 이동 거리 때문에 이후에 
이름이 같더라도 서로 같지 않게 판단하게 되는 단점을 알 수 있었습니다.

소니의 말씀으로 현재 equals의 재정의 목적이 이후에 오작동이 될 수 있는 부분은 확실히 위험한 부분이라고 생각됐습니다.
단순히 이후에 변경해도 된다는 생각으로 수정하지 않았는데 
아무런 표시도 없었고 테스트 코드에서나 혹은 애플리케이션 동작 중에 
"이전에 이런 구현을 했었는데 고치지 않아서 장애가 났구나 !!" 라고 후회할 상황을 만들었습니다. 😱

소니가 말씀해주신 값 객체를 이용하기 위해 CarName 같은 새로운 도메인을 만들고 내부에 isSameName같은 메서드를 만들어 서로 비교할 수 있는 방법도 사용해보도록 하겠습니다 !! 😁

2023-02-11 06:31 UTC, hyena0608 commented on src/main/java/racingcar/dto/GameRoundRequest.java
> +
dto는 도메인을 보호하기 위해서 사용하는 것으로 알고 있습니다.
getter, setter가 있을 수 있고
비즈니스 로직을 들어가지 않는 데이터 전달 역할이라고 생각했습니다. 🤔

**DTO가 단순히 데이터 전달 역할만 하는게 목적에 부합하다는 말을 아직 이해하지 못했습니다** ☹️

Request 객체 내 변환 기능에 대해서는
페어 프로그래밍을 진행하면서 여러 의견을 들어보았고
InputView는 입력만을 담당하고
Request 객체는 입력을 받아서 원하는 값을 던져주자 라는 의견이 나왔었습니다.

역할을 분리할 때 단순히 "입력"이라는 부분만을 나누고 모든 입력을 String에서 Request 객체에게 넘겨주는 방식이었고
어떠한 값으로 변환시켜주는 Parsing 기능을 InputView 혹은 변환에 대한 책임을 가질 클래스로 따로 분리하지 않고 
Request에 뭉쳐놓고 싶은거라고 생각했습니다.

만약 콘솔 애플리케이션에서 같은 기능을 여러 입력 형태로 받을 수 있다면 해당 Request에 변환 기능이 있는 것도 여러 버전 별로 재밌게 사용할 수 있을거 같기도 합니다.
물론 변환과 Request 객체에서 분리 되어있다면 변환 기능만 수정하면 되지만 현재 같은 경우는 Request 객체를 여러 개  만들어야 되는 단점이 크다고 생각하기 때문에 Request 객체는 단순히 데이터를 가지고 있는게 좋다고 느낍니다.

2023-02-11 06:43 UTC, hyena0608 commented on src/main/java/racingcar/view/OutputView.java
> +	}
이런 식으로 한 번에 볼 수 있는게 편리하다고 느꼈습니다.

- 출력문의 개수를 알 수 있습니다.
- 어떤 출력을 하고 있는지 알 수 있습니다. (print 메서드의 인자로 들어간 변수의 명을 통해서)
- 코드 간결성 (길이가 줄어들어서 개인적으로 느낀거 같습니다.)

<img width="740" alt="image" src="https://user-images.githubusercontent.com/82203978/218244332-b946fee9-92e8-41c4-9172-f30c8a752169.png">

하지만 출력 메서드의 네이밍만으로도 충분히 의미를 알 수 있고
출력을 몇 번하고 있는지를 알고 활용할 수 있는 상황이 없는거 같습니다.

출력할 때 일정한 메시지 포맷이 있다면 메서드로 따로 빼는 것이 중복을 줄인다고 할 수 있겠지만
소니 말씀처럼 현재 똑같은 기능을 메서드 이름만 바꿔서 호출하는 것은 메서드 한 번 호출 할 것을 두 번 호출하게 되는 상황으로 만들었네요 ! 😂

헤헤 생각하니까 재밌네요 ㅎㅎㅎ 피드백 감사합니다 소니 ! 👍👍👍👍👍👍👍👍👍👍

2023-02-11 06:47 UTC, hyena0608 commented on src/main/java/racingcar/domain/Car.java
> +	}
댓글 버튼을 잘못 눌렀나 봅니다 !! 🥲

boolean 타입을 반환할 수 있도록 메서드를 수정했습니다.
자동차가 움직이는가 아닌가의 결과를 판단할 수 있게 됐습니다.

```java
public boolean move() {
  final boolean isMoved = carMovement.isMove();
  if (isMoved) {
    position++;
  }
  return isMoved;
}
```

```java
@DisplayName("자동차 이동 성공 테스트")
@Test
void moveSuccessTest() {
  carMovement = new CarMovement(MOVE_FORWARD_MIN_NUMBER::getNumber);
  Car car = new Car(carMovement, "헤나");

  boolean isCarMoved = car.move();

  assertThat(isCarMoved).isTrue();
}
```

2023-02-12 16:35 UTC, sonypark commented on src/main/java/racingcar/config/CarMovementConfig.java
> +	}
`java
public class CarMovement {
  public static final int STOP_MIN_NUMBER = 0;
  public static final int STOP_MAX_NUMBER = 3;
  public static final int MOVE_FORWARD_MIN_NUMBER = 4;
  public static final int MOVE_FORWARD_MAX_NUMBER = 9;

  // ...
}
`
1. 이렇게 접근제어자를 public으로 놓으면 테스트에서도 사용할 수 있지 않을까요?

2.  움직임까지 판별하는 책임까지 생각해서 enum으로 만드셨군요! 좋습니다👍 추가로 의견을 드리자면 enum이 아닌 interface를 만들어 움직임을 판별하는 로직을 구현할 수도 있을것 같은데, 이 부분도 같이 생각해보면 좋을 것 같네요.
`hint. 전략패턴`

2023-02-12 16:49 UTC, sonypark commented on src/main/java/racingcar/dto/GameRoundRequest.java
> +
DTO는 말 그대로 Data Transfer Object로 (일반적으로) 로직을 갖고 있지 않는 순수한 데이터 객체이며, getter/setter 메서드만을 갖습니다. DTO는 쉽게 변경되고 지워지고 대체되기 때문에 그 안에 도메인 규칙에 영향을 받는 로직(서비스 로직, 검증 로직 등)이 들어있으면 유지보수에 큰 비용이 들 수 있다고 생각합니다. 아래 영상도 한 번 참고해보세요.
- https://www.youtube.com/watch?v=EeJnNaiMy3U
- Clean Code 6장: 객체와 자료구조