[1단계 - 자동차 경주 구현]  루카(백경환) 미션 제출합니다.
woowacourse/java-racingcar pull request #474
Opened 2023-02-09 07:05 UTC by dooboocookie

안녕하세요. 
리뷰 요청 부탁드립니다.

제가 가장 궁금했던 점을 좀 정리해볼까 합니다.

## 1. 검증을 어디서 하는 것이 맞을까?
- 이번에 `Car`와 같은 모델을 생성할 때 여러 가지 검증사항이 있습니다.
- 그 검증을 `InputView`, `GameManager`, `Car 생성 시` 중에 어디서 검증 처리를 하면 좋을지에 대해서 팀원과 이야기를 많이 나눴습니다.
- 저의 경우 처음에는 모두 검증해야 한다는 의견이었으나, 콘솔에서 돌아가는 프로그램에서 굳이 여러번 검증을 할 필요가 있는지에 대한 의견이 있었고, 그렇다면 제일 중요한 부분인 `Car`에서 하는게 맞다고 의견이 모아졌습니다.
- 그렇다고 모두 모델에서 검증을 할 수가 없고 InputView에서 받아오는 `GameRoundRequest`라는 DTO에서 검증을 하게 되었습니다.
- 이런 부분에서 일관성이 없다라고 판단이 들었는데, 이 부분에 대한 조언을 주시면 감사하겠습니다.

## 2. RandomNumberGenerate의 위치에 대해서
- 랜덤 넘저 자체를 사용하는 것이 `Car`가 `move()`할 때여서 `RandomNumberGenerate`를  move로 이동할 때마다 매번 생성을 하였습니다.
- 처음에는 Car가 move() 할 때 외부에서 생성된 숫자(랜덤이든 아니든)를 파라미터로 넘겨받아 그 숫자를 통하여 이동해야 한다고 생각했습니다.
- 그렇다 보면 `RandomNumberGenerate`를 `Car`를 다루고 있는 `Cars`에서  `RandomNumberGenerate`를 갖게 되는데 그렇게 의존성이 생기는 것이 맞는지 확신이 들지 않습니다.
- RandomNumberGenerate를 Car 외부에 둔다면 어디쯤에서 객체를 생성하고 숫자를 생성해야할지 조언 주시면 감사하겠습니다.

---
긴 글 읽어주셔서 감사합니다.
고견 부탁드리겠습니다!!🙏

2023-02-09 14:05 UTC, giantim commented on README.md
> +- [x] 입력된 자동차 이름 더미를 ,(쉼표)로 분리하는 기능
예외 처리에 대한 고민을 꼼꼼하게 잘 해주셔서 기능 요구사항을 파악하는데 많은 도움이 됐습니다 👍

2023-02-09 15:22 UTC, giantim requested changes
루카 안녕하세요~ 라빈입니다.

우테코가 시작한지 이제 첫 주인데 벌써 엄청난 고민을 해주고 계시네요 👏
관련해서 저도 의견 남겨보았습니다! 지금 단계에서 이정도 고민을 하시는거 부터가 정말 훌륭합니다. 페어분들과 이야기 나누면서 생각을 정리해보는 정도도 좋을것 같아요! 미션 기간이 짧은거 같은데 무리하게 구조 개선을 하지 않아도 저는 좋다고 생각해요!!

궁금하신 부분은 언제든지 편하게 DM 주세요~

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/GameManager.java
> +			try {
요기 구문에 컨벤션이 안맞는거 같은데 IDE의 도움을 받아보면 어떨까요?

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/GameManager.java
> +				CarNamesRequest carNamesResponse = inputView.inputCarName();
객체의 이름을 보고 기대하는 것과 변수명을 보고 기대하는것에 차이가 있을거 같아요.
의미를 명확하게 나타낼 수 있도록 바꿔보면 어떨까요?

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/Car.java
> +	int position;
요기 친구들은 접근제어자를 누락하신거 같네요 😄

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/Car.java
> +		if (nameLength > 5) {
다른 에러메시지들이나 config 값에서 이름으로 의미를 잘 표현했던것처럼 5 라는 규칙에 대해서 의미를 갖는 이름을 정의해보면 어떨까요?

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/NumberGenerator.java
> +	int generateNumber();
인터페이스로 도출하신 이유가 궁금하네요! 설명 한번 부탁드리겠습니다 😉

2023-02-09 15:22 UTC, giantim commented on src/main/java/racingcar/domain/GameManager.java
> +	}
적어주신 두 가지 고민점에 대해서 같이 의견 나눠보면 좋을거 같아요!

먼저 첫번째로 게임 규칙에 대한 검증을 어디서 수행하면 좋을지에 대해 고민을 해주셨네요.
현재 구조를 살펴보면 ```도메인이 검증하기 vs 뷰가 검증하기```에 대해서 고민하신거 같아요. 그리고 지금 결정사항으로는 도메인이 그 책임을 가져가기로 결정하신거 같네요! 
우리가 검증이 필요한 부분은 게임 규칙과 같은 요구사항이죠? 제가 자동차 경주 게임에 대한 규칙을 만들때와 루카가 규칙을 만들때 서로 다르게 만들 수 있을것 같아요. 그럼 지금 정의한 도메인의 경우 여러 게임 규칙에 확장하기는 어렵고 수정사항을 그때그때 반영해줘야 하는 구조인거 같아요! 그리고 이렇게 된 이유는 검증에 대한 책임을 도메인이 갖고 있기 때문이지 않을까 싶습니다.
이 부분에 대해서 같이 설계를 진행한 페어분들과 이야기 나눠보면 어떨까요? 😄

두번째 고민 사항으로는 ```랜덤 숫자 생성기```의 위치에 대한 고민을 해주셨네요.
루카는 랜덤 숫자 생성기를 도메인으로 정의하셨고 CarMovment에서 사용하고 계시네요! 음... 도메인간의 의존성을 고민하다보니 랜덤 숫자 생성기의 위치가 애매한거 같다는 결론을 하신거 같아보이네요. 저는 루카의 고민을 보고 GameManager 클래스에 다른 역할을 주면 이 고민을 해결할 수 있지 않을까라고 생각이 들었어요.
GameManager를 보면 뷰에 관한 클래스와 도메인에 관한 클래스들을 멤버로 가지고 있네요? 그럼 첫번째 고민에 대해 드린 리뷰에도 해당하는 클래스인거 같아요. 그럼 GameManager를 뷰와 도메인을 묶어주는 별개의 계층으로 생각해보면 어떨까요? 누군가는 뷰와 도메인을 조합해봐도 좋을거 같아요 🤔 그럼 자연스럽게 랜덤 숫자 생성기의 위치도 결정해볼 수 있지 않을까요?

루카의 고민에 대한 내용을 GameManager가 모두 갖고있는거 같아서 여기에 제 생각을 적어보았습니다!! 궁금하거나 의견 나눠보고 싶은 내용이 있다면 언제든지 남겨주세요 😄

2023-02-09 15:22 UTC, giantim commented on README.md
> +|                                         [루카](https://github.com/dooboocookie)                                          |                                          [썬샷](https://github.com/Ohjintaek)
이 내용은 어디에 남길지 애매해서 여기에 남길께요 🤗
세 분이서 페어를 진행해 주셨군요! 처음에 PR을 보고 커밋 수가 58개여서 깜짝 놀랐습니다! 다음 페어활동에서는 조금 더 큰 기능 요구사항 단위로 묶어보면 어떨까요? 😉

2023-02-10 04:58 UTC, dooboocookie commented on src/main/java/racingcar/domain/NumberGenerator.java
> +	int generateNumber();
인터페이스로 나눈 이유는 숫자를 생성하는 기능이지금은 랜덤으로 생성하지만, 요구사항이 변하거나하면 랜덤이 아닌 숫자로도 발생시킬 경우가 있을 것 같았습니다.
따라서, 숫자를 생성하는 역할 자체를 인터페이스를 만들고, 랜덤한 숫자를 발생시키는 구현체를 만들었습니다.
그러다 보니 차 이동을 테스트 할 때 특정 숫자를 리턴하도록 오버라이딩 하여 테스트를 할 수 있었습니다!!

2023-02-10 05:24 UTC, dooboocookie commented on src/main/java/racingcar/domain/GameManager.java
> +	}
1. `게임 규칙`을 검증하는 애용이 도메인에 있어서 게임 규칙을 확장하기 어렵다면, 제 지금 생각에는 `GameRuleValidator`와 같이 게임 검증을 하는 인터페이스를 만들고 제가 생각한 규칙으로 위 인터페이스를 구현한 검증하는 클래스를 만들면 될 것 같습니다!!

2. `랜덤 숫자 생성기` 위치에 대한 고민을 여전히 헷가리는 부분이 많습니다. 
제 생각엔 `GameManager`를 뷰와 도메인을 이어주는 컨트롤러의 역할로 생각하면 `GameManager`는 뷰와 도메인간 값을 전달하고 다음 컨트롤러의 호출(?)의 역할을 수행하고 실제 게임에 대한 로직을 실행하는 서비스같은 계층이 추가로 필요할 것 같습니다. 그렇다면 서비스 계층에 `랜덤 숫자 생성기`가 있어야 될 것 같다는 게 지금까지 제 생각입니다!!

바쁘신 와중에 세심하게 리뷰 남겨주셔서 정말 감사합니다 ㅠㅠ🙇‍♂️
조언해주신 내용 토대로 수정 진행해보겠습니다!!

2023-02-10 05:25 UTC, dooboocookie commented on src/main/java/racingcar/domain/GameManager.java
> +				CarNamesRequest carNamesResponse = inputView.inputCarName();
CarNamesRequest 의  변수명을 좀더 명확하게 바꿔보도록 하겠습니다!!

2023-02-10 05:27 UTC, dooboocookie commented on src/main/java/racingcar/domain/GameManager.java
> +			try {
넵 수정하겠습니다!!

2023-02-10 05:27 UTC, dooboocookie commented on src/main/java/racingcar/domain/Car.java
> +	int position;
앗 그렇네요... 수정하겠습니다!!

2023-02-10 05:28 UTC, dooboocookie commented on src/main/java/racingcar/domain/Car.java
> +		if (nameLength > 5) {
5라는 숫자의 의미가 잘 나타나도록 이름을 정해보겠습니다

2023-02-10 09:33 UTC, dooboocookie commented on src/main/java/racingcar/domain/GameManager.java
> +	}
1단계에서는 아직 서비스 계층을 만들거나 그렇지는 못하였고, 
일단 조언 주신대로 검증하는 부분을 도메인에서 빼보고,
`랜덤 숫자 생성기` 를  `GameManager`에서 주입받아서 쓰도록 바꿔보았습니다!!

2023-02-10 14:03 UTC, giantim requested changes
루카 안녕하세요.
빠르게 피드백 반영해주셨네요. 몇 가지 의견 남겼습니다.
궁금하신 부분은 언제든지 질문 남기시거나 DM 주세요!

2023-02-10 14:03 UTC, giantim commented on src/main/java/racingcar/domain/Car.java
> +        carValidator.validateCarName(name);
Car와 GameRound의 차이점을 한번 생각해볼까요?
입력받은 자동차 이름에 대한 유효성 검사는 도메인인 Car가 책임을 그대로 갖고 있네요. 작성해주신 GameRound와 어떤 차이가 있나요? 구조적 일관성을 갖는게 좋아보입니다.

2023-02-10 14:03 UTC, giantim commented on src/main/java/racingcar/config/CarMovementConfig.java
>  public enum CarMovementConfig {
자동차의 이동을 판단하는 클래스는 CarMovement라고 정의해주셨는데요.
해당 규칙을 관리하는 설정 파일을 따로 작성해 주셨어요. 이렇게 작성했을 때 어떤 이점을 기대하셨을까요?

2023-02-10 14:03 UTC, giantim commented on src/main/java/racingcar/domain/Cars.java
> +        }
루카가 작성한 코드에서 반복문 내부에 조건문 / 예외 검사 등을 넣어주셨는데요.
이런 부분들을 메서드로 분리해보고 의미있는 이름을 지어보면 어떨까요?

2023-02-10 14:03 UTC, giantim commented on src/main/java/racingcar/dto/RoundResultResponse.java
> +    private final List<CarDTO> roundResult = new ArrayList<>();
DTO 내부에 DTO를 갖는 구조로 되어있네요.
이번 미션처럼 입력 / 출력 부분이 단순한 경우에 DTO가 꼭 필요할지 고민해봐도 좋을것 같아요. 특히 지금처럼 DTO 내부에 DTO를 갖는게 적합하고 이해하기 좋은 구조일까요? 다른 사람이 RoudResultResponse를 사용하려면 CarDTO 내부까지 들어가서 어떤 값을 포장해두었는지 확인해야할것 같아요. 그럼 우리가 어떤 경우에 값을 포장해서 사용하면 좋을지 고민해보고 의견 남겨주세요~

2023-02-10 14:03 UTC, giantim commented on src/main/java/racingcar/validator/CarValidator.java
> +public interface CarValidator {
오.... 인터페이스로까지 분리를 해주셨네요.
사실 기대했던 부분은 이런 단계가 아니었습니다 😂 규칙을 추상화해서 갖기 보다는 도메인과 뷰 중에 명확하게 책임을 분리하는 단계까지 기대를 했습니다.
Car 부분에 드린 리뷰처럼 일단은 구조적으로 일관되게 개선해보면 좋을거 같네요!

2023-02-11 13:49 UTC, dooboocookie commented on src/main/java/racingcar/domain/Car.java
> +        carValidator.validateCarName(name);
조언 해주신 내용을 제가 잘 이해를 못하고 고쳤던 것 같습니다!!
이제는 GameRound와 일관성 있게 입력 받은 내용을 DTO에 바인딩 할 때 유효성 검사를 하도록 수정하였습니다!!

감사합니다!!

2023-02-11 13:53 UTC, dooboocookie commented on src/main/java/racingcar/config/CarMovementConfig.java
>  public enum CarMovementConfig {
CarMovement를 만든 것은 Car의 움직임은 자동차 자체적인 판단이 아니라 숫자 생성기에서 숫자를 반환하면 그 숫자로 다른 누군가가 판단해서 차를 움직인다고 생각해서 분리를 하였습니다.

그 차 움직임에 대한 규칙을 관리하는 설정 파일을 따로 enum으로 뺀 이유는 처음에는 그 규칙에 해당되는 숫자들로 테스트에도 사용하고, CarMovement에도 사용해서 였습니다.

처음에는 CarMovent 클래스 내에 상수로 선언할까 생각이 들었지만, 저 규칙은 게임에서 매우 중요한 규칙이기 때문에 확장하다보면 다른 곳에서 쓰일 수 있을 것 같아 빼는 것이 낫다고 판단하였습니다.

2023-02-11 13:55 UTC, dooboocookie commented on src/main/java/racingcar/domain/Cars.java
> +        }
저 부분이 약간 깔끔하지 못한 로직이여서 메서드로 분리하기 좀 번거로웠는데요..
약간 방법을 수정하여 따로 메서드 분리하였습니다!!!

그 GameManager에서는 주석을 달았는데, 현재 구조에서는 catch문에서 재귀호출을 하는 것 말고는 while문 안에 if 문을 빼는 것이 좀 어려워서 일단은 그대로 두었습니다 😭

2023-02-11 13:59 UTC, dooboocookie commented on src/main/java/racingcar/dto/RoundResultResponse.java
> +    private final List<CarDTO> roundResult = new ArrayList<>();
코드 짤 때는 몰랐는데 DTO 내부에 DTO를 갖는게 이해하기 힘든 구조라는 것을 깨달았습니다..

일단 Car자체를 CarDTO로 넘겨준 이유는 `Car`라는 도메인에 해당되는 객체를 그대로 뷰까지 전달하는게 좀 위험하게 느껴져서 제가 페어들에게 강하게 주장했던 내용이었습니다..
(지금처럼 단순한 구조에서는 아니지만) Car 내부에는 공개되면 안되는 민감한 정보들이나 변경되면 안되는 정보들이 있을 태니 그 객체 자체를 반환하는 것은 위험하다는 생각이 들었습니다!!

현재는 DTO내부에 DTO를 감싸는 형식은 많이 과한 느낌이 들어서 Car의 정보를 갖고있는 DTO 를  List에 담아서 반환하는 형식으로 수정하였습니다!!

2023-02-11 14:01 UTC, dooboocookie commented on src/main/java/racingcar/validator/CarValidator.java
> +public interface CarValidator {
제가 잘 이해하지 못해 죄송합니다 ㅠㅠ
한번 더 짚어 주셔서, `차 이름`과 `게임 라운드` 입력 시 검증은 일관되게 DTO 에 바인딩 할 떄 검증하는 것으로 수정하였습니다.

하지만 여전히 DTO에서 넘어오는 값을 도메인이 믿어도 될까? 라는 의문이 약간은 남아있긴합니다 ㅠㅠ 이 부분은 다음 미션 때 조금 더 고민 해보도록 하겠습니다😢

2023-02-11 14:03 UTC, dooboocookie commented
바쁘신 와중에 또 이렇게 피드백 주셔서 감사합니다 🙇

첫번째 피드백 이후 미흡하게 수정했던 내용을 최대한 잘 수정해 보았습니다!!

2023-02-12 06:35 UTC, giantim commented on src/main/java/racingcar/config/CarMovementConfig.java
>  public enum CarMovementConfig {
게임에서 매우 중요한 규칙을 담당하는 클래스가 잘 정의되지 않아서 매우 중요한 규칙이 외부로 노출된거 같아요.
다음 단계에서는 캡슐화에 대해 더 고민해보면 좋을것 같습니다.

2023-02-12 06:35 UTC, giantim commented on src/main/java/racingcar/domain/Cars.java
> +        }
메서드가 반환값을 갖는 구조면 어떨까요?

2023-02-12 06:43 UTC, giantim approved these changes
루카 안녕하세요.
미션 수행하시느라 고생 많으셨습니다.
간단한 의견 남겨드렸고 다음 미션도 재밌게 잘 즐기시길 바랄께요 👏

2023-02-12 06:43 UTC, merged