콩하나 자동차 경주
woowacourse/java-racingcar pull request #477
Opened 2023-02-09 07:19 UTC by kong-hana01

2023-02-10 00:03 UTC, joseph415 requested changes
안녕하세요. 리뷰어 서브웨이입니다. 미션 구현 **너무** 잘해주셨네요! 💯
책임분리, 가독성이 좋아서 잘 읽혔어요~

간단한 코멘트 남겼습니다~

2023-02-10 00:03 UTC, joseph415 commented on src/main/java/domain/NumberGenerator.java
> +public interface NumberGenerator {
인터페이스 활용👍

2023-02-10 00:03 UTC, joseph415 commented on src/main/java/controller/RacingGameController.java
> +    public RacingGameController(NumberGenerator numberGenerator) {
컨트롤러가 NumberGenerator 를 상태로 갖고있는게 맞을까요?!
현재 Controller가 도메인인 NumberGenerator를 가지고 있는 형태여서 Controller외부에서 주입을 해주는 상황인데요.

컨트롤러가 해당 객체를 가지고 있는것보다 컨트롤러에서 RacingGame에 직접 주입해주는 방식이 어떤가요? 저는 도메인 모델은 외부로부터 보호받아야할 존재라고 생각해서, 노출되지 않는게 맞다고 생각합니다!

2023-02-10 00:03 UTC, joseph415 commented on src/main/java/domain/RacingGame.java
> +    private final static int MIN_MOVE_NUMBER = 4;
필수는 아니지만 다음과 같은 내용이 있어서 공유드려요~

https://stackoverflow.com/questions/11219556/difference-between-final-static-and-static-final

> For fields, the said production lists the modifiers in this order:
> @Annotation public protected private static final transient volatile

2023-02-10 00:03 UTC, joseph415 commented on src/main/java/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근제어자가 빠져있네요!

2023-02-10 00:13 UTC, joseph415 commented
Q1. 예외 사항을 점검하는 로직을 어느 부분에 추가하는 것이 좋을지 궁금합니다.

MVC 패턴을 잘 활용하셔서, 각 계층에 따른 책임 분리를 해주셨는데요. validate 도 그에 따른 책임분리가 되어야한다고 생각합니다.

view단은 외부와 밀접한 계층입니다. 외부에 대한 Input,output 에 대한 책임을 갖고 있는데요. 따라서 값에대한 검증도 외부에서 들어오는 값이 옳은가? 에 대한 검증이 이루어져야한다고 생각합니다. 예를들어, input으로 들어온 형식이 맞는지, name이 string 값이 맞는지..
하지만 domain은 비지니스 핵심로직이 담겨있는 계층이기 때문에 외부 값에대한 검증보단, 비지니스적으로 초점이 맞춰 검증이 들어가야한다고 생각해요! 예를들어, 도메인객체 생성 시점에 해당 값이 옳바른가?, carMove 하는데 -1이 올 수 있나?

답변이 됐을지 모르겠지만, 각 계층마다 검증책임이 다르기 때문에, 그에 맞게 검증이 들어가야한다고 생각합니다!

Q2. NumberGenerator 인터페이스의 패키지명을 어떻게 하면 좋을지 감이 오지 않습니다.

컨벤션에 따라 달라질 것 같은데요. 페어와 진행하면서 둘이 동의를 했다면, 그렇게 진행해도 무방하다고 생각합니다. 저는 numbergenerator, generator 정도 좋은 것 같네요!

2023-02-11 05:34 UTC, kong-hana01 commented
> Q1. 예외 사항을 점검하는 로직을 어느 부분에 추가하는 것이 좋을지 궁금합니다.
> 
> MVC 패턴을 잘 활용하셔서, 각 계층에 따른 책임 분리를 해주셨는데요. validate 도 그에 따른 책임분리가 되어야한다고 생각합니다.
> 
> view단은 외부와 밀접한 계층입니다. 외부에 대한 Input,output 에 대한 책임을 갖고 있는데요. 따라서 값에대한 검증도 외부에서 들어오는 값이 옳은가? 에 대한 검증이 이루어져야한다고 생각합니다. 예를들어, input으로 들어온 형식이 맞는지, name이 string 값이 맞는지.. 하지만 domain은 비지니스 핵심로직이 담겨있는 계층이기 때문에 외부 값에대한 검증보단, 비지니스적으로 초점이 맞춰 검증이 들어가야한다고 생각해요! 예를들어, 도메인객체 생성 시점에 해당 값이 옳바른가?, carMove 하는데 -1이 올 수 있나?
> 
> 답변이 됐을지 모르겠지만, 각 계층마다 검증책임이 다르기 때문에, 그에 맞게 검증이 들어가야한다고 생각합니다!
> 
> Q2. NumberGenerator 인터페이스의 패키지명을 어떻게 하면 좋을지 감이 오지 않습니다.
> 
> 컨벤션에 따라 달라질 것 같은데요. 페어와 진행하면서 둘이 동의를 했다면, 그렇게 진행해도 무방하다고 생각합니다. 저는 numbergenerator, generator 정도 좋은 것 같네요!

의견 감사합니다! 
페어와도 해당 부분으로 이야기를 했었을 때 도메인 객체 생성 시점에서 검증을 하는 것이 조금 더 좋을 것 같다고 이야기가 결론이 났습니다. 감사합니다!

2023-02-11 05:35 UTC, kong-hana01 commented on src/main/java/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
추가했습니다!

2023-02-11 05:35 UTC, kong-hana01 commented on src/main/java/domain/RacingGame.java
> +    private final static int MIN_MOVE_NUMBER = 4;
좋은 의견 감사합니다!
해당 부분은 크게 신경쓰지 않고 있었는데 앞으로 제출하기 전에 한번씩 점검해야할 것 같습니다 :)

2023-02-11 05:41 UTC, kong-hana01 commented on src/main/java/controller/RacingGameController.java
> +    public RacingGameController(NumberGenerator numberGenerator) {
피드백 주신 부분을 바탕으로 페어와 함께 이야기를 나눠봤는데 말씀해주신 대로 컨트롤러 외부에서 주입되는 코드를 수정하기로 의견을 모았습니다! 다만 추후에 NumberGenerator를 구현한 또 다른 클래스로 갈아 끼울 수 있는 가능성을 고려해 NumberGenerator는 변수로 정의를 했는데 해당 부분은 어떻게 생각하시나요?

2023-02-11 14:46 UTC, joseph415 commented on src/main/java/controller/RacingGameController.java
> +    public RacingGameController(NumberGenerator numberGenerator) {
넵! 이견 없습니다~ 제가 의견드린거는 아래와 같은 방식이여서 큰 차이 없는것 같아요!

```java
new RacingGame(cars, gameTrial, numberGenerator, new RandomNumberGenerator() );
```

2023-02-11 15:21 UTC, joseph415 approved these changes
리뷰 잘 반영해주셨는데요.💯

1단계는 마무리해도 될 것 같아서 merge 하겠습니다! 고생 하셨습니다!
1차 리뷰에서 [추가 코멘트](https://github.com/woowacourse/java-racingcar/pull/477#discussion_r1103646840) 확인부탁드려요!

아래 코멘트는 2단계에서 적용 부탁드립니다!

2023-02-11 15:21 UTC, joseph415 commented on src/main/java/view/OutputView.java
> +import domain.Car;
이 부분제가 놓치고 있었는데요.

View(클라이언트)에서 도메인을 직접 의존하고 있는 형태인데, 이부분 의존 끊어주도록 리팩토링을 해보는 것 어떤가요?
외부의 변경에 영향을 받을 수 있어서 도메인 객체가 외부로 나가는 형태는 지양해야합니다!

도메인모델이 외부로부터의 영향을 받지 않도록 해주세요!

2023-02-11 15:21 UTC, joseph415 commented on src/main/java/view/InputView.java
> +        Validator.validateCarName(carNames);
콩하나 도메인 생성시점으로 validator를 옮긴다고 했는데, 적용이 안된걸까요? 저는 생성자에서 생성 시점에 검증한다고 이해했습니다.

그렇게 되면 validator 패키지 위치도 알맞게 변경되야겠네요

2023-02-11 15:21 UTC, joseph415 commented on src/main/java/validation/Validator.java
> +        if (!Pattern.matches(DIGIT_REGEX, input)) {
Pattern.matches 내부로 들어가면
```java
public static boolean matches(String regex, CharSequence input) {
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(input);
        return m.matches();
    }
```
로 Pattern 객체를 리턴하는 형태인데요. Pattern 객체는 객체생성비용이 높아 캐싱해서 사용하는게 이점을 갖습니다.
[Effective Java 3/E 2장 Item 6 : 불필요한 객체 생성을 피하라](https://easthshin.tistory.com/7)

2023-02-11 15:38 UTC, joseph415 commented on src/main/java/controller/RacingGameController.java
> +    public RacingGameController(NumberGenerator numberGenerator) {
이 부분 추가적으로 더 의견을 남기자면, 컨트롤러 외부에서 주입해줄 수 있는 상황이 물론 컨트롤러 테스트를 더 용의하게 유연함을 가져다 주지만, NumberGenerator을 domain으로 간주했기 때문에 다음과 같은 의견을 드렸습니다!

제가 남기고자 했던 리뷰의도는 **영역의 분리를 확실하게 하고자** 다음과 같은 의견을 남겼습니다! 궁금한 사항이 있으면 DM주세요ㅎㅎ

2023-02-11 15:45 UTC, merged

2023-02-11 17:28 UTC, kong-hana01 commented on src/main/java/controller/RacingGameController.java
> +    public RacingGameController(NumberGenerator numberGenerator) {
네 ㅎㅎ
좋은 피드백 감사드립니다! :)

2023-02-11 17:33 UTC, kong-hana01 commented on src/main/java/view/OutputView.java
> +import domain.Car;
흠... 조금 고민이 되는 부분이네요!

요구사항을 만족하기 위해선 출력과 관련된 뷰에서는 어쩔 수 없이 도메인에 의존해야 할 것 같다는 생각이 드는데, 
혹시 좋은 아이디어가 있을까요?

일단 두 가지 방법 정도가 떠오르네요!
1. 출력 용 도메인을 만들어 도메인 객체가 직접적으로 외부에 노출되지 않도록 한다.
2. RacingGame에서 도메인 객체를 unmodified 형태로 리턴하고 이를 OutputView에 전달한다.

두 가지 방법 모두 장단점이 있을 것이라 생각이 들긴 하는데,
한번 고민해보도록 하겠습니다!

2023-02-11 17:42 UTC, kong-hana01 commented on src/main/java/view/InputView.java
> +        Validator.validateCarName(carNames);
네! 맞습니다!!

해당 부분은 1단계에 반영하면 될지, 2단계에 반영하면 될지 고민하다가 2단계에 반영해야겠다고 생각해서 코드만 수정하고 push를 하지 않았습니다...!

생각해보니 해당 내용까지 반영해서 같이 요청을 보내면 더 좋았을 것 같네요 ㅎㅎ...


해당 부분에서 고민이 됐던 부분은 validator의 역할을 도메인별로 분할해서 클래스를 생성하고자 하는데, 
이를 어떤 방식으로 생성할 지가 고민이었습니다. 

각 validator는 도메인에만 한정해서 처리할 예정이기 때문에 이를 각 도메인의 내부 클래스로 구현해도 괜찮을 지,
아니면 따로 클래스로 만들어서 사용하는 것이 좋을지 의견을 한번 여쭙고 싶습니다!

2023-02-11 17:44 UTC, kong-hana01 commented on src/main/java/validation/Validator.java
> +        if (!Pattern.matches(DIGIT_REGEX, input)) {
감사합니다! 
참고해서 리팩토링하도록 하겠습니다 :)

2023-02-13 08:15 UTC, joseph415 commented on src/main/java/view/OutputView.java
> +import domain.Car;
2가지 대안을 잘 생각해주셨네요!ㅎㅎ
사실 나중에 현업에서 작업을 할 경우에는 1번의 형태로 많이 사용하는데요!(외부로 나갈 출력용 객체를 만들어서 사용)
콩하나가 괜찮다고 생각되는 방식으로 작업해주시면 될 것 같습니다!
(이미 리뷰요청주셨네요 ㅎㅎ 참고해서 리뷰하겠습니다!,,)

2023-02-13 08:22 UTC, joseph415 commented on src/main/java/view/InputView.java
> +        Validator.validateCarName(carNames);
저는 개인적으로 검증책임만을 갖는 Validator를 따로 빼는것을 선호합니다! (car.validator.CarValidator.java)
만약 Car 내부에 Validator를 두어 선언한다면, Car 객체가 Validator까지 관리해야하는 책임도 생성된다고 생각해서 따로 빼어 관리하는것이 더 낫지 않을까 합니다!

2023-02-13 08:30 UTC, kong-hana01 commented on src/main/java/view/OutputView.java
> +import domain.Car;
네 ㅎㅎ 감사합니다!