[1단계 - 자동차 경주 구현] 쥬니(전정준) 미션 제출합니다.
woowacourse/java-racingcar pull request #480
Opened 2023-02-09 07:28 UTC by cpot5620

안녕하세요. 우테코 5기 쥬니입니다.
아직 많이 부족하지만, 잘 부탁드립니다.

이번 미션을 진행하면서, 페어와 함께 고민한 부분은 다음과 같습니다.

1. 원시값과 문자열을 모두 포장해야하는가?
    - 저희는 `TryCount`로 사용자로부터 입력 받은 반복 횟수를 포장하였습니다.
    - 하지만, 별다른 로직 없이 사용되는 클래스인데, 이를 컨벤션을 따라서 포장하는 것이 맞는지 고민이 되었습니다.
    
2. `InputView/OutputView`의 출력 책임
    - 저희는 사용자로부터 입력 받기 위해 메시지를 출력하는 행위를 `InputView`의 책임이라 생각했습니다.
    - 한편으로는, 출력하는 행위 자체를 `OutputView`에서 모두 관리해야 하는지 궁금했습니다.
    - 사용자로부터 입력 받는 과정에서 콘솔에 출력해야 하는 메시지를 `InputView`에서 관리해야 하는지
    - 아니면 출력의 책임으로 보고 콘솔에 출력되는 부분을 모두 `OutputView`에서 관리해야 하는지 궁금합니다.

2023-02-09 17:34 UTC, bimppap requested changes
반가워요 쥬니! 자동차 경주 구현 미션에서 함께하게 된 춘식입니다. 잘 부탁드려요! 👍 

깔끔하게 코드를 짜서 읽기 편했어요. 고생 많았습니다.
질문에 대한 답과 코멘트들 짧게 남겨봤어요. 확인 부탁드립니다. 🙂

궁금하거나 이해가 안 되는 부분은 편히 디엠 주세요. 😉

2023-02-09 17:34 UTC, bimppap commented on src/main/java/error/ErrorMessage.java
> +    INVALID_COUNT("시도 횟수는 1회 이상이여야 합니다."),
나중에 이름은 7글자 이하가 되야한다던가, 시도 횟수가 5회 이상이어야 한다고 요구사항이 바뀌면 어떻게 해야할까요?

2023-02-09 17:34 UTC, bimppap commented on src/test/java/domain/NameTest.java
> +    @DisplayName("자동차 이름은 1자 이상, 5자 이하여야 한다.")
ParameterizedTest를 적용하면 좋을 것 같아요!

2023-02-09 17:34 UTC, bimppap commented on src/test/java/domain/NameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
테스트는 성공케이스와 실패케이스를 분리하여 짜는 게 가독성이 좋습니다만, 굳이 한 메소드로 하고 싶다면 CsvSource를 고려한 ParameterizedTest를 적용해도 좋습니다. 정답은 없으니 원하시는 쪽으로 리팩토링해보아요 🙂

2023-02-09 17:34 UTC, bimppap commented on src/main/java/utils/RandomGenerator.java
> +@FunctionalInterface
FunctionalInterface를 사용한 이유가 있나요?

2023-02-09 17:34 UTC, bimppap commented on src/test/java/uilts/RandomUtilTest.java
> +    }
범위를 다루는 테스트를 할 경우, 경계값(여기서는 3과 4입니다)을 확인하는 테스트를 넣는 것이 좋습니다.
하지만 여기서 쓰이는 RandomGenerator는 무조건적으로 숫자를 랜덤 생성하고 있는데요, 하드코딩하지 않고 테스트하는 방법이 없을까요?

2023-02-09 17:34 UTC, bimppap commented on src/main/java/domain/Cars.java
> +    private final List<Car> cars;
일급컬렉션 👍

2023-02-09 17:34 UTC, bimppap commented on src/main/java/domain/Cars.java
> +    private final List<Car> cars;
Iterable를 꼭 implements 해야할 이유가 있나요?

2023-02-09 17:34 UTC, bimppap commented on src/main/java/controller/RacingGameManager.java
> +    public List<Name> readCarNames() {
private 메소드여도 무방하지 않을까요? ㅎㅎ

2023-02-09 17:34 UTC, bimppap commented on src/main/java/domain/Name.java
> +        if (name.isBlank() || name.length() > 5) {
숫자를 직접 넣는 건 하드코딩이므로 상수화해주세요!

2023-02-09 17:34 UTC, bimppap commented on src/main/java/domain/TryCount.java
> +public class TryCount {
> 원시값과 문자열을 모두 포장해야하는가?

꼭 전부 포장해야할 필요는 없습니다만 확장성이 고려되는 객체라면 포장을 하는 게 추후 유지보수에 좋습니다. 
TryCount의 경우 별다른 로직이 없이 사용되는 클래스라고 했는데, 코드를 보니 TryCount에 들어가는 데이터의 경우 InputView에서 검증을 거치고 있더군요. InputView와 TryCount 중 입력 데이터를 검증하는 책임을 가져야 하는 건 어느쪽인가 고민을 해봐도 좋을 것 같습니다.

이건 쥬니의 생각에 따라 답이 달라지는 부분이므로 꼭 반영할 필요는 없습니다. 😉

2023-02-09 17:34 UTC, bimppap commented on src/main/java/view/InputView.java
> +public class InputView {
> InputView/OutputView의 출력 책임

쥬니가 InputView와 OutputView의 정의를 어떻게 내리느냐에 따라 달렸습니다.

저의 경우 View에 중점에 두어 일종의 화면과 같은 역할이라 생각해서요. 입력화면과 출력화면에 각각 필요한 것을 모아놓는 쪽으로 생각했습니다. 하지만 Input과 Output에 중점을 두어 입력은 오직 입력만, 출력은 오직 출력만 하게끔 쓰는 구조도 많이 보았습니다.

상황에 따라 중점을 다르게 둬야할 케이스도 있으니 참고만 하면 좋을 것 같습니다ㅎㅎ

2023-02-09 17:34 UTC, bimppap commented on src/main/java/view/OutputView.java
> +        }
StringJoiner를 사용하셨군요ㅎㅎ
cars의 이름만 모아 String.join을 하거나 스트림+Collectors.joining을 사용해봐도 좋습니다.
이건 여담이니 반영하지 않아도 됩니다ㅋㅋ

2023-02-09 17:34 UTC, bimppap commented on src/main/java/controller/RacingGameManager.java
> +public class RacingGameManager {
MVC 패턴을 잘 녹여냈군요 굿굿

2023-02-10 04:47 UTC, cpot5620 commented on src/main/java/error/ErrorMessage.java
> +    INVALID_COUNT("시도 횟수는 1회 이상이여야 합니다."),
```suggestion
    INVALID_NAME_LENGTH("이름은 " + Name.MAX_NAME_LENGTH + "글자 이하여야 합니다."),
    INVALID_COUNT("시도 횟수는 " + TryCount.MIN_COUNT + "회 이상이여야 합니다."),
```
이름의 길이와 시도 횟수의 검증을 확인하는 각 클래스 내부에 선언된 상수를 public으로 수정하였습니다.
요구 사항이 변경될 경우 해당 검증을 수행하는 클래스 내부의 상수 값을 변경해주면 유지 보수에 용이할 것 같습니다.

2023-02-10 05:12 UTC, cpot5620 commented on src/test/java/domain/NameTest.java
> +    @DisplayName("자동차 이름은 1자 이상, 5자 이하여야 한다.")
```suggestion
    @DisplayName("1자 이상, 5자 이하로 생성할 수 있다.")
    @ParameterizedTest
    @ValueSource(strings = {"쥬", "쥬니", "쥬니헙크1"})
    void test1(String name) {
        assertDoesNotThrow(() -> new Name(name));
    }
```
다른 Test 코드에서도 위와 같이 @ParameterizedTest를 사용하였습니다.

2023-02-10 05:14 UTC, cpot5620 commented on src/test/java/domain/NameTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
```suggestion
    @DisplayName("1자 이상, 5자 이하로 생성할 수 있다.")
    @ParameterizedTest
    @ValueSource(strings = {"쥬", "쥬니", "쥬니헙크1"})
    void test1(String name) {
        assertDoesNotThrow(() -> new Name(name));
    }

    @DisplayName("1자 이상, 5자 이하가 아닌 경우, 생성할 수 없다.")
    @ParameterizedTest
    @ValueSource(strings = {"", "123456"})
    void test2(String name) {
        assertThatThrownBy(() -> new Name(name))
                .isInstanceOf(IllegalArgumentException.class);
    }
```
조언해주신 것처럼, 가독성을 위해 성공 테스트와 실패 테스트를 분리하였습니다.

2023-02-10 05:25 UTC, cpot5620 commented on src/main/java/domain/Name.java
> +        if (name.isBlank() || name.length() > 5) {
미션 수행 당시에 인지하지 못했던 것 같습니다. 
수정하여 반영하였습니다. 감사합니다 !

2023-02-10 05:32 UTC, cpot5620 commented on src/main/java/domain/TryCount.java
> +public class TryCount {
InputView에서는 사용자의 입력이 숫자인지를 검증하였고, TryCount에서 데이터의 범위에 대한 검증을 수행하였습니다.
질문 당시, TryCount에 별 다른 로직이 존재하지 않는다고 말씀드렸었는데 제가 착각했던 것 같습니다.
원시 데이터를 반드시 포장할 필요는 없으나, 해당 데이터와 관련된 기능이 추가될 가능성에 대해 고민해보아야 한다는 점을 염두에 두어야 겠네요. 조언 감사합니다 !!

2023-02-10 05:43 UTC, cpot5620 commented on src/main/java/view/InputView.java
> +public class InputView {
항상 View를 구현할 때, 고민 했던 부분이였는데 정답이 정해져 있는 영역이 아니라고 말씀해주시니 마음이 놓입니다.
(그동안 이 방식이 맞는건지에 대한 고뇌에 시달렸었습니다:cry::cry: )

2023-02-10 07:44 UTC, cpot5620 commented on src/main/java/domain/Cars.java
> +    private final List<Car> cars;
public static void printAllCars(Cars cars) {
        for (Car car : cars) {
            printCurrentState(car);
        }
    }

위 처럼, `Cars` 클래스 외부에서 컬렉션 내부 원소에 접근하기 위해 사용했습니다.

2023-02-10 08:26 UTC, cpot5620 commented on src/main/java/utils/RandomGenerator.java
> +@FunctionalInterface
랜덤 값에 대한 테스트를 수행하기 위해 함수형 인터페이스를 정의하였습니다.
이에 따라, 컴파일 과정에서 해당 인터페이스 내부에 하나의 추상 메서드만이 존재하는지 확인하기 위해 해당 어노테이션을 작성했던 것 같습니다.

(리팩토링 과정에서 해당 인터페이스를 삭제한 상태입니다.)

2023-02-10 08:29 UTC, cpot5620 commented on src/main/java/view/OutputView.java
> +        }
```java
    List<Name> carNames = new ArrayList<>();

    for (Car car : cars) {
        carNames.add(car.getName());
    }

    System.out.println(String.format(WINNER_MSG, String.join(SEPARATOR, carNames.toString())));
```
위와 같이, cars의 이름을 모아 `String.join()`을 사용하는 경우 `carNames.toString()` 에서 carNames 컬렉션 내부에 있는 `Name.toString()`까지 호출되지 않아서 출력시 대괄호(`[]`)가 함께 출력되어 적용해보지 못했습니다.
혹시 해당 대괄호를 출력하지 않기 위해, `carNames`를 `List<Name>`이 아닌 `List<String>`으로 바꾸는 방법외에 다른 방법이 존재하는지 궁금합니다.

2023-02-10 08:34 UTC, cpot5620 commented on src/test/java/uilts/RandomUtilTest.java
> +    }
```java
    @BeforeEach
    public void setup(){
        car = new Car(new Name("쥬니"));
    }

    @DisplayName("4 이상일 경우 전진한다.")
    @Test
    public void test1() {
        car.tryMove(4);

        Position position = new Position();
        position.move();

        Assertions.assertThat(car.getPosition())
                        .isEqualTo(position);
    }
```
기존 RandomGenerator의 역할을 단순히 랜덤 값을 생성하도록 수정하였습니다.
이에 따라, `Car 객체` 외부에서 랜덤 값을 생성해주었고, 이를 `tryMove()` 메서드의 인자로 전달하여 이동 여부를 결정하도록 로직을 수정하였습니다.

2023-02-10 08:44 UTC, cpot5620 commented
안녕하세요 춘식님 ! 좋은 리뷰 감사드립니다 😃 
코멘트 해주신 부분에 반영한 내용과 추가적으로 궁금한 사항을 작성했습니다.
리뷰 해주신 내용을 최대한 반영해보려 노력했는데, 제대로 반영한 것인지 잘 모르겠네요 😢
유익한 코멘트를 달아주셔서 다시 한 번, 감사의 말씀드립니다 !

2023-02-10 08:46 UTC, cpot5620 commented on src/main/java/controller/RacingGameManager.java
> +    public List<Name> readCarNames() {
해당 메서드 구현 당시에 인지하지 못했던 것 같습니다.
수정하여 반영하였습니다. 감사합니다 !!

2023-02-10 12:10 UTC, bimppap commented on src/main/java/error/ErrorMessage.java
> +    INVALID_COUNT("시도 횟수는 1회 이상이여야 합니다."),
좋은 시도군요! 더 나아가서 MAX_NAME_LENGTH나 MIN_COUNT를 ErrorMessage가 모르도록 String.format을 사용해보셔도 좋을 것 같습니다. 객체지향의 특징 중 하나는 캡슐화와 정보은닉이니까요 😉

2023-02-10 12:27 UTC, bimppap commented on src/main/java/view/OutputView.java
> +        }
찾아보니 아래와 같이 쓰는 방법도 있네요!

```java
String winners = StreamSupport.stream(cars.spliterator(), false)
                .map(car -> car.getName().toString()) // 혹은 .map(Car::getName).map(Name::toString)
                .collect(Collectors.joining(", "));

```

Iterator와 Stream 모두 효율적으로 반복작업을 수행하기 위해 쓰이는 것인데요. 찾아보니 관련해서 재미있는 글이 보여서 공유해봅니다ㅎㅎ [링크1](https://stackoverflow.com/questions/31210791/iterator-versus-stream-of-java-8) [링크2](https://stackoverflow.com/questions/48846529/java-streams-vs-iterators)

2023-02-10 12:39 UTC, bimppap commented on src/test/java/domain/CarTest.java
> +    public void test1() {
지금 확인했는데, `@DisplayName을 쓰고 있더라도 메서드명도 어떤 기능인지 알 수 있게 써주는게 좋습니다!

2023-02-10 12:44 UTC, bimppap approved these changes
고생하셨습니다, 쥬니! 리뷰 반영 잘 해주셨네요. 💯 
질문에 대한 답과 간단 코멘트 남겼으니 확인하고 2단계에서 반영하면 될 것 같습니다.
궁금한 점은 언제든지 DM 주세요! 이만 머지하겠습니다 🙏

2023-02-10 12:44 UTC, merged

2023-02-12 13:43 UTC, cpot5620 commented on src/main/java/error/ErrorMessage.java
> +    INVALID_COUNT("시도 횟수는 1회 이상이여야 합니다."),
```java
INVALID_NAME_LENGTH("이름은 %d글자 이하여야 합니다.")
```
```java
throw new IllegalArgumentException(
                    String.format(ErrorMessage.INVALID_NAME_LENGTH.getValue(), MAX_NAME_LENGTH)
            );
```
String.format을 적용함으로써, public으로 선언해 두었던 상수를 private으로 변경하였습니다.