[1단계 - 자동차 경주 구현] 글렌(전석진) 미션 제출합니다.
woowacourse/java-racingcar pull request #481
Opened 2023-02-09 07:29 UTC by seokjin8678

안녕하세요!
최종 테스트 이후 간만에 자바 프로그래밍을 해보네요
프리코스때 했던 미션 정도의 난이도 였지만
어제 배웠던 단위 테스트, 코드 품질에 대해 신경을 쓰느라 더 신경쓰고 시간이 걸린 것 같습니다.
초반에는 TDD를 잠깐 적용을 해봤는데 처음이라 시간이 오래걸려 뒤에는 구현을 먼저 한 것 같네요..
피드백 결과 기다리겠습니다! 감사합니다!

2023-02-09 12:22 UTC, toneyparky requested changes
안녕하세요 글렌~
우테코의 첫 미션 리뷰를 담당하고 있는 토니에요 😁
첫 미션이지만 요구사항을 잘 만족해주셨고 코드도 읽기 쉽게 잘 구성해주셨어요. 

학습을 위한 몇가지 질문과 개선하면 좋을 사항에 대해 리뷰 남겼으니 확인 및 답변 부탁드려요!
궁금한 사항은 편하게 DM 주세요~!

2023-02-09 12:22 UTC, toneyparky commented on docs/README.md
> +## 자동차 경주 구현 목록
미션 요구사항을 잘 정리하주셨네요~!
개발하며 놓치는 부분이 있을 수 있기에 이렇게 정리하는 습관을 들여두면 좋아요. 다른 미션에서도 잘 정리하시면 많은 도움이 될거에요.
기존 요구사항에 없는 `자동차 이름이 중복되는 경우`에 대해서 고민하여 추가하신 부분도 좋네요~!

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/RacingCarGame.java
> +        racingCarController.start();
2단계에서 리팩터링하는 MVC 패턴을 이미 적용하셨군요? MVC 패턴은 어떤 특징을 가지는지 간단하게 댓글로 남겨주세요 😊

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/domain/Position.java
> +    }
`equals` 와 `hashCode`를  오버라이드 해주셨네요. 어떤 이유에서 이런 코드를 추가해주셨을까요?

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +        validateDuplicateCarNames(names);
dto에서 유효성 검사를 하고 있군요. 글렌이 생각하는 DTO의 정의는 무엇인지 궁금해요~!

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/dto/RacingCarStatusResponse.java
> +    }
`toString`을 오버라이드하여 사용자에게 출력할 내용을 표시해주는군요! `toString`은 자바에서 어떤 용도로 사용하도록 만들어진 함수일까요?

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/validator/Validator.java
> +    private Validator() {}
빈 생성자는 어떤 의미로 추가하신건지 궁금해요😀

2023-02-09 12:22 UTC, toneyparky commented on src/test/java/racingcar/domain/CarTest.java
> +}
파일 가장 마지막 줄은 공백을 넣어주는 게 좋아요. 그 이유를 찾아보고 댓글로 남겨주시면 더 기억에 남을거에요~!

깃헙에서도 공백이 없는 파일은 아래 캡쳐처럼 경고한답니다 : 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/37579660/217808808-a88735a1-112c-4278-bbdb-16bb50b33bcb.png">

2023-02-09 12:22 UTC, toneyparky commented on src/test/java/racingcar/controller/RacingCarControllerTest.java
> +    void controller_start() {
해당 테스트는 어떤 의미를 가지나요?

2023-02-09 12:22 UTC, toneyparky commented on src/test/java/racingcar/service/RacingCarServiceTest.java
> +    void move_shouldNotMoveWhenNumberIsUnderThree(int input, int expected) {
`ParameterizedTest`와 `CsvSource`를 사용하셨군요~! 테스트하고픈 내용을 잘 검증할 수 있는 좋은 방법이라 생각해요 👍

잘 해주셨지만 학습을 위해 한가지 피드백을 드릴게요.

함수명과 `DisplayName`을 따르면 3이하일 경우 움직이지 않는 내용만 테스트할 것 같아요. 그렇지만 실제 내용은 움직이는 경우도 테스트하고 있죠. 즉 하나의 함수에서 두가지 다른 경우를 테스트하고 있는게 아닐까요?

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +        validateCarNameLength(name);
`Validator` 라는 전역 객체를 사용하여 자동차의 이름이 빈칸인지, 특정 글자 수를 넘지 않는지를 검증하는군요! 자동차라는 `객체`가 본인의 이름 길이 `정책`을 관리하는 `책임`을 가지는건 어때요?

2023-02-09 12:22 UTC, toneyparky commented on src/main/java/racingcar/service/RacingCarService.java
> +    private final List<Car> cars =  new ArrayList<>();
`RacingCarService` 클래스를 확인해보면 필드로 가지는 `cars`를 거의 모든 메서드에서 사용함을 확인하실 수 있어요. 일급컬렉션이라는 키워드를 찾아보고 cars를 이 방식으로 리팩터링했을 때에 `RacingCarService`와 `RacingCarServiceTest` 클래스가 어떻게 달라지는지 비교해볼까요?

2023-02-09 14:07 UTC, seokjin8678 commented on src/main/java/racingcar/domain/Position.java
> +    }
Car 클래스에서 사용하는 isSamePosition 메소드를 구현하기 위해 `equals`를 재정의 하였습니다!
`hashCode`를 재정의한 이유는 `이펙티브 자바` 내용 중 아이템 11을 보고 재정의 하였습니다!

2023-02-09 14:13 UTC, seokjin8678 commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +        validateDuplicateCarNames(names);
계층 간 데이터 전달을 위한 객체로 알고 있습니다!
DTO에서 유효성 검사를 한 이유는 View -> Controller로  DTO가 전달될 때 View 에서 잘못된 값을 넘겨줄 수 있다고 생각해서 입니다!
물론 도메인 클래스에서 유효성 검사를 할 수 있지만 View에서 제공하는 값을 신뢰하기 위해 유효성 검사를 하였습니다!

2023-02-09 14:18 UTC, seokjin8678 commented on src/main/java/racingcar/dto/RacingCarStatusResponse.java
> +    }
`이펙티브 자바`의 아이템 12 내용에서 본 바로 '간결하면서 사람이 읽기 쉬운 형태의 유익한 정보'를 반환한다고 되어 있습니다!
하지만 의도를 밝히는 내용을 작성해야 하는걸 구현하지 못했네요!

2023-02-10 00:54 UTC, seokjin8678 commented on src/test/java/racingcar/domain/CarTest.java
> +}
네! 찾아보니 POSIX 명세에서 `행의 끝은 개행(EOL)으로 끝나야 한다`라고 하네요!
GCC, 깃허브에서 파일에 개행이 없다면 경고해주고
A라는 개발자가 개행을 추가하지 않고 커밋을 했는데, B라는 개발자가 개행을 추가한다면 불필요한 로그를 남길 수 있는 우려도 있으니
앞으로 개행을 꼭! 넣어야겠습니다!

2023-02-10 02:34 UTC, seokjin8678 commented on src/main/java/racingcar/validator/Validator.java
> +    private Validator() {}
Validator 클래스는 검증을 위한 전역 클래스로 굳이 인스턴스를 만들 필요가 없어서 입니다!
혹시 모르는 상황을 방지하여 생성자의 접근자를 private로 두어 인스턴스화를 방지했습니다!

2023-02-10 05:33 UTC, seokjin8678 commented on src/test/java/racingcar/controller/RacingCarControllerTest.java
> +    void controller_start() {
인수 테스트를 하려고 작성하였습니다!
자동차 경주를 구현할 때 View를 마지막으로 구현했는데, 지금까지 한 내용으로 Controller를 테스트하려면 View를 구현해야하니(Scanner 때문에 테스트 진행 불가) 당장 테스트를 진행하기가 불가했습니다!
따라서 View를 우선 인터페이스로 만들어 테스트를 위한 목을 만들고 Controller의 로직이 제대로 작동하는지 테스트 했습니다!

2023-02-10 05:33 UTC, seokjin8678 commented on src/test/java/racingcar/service/RacingCarServiceTest.java
> +    void move_shouldNotMoveWhenNumberIsUnderThree(int input, int expected) {
메소드 명과 `DisplayName`의 내용을 해당 테스트 코드를 잘 설명할 수 있게 바꿔보겠습니다!

2023-02-10 05:34 UTC, seokjin8678 commented on src/main/java/racingcar/domain/Car.java
> +        validateCarNameLength(name);
Validator의 로직들을 관련된 도메인이나 DTO로 이동 시켜 보겠습니다!

2023-02-10 05:35 UTC, seokjin8678 commented on src/main/java/racingcar/service/RacingCarService.java
> +    private final List<Car> cars =  new ArrayList<>();
아무래도 작은 규모의 코드라 생각하여 따로 Repository를 만들지 않았는데 일급 컬렉션을 사용하려면 결국 Repository를 만들어야 할 것 같네요!

2023-02-10 07:18 UTC, seokjin8678 commented on src/main/java/racingcar/RacingCarGame.java
> +        racingCarController.start();
네! TDD를 해보려고 하니 우선 설계부터 고민을 했습니다. 그러다보니 자연스럽게 MVC 구조를 선택하게 되었고 2단계에서 적용해야 할 MVC 패턴을 일찍 적용한 것 같습니다!
MVC 패턴의 구조는 Model, View, Controller로 계층을 나눠 각자 역할을 분담하는 구조를 가지고 있습니다!
Model은 비즈니스 로직, 데이터 접근 등을 역할을 담당하고,
View는 사용자가 직접적으로 상호작용(입력, 출력)을 역할을 담당합니다.
Controller는 View와 Model을 연결하며 View가 전달한 데이터를 Model에 전달하고, Model이 전달한 데이터를 가공하여 View에 다시 전달해주는 역할을 합니다.
이렇게 알고있는데 만약 제가 틀린 정보를 알고 있다면 지적해주시면 감사하겠습니다!

2023-02-10 07:27 UTC, seokjin8678 commented
> 안녕하세요! 최종 테스트 이후 간만에 자바 프로그래밍을 해보네요 프리코스때 했던 미션 정도의 난이도 였지만 어제 배웠던 단위 테스트, 코드 품질에 대해 신경을 쓰느라 더 신경쓰고 시간이 걸린 것 같습니다. 초반에는 TDD를 잠깐 적용을 해봤는데 처음이라 시간이 오래걸려 뒤에는 구현을 먼저 한 것 같네요.. 피드백 결과 기다리겠습니다! 감사합니다!

2023-02-10 07:28 UTC, seokjin8678 commented
실수로 Close를 눌러버렸어요 ㅠㅠ
다시 PR 열었는데 문제 없겠죠..?
아무튼 피드백 한 내용에 대해 커멘트 남기고 지적해주신 부분 리팩터링 하였습니다!!
리뷰 기다리겠습니다! 감사합니다!

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/RacingCarGame.java
> +        racingCarController.start();
MVC 패턴에 대해 정확하게 파악하고 계시네요~! 글렌의 깊이 있는 지식이 느껴져요 👍 
이런 구조를 유지하면 각 레이어별로 변경을 억제할 수 있다는 장점이 있죠. 앞으로 우테코에서 시간을 보내며 계속 활용할 패턴이니 지금처럼 잘 이해해두면 좋겠어요.

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/domain/Position.java
> +    }
이펙티브 자바까지 읽으셨군요. 객체간의 비교시에는 항상 두 메서드를 오버라이드해야죠. 
[해당 커밋](https://github.com/woowacourse/java-racingcar/pull/481/commits/d887ad7f5b378093f4afa6f3885fe4020fabddaf)에서 `Objects.equals`을 활용하여 리팩터링하신 부분도 확인했어요 👍
해당 함수가 인자로 받은 null을 어떻게 처리하는지도 학습해보면 예기치 못한 예외를 대비할 수 있을거에요.

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +        validateDuplicateCarNames(names);
맞아요 데이터를 전달하기 위한 객체죠. 지금과 같은 뷰에서 컨트롤러로 넘어가는 경우에 유효성 검사하는 부분은 상황에 따라 필요할 수 있다고 생각해요. 유효하지 않은 데이터를 앞단에서 처리해줄 수 있으니까요. 다만 이렇게 DTO가 유효성 검사를 하게되면 DTO가 점점 똑똑해지고 비즈니스 로직이 추가될 수 있어요. 요 부분은 차차 미션을 진행하며 마주할 고민일테니 우선은 이정도만 이야기하죠 😉

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/dto/RacingCarStatusResponse.java
> +    }
맞아요 이펙티브 자바에는 글렌이 적어주신 내용처럼 나와있어요. 하지만 해당 관점을 어떻게 해석하느냐에 따라 구현은 달라질 수 있다고 생각해요. `사람`이 읽기 쉬운 형태에서 사람이 `개발자`인지, 혹은 애플리케이션의 `사용자`인지에 대해서는 고민해보셨을까요?

아래의 글을 하나 첨부할게요, 확인해보시고 느낀점을 적어주시면 좋겠어요 😀 : 
https://stackoverflow.com/questions/19911290/java-tostring-for-debugging-or-actual-logical-use

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/validator/Validator.java
> +    private Validator() {}
좋네요. 정적 클래스와 생성자에 대해 잘 이해하고 계시군요. 꼼꼼하십니다!

2023-02-11 06:16 UTC, toneyparky commented on src/test/java/racingcar/domain/CarTest.java
> +}
맞아요 PR에 불필요한 노이즈가 낄 수 있겠죠? 매번 손으로 넣어주기보다는 intellij를 통해 처리할 수 있는 방법을 고민해보고 적용해보죠!

2023-02-11 06:16 UTC, toneyparky commented on src/test/java/racingcar/controller/RacingCarControllerTest.java
> +    void controller_start() {
오 흥미롭네요~! 글렌은 인수 테스트의 개념에 대해서도 알고 계시군요! 
글렌이 생각하는 인수 테스트의 정의는 뭘까요? 그리고 어떤 경우에 인수 테스트를 하면 좋을까요? 알고 계신 내용을 적어주세요 😊

2023-02-11 06:16 UTC, toneyparky commented on src/test/java/racingcar/service/RacingCarServiceTest.java
> +    void move_shouldNotMoveWhenNumberIsUnderThree(int input, int expected) {
이해하기 쉽도록 바꿔주셨네요 좋아요!
혹은 테스트 자체를 두 개로 쪼갤 수 있다고 생각해요. 움직이지 않는 케이스, 움직이는 케이스 이렇게 말이죠. 

그리고 모든 숫자를 테스트하는 것도 좋지만 만약 숫자의 범위가 0-9가 아닌 0-999일 경우에도 다 테스트하면 될까요? 글렌의 생각을 댓글로 공유해주세요!

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/domain/Car.java
> +        validateCarNameLength(name);
validator라는 객체를 이용하여 도메인과 DTO에 일관된 유효성 검증 정책을 적용하는건 좋다고 생각해요. 하지만 아시듯 DTO는 도메인보다 변경의 여지가 더 많죠. 그 말은 DTO의 유효성 검증에 대한 정책도 변경될 가능성이 도메인보다 더 높음을 의미해요. 프로젝트(자동차 경주)에 핵심이 되는 도메인 정책은 소중하게 도메인 객체에 관리하는 편이 좋습니다.

2023-02-11 06:16 UTC, toneyparky commented on src/main/java/racingcar/service/RacingCarService.java
> +    private final List<Car> cars =  new ArrayList<>();
글렌이 적어주신 내용에 따르면 일급 컬렉션을 레포지토리와 관련지으셨네요. 레포지토리와 일급 컬렉션은 어떤 관계라고 생각하시나요? 레포지토리 `CarRepository`와 일급컬렉션 `Cars`를 바라보는 차이도 궁금하네요.

2023-02-11 06:23 UTC, toneyparky approved these changes
안녕하세요 글렌~ 좋은 토요일 오후네요! 제가 남긴 코멘트에 달아주신 답변과 코드 변경에 대해 확인했어요. 
코드에서는 부족함이 없기에 머지하도록 할게요. 

조금 더 이야기 나누면 좋을 내용에 대해서는 추가로 댓글을 남겼으니 PR이 머지되더라도 답변해주시면 보다 의미있는 시간을 보낼 수 있을거에요. 첫번째 미션 너무 고생 많으셨어요 😬

2023-02-11 06:24 UTC, merged

2023-02-11 12:30 UTC, seokjin8678 commented on src/main/java/racingcar/domain/Position.java
> +    }
결과적으로 첫번째 인자의 equals 메서드를 호출하는데 short-circuit을 사용하여 NullPointerException을 방지하고 있는 것 같네요!

2023-02-11 12:36 UTC, seokjin8678 commented on src/main/java/racingcar/dto/RacingCarStatusResponse.java
> +    }
네 확실히 개발자와 사용자간의 생각하는 차이가 있어보여요.
나중에 국제화, 상속 등을 생각한다면 다른 메서드로 구현을 해야겠네요!

2023-02-11 12:39 UTC, seokjin8678 commented on src/test/java/racingcar/domain/CarTest.java
> +}
안그래도 현구막 리뷰어님이 슬랙에 IntelliJ에서 자동으로 개행을 적용할 수 있는 방법을 공유해주셔서 적용했습니다!

2023-02-11 12:43 UTC, seokjin8678 commented on src/main/java/racingcar/service/RacingCarService.java
> +    private final List<Car> cars =  new ArrayList<>();
정확히 연관이 있지는 않지만 하나의 객체를 관리하는 점에서 관련이 있다고 생각합니다!
예를들어 이름이 `Glen`으로 시작하는 자동차만 가져오고 싶을 때 단순히 컬렉션이면 해당 컬렉션에 대해 로직을 작성해야하지만, 일급 컬렉션이나 Repository로 감싸면 Repository에 메시지를 전달하여 원하는 값을 가져올 수 있기 때문입니다!

2023-02-11 13:03 UTC, seokjin8678 commented on src/test/java/racingcar/controller/RacingCarControllerTest.java
> +    void controller_start() {
단위 테스트는 말그대로 프로그램의 작은 단위만 테스트를 해준다고 생각합니다!
하지만 모든 단위를 테스트하는 것은 시간이 많이 걸리고, 실수로 누락할 수 있다고 생각합니다!
따라서 사용자가 입력할 값이 최종적으로 어떠한 결과가 나오길 예측하는 테스트도 필요하다 생각했습니다!
그러다 보니 통합 테스트와 인수 테스트에 대해 알게되었고, 서로의 차이점에 대해 자세히 공부하지는 않은 것 같네요..
그래도 자동차 경주 게임의 진행사항이 명확하고(자동차의 이름에 대한 문자열과 반복 횟수) 입력이 올바르면, 즉 입력에 대해 예외 상황이 발생하지 않으면 요구사항에 맞는것이라 판단하여 인수 테스트라 생각했습니다!

2023-02-11 13:16 UTC, seokjin8678 commented on src/test/java/racingcar/service/RacingCarServiceTest.java
> +    void move_shouldNotMoveWhenNumberIsUnderThree(int input, int expected) {
네 아무래도 테스트의 목적이 비슷한데 둘로 쪼개니 코드의 중복이 생기더라구요!
`테스트 코드도 코드다`라는 프리코스에서의 피드백이 있어 중복을 최대한 피하려고 했습니다!
생각해보면 모든 숫자를 테스트할 필요는 없는 것 같네요. 기대하는 입력 값의 자료형이 int형이니 Integer.MAX_VALUE, Integer.MIN_VALUE 처럼 에지 케이스를 테스트하면 좋을 것 같아요!

2023-02-12 08:09 UTC, toneyparky commented on src/main/java/racingcar/dto/RacingCarStatusResponse.java
> +    }
굳 좋습니다~! 확실하게 이해하신거 같네요!

2023-02-12 08:11 UTC, toneyparky commented on src/test/java/racingcar/controller/RacingCarControllerTest.java
> +    void controller_start() {
말씀하신대로 단위 테스트와 인수 테스트는 검증하는 영역이 달라요. 이 부분까지 이해하고 계시군요 👍
지금은 인수 테스트를 프로젝트 요구사항을 사용자 관점에서 정상적으로 지원하는지를 검증한다고 생각하시면 좋겠네요. 레벨 2에서 학습할 기회가 있을거에요. 이런 관점에서 정상 입력에 대한 시나리오를 검증하기에 적절한 테스트라 보여지네요~!

2023-02-12 08:13 UTC, toneyparky commented on src/test/java/racingcar/service/RacingCarServiceTest.java
> +    void move_shouldNotMoveWhenNumberIsUnderThree(int input, int expected) {
글렌이 구현하실 때에 기준이 있는거 같아서 좋네요 👍

테스트 케이스도 모든 경우보다 엣지 케이스를 검증하는 게 좋아요. MAX_VALUE 와 같은 엣지 케이스도 좋지만 다른 관점도 있어요. 사용자에게 도메인을 더 쉽게 이해할 수 있는 힌트를 제공하는 엣지 케이스도 있죠. 지금과 같은 경우는 3이랑 4를 필히 테스트해야겠죠!

2023-02-12 08:20 UTC, toneyparky commented on src/main/java/racingcar/service/RacingCarService.java
> +    private final List<Car> cars =  new ArrayList<>();
답변 감사해요. 레포지토리의 개념을 잘 알고 계시네요. 저는 레포지토리를 (데이터베이스와 통신하여) 영속화된 데이터를 이용하여 객체를 반환하는 클래스로 인식하고 있어요. 글렌이 말한 하나의 객체(car)를 관리한다는 측면에서 일치하네요. 하지만 객체라기보다는 일종의 정보를 반환하는 클래스 느낌이라 도메인 객체인 일급컬렉션보다는 생동성이 떨어진다고 느껴요. Cars는 Car가 여러개일 때에 할 수 있는 행위를 담고 있는 객체라 보다 도메인과 가깝다고 생각합니다. 
코멘트의 목적은 `꼭 레포지토리가 없어도 일급컬렉션만으로 구현할 수 있다`였지만 글렌이 적어주신 내용도 이해가 되어서 지금 코드도 좋다 생각합니다 👍