[1단계 - 자동차 경주 구현] 베로(김은솔) 미션 제출합니다.
woowacourse/java-racingcar pull request #494
Opened 2023-02-09 07:46 UTC by Cyma-s

2023-02-10 07:30 UTC, Hyeon9mak requested changes
안녕하세요 베로~ 자동차 경주 미션을 함께 하게된 현구막입니다~
미션 리뷰가 늦었어요 🙏 

MVC 패턴도 확실하고 완성도 높게 미션을 진행해주셨어요!
디테일한 부분에 코멘트 남겼습니다~
아래는 질문에 대한 답변입니다.

> DTO 내부에서 DTO를 사용해도 되는가?

`Car` 처럼 비즈니스 로직을 수행하는 객체는 보통 도메인, 도메인 엔티티라고 부르는 것 같아요.
도메인과 DTO 사이에 의존이 생기면 어떤 문제가 있을까요? DTO 를 사용하는 이유는 무엇일까요?
자동차 경주 애플리케이션 특성상 자동차 규칙(로직)과 VIEW 중에 어떤 쪽의 유지보수가 더 잦을까요?
이 질문에 대한 답을 찾으면 자연스럽게 베로의 질문에도 답변이 될 것 같습니다 😄 

> 테스트만을 위한 코드는 필요한가?

테스트를 짜는 이유는 무엇일까요? 테스트 코드를 짜는 것도, 읽는 것도 모두 리소스인데 그걸 투자하는 이유가 무엇일까요? 그만한 가치가 있나요?

테스트 코드는 배포를 내보내기 전 내가 불안하다고 느끼는 부분을 검증하고 싶다는 욕구를 해소하기 위해 작성한다고 생각해요. 필요하다면 짤 수도 있을거 같아요.

그렇지만 자바 프로그램 특성상 빌드 후 jar 파일이 생성될 때 test 패키지 자체가 빠지기도 하는데요, 그렇게 되면 전혀 사용되지 않는 코드가 덩그러니 남는다고 볼 수 있어요. 또 테스트만을 위한 코드를 추가한다는 건, 어찌보면 정말 비즈니스 로직이 불안해서 테스트한다기보다 테스트를 어떻게든 만들기 위해 기능을 끼워맞춘다고도 볼 수 있을거 같아요.

아마 테스트를 위한 로직이 생겨난 이유는 테스트가 어려워서였겠죠? 테스트가 어려운 대부분의 이유는 테스트를 어렵게 하는 로직이 테스트 하려는 로직에 강하게 결합되어 있어서 그런데요, 그런걸 완화하기 위해서 역할과 책임을 분리하고 의존성을 부여하는 것으로 조금 더 쉬운 테스트 작성이 가능한 것 같아요.

제 의견도 정답은 아니니 충분히 고민해보시고 베로만의 생각을 공유해주시면 더 좋을 것 같습니다 😄 

궁금하신 점 부담없이 답글이나 DM 남겨주세요 🙇‍♂️

2023-02-10 07:30 UTC, Hyeon9mak commented on docs/README.md
> +- [x] 게임이 완료되면 우승자 목록을 찾을 수 있어야 한다.
요구사항 정리 좋습니다 😄

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarGame.java
> +}
컨트롤러에 service, view 의존성 주입 😮 👍

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/controller/RacingCarController.java
> +        }
`tryCount` 도 원시값을 포장해준다면, `tryCount` 에게 '게임을 더 지속하니, 아니면 멈추니?' 라고 물어볼 수 있지 않을까요?

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
컨트롤러가 최대한 view 와 service 에 대한 통제만 하려고 한 점이 인상적이네요 👍 💯

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Car.java
> +    private final String name;
Position 을 감싼 것처럼 name 도 감싸보면 어떨까요?
어떤 장점이 생길까요?

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Car.java
> +    }
자동차의 상태를 반환하기 위해 `RacingCarStatusResponse` 라는 DTO를 `Car` 도메인이 의존하는 형태로 보여요. 도메인이 DTO를 의존하는 경우 유지보수상에 어떤 문제가 생길 수 있을까요? 🤔

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Position.java
> +
`new Position(-10)` 을 입력하면 어떻게 될까요? 🤔

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Position.java
> +    }
동등성 부여 👍

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +    }
이름의 길이와 공백여부에 대한 내용은 입력 단에서 걸러줄 수도 있지만 비즈니스적으로도 중요한 검증 로직으로 보여요. 안정성을 추가로 확보하려면 어떤 방법이 있을까요?

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/service/MoveStrategy.java
> +    public static final int STOP_BOUNDARY = 3;
이동전략에서 정지기준이 정수 3이라는건 `RandomMoveStrategy`만의 특성 아닐까요? 💭

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/service/RacingCarService.java
> +    }
`RacingCarService`에게 `moveStrategy`를 넘겨서 이동시키는군요!! 처음보는 형태라 흥미롭네요 👍 👍 👍

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/service/RacingCarService.java
> +                .orElseThrow(() -> new IllegalStateException(EMPTY_CARS.getMessage()));
기가막히네요 😄 👍

2023-02-10 07:30 UTC, Hyeon9mak commented on src/main/java/racingcar/validator/Validator.java
> +                .distinct()
검증로직을 한 곳으로 몰아두면 검증로직을 확인할 땐 검증로직만, 정상적인 비즈니스 로직을 확인할 땐 비즈니스로직만. 흐름을 한 눈에 쉽게 파악할 수 있다는 큰 장점이 있는 것 같아요! 그러나 모든 것은 트레이드 오프라 단점도 분명 있을 것 같은데요, 어떤 단점들이 있을까요? 베로가 생각하시기엔 장점과 단점 중 어떤 부분이 더 크게 느껴져서 `Validator`로 분리를 하신걸까요?

2023-02-10 07:30 UTC, Hyeon9mak commented on src/test/java/racingcar/domain/CarTest.java
> +}
![image](https://user-images.githubusercontent.com/37354145/218021721-102f22a6-a911-4078-81bd-1228345cd959.png)

참고해주세요 😉 

https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

2023-02-10 07:30 UTC, Hyeon9mak commented on src/test/java/racingcar/domain/CarTest.java
> +        car.move();
생성자를 호출할 때 위치에 대한 값을 주입해줄 수 있다면 더 편리한 테스트도 가능하지 않을까요?

```java
Car car = new Car("mycar", 5);
...
```

2023-02-10 07:30 UTC, Hyeon9mak commented on src/test/java/racingcar/validator/ValidatorTest.java
> +    }
`ParameterizedTest` 활용 👍

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/controller/RacingCarController.java
> +        }
position을 포장했던 것처럼 Service의 tryCount도 포장해줄 수 있는거군요! tryCount를 포장하게 되면 검증 로직 분리가 이루어져서 책임을 원활하게 분리할 수 있을 것 같습니다.
tryCount의 wrapper 클래스를 만들 때 service에서만 사용되니 TryCount 클래스의 위치는 service 패키지라고 생각했는데, 맞는 구조인지 궁금합니다! 🧐

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/domain/Car.java
> +    private final String name;
현재 Validator가 맡고 있는 검증 로직을 Name 클래스로 분산할 수 있어 책임 분리가 될 것 같습니다!

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/domain/Car.java
> +    }
저도 미션 구현을 하면서 마음에 걸렸던 부분인데요, DTO 클래스가 변경될 때 도메인이 영향을 받아서 문제가 생길 것 같습니다. 해당 부분은 getter를 최대한 안 쓰기 위해 DTO를 리턴하는 방식으로 구현했는데, getter 를 쓰는게 더 나았을지 의문이네요 🤔

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/domain/Position.java
> +
Position이 사용되는 위치가 Car 뿐이고, 초기값이 0으로 지정된 후에 계속 값이 증가할 거라고 생각해서 음수 값은 고려하지 않았습니다. 그렇지만 언제나 '절대' 라는 것은 없기 때문에 음수에 대한 검증 로직을 추가해보았습니다!!

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +    }
name에 대한 wrapper 클래스로 분리하여 비즈니스 단에서 검증 로직을 추가하는 것도 방법이 될 것 같습니다.
중복 이름에 관한 문제는 List<Car>에 대한 일급 컬렉션을 만들어 검증 로직을 일급 컬렉션에서 관리하는 것이 좋아보입니다.

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/service/MoveStrategy.java
> +    public static final int STOP_BOUNDARY = 3;
CustomMoveStrategy는 랜덤 숫자 대신 테스트를 위한 숫자를 넣기 위해 만든 클래스였습니다.
숫자의 생성 방식만 다르고 움직임에 대한 로직은 똑같다고 생각해서 STOP_BOUNDARY를 MoveStrategy에 생성했었습니다!

2023-02-11 13:41 UTC, Cyma-s commented on src/main/java/racingcar/validator/Validator.java
> +                .distinct()
먼저 Validator를 따로 클래스로 분리하게 되면 Validator에 의존하는 클래스가 많아지는 단점이 있습니다. 또한 검증 로직이 증가하면 Validator 클래스가 너무 많은 책임을 갖게 될 위험이 있습니다. 
처음에 미션을 구현할 때는 검증로직이 많지 않다고 생각해서 하나의 Validator로 통합하는 결정을 내렸습니다. 그런데 지금 다시 생각해보니 Name과 TryCount라는 서로 다른 객체에 대한 검증 로직이 하나에 있는 것은 책임 분리가 제대로 되지 않은 것 같다는 생각이 드는군요 🧐

2023-02-11 14:18 UTC, Cyma-s commented on src/test/java/racingcar/domain/CarTest.java
> +        car.move();
오 그런 방법이...!
위치의 초기값이 항상 0이라고 생각하고 MoveStrategy라는 전략 패턴을 만들었어서 그런지 생성자로 입력 받는 방법을 생각하지 못한 듯 합니다 🤔

2023-02-12 04:54 UTC, Hyeon9mak commented on src/main/java/racingcar/controller/RacingCarController.java
> +        }
저는 패키지를 '팀원이 요구사항에 따라 코드를 수정할 때 빠르게 클래스 파일을 찾아낼 수 있는 이정표' 라고 생각하는 편이에요.
즉,'유지보수에 도움이 되는가'를 기준으로 패키지를 나눕니다.

`controller`, `service`, `domain`, `dto`, `exception`, `view` 와 같이 기술별로 패키지가 나눠진 상태에서
동료 개발자가 "게임 진행 비즈니스를 담당하는 객체"를 찾을 때 어떤 패키지부터 열어볼지 상상해본다면 쉽게 결정이 가능할거 같네요.

2023-02-12 05:13 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Car.java
> +    }
자동차 경주는 비즈니스 로직(도메인)보다 출력(뷰)에 대한 변화가 잦은 애플리케이션을 가정하고 진행되는 미션 같아요. 그래서 MVC 패턴을 적용해보는 것이겠죠? 뷰에 직접적으로 사용되는 DTO를 도메인이 의존함으로서 유지보수에 영향을 받으면 베로의 퇴근시간만 늦춰질 뿐이죠. 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/37354145/218294041-95069174-c8a5-48a8-b75f-9f694fb853d6.png">

만약 DTO 사용을 하고 싶었다면 뷰의 변화에 영향을 받지 않는, 온전히 데이터 전달용만으로만 사용되는 DTO 를 만들어주면 좋을 것 같습니다. (단, 이때 사용되는 DTO는 출력을 위한 데이터를 전달보다, 다른 비즈니스 로직에서도 활용할 수 있다는 의미를 가져야 함)

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/37354145/218294046-5aa65671-ac37-4b2d-b7d9-f06f7b384a27.png">

그래야 `RacingCarView`와 `RacingCarStatusResponse`의 변화에도 `Car` 가 영향을 받지 않을테니까요.

getter 사용을 지양하신 이유가 있을까요? 도메인에서 getter로 값을 뽑아낸 후 서비스 계층에서 비즈니스로직을 수행하는 것은 지양해야하지만, `전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.` 라는 비즈니스 요구사항이 있으므로 getter 메서드도 비즈니스 로직을 충실히 수행하는 메서드가 아닌지 고민 해봐야할 것 같아요.

2023-02-12 05:16 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Position.java
> +
베로와 함께 작업을 진행한 동료는 의도를 이해하고 `Position`을 사용하겠지만, 그렇지 않은 개발자는 아무것도 모른채 객체를 사용하게 될거에요. 안전하게 만들어줄수록 좋습니다. 👍

2023-02-12 05:17 UTC, Hyeon9mak commented on src/main/java/racingcar/dto/RacingCarNamesRequest.java
> +    }
좋습니다! https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103736987 와 같은 맥락의 이야기였습니다.

2023-02-12 05:23 UTC, Hyeon9mak commented on src/main/java/racingcar/service/MoveStrategy.java
> +    public static final int STOP_BOUNDARY = 3;
이동전략 인터페이스 구현체로 "정수가 아닌 문자열", "다른 자동차들과의 관계", "주입한 기름" 등등 여러가지를 만들 수 있을 것 같은데 모두가 `STOP_BOUNDARY` 값을 필요로 하진 않을 것 같은데 혹시 제가 잘못 이해하고 있는걸까요? 🙏

2023-02-12 05:32 UTC, Hyeon9mak commented on src/main/java/racingcar/validator/Validator.java
> +                .distinct()
Q. `Validator`가 '검증'이라는 책임을 가지는 것도 역할과 책임이 잘 나누어진 것은 아닐까요? 왜 책임은 한 곳으로 몰리면 안될까요? 어떤 경우를 염두에 두고 `Name`과 `TryCount` 에게 책임을 분리하신걸까요?

2023-02-12 05:51 UTC, Hyeon9mak approved these changes
안녕하세요 베로~ 자동차 경주 1단계 고생 많으셨습니다.

질문 주신 내용들에 대해 답변과 추가질문, 제 생각을 적어보았어요.
2단계 미션을 제출하시면서 추가질문에 대해 답변 주시면 더 좋을 것 같아요 😄 

- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103735212
- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103736677
- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103736987
- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103737055
- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103737529
- https://github.com/woowacourse/java-racingcar/pull/494#discussion_r1103738241

그럼 2단계에서 만나요~ 👍

2023-02-12 05:51 UTC, Hyeon9mak commented on src/main/java/racingcar/controller/RacingCarController.java
> +        }
```suggestion
        while (tryCount.isAvailable()) {
            ...
        }
```

검증을 위해 원시값을 포장한 VO로만 사용할 수도 있겠지만, 
자동차 경주 반복을 물어볼 수 있는 도메인 객체가 될수도 있겠네요.

2023-02-12 05:51 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/Car.java
> +    }
```suggestion
    public Car(String name) {
        this(name, 0);
    }
    
    public Car(String name, int position) {
        this.name = new Name(name);
        this.position = new Position(position);
    }
```

생성자 체이닝을 통해서 자동차 생성의 편의를 도와줄 수도 있겠네요.

2023-02-12 05:51 UTC, merged

2023-02-12 13:41 UTC, Cyma-s commented on src/main/java/racingcar/controller/RacingCarController.java
> +        }
오오... 확실히 VO보다 책임을 가지고 있는 도메인 객체로서의 역할이 더 어울려 보이네요!

2023-02-12 13:48 UTC, Cyma-s commented on src/main/java/racingcar/service/MoveStrategy.java
> +    public static final int STOP_BOUNDARY = 3;
저는 MoveStrategy가 오직 "앞으로 간다" 에 대한 것만 생각하고 있었어서 STOP_BOUNDARY가 모든 전략에 포함된다는 생각이었습니다! 그런데 의견 주신 것처럼 프로그램이 확장되면 자동차가 "앞으로 가는 것" 이외에 다른 전략들도 존재할 수 있겠다는 생각이 들어요..!! 
그렇다면 STOP_BOUNDARY가 RandomMoveStrategy만의 특성이 맞을 것 같아요 😮 확장성 측면에서 좀 더 다양한 전략들을 생각해 봤어야 했네요 😥