[1단계 - 자동차 경주 구현] 후추(주찬민) 미션 제출합니다.
woowacourse/java-racingcar pull request #496
Opened 2023-02-09 07:52 UTC by Combi153

안녕하세요! 반갑습니다. 우아한 테크코스 5기 후추입니다.

코드를 작성하면서 고민했던 사항과 어려움을 남겨봅니다. 리뷰 시 고려해주신다면 정말 감사하겠습니다!

1. 시간 부족으로 인한 하드코딩
 - 시간이 부족하여 하드코딩된 부분이 많습니다. 2단계 미션을 진행하면서 하드코딩 등을 수정해보도록 하겠습니다.
 
2. 좋은 구조란 무엇인가?
- MVC 패턴에 대한 얕은 지식으로 해당 구조를 사용하였습니다. 그러나 같은 MVC 패턴임에도 사람마다 그를 구현하는 방법이 다른 것 같습니다. 그러다보니 단순히 어떤 패턴을 사용하는 것이 좋은 구조의 조건이라고 말하기 어려운 것 같습니다. 좋은 구조를 갖기 위해 어떤 것들을 고려해야 하는지 궁금합니다. 

3. getter 를 사용하지 않으려 노력했지만, 저희가 설계한 구조에서는 getter 사용이 불가피하다고 느꼈습니다. 어떤 방식으로 리팩토링하면 좋을지 힌트를 주신다면 감사하겠습니다.

4. 자바를 자바답게 사용하지 않은 곳이 있다면 모두 알려주신다면, 열심히 공부해보겠습니다.

감사합니다. 열심히 성장하겠습니다!

2023-02-10 08:53 UTC, Hyeon9mak requested changes
안녕하세요 후추! 자동차 경주 미션을 함께 하게된 현구막입니다~
미션 리뷰가 늦었어요 🙏 

MVC 패턴에 대한 고민이 많으시군요! 그래도 미션을 잘 진행해주신 것 같아서 너무 멋집니다 👍 
차근차근 진행해보면 좋을 것 같아서 디테일하게 코멘트를 남겼어요!
미션 진행이 더뎌도 좋으니 천천히 확인해주세요.

> 좋은 구조란 무엇인가? MVC 패턴

너무 좋은 고민!! 맹목적으로 "MVC 패턴 짱이래. 이렇게 짜는게 객체지향이야. 이게 아름다운 코드지." 라는건 아무런 의미가 없다고 생각해요. 정말 왜 좋은지? 왜 객체지향이어야만 하는지? 건강한 고민이 뒤따른다면 복잡해보이는 패턴도 '아 이래서~' 하고 이해가 되는거 같아요.

MVC 패턴을 포함한 모든 디자인 패턴, 아키텍처는 결국 유지보수를 위해서 존재한다고 생각해요. 모든 서비스는 유지보수해야 할 포인트가 다른 것 같아요. 어떤 서비스는 데이터는 잘 변화하지 않는데 브라우저로 출력했다가, 모바일로 출력했다가 뒤바뀌는 경우가 잦고, 또 어떤 서비스는 출력은 항상 모바일 앱으로만 하는데 내부 데이터와 구조가 시시각각 변화해요. 이들은 각각 출력기능을 유지보수하기 쉬운 패턴과 구조를 바꾸기 쉬운 패턴을 적용하는게 좋겠죠?

자동차 경주 게임의 경우 자동차 경주 진행 방식과 화면 출력 방식 중 어떤게 자주 변경될까요?
아무래도 출력방식에 대한 변화가 잦기 때문에 MVC 패턴이 도입된 것 같아요.
그렇다면 출력에 대한 유지보수가 쉽도록 구조를 만들어야 자동차 경주 게임에 잘 어울리는 MVC 패턴을 도입했다고 말할 수 있을 것 같아요. (출력에 대한 유지보수가 쉽다는 건, View 의 변화에 Controller 와 Model 이 영향을 안받는다는 뜻이겠죠? 😉 )

현재 애플리케이션의 동작 특성과 유지보수 할 때 어떤 부분에 가장 주의를 기울여야하는지를 고민하면 자연스럽게 좋은 구조에 대해 떠올리실 수 있을 것 같아요.

> getter 사용

getter 를 사용하면 안될 이유가 있나요? 어떤 점에서 getter 사용을 지양해야한다고 느끼셨나요? 😄 

> 자바답게

저도 제 자신이 '자바답게' 짜는진 모르겠지만... 열심히 코멘트 남겨보았습니다! 코멘트 내용 확인해주세요 😄 👍 

진행하시면서 궁금하신 점 부담없이 답글이나 DM 남겨주세요 🙇‍♂️

2023-02-10 08:53 UTC, Hyeon9mak commented on docs/README.md
> +                - 정수x (1이상, Integer 범위)
`- [ ]`, `- [x]` 를 사용하면 체크박스를 생성해서 어떤 작업을 얼마나 진행했는지 기록할 수 있어요! 👍

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/controller/GameController.java
> +    }
호출되는 순서에 따라 메서드를 정리해주면 가독성이 더 좋아질거 같아요 😄

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +    public static final int MINIMUM_ROUND = 1;
`Car` 내부에서만 사용되는 상수들은 private 접근제한자로 가려줄 수 있겠죠?

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +        if (!isValidName(name)) {
부정형 표현을 위해 if 키워드 내부에서 사용되는 `!`는 잘 눈에 띄지 않는데요, `isValidName` 표현을 `isNotValidName` 등으로 바꾸어주면 문제를 해결해줄 수 있어요!

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +    }
조금 더 자동차 경주 게임에 어울리는 행위를 네이밍으로 정해주면 어떨까요? 😄 
또 그렇게 했을 때 생기는 장점은 무엇일까요? (유지보수 관점)

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +    }
동등성 부여 👍 
실제 사용처는 `이름 중복 검증`인거 같은데요, position 까지 같아야 할 필요가 있을까요?

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/carfactory/CarFactory.java
> +    }
메서드 명칭은 `createCareRepository` 인데 실제 반환타입은 `Cars`인거 같아요! 네이밍을 조금 더 직관적으로 바꾸어주면 어떨까요?

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +
일급 컬렉션 활용 👍

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
중복된 자동차가 경주에 포함되어선 안되는군요! 혹시 `Set` 자료구조를 사용해볼 수도 있지 않을까요? `List`와 `Set` 은 어떤 차이가 있을까요? `List`가 더 나을까요? 후추의 생각이 궁금합니다 😄

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +
`MOVING_CONDITION` 는 현재 사용되지 않는 것 같아요.

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
`Cars` 는 경주에 참가한 자동차들 묶음(컬렉션)으로 자동차들이 일괄적으로 수행해야할 비즈니스로직을 담당하는 객체 같은데요, 현재 `movePosition()` 메서드는 경주 수행 결과가 어떻게 출력(이름, 위치)될지를 인지(`Map<String, Integer>`)하고 있는 것 같아요. 이럴 경우 어떤 문제가 생길까요?

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +        return car;
매직넘버! `MOVING_CONDITION` 로 대체 가능하겠네요 😄

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
사용되지 않는 메서드는 동료 개발자들에게 혼란을 줄 수 있어요 🙏

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +                .orElseThrow(NoClassDefFoundError::new);
- 현재 메서드는 테스트에서만 사용되고 있는 것 같아요 😱 
- `NoClassDefFoundError` 는 컴파일 타임에 존재했던 클래스에 런타임에 존재하지 않을 때 발생하는 에러입니다. 개발자들이 잘 아는 예외를 사용하는 건 가독성에 도움이 되지만 잘못 사용하면 더 큰 역효과를 만들 수 있어요!

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/numbergenerator/NumberGenerator.java
> +}
- `Random().nextInt(9)` 는 0~8 사이의 난수가 발생됩니다.
- 명칭만 보아서는 0~9 사이의 랜덤한 숫자를 발급한다는 걸 알기가 어려울 것 같아요! 메서드 네이밍을 조금 다듬어주면 어떨까요? 😉

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/result/Result.java
> +    }
`Result` 는 결과 출력을 위해 사용되는 객체인 것 같은데요,
내부에서 우승자를 가리기 위한 비즈니스 로직을 포함하고 있는 것 같아요.

비즈니스 로직 수행과 출력을 온전히 분리할 수 있을까요?

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/system/GameSystem.java
> +
`NumberGenerator`가 `Cars` 내부에서 생성되어 사용되는 덕분에 `GameSystem`에서는 사용되지 않는 것 같아요 😱

2023-02-10 08:53 UTC, Hyeon9mak commented on src/main/java/racingcar/view/InputView.java
> +    }
오! 공백인지, 숫자인지에 대한 간단한 검증연산은 `View`의 책임으로도 볼 수 있죠 💯 👍

2023-02-10 08:53 UTC, Hyeon9mak commented on src/test/java/racingcar/domain/carfactory/CarFactoryTest.java
> +}
![image](https://user-images.githubusercontent.com/37354145/218042990-1a6904bc-0f70-4c43-9e21-78ef1801d8c5.png)

https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

참고해주세요 😄

2023-02-10 08:53 UTC, Hyeon9mak commented on src/test/java/racingcar/domain/carfactory/CarFactoryTest.java
> +    void createCarRepository(List<String> carNames) {
무엇에 대한 테스트인지 명시해주면 동료 개발자들이 테스트 의도를 파악하기 더 좋을 것 같아요 👍

2023-02-10 09:25 UTC, Combi153 commented on docs/README.md
> +                - 정수x (1이상, Integer 범위)
오 알려주셔서 감사합니다 적극 활용해볼게요!

2023-02-10 09:25 UTC, Combi153 commented on src/main/java/racingcar/controller/GameController.java
> +    }
앗 꼼꼼하지 못했네요 앞으로는 더 신경써보겠습니다!

2023-02-10 09:26 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +    public static final int MINIMUM_ROUND = 1;
이 역시 마찬가지네요ㅠㅠ 단축키를 활용해 상수를 만들고 미처 확인을 안 했습니다 얼른 고칠게요~!

2023-02-10 09:34 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +        if (!isValidName(name)) {
언젠가 함수 네이밍에 대해 알아보고 고민할 때, boolean 값을 반환하는 함수에 `부정형` 표현을 쓰지 않는 것이 좋다는 생각을 하였습니다. 왜냐하면 함수의 반환값을 예상할 때, 부정형으로 인해 뒤집어서 생각해야 되니까 헷갈릴 수 있겠더라구요. 그래서 `!`을 지향하려 했습니다.

현구막님 말씀을 듣고 보니, 헷갈리기란 둘 다 마찬가지일 거라는 생각이 드네요! 오히려 눈에 띄도록 `not` 등을 붙이는 것이 좋아보입니다.

한편, 헷갈리지 않으면서도 `not`을 붙이지 않는 방법은 없을까요? `isInvalidName` 정도는 괜찮은 이름일까요?

2023-02-10 15:01 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +    }
리뷰를 받은 후 `객체지향`에 대해 다시 돌아보는 중입니다. 감사드려요!😀

이번에 진행한 미션 내용이 자동차 경주 게임이고, 이 기능은 `자동차` 객체가 가지므로 updatePosition 보다는 `move` 정도가 어떨까 해요. 앞으로는 객체가 주체성을 갖도록 네이밍에 신경을 쓰겠습니다!

`move` 등으로 자동차 객체와 어울리는 네이밍을 했을 때 다음과 같은 장점이 있을 것 같아요

1. 보다 추상화된 이름이에요. 구현 기능이 변경되더라도 이름 덕분에 새로운 함수를 만들지 않아도 될 것 같아요. 가령, move 메소드 내에 "여러 번" 움직이거나, "앞으로 혹은 뒤로" 움직이는 등의 기능이 추가되어도 이상하지 않아요
2. 가독성이 좋아졌어요. 다른 개발자들이 이해하기 편한 이름이에요. Car 객체를 외부에서 사용하거나, Car 객체를 직접 수정할 때 모두 도움이 될 것 같아요

또 다른 주요한 장점이 있다면 힌트를 주시면 감사할 것 같아요 또 고민해볼게요!

2023-02-10 15:06 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +    }
position 까지 같을 필요는 없을 것 같아요!

자동차 객체 간 이름의 중복이 허용된다면 필요할 수도 있을 것 같다는 생각이 순간 머릿속을 스쳐지나갔지만,,, 그때 역시 position으로 구분하는 것이 완전한 구분이라고 볼 수는 없겠네요!

이런 점에서도 세심하게 코드를 짜는 연습을 더 해볼게요 감사합니다😁

2023-02-10 15:08 UTC, Combi153 commented on src/main/java/racingcar/domain/carfactory/CarFactory.java
> +    }
Cars 객체는 처음에 이름이 CarRepository 였어요. 객체 이름을 Cars 로 바꾸면서 놓친 부분이 있었네요. 이름을 바꾸는 것도 신중해야할 것 같습니다!
말씀하신 메소드의 이름이 `createCars` 라면 `직관적`인 이름에 부합할까요?

2023-02-10 15:09 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +
얼른 지우겠습니다!

2023-02-11 05:04 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
와 이런 생각은 못해봤습니다! 리뷰 최고입니다 현구막!!!😆😆😆

- 출력에 대한 요구사항이 변경된다면 문제가 생길 것 같습니다. 
출력 방식을 변경할 때는 View의 코드를 바꾸는 것이 마땅한데, 비즈니스 로직을 담당하는 코드까지 바꾸는 일이 생길 것 같아요! Domain 에서 지나치게 많은 정보를 알고 있는 상황 같습니다.
- 데이터를 있는 그대로 전달하는 것이 좋은 방법이 될 것 같습니다!

2023-02-11 05:05 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +        return car;
맞습니다!! 꼼꼼한 코드 작성에 유의할게요!

2023-02-11 05:08 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +                .orElseThrow(NoClassDefFoundError::new);
이 기능을 Result 객체로 옮기면서 지우지 않았던 것 같습니다. `NoClassDefFoundError` 는 저도 처음 보는 에러네요🤔 언제 왜 이 코드를 적었는지 모르겠습니다...

꼼꼼한 코드 작성! 정신차리고 코딩하기! 명심하겠씁니다!!!

2023-02-11 05:15 UTC, Combi153 commented on src/main/java/racingcar/domain/numbergenerator/NumberGenerator.java
> +}
- 메소드의 사용법을 보다 자세히 알고 사용하는 습관을 들여야 할 것 같아요! 알려주셔서 감사드립니다!

- 혹은 테스트코드에서 0부터 9가 나오는지 테스트하였다면, 이런 실수를 방지할 수 있었을 것 같네요. Random한 값을 불러오는 기능인지라 테스트 코드 작성에 어려움이 있어 못했습니다. Random 값에 대한 테스트 코드를 짜는 방법도 존재하나요? 존재한다면 도전해보고 싶습니다!

- 메서드 네이밍도 고려해보겠습니다!

2023-02-11 05:16 UTC, Combi153 commented on src/test/java/racingcar/domain/carfactory/CarFactoryTest.java
> +    void createCarRepository(List<String> carNames) {
DisplayName을 추가하겠습니다!

2023-02-11 05:16 UTC, Combi153 commented on src/test/java/racingcar/domain/carfactory/CarFactoryTest.java
> +}
설정했어요😎

2023-02-11 05:17 UTC, Combi153 commented on src/main/java/racingcar/domain/system/GameSystem.java
> +
꼼꼼하게 보기! 다시 한 번 가슴 깊이 새깁니다!!!!!!!!

2023-02-11 11:13 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
- `List`는 중복을 허용하지만, `Set`은 중복을 허용하지 않는다는 특징이 있습니다.

- 자동차 간 중복이 있다면 오류가 발생하도록 검증 기능을 구현해두었기 때문에 처음에는 `Set` 자료구조의 필요성을 느끼지 못했습니다.

- 하지만 그러한 정보는 `Cars 클래스의 코드를 열어봐야만 알 수 있는` 정보입니다. 만약 `Set` 구조를 사용했다면 다른 객체에서 Cars의 필드를 사용할 때 중복이 허용되지 않은 것을 유추할 수 있겠어요!

- 생성 및 검증 단계에서 중복을 막고, 이후 자료의 특성으로 중복을 막도록 하는 것이 객체의 주기 및 유지보수 관점에서도 긍정적인 방향일 것 같습니다.

- 한편 자동차 간 중복이 있다면 오류가 발생하도록 하는 것은 여전히 구현하고픈 기능입니다. 따라서 생성자에서 입력을 받을 때는 `List`로 받아 검증을 받도록 하고, 이후 `Set`자료구조로 초기화하도록 리팩토링 하는 것이 좋을 것 같습니다.

깊게 생각해볼 수 있는 또 하나의 키워드였네요 감사드립니다😁😁😁

2023-02-12 11:50 UTC, Combi153 commented on src/main/java/racingcar/domain/result/Result.java
> +    }
분리해보겠습니다!

2023-02-12 13:35 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +        if (!isValidName(name)) {
그런 고민을 거치셨군요! 💯 
`!` 를 사용하는 것과 `not`을 사용하는 것 모두 가독성 가시성이라는 트레이드오프가 있으니 후추가 생각하시기에 더 중요하게 느껴지는 걸 선택하시면 될 것 같습니다.

2023-02-12 13:37 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +    }
1번 답변을 기대하고 드린 질문이었습니다 😄 👍 💯

2023-02-12 13:39 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/car/Car.java
> +    }
만약 이름중복을 허용한다면 name + position 으로 동등성을 부여하는게 아니라, 완전히 equals & hashCode 오버라이드를 제거하고 인스턴스 고유의 해시값으로 비교되도록 바꿔야할 것 같아요. 현재는 이름을 통한 비교가 의미가 있으므로 `name` 으로만 동등성을 부여해주면 될 것 같습니다.

2023-02-12 13:39 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/carfactory/CarFactory.java
> +    }
네 그정도면 좋은 것 같아요 😄

2023-02-12 13:53 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
> 생성자에서 입력을 받을 때는 List로 받아 검증을 받도록 하고, 이후 Set자료구조로 초기화하도록 리팩토링 하는 것이 좋을 것 같습니다. 

여기까지도 생각하신 점 너무 멋집니다. 기대했던 모든 답변이 다 나왔어요!!!! 💯 💯 💯 💯 
`LinkedHashSet` 까지는 저도 생각하지 못했네요 👍 👍 👍 
코멘트의 의도는 '비즈니스 로직에 어울리는 자료구조가 있지는 않을지 항상 고민하기' 였습니다.

- 말씀주신대로 `List`는 중복을 허용해서 자체적인 검증이 필요하고, `Set`은 순서를 보장해주지 않아 출력순서를 보장할 수 없습니다.
- `LinkedHashSet`이 가장 적합해보이는데, 성능이 우려됩니다. 
- 하지만 현재 자동차 경주 미션에 참가자가 999,999,999명 동시에 참여할 일이 있을까요?
- 보편적인 `List`를 놔두고 `LinkedHashSet`를 써야할만큼 중요한 로직일까요?

모든 기술은 트레이드오프가 있고 걔중에 애플리케이션 특성에 가장 부합하는(가장 단점이 적은)걸 선택하면 되는 것 같습니다.
애플리케이션 특성에 맞는 건 무엇일지, 팀원들이 유지보수할 때 어떻게 느낄지를 고려해보시고 후추만의 결정을 내려주세요. 그리고 저를 설득해주세요 😄

2023-02-12 13:59 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/numbergenerator/NumberGenerator.java
> +}
랜덤한 값을 테스트 하는 방법은 여러가지가 있을 것 같은데, 그전에 `Random` 라이브러리를 꼭 테스트 해야하는가 고민 해봐야 할 것 같아요. 후추는 `List`, `Set`, `Map`, `String`, `Integer` 와 같은 자료구조, 라이브러리들을 테스트하고 사용하시나요? 이것들을 믿고 사용하시지 않나요?

자신이 불안을 느끼는 요소에 대해 테스트를 작성하는게 좋지만 테스트 작성도 결국 리소스고, 테스트 하나하나도 유지보수 포인트가 됩니다. 저명한 라이브러리나 프레임워크 같은 경우 사용설명서(공식문서)를 제공해주니 이를 참고하는 습관을 기르면 많은 시간을 아끼실 수 있을 것 같아요. https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextInt-int-

2023-02-12 14:14 UTC, Hyeon9mak approved these changes
후추~ 자동차 경주 1단계 고생 많으셨습니다~

질문 주신 내용에 대해 답변과 제 생각을 적어보았어요.
2단계 미션을 진행하면서 참고해주세요 🙂

- https://github.com/woowacourse/java-racingcar/pull/496#discussion_r1103804480
- https://github.com/woowacourse/java-racingcar/pull/496#discussion_r1103804663
- https://github.com/woowacourse/java-racingcar/pull/496#discussion_r1103804984
- https://github.com/woowacourse/java-racingcar/pull/496#discussion_r1103807410
- https://github.com/woowacourse/java-racingcar/pull/496#discussion_r1103808251

그럼 2단계에서 만나요 ~ 👋

2023-02-12 14:14 UTC, Hyeon9mak commented on docs/README.md
> +- [x] 코드 및 요구사항의 변경 가능성을 고려하기
👍

2023-02-12 14:14 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/record/GameResultOfCar.java
> +    }
getter 메서드를 통해 출력을 모두 행하는 것 같은데, `toString`을 오버라이드 한 이유가 있을까요?

2023-02-12 14:14 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/record/GameRecorder.java
> +    }
`GameRecorder`와 `GameRecordManager`의 책임은 각각 무엇인가요? 어떤 이유로 나뉘게 된 것인지 궁금하네요.

2023-02-12 14:14 UTC, Hyeon9mak commented on src/main/java/racingcar/view/OutputView.java
> +    }
내부에서만 사용되는 메서드 같아요.

2023-02-12 14:15 UTC, merged

2023-02-13 01:16 UTC, Combi153 commented on src/main/java/racingcar/domain/numbergenerator/NumberGenerator.java
> +}
> 테스트 작성도 결국 리소스고, 테스트 하나하나도 유지보수 포인트가 됩니다.

이 문장이 와닿네요. 어쩌면 `테스트 코드 그 자체를 목적`으로 두고 코드를 작성하려고 했던 것 같습니다.

앞으로는 기술을 맹목적으로 추구하기보다는 `기술의 배경과 이유`에 대해 고민하고 활용하는 것이 맞을 것 같습니다.

소중한 교훈을 알려주셔서 감사합니다😄

2023-02-13 01:16 UTC, Combi153 commented on docs/README.md
> +- [x] 코드 및 요구사항의 변경 가능성을 고려하기
감사해요😎

2023-02-13 01:21 UTC, Combi153 commented on src/main/java/racingcar/domain/record/GameResultOfCar.java
> +    }
기능을 구현하던 단계에서 의도대로 코드가 동작하지 않았습니다. 그래서 `디버깅`을 위해 `toString`을 오버라이드 해 사용했어요. 다른 사람이 개발할 때도 디버깅 등 상황에서 사용할 일이 있을 것 같아 지우지 않았습니다!

Effective Java 책에서 toString의 재정의를 강조하는 글을 참조하기도 했습니다.

마땅한 이유가 될까요?

2023-02-13 01:25 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/record/GameResultOfCar.java
> +    }
디버깅 용도였다면 훌륭한 이유입니다 😄

2023-02-13 06:26 UTC, Combi153 commented on src/main/java/racingcar/view/OutputView.java
> +    }
앗 private로 바꾸겠습니다! 메소드 순서도 아래로 내려야겠네요

2023-02-13 06:36 UTC, Combi153 commented on src/main/java/racingcar/domain/record/GameRecorder.java
> +    }
- `GameRecorder` 는 게임 결과를 기록하는 역할을 합니다. 
- `GameRecordManager` 는 게임 결과의 기록 방식을 관리하는 역할입니다.
- 게임 결과를 기록할 때 기록하는 방식이 `변화할 수 있다`고 생각 했습니다. 지금은 GameResultOfCar 클래스에 `name`, `position`, `gameRound` 를 담아서 저장하는데, 자동차에 대한 상태가 추가된다면 새로운 정보도 저장할 수 있을 것 같습니다.
- 따라서 저장하는 방식의 변화를 `GameRecorder` 객체의 외부에서 주입을 받아 사용하는 방법을 떠올렸습니다.
- 차후 리팩토링 시에 `GameRecordManager`를 인터페이스로 두고, 다른 구현체를 만들어 사용할 계획이었습니다.

혹시 이러한 방식에 어떻게 생각하시나요?

2023-02-13 07:00 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +        if (!isValidName(name)) {
저는 `valid`의 반대 표현인 `invalid`가 있으니 `isInvalidName` 으로 정하는 것이 좋을 것 같습니다.

트레이드 오프 상황을 마주했을 때 근거 있는 선택을 내리는 연습을 많이 해보겠습니다!!

2023-02-13 07:01 UTC, Combi153 commented on src/main/java/racingcar/domain/car/Car.java
> +    }
넵 알겠습니다! 인스턴스 해시값으로 비교하는 것은 다음에 실험해보고 싶네요

2023-02-13 07:59 UTC, Combi153 commented on src/main/java/racingcar/domain/cars/Cars.java
> +    }
`List` 사용에 대한 생각
- 출력순서가 보장됩니다.
- 중복을 허용합니다.
- 중복 여부에 관한 정보를 전달하지는 못합니다.
- 보편적인 자료형으로 다른 개발자들이 사용할 때 어려움이 없습니다.

`Set` 사용에 대한 생각
- 출력순서가 보장되지 않습니다.
- 중복을 허용하지 않습니다.
- 중복 여부에 관한 정보를 간접적으로 전달합니다.
- 출력 순서를 보장하기 위해 `LinkedHastSet` 등을 활용해야 합니다. 이는 성능 면에서 떨어집니다.
- 다른 개발자가 `LinkedHashSet`이 아닌 다른 Set 자료형으로 새로운 게임을 개발할 시 의도대로 동작하지 않을 수 있습니다.

두 자료형에 대해 `비즈니스 로직에 더 어울리는 자료구조 무엇일지` 고민을 해본다면, 자동차 간의 순서가 반드시 보장되어야 할 것 같습니다. 이때 Set 자료형을 쓴다면 유지 보수 시 다른 개발자들에게 혼란을 초래할 수 있을 것 같습니다.

2023-02-14 08:16 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/record/GameRecorder.java
> +    }
설명을 듣고 나니 이해가 되는데, 그 전에는 어떤 의도인지 궁금했어요.
저는 개인적으로 '당장 분리가 필요한게 아니면 굳이 미리 분리할 필요 없다.' 고 생각하는 편인데, 
취향의 영역이라서 후추가 끌리시는 대로 해도 좋을 것 같아요 😃

2023-02-14 08:18 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/record/GameRecorder.java
> +    }
대신 그러한 설계에 대해서는 PR description 에 미리 설명을 적어두면 💯  (저도 맨날 까먹어요.. ㅎㅎ;;)