[1단계 - 자동차 경주 구현] 푸우(백승준) 미션 제출합니다.
woowacourse/java-racingcar pull request #502
Opened 2023-02-09 07:59 UTC by BGuga

안녕하세요 리뷰 감사합니다.

페어 프로그래밍을 하며 궁금했던 부분을 정리하여 문서로 작성해 두었습니다.
아래는 피드백 받고 싶은 부분에 대한 정리글 입니다.
(피드백)[https://github.com/BGuga/java-racingcar/blob/step1/docs/Feedback.md]

2023-02-09 14:48 UTC, xrabcde requested changes
안녕하세요 푸우! 바다입니다 🌊
과정의 첫 시작을 함께하게 되어 반갑습니다 ㅎㅎ
요구사항에 맞게 잘 구현해주시고 테스트와 커밋 단위를 꼼꼼히 잘 작성해주셨네요 👍🏻
몇 가지 리뷰 남겼는데 확인해보시고 궁금한 점은 언제든 코멘트나 DM으로 알려주세요~
질문에 대한 답변 드릴게요 :)

> 1. Car 객체의 Position 객체가 분리돼야 하는지

질문하신 내용을 읽어보니 분리했을 때의 장점과 단점을 이번 미션을 통해 충분히 느끼신 것 같아요 ! 그때그때 요구사항에 따라, 개개인의 취향에 따라 다르겠지만 분리했을 때의 장점을 명확히 알고 있고 분리의 필요성을 느꼈다면 분리해도 좋다고 생각합니다 ☺️

> 2.MVC 패턴에서 controller와 model의 역할과 차이

이 질문은 아래 코멘트에서도 남겼지만 일급컬렉션을 학습해보시면 해소될 것 같아요 ㅎㅎ!

> 3.InputView에서 Model을 생성해서 Controller로 보내줘도 되는가

MVC 패턴을 사용하면 어떤 장점이 있을까요? layer를 나누게 된 배경을 생각해보시면 Model과 View는 서로를 모르는 게 좋을 것 같은데요 ㅎㅎ Car를 생성하는 과정에서 여러 검증로직들을 거치게 될 것이고 그것들은 모두 domain의 로직들인데 view가 알 필요가 있을까요?! 푸우는 어떻게 생각하시나요?
MVC 패턴이 헷갈린다면 [테코톡 영상](https://youtu.be/ogaXW6KPc8I)을 추천드립니다 :)

> 4. CarManager에서 moveCarsRandomly 함수 테스트를 못하겠습니다.

이 부분은 아마 2단계를 진행하시면서 학습하게 될 거 같은데 테스트가 어렵다면 먼저 함수의 단위가 너무 큰 것은 아닌지 고민해보시고, 테스트하고 싶은 부분(혹은 테스트가 가능한 부분)만을 분리해서 단위테스트를 해보시는 건 어떨까요?

2023-02-09 14:48 UTC, xrabcde commented on docs/README.md
> +  - [예외] 0보다 작을 경우 예외 발생
README 를 꼼꼼히 작성해주셨네요 👍 
[체크 박스를 추가](https://jihyehwang09.github.io/2019/05/06/TIL-2019-05-06/)하면 진행상황을 파악하기 더 쉽답니다 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/controller/CarManager.java
> +import java.util.Map;
사용하지 않은 import 문들은 정리해주세요!

```
import racingcar.domain.CarName;
import java.util.Map;
```

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/controller/CarManager.java
> +    private List<Car> cars;
cars 로만 구성된 클래스를 만들어주셨네요 ! 
이 클래스의 위치를 controller에 배치하신 이유가 있을까요? 

> 2.MVC 패턴에서 controller와 model의 역할과 차이

이 질문에 대한 답변이 될 수도 있을 것 같은데 [일급컬렉션](https://jojoldu.tistory.com/412)에 대해 공부해보셔도 좋을 것 같아요 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/controller/CarManager.java
> +                .forEach(car -> car.move(makeRandomCarMove()));
```suggestion
        this.cars.forEach(car -> car.move(makeRandomCarMove()));
```
이렇게 작성할 수도 있겠네요 ! (참고 : [Java 반복문](https://tecoble.techcourse.co.kr/post/2020-08-31-java-loop/))

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/controller/CarManager.java
> +        return new CarMovement(moveCount);
계속해서 `Integer`와 `int`를 혼용해서 사용하고 있는데 두 타입의 차이는 무엇일까요?
아래 글을 읽어보시면 좋을 것 같아요 !

[이펙티브 자바 item 61 - 박싱된 기본 타입보다는 기본 타입을 사용하라](https://jithub.tistory.com/271)

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/controller/RacingGame.java
> +                    .map(name -> new Car(name))
[메서드 참조](https://countryxide.tistory.com/127)를 활용하면 더 깔끔한 코드가 될 것 같아요 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Car.java
> +import java.util.Comparator;
사용하지 않는 import 문이네요!

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Car.java
> +    private final Position pos;
그렇게 길지 않으니 축약하지 않고 `position` 그대로를 네이밍에 사용해도 될 것 같아요

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/CarMovement.java
> +        return false;
```suggestion
        return this.value >= 4;
```
더 간결하게도 가능할 것 같아요 ㅎㅎ

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/CarName.java
> +    }
[Java Code Convention](https://myeonguni.tistory.com/1596) 에서는 `static 변수 > 일반 변수 > 생성자 > 메서드` 순으로 선언하는 것을 권장하고 있어요 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +    private final Integer MOVE_STEP = 1;
상수로 사용하고 싶다면 [접근제어자](https://zorba91.tistory.com/275) 확인해주세요 ! 
(이 클래스뿐 아니라 전체적으로 확인부탁드립니다 🙏🏻)

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +    private Integer value;
멤버 변수를 선언하면서 동시에 초기화 해주는 건 어떤가요~?

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +        this.value += MOVE_STEP;
```suggestion
        this.value ++;
```
이렇게 쓸 수도 있겠네요!

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +        return -1;
`Integer.compare()` 를 이용할 수 있을 것 같아요 

[[이펙티브 자바] 아이템14 | Comparable을 구현할지 고려하라](https://velog.io/@alkwen0996/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C14-Comparable%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%A0%EC%A7%80-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +    }
1. `hashCode`를 오버라이드 하지 않고 `equals`만 오버라이드하면 어떤 문제가 생길 수 있을까요? [이 글](https://wisdom-and-record.tistory.com/114)을 읽어보시면 좋을 것 같아요 !

2. `==` 비교와 `equals` 비교는 어떻게 다를까요?  또 기본 타입(`int`)과 박싱된 타입(`Integer`)에서 각각 어떻게 동작할까요? 전체적으로 데이터 타입 정리하면서 같이 확인해주세요 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/TrialCount.java
> +    private void validate(int value) {
어떤 값을 validate 하는 걸까요? 좀 더 친절한 이름을 지어줘도 좋겠네요 !

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/view/InputView.java
> +    Scanner input = new Scanner(System.in);
접근제어자를 깜빡하신 것 같아요 ~!

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/view/InputView.java
> +        Integer number = Integer.parseInt(input_count);
혼자 스네이크케이스를 쓰고 있는 변수명이 있네요 ㅎㅎ 네이밍 문법을 통일해주세요!

2023-02-09 14:48 UTC, xrabcde commented on src/main/java/racingcar/domain/CarMovement.java
> +        if(value >= 10 || value < 0){
매직넘버가 있네요 🤓

2023-02-09 14:48 UTC, xrabcde commented on src/test/java/domain/CarMovementTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
`hasMessage()` 를 이용하면 예외메시지까지 확인해볼 수 있어요!

2023-02-09 14:48 UTC, xrabcde commented on src/test/java/domain/CarMovementTest.java
> +    @ValueSource(ints = {-1, -2, 30, 40, 50})
예외테스트의 경우 경곗값을 테스트해보면 더 확실한 테스트가 될 수 있어요 !

2023-02-09 14:48 UTC, xrabcde commented on src/test/java/domain/CarNameTest.java
> +        assertThat(testCarName).isInstanceOf(CarName.class);
`예외를 던지지 않는다` 를 테스트하고 싶다면 `assertDoesNotThrow` 를 사용할 수도 있답니당

2023-02-10 11:25 UTC, BGuga reviewed
안녕하세요 바다님!! 너무 좋은 리뷰 감사드립니다ㅎㅎ 특히 같이 참고하라고 주신 글들이 너무 잘 작성된 글이여서 사실상 피드백을 몇 천줄 받은 느낌입니다.. 감사합니다 🙇‍♂️

2023-02-10 11:25 UTC, BGuga commented on src/test/java/domain/CarNameTest.java
> +        assertThat(testCarName).isInstanceOf(CarName.class);
감사합니다!! 이런 메서드 들이 있는지 공부를 더 해야겠습니다😀

2023-02-10 11:25 UTC, BGuga commented on src/test/java/domain/CarMovementTest.java
> +    @ValueSource(ints = {-1, -2, 30, 40, 50})
감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on docs/README.md
> +  - [예외] 0보다 작을 경우 예외 발생
감사합니다! readme가 기능목록을 설명해주는 것 뿐만 아니라 여정표로도 사용할 수 있을거 같아요 ㅎㅎ

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/controller/CarManager.java
> +import java.util.Map;
이런 부분까지 봐주셔서 감사합니다 ㅠㅠ 덕분에 하나하나 바꾸기 귀찮아서 안쓰는 Import문을 제거할 수 있는 단축키를 알게 되었네요

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/controller/CarManager.java
> +    private List<Car> cars;
글을 읽은 뒤 느낀 것이 기본 타입을 포장하는 객체(ex. CarName)처럼 List도 똑같은 장점을 누리기 위해서 포장하는 것 같다는 생각이 드네요!! 만약 리팩터링 한다면 CarManager를 서비스 layer로 분리한뒤 cars만 일급 컬렉션으로 바꾸고 싶은데 이 방향은 괜찮은가요??

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/controller/CarManager.java
> +        return new CarMovement(moveCount);
Integer를 사용하는 것 만으로도 시스템 내에서 발생하는 에러 요소를 늘릴 수 있었네요.. 이런 하나하나를 다 고려해야 한다니 갈 길이 멀구나 싶습니다 😭

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/controller/CarManager.java
> +                .forEach(car -> car.move(makeRandomCarMove()));
감사합니다 ㅠㅠ 덕분에 너무 좋은 메서드 하나 배워갑니다 😆

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/controller/RacingGame.java
> +                    .map(name -> new Car(name))
메서드 참조 관련한 글을 많이 봤는데 이렇게 이해가 잘되도록 좋은 케이스를 둔 글은 못 봤었어요!! 덕분에 메서드 참조에 대한 이해도와 앞으로 친근하게 사용할 수 있을 것 같습니다 ㅎㅎ

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Car.java
> +import java.util.Comparator;
감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Car.java
> +    private final Position pos;
감사합니다 이런 것도 하나의 매직넘버인 것 같네요.. 확실한 의미를 전달할 수 있는 변수명을 고려하면서 코딩해야 겠습니다!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/CarMovement.java
> +        if(value >= 10 || value < 0){
감사합니다!! 매직 넘버가 값의 의미를 확실하게 해준다는 것도 있고 값 객체  장점 중 하나인 변경점을 확실히 해준다는 것도 장점이 될 수 있나요??

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/CarMovement.java
> +        return false;
감사합니다!! 이런 메서드를 짤 때 머리 속에 먼저 떠오르는 대로 손이 먼저 나가네요.. 항상 더 좋은 방법을 생각해보는 습관을 들여야 할 것 같습니다!!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/CarName.java
> +    }
헉.. 이게 왜 이렇게 됐을까나 ...😱

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    private final Integer MOVE_STEP = 1;
생각해보니 final만 붙힌다면 추후에 이 필드를 변경하는 생성자가 생길 수 있었네요.. 감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    private Integer value;
이 부분은 생성자가 여러개가 생길 경우 초기화 값이 여러가지가 될 수 있기 때문인가요??

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +        this.value += MOVE_STEP;
포지션이 증가하는 값에 대해서 조금 더 명시 해주고 싶어서 값을 분리 했었는데 이건 조금 지나친 분리였을까요??

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +        return -1;
감사합니다!! 너무 이해가 잘되는 글이네요 ㅎㅎ

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    }
이런 부분에 디테일이 없다면 당연하다 생각하는 부분에서 에러가 발생해서 고생을 할 수 있겠네요 ㅠㅠ 감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/view/InputView.java
> +    Scanner input = new Scanner(System.in);
앗.. 감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/view/InputView.java
> +        Integer number = Integer.parseInt(input_count);
엇.. 이런 친구가 있는지 놓쳤었네요 감사합니다!!

2023-02-10 11:25 UTC, BGuga commented on src/test/java/domain/CarMovementTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
좀 더 확실한 테스트를 할 수 있겠네요!! 감사합니다

2023-02-10 11:25 UTC, BGuga commented on src/test/java/domain/CarMovementTest.java
> +    @ValueSource(ints = {-1, -2, 30, 40, 50})
경계값이 테스트에서 가장 특별한 값인 것 같네요 앞으로 고려해서 테스트를 짜보겠습니다~!

2023-02-10 11:25 UTC, BGuga commented on src/test/java/domain/CarNameTest.java
> +        assertThat(testCarName).isInstanceOf(CarName.class);
감사합니다!! 너무 좋은 메서드를 많이 배우네요ㅎㅎ

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/TrialCount.java
> +    private void validate(int value) {
감사합니다!! 항상 남이 봐도 이해할 수 있는 명명을 해야겠네요

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +        this.value += MOVE_STEP;
저는 한 단계씩 진행한다는 것을 좀더 명시해주고 싶어서 따로 변수로 분리했던 것 같네요.. 혹시 이 변경은 오버 프로그래밍 관점에서 수정하는게 좋을 까요 아니면 다른 이유가 있을까요??

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    private Integer value;
여러 생성자가 있을 경우 기본 초기화 값이 바뀔 수 있어서 그런 것인가요?.?

2023-02-10 11:25 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    private final Integer MOVE_STEP = 1;
static을 붙히지 않는다면 변경가능성이 열려서 상수라 볼 순 없는 것이였네요 감사합니다!!

2023-02-12 06:11 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +        return -1;
> , < 와 같은 연산자를 쓴다면 null일 경우 에러가 발생해서 그런 것인가요??

2023-02-12 06:23 UTC, BGuga commented on src/main/java/racingcar/domain/Position.java
> +    }
1. equals만 정의한다면 당연히 같다고 처리될 줄 알았던 부분(Ex. Set)에서 의도치 않은 결과를 받을 수 있겠네요!!
2.
wrapped class는 기본 타입 값은 감싼 객체네요!
그렇기 때문에 발생할 수 있는 문제가
1.  래퍼 클래스는 기본 타입과 비교할 때 자동으로 언박싱을 하기 떄문에 null이 될 경우 에러가 발생할 수 있다.
2.  래퍼 클래스 끼리 == 비교를 한다면 주소값으로 비교를 하기 떄문에 예상 밖의 결과 값을 얻을 수 있다.

1번의 에러 발생 실 예시를 든다면
Integer num1 = null;
int num2 = 2;

1번 상황
---
num1.equals(num2) // 예외 발생

2번 상황
---
num1==num2 // 예외 발생

이 있는 것 같습니다.
그렇기 떄문에 Integer를 사용하는 것 만으로도 이런 에러에 대해 고려하는 비용이 발생하기 떄문에 깔끔하게 기본형 타입을 쓰는 것이 좋아 보이네요 ㅎㅎ

2023-02-12 12:44 UTC, xrabcde approved these changes
안녕하세요 푸우 ~ 바다입니다 🌊
피드백 드린 부분을 대부분 반영해주셨네요 !
추가로 몇 가지 코멘트 더 남겼으니 2단계 미션 진행하시면서 같이 반영해주시면 됩니다 ~ 
수고하셨습니다 :) 2단계에서 만나요 ~

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/domain/Car.java
> +            ;
```suggestion
    private final Position position;
```
> 코드 자동 정렬하기 (Reformat Code)
MacOS: Cmd + Opt + l
Win/Linux: Ctrl + Alt + l

[[IntelliJ] intellij 유용한 단축키 정리](https://gmlwjd9405.github.io/2019/05/21/intellij-shortkey.html) 😉

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/domain/Car.java
> +
Car 안에 CarManager 를 static class로 생성하신 이유가 있나요? 
리팩터링 과정 중에 잘못 들어간 것 같은데 확인부탁드립니다 🙏🏻

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/domain/CarMovement.java
> +    public static final int MIN_VALUE = 0;
접근제어자를 잘 수정해주셨는데 이 친구만 실수하신 것 같아요!

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/domain/CarMovement.java
> +            throw new IllegalArgumentException(OUT_OF_MOVEMENT_RANGE_EXCEPTION);
매직넘버를 상수로 잘 선언해주셨네요 👍🏻
이렇게 하면 네이밍을 통해 어떤 역할을 하는지 드러낼 수도 있고 여러 번 사용하는 값일 경우 유지보수에도 수월해져요 :)

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/domain/CarMovement.java
> +        return this.value >= 4;
매직넘버가 아직 남았네요 🧐

2023-02-12 12:44 UTC, xrabcde commented on src/main/java/racingcar/view/InputView.java
> +        return new TrialCount(number);
시도 횟수를 숫자가 아닌 다른 형태의 값으로 입력하면 어떻게 될까요? 
RacingGame에서 try-catch를 통해 핸들링은 되고 있지만 더 친절한 예외메시지를 주면 좋을 것 같아요

2023-02-12 12:44 UTC, xrabcde commented on src/test/java/domain/CarNameTest.java
> +        });
```suggestion
       assertDoesNotThrow(()-> {
            new CarName(carName);
        });
```

👍🏻👍🏻

2023-02-12 12:44 UTC, xrabcde commented on src/test/java/domain/PositionTest.java
> +        assertThat(Collections.max(poses).equals(expected)).isTrue();
```suggestion
        assertThat(Collections.max(poses)).isEqualTo(expected);
```

🤓

2023-02-12 12:46 UTC, xrabcde commented on src/main/java/racingcar/controller/CarManager.java
> +    private List<Car> cars;
네 푸우가 이해하신 내용이 맞아요 :)
설계에 정답은 없으니 푸우가 생각했을 때 책임이 잘 분리된 것 같다면 그대로 진행해주시면 됩니다 ~

2023-02-12 12:48 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +    private Integer value;
초기값이 여러가지가 되는 것이 프로그램의 요구사항이라면 문제가 되는 것은 아닌데요 ㅎㅎ
현재 미션에서는 초기값이 항상 같기 때문에 선언하면서 초기화해줘도 될 것 같아요 ~

2023-02-12 12:49 UTC, xrabcde commented on src/main/java/racingcar/domain/Position.java
> +        this.value += MOVE_STEP;
상수의 접근제어자만 잘 작성해주신다면 증가하는 값을 명시해주는 것도 물론 좋은 방법입니다 ! 👍🏻

2023-02-12 12:51 UTC, merged

2023-02-12 14:12 UTC, BGuga commented on src/main/java/racingcar/domain/Car.java
> +
이것을 수정한 commit이 있었는데 누락하였던 것 같습니다 ㅠㅠ 확인을 잘했어야 하는데 바로 적용하겠습니다!

2023-02-12 14:13 UTC, BGuga commented on src/main/java/racingcar/domain/Car.java
> +            ;
감사합니다 마지막에 꼭 한번 정리를 해야겠네요

2023-02-12 15:39 UTC, BGuga commented on src/main/java/racingcar/view/InputView.java
> +        return new TrialCount(number);
기존 코드의 경우 NumberFormat 예외이기 때문에 핸들링이 되지 않았던 것 아닌가요??🤔
그래서 저는 NumberFormat 예외가 발생하면 IllegalArgument 예외를 발생시키도록 변경했는데 혹시 그냥 NumberFormat 에러를 catch하는 것이 더 좋았을까요??

2023-02-12 15:43 UTC, BGuga commented on src/main/java/racingcar/domain/CarMovement.java
> +    public static final int MIN_VALUE = 0;
왜 이렇게 했는지 생각해보니 intellij 의 psfi 단축키로 쓰다보니 이렇게 된 것 같습니다!

2023-02-12 15:44 UTC, BGuga commented on src/main/java/racingcar/domain/CarMovement.java
> +        return this.value >= 4;
발견한 매직넘버를 모두 제거 했습니다!

2023-02-12 15:44 UTC, BGuga commented on src/test/java/domain/CarNameTest.java
> +        });
하나의 메서드만 있어서 static import를 사용하지 않았는데 하나만 쓰더라도 꼭 쓰는 습관을 들여야 겠네요 ㅎㅎ

2023-02-12 15:45 UTC, BGuga commented on src/test/java/domain/PositionTest.java
> +        assertThat(Collections.max(poses).equals(expected)).isTrue();
이런 좋은 방법이 있어도 항상 먼저 생각나는대로 먼저 움직이는 것 같아요 ㅠㅠ 항상 좋은 방법을 생각하며 코딩하겠습니다!

2023-02-13 06:33 UTC, xrabcde commented on src/main/java/racingcar/view/InputView.java
> +        return new TrialCount(number);
NumberFormatException이 IllegalArgumentException을 상속했기 때문에 기존에도 핸들링은 되었을거에요 
```
```