[1단계 - 자동차 경주 구현] 도기(김동호) 미션 제출합니다.
woowacourse/java-racingcar pull request #506
Opened 2023-02-09 08:04 UTC by kdkdhoho

안녕하세요. BE 5기 도기입니다 😀
난생처음 페어 프로그래밍을 해보았는데, 생각했던 거보다 굉장히 힘든 작업이네요.. 그럼 잘 부탁드립니다 🙇‍♂️

몇 가지 궁금한 점이 있습니다.
0에서 9 사이의 난수 생성을 통해 자동차를 움직이는 로직을 테스트하기 위해 인터페이스 `NumberGenerator`를 만들었습니다.
이를 이용하여 프로덕트 코드를 위해 `RandomNumberGenerator`를, 테스트 코드를 위해서는 `FixedNumberGenerator`를 만들어 사용했습니다.
그런데, 어디선가 테스트를 위해 코드를 새롭게 추가해서는 안된다고 들었던 기억이 있어 의문이 들었습니다.

그리고 일부 로직의 테스트 필요성에 대해 의문이 들었습니다.
예를 들어, 랜덤값을 생성하는 로직이 해당할 거 같아요.
테스트를 해야하는 로직, 그렇지 않은 로직을 구분하는 기준이 있을까요?

2023-02-09 10:09 UTC, choijy1705 requested changes
안녕하세요 도기 
첫번째 미션 진행하시느라 고생 많으셨어요!
질문에 대한 답과 몇가지 피드백 남겼어요

2023-02-09 10:09 UTC, choijy1705 commented on docs/README.md
> +# 프로그램 규칙
docs 파일에 새롭게 readme 를 추가하는것보다는 기존의 readme 에 작성하는게 더 좋을것 같아요
다른 사람들에게 보여지는건 결국 상단에 있는 README가 보여져서요

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/controller/RacingCarController.java
> +        return carGroup;
변수로 별다른 작업이 없으면 인라인 해주면 좋을것 같아요
```suggestion
        return new CarGroup(carNames);
```

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/Application.java
> +        controller.run(new RandomNumberGenerator());
랜덤 숫자를 생성하는 클래스를 여기서 생성할 필요가 있을까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/controller/RacingCarController.java
> +    }
메서드명이 너무 세부적으로 표현해서 오히려 더 이해하기 어려운것 같아요
자동차 게임에 대해 알지 못하는 사람은 moveCar하고 view는 뭐하는거지 라는 생각이 들지 않을까요?
좀더 일반적인 네이밍은 어떤가요? (ex. racingCar, playRacing 등등)

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/domain/Car.java
> +    private Position position;
👍

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/domain/Car.java
> +        }
carName 이 null 이라면 어떻게 될까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/domain/CarGroup.java
> +    List<Car> carGroup;
보통은 Car를 모아둔 collection을 포함할때 네이밍은 cars라고 할것 같아요.

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/domain/CarGroup.java
> +                .orElseThrow(() -> new IllegalArgumentException())
에러에대한 메세지가 없네요!

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/util/FixedNumberGenerator.java
> +public class FixedNumberGenerator implements NumberGenerator {
이부분이 질문주신 테스트를 위해서 만든 클래스인것 같네요
저는 가급적이면 테스트를 위한 클래스는 만들지 않으려고합니다. 
그리고 만약 정말 필요하다면 main 쪽이 아닌 test 쪽에서 클래스를 만들어서 테스트를 진행했어요

지금 같은 경우는 굳이 이 클래스를 만들필요가 없을것 같아요.
테스트를 하기 어렵다면 구조를 먼저 바꿀필요가 없을지에 대해 고민해보면 좋을 것 같습니다

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/util/NumberGenerator.java
> +public interface NumberGenerator {
테스트를 위한 FixedNumberGenerator가 필요없다면 
굳이 interface로 생성하지 않아도 되겠네요

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/util/RandomNumberGenerator.java
> +    }
min, max를 상수로 두지 않고 파라미터로 받아서 유연하게 랜덤 숫자를 생성하도록 하는건 어떨까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/view/InputView.java
> +                .collect(Collectors.toList());
좀 더 간략하게 표현해볼 수 없을까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/main/java/racingCar/view/InputView.java
> +    private static void validateEmpty(String[] carNames) throws IllegalArgumentException {
thorws 를 명시할 필요가 있을까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarGroupTest.java
> +    @BeforeEach
```suggestion
    private CarGroup carGroup;
    
    @BeforeEach
```

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarGroupTest.java
> +        Assertions.assertThat(count).isEqualTo(0);
자동차가 0~3의 숫자를 받았을때 이동하는 관심사는
carGroup에 있나요 car에 있나요?
car에서 move하는 것을 테스트한다면
여기서는 필요없지 않을까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarTest.java
> +    }
여기에 잘 작성해주셨네요👍
그렇다면 carGroup 에서 3이하일때 안움직이고 4이상일때 움직이는 로직은 테스트 할 필요가 없을 것 같은데
어떻게 생각하시나요?

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarTest.java
> +}
```suggestion
}

```

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarTest.java
> +}
마지막은 띄어주세요!

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/study/SetCollectionTest.java
> +        assertThat(size).isEqualTo(3);
직접 작성하신 메서드가 아닌 
외부라이브러리의 기능을 굳이 test 할 필요가 있을까요?

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/util/RandomNumberGeneratorTest.java
> +    }
displayName에는 과 실제 검증하는 내용이 맞는건가요??

2023-02-09 10:09 UTC, choijy1705 commented on src/test/java/racingCar/util/RandomNumberGeneratorTest.java
> +    }
테스트를 해야하는 로직, 아닌 로직을 정하기는 어려울것 같아요.
랜덤 함수는 특히나 더 테스트를 하기 어렵겠죠. 
랜덤 숫자를 생성할때 Math.random 을 사용하셨는데 본인이 직접 랜덤수를 구현한게 아니기 때문에 여기에 대해서는 굳이 할 필요가 없지않을까요??
라이브러리를 못믿고 테스트를 하게되면 수많은 모든 기능들을 다 테스트해야할 것 같아요.
작성하신 메서드중 가장 작은 단위를 먼저 테스트하고 
그 위에 레벨에서만 테스트 할 수밖에 없는 것들을 테스트 해보면 어떨까요?

테스트에 대한 정답은 없는것 같아요. 기능이 변경되었을때 본인이 테스트가 통과하면 잘 구현했다고 믿을 수 있다면 잘 짠 테스트일것 같은데 요것도 제 생각입니다🙏

2023-02-09 13:24 UTC, kdkdhoho commented on src/main/java/racingCar/Application.java
> +        controller.run(new RandomNumberGenerator());
처음 페어와 의논할 때는, Controller 내부에 `NumberGenerator` 인스턴스를 선언하자고 하였습니다. 하지만 Controller가 `NumberGenerator`를 의존하는 것이 옳지 않다고 판단하여 main 함수에서 생성하도록 구현하였습니다.

지금 생각했을 땐, Controller 내부에서 `moveCarsAndView(new RandomNumberGenerator(), tryCount, carGroup)` 이렇게 해주는 게 main에서 선언해 주는 거보다 나은 방법이라고 생각되는데 맞을까요??

2023-02-09 13:45 UTC, kdkdhoho commented on src/main/java/racingCar/domain/Car.java
> +        }
말씀하신 null은 **아무 값이 들어오지 않는 경우** 라고 이해했습니다. 만약 틀리다면 말씀해주세요!
만약, 아무런 값이 들어오지 않는 경우에는 1차적으로 InputView에서 검증하도록 구현하였습니다.

2023-02-09 13:50 UTC, kdkdhoho commented on src/main/java/racingCar/util/RandomNumberGenerator.java
> +    }
`NumberGenerator`에 대한 구조적인 변경이 필요할 것 같습니다. 내일 리팩터링 시 참고해서 수정하겠습니다 😀

2023-02-09 13:52 UTC, kdkdhoho commented on src/test/java/racingCar/domain/CarGroupTest.java
> +        Assertions.assertThat(count).isEqualTo(0);
자동차가 0~3의 숫자를 받았을 때 이동하는 관심사는 아무래도 `Car`에 있다고 생각됩니다.
말씀하신 대로 테스트의 중복이 일어났네요. 수정하겠습니다!

2023-02-09 13:56 UTC, kdkdhoho commented on src/test/java/racingCar/domain/CarTest.java
> +}
클래스의 맨 마지막 중괄호 다음 개행을 넣으라는 말씀이신 거죠?
혹시 이유를 알 수 있을까요??

2023-02-09 13:57 UTC, kdkdhoho commented on src/test/java/study/SetCollectionTest.java
> +        assertThat(size).isEqualTo(3);
**학습테스트를 통한 JUnit 학습하기**에서 요구사항 1번을 충족시키기 위한 테스트 코드입니다 !

2023-02-10 09:59 UTC, kdkdhoho commented on src/test/java/racingCar/domain/CarTest.java
> +}
이유에 대해 파악하였습니다!

2023-02-10 10:53 UTC, kdkdhoho commented
안녕하세요 리뷰어 준 😀
남겨주신 질문에 대한 답변과 피드백들 모두 잘 보았습니다.
페어 프로그래밍 중 찝찝함이 있었던 부분들을 모두 짚어주셔서 정말 놀랐습니다..!
남겨주신 피드백과 개인적인 생각으로 리팩터링 해보았어요! 이번에도 잘 부탁드립니다 😄

추가로 또 질문드리고 싶습니다!
1. 이번 미션에서 페어와 상의하에 View를 모두 static으로 구현했습니다. 개인적으로 static은 객체지향과 거리가 있는 구현 방식으로 알고 있어서 잘 사용하지 않으려고 하는데요. 혹시 리뷰어님은 View를 static으로 구현한 것에 대해 어떻게 평가하시는지 궁금합니다.
2. Position과 CarName과 같은 Wrapper 클래스는 패키지 상에서 Domain에 포함시키면 적절할까요? 그렇지 않다면 따로 어디에 관리하는 것이 좋을까요?

2023-02-10 16:32 UTC, choijy1705 approved these changes
1단계 미션 진행하느라 고생하셨어요
질문에 대한 답변과 간단한 코멘트 남겼는데
2단계 진행하면서 반영해주세요
1단계는 머지할께요!

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/domain/Car.java
> +        }
InputView에서의 검증이 있다하더라도
나중에 Car 객체를 Input이 아닌 곳에서 생성하는 경우가 생길 수도 있을거 같습니다
그렇다면 InputView 검증과 별개로 null 값으로 생성될 수 있을것 같아요
그리고 Car 클래스에서 validate 로직에 null 체크가 들어있다면 다른사람이 봤을때
Car에는 null 이 들어가면 안되겠구나 생각할 수도 있을것 같아요

null은 아무값이 없는 경우가 맞지만 개발하다 보면 항상 예기치 못한곳에서 NullPointerException이 발생해서 항상 신경써주는 습관을 가지면 좋을것 같습니다!

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/Application.java
> +        controller.run(new RandomNumberGenerator());
요건 맞고 틀리고 정답이 없는 문제일거 같아요
다만 실제 랜덤숫자를 생성하는 로직은 cars 클래스에서 쓰이는데 
RandomNumberGenerator에 변경이 있다면 상위부터 변경해줘야하는 번거로움이 있을 수 있겠네요

저라면 랜덤숫자를 생성하는 로직은 별도의 util 클래스를 만들어서 사용할 것 같아요
static 메서드를 통하여 랜덤숫자를 생성로직을 만들어 놓으면 언제든지 호출해서 사용할 수 있어서요

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/controller/RacingCarController.java
> +        Integer tryCount = repeat(InputView::readTryCount);
int가 아닌 Integer를 사용한 이유가 있을까요?

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/domain/Car.java
> +    public boolean isSamePosition(int other) {
other 보다 좀 더 명확한 이름이면 좋을것 같아요
otherPosition 정도?

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/domain/Car.java
> +    public void move(int randomNumber) {
randomNumbe라는 명칭도 항상 randomNumber만을 강제하는 느낌이네요
굳이 여기서는 randomNumber라고 명시 안해도 되지않을까요?

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/dto/CarDto.java
> +        }
```java
stringBuilder.append(name + " : " + "-".repeat(position.getPosition());
```
요렇게도 쓸수있겠네요

2023-02-10 16:32 UTC, choijy1705 commented on src/main/java/racingCar/util/NumberPicker.java
> +    }
util 클래스 만들어주셨네요👍
static 메서드로 해서 
생성자를 통하지 않고 바로 호출하여 사용해도 좋을것 같아요

2023-02-10 16:32 UTC, choijy1705 commented on src/test/java/racingCar/domain/CarNameTest.java
> +        assertThatIllegalArgumentException().isThrownBy(() -> {
이런것도 있군요
하나 배워갑니다🙏

2023-02-10 16:32 UTC, merged

2023-02-11 01:56 UTC, kdkdhoho commented on src/main/java/racingCar/domain/Car.java
> +    public void move(int randomNumber) {
네 저도 randomNumber가 적절할까? 에 대해 고민을 해봤습니다.
이에 대한 제 생각은 만약 Car 객체가 다른 요소로 인해 move 하게 된다면, 그때는 오버로딩으로 구현하면 되지 않을까는 생각에 이렇게 두었습니다.

1단계 리팩터링 강의 때 네오가 이 부분을 power로 명명하였는데 power 같은 변수명으로 변경할 걸 그랬어요🤣

2023-02-11 01:58 UTC, kdkdhoho commented on src/main/java/racingCar/dto/CarDto.java
> +        }
repeat이라는 메서드가 있었군요..! 감사합니다!

2023-02-11 02:02 UTC, kdkdhoho commented on src/main/java/racingCar/controller/RacingCarController.java
> +        Integer tryCount = repeat(InputView::readTryCount);
타입 관련 API를 사용할 일을 대비해 사용한다는 페어의 개발 습관으로 인해 사용되었어요!