[1단계 - 자동차 경주 구현] 아마란스(송세연) 미션 제출합니다.
woowacourse/java-racingcar pull request #512
Opened 2023-02-09 08:17 UTC by amaran-th

2023-02-09 10:49 UTC, choijy1705 requested changes
안녕하세요 아마란스
첫번째 미션 하시느라 고생하셨어요!
질문에 대한 답변과 몇가지 리뷰 남겼습니다!

2023-02-09 10:49 UTC, choijy1705 commented on docs/README.md
> +- 경주할 자동차 이름을 입력받는다
[ ] 를 활용해서 진행한것들에 대해서 체크해보면 좋을것 같아요

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/contoller/RaceController.java
> +  private <T> T repeat(Supplier<T> inputReader){
접근 제어자가 public인 메서드가 더 상위에 있는게 보기 좋을것 같아요

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/view/InputView.java
> +    System.out.println(Messages.INPUT_CAR_NAMES);
별도의 클래스로 만들어 관리할지 아닐지에 대한 것은 정답은 없는것 같아요

개인적으로는 이렇게 작성하게 된다면 매번 클래스를 왔다갔다해서 번거로울것 같아요.
여러 클래스에서 공통적으로 사용하는 메세지의 경우 별도의 클래스로 관리하면 더 좋겠지만 사용빈도가 낮은 경우는 사용하는 클래스에서 선언해주는게 어떨까요?

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/domain/Car.java
> +  private int position = 1;
position 이 항상 처음은 1이더라도 생성자를 통해서 초기화 해주면 좋을것 같아요

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/util/RandomUtil.java
> +  private static Random random=new Random();
```suggestion
  private static Random random = new Random();
```

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/view/InputView.java
> +      throw new IllegalArgumentException(Messages.ERROR_CAR_NAME_LENGTH);
에러 메세지의 경우 다른곳에서 쓰일 일도 거의 없고
코드를 읽는 가독성 측면에서도
별도의 상수로 안빼고 바로 적는것도 좋을것 같아요
물론 제 개인적인 생각입니다

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +}
```suggestion
}

```
마지막 라인은 항상 한칸 띄어주세요

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +  }
위에 scanner.nextLine() 과 마찬가지로 굳이 잘알려진 기능을 
메서드로 한번 감쌀필요가 있을까라는 생각이 듭니다

2023-02-09 10:49 UTC, choijy1705 commented on src/test/java/domain/CarTest.java
> +    Car car2=new Car("car2");
```suggestion
    Car car2 = new Car("car2");
```
맥북이시라면 cmd + option +  l 을 통해서 컨벤션 정리가 되는데 
한번씩 해보면 좋을것 같습니다
구글링해보면 intellij 기본 설정으로도 할 수 있을거에요

2023-02-09 10:49 UTC, choijy1705 commented on src/test/java/view/OutputViewTest.java
> +class OutputViewTest {
단순히 view를 출력하는 건 테스트로 어떤 의미가 있는지에 생각해보면 좋을것 같아요

2023-02-09 10:49 UTC, choijy1705 commented on src/test/java/study/StringTest.java
> +
```suggestion
```

2023-02-09 10:49 UTC, choijy1705 commented on src/main/java/view/InputView.java
> +    System.out.println(Messages.INPUT_CAR_NAMES);
주석을 따로 작성하신곳은 없네요
주석 관련 질문을 주셔서 답변 하자면
주석은 가능하면 안적고 이해할 수 있도록 작성하는게 가장 베스트일것 같아요.
주석은 코드보다 아무래도 최신으로 관리되기 어렵고 실제 코드와 내용이 달라져도 이를 수정안해주면 에러가 따로 발생하지 않기 때문에 계속 모르다가 큰 문제가 발생할 수 있을것 같습니다

우테코 기간동안은 가능한 주석을 사용하지 않고 
메서드 네이밍등과 같은 방법으로 코드를 이해하기 쉽게 작성하는게 좋을것 같아요
테스트 코드도 다른 사람들이 쉽게 코드를 이해할수 있도록 하는 좋은 방법이라고 생각합니다

2023-02-10 00:56 UTC, amaran-th commented on docs/README.md
> +- 경주할 자동차 이름을 입력받는다
안녕하세요! 리뷰 감사합니다.
저희가 개발 과정 중에는 TODO 형식으로 정리해서 하나씩 체크하다가, 모든 기능 구현이 완료된 후에 보기 좋게 하려고평범한 리스트 형식으로 수정하였는데요, TODO 형식을 그대로 남겨 놓는 게 좋을까요?

2023-02-10 06:20 UTC, choijy1705 approved these changes
아마란스 1단계 진행하시느라 고생하셨습니다.
간단한 코멘트 남겼는데 2단계 진행하시면서 챙겨봐주세요!
merge하겠습니다!

2023-02-10 06:20 UTC, choijy1705 commented on docs/README.md
> +- 경주할 자동차 이름을 입력받는다
작성한 문서를 본인이 잘이해하고 남이 봐도 잘 파악이 된다면 
문제 없을것 같아요
TODO 형식은 본인이 체크를 하기 위한 용도니까 확인을 다하셨다면 상관없을것 같아요

2023-02-10 06:20 UTC, choijy1705 commented on src/main/java/view/Messages.java
> + */
이부분은 어떤의되일까요?

2023-02-10 06:20 UTC, choijy1705 commented on src/test/java/domain/CarTest.java
> +}
마지막 개행 챙겨주세요!
https://medium.com/sjk5766/git-no-newline-at-end-of-file-41cebe40bbb5

2023-02-10 06:20 UTC, choijy1705 commented on src/main/java/contoller/RaceController.java
> +    List<String> winnerNames = cars.stream().sorted()
정렬을 할 필요가 있나요??

2023-02-10 06:21 UTC, merged

2023-02-10 07:34 UTC, amaran-th commented on src/main/java/view/Messages.java
> + */
앗 풀리퀘로 올렸던 질문을 쓰면서 적었다가 실수로 남겨둔 것 같습니다! 2단계 진행하면서 지우겠습니다~~