[1단계 - 자동차 경주 구현] 레오(차영호) 미션 제출합니다.
woowacourse/java-racingcar pull request #514
Opened 2023-02-09 08:20 UTC by youngh0

안녕하세요 우아한테크코스 5기 백엔드 크루 레오입니다.

잘 부탁드립니다!!

이번 미션을 진행하면서 궁금했던 점들이 있습니다.

### view와 domain의 관계

이번 미션에서 inputView는 사용자의 입력을 받아 이를 자바의 collection혹은 String등 자바에서 제공하는 타입으로 변환 후 반환했습니다. 그 이유는 MVC패턴에서 view와 model은 서로 의존관계가 없다고 알고 있기 때문입니다. 

위 방식대로 했을 때 제가 생각하는 문제점은 controller에서 동시에 객체를 생성하고 사용한다는 점입니다. 그래서 이를 해결하는 방법으로는 view에서 domain객체를 반환한다면 controller는 domain객체를 생성하는 책임을 덜고, 사용하는 책임만 수행한다고 생각합니다.

그래서 view에서 domain객체를 생성하는 것도 괜찮다고 생각하시는지 궁금합니다!

### public, private메서드의 위치

캡슐화를 위해 객체는 구체적인 행위는 private으로 내부에 숨긴다고 알고 있습니다. 

그렇다면 public메서드를 위한 private메서드의 위치는 관련 public메서드와 붙어있는것도 가독성에 좋다는 생각이 들었습니다. 이에 대해서 어떻게 생각하시는지 궁금합니다!

```java
aPucliMethod()
aPrivateMethod()
bPucliMethod()
bPrivateMethod()
```

```java
aPucliMethod()
bPucliMethod()
aPrivateMethod()
bPrivateMethod()
```

### 상수 관리

OutputView에서 다양한 출력 메시지, delimiter들을 모든 멤버변수로 정의했습니다. 이렇게 작성하니 서비스가 보다 커질 경우 너무 많은 멤버변수가 발생될 거 같다는 생각을 했습니다.

그렇다면 이러한 상수들을 관련성이 있는 **상수들끼리 Enum혹은 class로 분리해 관리하는 방법** 혹은 **여러 개의 outputView를 생성하는 방법**이 있다고 생각했습니다. 이에 대해 어떻게 생각하시는지 궁급합니다!

예를 들어 게임 결과와 관련된 상수들끼리 묶고, 게임 진행에 관련된 상수끼리 묶는 방법입니다.

### 일관성에 관한 trade-off

현재 출력에 관한 모든걸 outputView에서 관리하게 하고 있습니다. 그러나 이렇게 하니 “실행 결과” 5글자를 출력하기 위해 output View에서 별도의 함수로 작성하게 됐습니다.

고민 끝에, 일관성을 위해 별도의 함수로 추출하게 됐습니다.

단순히 print하는 것보다 함수를 호출하는 것이 비용이 더 들지만 일관성을 위한 선택이었습니다. 이와 같은 상황에서 선배님은 어떤 선택을 하셨을지 궁금합니다!

2023-02-09 13:54 UTC, Laterality requested changes
안녕하세요 레오, 리뷰어 에단입니다.

첫 미션 잘 구현해주셨어요 👍 

몇가지 코멘트 남겨드렸으니 확인 부탁드려요.

궁금하신 점은 언제든 DM 주세요 :)

## Q&A

1. view와 domain의 관계
    컨트롤러가 도메인 객체를 생성하고 사용하는 것이 왜 문제라고 생각하시나요?
    반약 컨트롤러가 뷰에서 생성된 도메인 객체를 사용하는 방식으로 바꾼다면, 모델(도메인), 뷰, 컨트롤러의 의존 관계는 어떻게 될까요?
2. public, private 메서드의 위치
    코드를 작성하는 방법에 관해서는 엄격하게 정해진 규칙이 없기 때문에 가장 중요한 건 일관성이라고 생각해요. 일관된 방법으로 작성된 코드라면 의도적으로 읽기 어렵게 작성하지 않는 이상 이해하는 데 큰 어려움은 없을 거라 생각합니다. 말씀하신 형태도 좋고요.
3. 상수 관리
    상수들만 모은 클래스를 만들면 어떤 이점이 있을까요?
4. 일관성에 관한 trade-off
    무엇을 얻고 무엇을 버렸는지, 얻은 것은 버린 것 이상의 가치가 있었는지 고민해보시면 원하시던 답을 찾으실 수 있을 것 같아요 :)

2023-02-09 13:54 UTC, Laterality commented on src/main/java/domain/CarsInfo.java
> +public class CarsInfo {
일반적으로 `Info`나 `Data`와 같은 단어는 이름에서 의미 있는 역할을 하는 경우가 매우 드뭅니다. (참고. 클린코드 p.26)

이 경우도 마찬가지로 이름에서 `Info`를 제거해도 이름의 의미하는 바는 별 차이가 없는데요.

짧고 간결한 이름을 사용하면 어떨까요?

2023-02-09 13:54 UTC, Laterality commented on src/main/java/domain/CarsInfo.java
> +                orElseThrow(NoSuchFieldError::new);
`.orElseThrow`처럼 점 연산자(`.`)와 메서드명은 한 줄에 쓰면 어떨까요([참고](https://google.github.io/styleguide/javaguide.html#s4.5.1-line-wrapping-where-to-break))?

2023-02-09 13:54 UTC, Laterality commented on src/main/java/domain/CarsInfo.java
> +        return Collections.unmodifiableList(carsInfo);
외부에서 내부의 `carsInfo`의 요소에 접근할 수 있게 되는데요. `carsInfo`의 상태가 의도치 않게 변할 수 있지 않을까요?

2023-02-09 13:54 UTC, Laterality commented on src/main/java/util/Validator.java
> +    public static void validateMovingCountInput(String input) {
메서드 이름으로 미루어보아 "이동 횟수"라는 구체적인 역할에 쓰이는 메서드로 보이는데요. `util` 패키지에 두기 적당할까요?

2023-02-09 13:54 UTC, Laterality commented on src/main/java/util/Validator.java
> +        if (count < 1) {
이 매직 넘버도 상수로 선언하면 어떨까요?

2023-02-09 13:54 UTC, Laterality commented on src/main/java/view/OutputView.java
> +}
파일 끝에는 빈 줄을 추가해주세요. IDE 설정이 도움이 될 거에요([참고](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)).

2023-02-09 13:54 UTC, Laterality commented on src/test/java/domain/MovingCountTest.java
> +    void validateCountRangeTest() {
`validate`는 의미하는 바가 너무 포괄적이네요. 더 구체적인 이름으로 무엇을 테스트하는지 나타내면 어떨까요?

2023-02-10 09:20 UTC, youngh0 commented
> 안녕하세요 레오, 리뷰어 에단입니다.
> 
> 첫 미션 잘 구현해주셨어요 👍
> 
> 몇가지 코멘트 남겨드렸으니 확인 부탁드려요.
> 
> 궁금하신 점은 언제든 DM 주세요 :)
> 
> ## Q&A
> 1. view와 domain의 관계
>    컨트롤러가 도메인 객체를 생성하고 사용하는 것이 왜 문제라고 생각하시나요?
>    반약 컨트롤러가 뷰에서 생성된 도메인 객체를 사용하는 방식으로 바꾼다면, 모델(도메인), 뷰, 컨트롤러의 의존 관계는 어떻게 될까요?
> 2. public, private 메서드의 위치
>    코드를 작성하는 방법에 관해서는 엄격하게 정해진 규칙이 없기 때문에 가장 중요한 건 일관성이라고 생각해요. 일관된 방법으로 작성된 코드라면 의도적으로 읽기 어렵게 작성하지 않는 이상 이해하는 데 큰 어려움은 없을 거라 생각합니다. 말씀하신 형태도 좋고요.
> 3. 상수 관리
>    상수들만 모은 클래스를 만들면 어떤 이점이 있을까요?
> 4. 일관성에 관한 trade-off
>    무엇을 얻고 무엇을 버렸는지, 얻은 것은 버린 것 이상의 가치가 있었는지 고민해보시면 원하시던 답을 찾으실 수 있을 것 같아요 :)

1. 1 컨트롤러에서 도메인 객체를 생성하고 사용하는 것이 문제라고 생각한 이유
만약 도메인 객체 형식에 변화가 생겨 생성자 코드에 수정이 생길 경우 controller도 수정해야하는 필요가 있다고 생각해 controller에서 동시에 도메인 객체를 생성하고 사용하는 경우 문제가 있다고 생각했습니다.
그러나 다시 생각해보니 도메인 객체를 생성을 view에 작성할 경우 controller가 아닌 view를 수정해야 하는 문제점이 동일하게 발생될 거 같습니다. 그래서 객체의 생성을 담당하는 팩토리 패턴에 대해 조금 더 공부해봐야 할 거 같습니다.

1.2 view에서 도메인 객체를 생성할 경우 의존관계
만약 view에서 도메인 객체를 생성할 경우 view와 모델 사이에 의존관계가 발생하기 때문에 올바르지 않다는 생각을 했습니다.

3 상수관리
상수들을 모아서 관리할 경우 관련성 있는 상수들이 하나의 파일에 있기 때문에 추후 유지보수성이 조금은 향상되지 않을까 생각됩니다.
계속 생각해봤는데 이 정도의 이점만 생각이 나지 않습니다...

2023-02-10 09:25 UTC, youngh0 commented on src/test/java/domain/MovingCountTest.java
> +    void validateCountRangeTest() {
다시 보니 너무 추상적인 테스트인 거 같습니다!

2023-02-10 09:25 UTC, youngh0 commented on src/main/java/view/OutputView.java
> +}
전혀 몰랐던 컨벤션인데 알려주셔서 감사합니다!

2023-02-10 09:25 UTC, youngh0 commented on src/main/java/domain/CarsInfo.java
> +        return Collections.unmodifiableList(carsInfo);
해당 코드가 복사된 리스트가 반환되는줄 알았는데 추가적으로 찾아보니 참조값이 반환되는걸 알았습니다!

실제로 저 코드대로라면 원본 데이터가 변할 경우 반환된 데이터도 같이 수정되는 문제점이 있을 거 같아요!

2023-02-10 09:25 UTC, youngh0 commented on src/main/java/domain/CarsInfo.java
> +                orElseThrow(NoSuchFieldError::new);
이 부분은 꼼꼼하게 챙기지 못한 거 같아요! 감사합니다!!

2023-02-10 09:25 UTC, youngh0 commented on src/main/java/domain/CarsInfo.java
> +public class CarsInfo {
페이지 까지 알려주셔서 감사합니다! Cars라는 이름도 충분히 의미를 나타낼 수 있는거 같습니다.

2023-02-10 09:27 UTC, youngh0 commented on src/main/java/util/Validator.java
> +    public static void validateMovingCountInput(String input) {
별도의 유효성 검사를 위한 클래스라고 생각해 util패키지에 작성했습니다.

별도의 유효성 검사 클래스를 작성한 이유는 view에서 유효성 검사까지 하게 되면 입력 받는 책임, 유효성 검사 책임을 지게 된다고 생각해 이를 분리한것입니다.

그러나 다시 생각해보니 입력값을 알고 있는 클래스가 view이기 때문에 관련 유효성 검사도 view에서 진행하는 방법도 괜찮다는 생각이 들었습니다. 혹시 이 부분에 대해 어떻게 생각하시는지 궁금합니다!!

2023-02-10 13:17 UTC, Laterality approved these changes
안녕하세요 레오,

피드백 잘 반영해주셨습니다.

이번 단계는 이만 머지하도록 할게요.

남겨드린 코멘트는 다음 단계에서 참고해주세요.

고생 많으셨습니다 :)

## Q&A

1. 상수 관리
    a. '유지보수성'이란 무엇일까요? 상수를 모아두는 것이 어떤 상황에서 이점으로 작용하게 될까요?
    b. 다소 극단적인 예를 들어서, 50 개의 도메인 클래스가 사용하는 서로 다른 상수 100개를 한 클래스에 모아둔다면 이것이 a.에서 정의한 유지보수성의 향상으로 이어질까요?

2023-02-10 13:17 UTC, Laterality commented on src/main/java/util/Validator.java
> +    public static void validateMovingCountInput(String input) {
일반적으로 util과 같은 패키지나 이곳에 두는 클래스는 특정한 "영역"의 관심사를 반영하지는 않습니다. 특정 자료 구조나 알고리즘과 같이 코드 전역에서 쓰이는 매우 추상적인 기능들이 위치하는 게 바람직해요. 각종 자료 구조나 알고리즘 구현, I/O 관련 작업 등을 제공하는 [Guava](https://github.com/google/guava) 라이브러리가 좋은 예가 될 수 있겠네요.

유효성 검사, 특히 특정한 패턴(글자의 수, 형식 등)이 이미 정해져서 이를 검증하는 기능이라면 이 메서드에는 view가 됐든 domain이 됐든 특정 영역의 관심사가 이미 반영된 상태라고 봐야 합니다. 특정 영역의 관심사가 반영된 구현이라면 그 구현이 위치하기 더 적합한 곳이 있을 테고요.

2023-02-10 13:17 UTC, Laterality commented on src/main/java/domain/CarsInfo.java
> +        return Collections.unmodifiableList(carsInfo);
[다른 크루에게 남겼던 코멘트](https://github.com/woowacourse/java-racingcar/pull/485#discussion_r1102716370)를 참고해주세요.

2023-02-10 13:17 UTC, merged