[1단계 - 자동차 경주 구현] 루쿠(백경환) 미션 제출합니다.
woowacourse/java-racingcar pull request #527
Opened 2023-02-09 08:46 UTC by aiaiaiai1

안녕하세요 우테코 백엔드 5기 루쿠입니다!

이번이 페어 프로그래밍이 처음인 만큼 협업과 소통에 우선적으로 집중해서 같이 구현해보았습니다!

단위테스트를 작성하면서 궁금한점이 생겼는데 작은 단위의 기능들을 테스트하기 위한 테스트코드를 작성하고 후의 작은 단위의 기능들이 합쳐서서 하나의 큰 기능들을 하는 메소드들도 테스트를 해야되는지가 궁금합니다. 이미 작은 단위의 기능 메소드를 테스트를 하였기때문에 중복되는 부분이 존재한다고 생각해서 이걸 또 테스트 해야되나? 라는 생각이 들었는데 이에 관해서 선배님의 의견을 들어보고싶습니다! 

또한 코드의 부족한점이나 개선해야할 부분들을 아낌없이 피드백 해주시면 열심히 공부해서 더 성장해보겠습니다. 감사합니다!

2023-02-09 16:17 UTC, giantim requested changes
루쿠 안녕하세요~ 라빈입니다.

전체적으로 간결하게 잘 작성해 주셨네요 👏 고생 많으셨습니다. 고민점에 대해서는 리뷰도 남겼고 [글](https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/) 하나 읽어보셔도 좋을것 같아요!

궁금하신 부분은 언제든지 편하게 DM 주세요~

2023-02-09 16:17 UTC, giantim commented on src/main/java/controller/RacingGameController.java
> +        for (int i = 0; i < movingTrial; i++) {
인덱스와 움직일 횟수를 비교하면서 잘 동작할거 같은데 어떤 점에서 개선 고민이 있으실까요?

2023-02-09 16:17 UTC, giantim commented on src/main/java/domain/RacingGame.java
> +    }
RacingGame 클래스의 요 메서드가 정말 많은 기능을 하고 있어서 테스트하기 어려운거 같아요. 
그리고 질문주신 내용과 이어지게 내부에서 사용하는 부분을 단위테스트 했는데 이 부분을 테스트하는게 맞나라는 고민을 할 수 있을거 같아요.

그럼 이런 구조가 나오게된 이유부터 찾아볼까요? RacingGame에서 너무 한번에 많은 동작을 수행하려하지는 않았나 고민해봐도 좋을거 같아요. 어떻게 개선할 수 있을지 고민해보면 좋을거 같아요.

2023-02-09 16:17 UTC, giantim commented on src/main/java/domain/RacingResult.java
> +        Integer maxValue = Collections.max(history.values());
여기는 null을 허용할 수 있겠네요...!
Car 객체가 위치 정보를 갖고있는거 같던데 개선해볼 수 있지 않을까요?

2023-02-09 16:17 UTC, giantim commented on src/main/java/handler/InputHandler.java
> +//TODO: 예외 발생 시 재입력
필요한 TODO 인가요?

2023-02-09 16:17 UTC, giantim commented on src/main/java/handler/InputHandler.java
> +public class InputHandler {
컨트롤러를 따로 구현하셨던데 요런 핸들러를 추가로 구성했을 때 어떤 이점을 기대하셨을까요? 🤔
저는 의도가 잘 이해가 안돼서 한번 설명 부탁드리겠습니다 😉

2023-02-09 16:17 UTC, giantim commented on src/main/java/util/InputUtil.java
> +public class InputUtil {
입력을 받는 유틸 클래스가 꼭 필요할까요?
만약 정말 필요하다면 어떻게 사용하는 것이 좋은 예시일까요?

2023-02-09 16:17 UTC, giantim commented on src/test/java/SetTest.java
> +    private Set<Integer> numbers;
우와 학습테스트도 작성해 주셨네요 👏

2023-02-09 16:17 UTC, giantim commented on src/test/java/SetTest.java
> +    @Test
여기 있는 테스트들도 다른 테스트들과 동일하게 어떤 목적인지 DisplayName을 넣어주면 어떨까요?

2023-02-09 16:17 UTC, giantim commented on src/test/java/domain/CarTest.java
> +        //given
given - when - then 으로 테스트를 나눠서 읽기 좋은 문서처럼 작성해 주셨네요 👏

2023-02-10 04:58 UTC, aiaiaiai1 commented on src/main/java/controller/RacingGameController.java
> +        for (int i = 0; i < movingTrial; i++) {
인덱스 i라는 변수를 아래 메소드 몸체에서 사용하지 않아 while문을 이용해보거나 다른방법이 있지 않을까?라고 고민해보았습니다.

2023-02-10 05:12 UTC, aiaiaiai1 commented on src/main/java/handler/InputHandler.java
> +public class InputHandler {
컨트톨러가 뷰로부터 입력값을 받을때 예외가 발생되는 값을 검증하고 예외가 발생하면 재입력을 위한 그런 기능들을 핸들러가 맡아서 처리해 컨트롤로와 뷰의 맡은 책임을 덜어주는 의도로 구성해보았습니다.

2023-02-10 09:02 UTC, aiaiaiai1 commented on src/main/java/util/InputUtil.java
> +public class InputUtil {
단지 inputView 클래스가 지저분하다는 이유로 inputUtil 클래스를 사용했는데 inputUtil 클래스의 역할이 무엇이고 어떤 문제를 해결하기위해 존재하는지에 대해서와 과연 꼭 필요한가에  대해서도 좀 더 고민해봐야겠습니다.

2023-02-11 03:53 UTC, giantim commented on src/main/java/handler/InputHandler.java
> +public class InputHandler {
그렇군요! 그럼 해당 책임을 뷰가 가졌을때 문제라고 생각하신 부분이 있으셨을까요?
이 부분은 질문이고 의도를 명확하게 설계하셨다면 따로 수정을 제안드리는 부분은 아닙니다 😉

2023-02-11 04:03 UTC, giantim approved these changes
루쿠 안녕하세요!
리뷰 잘 반영해주신거 확인 했습니다. 첫 미션 고생 많으셨습니다 👏

2023-02-11 04:04 UTC, merged

2023-02-11 12:13 UTC, aiaiaiai1 commented on src/main/java/handler/InputHandler.java
> +public class InputHandler {
해당 책임을 뷰가 가졌을때는 아무런 문제는 없지만 사용자로부터 받은 입력값이 검증이나 정제가 필요한경우 이를 해결해서 컨트롤러에게 보내주는 기능들을 한곳으로 모아주고 싶었습니다!