[2단계 - 자동차 경주 구현] 제이(이재윤) 미션 제출합니다
woowacourse/java-racingcar pull request #549
Opened 2023-02-12 06:40 UTC by sosow0212

안녕하세요!

2단계 미션을 하면서 `interface`를 사용해서 랜덤 값 생성하는 기능을 구현했습니다.
이렇게 한 이유는 `Cars`도메인에서 `moveAll()` 메서드를 테스트할 수 있기 때문이라고 생각했습니다.

따라서 테스트용 `RandomPowerMakerForFail`과 `RandomPowerMakerForSuccess` 클래스를 만들어주었습니다.

이렇게 하면서 랜덤 값을 의도한대로 주고 테스트를 진행했습니다.

2023-02-12 11:19 UTC, jamie9504 requested changes
제이, 안녕하세요!! 리뷰어 제이미입니다 😄

랜덤 항목을 분리해서 테스트를 할 수 있도록 만드셨네요 👏 👏 👏 👏 👏 

이번 단계에서는 유틸성 클래스(모든 메서드가 static인 클래스)를 사용하지 않고,
객체(일급 컬렉션, 클래스)로 분리해보는 연습을 해보는 건 어떨까요?

`CarNamesValidation`의 `SPLIT_DELIMITER`는 사용하지 않는 상수로 보여서 제거해야 할 것 같아요!

피드백을 조금 남겨두었으니
수정하고 싶은 부분은 수정을 해주시고, 이 부분은 의도한 부분이다 하면 의견을 남겨주시면 좋을 것 같아요.

아마 다음 리뷰 요청이 마지막 리뷰 요청일 것 같아요.
궁금한 부분이나 고민했던 부분을 코멘트로 남기신 후 리뷰요청 주시면 그 부분 답변 드릴께요!

주말 마무리 잘 하시고, 너무 무리하지 마세요 😄

2023-02-12 11:19 UTC, jamie9504 commented on src/main/java/domain/Car.java
>          this.distance = distance;
왜 distance에는 final이 붙지 않고 name에만 붙은건지 궁금해요!

2023-02-12 11:19 UTC, jamie9504 commented on src/main/java/domain/Cars.java
>          for (final Car car : cars) {
여기서는 개행이 중간중간 있고, 아래 메서드에서는 개행이 없는데
하나로 통일하는 게 좋다구 생각해요 😄

2023-02-12 11:19 UTC, jamie9504 commented on src/main/java/engine/RacingGameEngine.java
> +    private void startRace(final Cars cars, final int tryCount) {
InputView에서 tryCount에 대한 검증을 다 한 후에 tryCount를 넘기고 있는데요!
이 부분 만약 검증 자체의 룰이 `자동차 경주의 tryCount는 2 이상이다.` 로 변경되고, 해당 private 메서드(startRace)를 제가 public 으로 바꿔서 다른 클래스에서 호출한다면 어떻게 될까요?
이 startRace에선 모든 범위의 int를 받을 수 있겠죠?

그렇다면 아래와 같은 부분을 고민해도 좋을 것 같아요.
1. validate를 InputView에서만 해도 되는가!
2. validate가 해당 메서드에 있어야 하는가?
3. tryCount라는 것에 대한 범위 제한이라면 과연 이 타입을 int로 가져가는 것이 맞는가? 새로운 클래스가 필요하진 않은가!

2023-02-12 11:19 UTC, jamie9504 commented on src/main/java/utils/CarsFactory.java
> +                .map(carName -> makeCar(carName))
람다 메서드 참조를 이용할 수도 있을 것 같네요!
`.map(CarsFactory::makeCar)`

시간이 된다면 알아보고 적용해보도록 할까요?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/59511689/218301376-044f8210-cb9d-4a66-bffd-7e6a0add7bab.png">

2023-02-12 11:19 UTC, jamie9504 commented on src/main/java/utils/CarsFactory.java
> +    }
CarNames를 받아서, Split을 해주는 부분이 총 두 곳으로 보여요
1. InputView에서 validate할 때
2. CarsFactory에서 실제로 이름을 나눌 때

중복로직이 필요하다면, 존재할 수 있다고 생각하지만
중복로직이 있을 경우 역할과 책임을 잘 나누었는가 고민해보면 좋다고 생각해요.

만일 InputView에서 validate를 하고 CarNames를 잘 분리해서 넘긴다면 어떻게 될까요?
그렇게 되면 이 나누는 로직의 책임은 누가 가져야 할까요?

이 부분을 고민해보면 좋을 것 같아요!
> 연관 키워드 - 일급컬렉션

2023-02-12 11:19 UTC, jamie9504 commented on src/test/java/domain/CarTest.java
> +        int power = givenPower;
재선언을 하는 이유가 있을까요?

2023-02-12 11:19 UTC, jamie9504 commented on src/test/java/domain/CarTest.java
> +        int expectedDistanceAfterMoveSuccess = givenDistance + 1;
`expectedDistanceAfterMoveSuccess`의 의미는 `expectedDistance`로 표현하더라도 이해할 수 있을 것 같아요!

2023-02-12 11:19 UTC, jamie9504 commented on src/test/java/util/RandomPowerMakerForFail.java
> +public class RandomPowerMakerForFail implements RandomPowerGenerator {
클래스명에 For를 써도 되긴 하겠지만, `RandomPowerMakerForFail` 
For를 쓰지 않아도 된다면, 안쓰는 방향이 더 좋겠죠? `RandomFailPowerMaker` 😄

2023-02-12 11:39 UTC, sosow0212 commented on src/main/java/domain/Car.java
>          this.distance = distance;
`distance`변수에 final을 붙이게 된다면, 생성자에서 설정된 distance 값이 변경할 수 없게됩니다!

하지만 Car 도메인의 메서드인 `move()` 메서드에서 값을 증가시키는 로직이 있기 때문에 `final` 키워드를 붙이지 않았습니다.

반면에 `name`은 변할 일이 없다고 생각해서 `final`키워드를 붙였습니다!

2023-02-12 11:49 UTC, sosow0212 commented on src/test/java/domain/CarTest.java
> +        int expectedDistanceAfterMoveSuccess = givenDistance + 1;
`test_move_success()` 테스트와, `test_move_fail()` 테스트의 변수명을 통일 시키고 싶었습니다.

하지만 지금 다시 생각해보니 `test_move_success()` 같은 경우에는 expectedDistance로 쓰는 것도 충분히 표현이 되니 짧게 써도 되겠네요!

2023-02-12 14:01 UTC, sosow0212 commented on src/main/java/engine/RacingGameEngine.java
> +    private void startRace(final Cars cars, final int tryCount) {
public으로 바꾸고 다른 클래스에서 호출 한다면 검증에 의미가 없겠군요..
도메인에서 검증하는 것이 중요함을 느끼게 됐습니다!

마지막 리뷰가 될 것 같다고 하셨는데 지금까지 리뷰해주신 내용으로 정말 많이 성장했음을 느낍니다! 항상 꼼꼼한 리뷰와 답변 정말 감사합니다 :)

도메인에서 어떻게 validation을 진행할지 고민하다가, 기존에 `Car`객체의 변수인 name, distance를 각자 객체로 만들었습니다.
객체로 만드는 과정에서 더욱 자신의 역할에 충실할 수 있다는 점을 느끼고 테스트도 더욱 용이해졌다는 것을 느낍니다!

테코블을 보면서 공부를 했는데, 추후에 '레이서'가 추가된다고 가정할 때 Name 객체를 재사용할 수 있다는 점에서도 재사용을 할 수 있다는 점에서 더욱 객체 분리의 중요성을 몸소 느끼게 됐습니다. 

이번 리팩토링을 하면서 궁금한 점이 생겼습니다!
1. 현재 carNames를 입력 받을 때 중복을 막기 위해서 한 번 검증하고, Name 객체에서 길이와 공백 여부를 한 번 더 검증합니다. 이것도 Name 객체에서 한 번에 하는게 더 좋을까요? 저는 이름 중복에 대한 부분은 `Name`객체 입장에서 봤을 땐 이름 하나만 관리하기 때문에 중복 처리는 다른 곳에서 하는게 맞다고 판단했습니다.제이미는 어떻게 생각하시나요?!

2023-02-12 14:54 UTC, jamie9504 requested changes
제이, 안녕하세요!! 리뷰어 제이미입니다 😄

지난번 리뷰 때 제가 거짓말을 한 셈이 되었네요(?)
이번엔 진짜로 다음 리뷰 요청이 마지막 리뷰 요청일 것 같아요.
궁금한 부분이나 고민했던 부분을 코멘트로 남기신 후 리뷰요청 주시면 그 부분 답변 드릴께요!

마지막 리뷰이니만큼 고민하면 좋은 점들을 좀 적어두었어요.
- 객체를 생성할 때, 파라미터에 대한 검증이 객체의 책임이라면, Validator 종류의 유틸성 클래스가 있을 필요가 있는지
- 그 객체에서 검증해야 하는 내용을 유틸성 클래스에 위임하는 게 좋을지
- 각각의 객체에서 담당해야 하는 책임이 과연 어디까지인지

final 키워드와 재할당, 불변에 대해서도 공부해보면 좋을 것 같아요 👍 

우테코를 진행할 기간은 길어요.
초반에 페이스를 높이면, 나중에 너무 힘들 수 있어요. 너무 무리하지 마세요 😄

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/console/InputView.java
> +    private final CarNamesValidation carNamesValidation = new CarNamesValidation();
Static 메서드만 있는 유틸성 클래스는 객체화를 할 필요가 없어요!
오히려 내부에서 생성자를 Private으로 막아놔도 되긴 합니다.

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/console/InputView.java
>      }
고민해보면 좋을 부분이, InputCarNames에서 Validate를 할 필요가 있을까요?
올바른 CarName인지 판단을 InputView에서 해야하는건지 생각해봅시다!

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Car.java
>      public Car(final String name, int distance) {
Distance가 재할당 되는 곳이 있나요?
name에만 String을 붙인 이유가 있을까요?

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Cars.java
> +    private void addWinnerName(List<String> winnerNames, final Car car, final int maxCountOfDistance) {
final을 붙이는 기준에 대해 고민해보면 좋겠어요.
final은 재할당을 막기 위해 사용하는 건데, 세 파라미터 모두 재할당은 하고 있지 않거든요!

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Cars.java
>          }
`getCurrentRacingStatus()`는 사실상 View를 위한 로직으로 보이는데요.
이 부분을 여기서 만드는 것이 좋을지 고민해볼 필요가 있을 것 같아요!

> 🚀 2단계 - 자동차 경주 리팩터링
> 리팩터링 요구사항

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Distance.java
> +    }
클래스명이 Distance이고, distance만 포장하는 만큼 메서드명에 중복이 들어가지 않아도 되겠죠?

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +public class Name {
자동차 이름을 검증하는 클래스인데요!

`Name`으로 선언시, 다른 클래스에서도 사용할 수 있겠죠?(`자전거`, `지하철` ... etc)
그렇지만, 다른 클래스에서 사용할 수 있다면 자동차 이름만을 위한 검증이 들어가도 될까요?
자동차 이름만을 위한 검증이 들어간 이 클래스의 이름을 어떻게 만들어줘야 적합한 이름이 될까요?

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        validateName(name);
파라미터로 `name`을 보내고 있어서, 메서드명과`validateName` 중복되지 않아도 될 것 같아요!
(TryCount class도 동일)

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/domain/Name.java
> +        CarNamesValidation.validateCarName(carName);
이 부분을 꼭 CarNamesValidation을 의존해야할까요?
해당 클래스에서 책임을 다할 수 있을 것 같아보이는데요!
(TryCount class도 동일)

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/engine/RacingGameEngine.java
> +        final Cars cars = CarsFactory.createCars(getCarNames());
괄호에 괄호가 중첩되면, 중첩되지 않을 때보다 가독성이 좋지 않아지기도 합니다.
이 부분은 개인의 취향영역일 수도 있어서 참고만 해주세요 😄 

```
        final Cars cars = CarsFactory.createCars(getCarNames());

        final List<CarName> carNames = getCarNames()
        final Cars cars = CarsFactory.createCars(carNames);
```

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/validation/TryCountValidation.java
> +        validatePermittedCount(input);
요 메서드로 분리한 이유가 있을까요~?

여러가지 행위를 나눌 경우 메서드의 분리가 의의가 있다고 생각하는데,
한 행위를 통째로 메서드를 나눌 경우, 메서드 이름을 애매하게 지어서일 수도 있다는 생각이 들어서요!

2023-02-12 14:54 UTC, jamie9504 commented on src/main/java/engine/RacingGameEngine.java
> +    private void startRace(final Cars cars, final int tryCount) {
저도 제이가 성장하시는게 느껴져서 기뻐요. 😄 

원시값을 포장하셨네요 👍 

> 현재 carNames를 입력 받을 때 중복을 막기 위해서 한 번 검증하고, Name 객체에서 길이와 공백 여부를 한 번 더 검증합니다. 이것도 Name 객체에서 한 번에 하는게 더 좋을까요? 저는 이름 중복에 대한 부분은 Name객체 입장에서 봤을 땐 이름 하나만 관리하기 때문에 중복 처리는 다른 곳에서 하는게 맞다고 판단했습니다. 제이미는 어떻게 생각하시나요?!

일단 첫째로, Input 값이 유효한지를 InputView쪽에서 검사를 하게 되면, 도메인에서 검사를 하지 않기에 도메인이 의도와 달리 완전하지 못하거나, 중복검사를 해야하는 경우가 생기는데요. InputView에서 검사를 할 필요가 있는지를 먼저 고민해보면 좋을 것 같아요. try - catch를 통해 다시 무언가를 받기 위해서라면, InputView이 아니라 그 InputView를 호출하는데에서, try - catch 문을 사용할 수도 있지 않을까요?
둘째로, 이름 중복에 대한 건이에요. 이게 간단하게는 "이름이 중복되지 않는다"라고 생각할 수 있지만, 다르게 생각을 해볼까요? 이름이 중복이 되면 안되는건 일단 Car는 알 수가 없어요. 자신의 이름만 들고 있으니까요. 그렇다면 Cars는 어떨까요? Cars는 Car들을 가지고 있는데, 같은 이름의 Car를 가지고 있고 싶지 않을 수 있겠죠? 그럼 이 Validate를 어디서 하면 좋을지 생각해볼 수 있을까요?

위 두 부분 고민해서 이번 리뷰 요청 때 반영해주세요 😄

2023-02-13 02:04 UTC, sosow0212 commented on src/main/java/domain/Cars.java
>          }
이것도 도메인이 뷰에 의존 될 수 있군요!

2023-02-13 04:32 UTC, sosow0212 commented on src/main/java/engine/RacingGameEngine.java
> +        final Cars cars = CarsFactory.createCars(getCarNames());
음 여러가지의 명령이 있기 때문에 상황에 따라서 오히려 가독성이 좋지 않을 수 있겠네요!

2023-02-13 04:34 UTC, sosow0212 commented on src/main/java/validation/TryCountValidation.java
> +        validatePermittedCount(input);
이 부분은 지금 당장은 안 나눠도 되겠지만, 추후에 추가 요구사항이 존재한다고 가정 했을 때를 생각해서 저렇게 나눴습니다!

2023-02-13 04:38 UTC, sosow0212 commented on src/main/java/console/InputView.java
>      }
이 부분에서 Domain에서 검증하도록 변경하였습니다!

즉 리팩토링 후에는
1. InputView에서 값 입력 받고 검증 
2. Domain에 넘어올 때 한 번 더 검증
이렇게 한 이유는 중복 처리는 1번에서 할 수 있기 때문입니다!

혹시 제이미는 제가 한 방법에 대해서 어떻게 생각하시나요?

2023-02-13 06:47 UTC, sosow0212 commented on src/main/java/engine/RacingGameEngine.java
> +    private void startRace(final Cars cars, final int tryCount) {
앗 이부분을 커밋을 해버려서 보질 못했네요..!
이 점은 이미 리뷰 요청을 남겨서.. 따로 해결하겠습니다!

2023-02-13 15:58 UTC, jamie9504 commented on src/main/java/console/InputView.java
> +        return tryCount;
<img width="411" alt="image" src="https://user-images.githubusercontent.com/59511689/218506266-312090f9-d7e4-47cf-a544-535aedbf2982.png">

변수로 추출한 이유가 있을까요?

2023-02-13 15:58 UTC, jamie9504 commented on src/main/java/console/InputView.java
>      }
중복 처리에 대해서도 장점이 있지요 👏 
또 어떤 다른 장점이 있을까요?

코멘트를 남겨둘 때 제이의 생각을 먼저 적어주면 좋을 것 같아요!
왜냐면 제 생각을 바로 알려드리기보다, 제이의 생각과 비교해보고 여러 방면으로 생각할 수 있게끔 방향을 잡아주고 싶어서요 😄

2023-02-13 16:06 UTC, jamie9504 commented on src/main/java/validation/TryCountValidation.java
> +        validatePermittedCount(input);
추가 요구사항이 존재한다는 가정은 오버엔지니어링을 발생시키기 쉬운데요,
현재의 요구사항에 충실하게 개발을 하는 것이 좋다고 생각해요!

추가 요구사항이 존재할 가능성과 존재하지 않을 가능성이 모두 있기 때문에,
존재하지 않는다면, 필요없는 코드가 되기 때문이에요!

오버엔지니어링에 대해 조금 알아보면 좋을 것 같아요!

2023-02-13 16:21 UTC, jamie9504 requested changes
제이, 안녕하세요! 리뷰어 제이미에요 😄 

13일 오후 6시 이전까지 온 미션은 한 번 더 리뷰를 남길 수 있다고 하더라구요!
이제 머지를 해도 될 것 같은데, 추가적으로 궁금하거나 수정하고 싶은 부분이 있다면 빠르게 작업 부탁드려요!

화요일부턴 새 미션을 시작하기 때문에, 새 미션에 집중하시는 것도 추천드립니다.
두 가지를 한꺼번에 잡고 있으면, 부담될 수 있거든요.

별도의 커밋과 코멘트 없이 리뷰요청이 오면, 이 부분 바로 머지하도록 하겠습니다 😄 

> + 추가로 리뷰 요청은 한 번만 눌러주세요!
> 두 번 눌러주시면, 리뷰 요청 후 시간 자체가 두 번째 누른 시간으로 되기 때문에.... 
> 뒤의 슬랙 메시지가 보여서 리뷰 순서가 뒤로 밀리기도 하고 그렇습니다 😢

2023-02-13 16:21 UTC, jamie9504 commented on src/main/java/console/InputView.java
> +        return tryCount;
<img width="411" alt="image" src="https://user-images.githubusercontent.com/59511689/218506266-312090f9-d7e4-47cf-a544-535aedbf2982.png">

변수로 추출한 이유가 있을까요?

2023-02-13 16:21 UTC, jamie9504 commented on src/main/java/console/OutputView.java
>      private static final String MOVE_DISTANCE_COUNT = "-";
요 -가 COUNT라는 이름을 가지는 게 적합할까요?

2023-02-13 16:21 UTC, jamie9504 commented on src/main/java/console/OutputView.java
> +    private Map<String, Integer> getCurrentRacingStatus(Cars cars) {
출력 로직 분리 👍

2023-02-13 16:21 UTC, jamie9504 commented on src/main/java/domain/CarName.java
> +            throw new IllegalArgumentException("자동차를 한 대 이상 작성해주세요.");
자동차 이름에 대한 검증 메시지가 아닌 것 같죠?

2023-02-13 16:21 UTC, jamie9504 commented on src/test/java/domain/CarsTest.java
> +        List<Car> cars = List.of(new Car("jay", 0), new Car("jay", 0));
"jay" 변수를 따로 빼면 조금 더 같다는 의미가 부각될 수 있을 것 같아요!

2023-02-13 16:21 UTC, jamie9504 commented on src/test/java/domain/NameTest.java
> +    @ValueSource(strings = {"pobi", "crong", "jay", "jamie", "odo"})
제 닉네임이라니... 감동이에요 🥺

2023-02-14 02:50 UTC, jamie9504 approved these changes
제이, 안녕하세요. 리뷰어 제이미입니다. 😄 

우테코 첫 미션이 종료되었습니다. 👏 👏 👏 👏 👏 

최대한 적절한 피드백을 드리려고 했는데 적절했을지 모르겠네요.
처음 PR 주셨을 때보다 코드가 많이 정돈된 것 같고, 피드백을 반영하실 때 고민한 흔적들도 보여 좋았어요.
의견을 여쭤봤을 때, 생각하신 부분을 코멘트로 남겨주신 부분도 리뷰할 때 도움이 되었습니다.

주말에도 열심히 피드백 반영을 해주셨는데, 지치시진 않으셨을지 조금 걱정되기도 했지만,
본인의 페이스를 찾아서 그 페이스대로 가주시면 될 것 같아요.

남은 우테코 기간도 즐겁게 즐기실 수 있길 바라며, 다음에 또 만나요!
이만 Approve합니다. 👍

2023-02-14 02:50 UTC, jamie9504 commented on src/main/java/console/OutputView.java
> +    private static final String MOVE_DISTANCE_DELIMITER = "-";
DELIMITER는 뭔가 구분자같은 느낌이 들어서,
DISTANCE를 표시하는 기호나 출력 기호정도로 이름을 지어줬어도 좋을 것 같아요 😄

2023-02-14 02:50 UTC, jamie9504 commented on src/test/java/domain/CarsTest.java
> +        Car duplicateCar = new Car("jay", 0);
이름만 중복인 차도 duplicate 검증에 걸리기 때문에 carName만 상수화하는게 더 좋았을 것 같긴 합니다 😃

2023-02-14 02:50 UTC, merged