[2단계 - 자동차 경주 리팩토링] 엔델(김민준) 미션 제출합니다
woowacourse/java-racingcar pull request #559
Opened 2023-02-12 08:59 UTC by SproutMJ

기본적으로 1단계에서부터 mvc 구조가 되도록 만들다 보니 2단계에서 어떤 점을 추가로 하면 좋을지 고민이 되었습니다.
이 관점에서 부족한 부분이나 추가하면 좋은 부분을 알려주시면 감사하겠습니다.
감사합니다.

2023-02-12 15:52 UTC, choijy1705 requested changes
1단계에서 이미 잘 구현해주셔서 
큰 변경사항이 없었네요!
간단히 몇가지 코멘트 남겼습니다! 확인부탁드려요

2023-02-12 15:52 UTC, choijy1705 commented on src/test/java/service/RacingGameTest.java
> +import domain.RacingGame;
이 클래스말고 CarTest에서 
`@parameterizedTest` 를 사용하고 계신데
별로 다르지 않은 것을 중복으로 테스트 하고 있는게 아닌지 고민해보면 좋을것 같아요

2023-02-12 15:52 UTC, choijy1705 commented on src/main/java/domain/RacingGame.java
> +            int random = numberGenerator.generate(RANDOM_START_INCLUSIVE, RANDOM_END_INCLUSIVE);
numberGenerator를 controller에서 생성해서 주입하는 형태인데
numberGenerator의 로직은 자동차 게임과 전혀 상관없는 로직인것 같아요
제생각에는 model, controller, view 어디에도 관련이없다는 느낌입니다

저는 보통 어디서나 사용할수 있는 기능들은 util 클래스로 따로 만들어서 언제 어디서든 호출할 수 있도록 static 으로 관리하곤 하는데 어떻게 생각하시나요?

2023-02-12 15:52 UTC, choijy1705 commented on src/main/java/view/InputView.java
>  import java.util.List;
InputView 클래스 뿐만아니로 다른 곳 몇몇 클래스에서
인텔리제이가 노란불로 경고를 주고 있는데
이런 부분들도 바꿀수 있는부분이라면 바꾸면 좋을것 같아요

![image](https://user-images.githubusercontent.com/63634505/218321536-a2f6ddd3-c1d9-44a6-80a3-a17ebf8e0978.png)

2023-02-13 12:23 UTC, SproutMJ commented on src/main/java/domain/RacingGame.java
> +            int random = numberGenerator.generate(RANDOM_START_INCLUSIVE, RANDOM_END_INCLUSIVE);
일단 static이 되도록 구현 방식을 바꿔보았는데 주입하는 게 아니라 바로 사용하게 되어 test를 위한 랜덤생성기를 주입할 수 없게 되었습니다. 아직 이를 해결할 방법이 떠오르지 않아 아쉽습니다. 다른 방법이 있을까요?

2023-02-13 12:24 UTC, SproutMJ commented on src/test/java/service/RacingGameTest.java
> +import domain.RacingGame;
경곗값을 위주로 테스트 하도록 바꿔보았습니다.

2023-02-13 14:22 UTC, choijy1705 approved these changes
2단계 까지 미션 진행하시느라 고생하셨습니다.👍
mvc패턴에 맞게 잘 구현해주신것 같아요!
간단한 코멘트 남겼는데 확인해주세요
머지하겠습니다!

2023-02-13 14:22 UTC, choijy1705 commented on src/main/java/RacingGameController.java
>  public class RacingGameController {
이 클래스도 controller package를 만들어서 그 안에 넣어주면 더 깔끔하게 보일것 같아요!

2023-02-13 14:22 UTC, choijy1705 commented on src/main/java/util/RandomNumberGenerator.java
> +    }
generate의 로직을 그냥 바로 getRandomNumber에서 사용하는건 어떤가요?
RandomNumberGenerator 클래스에서 RandomNumberGenerator를 생성해서 사용하는게 조금 어색해보여요

2023-02-13 14:23 UTC, merged