[2단계 - 자동차 경주 구현] 박스터(한우석) 미션 제출합니다.
woowacourse/java-racingcar pull request #570
Opened 2023-02-12 12:06 UTC by drunkenhw

안녕하세요 범블비! 박스터입니다.
먼저 리뷰를 통해 많이 배우는 것 같아 감사드립니다!

이번 2단계에선 dto를 제거하고 좀 더 많은 유효성 검증을 하도록 변경했습니다!

잘부탁드리겠습니다!

2023-02-13 12:08 UTC, ddaaac requested changes
안녕하세요 박스터 👋 

1단계에서 구현 잘 해주셔서 크게 남길 코멘트가 없네요.

간단한 코멘트 남겼으니 확인해주세요~

2023-02-13 12:08 UTC, ddaaac commented on src/main/java/racing/domain/Cars.java
> +        if (distinctNames.size() != cars.size()) {
set을 이용해서 중복검사 로직을 구현해주셨군요 👍

2023-02-13 12:08 UTC, ddaaac commented on src/main/java/racing/domain/Car.java
>      public int compareTo(Car other) {
Comparable은 대소 비교의 역할을 수행합니다. 이전 리뷰 때 자동차의 position이란 필드를 완전 감추는 건 어떨까 하는 코멘트를 드렸었는데요, 억지를 조금 보태면 Comparable이라는 인터페이스가 position이라는 값을 드러내고 있다!라고도 생각할 수 있을 것 같아요. 사용하는 쪽에서 `max`를 사용하고 있거든요.
(조금 극단적으로 우승자에 대한 요구사항이 position이 가장 큰 Car가 아닌 이름이 jason인 Car로 바뀐다고 가정하면 Comparable 인터페이스는 아무 소용이 없겠죠)

Stream 연습도 해볼겸 Comparable을 없애는 도전도 해보시면 좋을 것 같아요. 그러면 `max` 대신 사용할 메서드가 필요할 텐데 [reduce](https://www.baeldung.com/java-stream-reduce)를 한 번 사용해보시면 좋을 것 같습니다. 

이 리뷰는 반영해보고 싶다면 반영해보세요!

2023-02-14 05:26 UTC, drunkenhw commented on src/main/java/racing/domain/Car.java
>      public int compareTo(Car other) {
지난 리뷰를 보고 position이라는 단어가 상태를 노출하는 것 같아 감춰보려고 했었습니다.  그리고 범블비 말처럼 Comparable을 적용하면서도 이게 최선인가 하는 의문이 들었지만 reduce를 사용한다는 생각조차 못했던 것 같습니다..
좋은 방법을 알려주셔서 감사합니다!!!!!

2023-02-14 11:19 UTC, ddaaac approved these changes
안녕하세요 박스터 👋 

추가 코멘트까지 잘 반영해주셨습니다. 자동차 미션은 이정도로 마무리 지어도 좋을 것 같아요.

남은 미션들도 지금과 같이 진행하며 많은 것들을 배우시길 바랍니다 🙏

2023-02-14 11:19 UTC, ddaaac commented on src/test/java/racing/domain/CarTest.java
> +    @DisplayName("position이 앞에 있는 차를 반환한다")
position을 감추려면 테스트명에서도 감추면 좋을 것 같아요.
두 차가 주어지면 앞서있는  차를 구한다 등으로요.

2023-02-14 11:19 UTC, merged