[2단계 - 자동차 경주 리팩터링] 달리(김동연) 미션 제출합니다.
woowacourse/java-racingcar pull request #580
Opened 2023-02-12 13:32 UTC by waterricecake

2023-02-12 13:37 UTC, waterricecake commented
이번 리펙토링을 하면서 
- CarDto를 통한 View가 Car와 Game과 분리
- inputViewTest를 위한 input 인터페이스
- outputViewTest 출력값 assertThat사용을 위한 outputViewStream클래스
- 에러메세지 상수화
를 하였습니다. 이 과정에서 test를 위해 인터페이스를 생성해 보았는데  test를 위해 이러한 행위를 해도 되는지 아니면 코드가 오히려 복잡해져 지양해야하는지 궁금합니다.

2023-02-12 13:43 UTC, fucct requested changes
안녕하세요! 달리.
1단계에서 받은 피드백 내용이 반영되지 않은것 같아요! 
피드백 반영 하시고 다시 리뷰요청 주시면 함께 리뷰하도록 하겠습니다.

2023-02-12 13:55 UTC, waterricecake commented
지금 pr을 잘못해서 step1꺼와 혼동이 있는데 지금도 step1때와 같은게 보이시나요?

2023-02-12 14:15 UTC, fucct commented
안녕하세요 달리. waterricecake 브랜치를 rebase를 한 뒤 다시 요청해주세요. 
그리고 급한사항은 github 코멘트 말고 DM 주시면 빠르게 응답 받으실 수 있습니다 :)

2023-02-13 09:45 UTC, fucct requested changes
안녕하세요 달리. 첫번째 미션임에도 피드백을 많이드려서 쉽지 않으셨을텐데, 열심히 바꿔주셨네요!

더 깊이 고민해보시면 좋을것 같은 부분들 피드백 남겼습니다. 궁금하신점은 DM으로 보내주셔도 좋으니, 스스로 만족하실때까지 코드를 리팩터링 해서 다시 리뷰요청 주세요!

2023-02-13 09:45 UTC, fucct commented on README.md
> +### 순서별 기능 목록
순서별로 기능 목록을 작성해주신것도 괜찮은것 같아요. 

여기서 하나 더 피드백 드리자면, **자동차 이름을 받는다** 의 inner depth로 이름의 조건들에 대한 요구사항을 작성해주시면  요구사항을 한눈에 보기 더 좋을것 같아요. 
달리께서 기능목록을 보셨을때 어플리케이션 요구사항이 한눈에 읽히는지 보면서 작성해주시면 좋을것 같습니다 :)

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/controller/GameController.java
> +    private final InputView inputView;
만약 테스트를 위해 Interface로 분리하셨다면, 필드도 Interface타입으로 가지고 있으면 좋을것 같아요!
GameController의 테스트에도 동일한 문제가 발생할 수 있거든요!

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/controller/GameController.java
> +    }
GameController의 역할이 잘 분리된것 같아서 이전보다 훨씬 좋아진것같아요!

한가지 더 피드백 드리자면, private 메서드를 작성하는 기준을 고민해보시면 좋을것 같습니다.
private 메서드는 테스트가 불가능하기 때문에, private메서드가 많아질수록 그걸 사용하는 public 메서드가 해야할 일이 많아지고, 그만큼 test 단위도 커질 수 있거든요.  그런 경우엔, class를 나눠야하는지 한번 고민해보시면 좋을것 같아요.

또한 private 메서드를 많이 사용하게 되는 경우, 코드를 읽을때 흐름을 놓치기 쉬운 단점이 있습니다. 따라서 메서드를 너무 잘게 쪼개면, 오히려 가독성을 헤칠수도 있으니, 달리께서 적절한 단위를 고려하시면서 코드를 작성해주시면 좋을것 같아요!

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/controller/GameController.java
> +        outputView.printWinnersWith(game.getWinnersDto());
Dto를 분리해낸것 훌륭합니다!

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/controller/GameController.java
> +        return List.of(inputView.inputCarNames());
trialCount를 입력받을때는 입력에 대한 값검증을하는데, 여기선 안하고있네요. CarName을 입력받을때 어떤것들을 검증하면 좋을까요? 이런것들이 기능요구사항에도 작성되어있으면 좋을것 같아요!

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/domain/Car.java
> +    public CarDto getCarDto(){return new CarDto(this);}
Car는 Model(도메인) 영역의 객체이고, CarDto는 View 영역의 객체이기 때문에 서로 참조하는건 좋은 형태의 코드가 아닙니다. CarDto가 변경된다면, 도메인인 Car의 변경도 일어날 수 있거든요.
Domain 영역의 변경을 최소화하도록 하려면 어떻게 고치는게 좋을까요?

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/domain/Car.java
>          validatePositionOverInitialPosition(position);
name의 검증로직이 제거된 이유가 궁금합니다..!!

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/domain/Game.java
>          int maxPosition = findMaxPosition();
Game 클래스를 잘 분리해내셨네요!

여기서 하나 더 피드백 드리자면, 현재 Game메서드에서 하는 일들을 보자면

- List<Car>를 순회하며, 최대 위치 찾기
- List<Car>를 순회하며, 같은 위치에 있는 자동차들 찾기
- List<Car>를 순회하며, CarDto만들기

이처럼 List<Car>를 순회하는 로직이 반복되고 있습니다.  
이렇게 특정 로직이 반복된다는건, 새로운 메서드 혹은 객체의 정의가 필요하다는 의미일수도 있어요. 프리코스때의 기억을 더듬어서 한번 리팩토링 해볼까요?

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/domain/RandomMoveChance.java
> +
👍

2023-02-13 09:45 UTC, fucct commented on src/main/java/car/view/InputConsole.java
> +    Scanner scanner = new Scanner(System.in);
접근제어자가 빠진것 같아요!

2023-02-13 09:45 UTC, fucct commented on src/test/java/car/domain/CarTest.java
만약 외부에서 검증이 되더라도, 우리의 요구사항에 대한 검증은 Domain 영역에 필수적으로 존재하여야합니다.

2023-02-13 09:45 UTC, fucct commented on src/test/java/car/domain/GameTest.java
> +        game.getWinnersDto().forEach(carDto -> assertThat(carDto.getName()).isEqualTo(car2.getCarDto().getName()));
현재 테스트는, Game의 동작이 아닌 상태에 대한 검증을 하고 있어요.  

**우승자를 판별**을 검증하기 위해서는 Game의 동작을 수행하고, 동작에 대한 결과를 검증해야 합니다.

2023-02-13 13:27 UTC, fucct requested changes
테스트 코드 피드백 드린 부분 포함해서 재 요청 부탁드립니다.

2023-02-13 13:27 UTC, fucct commented on src/test/java/car/domain/GameTest.java
> +        game.getWinnersDto().forEach(carDto -> assertThat(carDto.getName()).isEqualTo(car2.getCarDto().getName()));
네 달리. 말씀하신대로 우승자를 찾는 기능을 테스트하기 위해선, 달리가 말씀하신대로 원하는 상황을 가정해놓고 테스트를 작성할 수 있습니다. 다만 달리께서 만들어주신 getWinnersDto() 메서드를 한번 살펴볼게요.

cars를 순회하면서 maxPosition을 찾는다.
cars를 순회하면서 찾아온 maxPosition과 동일한 position을 갖는 car들을 필터링한다.
찾아온 cars를 List<CarDto>로 만든다.

총 3가지의 역할을 하고 있는 메서드입니다. 
해당 메서드를 테스트하실때에는 모든 기능이 검증되어야 하므로 말씀드렸던 피드백이였습니다. 만약 달리가 말씀하신대로 우승자를 찾는 기능만 테스트 하고 싶으시다면, findMaxPosition(), hasSamePositionWith(), selectMaxPosition() 모두가 테스트코드로 검증된 상태여야 합니다. 

만약 제가 달리 코드에서 findMaxPosition()을 return 0; 하는 메서드로 만든다 하더라도 getWinnersDto() 테스트코드는 성공할 것이고, 그걸 본 개발자들은 getWinnersDto() 메서드가 문제없는것으로 생각할 수 있습니다.

따라서 테스트의 단위는 검증되지 않은 메서드 행위 모두를 포함해야 합니다. 말씀드린 부분중에 이해안되는 부분이 있다면 말씀 부탁드립니다 :slightly_smiling_face:

2023-02-13 14:12 UTC, waterricecake commented
game에 너무 많은 역할이 부여된것 같아 Winners 객체를 만들어 우승자를 찾는 기능을 분리하였습니다. 이를 통해 test를 분리하여 보았습니다.

2023-02-13 14:36 UTC, fucct requested changes
안녕하세요 달리. 마지막으로 한번만 더 변경 요청 드릴게요. 
변경요청 드리는 이유는 다음과 같습니다.

1. Java 코딩 컨벤션을 제대로 적용해주세요.
2. Dto와 Domain이 서로 무분별하게 참조하고 있습니다. (비즈니스 로직과 UI 로직을 분리한다)
3. 새로 만들어진 Winners객체가 Game객체를 포함하고 있는게 적절할지 고민해주세요. 
4. 모든 도메인의 public 메서드의 테스트코드가 작성되어 있어야 합니다. 생성자를 포함해서요.

만약 리뷰 내용이 너무 어렵다고 느껴지시면 반영안해주셔도 괜찮습니다. 미션에 맞게 잘 짜주셨으나, 한번 더 고민하셨으면 하는 마음에 리뷰 남겨드리는거니, 편하게 말씀해주세요.

2023-02-13 14:36 UTC, fucct commented on src/main/java/car/domain/Winners.java
> +    }
Winners가 다음 필드를 갖는게 맞는지 고민해보시면 좋을것 같아요.
- Game
- maxPosition

2023-02-13 14:36 UTC, fucct commented on src/test/java/car/domain/GameTest.java
>  public class GameTest {
Domain의 모든 public 메서드는 테스트 대상입니다. 생서자를 포함해서요.

2023-02-13 15:46 UTC, waterricecake commented
일단 말씀해주신 것을 최대한 반영해보기 위해 Winners 객체에서 Game을 분리하기 위해 또다시 GameDto를 생성해 보았습니다. 이게 맞는 방법인지는 모르겠으나 Winners에서 단순히 필요한 List<CarDto>와 maxPosition인 int 값 만은 인자로 받아 처리해볼까 고민해 보다가 그냥 두가지 타입을 갖고있는 객체를 만들어보자해서 진행해 보았습니다.
하지만 그 결과 Winners 객체에는 findWinner 메서드만 남게 되었고 이러면 차라리 이 메서드를 다른 메서드에 통합해버리는게 나은지 아님 이거라도 갖고있는 하나 객체가 있는 것이 맞는지 아니면 제가 잘못한건지 모르게 됬습니다;;;;
마지막으로 모든 public 메서드(생성자 포함) test를 작성하였습니다. 하지만 생성자의 경우 test 코드로 어떻게 검증해야할지 모르겠어서 해당 필드내에 값이 제대로 들어갔는 지 확인하거나 생성했을때 오류가 발생하는지 않하는지 정도로 판단하는 방법밖에 못했습니다. 더 좋은 방법이 있는 지 궁금합니다.

여러 고칠점이나 피드백을 올려주셨지만 제가 너무 늦게 과제를 진행하는 바람에 시간이 너무 늦어져 버렸네요. 늦은 시간까지 봐주셔서 감사합니다. 다음 미션때는 최대한 모든 피드백을 반영하여 더 좋은 결과물을 보여드리겠습니다.

2023-02-14 08:46 UTC, fucct requested changes
안녕하세요 달리.

테스트 추가해주신부분 잘 확인했습니다. 다만 나머지 구현들은 제자리걸음인것 같아요.
구현해주신 방법이 맞는지 프리코스 1,2,3단계를 반드시 다시 학습하시고 고민해주세요. 
아주 기본적인 코딩 컨벤션부터, 계속해서 말씀드린 클래스가 가지는 필드와 메서드의 기준 등이 전혀 적용되지 않고 있어요.

테크코스의 미션은 단순히 이 미션을 통과하기 위한 코드를 짜는게 아닙니다. 객체지향 코드에 대한 이해를 하셔야 하고, 개발을 할때 필요한 스킬들을 체화하는 과정입니다. 단순히 미션을 통과하고 교육과정을 수료하는게 목표가 아니여야 합니다.

- NAVER : [캠퍼스 핵데이 Java 코딩 컨벤션](https://naver.github.io/hackday-conventions-java/)
- Google : [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
- Oracle : [Code Conventions for the Java](https://www.oracle.com/java/technologies/javase/codeconventions-contents.html)

- Winners 객체가 필요한 이유는 무엇일까요? Winners 객체는 우승자를 담기 위한게 아닐까 싶어요. 필드로 어떤게 들어오는게 적절할까요? 자동차들, 혹은 우승한 자동차들의 이름 등이 될 수 있겠네요.
- 도메인 객체는 Dto(View)를 필드 혹은 메서드로 의존하고 있으면 안됩니다. 따라서 Winners에 GameDto라던지, Game이 CarDto을 리턴하도록 하기보단, 도메인 객체만을 사용하여 코드가 작성되어야 합니다. 
- CarDto가 도메인 패키지에 있어야 할지 다시 한번 고민해주세요.


이것들에 대해 고민해보시고 반영이 힘들다는 생각이드시면 DM 해주시면 Merge 하도록 하겠습니다.

2023-02-15 12:16 UTC, fucct commented on src/main/java/car/domain/Winners.java
> +    public List<CarDto> findWinners(GameDto gameDto){
Winners는 굳이 없어도 될것 같네요. carsDto를 응답객체로 사용하셔야될것 같아요.

2023-02-15 12:16 UTC, fucct commented on src/main/java/car/view/OutputView.java
> +    private List<String> getCarNameOf2(List<CarDto> cars) {
메서드명을 명확하게작성해주셔야합니다

2023-02-15 12:20 UTC, fucct commented on src/main/java/car/controller/GameController.java
> +        outputView.printWinnersWith(winners.findWinners(new GameDto(game)));
가장 중요한 부분은 이곳인것 같아요.
Game 객체가 게임을 실행하는 객체라면, 
1. Game 의 결과를 위해 최종 자동차의 상태를 리턴한다. ex) game.getGameResults()
2. 우승자 목록을 리턴한다. ex) game.getWinners()

GameController가 필드로 winners를 가질 필요는 없을것 같아요. winners가 우승자를 찾기위해 gameDto를 받을 필요도 없고요.
이부분을 그냥 지나치지 마시고 반드시 학습하셔서 어떻게 객체를 능동적으로 설계할지 고민해보시면 좋을것 같습니다.
개인 학습하시다가 모르거나 질문이 있으시면 저에게 DM주세요.

2023-02-15 12:24 UTC, fucct approved these changes
안녕하세요 달리. 

첫 미션임에도 불구하고 너무 피드백을 오랫동안 많이 드려서 힘드셨을텐데 포기하지 않으시고 끝까지 반영해주신 모습 인상적이였습니다. 
이번 미션에서 좀 더 고민해보고 다음 단계로 가셨으면 하는 마음에 계속해서 피드백을 드렸던 것 같아요. 
이번 미션과 관련해서 궁금하시거나 더 공부해보고 싶으시면 DM부탁드려요. 

수고많으셨습니다!

2023-02-15 12:24 UTC, merged