[2단계 - 자동차 경주 리팩토링] 디노(신종화) 미션 제출합니다
woowacourse/java-racingcar pull request #591
Opened 2023-02-12 15:42 UTC by jjongwa

안녕하세요 검프! 즐거운 주말 보내셨나요? 
두 번째 피드백 반영을 중점적으로 전체적인 구조를 변경해 봤어요.

이번 미션을 진행하며 한눈에 기능을 파악할 수 있는 구조를 만들자는 개인적인 목표가 있었는데,  지난 step에서 조언 받은 부분을 고치며 보니 과도하게 함수나 클래스의 분리가 이루어지고 있다는 생각이 들었고 이러한 관점에서 보았을 때 Util 패키지의 Finder와 Converter 클래스를 나누어 관리해야 할 필요가 있을까 하는 생각이 들었습니다. 

처음 작성할 때에는 검증과 변환의 역할이 서로 다르니 클래스도 나누어야 한다는 의도었지만 굳이 나누지 않고 검증 단계에서 실패하면 예외 처리, 성공하면 변환된 변수 반환의 형식으로 가도 좋겠다는 생각이 들었습니다. 이 부분에 관해서 검프의 의견은 어떤지 궁금해 질문 드립니다..!

이번 리뷰도 잘 부탁 드려요!
감사합니다 :)

2023-02-13 15:33 UTC, Livenow14 requested changes
안녕하세요 디노! 디노도 즐거운 주말 보내셨나요? ㅎㅎ
리팩터링 후 코드가 깔끔해졌네요 :) 
적절한 추상화 정도여서, 읽기 편했어요..! 
몇가지 코멘트 남겼으니, 확인해주세요! 

질문에 대한 답 남깁니다
> 검증과 변환의 역할이 서로 다르니 클래스도 나누어야 한다는 의도었지만 굳이 나누지 않고 검증 단계에서 실패하면 예외 처리, 성공하면 변환된 변수 반환의 형식으로 가도 좋겠다는 생각이 들었습니다. 이 부분에 관해서 검프의 의견은 어떤지 궁금해 질문 드립니다..!

검증과 변환이 하나의 추상화에서 이루어질 수 있는 포인트일까요?
차량의 이름은 얻는 readCarNames() 메서드를 생각해보면, 
(제가) 설정하기엔, "readCarNames는 검증과 변환을 함께한다." 로 설정할 수 있을 것 같아요. 
다만, 앞서 설정한것은 전체 구현의 요구사항에서 "무언가 읽을 때, 유효한 값만 읽는다" 로 설정된 경우일 것 같아요.
그렇지 않다면. "readValidatedCarNames"로 네이밍을 변경하는게, 읽는 입장에서 조금더 편하게 읽을 수 있을 것 같습니다 :) 
그렇지 않다면, 디노가 설정하신 것처럼, inputCarNames, getCarNames로 나눠서 볼 수 있을 것 같아요.

결국 중요한 것은, 제가 생각하기에 추상화 수준이라 생각합니다. 이부분은 취향 차이가 크기 때문에, 현재 단계에선 너무 크게 걱정하지 않으셔도 될 것 같아요..! 

2단계 구현하시느라 수고 많으셨어요 🙇🏻‍♂️🙇🏻‍♂️

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/Application.java
>      }
와우..! 눈에 띄게 코드량이 감소했네요 :) main을 읽기 편해졌어요

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +    }
GameController는 console RacingGame 만 지원하는걸까요?! 
이부분은 다른분 [피드백](https://github.com/woowacourse/java-racingcar/pull/473#discussion_r1102245243)에서도 남겼는데요!! 

현재 구조에선, RacingGame의 인스턴스를 main에서 가져와도 좋을 것 같아요 :) 

```suggestion
    public GameController(RacingGame racingGame) {
        this.racingGame = racingGame;
    }
```

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +    }
run 메서드에서 어떤 일을 수행하는지 추상화 정도가 적정하네요 :)

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/domain/Cars.java
이미 작성한 코드엔 리뷰가 안돼서 ㅠㅠㅠㅠ 테스트를 위한 메서드는 지워주세요...! 
비즈니스 로직상 혼란을 가중시키는 원인이 될 수 있어서요...!!

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/domain/Cars.java
> +            winners.add(car.getName());
여긴 static인 이유가 있을까요..?!?! 
객체 내부에서만 사용되고 있어서요..! 

++ 코드 리뷰가 안되는 부분이 있어서 아래에 추가 코멘트 달겠습니다..! 

Cars 에 정말많은 책임이있네요..! 
모든 로직이 해당 객체에 존재하는 듯으로 보여요. 
(게임 실행, 랜덤값 추출, 출력, 우승자 찾기 등)
몇몇 책임들은 Cars에 없어도 될 책임인 것 같아요 :) 

객체에 책임이 많아진다면,변경이 어려워 질 수 있어요..! 
분리를 해보시는건 어떨까요!?

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/domain/RacingGame.java
> +
한줄 공백이 있네요 :)

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/domain/RacingGame.java
> +        final List<Car> cars = new ArrayList<>();
변수에 final을 붙이신 이유가 있을까요? 
해당 로직 내에서는, 주솟값이 변경될 여지는 보여지지 않아서요 !!

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/domain/RacingGame.java
> +    }
상위 추상화와 하위 추상화 네미밍이 명확하네요 :) 
다만 랜덤값을 move의 인자로 넣어 준다면, 랜덤값을 관리하기 수월할 것 같아요.

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/view/output/OutputView.java
> +    }
car가 변경된다면, 해당 메서드에서도 변경이 이뤄져야겠네요..! 
전반적으로 Car를 인자로 받고있는데, 이경우 Dto를 이용하여 의존성을 분리해보는  것도 좋은 경험일 것 같습니다 :)

2023-02-13 15:33 UTC, Livenow14 commented on src/test/java/domain/RacingGameTest.java
> +        Assertions.assertThat(names.get(2)).isEqualTo("honux");
Junit에서 제공하는 AssertAll도 있답니다 :) 

```java
    assertAll(
        () -> assertThat(names.get(0)).isEqualTo("pobi"),
     ...
    );
```
테스트가 실패해도, 전체 테스트는 돌려보는 장점이 있어요,

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +
여기도 공백!!

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +        return Converter.splitInput(inputCarName);
이름을 가지고 있는, Car에서 해당 validation을 진행해보는 건 어떨까요?
name을 속성으로 가지고 있는 Car가 name의 정책을 가장 잘 알고 있는 "정보전문가"일 것 같아요

2023-02-13 15:33 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +    }
tryNumber도 마찬가지겠네요 :)

2023-02-14 13:08 UTC, jjongwa commented on src/main/java/racing/controller/GameController.java
> +    }
RacingGame의 인스턴스인 carNames와 tryCount를 main단에서 가져오게 변경해 봤습니다!

2023-02-14 13:11 UTC, jjongwa commented on src/main/java/racing/domain/Cars.java
자동차 객체가 올바르게 생성되었는지 확인하기 위해 생성된 Car 객체들의 이름 세팅 여부를 판단하는 테스트코드를 작성했는데, 더 작은 단위로 테스트를 구성하면 굳이 이러한 로직을 확인해 볼 필요가 없다는 생각이 들어서 해당 테스트 삭제하고 getCar 메서드도 삭제했습니다!

2023-02-14 13:28 UTC, jjongwa commented on src/main/java/racing/domain/Cars.java
> +            winners.add(car.getName());
stack 삭제했습니다!

++ 
Cars에 있던 책임을 분산하기 위해 조언해 주신 메서드들을 타 클래스로 옮기거나 따로 분리하였는데 적절하게 위치한건지 아직 확신이 들지 않아요.. 추가적으로 위치를 옮겨야 할 메서드가 있다면 더 알려주세요!

2023-02-14 13:31 UTC, jjongwa commented on src/main/java/racing/domain/RacingGame.java
> +        final List<Car> cars = new ArrayList<>();
앗.. 이건 수업시간에 네오가 함수의 매개변수값에 항상 final을 붙이는 이유에 대해 생각해보라는 질문을 듣고 끄적거리다가 지우지 않은 것 같습니다..! 
별 다른 이유는 없어 다시 삭제했습니다!

2023-02-14 13:33 UTC, jjongwa commented on src/main/java/racing/controller/GameController.java
> +        return Converter.splitInput(inputCarName);
Car의 생성자 부분으로 validation 위치를 옮겼습니다!

2023-02-14 13:33 UTC, jjongwa commented on src/main/java/racing/controller/GameController.java
> +    }
이부분도 마찬가지로 InputView 단계에서 검증을 시행하고 이후에는 int값을 받아 사용하게 변경했습니다

2023-02-14 13:45 UTC, jjongwa commented
안녕하세요 검프! step2 리뷰도 많은 부분을 다시 생각할 수 있는 시간이 된 것 같아요. 바쁘신데도 불구하고 세세한 리뷰 다시 한 번 감사드립니다! 우선 검프가 지적해 주신 부분을 최대한 바꿔 보려고 노력했는데 고치면서도 아직 부족한 부분이 많은 것 같아 갈 길이 멀다는 생각이 드네요.. 이번 미션의 리뷰 기간이 끝나 더 이상 피드백을 받지 못하는 상황인 것 같아 여기까지 고치고 코멘트 남깁니다..!


+추가적으로 여쭤볼게 있습니다..!
우테코 활동을 기록하기 위한 리포지터리를 작성하고 있는데 리뷰어 부분에 검프의 깃허브 주소를 태그해도 될까요?
https://github.com/jjongwa/woowacourse 이 부분입니다..!

2023-02-15 13:55 UTC, Livenow14 approved these changes
안녕하세요 디노 :) 
자동차 경주 잘 구현해주셨어요. 더 자세한 지식들은 다음 단계를 진행하며 충분히 슴득하실 수 있을거라 생각하여, 여기서 마무리 하겠습니다...! 
구현해주신다고 고생많으셨어요 🙇🏻‍♂️🙇🏻‍♂️

몇가지 성장을 위한 피드백을 남길게요..! 
> 테스트 코드를 많이 작성해보기 

테스트가 없는 구현코드는 어떤 패턴, 어떤 기술, 어떤 고수 개발자가 작성했다 해도, 완성되지 않은 코드라 생각합니다. 
사이드이펙트를 유추할 수 없기에 누구라도 만지기 쉽지 않는 코드이고, 그렇기에 살아있지 못한 코드가 된다고 믿어 의심치 않아요.

구현코드를 조금 기대에 못미치게 작성했다하더라도, 테스트 코드가 있다면,  누구나 접근하기 쉽게 되고, 이에 따라 함께 고민해볼 수 있는 기회를 열어주기도 해요.

레벨을 진행하며, 많은 테스트를 작성해보고, 많은 피드백을 받아보며 본인만의 테스트 방법을 찾아가봤으면 좋겠어요 :) 지금은 학습하는 단계고, 그렇기에 어떻게 작성한다 하더라도 바른 길로 안내해줄 많은 리뷰어가 있잖아요?!? 화이팅이에요.

ps. 깃허브에 제 주소 올려주시면 영광이죠! 교육이 끝나는 날, 많은 지식들이 정리되어 있다면 디노 스스로도 정말 뿌듯할거 같네요 :)  응원합니다!

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/Application.java
>  public class Application {
Application 보단 ConsoleApplication으로 콘솔 게임 애플리케이션이다! 를 나타내보는건 어떨까요?!

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/Application.java
> +        gameController.run();
💯

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/controller/GameController.java
> +        while (tryCount-- > 0) {
```suggestion
        while (racingGame.getTryCount()-- > 0) {
```
한군데서 밖에 쓰이지 않다면, 이렇게 설정해줘도 좋을 것 같아요 :)

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/domain/Car.java
> +        InputVerifier.validateNameLength(name);
>이름을 가지고 있는, Car에서 해당 validation을 진행해보는 건 어떨까요?
name을 속성으로 가지고 있는 Car가 name의 정책을 가장 잘 알고 있는 "정보전문가"일 것 같아요 

추가적으로 외부 Verifier 보단, Car 자체에서 validation을 수행해도 좋을 것 같습니다 :)

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/domain/Car.java
> +        }
RandomMaker를 파라미터로 받아올 순 없을까요? 
or Car에선 number만 받아도 괜찮을 것 같습니다. 

excute를 실행하기 위해, 랜덤 값을 가져오고, Move를 결정하고, moving를 하고있어서요 :) 

Move를 할지말지 결정하고, moving을 하는 것은 excute내에 함께 있어도 어색하지 않지만, RandomMaker.getRandomNumber()은 없어도 될 것 같아서요!

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/domain/Car.java
> +    }
메서드가 단순히 다른 메서드의 전달자 역할을 한다면, 하나로 줄일 수 있을 것 같아요 :) 
이것도 얕은 의미의 중복입니다

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/domain/Cars.java
>      }
이후엔.. 일급컬렉션에서 수정불가능한 list를 반환하는 작업이 추가되어도 좋을 것 같아요 :) (UnmodifiedList
++ 좀더 나아간다면, 전체 상태값을 반환할 필요가 있을지 고민해봐도 좋을 것 같습니다. 

일급컬렉션의 사용이유는, 상태를 숨기고 행동을 노출하므로서 캡슐화를 지키기 위함이거든요. 
이렇게 get으로 전체 상태를 노출하는것은 캡슐화에 위반되는 방법입니다 :)

2023-02-15 13:55 UTC, Livenow14 commented on src/main/java/racing/domain/Cars.java
>      }
comapreStep은 비교한다! 라는 의미가 있는데 반환값이 존재하네요.

이경우 command를 의미하는 네이밍인데, query용 이어서 읽기 힘들어보여요 :) 
getWinner등으로 네이밍을 변경하는건 어떨까요?

2023-02-15 13:56 UTC, merged