[2단계 - 자동차 경주 리팩토링] 밀리(김미성) 미션 제출합니다.
woowacourse/java-racingcar pull request #599
Opened 2023-02-12 16:55 UTC by miseongk

안녕하세요 로운! 5기 밀리입니다.
이번에도 리뷰 잘 부탁드립니다 😊

1단계에서 주신 피드백을 최대한 반영했습니다. 

- 생성된 Car 객체들을 일급객체 Cars로 관리
- Controller와 Service의 역할 분리
    - CarFactory 클래스 제거
    -  RacingcarService에서 Cars 생성
- toString으로 결과를 출력하지 않고 Cars 클래스의 getResult() 메소드를 만들어 OutputView에서 출력

피드백 주신 것 처럼 toString으로 결과를 출력하는 부분에서 고민을 했습니다. 간편하게 출력을 할 수 있지만, toString이 객체를 나타내는 String이라는 것을 생각하니, 이 값을 자동차 경주 외에는 사용할 수 없겠다고 판단하여 다른 방식으로 구현했습니다!

감사합니다!

2023-02-13 12:19 UTC, lowoon requested changes
반가워요 밀리! 2단계도 잘 부탁해요 😄 
질문에 답변달았습니다~
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남겨주세요 ^-^

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/RacingcarService.java
> +    public Cars makeCars(String[] cars) {
cars를 만들어 주는게 아니라 내부에서 가지고 로직을 도는게 역할에 맞지 않을까요?

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/Validation.java
> +
검증에 대한 부분이 따로 관리가 되고 있는데요.
관리와 생성을 담당하는 객체에서 검증을 하는 것이 역할과 책임에 맞지 않을까요?
만약 너무 많은 검증이 있는 것 같다고 한다면 원시값의 경우 원시값 포장 객체를 만들어서 검증을 하도록 할 수 있지 않을까요?

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/RandomMaker.java
>      public static int random() {
참고하시면 좋을것 같아요~
https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/
https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/RandomMaker.java
> +    private static Random random = new Random();
final 붙여도 될거 같아요~

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/view/OutputView.java
사용하지 않는 메서드는 지우는게 좋습니다~

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/view/OutputView.java
> +    public static void result(Cars cars) {
view 자체로 의미하는 바가 있지만 메서드를 통해 표현을 해주면 좀 더 명확해질 수 있을 것 같아요~
예를 들면 OutputView.printResult 라던가 InputView.receiveNames처럼??

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/view/InputView.java
> +        Arrays.stream(cars).forEach(Validation::validateNameLength);
개인적인 의견입니다~ 반영은 하지 않으셔도 되요. 역할과 책임에 따라 달라진다고 생각합니다~
input을 받고 split을 해서 List를 반환하고 있는데요.
저는 inputview의 역할과 책임을 입력이 있는지(null, empty 검증)까지로 생각하고 있어요.
이후의 로직들은 비지니스 로직에 포함이 되기 때문에 담당하는 객체에서 진행하는것이 맞다고 생각합니다~

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/domain/Cars.java
> +        return result;
```suggestion
        return cars.stream()
            .map(Car::getResult)
            .collect(Collectors.toList());

```
처럼 할 수도 있을 것 같아요~

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/domain/Cars.java
> +        cars.forEach(car -> car.move(RandomMaker.random()));
forEach는 보통 출력할 때와 프론트에서 사용하는 것 같은데요
[https://homoefficio.github.io/2016/06/26/for-loop-를-Stream-forEach-로-바꾸지-말아야-할-3가지-이유/](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)
개인적인 의견이라 한번 보시고 지금도 괜찮다고 생각하시면 유지하시면 될 것 같아요ㅎㅎ

2023-02-13 12:19 UTC, lowoon commented on src/main/java/racingcar/domain/Car.java
> +        return name + " : " + "-".repeat(Math.max(0, position));
어떻게 보여줄지에 대한 책임은 어디에 있을까요?
만약 position을 +로 표시하기로 했을 때 도메인인 car가 변경되는 것이 맞을까요?

2023-02-14 16:30 UTC, miseongk commented on src/main/java/racingcar/Validation.java
> +
항상 검증하는 부분이 이곳저곳에 퍼져있다고 생각하여 따로 관리해야 하나 고민했었습니다.
그런데 로운이 말씀하신 것처럼 **관리와 생성을 담당하는 객체에서 검증**을 하는 것이 역할에 맞다고 생각하여 
객체 생성 시 검증할 수 있도록 수정하였습니다!

2023-02-14 16:41 UTC, miseongk commented on src/main/java/racingcar/RandomMaker.java
>      public static int random() {
감사합니다!!
올려주신 글을 보고 전략패턴에 대해 학습하고 반영해보았습니다.

이전 코드에서 Car에서 move()를 호출할 때 숫자를 넘겨주던 것을
```java
public void move(MovingStrategy strategy) {
    if (strategy.move() >= MOVING_CONDITION) {
        position.updatePosition();
    }
}
```
위와 같이 구현체를 넘겨주도록 하니, 
좀 더 직관적이고 테스트도 쉽게 구현할 수 있었습니다.

2023-02-14 16:42 UTC, miseongk commented on src/main/java/racingcar/view/OutputView.java
앗 매번 잘 확인하도록 하겠습니다!

2023-02-14 16:48 UTC, miseongk commented on src/main/java/racingcar/view/OutputView.java
> +    public static void result(Cars cars) {
단순히 result()라고 하는 것 보다 prnitResult()가 훨씬 더 명확한 것 같네요 👍
반영했습니다!

2023-02-14 16:51 UTC, miseongk commented on src/main/java/racingcar/domain/Car.java
> +        return name + " : " + "-".repeat(Math.max(0, position));
position을 표현하는 것은 OutputView의 역할인 것 같네요. 
만약 '+'로 표시하도록 수정할 때 가장 먼저 OutputView를 열어볼 것 같아요!
OutputView에서 표시자를 getResult()의 매개변수로 전달하도록 리팩토링 하였습니다.

2023-02-14 16:55 UTC, miseongk commented on src/main/java/racingcar/view/InputView.java
> +        Arrays.stream(cars).forEach(Validation::validateNameLength);
단순히 검증하는 로직을 따로 분리하면서 모든 검증을 inputview의 역할로 넘겨버렸어요ㅠㅠ
`이름 길이 검증` 같은 로직은 비즈니스 로직에 포함하고 나니,
inputview에서의 역할은 로운이 말씀하신 것 처럼 `null, empty 검증`이 맞는것같습니다!

2023-02-14 17:25 UTC, miseongk commented
안녕하세요 로운 😀
바쁘실텐데 2단계 피드백도 너무 감사드립니다!
많은 부분을 변경하다보니 조금 늦어졌습니다ㅠㅠ

## 주요 변경 사항
### controller, service 구조 제거

> controller와 service 구조는 가져가지 않아도 될 것 같다.
    web의 구조를 가져가기 보다 객체를 만들어서 객체의 역할과 책임에 집중하는 것이 좋을것 같다.

위와 같은 피드백을 주셔서 구조를 크게 바꿔보았습니다. 
Controller 대신 게임을 진행하는 RacingcarGame 클래스를 만들고, 비즈니스 로직은 객체에서 처리하니 Service가 굳이 필요없었습니다. 

### name, position 원시값 포장

Car객체의 원시값 name과 position을 포장하여 각각의 객체에서 그에 따른 역할을 하도록 구현했습니다. 

### 전략 패턴 사용

`MovingStrategy` 인터페이스를 만들고, Car의 move()에 구현체를 넘겨주도록 리팩토링 하였습니다.
전략패턴을 사용하면서 
- 확장성 용이
- 테스트 가능

이러한 장점이 있음을 느꼈습니다!

### 예외처리는 담당 객체에서

> 검증에 대한 부분이 따로 관리가 되고 있는데요.
> 관리와 생성을 담당하는 객체에서 검증을 하는 것이 역할과 책임에 맞지 않을까요?

예외처리 부분을 따로 분리하여 관리하였던 것을, 각 객체에서 검증하도록 수정하였습니다.
`역할과 책임`을 생각하니 객체에서 관리하는 것이 맞다는 결론이 쉽게 내려졌습니다!

2023-02-15 11:20 UTC, lowoon approved these changes
고생하셨어요. 밀리! 이전 리뷰 내용을 잘 반영해주셨습니다 💯
이제 그만 자동차 경주 미션을 마무리해도 될 것 같아요.
간단한 코멘트만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 자동차 경주 미션 수고하셨습니다!

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/domain/Car.java
> +    public String getResult(String positionSign) {
도메인이 view와 직접적으로 의존성을 가지게 되면 view가 변동될때마다 서버에서 작업을 해주어야할 거에요.
프론트와 서버의 역할에 대해서 한번 고민을 해보시면 좋을것 같아요!
저는 개인적으로 클라에 상관없이 공통으로 사용할 수 있는 데이터를 서버에서 내려주면 클라에서 요구사항에 맞게 보여주는 것이 맞다고 생각합니다~

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/Application.java
> +        racingcarGame.run();
다음 미션에서는 아래와 같은 구조를 한번 시도해 보시면 좋을것 같아요!
```java
names = InputView.inputCarNames();
RacingCarGame game = new RacingCarGame(names);

tryCount = InputView.inputTryCount();
result = game.race(tryCount);

OutputView.printResult(result);
```

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/RacingcarGame.java
> +            OutputView.printResult(cars);
비지니스로직을 담당하는 객체인데 view에 의존성이 생겨서 view를 신경써야 할까요?

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/RacingcarGame.java
> +        this.carNames = carNames;
생성자에서 cars를 생성해서 cars를 할당할 수 있지 않을까요??

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/RacingcarGame.java
> +    private int tryCount;
tryCount를 변수로 가지고 있어야 할까요??

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/domain/Cars.java
> +        MovingStrategy randomMovingStrategy = new RandomMovingStrategy();
전략에 대한 생성과 관리는 어디에서 해야할까요?? 어느 객체의 역할과 책임일까요??
비지니스 로직과 객체들의 역할에 대해서 한번 고민해보시면 좋을것 같아요!

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/domain/Position.java
> +    public int compareAndFindPosition(int maxPosition) {
비교 후 postion을 찾는 건데 어떤 position을 찾는걸까요??
메서드명으로 어떤 메서드인지 명확하게 알기 힘든거 같아요!

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/strategy/MovableStrategy.java
> +        return 5;
2가지를 만들수도 있지만 생성자를 만들어서 number를 받게하고 메서드에서 number를 return하는 방법도 있구나라고 참고만 하시면 될 것 같아요~

2023-02-15 11:20 UTC, lowoon commented on src/main/java/racingcar/strategy/RandomMovingStrategy.java
> +    private final int MAXIMUM_VALUE = 10;
정적변수여도 되지 않을까요?

2023-02-15 11:20 UTC, merged

2023-02-20 10:27 UTC, miseongk commented on src/main/java/racingcar/domain/Car.java
> +    public String getResult(String positionSign) {
결과 출력하는 부분에서 정말 많이 고민했는데, 저도 로운 말씀대로 도메인에서는 객체가 어떻게 출력되든 알 필요가 없다고 생각합니다!
객체를 전달해주면 OutputView에서 가공하는 것이 맞는것같습니다!

2023-02-20 10:30 UTC, miseongk commented on src/main/java/racingcar/Application.java
> +        racingcarGame.run();
계속 RacingcarGame 생성 시에 names와 tryCount를 무조건 넣어줘야 한다고 생각하고, 다른 구조를 생각해보지 못했습니다. 
RacingcarGame에서 굳이 tryCount를 갖고 있지 않아도 될 것 같네요! 감사합니다 😊

2023-02-20 10:36 UTC, miseongk commented on src/main/java/racingcar/RacingcarGame.java
> +        this.carNames = carNames;
아 RacingcarGame에서 String carNames가 아니라 Cars만 갖고 있는 것이 맞을 것 같네요 😭
```java
public class RacingcarGame {

    private Cars cars;

    public RacingcarGame(String carNames, int tryCount) {
        this.cars = makeCars(carNames);
    }
}
```
이렇게 바꿔볼 수 있을것 같습니다!

2023-02-20 10:37 UTC, miseongk commented on src/main/java/racingcar/domain/Cars.java
> +        MovingStrategy randomMovingStrategy = new RandomMovingStrategy();
전략에 대한 생성은 RacingcarGame에서 하는 것이 좋을 것 같습니다!

2023-02-20 10:38 UTC, miseongk commented on src/main/java/racingcar/strategy/RandomMovingStrategy.java
> +    private final int MAXIMUM_VALUE = 10;
앗 상수로 만들어야 하는데 static을 빼먹었네요.. 확인 잘 하겠습니다!

2023-02-20 10:41 UTC, miseongk commented on src/main/java/racingcar/domain/Position.java
> +    public int compareAndFindPosition(int maxPosition) {
현재 자동차의 위치와 매개변수로 들어온 위치 중 더 큰 값을 반환하는 메서드인데, 메서드명이 명확하지 않네요.
`compareAndFindMaxPosition` 또는 `findMaxPosition` 가 좋을 것 같습니다.

2023-02-20 10:45 UTC, miseongk commented on src/main/java/racingcar/strategy/MovableStrategy.java
> +        return 5;
오 그렇군요 감사합니다!!

2023-02-20 10:55 UTC, miseongk commented on src/main/java/racingcar/RacingcarGame.java
> +            OutputView.printResult(cars);
Application에서 최종 우승자를 출력할 수 있을 것 같은데,
게임 중간에 자동차가 움직이는 부분을 출력하기 위해서는 for문 안에 outputview가 들어갈 수 밖에 없을 것 같습니다. 혹시 다른 방법이 있을까요??