[2단계 - 자동차 경주 구현] 하마드(이건회) 미션 제출합니다.
woowacourse/java-racingcar pull request #617
Opened 2023-02-13 03:34 UTC by rawfishthelgh

안녕하세요 검프 새로운 PR 올립니다 :) 어느 부분을 고민해야할지 명확히 짚어주시다 보니 에너지를 쏟기가 편했네요! 피드백을 듣고 반영한 부분, 그리고 새로운 궁금함을 아래 정리해 봤습니다ㅎㅎ이번에도 좋은 리뷰 해주시면 감사하겠습니다!

## Points To Watch
***
1. Car 객체의 역할 재설정 

  말씀해주신 피드백을 보고 Car라는 객체에게 어떤 역할을 부여해야 하는지를 생각해 봤습니다. 이 점에 대해 생각해보니 Position의 관리 주체를 누구에게 위임해야 할 지도 명확해지는 느낌이었습니다! 따라서 결정한 Car의 역할은 다음과 같습니다.

- Car는 스스로 움직일 수 있다
- Car는 숫자를 보고 움직일 수 있는지 판단할 수 있다
- Car는 독립적인 본인의 위치를 갖는다

다음과 같이 설정한 이유는 

- position은 Car의 인스턴스 하나가 생길 때 마다 부여 및 종속되어야 하는 값이므로, 이를 동등하거나 독립적으로 관리할 수 없다
- 그러므로 Car는 본인의 상태인 position을 스스로 관리할 수 있 어야 한다
-  따라서 이를 늘리거나, 늘릴 수 있는 지 판단하는 것도 Car의 역할이다

라고 생각했기 때문입니다.

2. CarRepository 삭제 및 List<Car>를 관리하는 일급컬렉션 Cars 사용

- position을 Car에서 관리하는 순간 Map으로 이름과 위치를 관리했던 CarRepository의 필요성이 적어졌고, 기존의 많은 역할을 분리할 수 있겠다는 생각이 들었습니다.
- 먼저 개별 차량의 이동, 이동 가능여부 판단 등의 역할은 Car 객체로 이동시켰고, 이제는 Car라는 객체를 리스트로 관리하여 관련 역할(차량 전체 이동, 리스트 중 우승자 판단)만 끄집어내면 된다고 생각했습니다. 따라서 List<Car>를 private으로 관리하는 Cars 라는 일급컬렉션을 생성했습니다.
- 또한 기존 처럼 set 메소드로 컬렉션을 넣는 것이 아닌 final 필드로 선언하고 생성자로 주입해 초기화했습니다.
- 여기서 Cars의 역할은 본인의 컬렉션 상태에 대답 및 변경을 수행합니다. ( 1) 차량들에 이동 명령을 내린다 2) 차량들 중 우승자들을 찾는다 )

3. 입력, 출력의 흐름을 GamePlay 하나에서 관리. InputController 삭제 후 GamePlay가 컨트롤러로 이동

- 말씀하신 “컨트롤러의 역할을 무엇으로 설정했는가”에 대해 답변을 드리면 저는 “어떠한 입력을 받으면 어떻게 처리할지 알려준다” 로 정했습니다. 따라서 초반 InputController를 사용해 차량 입력을 받을 때 게임을 시작함을 드러낸다는 전제를 깔았지만, 입출력의 흐름이 개별 클래스에서 관리되다 보니 타인이 읽기 힘들 것 같다는 생각이 들었습니다.
- 따라서 모든 입출력 흐름을 GamePlay 클래스에 위임하고 컨트롤러 패키지로 이동시킨 뒤, InputController 클래스의 역할은 그 명을 다했다고 생각하여 삭제했습니다.

4. 추가 변경 포인트

- 말씀하신 것 처럼 “정책에서 숫자를 반환한다”라는 개념이 어색해 보였습니다. 하지만 네이밍을 조금 바꿔보면 납득이 가지 않을까라고 생각해서 클래스의 이름을 NumberGenerator로 변경해 봤습니다.
- ENUM을 언제 사용해야 할 지를 명확히 정해야겠다고 생각했습니다. 같은 ENUM 클래스에 사용하는 상수들이 명확한 연관관계와 공통점을 바탕으로 분기해야 할 때만 사용하고, 지금처럼 단순히 매직넘버, 매직스트링을 감쌀 때는 각자 클래스 안에서 사용하기로 결정을 내렸습니다.   
- 내부 클래스에서만 쓰이는 private 메소드에 대해서는 테스트를 하지 않기로 결정했습니다(테스트하고 싶은 욕구를 참기 참 어렵네요ㅎㅎ)

## 궁금한 점
***
1. Getter의 사용이 “필연적이다”라고 생각이 들 때는 getter를 사용해도 되는 것인가? 혹은 getter의 사용은 오직 출력 계층과 테스트를 위해서만 존재해야 하는가?

저는 지금 Cars 라는 클래스 안에서 게임에 참여하는 Car 객체들을 관리하고 있습니다. 게임이 끝나면 각 Car의 position 값을 비교하여 우승자들을 가려야 합니다. 그러므로 각 Car들의 position 값을 getter을 통해 Cars까지 끌고 와서 비교해야 하는 동작은 제게 필연적이라고 생각했습니다. 첫 pr때 position을 따로 관리했었던 이유도 이와 같습니다.

따라서 위와 같이 **컬렉션에 함께 담긴 객체들의 세부 필드 값을 기준으로 비교를 수행해야 할 때, getter의 사용을 허용할 수 있는가** 에 대한 의견을 여쭙고 싶습니다!

2. 게임 진행 순서를 Controller에서 드러내는 것이 맞는가?

위에 언급하였듯 모든 입출력과 게임진행의 흐름을 GamePlay에서 드러내고 있는데, 저는 Service의 개념을 “받아온 정보를 비즈니스 로직에 맞게 가공한다”라고 생각했습니다. **따라서 “게임의 순서를 관리한다” 라는 개념이 서비스에 있지 않다고 봤습니다.**

또한 Controller에 이 클래스를 넘긴 이유는 요청의 진입 시점을 드러내고 진입 이후 어떤 순서로 요청이 처리되는지를 담당하는 것이 Controller의 역할이라고 생각했기 때문입니다!

그러나 “게임이 진행되는 순서”를 비즈니스 로직으로 봐야 하는지, 아니면 단순히 순서로만 봐야 하는지가 궁금했고, **따라서 위 제 의견에 대한 검프님의 의견이 궁금했습니다!**

2023-02-14 16:27 UTC, Livenow14 requested changes
안녕하세요 하마드 2단계도 정말 잘 구현해주셨어요 :) 
몇가지 피드백남겼으니, 선택에 따라 반영 부탁드려요 !! 
피드백 반영하시다가 질문이 있으시다면 언제든 DM 주세요 🙇🏻‍♂️

PR에 변경 포인트들이 작성되어있어, 어떤 의도로 미션을 진행했는지 쉽게 판단할 수 있어서 좋았어요 👍
질문에 대한 1번 답은 코멘트에 적었는데, 2번은 적지못해 여기다가 남겨요! 

> 게임 진행 순서를 Controller에서 드러내는 것이 맞는가?

게임 구현 요구사항이, 출력, 실행(순서에맞게), 출력으로 정의되어 있지 않나요?! 
그렇다면 저는 넓은 의미에서 비즈니스 로직이다! 라고 판단해도 좋을 것 같아요. 

"요구사항 == 비즈니스 로직" 으로 생각하면 조금더 수월한데요. 
미션에서 View와 분리하라는 점 때문에 많이 혼동이 있었으리라 예상돼요. 

console 게임에서 게임이 진행되는 순서는 사용자가가 아닌 시스템이 관리를 하게되는 것이고, 이에따라  "게임의 순서를 관리한다" 라는 개념은 서비스에 있는 것이 자연스러워요.

입/출력을 하는것 또한 비즈니스 로직이긴 하지만, 해당 입/출력에 대한 방식은 굳이 console에서만이 아닌, api-call, file i/o로도 관리될 수 있기 때문에 UI와는 분리를 하라! 라는 추가 요구사항이 생겨난 것이라 판단돼요.

그렇기에, 좁은 의미에서 비즈니스 로직은,  Car 가지고 있는 도메인 로직이라 생각이 들어요. 
Car의 역할이 잘 정의되어 있다면, 언젠가 요구사항이, "console이 아닌 api입력으로 Car의 게임을 진행하라!" 라고 변경되어도, Car의 책임은 변함이 없을거라 기대 되거든요. 

이부분은 미션을 추가적으로 진행하다보면 자연스럽게 체득하시게 되디라 기대됩니다 :) 
이번 단계도 수고많으셧어요 !

2023-02-14 16:27 UTC, Livenow14 commented on README.md
>  ## 구현 기능 목록
구현기능 목록이 업데이트 되었네요 ㅎㅎㅎ

2단계를 진행하며, 리팩터링한 것들이랑 추가 구현된 사항도 정리한다면 이번 미션에서 어떤걸 중점적으로 했는지 파악하기 편할 것 같아요 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/Main.java
> +        gamePlay.gameStart();
게임을 만들고, 진행한다! 가 조금더 잘 보이게 됐네요 :) 

다만 GamePlay에서 어떤 의존성이 필요한지 궁금해지는데요. 이부분을 아래 추가적으로 말씀드릴게요!

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/controller/GamePlay.java
> +    }
gameStart에서 전반적인 흐름을 파악할 수 있는 것은 잘해주셨어요!! 

다만, 메서드 안에서 초기화를 해주는 부분들이 많은데요, 이경우 내부구현의 변경이 GamePlay를 의존하고 있는 Main의 장애로 이어질 수 있어요. 이는 캡슐화를 위반하는 것인데요.

여기서 힌트는. 인스턴스 초기화를 진행하고 있는 부분들에서
1. GamePlay의 인스턴스로 설정한다. 
```java
    private final Cars cars;
    private final NumberGenerator numberGenerator;

    public GamePlay(Cars cars, NumberGenerator numberGenerator) {
        this.cars = cars;
        this.numberGenerator = numberGenerator;
    }

```
3. gameStart의 파라미터로 넣어준다
```java
    public void gameStart(Cars cars, NumberGenerator numberGenerator) {
```

로 변경할 수 있을 것 같아요. 

1번으로 진행한다면, GamePlay의 전체 책임을 온전히 수행하기 위해 Cars와 RandomNumberGenerator 등이 필요함을 의마할 수 있고, 
2번으로 진행한다면, GamePlay의 gameStart를 위해선 Cars와 RandomNumberGenerator가 필요함을 나타낼 것 같아요.

하마드께서 작성해주신 GamePlay에서는 해당 인스턴스를 여러 메서드에서 사용하고 있으니, 1번이 조금더 끌리긴 하네요 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/controller/GamePlay.java
> +    }
for문의 i가 반복문내에서 사용되지 않고 있어요 :) 

이경우 
```java
        while (tryTimes-- > 0) {
            cars.moveCars(numberGenerator);
            OutputView.printCarNameAndPosition(cars);
        }
```
등으로 한다면 조금더 의미를 잘 들어낼 수 있을 것 같아요

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/controller/GamePlay.java
> +        NumberGenerator numberGenerator) {
앞서 말씀해주셨듯이, NumberGenerator numberGenerator로 변경을 진행하니, 훨씬 더 가독성이 좋아졌네요! 💯

다만, 위에서 말씀드린 코멘트의 1번을 진행한다면, 인스턴스 변수로 둘 수 있게되어, 파라미터를 조금더 줄일 수 있을 것 같네요 ㅎㅎ

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/controller/GamePlay.java
> +    private void validateTryTimes(int tryTimes) {
깔끔한 정책이네요 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/domain/Car.java
> +    private static final int MAX_NAME_LENGTH = 5;
저는 단순 값에 대해서는 상수화를 진행하지 않는게 좋다고 생각합니다! 
    private static final int ADD_POSITION = 1;
    private static final int MIN_NAME_LENGTH = 1;

1이라는 값이 중복되는데요. 이경우 그냥 1로 써도 무방할 것 같아요. 
MIN_NAME_LENGTH이 사용되는 곳에 ADD_POSITION이 들어가도 아무런 문제가 없어 보여서요!! 

나중에는 
private static final int MIN_NAME_LENGTH = 1;
private static final int COUNT_LENGTH = 1;
private static final int FOO = 1;
...

로 추가될 것 같기도 해요..! 

매직넘버에 대해 상수화를 진행하는 것은 좋은 행동이긴 하지만, 이렇게 단순한 경우에는 메서드 내에서 그 의미를 쉽게 판단할 수 있을 것 같아요 :)  (그렇지 않다면, 로직이 조금 어렵게 짜여있다는 반증이기도 합니다)

상수화를 진행한다고 해서, 잘 짜여있지 않은 로직이 쉽게 읽히지는 않는 것 같아서요!

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/domain/Car.java
> +    private int position = INIT_POSITION;
position을 Car 생성시 받아와도 전혀 문제가 없을 것 같아요 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/domain/Car.java
> +    }
```suggestion

    private void validateNameLength(int nameLength) {
        if (!isValidNameLenght(nameLength)) {
            throw new IllegalArgumentException("[ERROR] 1에서 5사이의 이름 길이만 입력 가능합니다.");
        }
    }

    private static boolean isValidNameLenght(int nameLength) {
        return nameLength >= MIN_NAME_LENGTH && nameLength <= MAX_NAME_LENGTH;
    }

```
로 추상화를 진행해주신다면, 쉽게 읽을 수 있을 것 같아요

ex) 
기존> NameLength를 검사하네  > 1미만 5초과이면  예외를 뱉는구나.
변경 > NameLength를 검사하네 > 유효한 크기의 이름이 아니면, 예외를 뱉는구나, > 유효한 크기의 이름은 어떤 기준이지? 아~~  1이상 5이하가 유효한 크기의 이름이구나.

읽는 사람에 있어, 
valdate 기준은 구현 세부사항일 수 있어서, 적절한 이름으로 작성해주신다면, 필요할 때, 해당 기준을 살펴볼 수 있게 할 수 있을 것 같습니다 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/domain/Cars.java
> +    }
> 각 Car들의 position 값을 getter을 통해 Cars까지 끌고 와서 비교해야 하는 동작은 제게 필연적이라고 생각했습니다. 첫 pr때 position을 따로 관리했었던 이유도 이와 같습니다.

저는 getter의 사용에 대한 기준은 조금 유하게 가져 가는 편입니다 :) 
(setter의 의미를 가지는건 무조건 피해요 ex) setName -> changeName)

다만, 하마드의 말씀처럼 필연적이다! 의 부분은 객체의 책임에 따라 다르다! 라고 볼 수 있을 것 같아요.
1. position을 비교하는 책임을 Cars다 둘것이다.
- 그렇다면, 지금처럼 getPosition을 통해 하는것이 자연스러워 보입니다.
2. position을 비교하는 책임을 Car다 둘 것이다.
- Car에서 비교하는 로직을 Car에다 두어야 겠군요.
```java
#Car.java
public class Car implements Comparable<Car> {
 ...
    public boolean isSamePosition(Car car) {
        return this.position == car.position;
    }

    @Override
    public int compareTo(Car o) {
        int o1 = this.position;
        int o2 = o.position;

        if (o1 > o2) {
            return 1;
        }
        return -1;
    }

#Cars.java
public class Cars {
...
    public List<Car> findWinners2() {
        Car winner = cars.stream()
            .max(Car::compareTo)
            .orElse(new Car("dummy"));

        return cars.stream()
            .filter(it -> it.isSamePosition(winner))
            .collect(Collectors.toList());
    }
```

다만 어떤 방식이 더 좋을지는, 하마드가 판단해 주세요:)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/genertor/RandomNumberGenerator.java
> +public class RandomNumberGenerator implements NumberGenerator {
크.. 깔끔하네요 :)

2023-02-14 16:27 UTC, Livenow14 commented on src/main/java/domain/Cars.java
> +    }
++ 테스트가 작성되어있어, 검증이 정말 편했어요. 감사합니다 :)

2023-02-14 16:42 UTC, Livenow14 commented
++ 더이상 사용하지 않는 객체는 삭제 부탁드려요 :)

2023-02-17 06:08 UTC, rawfishthelgh commented
안녕하세요 리뷰 열심히 써주셔서 감사합니다ㅎㅎ두 번째 리팩토링 진행했습니다!!

1. 상수화를 진행하는 나름의 기준을 세워봤습니다. 앞으로는 단순 숫자나 문장의 경우 상수화를 진행하지 않고, 구분자나 출력에 필요한 도구(ex, “-“)만을 상수화로 진행하기로 했습니다!
2. Gameplay 에서 대부분 생성자를 통해 초기화를 진행할 수 있도록 리팩토링했습니다. 
3.  position을 Car 생성 시 받아오라는 말씀에 대해 조금 궁금한 점이 생겼습니다. 저는 Car를 생성할때 반드시 위치값이 0에서 시작하도록 하기 위해 position 초깃값을 0으로 세팅해놨습니다! 그러나 이를 Car 생성자에서 받아오도록 하면 0이 아닌 다른 값으로 초기화될 수 있기에 객체 내부에서 초기화하도록 설계했는데, 이 부분이 문제가 없는 이유가 궁금했습니다:)

2023-02-18 15:15 UTC, Livenow14 approved these changes
안녕하세요 하마드..! 구현 잘 해주셨어요 :) 
리팩터링 후 코드가 정말 깔끔해졌네요 :) 

>  이를 Car 생성자에서 받아오도록 하면 0이 아닌 다른 값으로 초기화될 수 있기에 객체 내부에서 초기화하도록 설계했는데, 이 부분이 문제가 없는 이유가 궁금했습니다:)

질문에 대한 답입니다.

저는 객체 내부의 속성을 자신이 결정하는 것보다, 자신을 사용할 다른 객체에게 속성값을 할당할 책임을 두는걸 선호합니다. 
만약 절대로 0이외의 다른 값이 들어오지 않는다면, 기존 구현대로 진행하셔도 좋지만, 소프트웨어는 항상 변하고, 또, 객체를 자유자재로 사용하기(테스트 등) 위해선, 외부에서 결정하도록 하는것이 좋을 것 같아요 :) 
이부분은 많은 미션을 진행하다보면, 자연스럽게 보일 것 같아서, 너무 깊게 고민안하셔도 될 것 같습니다 ㅎㅎ 

간단한. 피드백을 남긴다면. 
> comment에 의견을 전달해주셨으면 좋겠어요. 

코드 리뷰 과정은 평가의 과정이 아닙니다. 리뷰어와 함께 소통 하면서 코드를 완성해가면 좋을 것 같아요 :) 
남은 미션들도 화이팅입니다!

2023-02-18 15:15 UTC, Livenow14 commented on src/test/java/service/GamePlayTest.java
>      }
give when then 패턴을 활용해보는건 어떨까요?

2023-02-18 15:15 UTC, merged