[2단계 - 자동차 경주 리팩토링] 디투(박정훈) 미션 제출합니다.
woowacourse/java-racingcar pull request #627
Opened 2023-02-13 06:04 UTC by shb03323

2023-02-13 23:17 UTC, KIMSIYOUNG requested changes
안녕하세요 디투!
전체적으로 역할분리, 네이밍 등이 잘 되어 있어서 읽기 좋은 코드인 것 같아요.
몇가지 코멘트 남겼는데 추가로 고민해보시면 좋을 것 같습니다.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Car.java
> +    public Car(final String name, final int startPoint) {
자동차의 위치를 받는 생성자가 필요한 이유가 무엇인가요? 

위치 비교를 위한 테스트는 자동차를 움직여서 테스트해도 좋을 것 같아요.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Car.java
> +    public int compareTo(final Car other) {
어떤 이유로 구현되었나요? Getter를 지양하기 위함이라면, Getter를 지양하자는 규칙이 어떤 의미인지 조금 더 고민해보면 좋을 것 같아요.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> moveCars(final NumberGenerator numberGenerator) {
자동차의 이동과, 이동된 자동차의 위치반환 두가지 일을 한 곳에서 하고 있는 것 같아요.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Cars.java
> +    private List<Car> createCarsByNames(final List<String> carNames) {
자동차의 시작위치는 자동차가 알고 있는 것이 자연스러울 것 같아요.

위치를 받는 생성자가 없어진다면 자연스럽게 사라질 수 있을 것 같네요.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/TryCount.java
> +public class TryCount {
TryCount보단 도메인 의미를 드러낸다면 Lap과 같은 네이밍이 의미를 더 잘 표현하는 것 같아요.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/WinnerMaker.java
> +    public static List<String> getWinnerCarsName(final List<Car> cars) {
static한 형태로 구현하는 것과, 객체로 구현하는 것의 장단점에 대해서 고민해보면 좋을 것 같습니다.

2023-02-13 23:17 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/WinnerMaker.java
> +    public static List<String> getWinnerCarsName(final List<Car> cars) {
static한 형태로 구현하는 것과, 객체로 구현하는 것의 장단점에 대해서 고민해보면 좋을 것 같습니다.

2023-02-14 15:01 UTC, shb03323 commented
안녕하세요 카일! 부족한 코드 꼼꼼하게 챙겨주셔서 감사합니다! 리뷰 통해서 더 많은 공부를 할 수 있었습니다:)
2단계 리뷰 확인하고 리팩터링을 진행했는데, 리팩터링 진행하면서 궁금한 점이 2가지 있습니다.


1. 자동차 위치를 받는 생성자: 현재 프로그램에는 필요가 없지만 추후에 핸디캡이라는 기능이 생겨 핸디캡을 받는 자동차는 조금 더 앞에서 출발할 수 있다고 가정하면 초기 위치값과 함께 자동차를 생성하는 것이 옳을 것 같다고 생각했습니다. 어제 크루들과 이야기 나누고 수업도 들으면서 제가 과한 기능 확장으로 생각하지 않았는가? 생각이 들더라고요... (사실 기능을 확장하게 되면 전략 패턴으로 관리할 수 있을 것 같습니다ㅋㅋ..) 하지만 이건 미션이기 때문에 확장성을 얕게 생각해서 그런 것인지, 실제 현업에서도 확장성에 대해 깊게 고민하지 않는지 궁금합니다!


2. static: 
    단점:
        1) 프로그램 실행 시에 처음부터 끝까지 메모리에 남아있기 때문에 과한 static 남용은 정적 메모리 공간을 부족하게 합니다.
        2) 또한 인스턴스를 생성하지 못한다는 단점이 있습니다. 
        3) 변수를 캡슐화하지 못합니다.
    장점:
        1) 인스턴스 생성으로 낭비되는 메모리를 줄일 수 있습니다.
        2) 고정 메모리를 사용하기 때문에 메모리 주소를 찾기 편합니다.

저는 `우승자를 구하는 클래스`만을 보았을 때 단점은 단점으로 보이지 않았습니다. 첫째로, 인스턴스 변수가 존재하지 않기 때문에 캡슐화를 고려할 필요가 없다고 생각했습니다. 또, 우승자를 구하는 객체는 단 하나의 인스턴스만 생성이 됩니다. 인스턴스를 생성하지 않고, static 객체 그대로 사용해도 크게 문제가 되지 않는다고 생각했습니다. 
인스턴스를 생성하지 않음으로써 코드를 조금 줄일 수 있고, 속도도 더 빠를 것 같아서 static을 사용하게 되었습니다. 같은 이유로 `InputView`와 `OutputView`를 static으로 관리했습니다!
구글링을 통해 `static이 interface를 생성하지 못하게 한다.`라는 정보를 추가적으로 배웠습니다. 우승자를 구하는 클래스가 interface까지 고려할만한 클래스라는 생각은 들지 않아서요... 혹시 어떤 부분 때문에 static 사용에 대해 말씀하셨는지 이야기해주실 수 있을까요? 그리고 혹시 static을 지양해야 한다면 이걸 싱글턴 패턴으로 적용해도 괜찮을까요? 


앞에서도 말씀드렸지만 카일님에 작성해주신 코드 리뷰 덕분에 더 깊게 고민할 수 있었습니다! 첫 번째 미션동안 깊은 고민에 빠질 수 있게 해주셔서 감사합니다. 좋은 밤 되세요:)

2023-02-15 01:00 UTC, shb03323 commented
안녕하세요 카일, 코드를 다시 살펴보다가 자동차 이름도 원시값 포장을 해야할 것 같아 포장을 진행했습니다!

2023-02-15 10:04 UTC, KIMSIYOUNG approved these changes
안녕하세요.
리뷰도 잘 반영해주셨고 전체적으로 깔끔하게 잘 구현해주신 것 같아요.
질문 주신 내용은 답변으로 달아두었습니다!
고생 많으셨습니다. 다음 미션도 화이팅하세요!

2023-02-15 10:04 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Position.java
> +    public int compareTo(final Position other) {
구현되어야 하는 이유가 있을까요?

2023-02-15 10:04 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/WinnerMaker.java
> +    public List<String> getWinnerCarsName(final List<Car> cars) {
네네 좋은 고민이신 것 같아요.

저의 의도는 객체를 지향한다면 어떤 형태가 나을까에 대해서 고민해보면 좋을 것 같다고 생각했어요. 말씀하신 장점을 위해 현재와 같이 구현해도 좋은 방법이라고 생각합니다. 다만 현재 해당 클래스는 객체라고 보긴 어려울 것 같아요.

추가로 우승자의 이름만을 반환하는 것은 뷰를 위한 로직인 것 같아요. 도메인 패키지에 들어있다면 뷰와 무관하게 구현되어야 할 것 같습니다.

2023-02-15 10:04 UTC, KIMSIYOUNG commented on src/main/java/racingcar/domain/Car.java
> +    public Car(final String name) {
확장을 고려하여 설계하는 것은 좋은 것 같습니다. 
이 부분은 개인적인 의견이니 참고만 해주세요.
1. 저는 경험상 제가 생각한 형태대로 어플리케이션이 확장되고 변경되는 경우가 적었습니다. 그렇기에 과도한 추상화나 확장을 고려한 형태의 개발을 지양하고 있습니다. 확장을 위한 설계는 `이 생성자는 왜 테스트에서만 쓰는데 필요하지?`, `여기는 왜 인터페이스로 구현되어 있지?`와 같은 가독에서 헷갈림을 주는 것 같아요. 그렇기에 현재의 요구사항을 만족하는 가장 단순한 형태의 개발을 지향합니다.
2. 확장을 고려한 생성자라 하더라도, 우승자를 가려내기 위해 `어떠한 흐름에 따라 움직여야 한다`는 말씀하신대로 어플리케이션이 확장되더라도 변하지 않을 것 같아요. 그렇기에 어떠한 흐름에 따라 움직인 이후에 위치를 통해 우승자를 찾아내는 테스트가 진짜 어플리케이션의 테스트가 될 것 같습니다.  추가로 우승자를 찾아내는 곳으로만 한정해서 본다면 단위테스트가 어렵습니다. (자동차의 움직임을 추가해야하기 때문에) 다만 이런 경우 매번 이를 위한 편의 메소드를 만들어낼 것인가? 에 대해서도 고민해보면 좋을 것 같습니다.

2023-02-15 10:04 UTC, merged

2023-02-15 13:09 UTC, shb03323 commented on src/main/java/racingcar/domain/Position.java
> +    public int compareTo(final Position other) {
가장 먼 위치(Position)를 구하는 작업은 Position의 업무라고 생각했습니다. 정확히는 Position 목록을 가지고 있는 일급 컬렉션의 역할이지만, 가장 먼 위치를 구하는 작업 만을 메서드로 가지는 객체(일급 컬렉션)를 생성하는 것은 과한 분리라고 생각했습니다. getter를 사용하여 WinnerMaker에서 해결해야 할 문제였을까요?

2023-02-15 13:11 UTC, shb03323 commented on src/main/java/racingcar/domain/WinnerMaker.java
> +    public List<String> getWinnerCarsName(final List<Car> cars) {
코멘트 감사합니다:) 뷰를 몰라야 하는데, 마치 아는 것처럼 되어버렸군요. 말씀해주셔서 감사합니다!

2023-02-15 13:12 UTC, shb03323 commented
긴 질문 읽어주셔서 감사합니다. 카일 덕분에 의미있는 고민을 할 수 있었습니다.
리뷰해주셔서 감사합니다!