[2단계 - 자동차 경주 리팩토링] 매튜(김재연) 미션 제출합니다.
woowacourse/java-racingcar pull request #636
Opened 2023-02-13 08:03 UTC by kpeel5839

안녕하세요 제이미!

제이미가 주신 피드백대로 최대한 적용해보았어요!

개인적으로 성장한 느낌이 듭니다!

정말 감사합니다!

2023-02-13 16:42 UTC, jamie9504 requested changes
매튜, 안녕하세요! 리뷰어 제이미입니다 😄 

13일 오후 6시 이전까지 온 미션은 한 번 더 리뷰를 남길 수 있다고 하더라구요!
피드백을 남겨놓았습니다.
추가적으로 궁금하거나 수정하고 싶은 부분이 있다면 빠르게 작업 부탁드려요.

리팩터링을 할 때도, 커밋 로그를 신경 써보면 좋을 것 같아요.
저도 이것 저것 고치다보면 저도 종종 커밋이 커질 때가 있더라구요. 😄
커밋로그를 너무 잘게 쪼개는 것이 능사는 아니지만, 적당한 단위로 쪼개놓으면 커밋을 보면서 어떤 작업을 했는지 확인도 편하고, 나중에 다른 브랜치에서 해당 커밋의 변경 사항을 가져온다거나, 그 전으로 롤백한다거나 할 때도 유용하게 도움이 된답니다!  

화요일부턴 새 미션을 시작하기 때문에, 새 미션에 집중하시는 것도 추천드립니다.
두 가지를 한꺼번에 잡고 있으면, 부담될 수도 있고 오히려 이것저것 하느라 능률이 떨어질 수도 있어요!

별도의 커밋과 코멘트 없이 리뷰요청이 오면, 이 부분 바로 머지하도록 하겠습니다 😄

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/controller/RacingController.java
>      private void end(Cars cars) {
end라는 메서드 명이 적합한지는 조금 고민이 되네요!

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/controller/RacingController.java
> +}
개행을 해주세요!

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/domain/Car.java
> +        String validCarName = validateCarNamesLength(name);
validate-로 시작하는 메서드의 경우, void를 반환하며 안에서 검증 실패시 exception을 던질 것 같은 느낌을 줍니다.
메서드명을 적합하게 변경해보거나, 역할을 분리하는 것도 좋을 것 같아요!

---

바로 아래에서 가공 없이 1회만 쓰는 경우, 변수로 빼는 것이 좋을지 고민해보아요.

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/domain/Car.java
> +
검증로직이 들어오면서, 차 객체가 해야할 책임이 늘어났네요!
책임이 너무 늘어났다 싶으면, 요 책임을 원시값을 포장해서 위임해보아도 좋지요.

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/domain/Cars.java
> +    public void moveAll(PowerGenerator powerGenerator) { // 모든 Car 들을 moveAll
사용하지 않는 주석 or 필요하지 않는 지워주세요!
관리 포인트만 늘어납니다!

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/domain/GameCount.java
> +        }
요 부분은 테스트 코드를 거치지 않고 있네요!

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +    private static final int CAR_NAME_INPUT_EMPTY = 0;
상수명을 조금 더 적합하게 만들어볼 수 있을 것 같아요!

2023-02-13 16:42 UTC, jamie9504 commented on src/test/java/domain/CarTest.java
> +    @ValueSource(strings = {"  pobi   ", "  hello  ", " 제이미짱! "})
🥺 감동이에요

2023-02-13 16:42 UTC, jamie9504 commented on src/test/java/domain/CarsTest.java
> +                .getCars()
요거는 합칠 수 있겠죠?!
```suggestion
        assertThat(cars.getCars()
```

2023-02-13 16:42 UTC, jamie9504 commented on src/main/java/view/InputView.java
> +        validateCarNamesInputEmpty(carNames);
Input에 대한 검증과 가공을 여기서 하고 있는데, 이렇게 되면 InputView가 여러개가 된다면 (ex. consoleView, webView... etc)
각 View마다 동일한 로직을 구현해주어야만 하는 거겠죠?

이 부분이 여기에 위치하는 게 좋을지 고민해봅시다!

2023-02-13 22:44 UTC, kpeel5839 commented on src/main/java/domain/Cars.java
> +    public void moveAll(PowerGenerator powerGenerator) { // 모든 Car 들을 moveAll
아니 이것을 제가!!!!!!!

진짜 미친놈인가 봅니다 제가...

죄송합니다ㅠㅠㅠㅠ

2023-02-14 02:57 UTC, kpeel5839 commented
안녕하세요 제이미!

이번에도 제이미가 주신 피드백을 제가 할 수 있는 최선으로 해결해보았습니다!

네이밍이 정말 어렵고 책임을 분리하는 것도 정말 어렵네요 ㅠㅠ

아 그리고 커밋이 세세하지 못했던 이유는 제가 fetch, rebase 를 잘못했는데.. 해결방안을 잘 모르겠어서 일단 빠르게 리뷰요청 하려고 저장소를 전부 밀어버리고 코드를 복붙해서 옮기느라 신경쓰지 못했네요 죄송합니다 ㅠㅠ

다음부터는 잘 할 수 있도록 하겠습니다!

그리고 지금까지 정성스런 리뷰 주셔서 너무 감사합니다.

제이미의 리뷰가 너무 너무 좋았어서 한편으로 걱정이 되기도 하네요!

이 이후로 제 눈이 너무 높아지지 않을까 해서요! 허허허

제이미, 오늘도 행복하세요!😀

2023-02-14 11:29 UTC, jamie9504 approved these changes
매튜, 안녕하세요! 리뷰어 제이미입니다 😄 

우테코 첫 미션이 종료되었습니다. 👏 👏 👏 👏 👏

피드백을 조금 남겨두었으니, 수정을 해봐도 좋고, 고민만 해봐도 좋고, 넘겨도 좋을 것 같아요 😃 
새로운 미션이 시작된만큼, 새 미션에 집중하는 것도 좋은 선택이라고 생각합니다.

네이밍과 책임 분리는 저도 항상 어렵습니다. 언제쯤 쉬워질 수 있을까요 😢 
조금 더 시간이 지나면, 자주쓰는 표현들이 생기게 될거고 그때쯤엔 지금보다는 수월해질거에요!

이번에 fetch, rebase를 잘못 사용해서 커밋을 제대로 못하셨다고 하셨는데,
다음엔 동일한 실수를 하지 않도록 시간이 되실 때 git에 대해 간단히 공부해보는 것도 좋겠네요.
실수가 가끔은 성장을 위한 원동력이 되기도 하더라구요.

저도 덕분에 서로 피드백을 나누며 즐거운 시간 보낼 수 있었습니다. 😄 

남은 우테코 기간도 행복하게 지내실 수 있길 바라며, 다음에 또 만나요!
이만 Approve합니다. 👍

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/Cars.java
> +    public void moveAll(PowerGenerator powerGenerator) { // 모든 Car 들을 moveAll
코드를 짜다보면 놓칠 수도 있죠!
최대한 놓치지 않도록 신경써보아요 😄

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/controller/RacingController.java
> +        List<String> carNamesByDivider = carNamesDivider.divideCarNames(carNames);
변수명.. 저도 맨날 고민하게 되는 부분인데요!

`String carNames` 라고 했을 때 뒤에 's'가 오면 꼭 이것이 복수일 것 같다는 느낌을 주곤 합니다.
한국어로 표현해보자면 해당 변수는 '차의 이름들'을 가지고 있을까요, '차들의 이름'을 가지고 있을까요?
`carNames`와 `carsName` 이런 뉘앙스의 차이도 고민해보면 좋을 것 같아요.

---

carNamesByDivider과 같이 변수명이 길어지는 이유는 종종 위의 변수와 겹쳐지기 때문이기도 합니다.
전치사를 사용하는 건 나쁘진 않지만, 어떤 행위에 의한 변수라면 `~된 oo` 이런 느낌으로 이름을 지어줘도 좋다고 생각하는데 매튜의 의견은 어떨까요?
`dividedCarNames` 처럼요 😄

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/controller/RacingController.java
> +        GameCount gameCount = new GameCount(inputView.requestNumberOfTimes());
괄호 안에서, 어떠한 메서드에서 결과값을 가져온 것을 파라미터로 넣으면 때때로 가독성이 좋지 않게 느껴지기도 합니다.

```java
        GameCount gameCount = new GameCount(inputView.requestNumberOfTimes());

        int numberOfTimes = inputView.requestNumberOfTimes()
        GameCount gameCount = new GameCount(numberOfTimes);
```

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/Car.java
> +
Equals랑 HashCode를 재정의할 때는 조금 도메인의 성격을 고민해보아야 합니다.

중복이 발생할 때 검증을 하기 위해서 해당 메서드들이 오버라이드되어 사용되고 있는데요.

Car라는 도메인만 봤을 때, name이 같으면 같은 Car라고 볼 수 있는가!
- name은 유니크한 값이라, name이 같다면 그것은 무조건 같은 차이다. = name만 사용
- name은 유니크한 값은 아니고, cars의 조건이 같은 이름의 차가 묶일 수 없는 것이었다. = cars에서 이름이 같은지 검증

이 둘 중 무엇이 답이라곤 할 수 없고, 매튜가 만든 car가 어떤 도메인인지 고민을 해서 사용하면 좋을 것 같아요! 😄

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/CarName.java
> +    }
한 메서드에서 너무 많은 책임을 가지고 있어요!

`name.trim()`을 생성자에서 먼저 호출하고, 여기서는 trim된 name을 받아서, validation만 해주어도 되지 않을까요?

validate로 메서드 이름이 시작되면 종종 이 메서드는 void를 리턴할거야, 라는 생각을 하곤 합니다!

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/GameCount.java
> +    private static final String NON_INTEGER_ERROR = "숫자만 입력 가능합니다.";
ExceptionMessage를 상수화하셨는데, 뒤에 Message같은게 붙어도 좋을 것 같아요!

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/GameCount.java
> +    private static final int COUNT_NO_MORE = 0;
이게 무엇이다!가 가장 뒤에 오는 게 조금 더 잘 읽히는 느낌이 들어요!
(취향따라 달라질 수도 있겠어요)
`COUNT_NO_MORE` / `NO_MORE_COUNT`

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/domain/GameCount.java
> +        }
테스트 코드 반영 👍

2023-02-14 11:29 UTC, jamie9504 commented on src/main/java/util/CarNamesDivider.java
> +}
안에 변수가 없는, 즉 상태가 없는 객체는 유틸성 클래스(모든 메서드가 static)와 차이가 무엇일까요?

객체가 차의 이름들을 받아서 차 이름을 나누는 책임을 가진다면, 그 책임을 가진 객체는 어떤 객체일까요?
이런 객체를 원시값 또는 컬렉션을 포장한 객체로 두는 게 좋을지, 유틸성 클래스로 두는 게 좋을지 고민해봅시다 😄

2023-02-14 11:29 UTC, jamie9504 commented on src/test/java/domain/GameCountTest.java
> +    void proceedOnce() {
아래서 검증하는 바가 테스트명에 드러나지 않은 것 같아요!

2023-02-14 11:29 UTC, merged

2023-02-14 11:40 UTC, kpeel5839 commented on src/main/java/domain/GameCount.java
> +    private static final int COUNT_NO_MORE = 0;
No 가 앞으로 와도 되는군요 역시 항상 배웁니다!

2023-02-14 11:42 UTC, kpeel5839 commented on src/main/java/controller/RacingController.java
> +        List<String> carNamesByDivider = carNamesDivider.divideCarNames(carNames);
> 전치사를 사용하는 건 나쁘진 않지만, 어떤 행위에 의한 변수라면 ~된 oo 이런 느낌으로 이름을 지어줘도 좋다고 생각하는데 매튜의 의견은 어떨까요? dividedCarNames 처럼요 😄

너무 좋은 것 같습니다! 항상 가르침 주셔서 정말 너어어어어어어무우우우 감사합니다

2023-02-14 11:42 UTC, kpeel5839 commented on src/main/java/controller/RacingController.java
> +        List<String> carNamesByDivider = carNamesDivider.divideCarNames(carNames);
> String carNames 라고 했을 때 뒤에 's'가 오면 꼭 이것이 복수일 것 같다는 느낌을 주곤 합니다.
한국어로 표현해보자면 해당 변수는 '차의 이름들'을 가지고 있을까요, '차들의 이름'을 가지고 있을까요?
carNames와 carsName 이런 뉘앙스의 차이도 고민해보면 좋을 것 같아요.

이런 부분도 신경쓰도록 하겠습니다!

2023-02-14 11:44 UTC, kpeel5839 commented on src/main/java/controller/RacingController.java
> +        GameCount gameCount = new GameCount(inputView.requestNumberOfTimes());
제이미의 피드백을 받고, 추출해보려고 노력하는데 기준을 세우기가 쉽지 않네요ㅠㅠㅠ

제이미의 피드백을 머리에 각인하여 앞으로의 미션에도 적용하면서 저만의 기준을 세워보겠습니다!

2023-02-14 11:46 UTC, kpeel5839 commented on src/main/java/domain/Car.java
> +
> name은 유니크한 값이라, name이 같다면 그것은 무조건 같은 차이다. = name만 사용
name은 유니크한 값은 아니고, cars의 조건이 같은 이름의 차가 묶일 수 없는 것이었다. = cars에서 이름이 같은지 검증
이 둘 중 무엇이 답이라곤 할 수 없고, 매튜가 만든 car가 어떤 도메인인지 고민을 해서 사용하면 좋을 것 같아요! 😄

명심하겠습니다!