[2단계 - 자동차 경주 리팩토링] 라온(문채원) 미션 제출합니다.
woowacourse/java-racingcar pull request #638
Opened 2023-02-13 08:19 UTC by mcodnjs

안녕하세요, 춘식!

늦게 제출한 1단계 실수에 이어 깃허브가 꼬이는 2단계 실수도 해버렸네요😢
너무 늦게 알아버린 탓에 step3 branch를 새로파서 PR 날립니다 ㅠㅠ .. 부끄럽네요 죄송합니다 ㅠㅠ 
step2 commit 내역들은 링크 참고하시면 좋을  것 같아요 .. : )

2023-02-13 15:45 UTC, bimppap requested changes
안녕하세요 라온! 커밋 내역은 잘 읽고 왔으니 걱정 마세요ㅎㅎ
리팩토링한 부분을 명시해준 덕분에 코드를 읽는게 더욱 수월했어요. 👍 
1단계에 비해 많이 개선된 것 같네요!
더 좋아질 수 있는 부분들에 대해 코멘트 남겼으니 확인 부탁드립니다. 😉

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/utils/NumberGenerator.java
>  	public int getNumber();
```suggestion
	public int generateNumber();
```
get~ 는 보편적으로 getter에만 쓰이기 때문에 이 경우 다른 네이밍을 쓰는게 좋을 것 같습니다 😉

2023-02-13 15:45 UTC, bimppap commented on README.md
>  ## 기능 요구사항
꼼꼼한 요구사항 작성 매우 좋습니다 👍

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/domain/RacingCars.java
>  	public static void add(Car car) {
RacingCars 필드변수와 메서드들을 static으로 만든 이유가 있을까요?

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/controller/CarController.java
> +		while (!inputRoundCount()) ;
입력값이 조건과 다르면 재입력이 가능하도록 했군요! 꼼꼼한 로직 👍

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/controller/CarController.java
> +			carNames.stream().forEach(carName -> racingCars.add(new Car(carName)));
```suggestion
			carNames.stream()
			    .forEach(carName -> racingCars.add(new Car(carName)));
```
스트림은 연산자마다 줄바꿈을 해줘야 가독성이 좋습니다 😉

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/controller/CarController.java
> +		while (!inputRoundCount()) ;
조금 아쉬운 점이 있다면 inputCarNames 과 같은 메소드명이라면 일반적으로 String 또는 List<String>과 같은 타입의 입력값이 오길 기대합니다. 여기서는 boolean 타입을 반환하고 있는데 더 좋은 방법은 없을까요? 🤔

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/domain/RacingGame.java
> +	List<Car> cars = RacingCars.getCars();
RacingCars를 static하게 가져온 이유가 있을까요? 생성자를 통해 외부에서 넘겨주면 안되는 걸까요?

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/domain/RacingGame.java
> +	}
코드 포맷팅을 생활화합시다 😎

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/utils/RandomNumberGenerator.java
>  public class RandomNumberGenerator implements NumberGenerator {
이 [사유](https://stackoverflow.com/questions/54629033/cast-to-int-vs-math-floor)로 캐스팅 대신 Math.floor를 쓰는 것을 추천합니다!

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/utils/RandomNumberGenerator.java
>  public class RandomNumberGenerator implements NumberGenerator {
여담으로 casting과 parsing의 차이를 알아보는 것도 좋을 것 같습니다!

2023-02-13 15:45 UTC, bimppap commented on src/test/java/racingcar/domain/RacingGameTest.java
> +	class CarsMovementTest {
> 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.

테스트를 할 때는 경계값을 확인하는 것이 좋습니다! 여기서는 3,4가 되겠네요.

2023-02-13 15:45 UTC, bimppap commented on src/test/java/racingcar/domain/RacingGameTest.java
> +	class ZeroGenerator implements NumberGenerator {
테스트용 NumberGenerator 👍

2023-02-13 15:45 UTC, bimppap commented on src/test/java/racingcar/domain/RacingGameTest.java
> +	@Nested
`@Nested` 를 쓰고 있군요! 이렇게 그룹화를 하면 이렇게 `@DisplayName`을 활용해볼 수도 있답니다.

```
@Nested
    @DisplayName("many car")
    class CarsTest {

        @Test
        @DisplayName("can move at once")
        void moveAll() {
           // test code here
        }
    }
```

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/domain/Name.java
> +public class Name {
원시값 포장 👍

2023-02-13 15:45 UTC, bimppap commented on src/main/java/racingcar/domain/RacingGame.java
> +public class RacingGame {
> 사실 MVC 패턴을 사용하는 것과 Service, Repository를 사용하는 것의 차이는 크게 와닿지 않더라구요 .. Service와 Repository를 사용하는 경우는 MVC 패턴을 조금 더 세부적으로 나누고 DB를 사용할 때 Entity와 DTO 등을 사용할 수 있는 구조 정도로 이해했는데 맞을까요 ? 춘식이 왜 MVC 패턴을 적극적으로 활용하라고 하셨는지도 궁금합니다 !!

라온의 말대로 Service와 Repository는 보다 세세하게 나눠진 MVC 패턴에서 나온 것이라 보면 됩니다! 아래 이미지가 이해를 도왔으면 좋겠네요.
![image](https://user-images.githubusercontent.com/48675973/218499869-a915d7c1-4023-4aed-916e-aee2a304d6d2.png)
(당장은 Spring Framework에 대해 알 필요가 없습니다. 그냥 이런게 있구나 정도로만 알아두면 됩니다ㅎㅎ)

MVC 패턴을 적극적으로 활용하라고 한 이유는 너무 복잡하게 생각하지 말란 뜻이었습니다.🥲 당연히 Service와 Repository를 써도 되긴 하지만, 프로젝트의 규모 대비 비용을 더 쓰게 될 수도 있어서요. 그래도 시도해보면서 많은 공부가 됐을거라 봅니다! 😉

2023-02-14 00:48 UTC, mcodnjs commented on src/test/java/racingcar/domain/RacingGameTest.java
> +	@Nested
오 `@Nested`와 `@DisplayName`을 같이 사용할 수도 있네요. 팁 감사합니다!
`@Nested` 아래부터 탭이 한 칸 더 들어간 것은 오타일까요 ?! 아니면 보통 그렇게 사용하나요 ?!

2023-02-14 00:51 UTC, mcodnjs commented on src/main/java/racingcar/domain/RacingGame.java
> +public class RacingGame {
아하! 어떤 의도로 말씀하셨는지 완벽히 이해가 되네요! 
찜찜했는데 개념을 명확히 잡고 간 것 같아서 마음이 편안하네요 ㅎㅎ 감사합니다 :)

2023-02-14 02:26 UTC, mcodnjs commented on src/main/java/racingcar/utils/RandomNumberGenerator.java
>  public class RandomNumberGenerator implements NumberGenerator {
캐스팅이 음수에서는 그런 단점이 존재하는지 처음 알았습니다 ㅎㅎ.. 감사합니다 ( _ _ )
다만 이 문제에서는 **int로 캐스팅해주는 이유가 double을 int로 반환해주기 위해서**인데, 
**`Math.floor()`의 반환값도 double이어서 해당 문제는 `Math.floor()`로 해결불가능하다고 생각**되는데 맞을까요 ?!

2023-02-14 06:00 UTC, mcodnjs commented on src/main/java/racingcar/domain/RacingCars.java
>  	public static void add(Car car) {
이 부분은 정확히 제가 이해하지 못하고 넘어갔습니다 .. 그래서 페어에게 다시 여쭤봤는데요!
cars를 db의 respository라고 보았을 때, 해당 객체는 전체 서비스에서 동일한 객체로 다뤄져야하는데 이를 위해 static 을 사용하였습니다. 이러한 관점에서 보았을 때 static 사용은 올바르다고 생각되는데 .. static을 사용하지 않는다면, 해당 cars를 사용하는 모든 class에서 동일한 cars를 가져오기 위한 다른 방법이 필요하다고 생각합니다. 

저는 이러한 생각을 가지고 있는데, 올바른 접근 방법인지는 .. 사실 자신은 없네요 🤐

2023-02-14 06:08 UTC, mcodnjs commented on src/main/java/racingcar/domain/RacingGame.java
> +	List<Car> cars = RacingCars.getCars();
이 부분도 [위](https://github.com/woowacourse/java-racingcar/pull/638#discussion_r1105328203)와 같은 이유로 static하게 사용하였습니다 .. !

2023-02-14 11:04 UTC, mcodnjs commented on src/main/java/racingcar/controller/CarController.java
> +		while (!inputRoundCount()) ;
해당 부분에 대한 문제점을 인지하였고, 많은 고민을 하며 수정해보려 하였으나 좋은 방법이 떠오르지 않았어요 😢

고민 끝에 [수정한 사항](https://github.com/woowacourse/java-racingcar/pull/638/commits/b08c52a81643882275dd8b381035e75ffda4f367)은, 
- 우선 `inputCarNames()` 메서드에서 input 을 받는 부분과 생성한 car를 RacingCars에 추가하는 메서드를 분리하였고,
- `try~catch`를 통하여 오류가 발생하면 false를 반환하는 `isValidInput()` 이라는 메서드를 구현하였습니다. 

잘못된 입력이 들어왔을 때는 재입력이 항상 필요한데, 제가 수정한 방식은 결국엔 try~catch 같은 중복되는 로직을 input 마다 반복해요. 결국엔 input이 많아지면 해당 로직을 가진 while문도 계속 반복되게 되는데, 좋은 코드라는 생각은 안들더라구요.. 그래서 다른 크루들의 코드를 찾아보았는데 `supplier` 라는 함수형 인터페이스를 사용하여 제어하는 것을 보았습니다. 처음 접해보는 개념이라 당장 적용하기에는 힘들다고 생각하여 적용은 못해봤습니다. 혹시 춘식이 생각하기에 더 좋은 알고리즘이나 방법이 있을까요 ? 

(또 다른 방법으로는,  input을 받았을 때 `carNames.size() == 0`, `roundCount < 0` 과 같은 방식을 통하여 로직을 제어할 수 있지만, 그게 결국에는 inputView에서 검증한 로직과 똑같아서 이것 또한 중복 코드라는 생각이 들었습니다 ㅠㅠ)

2023-02-14 11:11 UTC, mcodnjs commented
수정 코멘트 남겨주신 부분은 모두 수정했습니다!
다만, 아래 두 부분에 대해서는 명확한 답변을 하진 못했습니다 :( 

> 조금 아쉬운 점이 있다면 inputCarNames 과 같은 메소드명이라면 일반적으로 String 또는 List과 같은 타입의 입력값이 오길 기대합니다. 여기서는 boolean 타입을 반환하고 있는데 더 좋은 방법은 없을까요? 🤔 ([답변](https://github.com/woowacourse/java-racingcar/pull/638#discussion_r1105633413))

> RacingCars 필드변수와 메서드들을 static으로 만든 이유가 있을까요? ([답변](https://github.com/woowacourse/java-racingcar/pull/638#discussion_r1105328203))

최대한 저의 생각을 녹여서 답변을 하였는데 추가 코멘트 있으시면 해주시면 감사하겠습니다!

2023-02-14 14:04 UTC, bimppap commented on src/test/java/racingcar/domain/RacingGameTest.java
> +	@Nested
오타입니다ㅎㅎ 제가 급하게 쓰느라 제대로 확인을 못했네요 😂

2023-02-14 15:41 UTC, bimppap commented on src/main/java/racingcar/domain/RacingCars.java
>  	public static void add(Car car) {
static은 자주 사용하지만 `절대 변하지 않는 변수, 즉 상수`일 때 사용하는 것이 좋습니다. static에 관한 재미난 글이 있는데 한번 읽어보면 좋을듯 해요!

 [Why are static variables considered evil?](https://stackoverflow.com/questions/7026507/why-are-static-variables-considered-evil)

사용범위를 보면 RacingCars는 CarController에서 만들어서 RacingGame에서만 쓰이고 있네요! 이 경우 Controller에서 RacingGame에 RacingCars를 주입하는 방향으로 가도 다른 코드에 영향을 주지 않을 것 같습니다. 테스트도 마찬가지고요.

2023-02-14 15:57 UTC, bimppap commented on src/main/java/racingcar/utils/RandomNumberGenerator.java
>  public class RandomNumberGenerator implements NumberGenerator {
제가 요즘 typescript를 배우고 있어서 반환 타입을 헷갈렸네요 ^^;;
찾아보니 아래와 같이 사용해도 될 것 같습니다.
```
Double.valueOf(Math.random()*10).intValue();
```

2023-02-14 16:35 UTC, bimppap commented on src/main/java/racingcar/controller/CarController.java
> +		while (!inputRoundCount()) ;
`메소드명에 따라 기대되는 타입이 있다`에 유념하여 코드를 재구성했다는 것만으로도 의미가 있다고 봅니다.
리팩토링과 관련해 저는 이런 구조를 생각했었는데, 라온의 방식도 좋다고 생각해요! 코드에 정답은 없으니까요 😉 

```java
public void run() {
    RacingCars cars = inputCars();
    // ...후략
}

private RacingCars inputCars() {
     try {
         List<String> carNames = inputCarNames();
         // carNames를 이용해 RacingCars 인스턴스 생성 후 반환
     } catch (Exception e) {
         // 에러처리
         return inputCars();
     }
}
```

이렇게 할 수도 있구나 정도로만 봐주면 좋겠습니다 :)

2023-02-14 16:39 UTC, bimppap commented on src/main/java/racingcar/controller/CarController.java
> +		while (!inputRoundCount()) ;
라온 말대로 try-catch 와 같은 중복을 피하기 위해 supplier를 쓰기도 하지만 꼭 알아둘 필요는 없으니 넘어가도 좋습니다! 

+ 사족을 조금 붙여보자면, 저도 이 미션을 할 때 함수형 인터페이스는 꿈도 못 꿨습니다ㅋㅋ 하다보면 언어에 대한 이해도가 높아지면서 어려워 보이던 것도 자연스럽게 쓸 수 있는 때가 오니 본인 페이스에 맞춰 공부하면 됩니다. 제가 볼 때 라온은 충분히 잘해내고 있습니다. 👍 👍

2023-02-14 16:50 UTC, bimppap approved these changes
안녕하세요 라온! 피드백 반영 너무 잘해주셨어요 💘 
첫 미션은 여기서 마무리 지어도 좋을 것 같아 approve 하겠습니다.
질문에 대한 코멘트도 남겨놨으니 확인 부탁드립니다.
코멘트 관련 리팩토링을 더 해보고 싶다면 언제든지 DM으로 찾아와주세요. 😄
수고하셨습니다!! 남은 미션도 파이팅입니다 🔥

2023-02-14 16:50 UTC, merged

2023-02-14 23:26 UTC, mcodnjs commented on src/main/java/racingcar/domain/RacingCars.java
>  	public static void add(Car car) {
이 경우에 static 사용은 저도 크게 와닿진 않네요 😅 
링크에서는 static 사용의 다양한 장단점을 토론하고 있네요 ㅎㅎ 
참고해서 보겠습니다 감사합니다 ~!