1단계 미션 제출합니다.
woowacourse/java-racingcar pull request #650
Opened 2024-02-15 03:12 UTC by robinjoon

**레이싱 카 미션 구현을 위해 요구사항을 다음과 같이 해석했습니다.**

## 요구사항 해석

1. 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
    - n 은 2 이상 10 이하의 정수만 가능하다.
2. 각 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
3. 자동차 이름은 쉼표(,)를 기준으로 구분하며 이름은 5자 이하만 가능하다.
    - 자동차 이름은 알파벳 대문자 혹은 소문자의 조합으로 이루어져있어야 한다.
    - 각 자동차 이름은 중복될 수 없다. 대소문자를 구분한다.
    - 자동차 이름은 1글자 이상이어야 한다.
4. 사용자는 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
    - 이동 횟수는 1 이상 100이하의 정수만 가능하다.
5. 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4 이상일 경우 전진하고, 3 이하의 값이면 멈춘다.
6. 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한 명 이상일 수 있다.
    - 최종 이동 거리가 제일 먼 자동차가 우승한다.
7. 사용자가 잘못된 입력을 한 경우, 해당 입력부터 다시 수행한다. 이전에 입력한 내용은 그대로 유지된다.
    - 입력이 왜 잘못되었는지 에러 메세지를 출력한다.
    - 5번째 재입력이 잘못된 입력인 경우 프로그램을 종료한다. 이때, 비정상 종료 메세지를 출력한다.

## 기능 목록
위 요구사항을 기반으로 아래와 같은 기능 목록을 작성했습니다.

- [x] 자동차 이름 입력 기능
- [x] 자동차 이동 횟수 입력 기능
- [x] 지동차 이동 기능
- [x] 랜덤 숫자 생성 기능
- [x] 우승자 판별 기능
- [x] 결과 출력 기능
- [x] 입력 가이드 출력 기능
- [x] 잘못된 입력 처리 기능

2024-02-15 13:24 UTC, lxxjn0 requested changes
안녕하세요, 로빈 :)
이번에 리뷰를 맡게 된 스티치라고 합니다.

우테코의 첫 미션이라고 하기에는 정말 코드를 잘 작성하신 것 같아요 👍🏼 

코드의 전반적인 부분에 대해서 피드백을 드리고는 싶지만, 그러기 보다는 자동차 미션에서 숙지하고 넘어가야 할 중요한 부분에 대해서 좀 더 집중적으로 리뷰를 드리기로 하였습니다. 그래서 생각했던 것 보다는 피드백이 조금은 쉬워보일 수도 있습니다. 

그래도 쉬운 것이 중요하지 않은 것은 아니기에, 잘 확인하고 고민해보고 피드백 반영 부탁드리겠습니다 :)

추가로 반복적으로 피드백이 필요한 부분에 대해서는 따로 코멘트를 더 남기지는 않았습니다. 제가 작성한 피드백은 전체 코드에 해당하는 피드백이라고 생각하고 코드 전체적으로 반영해주시면 좋을 것 같아요 😃

2024-02-15 13:24 UTC, lxxjn0 commented on README.md
> +## 요구사항 해석
미션 요구사항과 구현할 기능을 잘 작성하였네요. 커밋도 기능 구현 단위로 잘 작성해주셨어요 👍🏼

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +public class RacingManager {
[질문] 전체적으로 Manager라는 이름을 많이 사용하신 것 같아요. 혹시 어떠한 의도나 목적을 가진 클래스에 Manager라는 이름을 붙이셨을까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +    }
[제안] 메서드의 길이가 15줄을 넘진 않았지만, 로빈의 기준에 따라 조금 더 나눠보는 것은 어떨까요? 그리고 코드에 공백(blank line)을 사용하지 않는데 공백을 적절하게 사용해보면 어떨까요?

[질문] 위 제안에 따라 메서드를 나눠본다면 기존에 비해 어떠한 점이 달라졌나요? 만약 공백을 추가하였다면 공백을 적절히 활용한 코드와 그렇지 않은 코드의 차이점은 어떤 점이 있나요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/util/RetryHelper.java
> +    }
[제안] 해당 부분은 지극히 개인적인 제안이니 참고만 해주세요 :) 

null을 return하는 부분이 catch 문 밖에 있어야 할 이유가 없어보였어요. try 문에서 early return을 해준다면, null을 return하는 케이스는 catch 문을 통과한 케이스 뿐입니다. 그렇다면 null을 return하는 것은 catch 문에서 행해지는 행위로 보여지고 동일한 맥락에서 진행되어야 하는 코드가 모여있다면 코드를 읽는 사람으로 하여금 더 좋은 가독성을 제공해 줄 수 있다고 생각합니다.

```suggestion
    private <E> E useSupplier(Supplier<E> supplier) {
        try {
            return supplier.get();
        } catch (RuntimeException e) {
            System.out.println(e.getMessage());
            return null;
        }
    }
```

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +        RetryHelper carNameInputManager = new RetryHelper(5);
변수 이름과 변수에 할당되는 객체 타입이 매칭이 되지 않는 것 같아요. 생성된 객체에 맞는 적절한 이름을 지어보면 어떨까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +                .map(name -> new Car(0, name))
자동차가 처음 생성될 때의 위치를 0으로 할당하는 것으로 보여지네요. 생성자의 다양한 활용을 통해 해당 부분을 개선해 볼 수 있지 않을까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +    static List<String> getName(String input) {
[질문] 해당 메서드의 접근지정자를 package-private으로 설정하신 이유가 무엇인가요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +        if (input.startsWith(",") || input.endsWith(",")) {
`,`이 자동차 이름을 입력받는 비즈니스 로직에서 어떠한 의미를 가지고 있나요? 만약 특별한 의미를 가지고 있다면 어떻게 처리하면 더 좋은 코드가 될 수 있을까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +        }
해당 로직에서 발생되는 예외 메시지가 적절하지 않은 것으로 보여져요.

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +    }
[제안] 해당 메서드도 공백없이 꽉 채워서 15라인을 맞춘 것 같아요. 메서드를 적절히 분리를 해보면 어떨까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +public class CarNameInputManager {
해당 클래스 내에서 매직 넘버와 같은 값들이 많이 보입니다. 비즈니즈 적으로 유의미한 값이라면 어떠한 방법으로 값에 의미를 부여할 수 있을까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/input/RacingMaxTurnInputManager.java
> +    }
[제안] 해당 메서드를 적절하게 분리한다면 좀 더 가독성이 좋고 행위가 구분되어 보여질 수 있을 것 같아요.

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/output/RacingResultOutputManager.java
> +    }
자동차의 위치를 출력하는 방식을 출력을 담당 클래스에서 결정할 수 있도록 코드를 작성하였군요! 덕분에 출력 로직이 자동차 위치나 이름을 관리하는 도메인 로직과 의존성을 가지지 않게 될 수 있었던 것 같네요 👍🏼

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingDTOMapper.java
> +}
[제안] 해당 클래스는 현재 미션에서 굳이 구현되어야 할 클래스는 아닐 것 같아요. 만약 꼭 사용하고 싶다면 해당 클래스가 도메인 로직에 해당하는 게 맞는가에 대해서 한번 고민해보시는 것도 좋을 것 같습니다.

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/Car.java
> +    }
해당 코드에도 매직 넘버가 존재하는 것 같아요. 특정한 값이 가지는 의미를 이름으로 나타내보면 좋을 것 같습니다.

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/Car.java
> +    private final String name;
[제안] 현재는 Car라는 객체에서 자동차 이름에 대한 도메인 로직을 관리하고 있어요. 만약 클래스를 한번 더 분리해보면 어떨까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/Car.java
> +    }
[질문] 아무런 행위를 하지 않는 메서드인데 이렇게 만들어 두신 이유가 있을까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/Car.java
> +class Car implements Comparable<Car> {
[질문] 해당 객체의 메서드 접근지정자가 대부분 package-private으로 설정되어 있습니다. 접근지정자를 제한한 이유가 무엇일까요?

2024-02-15 13:24 UTC, lxxjn0 commented on src/main/java/racing/domain/Cars.java
> +    private final List<Car> cars;
구글 코딩 컨벤션을 참고하여 수정해보면 좋을 것 같아요.

2024-02-15 13:24 UTC, lxxjn0 commented on src/test/java/racing/domain/CarTest.java
> +class CarTest {
`hasSameDistance` 메서드에 대한 테스트가 빠져있는 것 같아요.

2024-02-15 13:24 UTC, lxxjn0 commented on src/test/java/racing/domain/CarTest.java
> +    }
테스트에서 변경된 자동차의 위치를 실제 이동시킨 자동차의 위치가 아닌, 새로 생성한 자동차 객체를 통해서 테스트하고 있어요. 로빈이 움직인 자동차의 위치를 확인해서 테스트를 해보는 것은 어떨까요?

만약, 위와 같이 테스트 코드를 작성한 이유가 따로 있다면 이야기해봐도 좋을 것 같아요 :)

2024-02-15 13:24 UTC, lxxjn0 commented on src/test/java/racing/domain/CarsTest.java
> +class CarsTest {
Cars 객체에서 활용하고 있는 메서드에 비해 테스트가 부족한 것 같아요. 유의미한 비즈니스 로직을 가지고 있는 메서드라면 해당 메서드에 대한 단위 테스트를 추가로 작성해주세요.

2024-02-15 13:24 UTC, lxxjn0 commented on src/test/java/racing/domain/RacingTest.java
> +    @MethodSource("nextTurnParameters")
JUnit의 다양한 테스트 방법을 잘 활용하셨네요 👍🏼

2024-02-15 13:59 UTC, robinjoon commented on src/main/java/racing/domain/RacingManager.java
> +public class RacingManager {
> [질문] 전체적으로 Manager라는 이름을 많이 사용하신 것 같아요. 혹시 어떠한 의도나 목적을 가진 클래스에 Manager라는 이름을 붙이셨을까요?

`무엇을 관리하는 역할을 가진 클래스`에 사용했습니다. ~ InputManager 는 사용자의 입력을 관리하여 적절한 입력이 주어졌는지 확인하고 이를 도메인 인스턴스에 전달하기 때문에, ~OutPutManager는 도메인 로직의 결과를 관리하여 적절한 포맷으로 출력하기 때문에, RacingManager 는 Racing의 생성과 관리를 하기 때문에 Manager를 붙였습니다.

2024-02-15 14:15 UTC, robinjoon commented on src/main/java/racing/domain/RacingManager.java
> +    }
> [제안] 메서드의 길이가 15줄을 넘진 않았지만, 로빈의 기준에 따라 조금 더 나눠보는 것은 어떨까요? 그리고 코드에 공백(blank line)을 사용하지 않는데 공백을 적절하게 사용해보면 어떨까요?
> 
> [질문] 위 제안에 따라 메서드를 나눠본다면 기존에 비해 어떠한 점이 달라졌나요? 만약 공백을 추가하였다면 공백을 적절히 활용한 코드와 그렇지 않은 코드의 차이점은 어떤 점이 있나요?

코멘트를 남기는 시점에서는 아직 분리를 하지 않았지만, 이 메서드는 입력, 레이싱 수행, 결과 출력 을 하기 때문에 이 3가지 역할군으로 분리할 수 있을 것 같습니다. 그리고, 중간에 공백을 추가한다면, 이 3가지 역할군을 시각적으로 분리하기 때문에 코드를 보는 사람이 3가지 역할의 존재를 더 쉽게 알 수 있을 것입니다.

2024-02-15 14:47 UTC, robinjoon commented on src/test/java/racing/domain/CarTest.java
> +    }
> 테스트에서 변경된 자동차의 위치를 실제 이동시킨 자동차의 위치가 아닌, 새로 생성한 자동차 객체를 통해서 테스트하고 있어요. 로빈이 움직인 자동차의 위치를 확인해서 테스트를 해보는 것은 어떨까요?
> 
> 만약, 위와 같이 테스트 코드를 작성한 이유가 따로 있다면 이야기해봐도 좋을 것 같아요 :)

원래 의도는 도메인 객체에 getter를 사용하지 않기 위해서 이렇게 했습니다. 그런데, 이 테스트가 작성된 한참 뒤 결국 DTO로 변환하기 위해서 어쩔 수 없이 getter를 추가했습니다.

객체에 메세지를 던질 수 있도록 코드를 고친다면, Car 객체를 매번 생성하지 않아도 될 것 같습니다. 이 경우 Car의 현재 위치가 int 인지 확인하는 메서드를 추가하면 될 것 같습니다.

2024-02-15 14:50 UTC, robinjoon commented on src/main/java/racing/input/CarNameInputManager.java
> +        }
문자열 맨 앞이나 뒤에 ","가 입력되는 것은 "," 앞 혹은 뒤에 길이가 0인 문자열이 존재한다. 라고 해석했습니다.

2024-02-15 14:53 UTC, robinjoon commented on src/main/java/racing/input/CarNameInputManager.java
> +        if (input.startsWith(",") || input.endsWith(",")) {
구분자이기 때문에, 상수로 분리하는 것이 적절할 것 같네요. 비록 한단계 더 확인해야 구체적인 구분자가 무엇인지 알 수 있지만, 상수로 추가된다면 언어의 문법의 검사 대상이 되기 때문에 오용의 여지도 적어지구요. 상수로 분리하겠습니다!

2024-02-15 15:03 UTC, robinjoon commented on src/main/java/racing/input/CarNameInputManager.java
> +    static List<String> getName(String input) {
`테스트코드를 작성하기 위해서`입니다.

`일반적으로 테스트코드를 작성하기 위해 접근제어자를 더 널널하게 푸는 것은 부작용이 크다`는 것을 잘 알고 있습니다. 도서 좋은 코드, 나쁜 코드에도 잘 나와 있는 것 처럼 이 경우 클래스를 분리하는 것이 보통은 더 나은 선택입니다.

하지만, `이 클래스는 너무나도 명확하게 사용 용도가 한정`되어 있습니다. 따라서, `같은 패키지 내의 다른 클래스에서 이를 실수로라도 사용할 가능성이 없다고 판단`했습니다. 그렇다면, 앞서 말한 원칙을 적용하지 않아도 부작용이 발생하지 않을 것이라고 생각했습니다. 반면, 이로 인해 핵심 로직 중 하나인 `입력값 검증과 콘솔 입력을 분리해 콘솔 입력을 테스트코드에서 고려하지 않게 할 수 있다는 장점은 여전히 유효`하기 때문에 접근제어자를 조금 풀어 package-private 으로 설정했습니다.

2024-02-15 15:13 UTC, robinjoon commented on src/main/java/racing/domain/RacingManager.java
> +        RetryHelper carNameInputManager = new RetryHelper(5);
`저는 지금 변수명이 복합적인 상황을 고려해 적절한 이름이라고 판단`했습니다. 아래는 그 판단에 대한 근거입니다.

RetryHelper 는 특정 로직을 일정 횟수까지 재시도할 수 있도록 해주는 유틸리티성 클래스입니다. 다만, 최대 재시도 횟수를 경우에 따라 다르게 할 수 있도록 정적 메서드 방식이 아니라, 객체를 생성하는 방식을 사용했습니다.

만약, 이 변수의 이름을 RetryHelper 라는 타입에 맞추게 된다면, `~~RetryHelper.retry(lamda);`와 같은 방식으로 사용자 입력을 받는 작업을 수행할 것입니다. 이때, **이것이 입력을 받는 행위라는 것을 알기 위해서는 lamda를 분석해야**만 합니다. 하지만, **지금의 코드처럼 변수 이름을 통해 사용자 입력을 받는 역할을 수행한다는 것을 좀 더 쉽게 알릴 수 있다고 생각**했습니다.

2024-02-15 15:19 UTC, robinjoon commented on src/main/java/racing/domain/RacingManager.java
> +                .map(name -> new Car(0, name))
여러 테스트코드에서 작성한 것 처럼 자동차가 일정 거리만큼 이동한 경우를 손쉽게 나타내기 위해서는 이를 생성자를 이용해 쉽게 만들 수 있습니다.
만약, 처음 생성될 때의 위치가 0으로 설정하기 위해, **이름만 매개변수로 받는 생성자를 만든다면, 기존의 생성자가 테스트코드에서만 사용하는 생성자**가 됩니다. **테스트에서만 사용되는 코드가 실제 코드에 존재하는 것은 부적절하기 때문에 별도의 생성자 없이 이렇게 사용**했습니다.

2024-02-15 15:22 UTC, robinjoon commented on src/main/java/racing/domain/Car.java
> +    }
개념적으로 자동차가 전진 혹은 정지 중 하나를 수행하는 것이기 때문에, 이를 좀 더 명확하게 하기 위해 메서드로 작성했습니다.

2024-02-15 15:30 UTC, robinjoon commented on src/main/java/racing/domain/Car.java
> +class Car implements Comparable<Car> {
접근지정자를 최대한 줄인다면, 클래스를 잘못 사용하는 경우를 원천적으로 차단할 수 있기 때문입니다. 다른 개발자 혹은 미래의 저는 잠재적으로 기존의 클래스들을 잘못 사용하고 고장낼 위험을 가지고 있습니다. 외부 패키지에서 접근할 수 있는 클래스와 그렇지 않은 클래스를 확실하게 한다면, 무엇이 상세 세부 구현이고, 무엇이 공개 인터페이스(자바의 인터페이스가 아니라 좀 더 범용적인 개념의)인지 명확해집니다.

2024-02-15 15:37 UTC, robinjoon commented on src/main/java/racing/domain/Car.java
> +    private final String name;
조금 더 이름 관련 도메인 로직이 복잡해질 경우 분리하는 것이 좋을 것 같습니다. 아직은 고작 6줄의 반복 없는 코드 뿐이라서 클래스 개수를 늘렸을 때의 단점이 더 큰 것 같습니다.

2024-02-16 11:03 UTC, robinjoon commented
안녕하세요. 말씀 주신 내용 중 아래 항목들을 반영했습니다.

- [x] 메서드 15줄 꽉 채운거 분리
- [x] 의미 있는 상수 추가
- [x] Cars 누락된 테스트 추가
- [x] 구글 컨벤션 적용
- [x] RetryHelper early return
- [x] DTO Mapper 삭제

상수를 추가하는 과정에서 자동차 이름의 제한을 검증하는 것을 다른 클래스로 분리하는 것으로 결정했습니다. 그 이유는, 사용자 입력에서도 이를 처리해야 하고, 이를 도메인 패키지 내의 public 클래스로 추가하여 나머지 클래스들의 접근지정자를 그대로 유지하기 위함입니다.

Car의 생성자나, 일부 변수의 네이밍은 답변 드린 것 처럼 합리적인 이유가 있다고 생각해 그대로 유지하였습니다.

2024-02-17 10:10 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +public class RacingManager {
Manager라는 이름은 클래스의 책임이나 역할을 표현하기엔 그 의미가 모호한 것 같습니다. 입력을 받는 곳이라면 단순하게 InputView와 같은 이름도 좋을 것 같구요. 

로빈이 지은 클래스 이름들은 도메인 위주로 설계된 코드라기 보다는 보편적인 웹 어플리케이션 코드에서 만나기 쉬운 이름들로 선택되어서 지어진 것 같아요. RacingManager는 사실 입력도 받아오고 출력도 하며 레이싱 게임의 전반적인 진행 과정이라는 비즈니스 로직을 전개하는 클래스로 보입니다. 그렇다면 오히려 RacingGame과 같이 자동차 게임의 진행 비즈니스를 관리하는 이름으로 선택해도 될 것 같고요.

이번 미션에서는 로빈이 클래스를 설계했을 때 어떠한 역할과 책임을 가지는지 고민하고 그에 맞는 이름을 직접 선택해서 지어보는 연습을 해보는 것도 좋을 것 같습니다.

2024-02-17 11:05 UTC, lxxjn0 approved these changes
피드백 반영하시느라 수고 많으셨습니다 👍🏼 

이번 리뷰는 앞선 질문들에 대한 코멘트 위주로만 마무리해도 괜찮을 것 같습니다. 제가 추가로 남긴 코멘트를 한번 읽어보시면서 다음 단계 진행해주시면 좋을 것 같습니다.

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +                .map(name -> new Car(0, name))
제가 느끼기에 로빈이 말한 아래 대답이 오히려 비즈니스 로직보다는 테스트에 초점을 맞추고 작성하신 느낌이 들어요. 

> 여러 테스트 코드에서 작성한 것 처럼 자동차가 일정 거리만큼 이동한 경우를 손쉽게 나타내기 위해서는 이를 생성자를 이용해 쉽게 만들 수 있습니다.

오히려 비즈니스 로직을 중점에 둔 코드였다면 모든 자동차는 처음 0인 위치에서 출발할 수 있도록 생성자를 제한하는게 맞지 않을까요? 지금의 코드는 개발자가 언제든 0이 아닌 다른 위치에서 출발하는 자동차를 만들 수 있는 위험이 있어보여요.

그리고 생성자는 객체를 생성하기 위해 존재하는 메서드입니다. 그렇다면 사용자가 객체를 다양한 방식으로 생성할 수 있도록 지원해 줄 수 있고, 개발자의 의도에 맞게 이를 제한해서 특정한 케이스의 객체만 생성할 수록 제한할 수도 있어요. 둘 중 어느 방향을 정해서 개발을 할지는 개발자의 몫이라고 생각합니다.

단지 제가 느끼기에는 테스트에서만 사용되는 메서드를 만드는 것이 부적절하다면 비즈니스 로직에 대한 중점도를 높이 가져간다는 방향으로 보여지는데, 그러기에 위 생성자는 비즈니스 로직을 드러내기엔 적절하지 않은 생성자라는 생각이 들어서요.

이 부분은 로빈이 잘 생각해보고 결정하시면 좋을 것 같습니다 👍🏼

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/Car.java
> +    }
메서드는 행위를 나타내기 위한 코드입니다. 행위가 없는 메서드는 메서드로써의 의미가 없습니다. 단순히 코드에서 go를 실행하지 않으면 정지된 상태라는 것을 충분히 알 수 있지 않을까요?

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +        if (input.startsWith(",") || input.endsWith(",")) {
'언어의 문법의 검사 대상'이라는 말씀이 어떠한 말인지 제대로 이해하진 못했는데 컴파일러에서 문법 오류 검증을 할 때의 대상이 되는 값이라고 생각하고 답변을 달도록 하겠습니다. 제가 생각하는 상수 사용의 장점은 위 장점보다는 아래의 상황에서의 장점이 더 크다고 생각합니다.

이번 자동차 게임에서 자동차의 이름을 구분짓는 문자를 /로 바꾼다고 한다면 상수로 치환된 코드와 기존의 코드, 어떤 코드가 더 변경에 유연하게 대처할 수 있을까요? 

우리가 매직넘버라고 일컫는 값들은 비즈니스 로직에서 유의미한 값을 말합니다. 지금처럼 ,는 단순히 문법 검사 대상이라기보다는 '자동차의 이름을 입력받을 때 사용되는 구분값'이라는 비즈니스 적인 의미를 지는 값입니다. 이를 상수로 뺀다면 추후 이 구분값이 변경된다면 상수의 코드만 변경하면 그 이상의 대응은 필요하지 않게 됩니다. 상수가 가지는 장점을 단순히 코드 상의 이점이라기 보다는 비즈니스 로직을 드러낼 수 있으며, 추후 변경에 대해서 더 용이한 코드라는 부분을 생각해보면 좋을 것 같아 코멘트 남겨봅니다.

2024-02-17 11:05 UTC, lxxjn0 commented on src/test/java/racing/domain/CarTest.java
> +    }
getter를 왜 최대한 지양하라고 이야기 하는지에 대해서 한번 고민해보면 좋을 것 같아요. 코틀린의 경우 언어에서 기본적으로 프로퍼티에 대한 값을 읽을 수 있는 getter를 지원하고 있습니다. 만약 getter를 지양하는 것이 더 올바른 코드라면, 이러한 언어의 설계는 잘못된 방향이지 않을까요? 그렇지 않다면 getter를 단순히 지양해야 하는 것이 아니라는 생각도 해볼 수 있을 것 같아요.

getter를 어떠한 상황에서는 사용하는 것이 적절한지, 어떤 상황에서 문제가 발생할 수 있어서 사용을 지양하는 지를 한번 공부해보시는 것을 추천드리겠습니다.

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/input/CarNameInputManager.java
> +    static List<String> getName(String input) {
이 부분은 위에 [다른 코멘트](https://github.com/woowacourse/java-racingcar/pull/650/files/d09de4babd9125fb5518f05ff6b00eac48ee5839#r1490984912)에서 로빈이 이야기한 내용과 의견이 상충되는 것 같은데 혹시 제가 잘못 이해하고 있는 것일까요? 

로빈은 접근 지정자를 '외부 패키지에서 접근할 수 있는 메서드와 그렇지 않은 메서드를 확실하게 구분짓기 위한 용도'로 사용하려고 하는 것 같습니다. 그러나 지금처럼 '명확하게 사용 용도가 한정'된 경우는 이러한 단점이 존재하지 않게 될까요? 

접근 지정자는 사용자가 객체에 접근할 수 있는 메서드의 접근 범위를 지정하는 용도입니다. 이는 개발자 본인이 아닌 다른 누구는 언제든지 해당 접근 범위에 해당된다면 메서드를 사용할 수 있게 됩니다. 현재 메서드는 '실수로라도 사용할 가능성이 없다고 판단'하셨다고 했는데 어떠한 개발자든 모두 이 의도를 명확히 이해하고 사용하지 않을 것이란 확신이 있으신 걸까요? 제가 생각하기에는 코드 상에서는 그렇게 할 어떠한 제약 조건도 존재하지 않는 것으로 보입니다. 접근 지정자를 private로 변경하지 않는 이상은요.

해당 메서드의 접근 지정자가 package-private 라는 것이 문제는 아니라고 생각합니다. 단지 코드를 작성하는 개발자가 코드를 작성할 때 코드 전체에 일관된 맥락을 유지하지 않는다면 코드를 사용하거나 읽는 사람은 그 맥락을 이해할 수 없습니다. 어떤 코드는 package 레벨에서 사용할 수 있도록 오픈했는데 어떤 코드는 오픈이 되어있지만 사용하지 말라고 하는 말이 되어버리니깐요.

접근 지정자를 public으로 연다는 것은 누구나 해당 메서드를 접근할 수 있습니다. 그러나 해당 메서드가 순수 함수로써 side-effect를 만드는 함수가 아니라면 public으로 메서드를 오픈하더라도 별 다른 문제가 발생할 상황은 없을 것으로 보여집니다. 또는 public으로 열린 메서드를 활용해 private 메서드를 테스트 할 수도 있겠지만, 이는 코드의 로직 변경에 너무 기민하게 반응하는 테스트 코드가 될 수도 있겠지요.

이러한 다양한 관점을 생각해보면서 한번 접근 지정자에 대해 고민해보는 것도 좋을 것 같습니다.

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +        RetryHelper carNameInputManager = new RetryHelper(5);
제가 생각하기엔 RetryHelper는 로직을 재수행하는 역할이 맞으니 이에 맞는 이름을 설정하는게 맞지 않을까요? '이것이 입력을 받는 행위라는 것을 알기 위해서는 lamda를 분석해야만 합니다'라는 말은 해당 코드가 하는 당연한 역할이라고 생각이 듭니다. 

변수의 이름은 비즈니스 로직에서의 의미를 드러내야 하면서 또한 해당 변수가 가지고 있는 값에 대한 설명이 되어야 합니다. 현재 RetryHelper는 재수행을 하는 역할과 책임을 가지고 있는데 carNameInputManager는 그러한 역할을 드러내기에 적절한 이름일까요? '입력을 담당하는 매니저에서 retry를 한다'와 '재수행을 담당하는 헬퍼에서 retry를 한다', 둘 중 어떤 편이 더 자연스럽게 읽히는 코드라고 생각하시나요?

```java
return carNameInputManager.retry(
                () -> CarNameInputManager.getNameFromConsole(scanner));
```

이 코드는 _자동차 이름의 입력을 관리하는 곳에서 '자동차 이름을 관리하는 클래스의 콘솔에서 이름받기'라는 메서드를 재수행한다_ 라고 읽힙니다.

```java
return retryHelper.retry(
                () -> CarNameInputManager.getNameFromConsole(scanner));
```

이 코드는 _재수행을 도와주는 곳에서 '자동차 이름을 관리하는 클래스의 콘솔에서 이름받기'라는 메서드를 재수행한다_ 라고 읽히고요.

제가 느끼기엔 변수가 가지고 있는 값의 역할을 명확히 드러내는 아래의 코드가 더 적절하게 보이는데 로빈의 생각은 어떠한지 궁금합니다.

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +public class RacingManager {
Manager라는 이름은 클래스의 책임이나 역할을 표현하기엔 그 의미가 모호한 것 같습니다. 입력을 받는 곳이라면 단순하게 InputView와 같은 이름도 좋을 것 같구요. 

로빈이 지은 클래스 이름들은 도메인 위주로 설계된 코드라기 보다는 보편적인 웹 어플리케이션 코드에서 만나기 쉬운 이름들로 선택되어서 지어진 것 같아요. RacingManager는 사실 입력도 받아오고 출력도 하며 레이싱 게임의 전반적인 진행 과정이라는 비즈니스 로직을 전개하는 클래스로 보입니다. 그렇다면 오히려 RacingGame과 같이 자동차 게임의 진행 비즈니스를 관리하는 이름으로 선택해도 될 것 같고요.

이번 미션에서는 로빈이 클래스를 설계했을 때 어떠한 역할과 책임을 가지는지 고민하고 그에 맞는 이름을 직접 선택해서 지어보는 연습을 해보는 것도 좋을 것 같습니다.

- https://medium.com/@lunay0ung/clean-code-class-%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-10%EC%9E%A5-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B4%80%EB%A0%A8-%EB%82%B4%EC%9A%A9-%EC%9A%94%EC%95%BD-31cbdd774666

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/Cars.java
> +  private final List<Car> cars;
상수와 필드 사이에 공백을 추가해주세요 (구글 자바 코딩 컨벤션)

2024-02-17 11:05 UTC, lxxjn0 commented on src/main/java/racing/domain/RacingManager.java
> +  public static void raceStart() {
이전보다 훨씬 코드의 가독성이 좋아지고 수행 단위가 구분되어 보여지는 것 같습니다 👍🏼

2024-02-17 11:05 UTC, merged

2024-02-17 15:19 UTC, robinjoon commented on src/main/java/racing/input/CarNameInputManager.java
> +        if (input.startsWith(",") || input.endsWith(",")) {
정말 단순히 "," 를 "/" 과 같은 것으로 변경한다면 에디터의 찾기(컨트롤 + f) 및 바꾸기 (컨트롤 + r)기능을 이용해 변경할 수 있습니다. 그런데, 이건 언어 차원에서 검사 대상이 되지 않기 때문에 그 "," 을 여러 클래스에서 사용한다면 누락될 여지가 있습니다. 이런 점에서 문법의 검사 대상이라는 말을 썼는데, 표현이 조금 이상했던 것 같습니다. 말씀하신 것 잘 이해하고 있습니다. 순간의 귀찮음에 상수로 한다는 선택을 하지 않았던 것 같습니다.

2024-02-17 15:28 UTC, robinjoon commented on src/main/java/racing/domain/Car.java
> +    }
> 메서드는 행위를 나타내기 위한 코드입니다. 행위가 없는 메서드는 메서드로써의 의미가 없습니다. 단순히 코드에서 go를 실행하지 않으면 정지된 상태라는 것을 충분히 알 수 있지 않을까요?

**없어도 전체적인 로직을 이해하는 것이 어렵지 않게 가능하다는 것은 동의**합니다. 하지만, **그것이 이 메서드가 있어서는 안되는 이유는 아니**라고 생각합니다.

메서드 뿐 아니라 **모든 코드는 그 자체로 로직을 설명하는 역할**을 한다고 생각합니다. 비록 **아무것도 하지 않는 메서드라고 해도, 그것이 존재함으로써 조금 더 로직을 잘 이해할 수 있다면 있어도 된다**고 생각합니다. 

나아가 만약 **정지 시의 동작이 추가될 경우, 코드의 어떤 부분을 수정해야 할지도 명확**해진다고 생각합니다.

2024-02-17 15:34 UTC, robinjoon commented on src/main/java/racing/input/CarNameInputManager.java
> +    static List<String> getName(String input) {
> 이 부분은 위에 [다른 코멘트](https://github.com/woowacourse/java-racingcar/pull/650/files/d09de4babd9125fb5518f05ff6b00eac48ee5839#r1490984912)에서 로빈이 이야기한 내용과 의견이 상충되는 것 같은데 혹시 제가 잘못 이해하고 있는 것일까요?
> 
> 로빈은 접근 지정자를 '외부 패키지에서 접근할 수 있는 메서드와 그렇지 않은 메서드를 확실하게 구분짓기 위한 용도'로 사용하려고 하는 것 같습니다. 그러나 지금처럼 '명확하게 사용 용도가 한정'된 경우는 이러한 단점이 존재하지 않게 될까요?
> 
> 접근 지정자는 사용자가 객체에 접근할 수 있는 메서드의 접근 범위를 지정하는 용도입니다. 이는 개발자 본인이 아닌 다른 누구는 언제든지 해당 접근 범위에 해당된다면 메서드를 사용할 수 있게 됩니다. 현재 메서드는 '실수로라도 사용할 가능성이 없다고 판단'하셨다고 했는데 어떠한 개발자든 모두 이 의도를 명확히 이해하고 사용하지 않을 것이란 확신이 있으신 걸까요? 제가 생각하기에는 코드 상에서는 그렇게 할 어떠한 제약 조건도 존재하지 않는 것으로 보입니다. 접근 지정자를 private로 변경하지 않는 이상은요.
> 
> 해당 메서드의 접근 지정자가 package-private 라는 것이 문제는 아니라고 생각합니다. 단지 코드를 작성하는 개발자가 코드를 작성할 때 코드 전체에 일관된 맥락을 유지하지 않는다면 코드를 사용하거나 읽는 사람은 그 맥락을 이해할 수 없습니다. 어떤 코드는 package 레벨에서 사용할 수 있도록 오픈했는데 어떤 코드는 오픈이 되어있지만 사용하지 말라고 하는 말이 되어버리니깐요.
> 
> 접근 지정자를 public으로 연다는 것은 누구나 해당 메서드를 접근할 수 있습니다. 그러나 해당 메서드가 순수 함수로써 side-effect를 만드는 함수가 아니라면 public으로 메서드를 오픈하더라도 별 다른 문제가 발생할 상황은 없을 것으로 보여집니다. 또는 public으로 열린 메서드를 활용해 private 메서드를 테스트 할 수도 있겠지만, 이는 코드의 로직 변경에 너무 기민하게 반응하는 테스트 코드가 될 수도 있겠지요.
> 
> 이러한 다양한 관점을 생각해보면서 한번 접근 지정자에 대해 고민해보는 것도 좋을 것 같습니다.

**원칙을 준수하되, 원칙이 있는 이유를 부정하는 상황이거나, 원칙을 깨는 것이 충분히 유익하다면 그것을 깨는 것도 가능**하다는 생각에 **예외적으로 허용한 케이스**입니다. 하지만 이는 말씀하신 것 처럼 분명히 부작용이 큽니다. 게다가 이번 경우처럼 그것이 코드의 호출 가능 여부를 결정하는 것이라면 더욱 커지는 것 같습니다.

다음부터는 더 신중하게 생각해 봐야 할 것 같습니다. 어렵네요 ㅠㅠ

2024-02-17 15:36 UTC, robinjoon commented on src/main/java/racing/domain/Cars.java
> +  private final List<Car> cars;
인터넷에 돌아다니는 구글 스타일 설정 파일을 인텔리제이에 적용했는데.. 뭔가 잘못되었나 봅니다.