포케(이무송) 1단계 - 자동차 경주 구현 미션 제출합니다.
woowacourse/java-racingcar pull request #651
Opened 2024-02-15 05:14 UTC by fromitive

## PR 리뷰 요청 

안녕하세요 리뷰어님  포케입니다~

1단계 - 자동차 경주 구현 PR 제출 합니다~~

자동차 경주 게임의 시작 코드는 `main/java/racingcar/Application.java`에 있습니다.

디렉터리의 각 설명은 다음 같습니다.

```
* main/java/racingcar
- 각 도메인의 구현 코드 및 인터페이스가 있음

* test/java/racingcar
- 각 도메인별 값 검증(ValidateInput) 및 기능(Feature) 테스트로 구성되어 있음
```

아래와 같은 도메인을 정의하여 구현을 완료하였습니다.

## model

### Cars and CarsTest

n개의 자동차를 넣고 일급 컬랙션입니다.

n개의 자동차 각각 생성된 숫자에 따라 이동하거나 정지시킬 수 있음

n개의 자동차 중 우승자를 출력 할 수 있음

#### ValidateInput

- [X] 여러개의 자동차 이름을 받을 때 입력값 검증
    - [X] 콤마가 맨 앞 또는 맨 뒤에 위치하면 에러 발생

#### Function

- [X] 콤마(,)로 구성된 문자열을 파싱하여 여러대의 차를 추가
- [X] 숫자에 따라 차 전진 또는 정지
    - [X] 랜덤 넘버가 4 이상인 경우 차 위치 이동
    - [X] 랜덤 넘버가 3 이하인 경우 차 정지
- [X] 우승자는 단독 또는 여러명의 우승자가 나온다
    - [X] 폭포가 4 포케가 3이 나오면 우승자는 폭포여야 함

### Car and CarTest

자동차의 이름과 현재 위치를 저장합니다.

자동차 이름이 5자 초과 시 예외를 발생시킵니다.

#### ValidateInput

- [X] 차 이름 길이 검증
    - [X] 이름이 5자 초과 시 예외 발생

#### Function

- [X] 차 1칸 이동

### TryCount

시도 횟수를 저장합니다. 시도 회수를 `consume()`으로 소비하고, 시도횟수가 0인지 확인합니다.

문자열로 초기화할 수 있고 숫자가 아닌 문자나, 음수로 초기화 할 경우 예외를 발생시킵니다. 

#### ValidateInput

- [X] 입력값이 문자이면 예외(IllegalArgumentException)를 발생시킨다

- [X] 입력값이 음수이면 예외(IllegalArgumentException)를 발생시킨다.

#### Function

- [X] 시도회수를 1개 소비한다.

- [X] 시도회수가 1이상인지 확인한다.

## View

### InputView

사용자의 콘솔 입력을 처리합니다.

### OutputView

게임의 콘솔 출력을 처리합니다.

## Controller

### CarController

startGame()을 통해 게임을 시작할 수 있습니다.

### NumericGenerator

`generate()`를 통해 숫자를 생성하는 인터페이스 입니다.

랜덤 숫자를 생성하도록 `racingcar/controller/numericgenerator`에 `RandomNumericGenerator()`가 구현되어 있습니다.

2024-02-15 13:15 UTC, Deocksoo requested changes
안녕하세요 포케! 리뷰어 러너덕입니다.
작성해주신 코드 잘 읽어보았어요. 전반적으로 메서드를 작은 단위로 나누어주셨고, 테스트도 꼼꼼하게 잘 작성해주셨네요 👍 
인터페이스를 활용하여 랜덤한 동작을 분리해내거나, 테스트를 용이하게 하기 위해 여러 가지 기능들을 사용하기도 하시면서 다양한 시도들을 해보신 것 같아요 :)
이미 이런 시도들은 다양하게 잘 하고 계시는 것 같아서, 이번 미션에서는 아래 두 가지를 집중해서 연습해보시면 어떨까 싶어요. 

1. 좋은 이름 짓기
2. java 컨벤션 익숙해지기

관련해서 고민해보시면 좋을 만한 부분들을 피드백으로 남겨두었어요. 확인 한번 부탁드려요~

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/Car.java
> +    private static void nameUnderFive(String name) {
[Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)에 맞게 메서드 이름을 수정해보면 어떨까요?
메서드가 무슨 일을 하는지도 이름에 잘 드러날 수 있으면 좋겠어요.

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/TryCount.java
> +    public int validatedInput(String input) {
이 메서드는 한번에 여러가지 일을 하고 있는 것 같네요.
메서드 이름과 메서드가 하는 일이 다른것 같은데, 기능을 분리해보는 것은 어떤가요?

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/TryCount.java
> +    public int getValue() {
테스트에서만 사용하는 메서드가 생겼네요.
이런 메서드는 실제 production 코드에는 사용되지 않는데, 어떻게 처리하는 것이 좋을까요?

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/Cars.java
> +            if (generator.generate() >= 4) {
숫자 4는 꽤 특별한 의미가 있는 숫자일 것 같아요. 
이 부분도 [Java constant convetion](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) 에 따라 처리해주는 것은 어떤가요?

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/Cars.java
> +        Matcher matcher = pattern.matcher(input);
이 부분은 메서드가 호출 될 때마다 바뀌는 부분이 아니라, 항상 상수로 동일한 값이 들어가겠네요 :) [Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)에 따라 처리해보는 것은 어떤가요?

2024-02-15 13:15 UTC, Deocksoo commented on docs/README.md
> +## 구현할 기능 목록
👍

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/view/InputView.java
> +    private static final BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Ditto, Java constant convetion

2024-02-15 13:15 UTC, Deocksoo commented on src/main/java/racingcar/model/TryCount.java
> +    public boolean untilZero() {
이 메서드가 하는 일은 무엇인가요?
무슨 역할을 하는지 조금 더 잘 드러내는 이름으로 수정해보는 것은 어떨까요?

2024-02-15 13:15 UTC, Deocksoo commented on src/test/java/racingcar/CarsTest.java
> +public class CarsTest {
중요한 도메인 규칙들을 꼼꼼히 테스트해주셨네요 :) 👍

2024-02-15 13:15 UTC, Deocksoo commented on src/test/java/racingcar/CarTest.java
> +    @Nested
Nested 테스트를 사용하는 이유는 무엇인가요?
이 테스트에서 필요한 기능인가요?

2024-02-16 13:22 UTC, fromitive commented
안녕하세요 러너덕! 🐤

늦은 시간에도 불구하고 코드 리뷰해주셔서 감사합니다!! 🙏

러너덕의 의견을 반영해서 아래와 같이 추가로 커밋 작업을 진행하였습니다~

커밋 하면서, 러너덕이 주신  [Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) 덕분에 가독성 있고 읽기 쉬운 네이밍을 짓는데 많은 도움이 되었습니다! 

아래는 네이밍 컨벤션을 한글로 정리해 봤습니다 😁

### Java Naming Conventions 

| 타입                   | 규칙                                                                                                                                                                                                                                                                                                | 예시                            |
| ---------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------- |
| 패키지(packages)       | ISO Standard 3166, 1981에 따라 lowercase(소문자) ASCII 문자를 사용하는 것이 좋다. 보통 DNS 주소처럼 사용하는 것이 괜찮다                                                                                                                                                                            | com.poke.org                    |
| 클래스(Classes)        | 클래스 명은 명사를 사용하고, 축약어를 사용하지 않는다. 첫 글자는 대문자 ASCII 문자를 사용한다. 두 단어로 구성되어 있으면 CamelCase처럼 작성한다.                                                                                                                                                    | class CamelCase, class TryCount |
| 인터페이스(Interfaces) | 클래스와 동일하게 작성한다.                                                                                                                                                                                                                                                                         | interface NumericGenerator      |
| 메서드(Methods)        | 메서드는 동사로 표현한다.<br>첫 글자를 소문자로 작성하고, 두단어로 표현해야하면 두번째 단어의 첫 문자를 대문자로 작성해야 한다.                                                                                                                                                                        | void moveCars                   |
| 변수(Variables)        | 메서드의 표현처럼 변수는 첫 글자를 소문자로 작성하고 두단어로 표현해야 한다면 대문자로 작성해야 한다.<br>특히, 맨 앞에 특수 문자인 _ 와 $를 사용하지 않는 것을 권장한다. 되도록 의미없는 한 문자의 단어(i,j,k,l 등)의 사용을 금지한다.<br>정말 임시로 사용해야 한다면, 짧은 코드블럭에서 사용을 권고한다. | // 짧은 코드 블럭에서 사용가능<br>int i;  <br> char c; <br> // 의미가 있는 명칭 사용 <br> int possibleCountValue; |

또한 기타 `메서드 분리` 및 `Test 코드와 Production 코드 분리` 작업을 진행하면서 접근제어자에 대해 자세히 알 수 있었어요!  배움의 기회를 주셔서 감사합니다~

아래는 코드리뷰 반영 사항을 요약한 내용입니다! 추가로 커밋이 필요한 부분이 있거나 의도와 다르시다면 코멘트 부탁드립니다 🙏

## 1차 리뷰 반영 사항


### 명확한 의미를 담은 네이밍 사용

Java Naming Conventions가이드를 참고하여 메서드 이름 수정

#### model

- [X] Car의 nameUnderFive 네임 변경
- [X] Cars의 isValidInput 내 regex
- [X] Cars의 moveCars 내 매직 넘버(4)
- [X] Trycount untilZero 네임 변경

#### view

- [X] BufferedReader br 메서드 변경 (constant)

### 메서드 분리

- [X] model/Trycount validateInput 메서드 분리
    - [X] 입력 값이 숫자가 아닌 경우 
    - [X] 입력 값이 음수인 경우

### 테스트 코드와 프로덕션 코드 분리

- [X] model/Trycount getValue 접근제어자 변경
    - [X] test에 racingcar.model 패키지 생성
    - [X] CarsTest, CarTest 패키지 이동

2024-02-16 13:52 UTC, fromitive commented on src/test/java/racingcar/CarTest.java
> +    @Nested
단순히 nested를 통해 테스트 케이스의 종류(기능 테스트 및 입력 값 검증 테스트)를 나누고 싶어서 사용했습니다!

성격을 나누면 가독성이 좋아질 것이다 라고 생각하고 작성했어요 😅

2024-02-16 16:25 UTC, Deocksoo approved these changes
안녕하세요 포케! 학습하신 내용을 잘 정리해주셨군요~
필요한 부분에 변수가 생기고, 이름들이 조금 더 구체적으로 바뀌면서 코드가 보다 명확해졌네요 👍 
의도가 조금 달랐던 부분들은 코멘트 남겨두었으니, 머지 후에 확인 한 번 해주시면 좋을것 같아요.
피드백 반영하시느라 고생 많으셨어요 :) 다음 미션 계속 진행해주세요~

2024-02-16 16:25 UTC, Deocksoo commented on src/main/java/racingcar/model/Car.java
> +        final int MAX_LENGTH = 5;
메서드 내부에 선언하면 네이밍만 constant 컨벤션을 따르게 되고, 기능적으로는 큰 차이가 없을 것 같아요.
다른 곳에서도 공유해서 사용할 수 있도록 메서드 내부보다는 클래스의 static 변수로 두면 어떤가요?

2024-02-16 16:25 UTC, Deocksoo commented on src/main/java/racingcar/model/Cars.java
> +        Matcher matcher = pattern.matcher(input);
마찬가지로, static 변수로 처리되면 좋을것같아요!

2024-02-16 16:25 UTC, Deocksoo commented on src/main/java/racingcar/model/TryCount.java
> +    private int validatedInput(String input) {
앗.. 이 메서드 이름이 validateInput이 아니라 validatedInput 이었군요!
Java 메서드 네이밍 컨벤션을 따르지 않는 메서드네요. 메서드 컨벤션에 따라 코드를 읽다 보면 자연스럽게 앞의 단어가 동작을 의미하는 단어라고 기대하고 읽게 되고, '이 메서드는 Input을 validate 하는 메서드구나' 하고 생각하게 돼요. 메서드가 하는 일과 상당히 다른 의미로 받아들이게 될 수도 있는거죠. 컨벤션에 맞게 메서드 이름을 바꿔보면 어떤가요?

2024-02-16 16:25 UTC, merged

2024-02-17 04:50 UTC, fromitive commented on src/main/java/racingcar/model/Car.java
> +        final int MAX_LENGTH = 5;
아하! static 맴버변수로 선언하면, 다른 메서드에서 사용할 수 있겠군요..! 좋은 경험을 나눠주셔서 감사합니다!

2024-02-17 04:53 UTC, fromitive commented on src/main/java/racingcar/model/TryCount.java
> +    private int validatedInput(String input) {
앗 이부분을 놓쳤네요 😓 2단계 미션에서 해당부분 반드시 챙기겠습니다!