레벨1 자동차 경주 미션 제출합니다.
woowacourse/java-racingcar pull request #655
Opened 2024-02-15 06:07 UTC by jhon3242

안녕하세요! 타칸입니다!
페어프로그래밍을 하면서 예외 메시지를 상수화해야 할지 고민했던 부분이 있었습니다!

저는 예외 메시지를 별도의 객체에서 관리하는 편이 좋다고 생각합니다.
만약 예외 메시지의 수정이 필요한 경우 어느 로직에서 예외를 발생시켰는지 찾아서 직접 문자열을 수정하는 과정이 필요하기 때문에 비효율적이라고 생각합니다.
하지만 별도의 객체에서 예외 메시지들을 관리한다면 굳이 여러 패키지를 돌아다니면서 예외가 발생한 부분을 찾을 필요 없이
빠르게 수정할 수 있다고 생각해서 별도의 객체에서 관리하는 것이 좋다고 생각합니다.

반면,커찬의 의견은 별도의 객체로 관리하게 된다면 비즈니스 로직과 관련된 예외 메시지 처리 시 (예: "자동차 이름은 5자 이내여야 합니다.")
종속이 되기 때문에 의도치 않은 예외가 발생할 수 있다는 의견입니다.
그래서 그냥 문자열을 사용하는 게 그나마 낫다는 의견입니다.

이번 미션인 자동차 경주 미션에서는 예외 메시지를 위한 별도의 객체를 만드는 것은 불필요한 복잡성의 증가라고 판단이 되어 문자열 그대로 사용하는 방식을 채택하였지만 만약 실무에서와 같이 복잡한 프로그램인 경우, 예외 메시지를 어떤 식으로 관리하는지 궁금합니다!

리뷰해주셔서 감사합니다!!

2024-02-15 08:00 UTC, jinyoungchoi95 requested changes
안녕하세요 타칸 😄

자동차 미션의 리뷰어를 맡은 오리입니다.

첫 미션인데 잘 구현해주셨네요. 다음 단계 넘어가기 전 같이 이야기하면 좋을 내용 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-02-15 08:00 UTC, jinyoungchoi95 commented on README.md
> 이번 미션인 자동차 경주 미션에서는 예외 메시지를 위한 별도의 객체를 만드는 것은 불필요한 복잡성의 증가라고 판단이 되어 문자열 그대로 사용하는 방식을 채택하였지만 만약 실무에서와 같이 복잡한 프로그램인 경우, 예외 메시지를 어떤 식으로 관리하는지 궁금합니다!

말씀하신대로 예외 메시지를 위한 별도의 객체를 만드는건 불필요한 복잡성의 증가가 맞아요. 예외 메시지는 보통 예외를 처리해야하는 쪽에서 작성하는 비즈니스가 담기기 때문에 예외를 관리하기 위한 객체를 만들기보다는 예외를 처리해야하는 해당 객체에서 모두 처리하는 편입니다.

말씀하신 실무의 경우에서도 무수히 많은 케이스에 대해서 예외처리를 하고 있기 때문에 한군데 관리한다라고 했을 때 몇백줄되는 예외 메시지가 감당안되기도하구요.

2024-02-15 08:00 UTC, jinyoungchoi95 commented on README.md
> +## 구현 기능 목록
기능목록 잘 작성해주셨네요 👍

2024-02-15 08:00 UTC, jinyoungchoi95 commented on README.md
> +  - '자동차 경주 미션'의 제어 로직을 담고 있다.
`Controller`는 "제어 로직"을 담고 있는 의미로 네이밍을 달아주셨어요. "자바 콘솔 프로그램"을 작성한다라는 관점에서 보기에는 `RacingCarMachine`, `RacingCarGame`등과 같은 이름이 더 어울릴 것 같은데 `Controller`라는 네이밍을 명시한 이유가 있을까요?

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/Car.java
> +        this.position = 0;
0을 좀 더 의미를 담은 상수로 표현하면 어떨까요?

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/Car.java
> +        if (name.length() > 5) {
길이 제한도 의미있는 상수로 표현하면 좋을 것 같네요.

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/test/java/domain/CarTest.java
> +}
[eol](https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/) 경고가 나오고 있네요.

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/test/java/domain/CarTest.java
> +    void creationTest_whenNameLengthIsBlank_throwException(String name) {
테스트 네이밍 꼼꼼해서 좋네요 :)

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/Cars.java
> +    private final List<Car> carList;
`carList`와 같이 타입이 네이밍에 노출되어있으면 어떤 문제가 발생할까요?

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/MoveStrategy.java
> +public interface MoveStrategy {
자동차 움직임을 잘 추상화 해주셨네요 :)

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/RandomMoveStrategy.java
> +    public RandomMoveStrategy(IntSupplier supplier) {
`RandomMoveStrategy`로 랜덤 움직임 전략인데 `IntSupplier`로 추상화된 값을 받는다면 `RandomDigitSupplier`가 아닌 다른 랜덤 번호를 주지 않는 구현체를 넣을 수 있지 않을까요?

`Supplier`로 따로 분리하지 않아도 `RandomMoveStrategy`에서 `RANDOM`을 가지면서 처리해도 큰 문제가 없어보여요.

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/RandomMoveStrategy.java
> +    public static final int MIN_MOVABLE_DIGIT = 4;
```suggestion
    private static final int MIN_MOVABLE_DIGIT = 4;
```
외부에서 사용하지 않는 상수는 막아주는 것이 좋습니다 :)

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/Cars.java
> +    private final MoveStrategy moveStrategy;
타칸이 생각하기에 움직임 전략은 `Car`가 각각 가져야한다고 생각하시나요, `Cars`에서 한번에 관리해야한다고 생각하시나요?

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/Cars.java
> +        });
```suggestion
        carList.forEach(car -> car.move(moveStrategy.isMove()));
```
😄

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/domain/TrialCount.java
> +    public void repeat(Runnable consumer) {
👍

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/main/java/view/InputView.java
> +public class InputView {
생성자는 만들지 못하도록 막아도 좋을 것 같네요.

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/test/java/domain/MockCar.java
> +public class MockCar extends Car {
`Car`가 생성될 때 position을 받아도될 것 같은데 `MockCar`를 만든 이유가 있을까요?

2024-02-15 08:00 UTC, jinyoungchoi95 commented on src/test/java/domain/TrialCountTest.java
> +        Assertions.assertThat(count.getAmount()).isEqualTo(expected);
이정도 테스트 동작구조라면 bdd(given-when-then) 등을 써서 가독성을 늘리는 것도 좋은 것 같아요.

2024-02-15 08:23 UTC, jhon3242 commented on README.md
> +  - '자동차 경주 미션'의 제어 로직을 담고 있다.
RacingCarMachine 이나 RacingCarGame 와 같은 이름도 좋을 것 같아요!
하지만 이름을 통해서 "제어 로직"을 담고있는 컨트롤러라는 것을 알아보기 힘들 것 같아요!
그래서 저는 의도적으로 `xxxController` 라는 네이밍을 통해서 "이 객체는 제어 로직을 담고 있다." 라는 것을 은연중에 알려주기 위해서 이런식으로 사용했던 것 같습니다!

2024-02-15 08:24 UTC, jhon3242 commented on src/main/java/domain/Car.java
> +        this.position = 0;
`int DEFAULT_POSITION = 0` 과 같이 상수로 표현하는 방식이 더 좋을 것 같네요! 감사합니다!^^

2024-02-15 08:25 UTC, jhon3242 commented on src/main/java/domain/Car.java
> +        if (name.length() > 5) {
의식적으로 매직 상수를 사용하지 않으려는 연습이 필요하겠네요 ㅎㅎ 감사합니다!

2024-02-15 08:26 UTC, jhon3242 commented on src/main/java/view/InputView.java
> +public class InputView {
그러네요! private 생성자를 만들어주겠습니다! ㅎㅎ 감사합니다!

2024-02-15 08:41 UTC, jhon3242 commented on src/test/java/domain/MockCar.java
> +public class MockCar extends Car {
이 부분에 대해서 페어와 고민했던 부분인데 지적해주셔서 감사합니다! ㅎㅎ

별도의 `MockCar` 를 만든 이유는 `Car` 에서 문제가 발생했을 때 `CarTest` 와 `CarsTest` 테스트 둘 다 실패하기 때문입니다!
`Car` 객체에만 있는 문제 때문에 아무 문제 없는 `Cars` 객체에 대한 테스트인 `CarsTest` 도 실패하게 된다는 것이 옳지 않다고 판단했습니다. 그래서 굳이 `MockCar` 라는 별도의 테스트용 `Car` 객체를 만들어주어 `Car` 에 대한 문제 발생시 `CarTest` 테스트에서만 실패하도록 해주었습니다!

그리고 이후 `findWinner` 에 대한 테스트를 작성하는 과정에서도 `MockCar` 를 활용해 주면 좋을 것 같아서 `MockCar` 에 `position` 을 받는 생성자를 추가하여 활용하였던 것입니다! ㅎㅎ

2024-02-15 08:43 UTC, jhon3242 commented on src/test/java/domain/TrialCountTest.java
> +        Assertions.assertThat(count.getAmount()).isEqualTo(expected);
```java
        // given
        int expected = 4;
        TrialCount trialCount = new TrialCount(expected);
        CountForRepeatTest count = new CountForRepeatTest();

       // when
        trialCount.repeat(count::addCount);

      // then
        Assertions.assertThat(count.getAmount()).isEqualTo(expected);
```

이런식으로 활용하는 말씀이시죠? ㅎㅎ 넵 알겠습니다!

2024-02-16 06:21 UTC, jhon3242 commented on README.md
그러면 만약 "빈 값이 들어있습니다." 와 같이 공용적으로 사용될 만한 예외 메시지를 서로 다른 객체에서 같은 경우에는 어떻게 처리해야할까요??

저는 이런 공용적으로 사용되는 예외 메시지는 별도의 객체에 상수로 선언해주어서 여러 곳에서 사용하는 편이 옳을 것 같다고 생각이 들어요!

만약 별도의 상수로 만들어주지 않고 매번 새롭게 메시지를 작성하다보면 통일성에서 문제가 발생할 것 같아요!

예를 들어서 회원가입 하는데 이름칸에 빈 값이 들어갔을 때는  "빈 값이 들어있습니다." 와 같은 에러 메시지가 나오고, 게시글을 작성할 때 제목칸이 비어있으면 "빈 값입니다." 라는 에러 메시지가 나온다면, 서로 동일한 에러로 예외가 발생하는데 메시지가 다르기 때문에 통일성이 없다고 느껴져요. 

이를 방지하기 위해서 별도의 객체에 `public static final String INPUT_NULL_ERROR_MESSAGE = "빈 값입니다."` 와 같이 선언해두고 필요할 때 마다 해당 상수를 호출해서 사용해주면 통일성을 지켜줄 수 있을 것 같아요! 오리는 어떻게 생각하는지 궁금합니다!

2024-02-16 06:23 UTC, jhon3242 commented on README.md
> +  - '자동차 경주 미션'의 제어 로직을 담고 있다.
아니면 `controller` 패키지를 만들고, 안에 오리가 말해주신대로 `RacingCarMachine`, `RacingCarGame` 와 같은 이름으로 넣어주는 방법도 좋을 것 같아요!

2024-02-16 06:31 UTC, jhon3242 commented on src/main/java/domain/Car.java
> +        this.position = 0;
그런데 만약 요구사항이 변하지 않는 상황이라면 상수로 만드는 것이 오히려 코드의 복잡성을 늘리게 되지는 않을까 생각이 드네요🤔
이 부분에 대해서 오리는 어떻게 생각하는지 궁금합니다!

2024-02-16 07:20 UTC, jhon3242 commented on src/test/java/domain/CarTest.java
> +}
이번 기회에 eol 경고가 무엇인지 알아볼 수 있는 기회를 가졌어요! ㅎㅎ 감사합니다!

2024-02-16 07:32 UTC, jhon3242 commented on src/main/java/domain/Cars.java
> +    private final List<Car> carList;
만약 타입이 변경된다면 변수명은 물론이고 외부에서 사용하는 getter / setter 메서드명도 변경될 것 같네요! 변경의 영향력을 최소화하기 위해서 타입이 네이밍에 노출되는 방식은 지양하는게 좋을 것 같아요! 감사합니다!

2024-02-16 11:19 UTC, jhon3242 commented on src/main/java/domain/RandomMoveStrategy.java
> +    public RandomMoveStrategy(IntSupplier supplier) {
오리가 말해주신 대로 "랜덤 번호를 주지 않는 구현체 들어올 수 있도록 의도한 설계입니다! ㅎㅎ

테스트할 때 일부러 랜덤 번호를 주지 않고, 의도한 숫자만(예 : 4 이상의 정수만) 리턴하는 구현체를 넣어주어서 테스트에 용이하도록 설계했습니다 ㅎㅎ 만약 이런 식으로 설계하지 않고 `RandomMoveStrategy` 에서 RANDOM을 가지면서 처리하게 된다면 테스트하기 어려울 것이라고 생각했어요!

2024-02-16 11:55 UTC, jhon3242 commented on src/main/java/domain/Cars.java
> +    private final MoveStrategy moveStrategy;
저는 둘 다 맞는 것 같아요!

실제 레이싱 게임이라고 생각할 때 자동차마다 움직이는 전략은 다를 것 같아요!
그래서 `Car` 객체마다 각자만의 움직임 전략을 가지고 있는게 더 자연스러운 것 같아요!

그런데 만약 레이싱 게임이 공통된 차량으로 하는 경주라면 지금처럼 `Cars` 에서 한번에 관리하는게 맞다고 생각해요! ㅎㅎ
어떤 관점에서 보는가에 따라서 움직임 전략을 누가 가질지 정해질 것 같네요!

2024-02-16 14:38 UTC, jinyoungchoi95 commented on README.md
빈 값입니다라는 표현에 대해서 통일성이 있어야하지 않느냐라고 이야기주셨는데 말을 하는 메시지에 대해서 항상 통일성을 지켜야하는가의 문제인것 같아요. 문구가 100% 항상 동일한 어투의 통일성있는 상수를 보장한다는 건, 예를 들면 "입니다." 조차도 상수로 통일성을 지켜야하는 것으로 결론이 나오게 되는거죠.(누구는 구어체, 누구는 문어체를 쓸 수 있으니까요) 그럼 통일성을 지키고자하는 것들이 복잡성만을 올리지 않을까요? 

[YAGNI](https://ko.wikipedia.org/wiki/YAGNI)라는 원칙이 있는데요, 때로는 생각했을때 필요로하는 기능의 고민들이 오버프로그래밍으로 연결되지 않는지 의심해보면 좋을 것 같아요.

2024-02-16 14:41 UTC, jinyoungchoi95 commented on README.md
> +  - '자동차 경주 미션'의 제어 로직을 담고 있다.
제어로직을 담당한다는 의미가 `Controller`가 적절할까요? 

실제 상황에서 게임을 실행한다라고 한다면, 게임기가 게임을 실행할까요 게임 컨트롤러가 게임을 실행할까요? 게임은 본체가 실행을 하는 것이고 컨트롤러는 실행된 게임에 커맨드만 날리는 역할 아닐까요?

`Controller`를 스프링에서 사용하기 위해서 관습적으로 사용하고 계시다면 현재는 "자바만을 사용하는" 콘솔 게임이기 때문에 아예 사용하지 않으셔도됩니다.

2024-02-16 14:45 UTC, jinyoungchoi95 commented on src/main/java/domain/Car.java
> +        this.position = 0;
요구사항이 변하지 않으면 0도 변하지 않는다는 의미에서 말씀해주신 것 같아요.

하지만 상수를 사용하는 이유는 자주 변하는 값이기 때문에 사용하는 것이 아닌 의미를 **네이밍을 통해서 명확하게 전달해주기 위해서** 사용해요.
```
0 -> 0이 왜 있는거지?
DEFAULT_POSITION -> 아 이건 초기위치이구나
```
로 이해할 수 있기 때문에 의미를 바로 이해할 수 없는 매직넘버 대신 상수를 사용합니다.

2024-02-16 14:50 UTC, jinyoungchoi95 commented on src/main/java/domain/RandomMoveStrategy.java
> +    public RandomMoveStrategy(IntSupplier supplier) {
`MoveStrategy`를 랜덤 움직임을 추상화하기위해서만드셨고, 그 랜덤한 움직임을 관리하는 구현체가 `RandomMoveStrategy`인데 랜덤 번호를 주지 않는 구현체를 들어올 수 있도록 하는 이유가 없지 않을까요?

현재 구현된 내용만 보더라도 `RandomMoveStrategy`는 랜덤에 관련된 로직이 하나도 없어 클래스 명과 기능이 동일하지 않아요.

테스트하고자하기위해서 분리했다면 `RandomDigitSupplier`도 테스트 못하는건 마찬가지 아닐까요?

2024-02-16 15:03 UTC, jinyoungchoi95 commented on src/test/java/domain/MockCar.java
> +public class MockCar extends Car {
`Cars`가 `Car`에 의존하고 있어 `Car`가 실패한다면 `Cars`가 영향이 가는 건 당연한 것 아닐까요? `Car`에서 만든 기능이 문제가 발생해서 `Cars`의 테스트도 실패한다면 의존하고 있는 클래스가 문제가 있기 때문에 오히려 테스트에서 확인할 지점이 생겨 안정적인 것 으로 보이네요.

그리고 만들어주신 클래스가 정상동작한다는 것은 어디서 보장해주나요? 클래스 생성 자체가 문제라기보다는 지금 필요로하고 그게 지금 쓰이는가때문에 이야기드려요.

2024-02-16 15:21 UTC, jinyoungchoi95 approved these changes
안녕하세요 타칸 😄

피드백 잘 반영해주셨네요 👍 코멘트로 남겨주셨던 내용과 다음단계 넘어가기전 보면 이야기해보면 좋을 내용들 코멘트 달아두었으니 Step2에서 함께 반영부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-02-16 15:21 UTC, jinyoungchoi95 commented on src/main/java/domain/Car.java
> +    public static final int MAX_NAME_LENGTH = 5;
```suggestion
    private static final int DEFAULT_POSITION = 0;
    private static final int MAX_NAME_LENGTH = 5;
```
`Car`에서만 사용되는 상수는 private으로 접근을 막으면 좋겠네요.

2024-02-16 15:21 UTC, jinyoungchoi95 commented on src/main/java/domain/Cars.java
> +    }
생성자가 아닌 정적팩토리메소드를 사용한 이유가 있을까요? 생성자에서 해당 객체 생성로직을 가지면 안되는 이유가 있을까요?

2024-02-16 15:21 UTC, jinyoungchoi95 commented on src/main/java/domain/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
getter를 사용하여 로직을 처리하는 것이 아닌 `Car`에 maxPosition을 보내서 일치하는지 확인하는 메시지를 주고받는 형태면 어떨까요?

2024-02-16 15:21 UTC, jinyoungchoi95 commented on src/main/java/domain/TrialCount.java
> +        if (amount < 1) {
1도 `TrialCount`에서는 "최소 시도 횟수"라는 의미를 가지는 매직넘버가 되겠네요.

2024-02-16 15:21 UTC, jinyoungchoi95 commented on src/test/java/domain/CarTest.java
> +    void moveTest(boolean isMoved, int expected) {
자동차가 움직일 수 없는 테스트케이스도 있는데 다르게 표현되어야하지 않을까요?

2024-02-16 15:21 UTC, merged

2024-02-17 01:24 UTC, jhon3242 commented on README.md
항상 확장성과 복잡성 사이에서 고민하고 있었는데 YAGNI 라는 원칙도 있군요! 이번 기회에 알아봐야겠네요! ㅎㅎ 감사합니다!

2024-02-17 01:26 UTC, jhon3242 commented on README.md
> +  - '자동차 경주 미션'의 제어 로직을 담고 있다.
내가 지금 하고 있는 작업이 관습적으로 사용하는지, 꼭 필요한 작업인지 의식적으로 점검해보는 자세가 필요할 것 같네요!🧐
감사합니다!

2024-02-17 01:32 UTC, jhon3242 commented on src/main/java/domain/Car.java
> +        this.position = 0;
@jinyoungchoi95 
음 그렇게도 볼 수 있겠네요!
근데 저는 상수로 선언해주면 "선언된 값을 확인하는 작업"이 추가적으로 필요하기 때문에 복잡성을 늘리는 요인이 되지 않을까? 라고 생각해요! 생성자 단계에서 `this.position = 0;` 을 통해 "아 디폴트 위치는 0이구나" 라고 직관적으로 이해한다고 생각해요.

그런데 만약 오리가 말해주신대로
`this.position = DEFAULT_POSITION;` 으로 되어 있다면 "아 디폴트 위치를 초기화 하구나" 라는 것은 알 수 있지만 초기화 위치가 몇 인지 알아내기 위해 해당 상수가 선언된 부분을 찾아야하는 작업이 추가적으로 필요하니까요! 이 부분에 대해서 오리의 생각이 궁금해요!

2024-02-17 02:23 UTC, jhon3242 commented on src/main/java/domain/RandomMoveStrategy.java
> +    public RandomMoveStrategy(IntSupplier supplier) {
@jinyoungchoi95 
음 그러네요! 굳이 `RandomMoveStrategy` 에서 `IntSupplier` 로 구현체를 받는 것은 오히려 불필요한 확장성인 것 같아요!
`RandomMoveStrategy` 이름을 가지고 있는 구현체가 랜덤한 움직임을 받지 않도록 설계할 이유가 없는 것 같아요!

그렇다몀ㄴ 만약 `RandomMoveStrategy` 객체가 RANDOM 을 가지면서 처리하게 된다면 `RandomMoveStrategy` 의 테스트는 어떻게 할 수 있을까요?? 
Race 객체(기존의 Cars 객체의 이름을 Race로 변경했습니다) 에 대한 테스트는 별도의 `MoveStrategy` 를 구현하는 객체를 생성해서 테스트 해줄 수 있을 것 같은데, `RandomMoveStrategy`  객체 자체에 대해서는 테스트하기 어려울 것 같아요!

우선 `RandomMoveStrategy` 를 꼭 테스트 해줄 필요가 있을까?? 라고 생각했을 때, 실제 비즈니스 로직에서는 `RandomMoveStrategy` 를 활용해 레이스가 진행되니까 `RandomMoveStrategy` 에 대한 테스트도 해주는게 맞다고 판단이 들어요.

그런데 어떻게 테스트 해줄 수 있을지에 대한 마땅한 아이디어는 떠오르지가 않네요 ㅠㅠ 
```java
public class RandomMoveStrategy implements MoveStrategy {

    public static final int MIN_MOVABLE_DIGIT = 4;

    private static final Random random = new Random();

    public RandomMoveStrategy() {
    }

    public boolean isMovableDigit(int digit) {
        return digit >= MIN_MOVABLE_DIGIT;
    }

    @Override
    public boolean isMove() {
        return isMovableDigit(random.nextInt(10));
    }
}

```
지금 당장 생각나는 방법은 위와 같이 작성하여서 `isMovableDigit` 메서드를 만들어서 테스트해주는 것인데,, 더 좋은 방법이 있을까요??

2024-02-17 02:46 UTC, jhon3242 commented on src/test/java/domain/MockCar.java
> +public class MockCar extends Car {
음 그러네요.. 오히려 `MockCar` 도 정상동작한다는 것이 보장되지 않는다면 오히려 `MockCar`를 만든 것이 불필요한 작업일 수 있다는 생각이 들어요! 
또한 만약 요구사항이 확장되어서 `Cars` 객체를 포함하고 있는 별도의 객체가 생기고, 또 그 객체를 가지고 있는 객체가 생긴다면 해당 객체들을 테스트하기 위해 매번 `Mock` 객체를 만드는 것이 맞을까?? 라는 생각도 들어요! 생각의 확장!ㅎㅎ 감사합니다!

2024-02-17 04:23 UTC, jhon3242 reviewed
더 좋은 방법을 스스로 알고 있었는데도 적용하지 못했던 부분이 많이 보여서 아쉬운 코드였던 것 같아요ㅠㅠ step2 에서는 좀 더 꼼꼼하게 살펴보겠습니다!!🔥

2024-02-17 04:23 UTC, jhon3242 commented on src/main/java/domain/Cars.java
> +    }
자동차 이름을 문자열 리스트로 받아주면 좋을 것 같다는 생각에서 정적 팩토리 메서드를 사용했었어요.
생성자는 최대한 타입 그대로 받아주는게 좋다고 생각했거든요! (기본적으로 생성자에서는 필드값을 그대로 받는다고 기대한다고 생각해요 그래서 타입 그대로 받아주는 것이 가독성에 더 좋다고 판단했습니다.)

그래서 만약 필드값과 다른 타입으로 객체를 생성하거나 별도의 작업을 해준다면 정적 팩토리 메서드를 사용해서 메서드 명을 통해 어떤 작업이 일어나는지 예상할 수 있도록 하는게 좋다고 생각해요! (물론 지금 코드에서 of 라는 메서드명이 설명이 부족한 것 같아요)

그런데 지금 다시 살펴보니까 지금 상황에서는 굳이 문자열 리스트를 받도록 해줄 필요가 있었는지 의문이 드네요..  지금 상황에선 없는 편이 더 나은 것 같아요!

2024-02-17 04:23 UTC, jhon3242 commented on src/main/java/domain/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
좋은 것 같아요! getter 를 사용한 로직 방식 보다는 메시지를 주고 받는 형태가 더 좋을 것 같습니다!