레벨 1 '자동차 경주' 미션 1차 구현 제출합니다.
woowacourse/java-racingcar pull request #656
Opened 2024-02-15 06:09 UTC by leegwichan

안녕하세요! 커찬입니다.

페어 프로그래밍을를 통해 '자동차 경주' 미션을 구현해 보았습니다.
제가 보지 못하는 관점에서 제 코드를 보시고, 어떤 부분이 좋았고 어떤 부분이 안좋았는지 리뷰해주시면 감사드리겠습니다.

추가적으로 앞으로 리뷰 요청할 때, 어떤 내용이 추가적으로 들어있으면 좋을지 의견 부탁드립니다!
아래는 프로젝트 코드 이해를 위한 소스 코드 구조입니다

### 소스코드 구조
```text
main
└── java
     ├── domain
     ├── view
     ├── RacingCarController.java
     └── RacingCarApplication.java
```

- domain
  - '자동차 경주 미션'의 비즈니스 로직을 담고 있다.
- view
  - 입출력 로직을 담고 있다.
- RacingCarController
  - '자동차 경주 미션'의 제어 로직을 담고 있다.
- RacingCarApplication
  - 프로그램의 실행 시작 지점이다.

2024-02-15 07:19 UTC, kimhodol requested changes
안녕하세요 커찬! 우테코에 오신 것을 환영해요 👋 
첫 미션인데도 불구하고 군더더기 없는 코드를 잘 짜주셨네요 💯 

간단한 리뷰 남겼으니 확인 부탁드릴게요!

2024-02-15 07:19 UTC, woonjangahn commented on README.md
> +  - [X] : 공동 우승자가 존재할 수 있다. (쉼표로 구분)
요구사항을 잘 정리해주시고, 기능 단위로 커밋을 잘 작성해주셨네요 👍

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/RacingCarController.java
> +            return Cars.of(carNames, new RandomMoveStrategy(new RandomDigitSupplier()));
의존성 주입과 전략 패턴을 잘 적용해주셨네요 👍

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/Car.java
> +        if (name.length() > 5) {
[의견] `5`라는 magic number에 의미를 부여해주는 것은 어떨까요?

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
[의견] `getPosition` 대신 `Car`가 어떤 포지션에 있는지 스스로 표현해주는 메소드가 있으면 어떨까요?

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/Cars.java
> +        });
[의견] `car`에 불필요한 괄호를 없앨 수 있을 것 같아요.

```suggestion
        carList.forEach(car -> car.move(moveStrategy.isMove()));
```

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/Cars.java
> +                .orElse(0);
```suggestion
        int maxPosition = carList.stream()
                .mapToInt(Car::getPosition)
                .max()
                .orElse(0);
```

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/view/InputView.java
> +public class InputView {
[의견] 인스턴스로 생성하지 않는다는 의미를 주기 위해 `private` 생성자를 만들어주는 것은 어떨까요?

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/view/OutputView.java
> +public class OutputView {
[의견] 인스턴스로 생성하지 않는다는 의미를 주기 위해 `private` 생성자를 만들어주는 것은 어떨까요?

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/TrialCount.java
> +    public void repeat(Runnable consumer) {
[질문] `Runnable` 타입을 가진 `consumer`이라는 인자명은 다소 어색한 것 같은데, 의도하신 바가 있을까요?

2024-02-15 07:19 UTC, kimhodol commented on src/test/java/domain/CarTest.java
> +    void creationTest_whenNameLengthIsBlank_throwException(String name) {
`@ParameterizedTest`를 활용해주셨네요 👍

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/domain/RandomMoveStrategy.java
> +    public static final int MIN_MOVABLE_DIGIT = 4;
[의견] 접근제어자가 `private`이어도 될 것 같네요!

2024-02-15 07:19 UTC, kimhodol commented on src/main/java/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
[질문] `Scanner` 대신 `BufferedReader`을 사용하신 이유가 있을까요?

2024-02-16 06:05 UTC, leegwichan reviewed
페어 프로그래밍이 처음이다 보니, 평소에 보이던 부분도 잘 안보이게 되는 것 같네요;;
의견 주신 부분을 반영해서 작성해보도록 하겠습니다~

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/domain/Car.java
> +        if (name.length() > 5) {
우선, 숫자를 넣으면서 동작하는 코드에 집중하다 보니 5에 상수로 놓는 것을 깜박했네요;;
주신 의견에 맞춰 수정하도록 하겠습니다.

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/domain/Cars.java
> +        });
처음에는 `{}`안에 있는 구문이 여러 줄이었다가, 차례대로 줄여나갔습니다.
마지막 한 줄까지 줄이고 나서 더 간단하게 나타낼 수 있다는 점을 놓쳤네요;;

주신 의견에 맞춰 수정하도록 하겠습니다~

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/domain/RandomMoveStrategy.java
> +    public static final int MIN_MOVABLE_DIGIT = 4;
한 화면으로 두 명이서 프로그래밍 하다 보니 놓쳤던 것 같습니다.

주신 의견에 맞추어 수정하도록 하겠습니다.

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/domain/TrialCount.java
> +    public void repeat(Runnable consumer) {
처음에 설계할 때는 Consumer를 써야 되는 것 같아 해보다가, Runnable로 바꾼다는 것을 못바꿨네요.

Runnable로 수정해보도록 하겠습니다.

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/view/InputView.java
> +public class InputView {
평소에 `private` 생성자를 만들어 주는데, 이번에는 만들지 않았네요;;

주신 의견 반영해 보도록 하겠습니다.

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/domain/Cars.java
> +                .filter(car -> car.getPosition() == maxPosition)
객체 내부에 있는 값을 직접적으로 사용하는 것이 아니라, 해당 객체가 직접적으로 판단할 수 있어 좋은 것 같습니다!
주신 의견을 반영해서 `Car`에 메서드를 만들어 보도록 하겠습니다!

2024-02-16 06:05 UTC, leegwichan commented on src/main/java/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
제가 콘솔 창에서 입력받는 방법을 잘 몰라서 페어의 의견에 전적으로 따랐습니다.

제가 짤막하게 조사한 바로는 성능 면에서 `BufferReader`를 사용하는 것이 좋다고 생각합니다.
대신 `Scanner`는 단순히 String 뿐만 아니라 `nextInt()`와 같은 편의 메서드를 제공해 주는 것을 알게 되었습니다.
'자동차 경주' 미션이 성능에 크게 영향을 받지 않으므로, `Scanner`를 이용해 보도록 하겠습니다~

2024-02-16 07:34 UTC, ahnw1 commented on src/main/java/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
`Scanner`을 꼭 써야 한다는 것은 아니고, 정말 궁금해서 여쭤본거였습니다 ㅋㅋ 제가 옛날에 미션할때 Scanner을 썼던 것 같아서요. 동작만 확인되면 이슈 없습니다 :) 반드시 모든 리뷰를 반영할 필요는 없어요 ㅎㅎ

2024-02-16 07:41 UTC, ahnw1 commented on src/main/java/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
🤖 GPT한테 물어보니 다음과 같다고 합니다!

`Scanner`와 `BufferedReader`는 자바에서 텍스트 데이터를 읽기 위해 사용되는 두 가지 다른 클래스입니다. 간단하고 쉽게 차이점을 설명하자면:

1. **용도**:
   - **Scanner**: 사용자 입력과 같은 간단한 텍스트 읽기 작업에 적합합니다. 토큰 기반의 입력(공백으로 구분된 데이터 등)을 처리하는데 유용하며, 다양한 타입(int, float, 등)으로 데이터를 자동 변환할 수 있는 메소드를 제공합니다.
   - **BufferedReader**: 큰 파일이나 데이터 스트림을 효율적으로 읽기 위해 설계되었습니다. 문자열 데이터를 줄 단위로 읽는데 최적화되어 있으며, 성능상의 이점을 제공합니다.

2. **성능**:
   - **Scanner**: 내부적으로 정규 표현식을 사용하기 때문에 `BufferedReader`보다 느릴 수 있습니다.
   - **BufferedReader**: 버퍼링을 통해 대량의 데이터를 읽을 때 더 빠르고 효율적입니다.

3. **사용 편의성**:
   - **Scanner**: 사용하기 쉽고, 다양한 타입의 입력을 쉽게 처리할 수 있습니다. 예를 들어, `nextInt()`, `nextFloat()` 등의 메소드를 통해 다양한 타입의 입력을 직접 받을 수 있습니다.
   - **BufferedReader**: 주로 문자열 입력을 처리하며, `readLine()` 메소드를 통해 한 줄씩 읽습니다. 타입 변환을 수동으로 처리해야 할 수도 있습니다.

4. **버퍼링**:
   - **Scanner**: 내부적으로 버퍼링을 사용하지만, `BufferedReader`만큼 크지는 않습니다.
   - **BufferedReader**: 명시적으로 버퍼 크기를 설정할 수 있으며, 대량의 데이터를 효율적으로 처리할 수 있도록 설계되었습니다.

결론적으로, 간단한 사용자 입력이나 작은 파일을 처리할 때는 `Scanner`를, 큰 파일이나 데이터를 효율적으로 처리해야 할 때는 `BufferedReader`를 사용하는 것이 좋습니다.

2024-02-16 07:45 UTC, kimhodol commented
실수로 회사 계정으로 코멘트를 몇 개 달았는데, 동일 인물이니까 너무 당황하진 마셔요 🥲

고생하셨습니다 :) 다음 미션도 화이팅입니다 🚀

2024-02-16 07:45 UTC, merged