[1단계 - 자동차 경주 구현] 아루(이동훈) 미션 제출합니다.
woowacourse/java-racingcar pull request #657
Opened 2024-02-15 06:21 UTC by donghoony

안녕하세요 미르! 6기 아루로 함께하게 되었습니다. 잘 부탁드려요 🤩

이번 요구사항 완성까지는 페어와 함께 모두 구현했어요. 페어로 구현하는 것이 너무 재미있어서 시간 가는 줄 몰랐던 것 같네요. 코딩에 대한 주관이 확실한 페어를 옆에 둬서 토론을 많이 했고, 해결하지 못한 고민들을 공유해요. 혹시 조언하고 싶으신 부분이 있다면 가감없이 부탁합니다!

#### 입력값 검증은 뷰가 담당해야 할까요, 도메인이 담당해야 할까요? 
- 이번 미션에서의 '글자 수' 검증을 페어는 입력단에서 검증해야 하고, 저는 도메인에서 해야 한다고 생각해서 서로 의견이 부딪혔습니다. 페어는 글자 수가 도메인까지 내려가서 검증해야 하는 것과, 글자 수가 도메인의 책임인지에 대해서 물었고, 저는 글자 수는 도메인의 책임이다! 라는 이야기로 의견차를 좁히기 어려웠어요.
- 검증할 것이 많아져 `InputValidator`와 같은 클래스를 따로 두고, 그 클래스에서 입력들을 검증하는 것도 해당 클래스의 책임이 '검증'이라는 것으로 포장돼 너무 추상적이라고 생각했습니다. 이번 미션에서는 도메인에서 검증을 진행했어요. 미르의 의견이 궁금합니다 🙂

#### 클래스에서 무엇을 상수로 덜어내야 하는지 궁금해요. 단순한 값들은 그냥 두어도 괜찮은가요?
- 저는 문자열이나 범위를 나타내는 수를 보면 이를 상수로 만들곤 했습니다. 변경에도 용이하고, 상수에 이름을 붙이면 사용할 때의 가독성을 높일 수 있다고 생각했어요.
- 하지만 페어는 **한 번만 사용할 값**이나 **이미 메서드에 의미가 녹아있는 경우**, 상수를 쓰지 않는 편이 가독성이 좋다고 생각했습니다. 예를 들면 `Name`의 최대 글자수인 `5`는 상수로 두었지만, `validateNameLength`이라는 메서드 이름에서 이미 글자수를 내포하고 있기 때문에 사용하지 않는 편이 좋다는 페어의 의견이 있었습니다.

#### `Car`의 정보를 담는 `CarStatus` 를 어디에서 생성해야 할까요?
- 현재로서는 `Car` 객체에서 `getStatus`를 통해 자동차의 이름, 위치를 가져오도록 하고 있습니다. 하지만 `CarStatus`에서 정적 팩토리 메서드를 사용해 `Carstatus.from(Car)`처럼 만들면 좋겠다는 생각을 하고 있었어요. 하지만 `CarStatus`에서 생성하는 경우 `Car`의 필드를 외부에서 참조해야 하는 문제가 발생합니다. 정보를 담는 객체를 반환하는 메서드를 원래 클래스에 작성해도 괜찮은가요?
	
#### `getter`는 상황에 따라 사용해도 괜찮을까요?
-  "객체에 메시지를 던져라" 라는 것에 따라, `getXX`를 사용해 값을 가져와서 비교하는 것보다는 창구를 열어 객체에게 물어보고, `getter` 사용을 지양하고 있었어요.
- 하지만 자동차의 이름을 책임지는 `Name` 클래스의 경우, `Car`에서만 사용되는 이름이기도 하고,  `Car`를 표현할 때 이름을 가져올 필요가 있었어요. 메시지를 던지는 방법으로 사용하지 않기 때문에 이 경우에는 `getter`를 사용해도 괜찮다고 생각했습니다.

#### 플로우를 담당하는 클래스와 도메인과의 의존성은 필연적인 것일까요?
- 현재는 페어와의 이야기 끝에 클래스가 나뉘어져 있지만, 기존 코드는 경주의 흐름을 담당하는 `CarController`에서 `Engine`을 한 번 만든 뒤, `Circuit`에 넣어 주는 방식이었어요. 하지만 엔진을 만드는 게 다소 어색하게 느껴져서 `CarFactory`라는 생성하는 클래스를 분리한 뒤, 해당 객체에게 책임을 지게 했습니다.
- 이로써 `Controller`에서는 `Engine`과 무관하게 되었어요. 하지만 이를 고려하지 않았더라면 추가적인 코드를 작성할 필요도 없고, 깔끔하게 마무리할 수 있지 않았을까? 라는 생각을 하게 되었습니다. 흐름을 제어하는 클래스에서 도메인을 생성하는 의존성이 좋지 않다고 할 수 있나요?
- 나아가 `CarFactory`를 만들게 되더라도, 단순히 "자동차를 생성한다" 라는 역할이 전부이므로, 저는 이 클래스를 객체로 만드는 것에 반대했어요. `static createCars(List<String>, Engine)`를 통해 자동차를 생성해주는 방식은 어떤가? 라는 질문이 머릿속에서 이어졌습니다.
- `CarFactory`에게는 `NumberGenerator`를 주어야 할까, `Engine`을 주어야 할까? 둘 다 아니라면, `static`으로 단순히 생성하는 게 나을까? 라는 질문이 남은 채로 코드를 작성했습니다. 미르라면 어떻게 작성하실 지 궁금해요. 🙄

(이전에는 아래와 같은 이야기를 주고받았습니다.)
- 바깥에서 `NumberGenerator`가 아닌 `Engine`을 만들어서 `Controller`에게 제공하는 편이 낫지 않을까?
- 그런데 `Engine`은 도메인인데 `Controller`와의 의존성이 추가된다. 필요한 의존성인가?
- 사실 이미 `Engine`에 대한 의존성은 가지고 있다고 봐야 할까? `new`를 통해서 생성하고 있으니까?

쓰다 보니 글이 길어지게 되었네요 😅 조금 더 고민하면 좋겠다 싶은 이야기들은 답변을 질문으로 남겨주셔도 괜찮습니다. 페어와 더 토의해보고 각자의 주관을 확실히 잡을 수 있을 것 같아요. 도움 주셔서 정말 고맙습니다 🙌

2024-02-15 13:43 UTC, ddu0422 requested changes
안녕하세요 아루~  미르입니다 :)
몇 가지 고민할 점 코멘트 남겨드렸습니다!
자유롭게 아루의 의견을 이야기 주시면 될 것 같아요~

추가로 가독성 향상을 위해 전체 컨벤션을 맞추는 연습도 해보시면 어떨까요?
(공백에도 의미를 부여해 보는 건 어떨까요?)

> 입력값 검증은 뷰가 담당해야 할까요, 도메인이 담당해야 할까요?

제 의견과는 관계없이 페어분과 다시 상의할 때, 서로의 의견을 들으며 둘이 충분히 납득할만한 근거를 찾아보는건 어떨까요? 

> Car의 정보를 담는 CarStatus 를 어디에서 생성해야 할까요?

CarStatus는 Car가 없는 경우에 어떤 의미를 가지는지 생각해보면 어떨까요?
그러면 답을 생각보다 쉽게 찾을 수 있을 것 같습니다!

> getter는 상황에 따라 사용해도 괜찮을까요?

네! 적절한 근거가 있으신 것 같아요 :)

> 플로우를 담당하는 클래스와 도메인과의 의존성은 필연적인 것일까요?

반대로 의존성을 분리하고 싶다면 어떤 방식으로 플로우를 실행할지 고민해보는건 어떨까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/CarFactoryTest.java
> +    }
ParameterizedTest 👍🏻

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/CarTest.java
> +    Engine poweredOffEngine = new Engine((startInclusive, endInclusive) -> 0);
언제 사용하는걸까요~?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/CarTest.java
> +    Engine poweredOffEngine = new Engine((startInclusive, endInclusive) -> 0);
Test Class 외부에서도 사용할 수 있도록 한 특별한 이유가 있을까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/CarTest.java
> +    }
움직이지 않는 테스트도 작성하는건 어떨까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
Name 내부에서는 CustomException으로 예외처리를 하였는데 테스트 검증 시에는 포괄적인 RuntimeException으로 검증한 이유가 있을까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
Name 생성 시 null인 경우에는 어떻게 될까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/view/InputViewTest.java
> +    @DisplayName("시도한 범위가 올바른 범위라면, 정수로 변환한다")
양의 정수라고 표현해야하지 않을까요~?

2024-02-15 13:43 UTC, ddu0422 commented on src/test/java/racingcar/CarControllerTest.java
> +    @DisplayName("예외가 발생하는 경우 메시지를 출력한 뒤 다시 입력받는다.")
어떤 데이터가 어떤 상황에서 예외가 발생하는지 알기 어렵지 않을까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/Circuit.java
> +                .filter(carStatus -> carStatus.position() == maxPosition)
CarStatus에서 값을 가져와서 비교한 이유가 있을까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/Engine.java
> +        int value = numberGenerator.generateNumberInRange(MIN_RANGE, MAX_RANGE);
숫자의 범위를 정하는 책임이 Engine이 적절할까요? 🤔

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/Name.java
> +    private static final int MAX_LENGTH = 5;
Convention을 통일하는 작은 습관을 길러보는건 어떨까요~?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/Name.java
> +    private static final int MAX_LENGTH = 5;
MAX_LENGTH 보다 명확한 네이밍은 없을까요?

> 저는 문자열이나 범위를 나타내는 수를 보면 이를 상수로 만들곤 했습니다. 변경에도 용이하고, 상수에 이름을 붙이면 사용할 때의 가독성을 높일 수 있다고 생각했어요.
하지만 페어는 한 번만 사용할 값이나 이미 메서드에 의미가 녹아있는 경우, 상수를 쓰지 않는 편이 가독성이 좋다고 생각했습니다. 예를 들면 Name의 최대 글자수인 5는 상수로 두었지만, validateNameLength이라는 메서드 이름에서 이미 글자수를 내포하고 있기 때문에 사용하지 않는 편이 좋다는 페어의 의견이 있었습니다.

메서드와 상수는 어떤 책임을 지닐까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/CarStatus.java
> +public record CarStatus(String name, int position) {
record class는 일반 class와 어떤 점이 다를까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/view/reader/ConsoleReader.java
> +public class ConsoleReader implements Reader {
ConsoleReader를 나눈 이유가 있을까요?

2024-02-15 13:43 UTC, ddu0422 commented on src/main/java/racingcar/domain/Engine.java
> +    private boolean isWorking = false;
엔진을 끄고 키는 것과 자동차를 움직이는 것의 2가지 책임을 지니고 있는 게 아닐까요?

2024-02-15 14:47 UTC, donghoony commented on src/main/java/racingcar/domain/CarStatus.java
> +public record CarStatus(String name, int position) {
필드가 상수로 고정되고, 기본 `getter`, `hashCode`, `equals`와 같은 boilerplate code를 정의해주는 강점이 있어, 값을 담아두고 쓰는 데 좋을 것 같아 사용했어요.

2024-02-16 06:14 UTC, donghoony commented on src/main/java/racingcar/domain/Name.java
> +    private static final int MAX_LENGTH = 5;
`MAX_NAME_LENGTH`가 낫겠습니다.

메서드는 코드 다발에 이름을 붙인 것이라고 생각해요. 메서드는 그만큼 코드 전반을 대표하는 이름을 가져야 하고, 이는 곧 하나의 메서드에 여러 일을 하지 않도록 하는 책임이 부여되는 듯해요.

상수는 수에 이름을 붙인 것이라고 생각해요. 단순한 수에 이름을 붙여서 의미를 가지게 하고, 코드를 보는 사람이 이해가 쉽도록 하는 책임이 있습니다. (물론 재사용성과 변경에 쉬운 것도 있겠네요)

각자의 책임이 있으니 메서드 이름도 알아보기 쉽게 잘 작성하고, 상수도 잘 뽑아서 적어두는 것이 바람직할 것이라는 생각을 하게 되었습니다 😄

2024-02-16 06:35 UTC, donghoony commented on src/main/java/racingcar/domain/Name.java
> +    private static final int MAX_LENGTH = 5;
페어와 코딩하면서 컨벤션을 우선 같이 맞추는 것도 중요한 일이겠네요. 혹여 클래스 이름 바로 뒤에 빈 줄을 남겨두는 것이 일반적인 컨벤션에 어긋나는 것이라면 알려주시면 감사하겠습니다. 보기 편한 것 같아 모든 클래스에서 한 줄을 띄도록 수정할게요.

2024-02-16 06:44 UTC, donghoony commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
구현에 대한 테스트를 미리 작성하고, 이후에 CustomException을 구현해 테스트를 미처 수정하지 못했습니다. 예외를 바꾸고 나서 포괄적인 `RuntimeException`을 확인할 방법이 없었네요.

`CustomException` 때문일지, 다른 방식으로 구현하면 이 문제가 해결되는지는 더 공부해보겠습니다

2024-02-16 07:01 UTC, donghoony commented on src/test/java/racingcar/domain/CarTest.java
> +    Engine poweredOffEngine = new Engine((startInclusive, endInclusive) -> 0);
`default` 접근제한자에서 같은 패키지끼리는 객체를 생성한 뒤 이를 사용할 수 있겠지만, 코드에서는 사용하지 않았습니다. 테스트 코드를 인스턴스화하는 것도 생각해본 적 없는데요..

테스트 코드에서 `private`을 사용할 이유를 찾지 못했어요. 그렇게 생각한다면 `new`를 통해 다른 곳에서 생성될 수 있으므로 모든 테스트의 생성자를 `private`으로 막는 번거로움이 생기게 될 것 같습니다.

테스트 코드에서는 테스트에 집중하기 위해서 접근제한자에 대한 엄격한 기준을 덜었고, 외부에서는 이를 사용하지 않습니다.

2024-02-16 07:01 UTC, donghoony commented on src/test/java/racingcar/domain/CarTest.java
> +    Engine poweredOffEngine = new Engine((startInclusive, endInclusive) -> 0);
움직이지 않는 테스트를 미처 작성하지 못했습니다.

2024-02-16 07:01 UTC, donghoony commented on src/test/java/racingcar/domain/CarTest.java
> +    }
작성하겠습니다 👍🏼

2024-02-16 07:14 UTC, donghoony commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
`@CsvSource`로 수정하고, `null`의 경우를 추가합니다. `Name`에서의 검증도 추가하겠습니다.

2024-02-16 07:15 UTC, donghoony commented on src/test/java/racingcar/view/InputViewTest.java
> +    @DisplayName("시도한 범위가 올바른 범위라면, 정수로 변환한다")
**올바른 범위**가 positive라는 의미를 담고 있다고 생각했어요 (요구사항).
테스트도 문서라는 점에서, 양의 정수가 조금 더 명확한 것 같네요. 수정하겠습니다

2024-02-16 07:37 UTC, donghoony commented on src/main/java/racingcar/domain/Circuit.java
> +                .filter(carStatus -> carStatus.position() == maxPosition)
바로 위에서 `객체에 메시지를 던진다`를 이야기했는데, 부끄럽네요 😅
`CarStatus`를 비교 가능하도록 하고, 현재 이 포지션에 있는지 여부를 물어보는 메서드를 추가해 해결하겠습니다.

2024-02-16 07:43 UTC, donghoony commented on src/main/java/racingcar/domain/Engine.java
> +        int value = numberGenerator.generateNumberInRange(MIN_RANGE, MAX_RANGE);
인터페이스를 만들었으니, 수의 범위는 구현체가 맡아야 한다고 생각해요. 따라서 인터페이스를 `generate()`로 더 범용화하고, 구현체에서 범위 내에서 랜덤한 수를 뽑도록 수정하면 좋을 것 같아 수정합니다.

2024-02-16 07:53 UTC, donghoony commented on src/main/java/racingcar/view/reader/ConsoleReader.java
> +public class ConsoleReader implements Reader {
처음에는 입력에 대한 테스트를 진행해야겠다는 생각의 흐름으로 인터페이스를 작성한 뒤, 이를 구현하는 방식으로 진행했어요. 하지만 결국 테스트를 할 때에는 테스트를 하기 위한 `InputStream`을 만든 뒤, 이를 사용했네요.

테스트에서 이를 활용할 수 있도록 수정하고자 합니다. 위와 같이 `InputStream`을 사용하여 값을 테스트하는 방식은, 여러 줄을 미리 넣어둬야 하기 때문에 `CarControllerTest`에서 사용하겠습니다.

2024-02-16 07:54 UTC, donghoony commented on src/main/java/racingcar/view/reader/ConsoleReader.java
> +public class ConsoleReader implements Reader {
`Reader`가 하나의 `abstract method`를 가지므로, `@FunctionalInterface` 어노테이션도 추가하겠습니다

2024-02-16 07:57 UTC, donghoony commented on src/main/java/racingcar/view/reader/ConsoleReader.java
> +public class ConsoleReader implements Reader {
테스트를 위한 코드를 작성하는 느낌이었어서 찝찝한 느낌을 지울 수 없네요.. 😅

2024-02-16 08:08 UTC, donghoony commented on src/main/java/racingcar/domain/Engine.java
> +    private boolean isWorking = false;
엔진 클래스의 전체적인 책임을 말씀하시는 건가요? 엔진의 입장에서는 켜지거나/꺼지거나를 결정하고, 자동차에서 엔진의 상태를 확인하는 것으로 전진 여부를 결정하는 것이라 두 가지 책임으로 보지 않았어요. 

혹시 제가 잘못 짚고 있다면 다시 이야기해주시면 감사하겠습니다 😀

2024-02-16 08:18 UTC, donghoony commented
안녕하세요 미르! 꼼꼼하게 확인해주셔서 정말 고맙습니다. 많은 질문들 덕분에 제 주관을 조금씩 찾아가고 있는 것 같아 기뻐요 😊

> 제 의견과는 관계없이 페어분과 다시 상의할 때, 서로의 의견을 들으며 둘이 충분히 납득할만한 근거를 찾아보는건 어떨까요?

많은 크루들과 이야기를 나눈 결과, 뷰와 도메인에서 각각 검증할 것을 나누는 방향으로 갈피가 잡혔습니다. 간단한 형식, 정수와 같은 파싱은 뷰에서 검증해도 괜찮지만, 도메인의 정보를 다루는 부분은 도메인에서 검증하는 것이 바람직하다고 생각했어요. 도메인의 필드니깐 도메인이 관리해야 한다, 책임의 입장에서 바라봐서 더 명확해졌습니다.
 
> CarStatus는 Car가 없는 경우에 어떤 의미를 가지는지 생각해보면 어떨까요? 그러면 답을 생각보다 쉽게 찾을 수 있을 것 같습니다!

`CarStatus`는 `Car`가 없으면 그 의미도 사라지므로, `Car`와 `CarStatus`의 의존성은 필연적이라고 생각했습니다. `Car` 내부에 값을 나타내는 객체인 `CarStatus`를 생성할 수 있게 하는 것도 자연스럽게 느끼게 되었어요.
다만 아무래도 도메인 객체가 아닌 부분에서의 수정이 도메인의 수정으로 이어질 수 있는 점은 조심스럽게 느껴지기도 합니다.

> 반대로 의존성을 분리하고 싶다면 어떤 방식으로 플로우를 실행할지 고민해보는건 어떨까요?

중간에 레이어와 같은 클래스를 추가해서 의존성을 분리할 수도 있겠지만, 이 경우에 '정말 분리한 것이 맞는가?' 라는 의구심이 계속 들 것 같습니다. 흐름만을 제어하는 책임에 더 집중하면 대안이 보였습니다. 이번에 구현한 `CarFactory`처럼 생성하는 곳을 바깥으로 뺌으로써 `CarController`와 `Car`간의 의존성은 제거했지만, 결국 `CarFactory`라는 층이 하나 늘어난 결과에 만족할 만한 근거는 아직 찾지 못했어요. 조금 더 고민해봐야 할 것 같습니다 🙂

2024-02-16 08:36 UTC, donghoony commented on src/test/java/racingcar/CarControllerTest.java
> +    @DisplayName("예외가 발생하는 경우 메시지를 출력한 뒤 다시 입력받는다.")
명확하게 하기 위해 `ValueSource`에 들어가는 값과 `DisplayName`을 수정했습니다.

2024-02-16 11:12 UTC, ddu0422 commented on src/test/java/racingcar/domain/CarTest.java
> +    Engine poweredOffEngine = new Engine((startInclusive, endInclusive) -> 0);
다른 코멘트에서 테스트 코드도 문서인 점을 인지하셨군요~
문서란 다른 팀원에게 어떤 의미를 지닐까요?

지금은 같은 미션을 하고 있기에 크게 와닿지 않을 수 있지만, 다른 관점에서 생각해보는 것도 재밌는 일이라고 생각해요 😄

2024-02-16 11:13 UTC, ddu0422 commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
> 예외를 바꾸고 나서 포괄적인 RuntimeException을 확인할 방법이 없었네요.

제가 리뷰를 모호하게 드렸네요 ㅎㅎ
CustomException은 RuntimeException을 상속받기 때문에 정확히 어떤 예외가 발생하는지 테스트하기가 어렵다는 의미만 전달하고 싶었습니다~

2024-02-16 11:16 UTC, ddu0422 commented on src/main/java/racingcar/domain/Name.java
> +    private static final int MAX_LENGTH = 5;
컨벤션은 다른 문서나 의견을 수렴할 수 있지만 본인에게 맞는 방식으로 사용하면 된다고 생각해요 :)
컨벤션이란 무엇을 의미할까요? 🤔

2024-02-16 11:18 UTC, ddu0422 commented on src/main/java/racingcar/view/reader/ConsoleReader.java
> +public class ConsoleReader implements Reader {
테스트하기 어렵다면 테스트하기 쉬운 코드로 변경하는건 괜찮다고 생각해요 👍🏻 
좋은 고민 포인트니 우테코 생활을 하면서 고민해보면 괜찮을 것 같습니다 ㅎㅎ

2024-02-16 11:22 UTC, ddu0422 commented on src/main/java/racingcar/domain/Engine.java
> +    private boolean isWorking = false;
아니요! 아루의 의견이 맞을 수 있어요. 관점의 차이라고 생각하기 때문이에요.
자신감있게 아루의 의견을 주장해도 괜찮습니다 ㅎㅎ

2024-02-16 11:26 UTC, ddu0422 approved these changes
안녕하세요 아루! 미르입니다 :)
이번 미션 정말 고생 많으셨어요 ㅎㅎ
간단한 미션임에도 많은 걸 얻었다고 생각해요 💯 

아직 고민할 부분이 많이 있겠지만 다음 미션을 해결해가면서 충분히 해결할 수 있으리라 믿습니다 🥇 
궁금하신 부분이 많을 테지만 천천히 아루만의 개발을 하면 될 것 같아요 :)

이번 미션은 여기서 마무리할게요.
정말 고생 많으셨습니다!

2024-02-16 11:26 UTC, merged

2024-02-17 10:55 UTC, donghoony commented on src/test/java/racingcar/domain/NameTest.java
> +        Assertions.assertThrows(RuntimeException.class, () -> new Name(name));
앗, 답변도 모호했던 것 같네요. 구현에 대한 테스트를 작성하고, 이후에 CustomException을 작성할 때, 기존의 `RuntimeException`을 고치는 것을 놓쳤다는 의미였습니다. 이를 `어떻게 쉽게 알아챌(?) 수 있을까`가 고민이었어요.
`// TODO`를 활용하는 것도 하나의 방법이 될 것 같습니다..!