레벨 1 자동차 경주 미션 1단계 제출합니다.
woowacourse/java-racingcar pull request #658
Opened 2024-02-15 06:24 UTC by slimsha2dy

## 기능 목록
- [x] 자동차 이름을 입력 받는다
  - [x] 공백, null 값이면 예외를 발생 시킨다
  - [x] ✅ ","로 끝나면 예외를 발생 시킨다
  - [x] ","로 split 해준다
- [x] 자동차 이름에 올바른 값이 들어왔는지 확인한다(자동차 각각)
  - [x] 앞 뒤 공백을 제거한다
  - [x] 공백, null 값 체크
  - [x] ✅ 영문, 숫자, "_", "-"를 제외한 다른 값이 있는 경우 예외를 발생 시킨다
  - [x] 5자를 초과하는 경우 예외를 발생 시킨다
- [x] 중복되는 자동차 이름이 있으면 예외를 발생 시킨다
- [x] ✅ 총 자동차가 2대 이상 10대 이하가 아니면 예외를 발생 시킨다
- [x] 시도할 횟수를 입력 받는다
  - [x] 공백, null 값이면 예외를 발생 시킨다
  - [x] 입력한 숫자가 양의 정수가 아니면 예외를 발생 시킨다
  - [x] ✅ 시도 횟수가 1,000을 초과하면 예외를 발생 시킨다
- [x] 아래 동작을 시도할 횟수만큼 반복한다
  - [x] 0에서 9 사이의 랜덤 값을 생성한다
  - [x] 생성한 랜덤 값이 4 이상이면 자동차를 전진한다
  - [x] 각 자동차의 현재 상황을 "이름 : -"와 같이 출력한다
- [x] 모든 자동차 중에 가장 큰 전진 횟수를 찾는다
- [x] 가장 큰 전진 횟수와 동일한 자동차들을 필터링한다
- [x] ", "로 합쳐서 출력한다
- [x] ✅ 사용자의 입력에 대한 예외가 발생하면 해당 입력을 다시 받을 수 있도록 돌아간다

✅: 미션 요구 사항에 명시적으로는 없지만 구현한 부분

2024-02-15 14:42 UTC, syoun602 requested changes
안녕하세요 알파카 👋
첫 미션임에도 불구하고 너무 잘 구현해주셨네요~!
잘 작성된 기능목록부터 기본적인 컨벤션, 꼼꼼한 테스트까지 👍

간단한 코멘트 남겼으니 궁금하신게 있다면 언제든 코멘튼나 DM을 활용해주세요!

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/Application.java
> +}
[POSIX new line](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)에 대해 알아볼까요?
[인텔리제이 자동 개행 설정](https://kukim.tistory.com/100)을 추가해보아요

2024-02-15 14:42 UTC, syoun602 commented on README.md
> +## 기능 목록
꼼꼼한 기능목록 작성 👍

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/config/RacingCarConfig.java
> +public enum RacingCarConfig {
도메인 제약사항(+`ExceptionMessage` 클래스의 예외 메시지)를 enum으로 한 곳에서 관리하고 있네요!
이렇게 한 곳에서 관리했을 때 알파카가 느끼는 장점과 단점을 듣고 싶어요 😊

+) 앗 그리고 `config`라는 단어가 들어가면 무언가 설정을 할 것 같은데 여기는 그냥 제약사항에 대한 상수만 정의해놓은 enum 클래스네요!

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/controller/MainController.java
> +        final int tryCount = getTryCount();
get이라는 단어가 들어가면 그냥 단순히 값을 꺼낼 것 같은데, 좀 더 의미있는 메서드명을 작성해볼까요?

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Cars.java
> +                .orElseThrow(IllegalArgumentException::new);
예외 메시지를 정의해보아요

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +public class Car implements Comparable<Car> {
별도로 Comparable 인터페이스를 사용하셨네요 👍

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +        this.name = name.trim();
`trim()`을 여러 번 작성하셨네요. 중복을 줄여볼까요?

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +    }
도메인이 출력에 대한 책임까지 들고 있는게 맞을까요?

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Cars.java
> +    private final List<Car> cars;
일급 컬렉션 활용 👍

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/service/RandomNumberGenerator.java
> +    }
private 생성자를 잘 활용하셨네요 💯

2024-02-15 14:42 UTC, syoun602 commented on src/test/java/racingcar/domain/CarTest.java
> +class CarTest {
꼼꼼한 테스트 작성 👍 경계값도 잘 테스트해주셨네요

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/controller/MainController.java
> +public class MainController {
`MainController` 보다는 조금 더 의미있는 클래스명을 사용해보는건 어떨까요?

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +        Pattern pattern = Pattern.compile(regex);
매번 재사용되는 객체라면 상수로 분리해볼 수 있지 않을까요?

2024-02-15 14:42 UTC, syoun602 commented on src/main/java/racingcar/domain/Cars.java
> +    private List<String> getSamePositionCars(final Car highestPositionCar) {
메서드 순서에 신경써봅시다! 코드도 하나에 문서처럼 위에서 아래로 잘읽혀야 보기 좋은 코드가 될 것 같아요~

2024-02-17 13:47 UTC, slimsha2dy commented on src/main/java/racingcar/config/RacingCarConfig.java
> +public enum RacingCarConfig {
여러 파일에서 같은 의미로 여러 번 사용되는 상수들에 대해서 관리가 용이해진다는 장점이 있는 것 같습니다. 예를 들어 이름의 최대 길이를 바꾸고 싶을 때 해당 파일에서 한 번만 변경해도 예외 처리 코드와 예외 문구 출력에 모두 적용되어서 코드의 유지/보수 측면에서 편할 것 같습니다.
다만 한 곳으로 모았을 때, 코드를 보는 입장에서는 그만큼 파일의 이동이 잦아지게 되는 것 같아 가독성의 측면에선 안 좋은 점이 생기는 것 같습니다. 상수만으로 이해가 쉬운 경우 파일에 그냥 두거나 파일에서만 상수 처리를 해주는 것도 괜찮은 것 같습니다.

+ 해당 파일을 변경하면 과제 제한 사항이나 자의적으로 설정한 입력값의 범위를 변경할 수 있어서 파일의 이름을 config 라고 지었는데 다시 생각해보니 엄밀히 따지면 config 파일이라고 보기 힘들 것 같아 상수를 처리한 enum임을 알 수 있는 이름으로 수정하는 것이 나은 것 같습니다.

2024-02-17 13:52 UTC, slimsha2dy commented on src/main/java/racingcar/Application.java
> +}
파일의 끝에 개행이 없는 경우 POSIX 명세를 위반하는 줄은 몰랐네요 감사합니다!

2024-02-17 14:47 UTC, slimsha2dy commented on src/main/java/racingcar/controller/MainController.java
> +        final int tryCount = getTryCount();
새로운 메서드명을 위해 메서드의 역할을 고민해봤습니다.
getCars의 역할은 Cars 클래스의 생성자를 호출하고 예외를 처리하는 것인데, Cars의 생성자를 호출하는 건 createCars 메서드의 역할에 포함되는 것 같고, 예외 처리만을 굳이 하나의 메서드로 따로 뺄 이유가 없다고 생각해 createCars에서 처리하도록 수정했습니다.
getTryCount 메서드는 좀 더 역할에 맞는 메서드명으로 수정해봤습니다.

2024-02-17 15:25 UTC, slimsha2dy commented on src/main/java/racingcar/domain/Car.java
> +        this.name = name.trim();
trim()은 validateNotNull 이전에는 사용할 수 없어서 기존의 코드대로 작성했었는데 줄이려고 보니 깔끔하게 되지 않네요..

제가 생각한 방법으로는
1. validateNotNull을 따로 분리한다 -> validateName의 인자로 name.trim()을 넣을 수 있게 된다
   -> validateName에서 따로 빠져나와 불편하다
2. validateName에서 validateNotNull이 끝난 후 trimmedName 변수를 새로 만들어 이 변수를 이후 함수의 인자로 넣는다
   -> 그렇다 하더라도 필드에 반영할 땐 trim을 또 사용해야 해서 깔끔한 해결 방식이 아닌 것 같다. 
3. validateNotNull을 분리하고 이후 trimmedName 변수를 새로 만들어 validateName의 인자와 필드에 반영할 때 사용한다.
4. 냅둔다

함수의 중복을 줄일 수 있는 3번의 방식으로 해결했는데 중복 해결만을 위한 코드 같아서 찝찝하더라구요.. 멘토님의 의견이 궁금한데 어떻게 생각하시나요?

2024-02-17 17:16 UTC, slimsha2dy commented on src/main/java/racingcar/domain/Car.java
> +    }
저도 처음에는 값만 전달해주고 view에서 출력 처리를 해주는 것이 맞다고 생각해 String과 integer 값만 전달하는 식으로 구현하려고 C++의 pair처럼 여러 타입의 데이터를 간단하게 묶어서 view로 보낼 수 있는 방식을 생각해 봤습니다.
가장 비슷한 방식이 Map인 것 같았는데, Map은 key 값을 통해 value를 조회하는 컬렉션이라 값을 순서대로 하나씩 꺼내서 쓰는 경우에는 어색하다고 생각했습니다.
해당 메서드를 호출하는 곳에서 여러 Car의 결과를 순서에 따라 List에 담아 view로 보내주어야 했는데 일반적으로 Map은 순서가 없는 자료구조라고 알고 있었고, 그렇다고 List<Map>을 사용한다면 매번 iterator를 사용해 하나의 값만 들어있는 Map 여러개를 처리해야 해서 읽기도 불편하고 효율적이지 않은 것 같아 고민하다가 일단은 기능 구현을 위해 위의 방식으로 해결했었습니다.
찾아보니 LinkedHashMap은 값이 추가된 순서를 보장해준다고 하여 이를 사용해 출력에 대한 책임을 OutputView가 가지도록 수정해봤습니다!

2024-02-17 19:12 UTC, slimsha2dy commented on src/main/java/racingcar/controller/MainController.java
> +public class MainController {
역할을 쉽게 알 수 있도록 RacingController로 이름을 수정했습니다!

2024-02-17 19:14 UTC, slimsha2dy commented on src/main/java/racingcar/domain/Cars.java
> +    private List<String> getSamePositionCars(final Car highestPositionCar) {
놓쳤던 부분 같습니다 감사합니다!

2024-02-18 07:46 UTC, syoun602 approved these changes
안녕하세요 알파카~
1단계 리뷰 반영하시느라 수고 많으셨습니다!
전체적으로 잘 적용해주셔서 이만 머지하고 2단계 때 다시 뵙겠습니다.
본인만의 개발 철학을 쌓아가기 위해 조금 고민해볼만한 부분에 대한 코멘트 남겨봤으니,
충분히 고민해보시고 어떻게 결정하셨는지 다음 PR때 알려주세요 😊 

궁금한 점이 있으시다면 언제든 DM 보내주셔도 됩니다 😎

2024-02-18 07:46 UTC, syoun602 commented on src/main/java/racingcar/controller/RacingController.java
> +public class RacingController {
`Controller`라는 이름이 꼭 들어가야 하는 지에 대한 의문이 있습니다 🤔

현재 자바 콘솔기반 자동차 경주 게임을 만들고 있는데, 일반적으로 웹 애플리케이션에서 사용되는 MVC 아키텍처 네이밍을 따라갈 필요는 없다고 생각돼요. 일반적인 스프링 컨트롤러는`요청에 대한 전처리 -> 서비스 메서드 위임 -> 응답 반환`을 하는 반면, 알파카의 `RacingController`의 역할에 대해 살펴보자면, 아래와 같은 동작을 하고 있습니다.
```
1. 입력 값을 받는다.
2. 각 객체를 생성한다.
3. 라운드를 진행시킨다.
5. 모든 자동차를 전진 후, 각 라운드 결과를 출력한다.
6. 최종 결과를 출력한다.
```
웹 관점으로 본다면 오히려 컨트롤러+서비스의 역할을 하고 있다고 생각되는데요! 콘솔기반 게임 개발에서 굳이 엄격하기 MVC 패턴명을 따라갈 필요는 없다고 생각해요. 
차라리 게임의 동작을 담당하는 객체 관점의 네이밍을 사용해보는건 어떨까요?
단순 의견이므로 꼭 반영할 필요는 없습니다 :)

2024-02-18 07:46 UTC, syoun602 commented on src/main/java/racingcar/controller/RacingController.java
> +            return createCars(carNames);
자동차 이름 입력에 오류가 있다면 `StackOverFlow`가 날 것 같아요~!

2024-02-18 07:46 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +        this.name = trimmedName;
> trim 중복에 대한 질문

제가 너무 포괄적으로 말씀드린 것 같네요 😢
이미 적용하셨지만, `validateNotNull()` 내부의 `isEmpty()` 말고 `isBlank()`를 사용하는 것과 
기존 생성자의 순서를 아래와 같이 변경해보는 것을 의도했습니다!
```
public Car(final String name) {
    this.name = name.trim();
    validateNotNull(name);
    validateName(name);
}
```
이렇게 되면 생성자의 순서가 로직에 영향을 끼치게 되는데요! 현재 제가 작성한 로직의 경우 중복 제거 + 높은 가독성이 있으나, 누군가 의도치 않게 순서를 변경한다면 문제가 있을 수 있습니다. 

따라서, view에서 넘겨줄 때 애초에 앞 뒤 공백이 제거된 단어를 넘겨주고, 도메인 자신의 영역에만 관심을 가진 채로 앞뒤 공백이 있다면 예외를 반환하고 사용하는 입장에서 제대로 사용하도록 유도하는 방법도 있을 것 같아요. 이렇게 된다면 생성자 내부의 순서와 관계없이 항상 동작하는 코드를 작성할 수 있습니다!

정답은 없는 영역이니 알파카가 더 맞다고 생각되는 쪽으로 구현하시면 됩니다 😊
다만, 지금 작성하신 생성자는 로직에도 영향을 미치고 가독성도 높지 않을 것 같아요 🥲

2024-02-18 07:46 UTC, syoun602 commented on src/main/java/racingcar/domain/Car.java
> +        return Map.of(name, position);
view에 대한 의존은 줄었으나 여전히 필요한 메서드인지에 대해서는 의문이 드네요.
단순 `getter`랑 다를 바가 없는 것 같은데, `result()`라는 메서드명이 view에 의존하는 것 같네요!
만약, 자동차에 새로운 프로퍼티가 추가된다면 해당 메서드도 변경되야하지 않을까요?
`getter`를 쓰지 않는다는 것에 대한 의미를 다시 한번 살펴보면 좋을 것 같아요.
View에서 데이터를 보여주기 위한 getter는 충분히 합리적인 선택이라고 보여집니다!

[우테코 블로그](https://tecoble.techcourse.co.kr/post/2020-04-28-ask-instead-of-getter/) 
> getter를 무조건 사용하지 말라는 말은 아니다.
당연히 getter를 무조건 사용하지 않고는 기능을 구현하기 힘들것이다. 출력을 위한 값 등 순수 값 프로퍼티를 가져오기 위해서라면 어느정도 getter는 허용된다. 그러나, Collection 인터페이스를 사용하는 경우 외부에서 getter메서드로 얻은 값을 통해 상태값을 변경할 수 있다.

2024-02-18 07:46 UTC, syoun602 commented on src/main/java/racingcar/util/Constant.java
> +public enum Constant {
맞습니다! 각각의 장단점이 있겠지만 저라면 도메인 안에서 상수로 작성할 것 같은데, 이유는 다음과 같습니다.
1. 도메인이 커진다면 상수/예외메시지 enum 클래스가 굉장히 비대해진다. (ex. 상수가 100개가 넘어간다면?)
2. 도메인과 관련된 로직을 하나의 클래스에 응집할 수 있다.
3. 도메인과 관련된 로직이 변경된다면 도메인 내에서만 수정하면 된다.
4. 예외 로직과 메시지를 함께 관리할 경우 한 눈에 이해가 가능하다.

물론 제 개인적인 의견이니 알파카가 원하는 방식대로 적용해주시면 됩니다! 😊

2024-02-18 07:46 UTC, merged