[1단계 - 자동차 경주 구현] 엘라(오숙현) 미션 제출합니다.
woowacourse/java-racingcar pull request #681
Opened 2024-02-15 07:21 UTC by oshyun00

2024-02-15 11:41 UTC, andole98 requested changes
안녕하세요 리뷰어 안돌입니다.

README를 잘 작성해주신 것 같아요. 기능 목록 뿐 아니라 단어 정의 / 부록 등 잘 정리해주셔서 좋았습니다.

질문 남겨주신것에도 장/단점을 미리 생각해보신것도 훌륭해요. 👍 

질문 남겨드린것에 제 생각을 남겨봅니다.

알고 계시겠지만 정답이란 없습니다. 언제나 주어진 상황 속에서 가장 가치있는걸 선택하는게 최선입니다.

궁금하거나 다른 생각이 있다면 언제든지 코멘트 남겨주세요~

1. 의존성 갖는 관계에서 매개변수로 객체를 넘기는 방식과, 필드로 객체를 갖는 방식의 차이점

메서드와 필드부터 생각해보면 좋을것 같아요. 

메서드는 어떤 객체가 만들어지고 나서 수행됩니다. 그럼 매개변수는 객체가 메서드를 수행하기 위해서 부가적으로 필요한 재료가 되겠네요.

필드는 어떤 객체를 만들 때부터 필요합니다. 엘라님은 필드에 할당하는 방법으로 모두 생성자 주입을 사용하셨네요. 그럼 필드는 어떤 객체를 만들기 전에 필요한 재료가 되겠네요.

나머지는 더 생각해보시면 좋을것 같아요.

---

2. dto 재사용

저도 엘라와 같은 생각이에요. 

굳이 제 선호를 밝힌다면, 용도에 따라 사용하는걸 선호합니다.

`용도`가 다르다는건 사실 객체의 책임이 다르다는 것으로 이해할 수 있거든요.

---

3. dto 값을 활용하는 로직의 위치

dto는 레이어 specific한 용어가 아닙니다. 하지만 말씀하시는 맥락으로 보아 도메인 <> 뷰/컨트롤러 를 얘기하시는 것 같네요.

말씀해주신 대로 도메인 외부에서 dto를 처리하는게 좋습니다. dto 값에 더 관심있는 부분은 뷰/컨트롤러 입니다.

2024-02-15 11:41 UTC, andole98 commented on README.md
> +## 📒 단어 정의
매우 좋네요 :+1:

2024-02-15 11:41 UTC, andole98 commented on src/test/java/model/CarTest.java
> +        assertThat(car.getClass()).isEqualTo(Car.class);
이 검증은 왜 필요한걸까요~?

자바 컴파일러가 바로 윗줄 `Car car = ...` 를 보장해주는데 추가적으로 확인할 사항이 있는걸까요?

2024-02-15 11:41 UTC, andole98 commented on src/main/java/controller/RacingController.java
> +    }
indent 깊이가 2 이상이네요 :cry:

2024-02-15 11:41 UTC, andole98 commented on src/main/java/model/Car.java
> +    private static void validate(String name) {
`static` 이 필요한 이유는 무엇인가요?

2024-02-15 11:41 UTC, andole98 commented on src/main/java/model/Car.java
> +    private static final int CONDITION = 4;
CONDITION 으로 의미를 쉽게 예상하기 힘든것 같아요. 좀더 의도가 드러나는 이름이면 좋을것 같아요.

2024-02-15 11:41 UTC, andole98 commented on src/main/java/model/dto/CarState.java
> +    public static CarState create(Car car) {
이렇게 되면 Car와 CarState가 순환참조하네요.

이 메서드가 쓰이는 Car.captureCarState() 때문에 Car도 CarState를 의존하게 되고,
이 메서드는 Car를 의존하고 있어 상호참조 or 순환참조가 발생합니다.

이 패키지가 dto인것을 보아, 자연스러운 것은 CarState가 Car를 의존하는 것입니다.

2024-02-15 11:41 UTC, andole98 commented on src/main/java/model/intgenerator/IntGenerator.java
> +@FunctionalInterface
적절한 사용같네요 :+1:

2024-02-15 11:41 UTC, andole98 commented on src/main/java/model/intgenerator/RandomIntGenerator.java
> +    private static final int COUNT = 10;
변수 이름과 역할이 안 맞는것 같아요.

실제로는 random의 bound에 쓰이는데, `count라서 랜덤을 10번 만드는건가?` 로 오해할 수 있을것 같네요.

2024-02-15 11:41 UTC, andole98 commented on src/main/java/view/OutputView.java
> +        return String.join(", ", winners);
좋네요 :+1:

2024-02-16 23:51 UTC, oshyun00 commented on src/test/java/model/CarTest.java
> +        assertThat(car.getClass()).isEqualTo(Car.class);
생성자가 제대로 동작하는지에 대한 검증을 하고자 했습니다. 말씀을 듣고 보니 바로 윗줄에서 Car를 보장해주고 있어서 아랫줄의 코드는 결국 중복되는 내용이라는 생각이 들었어요. 생성자가 예외 없이 동작하는지 검증하는 방식으로 변경하였습니다.

2024-02-16 23:52 UTC, oshyun00 commented on src/main/java/controller/RacingController.java
> +    }
메서드를 분리하였습니다. try-catch 문을 분리하는 방식을 사용하였는데요, 이 과정에서 제대로된 값이 입력되지 않으면 null 값을 주고받는 형태가 되었습니다.
분리한 메서드에서 null값을 받는 곳에서 null 체크를 하고 있어서 기대한대로 동작은하지만 과연 적절한 방식인건지, 혹은 depth를 줄일 수 있는 더 좋은 방법은 없을지 궁금증이 생겼습니다.

고민 1. Null 대신 Optional 리턴하기: 자료를 찾다보니 Optional은 null이 아니면 값을 나타내고 null일 경우 값이 없음을 나타내는 래퍼 클래스라서 null 대신 Optional을 리턴하는 방식도 있다는 것을 알게 되었습니다. 다만 이번 경우 null 대신 Optional을 반환하게되면 관련된 코드 수정이 불가피하고 명시성이 개선되는게 맞는지도 의문이 생겨서, 필요한 기능 대비 비용이 많이 들어가는것처럼 느껴졌습니다.
고민 2. 올바른 입력이 들어올 때까지 계속해서 입력을 받는 반복문의 위치: 입력을 받는것, 받은내용을 바탕으로 객체를 생성하는것은 각각 view와 domain의 역할이라고 생각했습니다. 대신 그 과정이 올바르게 이루어질때까지 반복하는 것은 컨트롤러에서 제어해야하는 부분이라고 생각해서 컨트롤러에 repeatUntilSuccess() 메서드를 넣게 되었습니다.

혹시 관련해서 의견을 공유해주시면 제가 생각해보는데 많은 도움이 될 것 같습니다! 감사합니다.

2024-02-16 23:53 UTC, oshyun00 commented on src/main/java/model/Car.java
> +    private static void validate(String name) {
Cars의 validate()가 static 으로 선언되어 있어 해당 구조와 통일성을 맞추고자 static을 붙였었는데요. 실질적으로 Car의 validate()는 생성자에서만 사용하고 있어 static이 꼭 필요하지는 않았던것같습니다. static을 무분별하게 사용할 경우 메모리 부족현상이 생기거나 캡슐화 원칙을 위배할 수 있다는 점 등을 고려할 때 상황에 따라 적절하게 static을 사용해야겠다는 생각이 들었습니다.

2024-02-17 07:04 UTC, andole98 requested changes
안녕하세요 엘라 두번째 리뷰네요.

몇가지 코멘트 내용중에 반영되지 않은것 같은 부분이 있어 조금더 자세하게 남겼어요.

전체적으로 static 메서드가 많네요. static 메서드의 의도 or 필요에 대해 질문 남겼었는데, 그에 대해 제가 납득할만한 이유는 없는것 같아요.

다음 리뷰요청하실땐 static method 없이 구현해보세요~

2024-02-17 07:04 UTC, andole98 commented on src/test/java/model/CarTest.java
> +        assertThat(car.getClass()).isEqualTo(Car.class);
그럼 아래 예외 케이스를 검증하고 있으니 이 테스트는 없어도 되겠네요~

2024-02-17 07:04 UTC, andole98 commented on src/test/java/model/CarTest.java
> +        assertThat(CarState.create(car).forwardCount()).isEqualTo(forwardCount);
CarTest에서 CarState를 검증하고 있네요 😢 
Car로는 테스트할수 없을까요~?

2024-02-17 07:04 UTC, andole98 commented on src/main/java/controller/RacingController.java
> +    }
null이나 optional 모두 조금은 비효율적으로 느껴지네요. `repeatUntilSuccess` 라는 메서드는 역할이 무엇인가요? while, try/catch를 동시에 해야 하나요?

메서드 분리에 대해 조금더 고민해보시면 좋겠네요.

반복문 등 제어로직의 역할에 대해서는 다음 주제인 mvc 패턴을 학습하면서 고민해보시면 좋을것 같아요.

2024-02-17 07:04 UTC, andole98 commented on src/main/java/model/dto/CarState.java
> +    public static CarState create(Car car) {
static 메서드가 필요한가요??

```java
public CarState(Car car) {
    this(car.getName(), car.getForwardCount());
}
```

이렇게 하면 안되나요? static 메서드는 왜 필요한걸까요? 생성자로 객체를 만드는 방법과 static factory 메서드로 객체를 만드는 방법은 무엇이 다른가요?

2024-02-17 07:04 UTC, andole98 commented on src/main/java/model/Car.java
> +    private static void validate(String name) {
혹시 코멘트만 남기고 잊으신건 아니겠지요..?

static 이 필요한 적당한 이유가 없다면 static 메서드 없이 구현해보세요.

2024-02-17 09:54 UTC, oshyun00 commented on src/test/java/model/CarTest.java
> +        assertThat(car.getClass()).isEqualTo(Car.class);
수정한 방식도 결국 아래 예외 검증과 중복되는 역할을 하는 코드가 되는군요! 해당 부분 제거하였습니다.

2024-02-17 09:56 UTC, oshyun00 commented on src/main/java/controller/RacingController.java
> +    }
repeatUntilSuccess의 역할, 목적은 정확한 값을 받아올때까지 동작을 반복하는 것이었습니다. 메서드를 분리하면서 null값을 주고받는 방식 대신 재귀 방식으로 수정해보았습니다. 메서드 분리나 제어로직 부분은 제가 아직 부족한 부분이 많아 더 학습하고 고민해보고자 합니다!

2024-02-17 09:56 UTC, oshyun00 commented on src/test/java/model/CarTest.java
> +        assertThat(CarState.create(car).forwardCount()).isEqualTo(forwardCount);
car에서 바로 상태를 확인하는것으로 수정하였습니다.

2024-02-17 09:57 UTC, oshyun00 commented on src/main/java/model/dto/CarState.java
> +    public static CarState create(Car car) {
CarState를 생성하는 부분에서는 꼭 필요한 부분은 아니었던것같습니다! 해당 부분은 수정하였습니다.
생성자를 통한 방식은 클래스 내부 구조를 알고있을 때 객체를 생성할 수 있고, 반면 static factory 메서드는 메서드 이름을 통해 객체의 생성 방법을 알 수 있는 것이라고 생각했습니다.
그래서 Car나 Cars에서는 from Name(), fromNames()와 같이 static factory 메서드를 사용함으로써 가독성, 활용도 측면에서 이점이 있다고 생각해 적용하였습니다.

2024-02-17 09:58 UTC, oshyun00 commented on src/main/java/model/Car.java
> +    private static void validate(String name) {
다른 부분과 마찬가지로 static을 무분별하게 사용하고 있었다는 생각이 들었습니다. 앞으로 코드를 작성할 때 생각해볼 수 있는 부분이었습니다. 감사합니다!

2024-02-17 13:30 UTC, andole98 commented on src/main/java/model/dto/CarState.java
> +    public static CarState create(Car car) {
> static factory 메서드를 사용함으로써 가독성, 활용도 측면에서 이점이 있다고 생각

```java
new Car("name", forwardCound);
```
이것으로도 충분히 표현이 가능한것 같아요. Car는 생성자 파라미터가 2개로 생성하기 어렵지 않아요. 

생성자로 충분히 처리할 수 있는데도 static factory method를 쓰는것이 습관화되면, 생성자를 적절치 못하게 만들어놓고 static factory method 하나 쓱 만들어놓고 퉁 치는 경우도 생길것 같네요.

파라미터가 10개 넘어가는 등 생성자가 더러워지는 이유는 객체설계가 잘못되었기 때문입니다. 객체설계가 잘못됨을 생성자를 보면서 스스로 느낄수 있어야 하는데 static factory method들을 남발하면서 `괜찮지 않나? 이펙티브 자바에서도 나오는데` 로 잘못된 생각을 할까봐 우려스럽네요.

static factory 메서드의 named 이점은 언제 좋을지 알아보시면 좋을것 같네요.

2024-02-17 13:34 UTC, andole98 approved these changes
마지막까지 수고하셨어요 👏 아마 처음 코드리뷰 & 코드에 대한 피드백을 받아보셨을 것 같네요.

저를 포함해 모든 리뷰어가 하는 말은 정답이 아닙니다.(그 누구라도 말이죠) 

리뷰어 피드백이라서 수정하기 보다는, 

자신의 설계와 구현과 코드를 되짚어보고 본인이 추구하는 or 생각하는 바대로 설득하고 발전시켜 나갔으면 좋겠네요. 물론 피드백 내용이 더 나은 부분이 있다면 잘 받아들이는것도 중요합니다.

그 와중에 서로 생각이 다른 부분이 있으면 적절한 논쟁도 학습에 도움이 된다고 생각해요. 

수고 많으셨습니다 다음 미션도 화이팅하세요~

2024-02-17 13:34 UTC, merged