[1단계 - 자동차 경주 구현] 제리(김민정) 미션 제출합니다.
woowacourse/java-racingcar pull request #692
Opened 2024-02-15 07:51 UTC by mzeong

2024-02-15 21:54 UTC, pkeugine requested changes
안녕하세요 제리!
미션 깔끔하게 잘 구현해주셨어요
몇 가지 리뷰 남겨보았으니 한 번 리팩토링 해보고, 대화 나눠보면 좋을 것 같아요!

남겨주신 질문에 대한 답변도 코멘트에 남겨봤어요. 만약 궁금한 점이나 막히는 부분이 생긴다면 언제든지 DM 보내주세요!

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +}
테스트 클래스 [파일마다 새로운 line 을 넣어주는게 어떨까요?](https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b)
현재 PR 에서 변경점을 보면 아래와 같이 빨간 아이콘이 뜨거든요 : 
![image](https://github.com/woowacourse/java-racingcar/assets/48251668/6c0f30f1-2c25-4d88-8168-8ddb2c0ac049)

intelliJ 설정에서 개발자가 변경하는 파일마다 자동으로 파일 마지막에 new line 을 넣어주는 기능이 있어요. 이를 사용해보셔도 좋아요!

new line 이 사용되는 이유가 궁금하다면? [[클릭!](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)]
intelliJ 에서 파일이 저장될 때 마지막 new line 을 넣어주는 방법이 궁금하다면? [[클릭!](https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file)]

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    private int position;
```suggestion
    public static final int MAX_NAME_LENGTH = 5;
    public static final int MINIMUM_FORWARD_NUMBER = 4;
    
    private final String name;
    private int position;
```
엄격하게 정해진 컨벤션은 아니지만, static 한 상수와 변수를 분리시켜 놓으면 저는 더 눈에 잘 들어오더라구요!

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    }
이번에 페어와 함께 개발하시면서 서로 정한 컨벤션이 있을까요?
클래스의 메서드 순서도 컨벤션이 될 수 있어요 :
생성자, 부생성자, public 메서드, private 메서드, getter, toString, compareTo, equals, hashCode 등

이 순서 컨벤션을 맞추면 코드를 유지보수할 때 굉장히 큰 도움이 되더라구요!

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
메서드 분리를 하시면서 static 키워드가 메서드 시그니처에 추가된 것 같아요!
intelliJ 에서 메서드 분리하면 static 키워드를 붙일지 말지 정하는 체크박스를 눌러서 이 기능을 사용하지 않을 수 있어요

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
앞서 메서드 순서 얘기를 했었는데,
이 코드가 적절한 예시라고 생각해요

```java
    public Cars(String rawNames) {
        List<String> carNames = parseNames(rawNames); // 1
        validate(carNames); // 2
        this.cars = carNames.stream().map(Car::new).collect(Collectors.toList());
    }
```
위의 메서드에서 두 개의 private 메서드가 호출됐는데 (parseNames 와 validate),
이왕이면 처음 호출되는 메서드가 바로 밑에 있으면 읽기 좋은 구조가 되지 않을까 생각해요.
그리고 그 밑에 validate 를 두는거죠. 이러면 자연스럽게 아래로 읽으면서 해당 메서드를 발견할 수 있을거에요

이 외에도 public 메서드를 가장 먼저 두고, 나머지 private 메서드를 나열하는 방법도 있는데요
제리가 앞으로 개발하시면서 팀원들과 함께 무엇이 더 편한지 대화해보고 컨벤션으로 지정하면 정말 좋을 것 같아요!

이왕이면 비즈니스 로직이 잘 보이게 위로!
그 중에서는 나타나는 순서 또는 public 유무!
equals 와 같은 요소는 아래로!

코드 짜다보면 나중에는 무의식적으로 이렇게 만들고 있는 스스로를 발견할거에요 :)

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/view/InputView.java
> +    private final Scanner scanner = new Scanner(System.in);
```suggestion
    private static final String ENTER_TRYCOUNT = "시도할 횟수는 몇회인가요?";
    private static final String ENTER_NAMES = "경주할 자동차 이름을 입력하세요(이름을 쉼표(,)를 기준으로 구분).";
    
    private final Scanner scanner = new Scanner(System.in);
```
여기도 한 줄 띄워주는 것도 괜찮겠네요!

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    public static final int MINIMUM_FORWARD_NUMBER = 4;
저는 개인적으로 혼자 개발을 할 때도, 팀 내에서 개발을 할 때에도 '통일성'이 중요한 요소라고 생각해요
유지보수하기 편해지거든요

그런 의미에서 MAX, MINIMUM 이라는 표현을 줄임말, 줄이지 않은 표현 둘 중 하나로 통일해보는건 어떨까요?
뭔가 빌드업 했던 것 치고는 소소해 보이는 변경 요청이죠 😂 
MAX, MIN 말고 앞으로 다른 줄임말도 일관성 있게 사용해보면 좋을 것 같아요!

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/TryCountTest.java
> +    @DisplayName("정상적으로 TryCount를 생성합니다.")
통일성 이야기 두번째,
클래스 선언과 메서드 / 필드 사이의 공백

이런 것들은 intelliJ 의 자동 포매팅 기능을 활용하실 수 있어요
제리가 원하는 코드 스타일을 설정에서 지정해준 뒤,
option + command + L 을 누르면 intelliJ 가 알아서 그것에 맞게 코드를 포맷팅 해줘서 꽤 유용해요!

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/TryCountTest.java
> +    @DisplayName("시도 횟수가 0 이하의 숫자인 경우 예외")
별거 아닌 것 같아보여도 저는 테스트 이름을 그 의도에 맞게 짓는게 정말 중요하다고 생각해요
제리가 작성해주신 테스트는 모두 정확한 이름을 가지고 있어요 👍👍👍

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/util/RandomGenerator.java
> +    static public int generate() {
자바는 말이 많은 언어라 static, public, final... 뭐가 많이 붙어요
그래서 우테코를 포함해서 많은 개발자들이 흔히 사용하는 google style convention 이 있는데요,
[거기서 이 키워드의 순서를 정하고 그대로 사용하자는 약속을 하고 있어요
](https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers)

그걸 적용해본다면 다음과 같이 바뀌겠네요!
```suggestion
    public static int generate() {
```
컨벤션을 한 번 숙지해보시고, 앞으로 이렇게 작성해보길 권장해요

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/view/InputView.java
> +            throw new IllegalArgumentException();
예외를 던질 때 메시지를 포함하면 디버깅이나 그 예외 발생 상황을 기록할 때 훨씬 편하답니다!
한 번 넣어볼까요?

InputView 뿐만 아니라 Car 와 같은 domain 에서 발생하는 예외에도 넣어보죠 :)

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
일급컬렉션을 이번 미션부터 적용한게 대단한거 같아요 👍 
여러 Car 객체를 하나로 묶어서 관리하면서 관련 로직을 한 곳에 모을 수 있죠!

제리가 남겨주셨던 질문 중, 이 부분과 관련 있는 질문이 하나 있어요:

> ‘주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다’라는 요구사항에 대해 어떻게 테스트 코드를 작성해야 할지 고민이 됩니다. 어떤 식으로 코드를 작성하면 좋을까요?

랜덤 요소가 포함된 로직은 테스트 코드를 작성하기 정말 힘들어요
그래서 그런지 제리가 작성해주신 테스트를 보면 Car 객체는 전진 관련 테스트가 있는데 Cars 는 아직 없죠

이 로직을 잘 보면 왜인지 감이 잡힐 것 같은데요,
Car 객체는 랜덤한 요소를 외부에서 파라미터로 전달 받고 있죠?
그래서 Car 는 숫자가 랜덤인지, 늘 일정한 값인지...
전혀 상관하지 않고 특정 수 이상이면 전진을 해요
이 구조는 테스트할 때 우리가 원하는 값을 Car 에 넣어줄 수 있으니 테스트하기 좋은 구조라고 볼 수 있어요.

하지만 Cars 는 RandomGenerator 에 의존하고 있어요 (즉, 내부 로직에서 RandomGenerator 를 사용하고 있어요)
그래서 테스트할 때, 우리가 원하는 상황을 만들지 못해요. `proceedRound` 를 실행하고 움직이길 바라는 수 밖에 없는데,
**이는 테스트하기 좋은 구조라고 볼 수 없겠죠**

Car 의 구조를 정말 잘 만드셨으니 Cars 도 비슷하게 만들어볼 수 있지 않을까요?
만약 시도해보시다가 막히면 제게 꼭 DM 이나 코멘트 달아주세요!!

2024-02-15 21:54 UTC, pkeugine commented on src/main/java/racing/view/InputView.java
> +    }
제 생각엔 제리의 InputView, OutputView 구현이 정말 깔끔하고 현 요구사항에 적합하다고 생각해요
남겨주신 질문:

> 문구를 출력하기 위해 InputView 에 넣을지, OutputView 에 넣을지 고민이 되었는데, 어떤 것이 좋은 방법인지 모르겠습니다.

그렇다면 제리는 어떠한 이유로 이를 InputView 에 넣으셨나요?
제가 생각하는 '저에게 맞는' 방식이 있긴한데, 먼저 제리의 생각을 들어보고 싶어요 :)

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +    @DisplayName("랜덤값이 4이상이면 자동차를 전진합니다")
4 이상의 값이 들어오는 테스트라 4 와 9 를 넣은신 점 좋네요 👍

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +        assertEquals(1, position);
이렇게도 써볼 수 있어요. 수정할 필요는 없습니다!
```suggestion
        assertThat(position).isEqualTo(1);
```
`assertEquals()` 와 `assertThat().isEqualTo()`, assertJ 라이브러리에 대해 한 번 알아보시고 사용해보시는 것도 추천해요!
assertJ 는 특히나 쉽고 나름 유쾌한 공식문서를 가지고 있어서, 처음으로 공식문서를 읽어보기 좋은 입문용 공식문서입니다 :)

2024-02-15 21:54 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +    }
> 출력 형태를 안다는 가정 하에 작성된 코드라서 좋은 코드가 아니라고 판단됩니다. 그러나 아래 방법을 사용하지 않고 테스트를 하기 위해 getPosition 함수를 만드는 것도 좋은 선택이 아닌 것 같습니다.

좋은 포인트입니다. 지금 구조상 toString() 이 console 출력을 염두에 두고 만들어졌는데, 이걸 테스트에서 활용하고 있네요
제 생각에도 좋은 테스트 방식은 아니에요.

그런데 'getPosition' 함수를 만드는 것이 좋은 선택이 아니라면, 저 역시도 어떻게 position 값을 가지고 와서 검증할지 막막할 것 같아요 😂 그래서 저는 이런 용도로 getter 를 사용하는건 문제되지 않는다고 생각해요

하지만 그게 '테스트를 위한 프로덕션 코드를 작성하겠다'는 말은 아니에요.
getter 를 지양한다기보단, 테스트를 위한 코드는 최대한 지양해야한다고 생각하거든요

그런데 position 을 꺼내오는 getter 의 경우, 자동차 경주 프로그램에서도 분명 사용할거라 저라면 만들어놓고 테스트에서도 사용할거에요!

2024-02-16 15:30 UTC, mzeong commented on src/test/java/racing/domain/CarTest.java
> +}
안녕하세요 피케이! 
자세하게 피드백을 남겨주셔서 정말 감사해요! 고민해서 수정사항들을 반영해보았습니다

제가 아직 intelliJ 사용이 익숙치 않은데 여러 커스텀 설정 팁을 알려주신 덕분에 조금 더 intelliJ와 친해진 것 같아요. 감사합니다

2024-02-16 15:37 UTC, mzeong commented on src/main/java/racing/domain/Car.java
> +    }
리뷰를 받고 페어와 컨벤션에 대해서도 함께 고민해봤다면 좋았겠다는 생각이 들었어요! 
피케이의 조언대로 코드들을 다듬고 나니 이전보다 다른 개발자들이 보기 수월한 코드가 된 것 같아요
앞으로 일관되고 보편적인 코드 스타일을 갖춰보도록 하겠습니다! 🙇‍♀️

2024-02-16 15:40 UTC, mzeong commented on src/main/java/racing/view/InputView.java
> +            throw new IllegalArgumentException();
덕분에 예외에 메세지를 포함했을 때의 이점을 알게 되었어요! 감사합니다

2024-02-16 15:46 UTC, mzeong commented on src/test/java/racing/domain/CarTest.java
> +        assertEquals(1, position);
피케이의 리뷰를 받고 의식 없이 AssertJ와 JUnit을 혼용해서 썼다는 것을 알게 되었어요 😅
해당 코드와 함께 다른 테스트 코드에도 AssertJ를 사용해보았습니다

AssertJ 공식 문서도 꼭 읽어볼게요! 추천해주셔서 감사합니다

2024-02-16 16:04 UTC, mzeong commented on src/main/java/racing/view/InputView.java
> +    }
이 부분은 저와 페어의 의견이 갈렸던 부분이라 질문을 남겨보았는데요!

저는 문구를 출력하는 별도의 메서드를 만들게 되면, 두 메서드를 연달아 호출해야 한다는 것을 인지하고 있어야 하며 호출도 두 번 해야 하는데
inputView에서 입력을 받기 전에 문구를 출력하면 이러한 번거로움을 해결할 수 있다고 보았어요
저는 보통 컨트롤러로부터 데이터를 전달받아 출력하는 경우에 outputView를 사용하고 있어요
페어가 inputView에서 `System.out.printIn()`을 사용하는 것에 대해 찜찜하게 생각했는데, 저도 의식하고 보니 고민이 되었어요

피케이의 기준이 궁금해요!

2024-02-16 16:15 UTC, mzeong commented on src/test/java/racing/domain/CarTest.java
> +    }
테스트 코드를 작성해두고 이건 아닌 것 같아서😅 고민이 많이 되었던 부분인데 피케이의 피드백을 듣고 깔끔하게 수정할 수 있었습니다 감사해요!

리뷰를 읽으면서 한 가지 더 질문드리고 싶은 게 생겼는데요! 피케이는 출력을 위해 toString()과 getter 중 어떤 걸 선호하시나요?

2024-02-16 16:25 UTC, mzeong commented on src/main/java/racing/domain/Cars.java
> +    }
Cars가 RandomGenerator에 의존하고 있는 문제를 해결하기 위해 인터페이스를 사용해보았습니다
MovableNumberGenerator, ImmovableNumberGenerator로 원하는 상황을 만들어 테스트 코드를 테스트 코드를 작성할 수 있게 되었어요
어떤가요?

2024-02-17 10:49 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +    }
이동하지 않는 것까지 꼼꼼하게 테스트 👍

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    public static final String POSITION_MARKER = "-";
사용되는 곳이 Car 클래스밖에 없는데, public 으로 둘 필요가 있을까요?

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    public static final int MIN_FORWARD_CONDITION = 4;
제리가 인터페이스와 구현체를 추가하셔서, 이왕 하신 김에 더 가보자는 생각으로 리뷰 남겨봅니다 💪 

저는 상수화하는 매직넘버는 최대한 적합한 위치에 두고, private 으로 닫는게 좋다고 생각해요
물론 이걸로 하루종일 고민하는건 안 좋으니 public 으로 열어두어도 되는데,
여기서는 충분히 private 으로 둘 수 있을 것 같아요.

MIN_FORWARD_CONDITION 도 사용처가 Car 보다 NumberGenerator 구현체쪽에 더 많아요.
그렇다면 이 상수가 이 곳에 있는 것이 맞을지,
아니면 더 나아가 이 구조가 적합한지 다시 고민해보는 것도 좋을 것 같아요

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    }
생성자가 여러개 있다면 다음과 같이 관리해볼 수도 있어요.
```suggestion
    public Car(String name) {
        this(name, 0);
    }
```

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    Car(String name, int position) {
Cars 에서만 쓰이니 접근제한자를 package private 으로 두신 점 좋네요 👍 

제리는 생성자로 객체 생성하는 것을 테스트하시던데,
이러면 테스트에서는 이 생성자를 못 사용하겠군요 🤔

2024-02-17 10:49 UTC, pkeugine commented on src/test/java/racing/domain/CarsTest.java
> +                .extracting("name").containsExactly(winner.getName());
와 고급 기술을 사용하시네요 👍

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
좋네요! 인터페이스를 추가하고, 세 개의 다른 구현체를 만드셨군요 👍 
확실히 인터페이스를 만들면 무작위적인 행위를 개발자 마음대로 변경하여 테스트하기가 더 쉬워지죠

그런데 생각해볼 점이 있어요.
구현체 세 개가 어디서 사용되는지 보면 : 
- RandomNumberGenerator : 프로덕션 코드에서 로직으로 사용. 👍 
- ImmovableNumberGenerator : 사용처 없음 🤔 
- MovableNumberGenerator : 테스트에서만 사용하지만 프로덕션 코드와 같은 패키지에 있음 🤔 

테스트의 편의성을 챙기니 이번에는 다른 의문점이 드네요
- 과연 사용하지 않는 코드를 미리 만들어 놓는게 좋을까?
- "테스트하기 좋은 구조"로 로직을 작성하는 것은 좋은데, "테스트를 위한" 코드를 프로덕션 코드에 추가하는 것이 좋을까?

이미 말투에서 이 두 질문에 대한 제 생각이 드러난 것 같지만 😂
좋다면 왜 좋은지, 안 좋다면 왜 안 좋은지 한 번 생각해보시면 좋을 것 같아요!

2024-02-17 10:49 UTC, pkeugine commented on src/main/java/racing/view/InputView.java
> +    }
제리와 제 생각이 완전 일치해요!
output 행위더라도, input 행위와 매번 같이 사용되는 거라면 그 로직이 함께 있어야한다고 생각해요
어차피 InputView, OutputView 는 터미널용으로 만든거라, 따로 분리해서 다른 곳에서 사용하지도 않을거니까요

하필 이름이 "Input", "Output" 으로 구분돼서 이런 고민이 생기는 것 같은데요,
**응집도를 높이고, 결합도를 줄이겠다는 관점**으로 보면
InputView 에서 입력받는 값의 정보를 보여주는 것은 그리 어색하지 않다고 생각합니다 :)

2024-02-17 10:49 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +    }
getter 를 선호해요
getter 의 가장 주된 사용처가 데이터를 출력하기 위해 꺼낼 때라고도 생각하고요!
toString 은 디버깅, 로깅 용도로 사용해요 :)

2024-02-17 10:53 UTC, pkeugine requested changes
피드백 정말 잘 반영해주셨네요 👍 
리뷰랑 질문에 대한 답변 추가로 몇 개 달았는데,
이 부분 한 번 고민해보고 수정을 조금 더 해보죠!

2024-02-17 14:33 UTC, mzeong commented on src/main/java/racing/view/InputView.java
> +    }
응집도를 높이고, 결합도를 줄이겠다는 관점으로 보라는 피케이의 설명이 정말 명쾌해요! 감사합니다!

2024-02-17 16:14 UTC, mzeong commented on src/test/java/racing/domain/CarTest.java
> +    }
그렇군요!! 저는 항상 출력 형식에 맞춰 toString을 작성하면서 이 코드가 뷰에 있는 편이 나중에 유지보수하기 편하지 않나 라는 생각이 들었는데 getter를 사용하지 않겠다는 목표를 달성하기 위해 toString을 계속 사용해왔어요

그렇지만 toString만을 쓰다보면 이번처럼 출력에 의존하는 테스트 코드를 만들게 되기도 하고, getter를 무조건 지양하는 것이 큰 의미가 없다고 느껴져서 이번 기회에 getter를 데이터 출력과 테스트에 사용하는 방향으로 코드를 수정해보았습니다

2024-02-17 19:18 UTC, mzeong commented on src/main/java/racing/domain/Car.java
> +    public static final int MIN_FORWARD_CONDITION = 4;
> MIN_FORWARD_CONDITION 도 사용처가 Car 보다 NumberGenerator 구현체쪽에 더 많아요. 그렇다면 이 상수가 이 곳에 있는 것이 맞을지, 아니면 더 나아가 이 구조가 적합한지 다시 고민해보는 것도 좋을 것 같아요

피케이의 이 힌트가 도움이 많이 되었어요! 감사합니다

2024-02-17 19:22 UTC, mzeong commented on src/main/java/racing/domain/Cars.java
> +    }
피케이의 지적에 공감해요! 테스트에 너무 집중한 나머지 주객전도가 되어버린 것 같아요 😥
마찬가지로 리뷰를 남겨주었던 default 생성자도 다시 보니 테스트를 위한 코드로 보여 함께 수정하였어요!

2024-02-18 13:45 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +    }
> getter 를 '무조건' 지양하는 것이 큰 의미가 없다

💯💯💯💯💯💯💯

2024-02-18 14:16 UTC, pkeugine approved these changes
안녕하세요 제리!
정말 고생 많으셨어요
제리가 많은 것들을 적용해주셔서 저도 신나게 리뷰 남겼네요 😅

step 1 은 마무리하고, 이제 step 2 로 넘어가보죠
이번에 제가 남긴 코멘트는 step 2 에 반영하시면 제가 거기서 다 확인해볼게요
조금만 더 파이팅해보죠!

이번에도 궁금한 점이나 이야기할 요소가 있다면 언제든지 DM 주세요 :)

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/controller/Parser.java
> +}
필드가 없는 클래스는 static 한 유틸 클래스와 크게 다를게 없어요
특히 `Parser` 같은 경우는 로직이 단 한 줄이라, 굳이 분리하지 않아도 될 것 같네요!

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/domain/Car.java
> +    }
저만의 소소한 방식인데, 
```suggestion
    public boolean isSame(Car other) {
        return this.position == other.position;
    }
```
이렇게 쓰면 this & other 가 반대되는 느낌이라 뭔가 보기 좋더라구요 :)
그냥 TMI...

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
중복 검사를 할 때 이전에는 stream.distinct 를 사용하셨는데, 이 로직으로 변경하신 이유가 있나요?

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
```suggestion
    public List<Car> findCarsWithSamePosition(Car target) {
        return cars.stream().filter(car -> car.isSame(target)).toList();
    }
```

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    }
테스트 하기 위해 메서드를 public 으로 여는 행위는 지양하는걸 추천합니다 :)

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/domain/Cars.java
> +    public List<Car> findCarsWithSamePosition(Car target) {
테스트 하기 위해 메서드를 public 으로 여는 행위는 지양하는걸 추천합니다 2번째!

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/util/MovableStrategy.java
> +}
이전 피드백 정말 잘 반영해주셨어요 👍

마지막 생각거리 : 
"구현체가 하나만 있는 인터페이스는 굳이 인터페이스화 할 필요가 있을까?"
vs
"유연하고 확장 가능한 구조를 위해 구현체가 하나만 있더라도 인터페이스가 필요해"

전략 패턴이라는 방식을 잠시 잊고 고민해봐도 좋을 것 같아요

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/util/RandomMoveStrategy.java
> +    private static final int MIN_FORWARD_CONDITION = 4;
정말 고생하셨어요 제리
Random 과 관련된 상수 & 로직이 한 곳에 모이게 되었네요!! 🥳 🥳 🥳 🥳

2024-02-18 14:16 UTC, pkeugine commented on src/main/java/racing/view/InputView.java
> +    private static final String ENTER_NAMES = "경주할 자동차 이름을 입력하세요(이름을 쉼표(,)를 기준으로 구분).";
step 1 에서 저희는 예외 메시지와 출력을 enum 으로 한 곳에서 관리하는 방식에 대해 이야기 했었죠?

이제 step 2 를 진행하실텐데,
이번엔 "메시지를 상수로 관리했을 때 얻을 수 있는 이점" 에 대해 한 번 고민해보시면 좋을 것 같아요 :)

2024-02-18 14:16 UTC, pkeugine commented on src/test/java/racing/domain/CarTest.java
> +class CarTest {
테스트 진짜 꼼꼼하게 진행해주셨네요 👍 
테스트 이름도 디테일하고 비슷한 구조로 만드셨구요!

테스트 꼼꼼하게 만드는 것은 좋지만, 앞서 말했던 내용 중
"테스트 하기 위해 프로덕션 코드를 변경하는 행위", 특히 private -> public 으로 바꾸는 것은 지양해주세요!

2024-02-18 14:16 UTC, merged

2024-02-18 14:27 UTC, pkeugine commented
아 맞다 제리
앞으로 PR 올리실 때, 브랜치가 step1, step2 이런 식으로 해당 단계의 브랜치인지 꼭 확인해주세요!
이 PR 보니까 브랜치 명이 제리의 username 으로 되어있더라구요