[레벨1 - 자동차 경주] BE_ 도비 페어 프로그래밍 제출합니다.
woowacourse/java-racingcar pull request #696
Opened 2024-02-15 07:54 UTC by Dobby-Kim

## 자동차 경주 게임 프로젝트 상세 설명

### 프로젝트 개요
이 프로젝트는 사용자가 입력한 자동차 이름과 시도 횟수에 따라 진행되는 콘솔 기반 자동차 경주 게임입니다. 각 자동차는 랜덤하게 생성된 숫자를 기반으로 전진하거나 멈추며, 최종적으로 가장 멀리 이동한 자동차가 우승합니다.

### 핵심 구성요소 및 기능
- **Car.java**: `Car` 클래스는 자동차의 이름과 현재 위치를 관리합니다. 자동차는 랜덤 숫자에 따라 전진할 수 있습니다.
- **NumberGenerator.java & RandomNumberGenerator.java**: 이 인터페이스와 구현 클래스는 자동차의 전진 여부를 결정하는 데 사용되는 랜덤 숫자를 생성합니다.
- **Referee.java**: 모든 경주가 끝난 후, `Referee` 클래스는 각 자동차의 위치를 평가하여 우승자를 결정합니다.
- **Controller.java**: 게임의 진행을 총괄하는 클래스입니다. 사용자 입력을 받고, 경주를 진행하며, 결과를 출력합니다.
- **InputView.java & OutputView.java**: 사용자로부터의 입력을 처리하고(자동차 이름과 시도 횟수), 경주 진행 상황 및 결과를 사용자에게 출력합니다.
- **InputValidator.java**: 사용자 입력(자동차 이름과 시도 횟수)의 유효성을 검사합니다. 유효하지 않은 입력에 대해서는 예외를 발생시킵니다.

### 게임 진행 방식
1. **사용자 입력 처리**: 게임 시작 시, 사용자는 참여할 자동차의 이름과 총 시도 횟수를 입력합니다.
2. **경주 진행**: 입력된 시도 횟수에 따라, 각 자동차는 랜덤으로 생성된 숫자에 기반하여 전진하거나 멈춥니다.
3. **결과 발표**: 모든 시도가 완료된 후, 가장 멀리 이동한 자동차(들)가 우승자로 선언되고, 결과가 출력됩니다.

2024-02-15 16:10 UTC, syoun602 requested changes
안녕하세요 도비 👋
드디어 첫 미션이네요! 잘 작성된 기능목록 덕분에 확인하기가 수월했습니다! 👍
몇 가지 의견 남겨두었으니 언제든 코멘트나 DM을 활용해주세요. 


간단한 코멘트 남겼으니 궁금하신게 있다면 언제든 코멘튼나 DM을 활용해주세요!

2024-02-15 16:10 UTC, syoun602 commented on README.md
> +## 1. 기능 요구사항
꼼꼼한 기능 목록 작성 👍

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/Main.java
> +        controller.run();
`Controller`라는 단어만 보고 어떤 동작을 할지 모르겠네요! 조금 더 의미있는 단어를 사용해보는건 어떨까요?

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/controller/Controller.java
> +    private final Referee referee = new Referee();
인스턴스 변수의 수가 많네요! 
객체지향 생활체조 원칙에는 '2개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다' 라는 말이 있어요!
지금 구조에서 극단적으로 2개로 줄이라는 뜻은 아닙니다~
왜 이런 원칙이 있을 지에 대해 한번 생각해볼까요?

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/controller/Controller.java
> +        cars = new ArrayList<>();
단순히 일회성으로 진행될 게임이라면 상단의 인스턴스 변수에도 초기화해도 되지 않을까요?
또한 현재 클래스가 너무 비대한 것 같아요! 😢
입출력에 대한 책임부터 검증, 움직임 등 많은 역할을 하고 있는데, 각각의 책임에 맞게 분리해보아요.

`for(Car car : cars)`가 이곳 이외에도 여러 군데서 반복되고 있는데 어떻게 고쳐볼 수 있을까요?
한 번에 너무 많이 바꾸기보다는 하나씩 분리해보면 좋아요! 
`hint: 일급컬렉션`

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/controller/Controller.java
> +        for(String carName : carNames){
```suggestion
        for(String carName : carNames) {
```
다른 파일들도 그렇고 전반적으로 formatting 적용이 필요한 곳이 보이네요.
IntelliJ에서 기본적으로 자동 정렬을 제공해줍니다! macOS: `Cmd + Alt + L`, windows: `Ctrl + Alt + L`
커밋 전에 한번씩 사용해보는 습관을 들여보아요!
[save마다 정렬](https://hianna.tistory.com/791)이 되도록 설정할 수도 있습니다!

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +        return random >= 4;
매직 넘버를 제거해봅시다! 
의미있는 상수명은 코드를 읽는 사람에게 숫자가 아닌 이름으로 그 의미를 이해시킬 수 있습나다 😊

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/model/Referee.java
> +
불필요한 공백으로 보입니다 😢
공백 라인은 문맥을 분리하는 부분에 사용하는 것이 좋습니다!

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/model/Referee.java
> +    public List<String> generateWinners(List<Car> carList){
클래스를 `Referee`라고 지은 만큼 메서드명도 그에 맞게 변경해볼까요?
저라면 우승자를 '생성한다'보다는 '판단한다'로 작성해볼 것 같아요 😊

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/view/InputView.java
> +    final InputValidator inputValidator = new InputValidator();
인스턴스 변수를 이렇게 작성할 경우 기본적인 접근 제한자가 어떻게 될까요?
그리고 현재의 경우라면 어떤 문제가 발생할까요?

+) 객체지향 생활체조 규칙 `5. 줄여쓰지 않는다(축약 금지).`

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/view/InputView.java
> +    }
한번의 스트림으로도 할 수 있겠네요! `.`을 찍으면 인텔리제이에서 사용가능한 함수를 알려주니 한번 확인해봅시다 😊
```suggestion
        return Arrays.stream(initialInput.split(","))
                .map(String::trim)
                .toList();
    }
```

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/view/OutputView.java
> +    }
정적 메서드와 아닌 메서드가 섞여있는데 무슨 기준으로 나누신 걸까요?
또한, 메서드 순서에 신경써봅시다! 코드도 하나에 문서이므로 위에서 아래로 유기적으로 읽히도록 바꿔보아요.
[여기](https://engineerinsight.tistory.com/41)를 참고해봅시다!

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/view/UserMessage.java
> +public class UserMessage {
이렇게 메시지를 한 곳에 모아놓으면 어떤 장점이 있고 어떤 불편함이 있을까요?

2024-02-15 16:10 UTC, syoun602 commented on src/main/java/racingcar/view/validator/InputValidator.java
> +            throw new IllegalArgumentException();
예외 메시지를 작성해봅시다~! 현재의 경우 어디서 오류가 났는지 한 눈에 알아보기 쉽지 않을 것 같아요,

2024-02-15 16:10 UTC, syoun602 commented on src/test/java/racingcar/model/CarTest.java
> +}
[POSIX new line](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)에 대해 알아볼까요?
[인텔리제이 자동 개행 설정](https://kukim.tistory.com/100)을 추가해보아요

2024-02-15 16:10 UTC, syoun602 commented on src/test/java/racingcar/model/RefereeTest.java
> +
공백이 두개네요 👀

2024-02-15 16:10 UTC, syoun602 commented on src/test/java/racingcar/model/RefereeTest.java
> +    }
`CarTest`에서는 익명클래스로 작성하고 여기서는 직접 생성했네요!
이렇게되면 그냥 하나의 클래스로 추출해도 되지 않을까요?

2024-02-15 16:10 UTC, syoun602 commented on src/test/java/racingcar/model/RefereeTest.java
> +    Car car3;
접근 제한자가 없네요 👀

2024-02-15 16:10 UTC, syoun602 commented on src/test/java/racingcar/model/CarTest.java
> +class CarTest {
숫자 0 이나 9가 들어온다면 어떻게 되나요?
두 개의 테스트만으로는 자동차가 어떻게 움직일 지 확신할 수 없을 것 같아요.
경계값에 대한 테스트를 조금 추가해보는건 어떨까요?

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/controller/Controller.java
> +    private final Referee referee = new Referee();
controller가 전체적인 경주의 진행을 맡아서 해야된다고 생각하면서 코드를 작성했었습니다!
작성하고 나니, '전체적인 경주 안에서도 역할이 분배될 수 있었는데'라는 아쉬움이 들더라고요.. controller라는 하나의 클래스에 너무 많은 역할을 주려고 한 것 같습니다!

아마도 하나의 클래스가 너무 많은 역할을 가지게 되고, 하나의 클래스에 다른 인스턴스들이 줄줄이 달려있게 되면 해당 클래스의 의존이 높아져서 그런것 아닐까.. 하는 생각이 드네요!

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/controller/Controller.java
> +        cars = new ArrayList<>();
넵! 말씀해주신 것을 기반으로 일급컬렉션인 Cars를 만들어보겠습니다.
Controller에서 Car 객체들의 리스트를 직접 조작하는 대신 Cars 클래스를 통해 간접적으로 조작하도록 역할을 배분해보겠습니다!

또한, controller의 경주 진행 역할을 세분화해서 race라는 클래스를 따로 만들어보려고 합니다

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/model/Car.java
> +        return random >= 4;
여기서 질문이 하나 있습니다!
이렇게 매직넘버가 각각의 클래스에서 존재하는 경우가 많을텐데, 하나의 constant라는 클래스를 만들어서 이 모든 매직넘버들을 관리하는 것이 좋을까요, 아니면 각 클래스에 필드로 두는 것이 좋을까요?

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/view/InputView.java
> +    final InputValidator inputValidator = new InputValidator();
Java에서 클래스 내부에서 선언된 변수나 메소드에 접근 제한자를 명시하지 않으면, 그 멤버는 'package-private' 또는 'default' 접근 제한자를 갖게 됩니다!

어떤 문제가 발생할지 생각해보겠습니다! 근데 조금의 힌트를 얻을 수 있을까요ㅜㅜ

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/view/OutputView.java
> +    }
여러 클래스에서 두루 쓰이는 매서드를 static으로 선언했습니다!
정적 메서드가 아닌 메서드들은 controller에서만 사용되는 매서드들이라 static 사용을 지양해봤습니다..!!

리팩터링을 거치면서 추가한 메서드인데 메서드 순서에 신경을 못썼네요 신경써서 수정해보겠습니다!

2024-02-16 03:11 UTC, Dobby-Kim commented on src/main/java/racingcar/view/UserMessage.java
> +public class UserMessage {
출력되는 문구의 변경이 있을 때 수정이 용이할 것 같습니다!
불편함이라고 하면, 여러 메서드들에서 사용되는 메세지가 모여 있는 경우에 수정이 필요할 때 찾기가 불편할 수도 있다는 생각이 듭니다

2024-02-16 03:11 UTC, Dobby-Kim commented on src/test/java/racingcar/model/CarTest.java
> +class CarTest {
넵! 엣지케이스에 대해서 조금 더 생각해보도록 하겠습니다!

2024-02-16 12:26 UTC, syoun602 commented on src/main/java/racingcar/view/InputView.java
> +    final InputValidator inputValidator = new InputValidator();
현재와 같은 경우라면 같은 `view` 패키지 클래스에서 접근이 가능할 것 같아요.
`Scanner` 나 `InputValidator`는 `InputView`에 한해서만 사용할 것 같아서 말씀드렸습니다 !

곧 읽어보시겠지만, 이펙티브 자바에 `15. 클래스와 멤버의 접근 권한을 최소화하라`가 있습니다 😊

2024-02-16 12:33 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +        return random >= 4;
제 생각을 듣기 전에 도비가 직접 사용해보고 어떻게 느끼셨는 지 알려주실 수 있을까요?!
함께했던 페어나 크루들과 얘기해보면서 본인만의 코드 작성 기준을 하나씩 정리해보는 것도 중요합니다!
그게 또 우아한테크코스의 묘미가 아닐까요 😄

2024-02-18 08:51 UTC, syoun602 approved these changes
안녕하세요 도비 😄
리뷰 잘 반영해주신 것 확인했습니다!
1단계는 이만 머지하고 2단계에서 다시 뵙겠습니다.
몇 가지 고민해볼 부분들을 남겨두었는데 한번 고민해보시고 도비의 생각을 들려주세요.

상수 관리에 대한 답변은 도비가 충분히 고민해보고 내린 결론에 대한 의견을 들려주세요! 다음 리뷰때 제 생각을 공유해드릴게요!

+) 리뷰의 대댓글은 제가 빠르게 확인이 안되어서, 리뷰에 대한 의문이 있다면 편하게 DM 주세요!!! 
구현 후 궁금증은 코멘트에 남겨두시면 됩니다 😊
+) PR 브랜치를 살펴보면 `woowacourse:dobby <- dobby:step1`가 되어야 하는데, 현재는 아니네요! 다음 PR에서는 확인부탁드려요!

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/controller/RaceController.java
> +package racingcar.controller;
작성할 곳이 없어 여기에 남깁니다 😊

커밋에 대한 얘기를 먼저 드리고 싶은데요! 특별히 기능 뒤에 `(클래스명)`을 남기시는 이유가 있으실까요?
단순한 의견이니 도비가 원하시는 방향으로 (물론, 팀과 협의 하에) 작성하셔도 무관합니다.

다만, 커밋들을 확인해보니 커밋 그 자체로 돌아가는 코드가 아닌 특정 리팩토링을 전체적으로 진행 후 커밋할때만 각 파일마다 따로 올리신 것 같아서요 😢 커밋의 단위에 돌아가지 않는 코드를 올리는건 좋지 않습니다. 만약, 누군가가 버그를 찾기위해 커밋명을 읽고 해당 변경사항으로 돌아갔을 때 코드가 동작하지 않는다면 당황스럽지 않을까요? 
오히려 클래스명을 작성하려다보니 억지로 코드를 클래스로 쪼개서 작성하게 된 것일까봐 질문 드렸습니다.

저라면 클래스명을 작성하기보다는 무엇이 변경되었는지 충분히 녹여낼만한 메시지를 작성할 것 같아요. 이유는 다음과 같습니다.
1. 커밋 메시지가 너무 길어져 뒷 내용이 한 눈에 안들어온다
2. 또한, 클래스를 하나만 적었기 때문에 함께 변경된 다른 중요 정보가 은닉될 수 있다.
3. 반복적인 클래스명으로 인해 변경사항 추적이 어려워질 수 있다.

다만 제 개인적인 의견일 뿐이니 현재와 같이 작성하는 것도 충분히 합리적이라고 생각합니다! 도비가 어느 부분에 더 중점을 둘 것인지를 잘 생각해보고 결정하시면 될 것 같아요. 다만, 커밋 대상이 실행가능할 정도로 하는 것을 추천드립니다 😊

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/controller/RaceController.java
> +public class RaceController {
Controller라는 이름이 꼭 들어가야 하는 지에 대한 의문이 있습니다 🤔

현재 자바 콘솔기반 자동차 경주 게임을 만들고 있는데, 일반적으로 웹 애플리케이션에서 사용되는 MVC 아키텍처 네이밍을 따라갈 필요는 없다고 생각돼요. 일반적인 스프링 컨트롤러는요청에 대한 전처리 -> 서비스 메서드 위임 -> 응답 반환을 하는 반면, 도비의 RaceController의 역할에 대해 살펴보자면, 아래와 같은 동작을 하고 있습니다.
```
1. 입력 값을 받는다.
2. 입력 값을 검증한다.
3. 각 객체를 생성한다.
4. 라운드를 진행시킨다.
```
웹 관점으로 본다면 오히려 컨트롤러+서비스의 역할을 하고 있다고 생각되는데요! 
콘솔기반 게임 개발에서 굳이 엄격하기 MVC 패턴명을 따라갈 필요는 없다고 생각해요.
차라리 게임의 동작을 담당하는 객체 관점의 네이밍을 사용해보는건 어떨까요? 
단순 의견이므로 꼭 반영할 필요는 없습니다 :)

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/controller/RaceController.java
> +    private final InputValidator inputValidator = new InputValidator();
훨씬 단조롭네요 👍

추가로 `InputView`와 `InputValidator`가 여러번 생성될 필요가 있는 객체일까요?

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/controller/RaceController.java
> +    }
```suggestion
    private List<Car> generateCarListByCarNames(List<String> carNames) {
        return carNames.stream()
            .map(carName -> new Car(carName, new RandomNumberGenerator()))
            .collect(Collectors.toList());
    }
```
한 줄에 점 하나씩!
또한, `List<Car>`를 만들어서 `Cars`를 생성하기보다는 `Cars`가 내부적으로 생성하도록 책임을 넘겨줄 수 있지 않을까요?
도비가 생각하는 `Cars`의 책임은 무엇인가요? 🤔

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Car.java
> +    private final int RANDOM_NUMBER_BOUNDARY = 10;
상수는 static final을 사용해주세요. 또한 메서드 순서도 고려해봅시다!
저는 다음과 같이 작성하는 것을 선호합니다.
```
public class ClassName {
    // private static final
    // 상수
    // 클래스 변수
    // 인스턴스 변수
    // 생성자
    // 팩토리 메서드
    // 일반 메서드 (호출 순서 지키기)
    // getter, setter
    // equals, hashCode, toString
}
```

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +        return Collections.unmodifiableList(cars);
불변 리스트 사용 👍
불변을 사용했을 때의 장점은 무엇인가요? 😊

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +        return cars.stream().filter(car -> car.getPosition() == farthestDistance).collect(Collectors.toList());
postion을 꺼내서 비교하기보다는 `Car`에게 메시지를 보내보아요

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +        return cars.stream().mapToInt(Car::getPosition).max().orElse(0);
[객체지향 생활체조 원칙] 규칙 4. 한 줄에 점을 하나만 찍는다

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Race.java
> +public class Race {
`Race`는 어떤 도메인인가요? 이름만으로는 자동차나 심판처럼 값 객체(VO) 같아보이는데, 실상은 로직과 출력을 담당하고 있네요! (값 객체에 대해 학습해봅시다 😊)
작성하신 `Controller`는 입력만을 담당하고 막상 출력은 `Race`에서 담당하고 있으니 조금 애매한 것 같아요 😢

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Cars.java
> +public class Cars {
일급 컬렉션 👍

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Referee.java
>  public class Referee {
Referee 객체의 역할에 대해서도 고민해봅시다!
`Cars`를 받아와서 우승자를 리스트에 넣어주고 반환하기만 하는데 그냥 `Cars`가 내부에서 가장 멀리간 자동차들을 분류해보는건 어떨까요?

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/view/InputView.java
> +    Scanner scanner = new Scanner(System.in);
접근 제어자가 없습니다 😢 여쭤보신 코멘트에 남겨놓았는데 못보셨을까봐 다시 작성할게요 :)
> 현재와 같은 경우라면 같은 view 패키지 클래스에서 접근이 가능할 것 같아요.
Scanner 나 InputValidator는 InputView에 한해서만 사용할 것 같아서 말씀드렸습니다 !
곧 읽어보시겠지만, 이펙티브 자바에 15. 클래스와 멤버의 접근 권한을 최소화하라가 있습니다 😊

2024-02-18 08:51 UTC, syoun602 commented on src/main/java/racingcar/model/Race.java
> +}
EOF가 여전히 누락됩니다!

2024-02-18 08:53 UTC, merged

2024-02-19 08:20 UTC, Dobby-Kim commented on src/main/java/racingcar/controller/RaceController.java
> +    private final InputValidator inputValidator = new InputValidator();
아닌 것 같습니다!
이런 경우에는 정적 메소드를 사용해도 되는지 고민이 되는 부분이긴 했습니다..!

2024-02-19 08:23 UTC, Dobby-Kim commented on src/main/java/racingcar/controller/RaceController.java
> +    }
일급컬렉션으로서 list로 품고 있는 객체들에 대한 기본적인 데이터 처리 및 가공에 대한 책임을 가져야된다고 생각하고 있습니다!
말씀해주신 부분 생각해보니 지니고 있을 객체를 직접 생성하는 역할 또한 처리 및 가공 역할이라고 할 수 있을 것 같습니다!!