[1단계 - 자동차 경주 구현] 재즈(함석명) 미션 제출합니다.
woowacourse/java-racingcar pull request #704
Opened 2024-02-15 07:58 UTC by seokmyungham

2024-02-15 08:39 UTC, seokmyungham commented
안녕하세요!! 코드를 설계하면서 궁금한 부분들에 대해 여쭤보고 의견을 듣고 싶습니다.

1. 검증 로직 책임을 어디에 둬야할까?

입력 값 형식을 단순 검증하는 로직과 핵심 도메인과 관련된 검증 사항을 구분지어 생각했는데,
단순 검증의 경우 컨트롤러에서 진행하고, 핵심 검증 사항들은 각 도메인이 책임을 지도록 진행했습니다.

도메인에 단순 검증까지 책임을 부여할 경우 도메인이 과도하게 무거워지는 것 같다고 생각합니다.
그리고
단순 검증을 뷰가 아닌 컨트롤러에서 검증을 진행한 이유는
프론트엔드와 협업을 진행하는 프로젝트일 경우를 생각해보면 사용자 데이터는 가장 먼저 컨트롤러에서 만나게 되고,
프론트에서 검증을 하더라도 서버는 항상 데이터 무결성을 고려해야 하고, 서버에서 별도의 검증 과정은 필수라고 생각하는데 어떻게 생각하시는지 정말 궁금합니다.

2. 단순히 검증만을 위해 기능이 없는 모델을 만들어야 하는가?
사용자 입력 값 TryCount의 경우 양의 정수인지 검증하는 단순한 검증만을 포함하고,
모델 클래스를 생성하기에는 아무 기능이 없는 모델이 생성될 것 같아 int형으로 반환했는데 이럴 경우에 어떻게 해결하는게 더 나은 방향인지 궁금합니다.

3. 출력을 위한 getter를 사용하는 것
데이터가 외부에서 변경되는 것을 막고 도메인에서 책임을 지도록 의미를 반환하는 것이 맞다고 생각하고 있는데
이번 미션을 진행하면서 문자열 Name을 클래스로 포장하고 뷰에서 출력하기 위해 getter를 사용하게 되었습니다.

이러면 모델의 구조가 노출되는 형태가 되는 것 같고 이러한 부분을 지양하고 싶은데
DTO를 이용해서 정말 필요한 데이터만 전달하는 방식을 선택해야 할 지
출력을 위한 getter는 괜찮은지 궁금합니다.

시간 내주셔서 글과 코드 읽어주셔서 감사하고 리뷰 기다리겠습니다!!
감사합니다.

2024-02-16 11:53 UTC, Deocksoo commented on README.md
> +## 구현 기능 목록
👍

2024-02-16 13:33 UTC, Deocksoo requested changes
안녕하세요 재즈, 리뷰어 러너덕입니다.
작성해주신 코드 잘 읽어보았어요. 메서드를 작은 단위로 나누고, 규칙에 맞는 값이 들어오는지 잘 검증할 수 있도록 노력해주셨네요 👍 검증하기 위한 코드를 테스트하는 코드도 꼼꼼하게 잘 작성해 주셨어요.

규칙이 잘 동작하도록 꼼꼼하게 코드를 작성하는 부분은 잘 연습하고 계시는 것 같으니, 
이번 과제에서는 아래 부분들에 집중해서 코드를 작성하는 연습을 해보시면 어떨까 싶어요 :)

1. 좋은 이름 짓기
2. 중요한 규칙을 테스트하기
3. java 코드 컨벤션 익숙해지기

특히 첫 번째인 '좋은 이름 짓기'는 정말정말 중요해요. 코드를 작성하는 데에 있어서 중요한 것들이 참 많지만, 딱 한 가지를 뽑으라면 저는 '좋은 이름 짓기'를 뽑겠어요!
관련해서 고민해보시면 좋을 만한 부분들에 코멘트 남겨두었으니, 확인 한 번 부탁드려요~

ps.
> 1. 전체적인 검증 로직 책임을 어디에 둬야할까?

서버에서 필요한 검증을 하는 일은 반드시 필요하고, 중요한 일이죠!
다만 이번 미션에서는 값 검증과 관련해서 충분히 고민해주신 것 같네요 ㅎㅎ
이어지는 고민들은 다음 미션들을 진행하시면서 고민해보셔도 좋을 것 같아요.

> 2. 단순히 검증만을 위해 기능이 없는 모델을 만들어야 하는가?

그것을 모델이라고 부를 수 있을지는 모르겠지만, 검증하는 것도 기능일 수 있겠죠. 다만, 필요하다는 생각이 들지 않으면 만들지 않는 것이 좋아요.

> 3. 출력을 위한 getter를 사용하는 것

꼭 Dto 만들어야 하나요 ㅎㅎ 필요하면 getter 써야죠~

2024-02-16 13:33 UTC, Deocksoo commented on README.md
> +## 구현 기능 목록
👍

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/view/OutputView.java
> +    public static void showWinners(Race race) {
메서드 이름이 드러내는 것보다 더 많은 일을 하고 있네요.
단순히 winner를 보여주는 게 아니라, winner를 뽑는 일도 안에서 같이 하고 있군요.
메서드가 하는 일을 더 명확하게 드러내는 이름을 지어주거나, 혹은 메서드에서 하고있는 또다른 일을 분리해내는 것은 어떨까요?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/controller/RaceController.java
> +        showRaceResult();
Race 결과를 보여줄 것 같이 생겼는데, 별다른 일을 하지 않고 있네요. 꼭 필요한 메서드인가요?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Race.java
> +    public void oneGame() {
[Java naming convention](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)에 따라 메서드가 뭘 하는지 표현할 수 있도록 조금 더 좋은 이름을 찾아주면 어떨까요~?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Race.java
> +        if (randomNumber >= 4) {
이 숫자는 이번 게임에서 가장 중요한 규칙을 담고 있는 숫자일 것 같아요. 앞서의 리뷰와 마찬가지로 constant 처리해서 좋은 이름을 붙여주면 어떤가요?

더불어 이 부분은 아마도 자동차 미션에서 가장 핵심적인 부분 중 하나일 것 같아요.
제대로 동작한다는 것을 검증할 수 있는 테스트를 추가해보는 것은 어떤가요?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Race.java
> +        for (String name : invalidNames) {
name은 invalidNames 에서 뽑아온 이름들이군요.
이 name은 valid한 name인가요, 아니면 invalid한 name인가요?
이 name들은 항상 invalid한 이름만 들어오나요?
이 이름으로 Car를 만들어도 괜찮나요~?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Race.java
> +        if (invalidNames.size() < 2) {
이 숫자도 게임 규칙과 관련된 특별한 숫자일 것 같네요.
[Java naming convention](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) 에 맞게 constant 처리하는 것은 어떤가요?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Name.java
> +        if (name.isBlank() || name.length() > 5) {
이 숫자는 게임 규칙과 관련해서 특별한 의미를 가지고 있는 숫자일 것 같아요.
[Java naming convention](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)에 따라 constant 처리하는 것은 어떤가요?

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/utils/TryCountValidator.java
> +    private static final String format = "[1-9]\\d*";
Java naming convention에 따라 이름을 지어주면 좋겠어요!

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/model/Car.java
> +    public String showDistance() {
이 메서드는 distance를 보여주는 기능을 하나요?
메서드 이름과 실제 기능이 다른 것 같아요!

2024-02-16 13:33 UTC, Deocksoo commented on src/main/java/view/InputView.java
> +    private static Scanner scanner = new Scanner(System.in);
Java naming convention에 따라 이름을 지어주면 좋겠어요!

2024-02-16 19:30 UTC, seokmyungham commented
이렇게 페어와 구현하는 방식은 처음 경험해봤는데
즐거운 토론에 너무 열중한 나머지 마지막에 부랴부랴 기능 구현하기에도 시간이 빠듯했던 것 같아요

러너덕이 말씀 한대로 충분히 고민하고 신경 써야 할 부분들에 너무 소홀했네요...
리뷰 받고 코드를 다시 보니, 정말 코드 읽기 힘드셨을 것 같아요 ㅠㅠㅠㅠ

리뷰 해주신 부분들을 다시 돌아보며 단순히 가독성을 위한 이름 짓기 이상으로,
"네이밍이 힘든 메서드는 책임이 명확하지 않거나 기능이 너무 많기 때문이다"를 몸소 경험할 수 있었어요
기능과 책임이 명확한 메서드일수록 확실히 좋은 이름을 짓기 수월함을 알게 됐습니다!!
마찬가지로 컨벤션도 의식적으로 계속 지키도록 노력하기로 다짐하게 됐어요

이름을 매우 많이 바꿔야 했었는데 조금은 좋은 이름들이 되었는지 궁금해요

> 꼭 Dto 만들어야 하나요 ㅎㅎ 필요하면 getter 써야죠~

getter를 안 써야 한다는 무언의 압박 때문에 모델의 코드가 지저분해지는 것 같았는데 
distance를 그냥 get으로 꺼낼 수 있어서 속이 시원하네요
그런데 한편으로는 모델(도메인)이 출력 뷰까지 매개변수로 들어가는 부분은 찝찝함이 조금 남아있는 것 같긴 해요
컨트롤러에서 출력을 위한 값들을 꺼내서 값만 뷰로 넘겨야 할지.. 뭔가 좀 애매한 느낌... (distance, winner 출력)

네이밍을 신경쓰다보니 자연스레 코드 구조까지 개선된 것 같아요
리뷰 해주셔서 감사드리고
코멘트 기다리고 있겠습니다!

2024-02-17 14:05 UTC, Deocksoo approved these changes
맞아요. 좋은 이름 짓기는 단순히 이름만 고민한다고 해서 되는 것이 아니라, 역할과 책임을 명확하게 나누어야 비로소 할 수 있게 되죠. 
이번 미션을 진행하면서 아주 중요한 것들을 배웠군요 :)
적절한 이름을 잘 지어주신 것 같고, 덕분에 코드도 훨씬 명확하고 깔끔하게 정리되었네요 💯

미션 진행하시느라 고생 많으셨어요. 1단계 미션은 여기서 마무리하고, 다음 미션으로 넘어가주시면 될것같아요.

2024-02-17 14:06 UTC, merged