[1단계 - 자동차 경주 구현] 카키(서현준) 미션 제출합니다.
woowacourse/java-racingcar pull request #706
Opened 2024-02-15 08:02 UTC by hyeon0208

2024-02-16 06:56 UTC, Hyeon9mak requested changes
안녕하세요 카키, 자동차 미션을 함께할 현구막입니다. 🙇‍♂️
1단계 깔끔하게 잘 구현해주셨네요!

### 1. TDD 시 코드 작성 순서

예시를 들어주신 정도가 맞습니다.
만약 테스트 대상 객체가 의존하는 구현체가 너무 많아서 테스트를 성공시키기 까지 과정이 너무 오래걸린다면(테스트가 어렵다면), 해당 객체의 역할이 너무 많은게 아닌지 고민이 필요한 시점입니다.
더 작은 단위의 역할로 분리하면 (가령 자동차의 이름을 검증할 때 `CarName` 을 별개로 만든다.), 더 쉬운 테스트 코드 작성이 가능해집니다.

가장 중요한 것은 TDD 도 결국 하나의 방법론일 뿐, TDD 가 가지는 이점과 행해야하는 이유에 대한 고민 없이 매몰되어선 안되겠네요.
TDD 가 가지는 이점과 행해야하는 이유, TDD 가 시작된 근원에 대해 고민해보신 후 답변해주세요. 😄 

### 2. 네이밍

👍 

### 3. 도메인 검증, 입력 검증 분리

넵 전반적으로 적절하다고 느꼈습니다. 다만 카키의 생각이 궁금한 부분이 있어서 코멘트 남겼습니다.
대부분의 경우에 파라미터가 동일함에도 팩터리 메서드를 생성해주셨는데, 이 부분에 대한 질문입니다.

### 4. 전체적으로 객체지향이 잘 적용되었는지?

객체지향이 뭘까요? 우선 카키의 답변을 듣고 재답변 드리겠습니다 😄 

코멘트 확인해주시고, 카키의 의견을 공유해주세요.
궁금하신 점 언제든지 추가 코멘트 남겨주세요.

2024-02-16 06:56 UTC, Hyeon9mak commented on README.md
> +    - [x] 아래 예시와 같이 각 자동차 별로 자동차의 움직임을 `-` 표시한다. `pobi가 두 번 움직였을경우 ex) pobi : --`
기능별 구현사항을 꼼꼼하게 잘 정리 및 체크해주셨네요 👍 👍 💯

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/controller/RacingController.java
> +    }
코드를 잘 짠다, 코드를 읽는다는 건, "글을 잘 쓴다.", "글을 읽는다." 와 동일한 것 같아요.
자동차 경주 게임이라는 큰 흐름을 읽을 때, '입력에 실패하면 재입력을 유도한다.' 라는 부분은 굉장히 사소한 내용으로 보여요.
재입력을 유도하는 부분 까지도 잘 포장해서, 전체적인 로직의 흐름을 이해하기 편하도록 해주는 건 어떨까요?

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/controller/RacingController.java
> +    }
만약 카키 동료에게 "자동차 이름 파싱 기준을 `,` 에서 `#` 으로 변경해주세요." 라는 요구사항이 전달된다면
동료는 `inputView` 와 `StringConvertor` 중 어떤 패키지와 어떤 클래스 파일에 먼저 눈길이 갈까요?

혹시 이름을 `,` 기준으로 잘라주는 것 까지도 `inputView` 의 책임이라고 볼 수 있을까요?
카키의 생각이 궁금해요.

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/controller/RacingController.java
> +        }
`Attempt` 에게 `게임을 종료시킬 만큼 충분히 움직였니?` 라고 물어보는 건 어떨까요?

> 객체에 메세지를 보내라

객체에 메세지를 보내는 형태의 코드를 작성했을 때 생기는 이점은 무엇일까요?

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/domain/Attempt.java
> +
기본 생성자 대신 팩터리 메서드를 만든 이유가 있을까요?

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/controller/RacingController.java
> +        }
매번 새로운 난수 생성기 인스턴스를 만들 필요는 없어보이네요!

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/domain/Cars.java
> +    }
`2대 이상이` 에서 `MIN_CARS_SIZE + 대 이상이` 라는 메세지 표현을 이용하면, 추후 관리가 더 편해지겠네요 😉

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/domain/Name.java
> +    }
`name.contains(" "); ` 로 줄여볼 수도 있겠네요 😉

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/domain/NumberGenerator.java
> +}
함수형 인터페이스 선언 👍

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/domain/RandomNumberGenerator.java
> +    }
시작값도 명시해서, 시작값과 끝값을 한 눈에 드러내주는 것도 좋아보여요 😉

2024-02-16 06:56 UTC, Hyeon9mak commented on src/main/java/view/ExceptionRetryHandler.java
> +}
UNIX의 표준으로는 파일 마지막에 개행이 있어한다고 해요. 잠재적인 문제가 될 수 있기 때문에 Github 에서도 EOF 알림을 띄우는 것 같아요. (https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/)

 intellij 를 사용하시는 경우 `Editor` > `General` > `Ensure every saved file ends with a line break` 를 체크하시면 파일 마지막에 자동으로 개행이 적용됩니다.

![image](https://github.com/woowacourse/java-racingcar/assets/37354145/5402ed5a-d083-41ad-ba32-32e0493cf2cc)

2024-02-16 06:56 UTC, Hyeon9mak commented on src/test/java/domain/CarTest.java
> +    }
`@ParameterizedTest` 활용 👍

2024-02-16 08:20 UTC, hyeon0208 commented on src/main/java/domain/Cars.java
> +    }
말씀대로 요구사항이 바뀌어 MIN_CARS_SIZE의 값이 바뀌게 될 경우  예외 메시지도 동일한 요구사항에 맞게 출력되도록 변경이 필요해보이네요 !

2024-02-16 08:23 UTC, hyeon0208 commented on src/main/java/domain/Name.java
> +    }
기능명세서에 설명이 안되있는데 저희는 자동차 이름의 앞 뒤에 스페이스 " "를 허용하지 않고, 이름 중간에는 공백을 허용하도록 의도하고 설계했습니다! ("ka ki")
기능명세서에 추가로 해당 요구사항을 추가하고, 앞 뒤에 " "가 있을 경우 예외를 발생시키는 것이 아닌 사용자 편의성을 위해서 trim된 값이 반환되도록 설계할 수도 있을 것 같네요!

2024-02-16 08:27 UTC, hyeon0208 commented on src/main/java/domain/RandomNumberGenerator.java
> +    }
말씀대로 한눈에 파악되지 않는다고 생각합니다 ㅠ
범위안의 숫자가 랜덤으로 생성된다는 것을 한눈에 파악할 수 있도록 수정해봐야겠습니다 !

2024-02-16 08:47 UTC, hyeon0208 commented on src/main/java/view/ExceptionRetryHandler.java
> +}
이런 규칙이 있었군요 ! 
알려주신 방법대로 자동 개행 적용했습니다 감사합니다 ㅎㅎ

2024-02-16 10:12 UTC, hyeon0208 commented on src/main/java/controller/RacingController.java
> +        }
- Attempt 에게 게임을 종료시킬 만큼 충분히 움직였니? 라고 물어보는 건 어떨까요?

객체에 메세지를 보냄으로써 캡슐화 원칙을 지킬 수 있다고 생각합니다.
이로써 외부에서 상태값을 변경하는것이 아닌 객체가 스스로 자기 할일을 하도록 만듬으로써 보다 객체지향적 설계가 된다고 생각합니다!

- 매번 새로운 난수 생성기 인스턴스를 만들 필요는 없어보이네요!
반복문을 통해 계속 해서 새로운 인스턴스가 생성되고 있는지 인지하지 못했었네요 ..! 감사합니다 !

2024-02-16 10:56 UTC, hyeon0208 commented on src/main/java/domain/Attempt.java
> +
제가 확실하게 아는 것은 아니라서 이부분에 대해 정말 많은 고민이 있었는데
위 처럼 정적 팩토리 사용한 이유는 "생성자에 코드를 넣지마라"라는 글을 봤기 때문이였는데요..
지금까지 생성자에 코드를 넣지마라는 이유에 대해 알고 있던 건
1. 생성자는 말 그대로 필드값을 초기화하여 생성만 하는 것
2. 생성자에 코드가 있을 경우 매번 생성시점에 코드가 실행되기 떄문에 제어하기 힘들어진다.
라는 내용이었습니다.
하지만 이 내용에 대해 리뷰를 받고 고민해보며 찾아보니
제 결론은 다음과 같이 나왔습니다.

> 생성자에 코드를 넣지말라는 것은 파싱 같이 인자 값의 형태를 변환하는 코드가 들어가선 안된다는 말이다.
> 만약 생성시점에 인자를 변환하여 초기화할 경우 객체를 생성할 때 마다 의도와 다른 결과가 나올 수 있기 떄문에 제어권을 잃을 수 있다.
> 즉, 파싱 같이 데이터를 변환하지 않는 이상 유효성검증같은 신뢰도를 상승시켜줄 수 있는 로직은 생성자에 있어도 문제가 없다.

제가 이해한 내용이 맞는지 궁금합니다!

2024-02-16 13:16 UTC, hyeon0208 commented on src/main/java/controller/RacingController.java
> +    }
동료 입장에서 생각해보면 StringConvertor 쪽에 눈길이 갈것 같습니다.
inputView는 입력값을 받아서 반환만 하는 역할을 하도록 하고 StringConvertor가 요구사항에 따라 동적으로 구분자를 기준으로 잘라줄 수 있는 역할을 할 수 있도록 하는 것이 좋을 것 같다고 생각이 듭니다!

2024-02-16 16:50 UTC, hyeon0208 commented on src/main/java/controller/RacingController.java
> +    }
리뷰를 보고 어떻게 해야 로직의 흐름을 이해하기 편하게 할 수 있는지 고민해봤는데
말씀하신것에 대해 제가 확실히 이해 한 것이 맞는지 궁금합니다 !

> 현재는 컨트롤러의 run 메서드에서 Cars 객체와 Attempt 객체를 ExceptionRetryHandler 클래스의 메서드를 통해 중간에 어떤 과정을 거치는 지 흐름을 파악하지 못하는데 이 흐름 순서를 파악하기 쉽도록 분리하는 것이 좋을 것 같다.

2024-02-17 02:48 UTC, hyeon0208 commented
정말 꼼꼼한 리뷰 감사드립니다 현구막!
말씀해주신 리뷰를 반영하여 리팩토링을 진행해봤습니다.
여러 고민을 해보면서 많은 수정이 오갔는데 제가 잘 못 이해한 부분이 있는지 봐주시면 감사드리겠습니다!

 ### 수정된 부분
리뷰남겨주신 부분 외에도 리팩토링을 진행하다가 이렇게 바꾸는게 좋지 않을까? 라고 생각 든 부분에 대해서도 수정을 하여
이 수정된 부분이 괜찮은지가 궁금하여 질문드립니다.

- 정적 팩토리 메서드와 생성자가 상황에 맞게 적절히 사용 되었는지 ?
- 각 클래스들이 자신의 역할에만 충실하도록 수정되었는지 ?
- 재입력을 받는 로직의 indent를 1로 만들기 위해 재귀함수를 사용했는데, 이 경우 사용자가 악의적으로 무수히 많은 재입력을 유도하게 될 경우 스택오버플로우가 발생할 수 도 있다고 생각하여 제한된 재시도 입력 횟수를 초과할 경우 예외가 발생하도록 했는데 오버엔지니어링인지?


### 객체지향이란?
저는

2024-02-18 07:50 UTC, Hyeon9mak approved these changes
안녕하세요 카키! 피드백 잘 반영해주셨습니다 👍 👍 

#### 팩터리 메서드

추가 코멘트 남겼습니다.

#### 사용자 입력 SOF 방지

재귀함수 예외처리는 충분히 잘 해주셨다고 생각합니다. 
비즈니스 정책으로 제한하는 등 여러가지 해결방법도 있을텐데, 잘 해주신 것 같아요.

#### 클래스들의 역할, 팩터리 클래스

클래스들이 자신의 역할에만 충실한지, 책임을 잘 나눠 가졌는지는 어떻게 판단하면 좋을까요?
아래 객체지향 답변에 제 생각을 남겼습니다.

#### TDD

👍 여러 고민을 하면서 카키의 생각을 정리중이신 것 같네요.

TDD 를 병행하다보면 자연스럽게 코드 수정량이 많아질 수 밖에 없죠.
이게 시간 낭비이고 귀찮은 일이라고 여길 수 있지만, 그만큼 내 설계가 옳았나 틀렸나를 즉각적으로 인지할 수 있는 장점도 있다고 생각해요.

테스트 코드를 수정하는 일은 어렵게 여기지 않으셨으면 좋겠어요.
치아보험을 가입했던 카키가 치과치료를 건강히 마치고 더 이상 치아보험이 필요없어 졌을 때,
해지를 하거나 다른 보험으로 전환하는 것과 마찬가지일거 같아요.

#### 객체지향

객체지향에서 현실세계를 빗댄다는 것은
"현실에 존재하는 개념, 모든 사람들이 알고 있는 '상식'을 활용해서 코드 이해를 돕는다." 라고 생각해요.
`Car` 라는 클래스도 결국 정해진 로직에 따라 자신이 가진 정수 값을 바꾸는 것일뿐,
그 자체가 자동차처럼 엔진을 움직여 동력을 얻고 달리거나 하진 않죠.

그러나 우리는 `자동차` 라는 이름 덕분에 우리가 알고 있는 상식을 활용해
자동차의 모습을 상상하고, 상수 값 변경을 통해 위치가 변경되었음을 상상할 수 있습니다.
그 덕분에 "자동차 위치 변경 로직을 수정해주세요." 라는 요구사항이 전달되면, `Car` 클래스를 열어볼 수 있죠.

객체지향에서 이야기하는 결국 모든 것은 '유지보수'를 위함이고, 
자세하게는 '유지보수하는 시점에 최대한 적은 코드읽고 적은 코드를 수정하고 싶다.' 로 귀결 될 것 같아요.

만약 자동차 이름에 대한 정책만 자주 변경되는 프로젝트일 땐, 
`Car` 대신 지금처럼 `Name` 별개 클래스를 만들어 관리하면 읽어야할 코드도 확 줄어들고, 
더 집중적으로 관리하기 편하겠어요.

반대로 자동차 전체 비즈니스 정책에 대한 변경이 잦은 프로젝트일 땐, 
`Car` 클래스 파일 하나에 모든 검증 로직을 몰아두는 것이 코드를 수정할 때도 편하고, 
코드리뷰도 여러 클래스 파일을 열어볼 필요 없어서 편해질 것 같아요.
혹은 `CarValidations` 와 같은 별개 클래스를 만들어서 검증로직들만 몰아두어 관리하는게 더 좋을 수도 있겠네요.

이와 같이 각 상황에 따라 나누는 것이 좋을수도, 합치는 것이 좋을 수도 있습니다.
우테코 미션은 그 경계가 모호한 편인데,  우선 mvc 패턴에 맞춰 
"domain 은 자주 변경되지 않고 view 가 자주 변경되는 프로젝트다."
라는 기준으로 세우고 진행해보시면 클래스 분리에 대한 감이 쉽게 잡히실 것 같아요.

다음 단계 진행과 함께 고민해주세요!

2024-02-18 07:50 UTC, Hyeon9mak commented on src/main/java/controller/RacingController.java
> +    }
의도대로 잘 변경해주셨습니다! 제가 어렵게 설명했던거 같아요 🙏 
메서드 등을 이용해서 `재입력을 유도한다.`를 숨겨주면 어떨까 였어요. 👍

2024-02-18 07:50 UTC, Hyeon9mak commented on src/main/java/domain/Rap.java
> +    }
> 객체에 메세지를 보냄으로써 캡슐화 원칙을 지킬 수 있다고 생각합니다.
이로써 외부에서 상태값을 변경하는것이 아닌 객체가 스스로 자기 할일을 하도록 만듬으로써 보다 객체지향적 설계가 된다고 생각합니다!

👍 디테일하게 상황을 설명한다면, 추후 경주 횟수 관련 리팩터링이 필요할 때 `Rap` 클래스만 확인하면 된다는 장점이 생겨나겠네요. 다른 코드들의 변화를 신경쓸 필요가 없어지구요.

2024-02-18 07:50 UTC, Hyeon9mak commented on src/main/java/domain/Car.java
> +    }
> 생성자에 코드를 넣지말라는 것은 파싱 같이 인자 값의 형태를 변환하는 코드가 들어가선 안된다는 말이다.
만약 생성시점에 인자를 변환하여 초기화할 경우 객체를 생성할 때 마다 의도와 다른 결과가 나올 수 있기 떄문에 제어권을 잃을 수 있다.
즉, 파싱 같이 데이터를 변환하지 않는 이상 유효성검증같은 신뢰도를 상승시켜줄 수 있는 로직은 생성자에 있어도 문제가 없다.

카키처럼 해석하실수도 있겠네요!
저는 생성자에서도 검증과 같은 비즈니스 로직들을 수행해줄 수 있다고 생각해요.
팩터리 메서드의 존재 자체가 "생성하기 전/후로 무언가 다른 행위를 할것이니 확인해주세요." 라고 동료 개발자에게 메세지를 남기는 것과 같다고 생각해요.
그래서 지금 변경해주신 코드와 같이, "원래는 `Name`과 `poisition` 이 필요한데, 팩터리 메서드로 조금 다르게 만들기도 가능해요." 라고 메세지를 넘기는 상황에서 활용하는게 적절하다고 생각합니다.
팩터리 메서드가 너무 잦아지면, 그 메세지의 힘이 조금씩 흐려질 것 같아요.

2024-02-18 07:50 UTC, Hyeon9mak commented on src/main/java/domain/Name.java
> +    }
오호 그렇네요. 👍 제가 카키의 요구사항 정리를 제대로 읽지 않았어요 😱

2024-02-18 07:50 UTC, Hyeon9mak commented on src/main/java/domain/RandomNumberGenerator.java
> +        return random.nextInt((MAX_NUMBER_RANGE - MIN_NUMBER_RANGE) + 1) + MIN_NUMBER_RANGE;
오.. 👍 👍

2024-02-18 07:50 UTC, merged

2024-02-18 11:45 UTC, hyeon0208 commented on src/main/java/domain/Name.java
> +    }
이건 제 실수입니다.. ㅎㅎㅎ 기능 요구사항에 이름 중간에는 공백을 허용한다라는 요구사항을 추가하지 않았었어요 😅

2024-02-18 12:47 UTC, hyeon0208 commented on src/main/java/domain/Car.java
> +    }
협업 상황에서 메시지가 될 수도 있겠네요 !!
이 전에 이펙티브 자바를 읽고 "생성자 대신 정적 팩토리 메서드를 사용하라"라는 것을 보고 어떤 상황에 정적 팩토리가 고민되면 좋을지 블로그에 정리해놨던 글을 다시 읽어 보고 여러 상황이 있겠지만, 말씀 주신 적절한 상황을 해석해봤는데
Game이라는 객체에 "장르"와 "이용가능나이"가 있을 경우 생성자 생성 시 이를 작성한 사람은 어떻게 생성해야하는지 알지만
이를 작성하지 않은 사람은 내부 구조를 열어보지 않는 이상 각 파라미터가 어느 순서에 들어가야하는지 모를 수 있을 건데
팩토리 메서드로 adultAccessFrom(String genre)와 fullAccessFrom(String genre)를 만든다면 "장르만 넣어주면 성인용, 전체이용가 게임이 만들어져요" 라는 메세지를 주는 상황에서 적합할 수 있겠군요!