[1단계 - 자동차 경주 구현] 로키(정해성) 미션 제출합니다.
woowacourse/java-racingcar pull request #711
Opened 2024-02-15 08:07 UTC by HaiSeong

2024-02-15 09:28 UTC, woonjangahn requested changes
안녕하세요 로키! 우테코에 오신 것을 환영해요 👋 
`final`이나 `Stream`을 적극적으로 사용한 깔끔한 코드가 인상적이었어요 :)

코멘트 몇 개 남겼으니 확인 부탁드려요 :)

2024-02-15 09:28 UTC, woonjangahn commented on src/docs/README.md
> +    - `0 ~ 9` 사이에서 랜던값을 구한다.
```suggestion
    - `0 ~ 9` 사이에서 랜덤값을 구한다.
```

2024-02-15 09:28 UTC, woonjangahn commented on src/docs/README.md
> +- 우승자 출력
[의견] 우승자 판단 기능, 경기 결과 출력, 우승자 출력 등에서 조금 더 세부적으로 요구사항을 나누면 좋을 것 같아요 :)

2024-02-15 09:28 UTC, woonjangahn commented on src/main/java/config/AppConfig.java
> +}
의존성 주입을 사용해주셨군요 👍

2024-02-15 09:28 UTC, woonjangahn commented on src/main/java/controller/Controller.java
> +
[의견] Context를 분리한다던지 하는 쪽으로의 공백 줄은 괜찮지만, 의미가 담기지 않았다면 불필요한 공백줄은 없애주셔도 좋을 것 같아요!

2024-02-15 09:28 UTC, woonjangahn commented on src/main/java/controller/Controller.java
> +                .map(car -> car.getStatus().name())
```suggestion
                .map(car -> car.getName())
```

[의견] 어떤 표현을 할 때 되도록 객체 구조를 보이지 않게 하는 것이 가독성을 개선할 수 있을 것 같아요.

2024-02-15 09:28 UTC, woonjangahn commented on src/main/java/domain/CarFactory.java
> +public class CarFactory {
[질문] 팩토리 패턴을 사용해보셨군요 👍 이렇게 했을 때 어떤 이점이 있을까요?

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/Cars.java
> +
[의견] Context를 분리한다던지 하는 쪽으로의 공백 줄은 괜찮지만, 의미가 담기지 않았다면 불필요한 공백줄은 없애주셔도 좋을 것 같아요!

2024-02-15 09:28 UTC, woonjangahn commented on src/main/java/domain/Cars.java
> +                .peek(Car::move)
[의견] `Stream.peek`의 문서를 확인해보시면 디버깅 용도로 사용한다고 나와 있는데요, peek 대신 다른 체이닝 메소드를 사용해보는 것은 어떨까요?

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/Cars.java
> +                .mapToInt(car -> car.getStatus().distance())
```suggestion
                .mapToInt(car -> car.getDistance())
```

[의견] 어떤 표현을 할 때 되도록 객체 구조를 보이지 않게 하는 것이 가독성을 개선할 수 있을 것 같아요.

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/RacingRule.java
> +                .filter(car -> car.getStatus().distance() == maxDistance)
[의견] `Car` 객체가 어떤 위치에 있는지 직접 물어볼 수 있는 메소드가 있으면 getter을 사용하는 것보다 조금 더 의미가 명시적인 코드가 될 것 같아요.

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/RandomNumberGeneratorImpl.java
> +public class RandomNumberGeneratorImpl implements RandomNumberGenerator {
[의견] 인터페이스를 분리해주셨네요 👍 클래스의 네이밍이나 테스트에서의 용도를 봤을 때 `RandomNumberGenerator`보다는 조금 더 숫자 범위를 만들어준다는 광의적인 네이밍을 사용해주면 좋을 것 같아요. 이런 건 어떨까요?

```suggestion
public class RandomNumberRangeGenerator implements NumberRangeGenerator {
```

> 완전 주관적인 네이밍이니, 로키 하고 싶은대로 변경하시면 될 것 같아요! 다만 이렇게 하면 `~Impl`을 사용하지 않아도 된다는 장점(?) 정도 있을 것 같네요.

2024-02-15 09:28 UTC, kimhodol commented on src/test/java/domain/CarTest.java
> +    void forwardCar() throws Exception {
[질문] 테스트 메소드에서 `throws Exception`이 있으면 어떤 역할을 하게 되나요?

2024-02-15 09:28 UTC, kimhodol commented on src/test/java/domain/CarTest.java
> +    }
[의견] `@ParameterizedTest`를 사용하면 중복된 테스트 코드를 줄일 수 있을 것 같아요.

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/dto/CarStatus.java
> +public record CarStatus(String name, int distance) {
[질문] `CarStatus`를 `Car`에서 가지지 않고 `record`로 분리해서 사용하면 어떤 이점이 있을까요?

2024-02-15 09:28 UTC, kimhodol commented on src/test/java/domain/CarTest.java
> +    @DisplayName("3이하의 난수가 뽑히면 전진하지 않는다..")
```suggestion
    @DisplayName("3이하의 난수가 뽑히면 전진하지 않는다.")
```

2024-02-15 09:28 UTC, kimhodol commented on src/test/java/domain/CarTest.java
> +        assertThat(distance).isEqualTo(0);
```suggestion
        assertThat(distance).isZero();
```

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/Car.java
> +        }
[질문] `randomNumberGenerator`가 `null`인 경우가 어떤 상황에 발생할 수 있나요?

2024-02-15 09:28 UTC, kimhodol commented on src/main/java/domain/Car.java
> +        final int randomNumber = randomNumberGenerator.generateRandomNumberInRange(0, 9);
[의견] `0`과 `9`는 magic number로 보이는데, 의미를 부여해줄 수 있으면 더 좋을 것 같아요 :)

2024-02-17 07:36 UTC, HaiSeong reviewed
호돌, 안녕하세요!
급하게 과제 제출하느라 인사도 못드렸네요.
정말 꼼꼼한 코드리뷰 감사해요. 오타도 많고 컨벤션이 이상한 부분도 많았는데 다 잡아주셨군요.
지적해주신 사항 수정해서 다시 커밋 날리겠습니다!

2024-02-17 07:36 UTC, HaiSeong commented on src/docs/README.md
> +    - `0 ~ 9` 사이에서 랜던값을 구한다.
아이고 오타가 있었는데 확인도 잘 못하고 제출했군요..
잡아주셔서 감사합니다. 👍

2024-02-17 07:36 UTC, HaiSeong commented on src/docs/README.md
> +- 우승자 출력
호돌의 의견처럼 요구사항이 명확하게 보이지 않네요!
반영하겠습니다!

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/controller/Controller.java
> +
정말 부끄럽군요.
다음 미션 제출에서는 이런 실수는 하지 않겠습니다.
😢

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/controller/Controller.java
> +                .map(car -> car.getStatus().name())
`getter 사용을 지양하라`
라는 말을 의식하다보니 어거지로 더 이상한 방법을 사용하게 되었네요.
객체 구조를 외부에 노출하지 않도록 코드를 바꿔볼게요.
👍

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/Car.java
> +        }
[코드를 짤 당시 생각]
자동차 객체를 테스트 할때 랜덤한 값을 테스트 하기가 어려웠어요.
그래서 인터페이스를 이용해 `randomNumberGenerator`를 생성자에서 주입받도록 했는데요.
테스트를 하다보니 모든 자동차에 `new RandomNumberGenerator()` 를 선언해 넣어주는게 불필요하다고 생각되어서 전진하는 테스트가 아닌 자동차에는 null을 넣어서 생성했어요.
따라서 move()를 실행할때 `randomNumberGenerator == null` 인 경우는 없을 것 같아요.
그렇지만 혹시나 null을 넣은 자동차에 `move()`를 호출하면 `NullPointerException`이 발생할 수도 있다 생각해서  넣어줬어요

[지금 생각]
테스트를 위해서 원래 코드를 수정했다는 생각이 들어요. 
그리고 자동차를 만들때 `randomNumberGenerator`에 왜 굳이 `null`을 넣었나 생각이 들어요.
```suggestion
    public void move() {
    
    
    
```
이렇게 변경하고 테스트의 자동차 생성자에 
`new RandomNumberGenerator()` 를 넣으려는데 어떻게 생각하시나요?

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/Car.java
> +        final int randomNumber = randomNumberGenerator.generateRandomNumberInRange(0, 9);
의미있는 이름을 찾아서 상수로 처리하겠습니다!

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/CarFactory.java
> +public class CarFactory {
[코드를 짤 당시 생각]
팩토리 클래스가 있으면 중복된 이름의 자동차와 경주를 할 자동차의 최소 갯수를 검사하기 편하다고 생각했어요
[지금 생각]
`validateCarNamesCount`, `validateDuplicatedCarNames` 두 검증 메서드 모두 Cars 가 가질 책임이라고 생각되네요.
또한 `generateCars`를 이용해서 Cars를 생성하는 방식에 문제가 하나 더 있는것 같아요.
Cars의 생성자를 private로 막지못해 다른 사람이 Cars를 만들 때 두가지 검증을 하지 못하고 Cars를 만들게 될것 같아요.

[결론]
이 클래스는 지우는게 좋을것 같아요.
`validateCarNamesCount`,`validateDuplicatedCarNames ` 이 두 메서드는 Cars에 정의하고 생성자에서 호출하려 합니다.
생성자는 private로 막고 Cars에 정적 팩토리 메서드를 만들어 Cars를 생성하는 방법을 사용해보려고 해요.

호돌의 의견도 궁금합니다. 아니면 또 다른 방법을 추천해줄수 있나요?

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/Cars.java
> +                .peek(Car::move)
앗 그렇네요. 사용하기 편해서 유용한 기능이라고 생각했는데 위험한 메소드였군요! 다른 체이닝 메서드를 이용해볼게요.

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/Cars.java
> +
부끄럽군요.. 😂

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/Cars.java
> +                .mapToInt(car -> car.getStatus().distance())
`객체 구조를 보이지 않게` 다시한번 기억하겠습니다!

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/RacingRule.java
> +                .filter(car -> car.getStatus().distance() == maxDistance)
오 좋은 의견이에요.

그렇다면 getter를 사용하지 않아도 되겠군요.
수정해보겠습니다!

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/domain/RandomNumberGeneratorImpl.java
> +public class RandomNumberGeneratorImpl implements RandomNumberGenerator {
당시 페어와 네이밍을 고민했었는데 좋은 네이밍이군요!
Range 라는 단어가 정말 잘 어울리는것 같아요

2024-02-17 07:36 UTC, HaiSeong commented on src/main/java/dto/CarStatus.java
> +public record CarStatus(String name, int distance) {
`CarStatus` 는 Car 모델의 이름과 거리를 View에 전달하기 위해 만든 `dto` 입니다.
`dto`를 만들때 `record`로 만드는것을 추천받아서 record로 만들었습니다.

2024-02-17 07:36 UTC, HaiSeong commented on src/test/java/domain/CarTest.java
> +    void forwardCar() throws Exception {
사실 인프런의 김영한님 강좌를 들을때 테스트 코드 작성법을 처음 공부해서 그분이 사용하는 대로 무지성으로 따라했던것 같네요... ㅎㅎ
다시 생각해보니 `throws Exception`이 모든 메서드에 붙어있으면 가독성이 안좋아지고 예외가 발생할 수 있다는 오해를 불러올것 같아요.

2024-02-17 07:36 UTC, HaiSeong commented on src/test/java/domain/CarTest.java
> +        assertThat(distance).isEqualTo(0);
좋은 기능이 있군요! 감사합니다

2024-02-17 07:36 UTC, HaiSeong commented on src/test/java/domain/CarTest.java
> +    }
앗 정말 둘다 실패로직이라 `@ParameterizedTest`로 줄일 수 있겠네요. 고쳐보도록 하겠습니다!

2024-02-18 08:45 UTC, kimhodol commented on src/main/java/domain/Car.java
> +        }
제어할 수 없는 의존성을 바깥으로 빼는 것은 좋은 방법이죠 :)

2024-02-18 08:48 UTC, kimhodol approved these changes
피드백을 잘 반영해주셨습니다 💯 
다음 단계에서 뵈어요 :)

2024-02-18 08:56 UTC, kimhodol commented on src/main/java/domain/CarFactory.java
> +public class CarFactory {
정적 팩토리 메소드를 사용하는 것도 방법이 될 수 있고, 현재처럼 팩토리 클래스를 따로 분리해서 `Car` 자체의 클래스를 짧고 간결하게 유지할 수 있을 것 같아요.

개인적으로는 제일 먼저 주 생성자를 고려하고, 생성자 메소드 자체에 의미를 넣고 싶을 때 정적 팩토리 메소드를 사용해서 호출하는 쪽에서의 가독성을 개선하려고 해요. 생성시에 외부 의존이 많이 생기거나 생성로직 자체가 복잡할 때 팩토리 클래스를 따로 만드는 것 같네요 :) 

이 관점에서 바라보면, 자동차 경주에서 `Car`의 생성 로직이 복잡하지 않으니, `Car` 클래스 내부에서 주 생성자를 사용하거나 정적 팩토리 메소드를 사용하면 좋을 것 같아요 👍

2024-02-18 09:00 UTC, kimhodol commented on src/main/java/dto/CarStatus.java
> +public record CarStatus(String name, int distance) {
View에 전달하기 위한 DTO가 주 용도라면, 도메인 객체인 `Car` 안이 `CarStatus`를 알고 있기보다는, 객체 외부(컨트롤러라던가)에서 값들을 조합해서 전달해주는게 낫지 않을까 싶어요.

별개로, `record`를 사용해서 `CarName`, `CarDistance`를 각각 값 객체로 포장해서 단순한 문자열이나 숫자가 아니라는 의미를 담거나 생성 로직을 담는 것도 좋을 것 같아요 :)

2024-02-18 09:01 UTC, merged