[레벨1 - 자동차 경주] 비토(오상훈) 미션 제출합니다.
woowacourse/java-racingcar pull request #727
Opened 2024-02-15 08:48 UTC by unifolio0

2024-02-16 08:20 UTC, Hyeon9mak requested changes
안녕하세요 비토, 자동차 미션을 함께할 현구막입니다. 🙇‍♂️
1단계 깔끔하게 잘 구현해주셨네요.
몇가지 코멘트 남겼으니 확인해주시고, 비토의 의견을 공유해주세요.
또, 테스트 코드를 조금 더 보강해보는 것도 좋겠습니다.
궁금하신 점 언제든지 코멘트 남겨주세요!

2024-02-16 08:20 UTC, Hyeon9mak commented on README.md
> +  - [x] 여러명 일 시 쉼표로 구분
요구사항을 꼼꼼히 잘 정리해주셨네요 👍

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/view/InputView.java
> +    }
웹 프로그램이 되었을 때 모습을 상상한다면, 
웹페이지로부터 잘려진 자동차 이름과 정수로 이루어진 시도 회수를 입력하는 모습이 그럭저럭 자연스러울거 같아요.
그렇다면 `InputView` 역시도 그런 역할을 수행해줄 수 있겠는데요, 비토는 어떻게 생각하시나요?

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/Application.java
> +    }
객체의 생성자로 주입되는 대상은 "해당 객체가 이런 역할을 수행할 거야" 라고 힌트를 주기도 하는 것 같아요.
controller 는 어떤 역할을 수행하는 객체일까요?
controller 에게 있어 난수 생성기는 어떤 의미를 가질까요?

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/controller/RacingCarController.java
> +        } while(tryNumber.isTryable());
> 객체에 메세지를 보내라.

`TryNumber` 에게 메세지를 보내어 게임 유지/종료 여부를 결정하는군요 👍 💯

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +
난수 생성기 역시도 불변일 수 있겠어요.

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +
"자동차 이름에 대한 제약사항을 10자 제한으로 변경해주세요." 라는 요구사항이 비토의 동료에게 전달되었을 때,
동료 개발자는 `RacingCar` 와 `RacingCarNames` 중에 어떤 클래스를 먼저 열어볼까요? 비토의 의견이 궁금해요.
(아마 이것이 객체의 책임을 나누는 기준이 될 것 같아요 😄 👍 )

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +    }
사소하지만, is 대신 has 를 사용해도 자연스럽겠네요 ㅎㅎ

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +    }
Comparable 활용 👍 어떤 장점이 느껴졌나요?

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCarNames.java
> +    }
이름과 관련된 정책을 `RacingCar` 에 분산시키지 않고 `RacingCarNames` 에 모아둔 것이 때로는 더 빛날 수도 있겠는데요,
어떤 상황에서 장점이 있고, 어떤 상황에서 단점이 있을까요?

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCarNames.java
> +    }
"자동차 이름을 입력 받을 건데, 구분 기준을 `,` 에서 `#` 으로 바꿔주세요." 라는 요구사항이 전달되었을 때,
동료 개발자는 view 와 domain 패키지 중 어떤 곳을 더 먼저 열어보게 될까요? 🤔

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCars.java
> +    }
출력 객체와의 소통은 다른 계층에서 이루어져야 하지 않을까요? 🤔 
현재와 같은 구조는 어떤 위험을 갖고 있을까요?

2024-02-16 08:20 UTC, Hyeon9mak commented on src/main/java/domain/RacingCars.java
> +        Collections.sort(racingCars);
max 를 이용해봐도 좋겠어요!

2024-02-16 08:20 UTC, Hyeon9mak commented on src/test/java/domain/RacingCarNamesTest.java
> +}
UNIX의 표준으로는 파일 마지막에 개행이 있어한다고 해요. 잠재적인 문제가 될 수 있기 때문에 Github 에서도 EOF 알림을 띄우는 것 같아요. (https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/)

intellij 를 사용하시는 경우 `Editor` > `General` > `Ensure every saved file ends with a line break` 를 체크하시면 파일 마지막에 자동으로 개행이 적용됩니다.

![image](https://github.com/woowacourse/java-racingcar/assets/37354145/f4e11dd6-b8af-4aeb-8a0b-18b8506c4dc4)

2024-02-16 08:20 UTC, Hyeon9mak commented on src/test/java/domain/RacingCarTest.java
> +        Assertions.assertThat(racingCar.getMoveNumber()).isEqualTo(1);
전진이 불가능한지도 확인해보면 좋겠네요 😄

2024-02-16 10:07 UTC, unifolio0 commented on src/main/java/domain/RacingCar.java
> +
저는 RacingCar와 RacingCarNames 2개의 클래스가 있으면 RacingCar에 '이름'이라는 구성 요소가 있고, 이를 일차적으로 체크하는 곳이 RacingCarNames라고 판단할 것이라 생각했습니다.

2024-02-16 10:09 UTC, unifolio0 commented on src/main/java/domain/RacingCar.java
> +    }
Comparable을 사용하지 않으면 정렬하는 알고리즘을 직접 구현해야 해서, 정렬하는 부분의 코드를 봤을 때 이 부분이 정렬하는 코드라는 사실을 빠르게 알지 못할 것 같습니다.

2024-02-16 10:17 UTC, unifolio0 commented on src/main/java/domain/RacingCarNames.java
> +    }
RaingCar에 대한 제한 사항이 변경되었을 때, 이름과 관련된 제한 사항이면 RacingCarNames로 그 외의 제한 사항이면 RacingCar로 이동하여 변경하면 되므로 코드의 관리가 용이할 것 같습니다. 단점으로는 RacingCar와 같은 다른 도메인과 연결성이 증가할 것 같은데 이게 정말 단점이 될지는 잘 모르겠습니다.

2024-02-16 10:19 UTC, unifolio0 commented on src/main/java/domain/RacingCarNames.java
> +    }
view는 데이터 입출력과 같은 유저와 프로그램간의 상호작용을 수월하게 해주는 ui를 담당하며 데이터 가공에는 관여하지 않는다고 인지하고 있었기 때문에 domain을 먼저 열 것 같습니다.

2024-02-16 10:40 UTC, unifolio0 commented on src/main/java/domain/RacingCars.java
> +    }
각 계층간의 역할을 명확히 하여 이후에 수정이 용이하도록 해주도록 하는게 mvc패턴인데 출력 객체와의 소통은 컨트롤러에서 이루어져야 한단 것을 간과한 것 같습니다.

2024-02-16 10:48 UTC, unifolio0 commented on src/main/java/view/InputView.java
> +    }
질문을 정확히 이해하지 못 했습니다. InputView에서 입력값이 정수인 지 판별하는 로직을 넣는 것에 대해 어떻게 생각하는 지 질문 주신 건가요? 그리고 잘려진 자동차 이름이란 게 뭔지 정확히 이해하지 못했습니다.

2024-02-17 09:43 UTC, Hyeon9mak approved these changes
안녕하세요 비토~ 코드 잘 변경해주신 것 확인했어요.
답변 주신 내용중에 추가로 궁금한게 있어서 코멘트 남겼습니다!
다음 단계 진행과 함께 고민해주세요 😄 👍

2024-02-17 09:43 UTC, Hyeon9mak commented on src/main/java/view/InputView.java
> +    }
String 대신 int 로 전달하는 것과, `,` 를 기준으로 파싱하는 것에 대한 질문입니다.

2024-02-17 09:43 UTC, Hyeon9mak commented on src/main/java/domain/RacingCar.java
> +    }
음.. 정렬이라는 건 메서드 명칭이나 steam api 활용으로도 충분히 표현이 가능해보여요. 다른 장점은 없었을까요?

2024-02-17 09:43 UTC, Hyeon9mak commented on src/main/java/domain/RacingCarNames.java
> +    }
다른 도메인과 연결성이 증가한다는게 어떤 의미일까요?

2024-02-17 09:43 UTC, Hyeon9mak commented on src/test/java/domain/TryNumberTest.java
> +
`@ParameterizedTest` 를 통해 음수값 입력도 확인해보면 좋겠네요 😄 👍

2024-02-17 09:43 UTC, merged