자동차 경주 step1 제출합니다.
woowacourse/java-racingcar pull request #729
Opened 2024-02-15 08:56 UTC by hyxrxn

2024-02-15 12:00 UTC, seovalue requested changes
안녕하세요, 아토! 첫번째 리뷰를 맡은 조앤이라고 해요ㅎㅎ
미션 잘 구현해주셨네요~ 몇 가지 코멘트 남겼는데 확인 후 다시 리뷰요청주세요!
그리고 PR을 올릴 때 PR description도 잘 활용해보시면 좋을 것 같아요. 현재는 아무것도 적혀있지 않은데, 미션을 어떻게 구현하셨는지 혹은 질문이 있으시다면 남겨주셔도 좋을 것 같아요~

2024-02-15 12:00 UTC, seovalue commented on src/main/java/Car.java
> +public class Car {
모든 클래스를 main/java 내부에 위치해주신 이유가 궁금해요! (=별도로 패키지 구분을 하지 않은 이유가 궁금해요~)

2024-02-15 12:00 UTC, seovalue commented on src/main/java/Car.java
> +    private final NumberGenerator numberGenerator;
Car가 NumberGenerator를 갖도록 해주신 이유가 있나요?

2024-02-15 12:00 UTC, seovalue commented on src/main/java/Car.java
> +    public void tryMove() {
move도 있는데 tryMove를 선택해주신 이유가 궁금해요~

2024-02-15 12:00 UTC, seovalue commented on src/main/java/CarName.java
> +            throw new IllegalArgumentException("잘못된 이름입니다.");
<img width="668" alt="Screenshot 2024-02-15 at 20 52 18" src="https://github.com/woowacourse/java-racingcar/assets/48412963/5d3f930b-2178-43c5-b5f0-0746d86f4ef1">
상세한 예외 메시지를 내려주는 것은 어떨까요? 유저의 입장에서 어떤 이유로 잘못된 이름인지 판단하기가 어려워요.

2024-02-15 12:00 UTC, seovalue commented on src/main/java/InputView.java
> +            number = Integer.parseInt(sc.nextLine());
Integer의 MAX_VALUE를 최댓값으로 해주신 이유가 궁금해요~ 10000회만 찍어보더라도 UI가 이해하기 어려워지는데, 자체적으로 MAX_VALUE를 지정해보시는 것은 어떨까요?

2024-02-15 12:00 UTC, seovalue commented on src/main/java/RacingGame.java
> +    private static void run() {
👍 run 내부를 직관적으로 구현해주셨네요

2024-02-15 12:00 UTC, seovalue commented on src/main/java/NumberGenerator.java
> +public interface NumberGenerator {
👍 인터페이스의 사용 좋네요

2024-02-15 12:00 UTC, seovalue commented on src/test/java/CarTest.java
> +    }
어떤 목적의 테스트인지 궁금해요.

2024-02-15 12:00 UTC, seovalue commented on src/test/java/CarTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
`.isInstanceOf(IllegalArgumentException.class);`로만 테스트하면, 정확한 원인이 name 때문인지 파악하기 어렵다고 생각해요. 다른 이유로도 발생할 수 있기 때문에요. 예외 메시지 등으로 검증해보는 것은 어떨까요?

2024-02-15 12:00 UTC, seovalue commented on src/test/java/CarsTest.java
> +    Cars cars;
해당 변수는 setUp에만 사용되고 테스트에서는 사용되지 않아 제거해도 될 것 같아요.

2024-02-17 09:59 UTC, hyxrxn commented on src/main/java/Car.java
> +    private final NumberGenerator numberGenerator;
차가 잘 움직이는지 테스트하기 위해서 어떤 차는 항상 가고, 어떤 차는 항상 가지 않는 상황을 만들고자 했습니다. 
저도 이상적으로는 Car가 가지고 있을 필드는 아니라고 생각하긴 합니다.
다만... 테스트를 위해 다른 방법이 떠오르지 않았네요 ㅠㅠ

2024-02-17 09:59 UTC, hyxrxn commented on src/main/java/Car.java
> +    public void tryMove() {
move는 무조건 앞으로 간다는 의미처럼 느껴져서 앞으로 갈지 말지 시도해보는 메소드라는 의미에서 try를 붙였습니다!

2024-02-17 09:59 UTC, hyxrxn commented on src/main/java/Car.java
> +public class Car {
페어와 함께 구현할 때 필요성을 느끼면(현재 구현이 불편하거나, 비효율적이거나, 알아보기 힘들거나 등) 리팩토링 하자고 합의를 했습니다.
구현 중 큰 필요성을 느끼지 못해 구분하지 않았습니다!

2024-02-17 09:59 UTC, hyxrxn commented on src/main/java/InputView.java
> +            number = Integer.parseInt(sc.nextLine());
사용자가
1. 불편하더라도 10000번 라운드를 진행하고 싶다.
2. 알아보기 힘드니 10000번은 안하겠다.

중 직접 고르도록 하려는 의도였습니다.
1번을 원하는 사용자도 있을 수 있어 제작자가 먼저 라운드를 한정짓고싶지 않았습니다...! 알아보기 불편하면 사용자가 직접 10000을 입력하지 않으면 되니까요.

2024-02-17 09:59 UTC, hyxrxn commented on src/test/java/CarTest.java
> +    }
객체가 초기화될 때 이름이 원하는대로 잘 설정되었는지 확인하려는 테스트입니다!
현재는 중요한 테스트는 아니지만, 혹시 차후에 리팩토링으로 인해 코드가 변경되었을 때 이름이 의도하는 바대로 여전히 잘 설정되는지 확인하고자 했습니다.

2024-02-17 09:59 UTC, hyxrxn commented on src/main/java/CarName.java
> +            throw new IllegalArgumentException("잘못된 이름입니다.");
그러네요! 해당 사항 수정했습니다!

2024-02-17 09:59 UTC, hyxrxn commented on src/test/java/CarTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
CarName 수정과 연관해서 이 부분 또한 더 확실히 확인이 가능하게 수정했습니다!
그리고 공백과 5자 초과 이름이 함께 들어있어 이를 분리했습니다.

2024-02-17 09:59 UTC, hyxrxn commented on src/test/java/CarsTest.java
> +    Cars cars;
움직임 테스트를 위해 만들어놓고 그 테스트를 하지 않아 비참하게 잊혀졌네요...
앞으로는 미리 만들지 말고 필요할 때 만들도록 해야겠습니다.

2024-02-17 15:02 UTC, seovalue commented on src/main/java/InputView.java
> +            number = Integer.parseInt(sc.nextLine());
그렇다면 사용자는 반대로 최댓값이 Integer의 MAX 값이라는 것은 어떻게 알 수 있을까요?

2024-02-17 15:04 UTC, seovalue commented on src/main/java/Car.java
> +    private final NumberGenerator numberGenerator;
차는 자신이 얼만큼 이동할 것인지에 대한 값만 알아도 될 것 같은데, 어떻게 생각하세요?
그리고 이는 메서드의 매개변수로도 넘겨줄 수 있을 것 같구용

2024-02-17 15:06 UTC, seovalue approved these changes
안녕하세요, 아토! 리팩터링 잘 수행해주신 것 같아요.
step1은 여기서 마무리하고 step2 진행하시면 될 것 같아요~
소소한 코멘트 남겨두긴 했는데 다음 단계 진행하시면서 봐주세요!

2024-02-17 15:06 UTC, seovalue commented on src/main/java/CarName.java
> +        isPossibleName(name);
👍

2024-02-17 15:06 UTC, seovalue commented on src/main/java/CarName.java
> +    public void isPossibleName(String name) {
👍 리뷰 잘 반영해주셨네요~!!

2024-02-17 15:06 UTC, seovalue commented on src/main/java/OutputView.java
> +}
👍 나중에 다시 안내해드리려 했는데 EOF도 잘 적용해주셨네요ㅎㅎ

2024-02-17 15:06 UTC, seovalue commented on src/test/java/CarTest.java
> +                .isInstanceOf(IllegalArgumentException.class)
👍

2024-02-17 15:06 UTC, merged