[1단계 - 자동차 경주 구현] 최우종(종이) 미션 제출합니다.
woowacourse/java-racingcar pull request #731
Opened 2024-02-15 08:59 UTC by dwax1324

2024-02-15 13:10 UTC, pci2676 requested changes
반갑습니다. 🤠 

조금 더 개선해보고 고민해 볼 부분에 리뷰를 남겨두었으니 참고하시고 다시 요청부탁드립니다.

코드에 주석으로 남겨둔 부분이나 완성되지 않은 코드가 종종 보이는것 같습니다.

다음 요청주실때는 조금 더 꼼꼼히 살펴봐주시면 좋을것 같습니다 😄

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/controller/RacingGameController.java
> +    private <T> T retryUntillNoException(Supplier<T> supplier) {
오타가 있군요.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Count.java
> +            throw new IllegalArgumentException("횟수는 1에서 100사이로 입력해주세요.");
잘못 입력된 값을 같이 보여주면 더 유용할 것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Count.java
> +        if (!(count >= MIN_COUNT && count <= MAX_COUNT)) {
`!`를 사용하여 부정표현이 들어간것보다 없는것이 더 코드를 읽기 수월하게 합니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +import dto.CarNameRequest;
domain은 가능한 외부에 의존하지 않는것이 좋습니다.

외부의 변경이 domain의 변경으로 이어지지 않도록 변경해보시면 좋을것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/RacingGame.java
> +    public static RacingGame fromEmpty() {
테스트를 위한 메서드는 제거해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/RacingGame.java
> +    public static RacingGame fromCount(int count) {
테스트를 위한 메서드는 제거해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/RacingGame.java
> +    }
이름과 실제 행위가 일치하지 않는것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Car.java
> +    }
distance의 increase를 car 외부에서 get한 다음 호출하면 어떤일이 발생 할 수 있을까요?

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +        }
2대, 50대의 제한이 요구사항이었나요?

메세지가 더 풍부하게 상황을 설명해주면 좋을것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +    }
함수의 파라미터로 전달한 값이 함수를 통해 부작용이 발생하는 것은 값을 추적하기 힘들게하는 요소입니다.

winners 전달하여 값이 변하는 상황을 개선해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +    }
사용하지 않는 메서드는 제거해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/CarsTest.java
> +    }
코드 사이의 공백도 코드를 읽는데 도움을 주는 요소입니다.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/CarsTest.java
> +    }
아무것도 단언하고 있지 않는것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/RacingGameTest.java
> +    }
완성되지 않은 테스트 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/RandomMovementGeneratorTest.java
> +        assertThatCode(() -> new RandomMovementGenerator(new RandomNumberGenerator())).doesNotThrowAnyException();
exception이 발생하지 않는다는것을 테스트하는것은 의미가 있어보이지 않습니다.

RandomMovementGenerator가 어떠한 상황에서 boolean을 어떻게 내보내는지 명확하게 테스트해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/RandomMovementGeneratorTest.java
> +    }
제거해주세요

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/domain/CountTest.java
> +    }
하나의 테스트로 표현해볼 수 있을것 같습니다.

CsvTest를 참고해주세요.

2024-02-15 13:10 UTC, pci2676 commented on src/test/java/CarTest.java
> +    }
테스트 설명이 올바르게 작성 되어있는걸까요?

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/view/InputValidater.java
> +public class InputValidater {
view가 전달하는 dto에 validator에 있는 기능을 위임해주시면 좋을것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/dto/WinnersResponse.java
> +        return names;
Stream을 이용해서 표현해보는것도 좋을것 같습니다.

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/dto/CarStatus.java
> +
필요한 정보만 별도로 전달하는것 좋네요 👍

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Winners.java
> +    }
Cars에서 바로 Winner를 생성할 수 있지 않을까요?

2024-02-15 13:10 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +    }
static할 이유가 없어보입니다.

2024-02-16 00:51 UTC, dwax1324 commented on src/main/java/controller/RacingGameController.java
> +    private <T> T retryUntillNoException(Supplier<T> supplier) {
안녕하세요 비밥!
첫 미션이었는데 시간 관리를 못해 충분히 검토를 못한 거 같아요. 다음부턴 주의하겠습니다 😄

2024-02-16 03:33 UTC, dwax1324 commented on src/main/java/domain/Count.java
> +            throw new IllegalArgumentException("횟수는 1에서 100사이로 입력해주세요.");
에러메시지에 사용자의 입력을 보여준다는 것은 생각하지 못한 부분이었는데요.
그렇다면 사용자의 모든 잘못된 입력에 대한 에러 메시지마다 값을 같이 보여주어야 할까요? 
비밥의 생각이 궁금합니다.

2024-02-16 03:36 UTC, dwax1324 commented on src/main/java/domain/Count.java
> +        if (!(count >= MIN_COUNT && count <= MAX_COUNT)) {
동의합니다. 
미션 수행 중 인지하고 있었던 부분인데 리펙터링을 충분히 하지 못했네요. 수정하겠습니다!

2024-02-16 04:20 UTC, dwax1324 commented on src/main/java/domain/RacingGame.java
> +    }
이 부분에 대해서 고민을 많이 했습니다.
이 메서드에서 하는 일이 우승자를 가려내고 그 결과는 반환하는 일인데요.
두 가지 일을 한 메서드에서 하고 있어서 고민을 해봤습니다.

지금 이 메서드가 하는 일을 봤을 때 적절한 메서드명은 calculateAndGetGameResult()가 될 거 같아요.
한 메서드가 두 가지 일을 하는건 클린 코드 규칙에 의거하여 맞지 않다고 생각 했습니다.

제가 생각한 방법으로는 필드에 List<TurnResult> 를 추가하고 계산하는 메서드와 결과값을 반환하는 메서드로 분리하는 거였는데
객체지향 생활체조에서 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.라는 얘기도 있어서 결국 해결하지 못하고 시간이 촉박해 일단 넘어갔는데요.

혹시 이런 부분들에 대해 비밥의 생각이나 문제 해결을 하기 위해 제가 무엇을 더 공부해야할지 알려주실 수 있으실까요?

2024-02-16 04:29 UTC, dwax1324 commented on src/main/java/domain/Cars.java
> +        }
"경주할 수 있는 자동차는 최소 2대, 최대 50대입니다". 정도면 괜찮을까요?

2024-02-16 06:39 UTC, dwax1324 commented on src/main/java/domain/Cars.java
> +import dto.CarNameRequest;
좋은 지적 감사합니다! 
완전히 놓치고 있었던 부분이네요. "domain에 의존성이 생기면 안된다"에 대해서는 크게 인지하지 못하고 있었던 부분이었던거 같아요.
자동차 경주 같은 게임에서는 도메인이 다른 곳에 의존하지 않게 코드를 짤 수 있지만 큰 프로그램의 경우는 어떻게 되는지 궁금합니다.
제가 당장 생각 나는건 데이터 베이스 정도 인데요. 혹시 도메인이 외부에 불가피하게 의존하게 되는 다른 경우가 있을까요?

2024-02-16 07:14 UTC, dwax1324 commented on src/main/java/domain/Car.java
> +    }
distance의 increase를 car 외부에서 get한 다음 호출한다면 객체의 은닉성, 디미터 법칙, 책임에도 문제가 생길거 같습니다!
전혀 고려하지 못했던 부분이네요.
그렇다면 primitive type을 반환하는게 맞는지 궁금합니다.
어떨 때는 wrapping된 객체를 반환하고 어떨 때는 primitive type을 반환 시킬지 궁금하네요. 그 기준이라는게 있을까요?
현재 코드에서 Car 클래스 내부에 있는 Name 객체는 값을 변환시키는 메서드가 없어서 괜찮을까요?

2024-02-16 08:31 UTC, dwax1324 commented on src/main/java/domain/RacingGame.java
> +    public static RacingGame fromEmpty() {
테스트를 위한 메서드는 남겨두면 안되는 것일까요?
좋은 테스트를 가능하게 하기 위해서 서비스 코드가 약간은 바뀔 수도 있다고 생각했었는데요.
테스트를 위한 메서드를 제거해야 한는 이유에 대해 궁금합니다.

2024-02-16 08:43 UTC, dwax1324 commented on src/main/java/domain/Cars.java
> +    }
헉 전혀 고려하지 못했던 부분이네요.  
winners로 반환시키는게 방향으로 개선해보겠습니다!

2024-02-17 09:24 UTC, pci2676 commented on src/main/java/domain/Count.java
> +            throw new IllegalArgumentException("횟수는 1에서 100사이로 입력해주세요.");
외부로 노출될 문구와 개발자가 확인해야할 문구는 다르게 구분하는 경우가 있습니다.

이 부분에 대해서는 이후 레벨에서 점점 배우게 되지 않을까 싶네요

2024-02-17 09:38 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +import dto.CarNameRequest;
dto를 직접적으로 의존하지 않고 마지막에 말씀하신것처럼 날것의 데이터를 각 객체에게 넘겨주는 방법도 있을것 같습니다.

여러가지 경우가 있을 것 같은데   
지금의 경우 Cars의 생성하는, dto를 이용한 특정 구현세부사항을 Cars내에 구현해두는것이 과연 좋은 설계인지에 대한 의문을 가지게 되는 것 같습니다.

CarNameRequest 내부에 delimeter가 있길래 view에서 전달받은 데이터를 다루는것으로 보았습니다. 이는 특정 view와 밀접한 관련을 갖게 되는것 같습니다.

지금과 같은 구현을 보고 다른 view의 종류가 생겼을때 다른 개발자가 동일하게 컨벤션을 맞춰서 개발한다면 view의 종류에 따라 CArs가 점점 무거워질수 있을것 같아보여 리뷰를 드렸습니다. 😄

2024-02-17 09:40 UTC, pci2676 commented on src/main/java/domain/RacingGame.java
> +    public static RacingGame fromEmpty() {
테스트를 위해 서비스 코드가 변경될 수 있는 것은 코드를 제어하기에 설계가 적합하지 않아 개선되는 부분을 말하는것 같습니다. 😄 

모든 코드는 유지보수 대상입니다. 유지보수 비용은 낮을수록 좋지요.  
따라서 오로지 테스트 만을 위한 코드는 운영코드에서 제거해주는것이 좋다고 생각합니다.

2024-02-17 09:50 UTC, pci2676 commented on src/main/java/domain/RacingGame.java
> +    }
이것도 여러가지 방법이 있을것 같습니다.

지금 개선해주신 코드를 보았을때는 말씀해주신대로 내부 멤버변수에 결과를 저장해두고 반환하는것 같아보이네요.

아마 고민해보셨을만한 포인트가 있는데요.

결과가 만들어지기 전에 결과를 호출할 수 있지 않을까요?

이를 해결하기 위해 생각나는 방법은 2가지 정도 있을것 같습니다.

1. 기존 구현에서 메서드 이름만 바꾼다
2. getResult를 RacingGame이 아닌 다른 객체에게 넘긴다.

1번은 이름만 바꿔도 딱히 어색하지 않을것 같습니다. 두가지 일을 한다고 보여도 단순히 행위에 따른 결과를 반환한다고 하면 그리 큰 문제가 되지 않을 것 같습니다. 

2번은 조금 다른 방법입니다.  
1번에서 조금 변형하게 되는데요. 경기가 끝나고 나서 TurnResult를 얻게된다면 아래 기존 멤버변수들은 필요가 없을것 같아보입니다.

```
private final Count count;
private final Cars cars;
private final RandomMovementGenerator randomMovementGenerator;
```

그러면 move의 응답값으로 새로운 일급컬렉션을 도출하여 사용해보는건 어떨까요?

그렇게 된다면 controller에서 cars를 이용해서 winner를 가려내는 부분도 옮길수 있을것 같아보이네요.

혹시 이해가 되지 않는다면 편하게 DM주셔도 좋습니다 😄

2024-02-17 09:52 UTC, pci2676 commented on src/main/java/domain/Car.java
> +    }
이것도 여러기지 방법이 있습니다.

종이님이 말씀해주신대로 내보낼때는 원하는 정보만 내보내는것도 좋은 방법입니다.

그러면 이 방법이 왜 좋은 방법이 될 수 있을까요?

외부에서 해당 값을 가지고 변화를 가해도 기존 Car객체의 Distance는 불변하기 때문아닐까요?

그렇다면 동일하게 Distance 자체가 외부로 전달되어도 불변하도록 설계해본다면 어떨까요?

값 객체의 개념에 대해 찾아보시면 도움이 될 것 같습니다.

2024-02-17 09:53 UTC, pci2676 commented on src/main/java/domain/Cars.java
> +        }
요구사항을 일부러 추가하신건지 궁금해서 질문드렸습니다 😄 

그리고 저는 메세지에 정확한 오류의 원인을 알면 좋을것 같아 말씀드렸습니다.

위에 리뷰를 드렸던 내용이니 넘어가도록 하겠습니다.

2024-02-17 09:54 UTC, pci2676 approved these changes
다음 단계를 진행하면서 코멘트로 남겨둔 부분을 확인하고 고민해주시면 좋을것 같습니다.

머지하겠습니다 🚀

2024-02-17 09:54 UTC, merged