[2단계 - 자동차 경주 구현] 켬미(김경미) 미션 제출합니다
woowacourse/java-racingcar pull request #767
Opened 2024-02-18 12:12 UTC by kyum-q

안녕하세요 피케이😊 이번에도 리뷰를 받게된 켬미입니다!
이번엔 페어 없이 저 혼자 리팩터링을 진행해보았는데요. 1단계부터 MVC 패턴 기반으로 코드를 구현하여 어떻게 더 리팩터링 할 수 있을까 열심히 고민하면서 했습니다. 

이번 리팩터링으로 크게 변화된 부분은 ```controller와 view 분리``` 입니다.

1차 미션도 MVC 패턴을 이용해서 controller가 model(도메인)과 view 사이 중간다리 역할을 하도록 구현하였습니다. 하지만 이번 미션에서 알려준 ```MVC 패턴으로 리팩터링 후의 main 메소드 예시``` 와 다르게 1차 미션 때는 controller가 view를 관리하도록 구현하였습니다. 

```
// MVC 패턴으로 리팩터링 후의 main 메소드 예시
public class RacingMain {
    public static void main(final String... args) {
        final var carNames = InputView.getCarNames();
        final var tryCount = InputView.getTryCount();

        final var racingGame = new RacingGame(carNames, tryCount);
        racingGame.run();
        
        ResultView.printWinners(racingGame.getWinners());
    }
}
```

```
// 1차 미션에서 저의 Main 메소드
public class RacingMain {
    public static void main(final String... args) {
        final var racingGame = new RacingGame(new InputView(), new OutputView());
        racingGame.run();
    }
}
```

저는 view와 controller의 관계가 단순히 ```"view는 model과 직접적으로 연결되지 않고 controller를 거쳐간다."```라고만 생각하였습니다.
하지만 위에 예시를 보고나서 ```"view가 model과 직접적으로 통신하는 것이 아니라 컨트롤러를 통해 데이터를 얻는 방식"``` 이라고 생각하게되었습니다.

그래서 이번 미션에서는 컨트롤러에 inputView와 outputView를 주입하지 않고, inputView에서 값을 얻어와 ```controller에 해당 값들을 전달하는 방식```으로 입력을 처리하고, 레이싱을 진행시킨 후에 outputView로 출력을 하기 위해 필요한 데이터를 ```컨트롤러를 통해 얻어오는 방식```으로 구현하였습니다.

사실 하면서도 해당 방식이 맞는지에 대한 확신은 없습니다...! 혹시 이 방식이 일반적인 방식이 맞을까요?🤔

2024-02-18 17:21 UTC, pkeugine requested changes
안녕하세요 켬미, step 2 도 함께 해서 영광이에요 :)

이전에 리뷰 남겼던 내용, 그리고 이번에 추가로 작업하신 내용까지 다 확인해봤어요
켬미가 남겨주신 질문도 흥미로워서 열심히 답변 남겨봤습니다!

이미 step 1 때 MVC 구조를 어느정도 만들어놓으셔서
이번엔 바로 머지해도 괜찮겠다 싶었는데
리뷰를 남기다보니 좀 중요한 내용들이 있더라구요

그래서 좀 촉박하긴하지만, 같이 조금만 더 해보죠!
리뷰가 이해가 안되거나 질문이 있다면 언제든지 DM 보내주세요 :)

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/Main.java
> -  public static void main(String[] args) throws IOException {
불필요한 throws 제거 👍

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/model/Car.java
> +    }
경주 현황을 전체 다 받는게 아니라 원하는 만큼만 받을 수 있도록 구조를 변경하셨네요
제가 이걸 보고 가진 궁금증을 적어볼게요:

- `wantRacingCount` 라는 이름이 이해하기 조금 어려울 수 있을 것 같다. 그냥 `count` 가 더 직관적일지도?
- 요구사항에 없었고, 켬미의 애플리케이션에서 이 추가 구현으로 인해 기능이 늘어나지 않았다. (기존과 동일) 그렇다면 오히려 이렇게 복잡도를 늘린 이유는 무엇일까?
- 앞으로 Car 객체가 몇 번 이동했는지 알아야지만 경주현황을 가져올 수 있을 것 같네...
  - 이 메서드를 사용하는 쪽에서 예외를 발생시키기 딱 좋은 구조 아닐까? 예를 들어 내가 이동 횟수를 착각해서 status는 4개인데 5개를 `wantRacingCount` 로 전달했다면?
  - 위의 사태를 방지하려면 앞으로 status 를 알기 위해서는 trialCount 도 함께 다뤄야겠네. 예를 들어 파라미터로 trialCount 를 항상 전달해야겠다

실제로 step 1 과 비교해봤을 때 이 변경사항 때문에 OutputView 의 로직이 복잡해졌다고 생각해요 🤔

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/controller/RacingCarController.java
> +        return game.findWinners();
`get` 과 `find` 라는 표현을 선택하는 켬미의 기준이 있나요?
똑같이 game 에서 가져오는데 racingCar 는 `get` 이고 winner 는 `find` 네요!

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/model/Game.java
> +    }
제가 step 1 때 굉장히 중요한 부분을 놓치고 넘어갔네요...
`findWinners` 라는 메서드가 두 개이고, 한 개는 테스트에서 사용하기 위해 만들었네요!

`테스트하기 좋은 구조` 를 만드는 것은 정말 중요하지만,
`테스트에서만 사용하는 프로덕션 코드` 는 지양해야 해요.

테스트를 위해 로직을 추가한다는건
`지금 내 코드의 구조가 리팩토링이 필요하다` 는 신호로 볼 수 있어요

로직이 거의 동일하지만, 켬미가 테스트하는 `findWinners` 는 애플리케이션에서 사용하는 `findWinners` 가 아니기도 하구요
실제로 사용하는 findWinners 를 테스트할 수 있도록 Game 의 구조를 변경해보는건 어떨까요?

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/view/OutputView.java
> +    }
BufferedReader 를 사용하셔서 BufferedWriter 는 왜 안 썼을까 궁금했는데
그리 중요하진 않은 내용이라 리뷰하지 않았어요
그런데 바꾸셨다니! 👍 

여기서 재밌는 점은,
writer 의 메서드들이 `IOException` 을 throws 하기 때문에 `printWinners` 메서드도 그 예외를 throws 하고 있어요
그래서 이 메서드를 사용하는 모든 메서드가 다 `throws IOException` 을 시그니쳐에 포함해요
결국 Main 메서드의 try-with-resource 쪽에서 이 예외를 함께 잡아주고 있어요

이렇게 다른 메서드에 예외 처리를 위임하는 것은 필요할 때도 있지만
반대로 남용하다보면 예외 발생 위치를 찾기 힘들어지는 상황,
프로젝트의 구조를 변경하기 어려워지는 상황
등이 생기기 쉬워요

이 IOException 의 경우는 다른 메서드에게 예외 처리를 위임할 필요가 없어보이는데, 바로 잡아볼까요?

2024-02-18 17:21 UTC, pkeugine commented on src/test/java/model/CarTest.java
> +    return car;
테스트가 추가되면서 `createAndMovedCar()` 가 돌아왔군요!
`@BeforeEach` 에 대해서 학습해보셨을 것 같은데
이 어노테이션을 이용해서 테스트 픽스쳐를 한 번 관리해보는건 어떨까요?

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/Main.java
> +        }
켬미가 MVC 패턴에 대해 고민해본 내용을 구체적으로 적어주셔서 고마워요
덕분에 저도 좀 더 디테일한 리뷰를 남길 수 있을 것 같아요

#### 켬미의 원래 생각 "view는 model과 직접적으로 연결되지 않고 controller를 거쳐간다."
'직접적으로 연결되지 않고' 라고 한다면 model 에서 직접적으로 view 를 호출하지 않는다는 거겠죠?
좋은 생각이에요! 여기까지 일단 굳

#### 켬미의 현재 생각 "view가 model과 직접적으로 통신하는 것이 아니라 컨트롤러를 통해 데이터를 얻는 방식"
여기서 조금 미스가 생긴 것 같은데, 제가 생각하는 그 이유를 알려드릴게요

step 1 켬미의 Main 클래스는 PR 설명에 작성해주신 것처럼 생기지 않았어요.
정확히는 아래와 같습니다
```java
public class Main {
  public static void main(String[] args) throws IOException {
      // try-with-resource 는 제거하고 가져옴
      new RacingCarController(inputView, new OutputView()).run();
  }
}
``` 
Main 에서 Controller 를 만들어서 실행하죠.

예시 코드도 다시 볼게요:
```java
public class RacingMain {
    public static void main(final String... args) {
        final var carNames = InputView.getCarNames();
        final var tryCount = InputView.getTryCount();

        final var racingGame = new RacingGame(carNames, tryCount);
        racingGame.race();
        
        ResultView.printWinners(racingGame.getWinners());
    }
}
```
RacingMain 은 InputView 를 호출하고, 입력값을 받아와요.
그걸 도메인 RacingGame 에게 전달하고, `getWinners()` 를 받아와서 ResultView 를 호출해요
step 2 요구사항 보시면 아래와 같은 그림이 있죠?
<img width="905" alt="Screenshot 2024-02-19 at 12 56 03 AM" src="https://github.com/woowacourse/java-racingcar/assets/48251668/89858904-6f9c-41f4-8e25-86bd482c0070">
예시의 RacingMain 이 하는 일이 그림에서 말하는 Controller 같지 않나요?
즉, RacingMain 클래스가 Controller 역할을 하고 있어요
**RacingMain 에서 호출되는 `RacingGame`이 Controller 가 아니라 model 인거에요.**
그러니 예시에서는 view 관련 객체를 RacingGame 에게 하나도 전달하지 않아요.

그러니까 다시 말하면
켬미의 현 생각인 "view가 model과 직접적으로 통신하는 것이 아니라 컨트롤러를 통해 데이터를 얻는 방식"은
예시에서 당연히 RacingGame 이 controller 일거라고 판단해서 나온 생각이에요. 사실은 Main 클래스가 controller 인데요!
예시가 말하고자 한건
**켬미의 초기 생각인 "view는 model과 직접적으로 연결되지 않고 controller를 거쳐간다." 였던거죠 🤔** 

결론적으로 오히려 step 1 때가 요구사항에 더 적합한 MVC 구조였다고 생각해요!

"사실 하면서도 해당 방식이 맞는지에 대한 확신은 없습니다...! 혹시 이 방식이 일반적인 방식이 맞을까요?" 에 대한 질문은 이걸로 해결된 것 같네요 😄 

"그리고 이렇게 구현했을 때, 해결하지 못한 부분은 입력을 다 받아야지만 유효성검사를 할 수 있게 되었습니다!" 라는 문제점도 다시 없앨 수 있겠어요!

"이를 해결하려면 입력에서 바로 예외 검사를 해야하는데 객체 내에서 예외 검사하는 것이 더 올바르다 생각해서 따로 수정하진 않았습니다 !"

만약 유효성 검증을 바로해서 사용자에게 재시도 로직을 보여주는 것이 비즈니스적으로 정말 중요한 요구사항이었다면,
이건 당연히 구현해야할 요소라고 생각해요
충분히 구현할 수 있는 상황인데,
'그렇게 만들면 단일 책임 원칙에 어긋나'
'그러면 로직이 올바르지 않은 위치에 생겨'
라는 이유로 결과물이 좀 부족하게 만들어지는건 주객전도가 일어나는거니까요.

켬미가 말한 "입력에서 바로 예외 검사를 해야하는데 객체 내에서 예외 검사하는 것이 더 올바르다 생각" 하는건 굉장히 좋은 생각이에요 👍 
하지만 검증 시점이 빨라야한다면, 어쩔 수 없이 그 검증 로직도 다른 곳에서 더 일찍 실행되어야겠죠! 그게 제 생각이에요 :)

꽤나 많은 개발자들이 거기서 더 나아가 "모든 곳에서 검증을 해야한다"고 생각하기도 해요
중복된 검증이더라도, 외부 요소를 믿는 것보다 객체가 스스로를 책임져야한다고 생각하는거죠!

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/model/MoveStatus.java
> +    STOP("");
<img width="815" alt="Screenshot 2024-02-19 at 2 00 00 AM" src="https://github.com/woowacourse/java-racingcar/assets/48251668/a57baf06-6228-490f-aad4-cfe3a393928c">

위의 리뷰 기억하시나요?
제가 저기서 말한건 `join` 메서드를 MoveStatus 에서 빼는건 아니었어요!

자동차가 움직였을 때 "-" 표시를 출력하는건 output 요소인 것 같은데
그렇다면 MoveStatus 라는 도메인보단 view 쪽 역할일 것 같다는 생각이 들어요 😄

2024-02-18 17:21 UTC, pkeugine commented on src/main/java/model/Game.java
> +        }
테스트를 정말 잘 작성해주고 계셔서, 조금 심화(?) 내용을 한 번 다루어볼까해요

<img width="1651" alt="Screenshot 2024-02-19 at 2 08 12 AM" src="https://github.com/woowacourse/java-racingcar/assets/48251668/02758807-0185-4bb4-8d88-db80dc9e0ff5">

#### project -> test 우클릭 -> More Run/Debug -> Run tests ... with coverage

를 누르면, 현재 켬미의 코드 중 어느 부분이 테스트로 커버되어 있고 어느 부분이 되어있지 않은지를 알 수 있어요.

여기서 테스트 되어있지 않은 부분을 봤을 때,
테스트하기 어려운 곳 같다 싶으면 앞서 말한 "리팩토링이 필요하다는 신호" 가 될 수 있어요.

물론 테스트로 모든 곳을 다 커버하는 것이 늘 좋은 건 아니에요.
getter... InputView 또는 OutputView 같은 녀석들은 테스트가 필수로 있어야하는 요소는 아니니까요

해당 step 에서는 이 테스트 커버리지를 추가로 늘리진 않으셔도 괜찮아요 (이전 리뷰들이 훨씬 중요해요!)
그래도 한 번 이 프로젝트를 대상으로 커버리지 현황을 확인해보시고, 어떤 부분이 안되어 있는지 보는 것도 유용할 것 같습니다!

2024-02-18 23:41 UTC, kyum-q commented on src/main/java/model/Car.java
> +    }
사실 이 코드는 controller와 view를 분리해야한다고 한 착각때문에 수정하게 된 것 같아요
피케이 말 처럼 저도 좀 더 복잡해진 것 같다고 생각했어요 ..!
그리고 또 생각해보니 controller와 view를 분리해야한다는 생각에 사로잡혀 입출력에 의존하게 만든 것 같네요🤔
이 부분은 전에 코드로 다시 돌려놓겠습니다 !

2024-02-18 23:43 UTC, kyum-q commented on src/main/java/controller/RacingCarController.java
> +        return game.findWinners();
저는 get은 클래스에 있는 변수를 그대로 반환할 때(getter) 사용하는 걸로 find는 클래스에 있는 변수에서 코드를 거쳐 원하는 정보만 추출할 때 find를 사용하려고 했었어요
하지만 피케이 의견을 듣고 한 번 더 생각해봐야겠어요! 과연 이게 맞는지, 하나의 키워드로 통일시킬지 고민해보겠습니다!

2024-02-18 23:46 UTC, kyum-q commented on src/main/java/model/Game.java
> +    }
아 ! 그러네요 테스트를 해봤자 실제로 작동되는 findWinner()를 확인할 수 없어서 의미가 없겠네요!
이부분에 대해서는 생각을 못했던 것 같아요😓
다시 생각해보도록 하겠습니다!

2024-02-18 23:50 UTC, kyum-q commented on src/main/java/Main.java
> +        }
진짜 피케이가 저의 생각 오류 부분을 딱 집어주신 것 같아요 !
맞아요 딱 그부분에서 생각의 과부하(?)로 인해 착각을 했던 것 같아요.
피케이의 답변을 보니 main이 controller이고 racingGame이 model인데 확실히 보이네요
이번 계기로 다시 한번 MVC 모델에 대해 더 정확하게 알게되었다고 생각하려고요 😃
다시 예전 코드로 되돌려놓겠습니다 !

2024-02-19 02:23 UTC, kyum-q commented on src/main/java/view/OutputView.java
> +    }
throws 처리하는 거에 대해서는 단점을 생각하지 못했던 것 같아요 !
피케이 의견처럼 이렇게 예외 처리를 위임하는 것을 남용하지 않도록 해야겠네요 !
해당 코드 부분은 그냥 try-catch 로 변경하여 바로 RuntimeException으로 수정하였습니다 😊

2024-02-19 03:42 UTC, kyum-q commented on src/test/java/model/CarTest.java
> +    return car;
@BeforeEach는 모든 테스트 실행 전에 실행되는 함수로 알고 있는데 이걸 사용하면 해당 자동차 설정이 필요 없는 validateNullAndEmpty 나 validateNameLength 에서도 해당 부분이 실행되는 것이 좋지 않다고 판단해서 @BeforeEach를 사용하지 않았습니다. 
이렇듯 테스트 함수 중 해당 동작이 몇개는 중복적으로 필요하지만, 몇개는 필요하지 않을 경우는 @BeforeEach를 사용하는것보다 따로 함수로 분리해서 사용하는게 좋지 않은가요?
사실 잘 몰라서 하는 질문입니다 😊

2024-02-19 05:48 UTC, kyum-q commented on src/main/java/model/MoveStatus.java
> +    STOP("");
제가 리뷰를 잘 이해한 건지 모르겠지만, 해당 리뷰를 보고 MoveStatus에서 output을 빼고 OutputView에서 출력 표시 '-' 를 나타내도록 구현하였어요.
(글로 적으려니까 어떻게 설명해야할지 잘 모르겠네요)

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/model/Car.java
> -  }
커밋을 세부적으로 나누면서, 그 커밋을 checkout 했을 때 에러 없이 잘 돌아가게 유지하는 연습을 해보는 것도 좋겠네요!
e9c6abe9 - 이 커밋을 checkout 해보면 `getStatuses()` 를 사용하는 곳은 변경되지 않아서 컴파일이 되지 않거든요

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/view/OutputView.java
> +        String forwardString = "-";
"-" 이 값은 상수화하기 좋은 값일 것 같아요 :)

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/view/OutputView.java
> +        String winnersPrintMessage = String.format((PrintMessage.WINNER.getMessage()), winnersName);
```suggestion
        String winnersPrintMessage = String.format(PrintMessage.WINNER.getMessage(), winnersName);
```

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/view/OutputView.java
> +        }
예외 발생 시점에 바로 잡아주기 👍

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/model/MoveStatus.java
> +    STOP;
고생하셨어요 👍

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/view/OutputView.java
> +        return forwardString.repeat((int) forwardStatusCount);
```suggestion
    private String concatenateMoveStatuses(List<MoveStatus> moveStatuses) {
        int forwardStatusCount = (int) moveStatuses.stream().filter(status -> status.equals(MoveStatus.FORWARD)).count();
        String forwardString = "-";
        return forwardString.repeat(forwardStatusCount);
```
사용하는 값을 의도한 형태로 최대한 빨리 바꿔주면 나중에 실수할 확률이 줄어들더라구요
예외를 웬만하면 터지는 곳에서 바로 잡아주는 이유와 비슷한 것 같아요

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/model/Car.java
> +    }
이건 정적 팩토리 메서드라고도 볼 수 있겠네요!
생성자 근처에 두면 찾기 더 쉬울 것 같아요

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/controller/RacingCarController.java
> +        return game.findWinners();
저는 `game` 에서 가져온다면 RacingGameController 입장에선 변수를 그대로 가져오는게 아니라고 생각했어요
켬미의 기준 정말 좋다고 생각해요! 꼭 바꿀 필요 없어요!!

2024-02-19 16:23 UTC, pkeugine commented on src/test/java/model/CarTest.java
> +    return car;
함수도 좋죠! 테스트 픽스쳐를 관리하는 방법은 여러가지가 있는데, 그걸 상황에 맞게 쓰는게 제일 좋을 것 같네요
이전 대화 요약:
* 메서드가 많아지면 관리하기 힘들어질 수 있다
* 예외 상황, 검증 상황에서 사용하지 않더라도 보편적인 픽스쳐는 한 곳에서 공통으로 관리하는게 편할 때가 있다 (피케이 의견)

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/Main.java
> +        }
글이 잘 안 읽힐 거 같아서 걱정했는데 잘 전달되어 다행입니다 :)

2024-02-19 16:23 UTC, pkeugine commented on src/main/java/model/MoveStatus.java
> +    STOP("");
정확하게 잘 이해하셨어요!!

2024-02-19 16:34 UTC, pkeugine requested changes
고생 많았어요 켬미 👍 👍 👍 
step 2 에서 프로젝트 구조가 한 번 크게 바뀌었는데 끝까지 정말 잘 만들어주셨네요!
이번에 제가 남긴 리뷰는 정말 사소한 것들인데요, 5분...? 이면 반영하실 수 있을거에요
켬미의 의견에 따라 반영하지 않아도 되는 것도 있구요

금방 하실거에요! 수정하시고 다시 리뷰 요청 주세요 :)

2024-02-20 00:36 UTC, kyum-q commented on src/main/java/model/Car.java
> -  }
커밋할 때 도메인 단위로 하려고 하다보니 해당 부분을 놓쳤던 것 같네요 ! 
참고하겠습니다 ~!

2024-02-20 00:44 UTC, kyum-q commented on src/main/java/model/Car.java
> +    }
해당 메소드를 어디다 둘까 고민을 했었는데..! 피케이 의견처럼 생성자 근처가 가장 적절할 것 같네요 ~!

2024-02-20 00:50 UTC, kyum-q commented on src/main/java/model/Game.java
> +        }
이런 기능이 있는지 몰랐어요 !
스스로 테스트 코드를 최대한 만들어보고 필요에 따라 활용해 보도록 할게요 ! 좋은 꿀팁 감사합니다😊

2024-02-20 01:31 UTC, pkeugine approved these changes
이번 미션 고생하셨어요 켬미!
다음 미션도 파이팅입니다 🙂

2024-02-20 01:31 UTC, merged