[2단계 - 자동차 경주 리팩토링] 켈리(양성욱) 미션 제출합니다.
woowacourse/java-racingcar pull request #770
Opened 2024-02-18 12:41 UTC by kelly6bf

안녕하세요 현구막! 수정할 부분이 많이 없어서 빠르게 수정하고 요청 드립니다! 사실 제가 현구막이 주신 피드백을 제대로 이해하고 반영한건지 걱정이 많지만.. 시작이 반이니 제가 나름대로 이해한 방식을 설명해보겠습니다!

1. "RacingCar가 Cars에서만 쓰이고 있는데..."

처음 들었던 생각은 "RacingCar"를 Cars 내부에 연관관계로 설정하는 방식으로 수정해야겠다고 생각했어요. Cars말고는 해당 클래스를 사용하는 객체가 없으니 Cars의 책임을 수행하는 연관 객체로 설정하면 좋겠다는 생각으로 코드를 수정하려고 했어요. 하지만 "테스트 코드의 위치.."라는 문장을 듣고 제가 이해를 잘못한거가 싶어 다시금 고민하면서 다음 새로운 의견이 떠올랐어요.

[RacingRule 객체의 책임을 Cars로 위임]
현재 승자를 가리는 작업이 크게 복잡하지 않고, 현재 프로그램에서는 추가적인 규칙이 붙거나 다른 객체가 이걸 공유하는 여지가 없다고 생각해서 아예 Cars가 RacingRule의 역할도 가져가자는 생각을 하고 코드를 수정했어요. 하지만 이렇게 하니 Cars 내부에 Car객체를 임의적으로 수정할 방법이 없다보니 원하는 테스트를 수행하지 못하는 문제가 생겼어요. (우승자를 임의로 정하는 테스트)

결국 고민하다 처음 생각했던 Cars에 연관 관계로 설정하는 방식으로 코드를 수정했어요. 현구막은 어떤 의도를 주신건지 궁금합니다!

2. AppConfig
이부분은 저녁을 먹으면서도.. 커피를 사면서도.. 엘리베이터를 타면서도 고민했지만 "Controller가 계속 재할당 될 필요가 있을까..?" 라는 현구막의 질문을 잘 이해하지 못했어요.. 아무래도 제 식견의 한계인거 같습니다... 😢 혹시나 이 질문에 대한 답을 구하기 위해서 검색해보면 좋은 키워드가 있는지 힌트를 요청드리고 싶어요..!!

주말까지 꼼꼼하게 코드리뷰 해주셔서 너무 감사합니다 현구막!!

2024-02-19 11:57 UTC, Hyeon9mak requested changes
안녕하세요 켈리~ 이전 단계에서 이미 mvc 패턴 완성도가 높았기 때문에 큰 코드 변화가 없었네요!

`RacingCarController` 인스턴스에 대해서는 제가 잘못된 코멘트를 남겨드린 것 같아요....!
이전 단계에서 "애플리케이션이 실행될 때마다 `AppConfig#config` 가 수행되면서 `RacingCarController` 인스턴스가 매번 불필요하게 생성되는거 아닐까~?" 라고 생각하고 코멘트를 드렸는데요,
켈리가 남겨주신 질문을 곱씹으며 다시 생각해보니 어차피 로컬에서 애플리케이션이 여러번 실행될 수가 없으므로 아무런 차이가 없겠다고 느껴졌어요. 🤔 
괜한 이야기로 혼란을 드려서 죄송해요 🙏 

간단한 코멘트와 함께 Request changes 를 남길게요~
궁금하신 점 있다면 추가로 질문 주세요!
별도로 질문이 없으시다면 다음 요청에 approve 하도록 하겠습니다!

2024-02-19 11:57 UTC, Hyeon9mak commented on src/main/java/domain/car/Cars.java
> +    public static Cars of(List<String> carNames, RacingRule racingRule) {
다소 어렵게 말씀드렸던거 같은데, 의도를 잘 파악해주셨군요 😄 👍

2024-02-19 11:57 UTC, Hyeon9mak commented on src/main/java/domain/car/Cars.java
> +    public static Cars of(List<String> carNames, RacingRule racingRule) {
(굉장히 사소하지만) 현재 `RacingRule` 이 다른 인스턴스로 교체될 일이 없으므로, 생성자로 주입 받지 않고 자체적으로 생성하는 방법도 있겠네요!

> 하지만 이렇게 하니 Cars 내부에 Car객체를 임의적으로 수정할 방법이 없다보니 원하는 테스트를 수행하지 못하는 문제가 생겼어요.

`Cars` 의 생성자를 public 으로 개방하면 테스트 코드 작성이 한결 편해지지 않을까요?
`CarsTest` 에서 우승자를 구하는 로직을 테스트하는게 자연스러워질거 같아요.

2024-02-20 01:55 UTC, kelly6bf commented on src/main/java/domain/car/Cars.java
> +    public static Cars of(List<String> carNames, RacingRule racingRule) {
동의합니다! 다만 테스트 관련해서는 약간의 질문이 있습니다..! 밑에 남기겠습니다!

2024-02-20 02:04 UTC, kelly6bf commented
안녕하세요 현구막! 지금 작성하는게 마지막 질문입니다!

적어주신 커멘트 중 "RacingRule을 Cars가 자체적으로"생성에는 지극히 동의합니다! 다만 테스트를 편하게 하기 위해서 생성자를 public으로 여는것에 대해 큰 문제가 발생하지는 않을지 질문드려보고 싶어요! 마음에 걸리는 부분은 아래와 같습니다.

1. 테스트 코드에만 사용하는 로직(테스트만을 위한 접근 제한자 변경)을 작성해도 괜찮을까?
2. 생성자는 따로 자동차 이름을 검증하는 로직이 없는데 만약 생성자를 public으로 열면 협업하는 다른 사람들이 잘못 사용하지 않을까 싶은 고민이 있습니다.
-> 물론 이부분은 패키지 구조를 엄격히 나누고 생성자를 protected 혹은 default로 설정하는 방법도 있을거 같아요!!

일주일간 리뷰해주셔서 정말 감사합니다! 고생 많으셨어요!!!

2024-02-20 15:22 UTC, Hyeon9mak approved these changes
안녕하세요 켈리~ 어느덧 첫번째 미션 마지막에 다다르셨네요~

#### 테스트 코드에만 사용되는 생성자

생성자를 일반 메서드와 다르게 이해하고 사용하면 어떨까요?
생성자는 말 그대로 해당 인스턴스를 생성하고 할당하는 것에 집중할 뿐, 
비즈니스 로직을 수행하는 것과는 완전히 별개의 코드라고 생각해요.

대부분 객체를 설계하고 생성할 땐, 해당 객체의 행동(메서드)을 기준으로 삼을거에요.
생성자 내부에서 호출되는 검증 로직들도, 따지고 보면 모두 **메서드**로 분리해서 관리할 수 있을거 같아요.
(실제로 켈리도 그렇게 만들어주신거 같구요 😉)

#### 팩터리 메서드 속 검증로직

팩터리 메서드에서 수행하는 검증로직을 생성자 내부로 이동시키면 문제가 모두 해결될 것 같아보여요! 😮 

```java
    public Cars(List<Car> cars) {
        this.cars = cars;
        List<String> carNames = mapToCarNames();
        validateCarNamesCount(carNames);
        validateDuplicatedCarNames(carNames);
    }

    private List<String> mapToCarNames() {
        return this.cars.stream()
                .map(Car::getName)
                .toList();
    }

    private void validateCarNamesCount(List<String> carNames) {
        if (carNames.size() < 2) {
            throw new IllegalArgumentException("자동차 이름의 개수는 2이상이여야 합니다.");
        }
    }

    private void validateDuplicatedCarNames(List<String> carNames) {
        int distinctSize = new HashSet<>(carNames).size();
        if (carNames.size() != distinctSize) {
            throw new IllegalArgumentException("중복된 자동차 이름을 허용하지 않습니다.");
        }
    }

    public static Cars of(List<String> carNames) {
        List<Car> cars = initCars(carNames);
        return new Cars(cars);
    }
```

이 외에도 좋은 방법은 많이 있을거 같네요!

요구사항이 모두 충족되었기 때문에 approve 하도록 하겠습니다.
추가로 궁금하신 점 있다면 언제든지 DM 주세요.
다음 미션도 화이팅입니다!

2024-02-20 15:22 UTC, merged