Step2
woowacourse/java-racingcar pull request #772
Opened 2024-02-18 13:05 UTC by koust6u

안녕하세요. 제이! 프람입니다.

지난 1단계 미션에 이어 2단계 미션도 진행해보았습니다.

1단계 미션을 진행함에 있어 기본적으로 mvc패턴을 적용해보았기 때문에 
피드백을 주신을 부분을 바탕으로 리팩토링을 진행해보았습니다.

감사합니다😀

2024-02-19 00:47 UTC, JunHoPark93 requested changes
안녕하세요 프람~
2단계 구현하느라 수고많으셨어요.
컨벤션 관련 내용 위주로 한번 더 점검 부탁드릴게요.
수정 후 다시 요청주시면 확인 후 merge할게요~

2024-02-19 00:47 UTC, JunHoPark93 commented on src/main/java/racingcar/controller/RacingGameController.java
> +        while (racingGame.isRoundInProgress()) {
부정문 대신 명시적인 이름으로 바꿔보셨네요~ 👍🏼

2024-02-19 00:47 UTC, JunHoPark93 commented on src/test/java/racingcar/model/CarsTest.java
> +        Assertions.assertThat(cars.getMaxProgress()).isEqualTo(2);
컨벤션 확인해주세요~

2024-02-19 00:47 UTC, JunHoPark93 commented on src/test/java/racingcar/model/CarsTest.java
> +        Assertions.assertThat(cars.getMaxProgress()).isEqualTo(2);
이 위에 클래스들에서도 주석 확인해주세요
사소한거라고 생각하실수있어도 이번미션에서 경험해야할 중요한 부분 중 하나입니다!

2024-02-19 00:47 UTC, JunHoPark93 commented on src/main/java/racingcar/domain/service/RacingGame.java
> +        this.moveCount--;
명시적인 메서드로 잘 분리해보셨네요~
요 부분도 개행 확인해주세요

2024-02-19 00:47 UTC, JunHoPark93 commented on src/main/java/racingcar/domain/model/Car.java
>      private static final int MAX_NAME_LENGTH = 5;
어떤 이유로 개행이 사라졌을까요?

2024-02-19 00:47 UTC, JunHoPark93 commented on src/main/java/racingcar/domain/rules/DefaultCarMoveRule.java
> +import racingcar.domain.rules.CarMoveRule;
미사용 import는 제거해주세요~

2024-02-19 00:47 UTC, JunHoPark93 commented on src/main/java/racingcar/domain/service/RacingGame.java
> +                .filter(car -> car.isEqualToProgress(maxProgress))
메서드로 잘 분리해보셨네요~ 👍🏼

2024-02-19 01:05 UTC, koust6u commented on src/main/java/racingcar/domain/model/Car.java
>      private static final int MAX_NAME_LENGTH = 5;
전체적으로 컨벤션에 대한 숙지가 미숙했고 
꼼꼼한 확인을 못했던 것같습니다ㅠㅠ

2024-02-20 01:02 UTC, koust6u commented on src/test/java/racingcar/model/CarsTest.java
> +        Assertions.assertThat(cars.getMaxProgress()).isEqualTo(2);
컨벤션에 대해 더욱 신경쓰겠습니다!

2024-02-20 13:35 UTC, JunHoPark93 approved these changes
안녕하세요 프람~
리뷰 반영하느라 수고 많으셨습니다.
첫번째 미션에서 지켜야 할 내용들이 다음 미션들에서는 디폴트로 적용될거에요.
다음 미션도 화이팅입니다!

2024-02-20 13:35 UTC, merged