[2단계 - 자동차 경주 구현] 시소(신지) 미션 제출합니다.
woowacourse/java-racingcar pull request #783
Opened 2024-02-18 15:41 UTC by shin-jisong

안녕하세요! step1에 이어 step2를 진행하며 코드를 더 발전시켜 보았습니다.

**step2에서 변경된 것들은 다음과 같습니다**
- MVC 패턴 도입
- Exception enum으로 처리
- 각종 리팩토링

**지난 리뷰에서 주셨던 질의들**
- 상수에 관련하여
name.length() > 5에서 5라는 의미가 명확하고 반복되지 않기 때문에 따로 상수화하지 않았다라고 답변을 드린 후
추가적으로 고민을 진행해 보았습니다. 
만약, 요구사항이 변화하고 해당 코드를 변경시켜야 될 상황을 가정하였을 때 해당 함수를 찾아 수정하는 것보다 상수를 관리하여 상단에서 변경시키는 것이 적절하다고 판단하였고, 해당 변수의 재사용성을 고려하여 상수화하였습니다.
-   getter 사용을 지양해야 하는 이유
각 객체는 스스로가 가진 정보를 외부에 공개하지 않아야 하며 캡슐화가 필요합니다! 즉, 다른 객체에서는 해당 객체가 무엇을 가지고 있는지 알지 못하더라도 메시지를 주고받으며 해당 정보를 공유할 수 있어야 객체 지향이 추구하는 바를 이룰 수 있어 getter의 사용을 지양하는 것이 좋다고 생각합니다.
- getter 이후 값 변화가 생긴다면 문제점
getter는 단순 값 참조만을 해야 하는데 값을 변화하게 된다면 의도치 않은 동작이며 일부 객체의 경우 변화하지 말아야 할 값이 변화하여 로직에 큰 문제를 일으킬 수 있다고 생각합니다!

2024-02-19 00:09 UTC, Gomding requested changes
안녕하세요 시소!
2단계에서 페키지를 잘 나눠주셨네요 😃 

몇가지 코멘트 남겼으니 확인부탁드려요 🙏 
궁금한 점 있으면 언제든 DM이나 PR 코멘트 남겨주세요!

2024-02-19 00:09 UTC, Gomding commented on src/main/java/exception/CarLocationException.java
> +    NOT_NEGATIVE("[ERROR] 위치에는 음수가 입력될 수 없습니다.");
예외 메시지에 대해 enum으로 분리해주신 의도가 궁금해요!

2024-02-19 00:09 UTC, Gomding commented on README.md
> +- [x] 주어진 횟수동안 n대의 자동차는 전진 또는 멈출 수 있다.
체크박스 반영해주셨군요! 💯 💯 💯

2024-02-19 00:09 UTC, Gomding commented on src/main/java/model/Cars.java
> +                .filter(car -> car.getCarLocation() == getMaxLocation())
filter 에서 모든 요소에 대해 getMaxLocation 메서드를 실행해야 할까요! 😃

2024-02-19 00:09 UTC, Gomding commented on src/main/java/controller/RacingGame.java
> +            outputView.printCurrentRace(cars);
매 경기마다 outputView에게 경기결과 출력을 요청하고 있는데요!

1. 레이스 진행 후 결과만 기록해뒀다가
2. 경기 승자를 출력할 때 경기 결과를 넘겨주고
3. 경기 결과들도 출력해달라고 요청하면 어떨까요!

2024-02-19 00:09 UTC, Gomding commented on src/main/java/controller/RacingGame.java
> +        return new Cars(carList);
Cars 를 생성할 때 carNames 를 넘겨보는것을 시소는 어떻게 생각하시나요?

```java
Cars.from(carNames.split(SEPARATOR));
```

2024-02-19 00:09 UTC, Gomding commented on src/main/java/view/InputView.java
> +package view;
패키지를 깔끔하게 분리해주셨네요 💯 💯 💯

2024-02-19 00:09 UTC, Gomding commented on src/main/java/exception/CarLocationException.java
> +public enum CarLocationException {
사용되는 부분에 맞게 패키지를 구성해주면 어떨까요!

ex)
InputException -> package view.exception

2024-02-19 00:09 UTC, Gomding commented on src/main/java/utils/NumberGenerator.java
> +public interface NumberGenerator {
interface 를 사용하는곳이 없어보이네요!
어떤 의도로 만들어주신 걸까요? 🤔

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/controller/RacingGame.java
> +        return new Cars(carList);
그렇게 코드를 짜는 것이 책임을 더 적절하게 나누는 방안인 것 같습니다!
car 또한 이름으로 생성하기 때문에 코드의 통일성에 더 적합한 방안인 것 같아 반영하도록 하겠습니다.

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/controller/RacingGame.java
> +            outputView.printCurrentRace(cars);
string buffer를 사용하여 속도를 더 빠르게 개선하기 위해 추천하시는 방안일까요?
아니면 다른 사유가 있는 것인지 궁금합니다!

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/exception/CarLocationException.java
> +public enum CarLocationException {
해당 부분 반영하도록 하겠습니다!

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/exception/CarLocationException.java
> +    NOT_NEGATIVE("[ERROR] 위치에는 음수가 입력될 수 없습니다.");
예외 처리 메시지를 효과적으로 관리할 수 있도록 분리하였습니다!

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/model/Cars.java
> +                .filter(car -> car.getCarLocation() == getMaxLocation())
더 나은 방향을 고려해서 수정해 보도록 하겠습니다!

2024-02-19 14:42 UTC, shin-jisong commented on src/main/java/utils/NumberGenerator.java
> +public interface NumberGenerator {
기존 함수는 테스트를 위해 protected로 작성하였는데 해당 방안으로 작성하면 기존 비즈니스 코드를 변형하지 않고도 테스트를 진행할 수 있어서 해당 방식으로 작성하였습니다.
테스트 코드에 반영하도록 하겠습니다!

2024-02-20 11:11 UTC, Gomding commented on src/main/java/controller/RacingGame.java
> +            outputView.printCurrentRace(cars);
경주 회차마다 매번 OutputView와 소통해야하는 과정이 비효율적이라고 느껴져서요! 😄 

OutputView와 한 번만 소통하고 결과를 출력해줄 수 있는 방법도 있지않을까요?

2024-02-20 12:21 UTC, Gomding approved these changes
안녕하세요 시소!
패키지 잘 나눠주셔서 이번 미션은 이만 merge 하겠습니다 🙏 
몇가지 코멘트 남겼으니 확인부탁드려요 😃 

다음 미션도 화이팅입니다 🔥

2024-02-20 12:21 UTC, Gomding commented on src/main/java/utils/moveNumberGenerator.java
> +public class moveNumberGenerator implements NumberGenerator {
클래스 이름 컨벤션에 맞춰서 수정 부탁드려요! 😃

2024-02-20 12:21 UTC, Gomding commented on src/main/java/utils/Randoms.java
> +public class Randoms implements NumberGenerator {
Randoms 라는 이름이 클래스의 역할을 잘 표현해주고 있을까요? 🤔 

자동차 경주와 관련해서 이름을 지어보는것도 좋겠어요

+) NumberGenerator 이름도 바꿔보면 어떨까요
당장 떠오르는건 자동차에는 연료가 필요한데, 연료 생성기? 같은 개념을 생각해볼 수 있겠네요 😄 

++) NumberGenerator는 정말 유틸 객체일지도 고민해보아요!
자동차 경주의 규칙을 구현한 클래스인데 domain은 객체로는 어떻게 생각하시나요? 😃

2024-02-20 12:21 UTC, Gomding commented on src/main/java/utils/moveNumberGenerator.java
> +package utils;
테스트를 위한 클래스는 어디에 위치하면 좋을지 고민해보아요!

일단 실제 코드에서 사용할 건 아니니 main 하위 패키지는 피해야 되겠죠..! 😄

2024-02-20 12:21 UTC, Gomding commented on src/main/java/utils/moveNumberGenerator.java
> +            randomNumbers.add(4);
조금 더 동적으로 만들어보면 어떨까요!

TestNumberGenerator가 numbers 필드를 가지고 있다면 테스트에서 다양하게 활용할 수 있지 않을까요?! 😃 

```java
class TestNumberGenerator implements NumberGenerator {
    private final List<Integer> numbers;

    public TestNumberGenerator(List<Integer> numbers) {
        this.numbers = numbers;
    }
}
```

2024-02-20 12:21 UTC, Gomding commented on src/main/java/exception/view/InputException.java
> +package exception.view;
해당 패키지 구성도 괜찮다고 생각하지만..! 👀 

사용처인 클래스와 가까운곳에 위치에 응집시키면 다른 개발자가 봤을 때 연관성을 바로 눈치챌 수 있지 않을까요?
```
model
  ㄴ exception
       ㄴ CarLocationException.java
       ㄴ CarNameException.java
view
 ㄴ exception
       ㄴ InputException.java
```

2024-02-20 12:21 UTC, Gomding commented on src/test/java/CarNameTest.java
> +    @NullAndEmptySource
`@NullAndEmptySource` 사용 👍 
앞으로 Junit 과 친해질 기회가 많을거에요 😃

2024-02-20 12:21 UTC, Gomding commented on src/main/java/model/CarName.java
> +        return name == null || name.isBlank() || name.length() > MAX_NAME_LENGTH;
적절한 이름의 상수로 변경 💯

2024-02-20 12:22 UTC, merged