[자동차 경주 게임 - 2단계] 러쉬 미션 제출합니다.
woowacourse/java-racingcar pull request #806
Opened 2024-02-19 02:13 UTC by xogns1514

### 미션 목표

- 도메인은 도메인 관련 로직에 대해서만 일하게 하자
- MVC 패턴 역할 분리
- 랜덤값 생성으로 인한, 테스트 코드 하기 어려운 코드 리팩터링
- 피드백 반영

### 미션을 수행하며 궁금한점

- 현재 RacingGame 클래스를 MVC패턴의 컨트롤러를 맞고 있는지 궁금합니다.
    - controller는 모델에 명령을 보내어, 모델의 상태를 변경하는 역할로 알고 있습니다. 현재 RacingGame이 컨트롤러 역할을 하고 있는데, `makeCars` 메서드에서 생성자와 같은 역할을 해 MVC 패턴을 위반하고 있다고 생각했습니다.
- 테스트 코드를 위한 생성자를 만들어도 괜찮은가?
    - 위 질문 문제를 해결하기 위해, makeCars의 역할을 Cars에 만들어, List<String>을 인자로 받는 생성자로 수정하려고 했습니다. 하지만 test 코드 상에서는 List<Car>를 인자로 받아 Cars를 생성하기 때문에 많은 로직을 수정해야 할 것 같아 그대로 두었습니다. 이때 test 코드에서 List<Car> 생성자를 사용하기 위해, Cars에 해당 생성자를 유지해도 되는지 궁금합니다
    - 테스트 픽스처를 위해 **`Car(String name, int position)`** 라는 생성자를 두어도 되는 것인지 궁금합니다.

2024-02-20 14:10 UTC, choijy1705 requested changes
러쉬! 제가 리뷰요청을 놓쳐버렸네요!
늦어서 죄송합니다😭
질문에 대한 답변과 몇가지 코멘트 남겼습니다!

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/controller/RacingGame.java
> +    private final RandomNumberGenerator randomNumberGenerator = new RandomNumberGenerator();
필요한 시점에 생성하는게 좋지 않을까요??

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/domain/Car.java
> +    public boolean equals(final Object object) {
이건 의도하고 붙이신건가요?

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/controller/RacingGame.java
> +    }
저는 mvc 패턴을 잘 지켰다고 생각합니다!
모델에 대한 정보는 컨트롤러가 알 수 있고
직접적인 생성은 Cars 의 생성자를 통해서 생성하구 있구요!!

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/domain/Car.java
>      }
테스트를 위한 생성자에 대한 질문을 주셨는데
테스트를 위한 생성자는 안보이네요!
테스트를 위한 코드는 최대한 생성하지 않는것이 좋다고 생각합니다
지금 생각나는 이유는 코드 변경이 있어서 실패해야하지만 테스트 만을 위한 코드로 테스트가 되구 있어서 알아차리지 못할 가능성이 있을것 같네요
여러가지 문제들이 있을것 같네요!

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +        return String.join(" : ", car.getCarName(), DASH.repeat(car.getDistance()));
": "얘도 상수로 처리하면 어떨까요?

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/util/NumberGenerator.java
> +public interface NumberGenerator {
인터페이스가 과연 지금 시점에 생성하는게 좋을까요??

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/domain/Cars.java
>      }
우선 변경하려고 했던 코드를 코멘트나 혹은 반영해보시면 피드백드리기 좋을것 같아요!

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/domain/Cars.java
> +    public List<Car> getWinners(final int maxDistance) {
List<String> 혹은 String으로 반환하는게 더 좋지 않을까요??

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +    public static void printWinners(final List<Car> cars) {
view에 car라는 모델이 넘어오네요
이런 부분은 mvc를 제대로 지키지 않았다고 볼 수 있을것 같네요!

2024-02-20 14:10 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +    private static String generateResult(final Car car) {
여기두요!

2024-02-23 00:51 UTC, xogns1514 commented on src/main/java/controller/RacingGame.java
> +    private final RandomNumberGenerator randomNumberGenerator = new RandomNumberGenerator();
한번만 쓰이니 필요한 시점에 생성하면 되겠네요!

2024-02-23 00:57 UTC, xogns1514 commented on src/main/java/domain/Car.java
> +    public boolean equals(final Object object) {
넵! object가 메서드 내부에서 재할당될 일이 없다고 생각하여 붙였습니다.

2024-02-23 01:51 UTC, xogns1514 commented on src/main/java/domain/Cars.java
> +    public List<Car> getWinners(final int maxDistance) {
처음에 String으로 우승자 이름들을 모두 붙여 반환했는데 이것은 view의 책임이라고 생각하여, 현재 List<Car> 형태로 반환하고 있습니다! 혹시 List 혹은 String으로 반환한다는 것이 어떤 의미인가요?

2024-02-23 01:56 UTC, xogns1514 commented on src/main/java/domain/Cars.java
>      }
`public List<Car> getWinners() {
        List<Car> winnerCars = new ArrayList<>();
        int maxDistance = 0;
        
        for (Car car : racingCars) {
            maxDistance = getMaxDistance(car, maxDistance, winnerCars);
        }
        return winnerCars;
    }

    private static int getMaxDistance(Car car, int maxDistance, List<Car> winnerCars) {
        if (car.getDistance() > maxDistance) {
            winnerCars.clear();
            winnerCars.add(car);
            maxDistance = car.getDistance();
        }

        if (car.getDistance() == maxDistance) {
            winnerCars.add(car);
        }
        return maxDistance;
    }`
    
    이런 형식으로 한번 순회하면서 우승자 차들을 List<Car>를 반환하는 방식을 생각했습니다.

2024-02-23 02:02 UTC, xogns1514 commented on src/main/java/util/NumberGenerator.java
> +public interface NumberGenerator {
단위 테스트를 위해 필요하다고 생각합니다! 현재 RandomGenerator로 인해서 하나의 라운드를 진행하는 메서드를 테스트하기 어렵습니다. 이 메서드를 테스트하기 위해서, 인터페이스를 만들고 원하는 구현체를 각각 주입해주었습니다.

2024-02-23 02:42 UTC, xogns1514 commented on src/main/java/view/OutputView.java
> +    public static void printWinners(final List<Car> cars) {
view가 모델을 인자로 받는거 자체가 mvc 위반인건가요?? 2단계 - 자동차 경주 리팩터링 내용중 **view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만** 이라는 점을 참고해서, view가 모델을 받을 수 있게 구현했습니다! Controller가 view에게 전달해주어도 mvc위반인것인지 궁금합니다!

2024-02-23 08:24 UTC, choijy1705 approved these changes
러쉬 다음 미션 진행하신다고 정신없으셨을텐데
고생하셨습니다👍
이번 단계는 여기서 머지할께요
몇가지 코멘트 남겼으니 확인해주세요! 
궁금한점은 편하게 DM주세요!

2024-02-23 08:24 UTC, choijy1705 commented on src/main/java/domain/Cars.java
> +    public List<Car> getWinners(final int maxDistance) {
winners는 Car가 아닌 name에 가까운것 같아서요
메서드를 사용하는 다른 사람이 오해하기 쉬울것 같아요
getWinCars? 혹은 getWinners라면 List<String>으로 이름 list가 반환되면 좋겠네요

2024-02-23 08:24 UTC, choijy1705 commented on src/main/java/domain/Cars.java
>      }
좋은것 같아요!👍
다만 indent 규약에 집중하다보니 가독성이 떨어지는 메서드 분리가 된것 같네요
굳이 메서드 로 분리할 필요가 있을지 생각해보시면 좋을것 같아요!
트레이드 오프는 언제나 있으니 거기서 잘 판단하는 연습을 해보면 좋을것 같습니다

2024-02-23 08:24 UTC, choijy1705 commented on src/main/java/util/NumberGenerator.java
> +public interface NumberGenerator {
테스트를 위한 코드가 
과연 코드가 변경되었을때
해당 테스트를 신뢰할 수 있을지 고민해보면 좋겠네요🙏

2024-02-23 08:24 UTC, choijy1705 commented on src/main/java/view/OutputView.java
> +    public static void printWinners(final List<Car> cars) {
도메인 그대로 view에 넘길때 문제점을 생각해보면 좋을것 같아요
예를들어 user라는 객체가 있고 id와 비밀번호가 있다고하면
user를 그대로 view에 넘기면 비밀번호가 노출되는 문제가 있을 수 있을것 같아요. 그럼 웹에서는 개발자도구로 비밀번호를 볼 수 있을것 같네요
위 예시를 참고해서 도메인자체를 그대로 넘길때 생길수 있는 문제점을 고민해보면 좋을것 같네요!

2024-02-23 08:24 UTC, merged

2024-02-24 08:49 UTC, xogns1514 commented on src/main/java/domain/Cars.java
> +    public List<Car> getWinners(final int maxDistance) {
아 현재 메서드가 하는 일이, 메서드명과 일치하지 않는 문제가 있었군요! List<Car>를 반환한다면 getWinCars라는 메서드명이 더 잘 어울리는 것 같습니다.

2024-02-24 08:53 UTC, xogns1514 commented on src/main/java/domain/Cars.java
>      }
인덴트를 맞추기 위해 억지로 메서드를 분리했는데, 분리하면서도 가독성이 떨어진다고 느꼈습니다..메서드 분리시 가독성과의 트레이드 오프를 잘 따져봐야겠네요🧐

2024-02-24 08:57 UTC, xogns1514 commented on src/main/java/view/OutputView.java
> +    public static void printWinners(final List<Car> cars) {
도메인 자체가 view에 넘어올 경우 민감한 정보나, 비즈니스 로직이 노출 될 위험의 문제가 있겠군요..! 이것을 방지하기 위해 DTO를 통해 정보를 view에 전달하는 방법을 이용할 수 있을 것 같습니다

2024-02-24 09:07 UTC, xogns1514 commented on src/main/java/util/NumberGenerator.java
> +public interface NumberGenerator {
만약 도메인의 비즈니스 로직이 변경될 경우, 해당 코드도 변경되어야 한다는 문제점이 있을 것 같습니다. 이번 미션에서는 자동차 전진 조건이 변경된다면, MovableNumberGenerator를 이용해 작성된 테스트 코드들은 신뢰할 수 없겠네요. 테스트를 위해 iterface를 이용했지만, 다른 방법을 좀 더 고민해보겠습니다🧐